python/typeshed

README.md

Turns out, I created a pull request to myself by accident...

Fix link to PEP 484

---

stdlib/2.7/json.pyi
stdlib/3/json.pyi

Add keyword args to stdlib's json.pyi

---

stdlib/2.7/__builtin__.pyi
stdlib/3/builtins.pyi

Remove invalid Python 3 syntax

---

stdlib/3.4/asyncio/__init__.pyi
stdlib/3.4/asyncio/coroutines.pyi
stdlib/3.4/asyncio/events.pyi
stdlib/3.4/asyncio/futures.pyi
stdlib/3.4/asyncio/protocols.pyi
stdlib/3.4/asyncio/queues.pyi
stdlib/3.4/asyncio/streams.pyi
stdlib/3.4/asyncio/subprocess.pyi
stdlib/3.4/asyncio/tasks.pyi
stdlib/3.4/asyncio/transports.pyi

mypy ignores the contents of `__all__`, so they're not needed.

Remove contents of problematic asyncio __all__s

---

stdlib/3/abc.pyi

In https://github.com/python/mypy/issues/1459, this PR was suggested to add the method to ABCMeta.

Add abc.ABCMeta.register method

---

stdlib/2and3/warnings.pyi

Improve `warnings` a bit more, by being more precise on accepted types (such as adding `Optional` where `None` is handled).
Also, add types to `warnings.catch_warnings`.

Add somes types to warnings

---

tests/mypy_test.py

Add --strict-optional flag to mypy

---

tests/pytype_blacklist.txt

Remove files that now work with pytype from blacklist.

trim blacklist

---

tests/pytype_blacklist.txt

Broke travis with recent pytype push

Update pytype blacklist.

---

stdlib/2.7/sys.pyi

fix unprecise type in sys.exc_info in py2

---

stdlib/2and3/rlcompleter.pyi

https://docs.python.org/3/library/rlcompleter.html

add rlcompleter

---

stdlib/2.7/typing.pyi
stdlib/3/typing.pyi

Add type stub for typing.get_type_hints

---

tests/mypy_test.py

Add mypy blacklist, same syntax as pytype blacklist.

---

third_party/2.7/requests/sessions.pyi
third_party/3/requests/sessions.pyi

Once this is accepted I'd like to propegate these signatures to all of the
convience methods people actually use like get, post, put, etc...

Add more specific types for requests.sessions.Session

---

tests/pytype_blacklist.txt

Remove argparse, tarfile and logging/handlers.

adjust pytype blacklist

---

stdlib/2and3/locale.pyi

Different fix for locale/str/__builtin__ issue

---

stdlib/2.7/calendar.pyi
stdlib/3/calendar.pyi

These are undocumented but enough people seem to use them that they
should be considered public

Add MONDAY, TUESDAY, ... constants to stdlib/calendar

---

stdlib/2.7/future_builtins.pyi

Add stub file for <https://docs.python.org/2/library/future_builtins.html>.

Add future_builtins stub file

---

stdlib/2.7/__builtin__.pyi
stdlib/3/builtins.pyi

Improve types of staticmethod and classmethod

---

stdlib/3/builtins.pyi

Addresses https://github.com/python/typeshed/issues/619

Added RecursionError to builtins for Python >= 3.5

---

stdlib/2.7/tempfile.pyi

Also add some of the private methods of tempfile.

Add more methods to return type of tempfile.TemporaryFile.

---

stdlib/3/resource.pyi

Just some output from stubgen.pyi

Added variable types for resources.pyi

---

stdlib/2and3/distutils/extension.pyi

And name+sources do not have defaults.

The distutils.Extension class does take positional args

---

stdlib/2/time.pyi

gmtime(None) works

---

stdlib/3/urllib/parse.pyi

Fix urllib.parse.urlencode signature

---

stdlib/3/collections/__init__.pyi
stdlib/3/collections/abc.pyi

Add missing imports from collections.abc

---

CONTRIBUTING.md

Also included a note about _Names.

Expand CONTRIBUTING.md with information about sys.version_info checks

---

stdlib/3/sys.pyi

Fixes https://github.com/python/typeshed/issues/856

Add 'sys.is_finalizing' function

---

stdlib/3/urllib/parse.pyi

Fixes https://github.com/python/typeshed/issues/873

Add quote_via argument to urlencode

---

stdlib/2/uuid.pyi

Adds all the properties and methods that were missing

Update python 2 UUID stubs

---

stdlib/3/typing.pyi

Add Collection to typing.pyi

---

stdlib/3/subprocess.pyi

Add 2 new keyword arguments to popen and run that were added in python 3.6

Add encoding and errors keyword arguments (new in 3.6)

---

stdlib/3/os/__init__.pyi

Add os.supports_* sets (new in 3.3)

---

stdlib/3.4/tracemalloc.pyi

This one was nice to write because its documentation actually has type annotations for a few functions (https://docs.python.org/3/library/tracemalloc.html#api).

Add tracemalloc

---

stdlib/3/builtins.pyi

See https://github.com/python/typing/issues/402#issuecomment-288200802.
Calling out @JelleZijlstra and @sproshev.

Make PathLike generic in AnyStr

---

stdlib/2and3/cgi.pyi

I should probably have set up flake8-pyi locally.

fix version check in cgi

---

stdlib/3/urllib/request.pyi

https://github.com/python/cpython/blob/ee51327a2329eb9c2bfbb6ea673cfab4299450b0/Lib/urllib/request.py#L900

HTTPPasswordMgrWithDefaultRealm inherits from HTTPPasswordMgr

---

stdlib/2/os/__init__.pyi
stdlib/3/os/__init__.pyi

Reverts python/typeshed#1103
See discussion in issue -- there are two separate problems in real-world code.

Revert "Make os.stat_result and friends NamedTuples"

---

stdlib/2and3/tarfile.pyi

https://docs.python.org/2/library/tarfile.html?highlight=compresslevel

Add `compresslevel` kwarg to tarfile

---

stdlib/3.4/asyncio/__init__.pyi
stdlib/3.4/asyncio/futures.pyi

Add stub for asyncio.wrap_future

---

.gitignore

Since it's now generated by mypy by default.

Add .mypy_cache/ to .gitignore

---

stdlib/2and3/pty.pyi

https://docs.python.org/3/library/pty.html

stub for pty

---

stdlib/3/subprocess.pyi

Based on https://docs.python.org/3.6/library/subprocess.html#subprocess.Popen.args

Add args attribute to subprocess.Popen

---

CONTRIBUTING.md

From https://github.com/python/typeshed/pull/1266#issuecomment-302916761.

Add to core dev guidelines

---

README.md

Add explanation on how to use typeshed with mypy etc.

---

.flake8
CONTRIBUTING.md

- Removes references to 'runtests.sh', as it has been removed
- Adds links from the contributing file to the readme - testing section
- Updates flake8 stats

Documentation updates for testing information

---

stdlib/2/_ast.pyi
stdlib/3/_ast.pyi

make _ast.identifier private

---

stdlib/2and3/logging/__init__.pyi
stdlib/2and3/logging/config.pyi
stdlib/2and3/logging/handlers.pyi

fixes to logging stubs

---

third_party/3.6/click/decorators.pyi

- Add context_settings for command
- Make callback Callable type accept some more types
To address Issue 1238

Tweak Click 6.6 Decorator Type Stubs

---

stdlib/3/functools.pyi

Plus other cleanup to the py3 functools stub

add functools.partialmethod

---

third_party/3.6/click/decorators.pyi

Finish the lines I missed before @ambv merged earlier today.

Fix missed callback arguments to Click Decorators

---

stdlib/2and3/__future__.pyi

We were missing the most important one.

complete __future__ stubs

---

stdlib/2and3/symtable.pyi

https://docs.python.org/3/library/symtable.html#symtable.symtable
and
https://docs.python.org/2/library/symtable.html#symtable.symtable

add symtable.symtable

---

stdlib/3/types.pyi

I made this Generic because conceptually it is, but other types in this module are not generic; I'm not sure why.

add types.AsyncGeneratorType

---

stdlib/3.4/asyncio/subprocess.pyi

asyncio.subprocess: fix type to include IO instead of just int and match Popen

---

tests/mypy_selftest.py

With the removal of lib-typing in mypy, we need to ensure that python2 has `typing` available.

fix mypy_selftest

---

stdlib/3/types.pyi

See https://github.com/python/mypy/pull/3484 for background.

Correct the type of MethodType.__func__.

---

stdlib/3/multiprocessing/managers.pyi

Added:
* start
* shutdown
* context manager methods

Adding some missing methods to multiprocessing.BaseManager

---

third_party/2and3/click/termui.pyi

My sed script was too naive. :-)

Remove double Optional[]

---

third_party/2and3/requests/packages/urllib3/util/connection.pyi

This is defined at https://github.com/requests/requests/blob/v2.14.2/requests/packages/urllib3/util/connection.py#L130

Add type stub for requests.packages.urllib3.util.connection.HAS_IPV6

---

stdlib/2and3/logging/__init__.pyi

logging: make Logger inherit from Filterer

---

stdlib/2and3/logging/handlers.pyi

Related issue: https://github.com/python/typeshed/issues/1497#issuecomment-317883223

fix the type definition of namer function

---

stdlib/3/resource.pyi

I copied the `_RUsage` from the Python 2 definitions

Improve resource stubs for py3

---

CONTRIBUTING.md

Ask contributors to better explain their changes and link to documentation and code. These things generally make pull requests easier to review.

add to CONTRIBUTING

---

stdlib/3/sys.pyi

- More precise types for trace and profile functions
- Remove redundant comments

sys: clean up

---

stdlib/3/configparser.pyi

RawConfigParser dict_type argument should be a Type

---

stdlib/3/re.pyi

(3.6+) Adds re.RegexFlag and use it.

---

stdlib/2and3/logging/__init__.pyi

- Missing attribute `StreamHandler.stream`
- Missing attribute `StreamHandler.terminator`

Corrections to logging.StreamHandler stubs (#1624)

---

stdlib/2and3/xml/sax/__init__.pyi

Fixes https://github.com/python/typeshed/issues/1655

Fix type of source for xml.sax.parse

---

stdlib/2and3/bz2.pyi

- change a default value to ...
- add some missing version checks
- add some missing arguments
See https://docs.python.org/3/library/bz2.html and https://docs.python.org/2/library/bz2.html.

fill out bz2 stub

---

stdlib/3/types.pyi

```
def foo():
pass
class A:
def foo(self):
pass
print(foo.__qualname__)
print(A.foo.__qualname__)
print(A().foo.__qualname__)
print(open.__name__)
print(open.__qualname__)
```

Add `__qualname__` to functions and methods

---

third_party/2/six/__init__.pyi
third_party/2and3/requests/__init__.pyi
third_party/2and3/yaml/__init__.pyi
third_party/3/six/__init__.pyi

I am fixing three cases here that bit me recently (probably due to changes in typeshed.)

Several packages always auto-import certain submodules on import

---

stdlib/3/curses/__init__.pyi

Added LINE and COL definitions to fix issue #1596  'curses: Module has no attribute "{LINES,COLS}"'
Fixes #1596

Update to /stdlib/3/curses/__init__.py

---

stdlib/3.4/enum.pyi

This is needed for python/mypy#4311, and is sound.

Avoid over-constraining self type of EnumMeta

---

CONTRIBUTING.md

Follow up on https://github.com/python/mypy/issues/4470
although maybe this should be more prominently displayed, because it seems to come up a lot?

add note about not squashing

---

third_party/2/fb303/FacebookService.pyi
third_party/2/scribe/scribe.pyi

Ignore thrift imports

---

stdlib/3/typing.pyi

It is very useful for doing introspection.
Fixes #1861

Add missing private field to NamedTuple

---

stdlib/2and3/__future__.pyi

[stdlib/2and3/__future__] Add PEP 563 `annotations`

---

stdlib/2and3/argparse.pyi

Changes based on https://github.com/python/cpython/blob/master/Lib/argparse.py.

Add missing attributes, fix some parameter types in argparse.Action.

---

third_party/2and3/click/core.pyi
third_party/2and3/click/decorators.pyi
third_party/2and3/click/termui.pyi
third_party/2and3/click/types.pyi

The call accepts tuples of types and callback methods

Better type for click 'type' argument

---

third_party/2and3/termcolor.pyi

Added stubs for termcolor: https://pypi.python.org/pypi/termcolor
The tracking repo is not listed in the PyPI page so I'm not too sure who to ask permission for submitting this PR.

Stubs for termcolor

---

stdlib/2and3/struct.pyi
stdlib/3/_ast.pyi
stdlib/3/types.pyi

- https://bugs.python.org/issue21071 (struct.Formatter.format)
- https://github.com/python/cpython/commit/cb41b2766de646435743b6af7dd152751b54e73f (docstring on some ast nodes)
- https://github.com/python/cpython/commit/5a8516701f5140c8c989c40e261a4f4e20e8af86 (new FrameType attributes)

more 3.7 features (struct, FrameType, ast)

---

.travis.yml
requirements-tests-py2.txt

pytype recently added a dependency on six and pyyaml.

add six and pyyaml to requirements

---

stdlib/2and3/locale.pyi

add attributes to locale

---

stdlib/2and3/sqlite3/dbapi2.pyi

specify what type Binary is

---

third_party/2and3/attr/__init__.pyi

To support just released attrs 18.1

Add new factory arg to attrib and fields_dict

---

third_party/2and3/boto/kms/__init__.pyi

This may be causing intermittent test failures (see discussion on gitter).

explicitly import boto.regioninfo

---

third_party/2/google/protobuf/any_pb2.pyi
third_party/2/google/protobuf/any_test_pb2.pyi
third_party/2/google/protobuf/api_pb2.pyi
third_party/2/google/protobuf/compiler/plugin_pb2.pyi
third_party/2/google/protobuf/descriptor_pb2.pyi
third_party/2/google/protobuf/duration_pb2.pyi
third_party/2/google/protobuf/empty_pb2.pyi
third_party/2/google/protobuf/field_mask_pb2.pyi
third_party/2/google/protobuf/map_proto2_unittest_pb2.pyi
third_party/2/google/protobuf/map_unittest_pb2.pyi
third_party/2/google/protobuf/source_context_pb2.pyi
third_party/2/google/protobuf/struct_pb2.pyi
third_party/2/google/protobuf/test_messages_proto2_pb2.pyi
third_party/2/google/protobuf/test_messages_proto3_pb2.pyi
third_party/2/google/protobuf/timestamp_pb2.pyi
third_party/2/google/protobuf/type_pb2.pyi
third_party/2/google/protobuf/unittest_arena_pb2.pyi
third_party/2/google/protobuf/unittest_custom_options_pb2.pyi
third_party/2/google/protobuf/unittest_import_pb2.pyi
third_party/2/google/protobuf/unittest_import_public_pb2.pyi
third_party/2/google/protobuf/unittest_mset_pb2.pyi
third_party/2/google/protobuf/unittest_mset_wire_format_pb2.pyi
third_party/2/google/protobuf/unittest_no_arena_import_pb2.pyi
third_party/2/google/protobuf/unittest_no_arena_pb2.pyi
third_party/2/google/protobuf/unittest_no_generic_services_pb2.pyi
third_party/2/google/protobuf/unittest_pb2.pyi
third_party/2/google/protobuf/unittest_proto3_arena_pb2.pyi
third_party/2/google/protobuf/util/json_format_proto3_pb2.pyi
third_party/2/google/protobuf/wrappers_pb2.pyi

This fleshes out the auto-generated pieces of `google.protobuf`, by
using https://github.com/dropbox/mypy-protobuf to generate mypy stubs
from the .proto files in
https://github.com/google/protobuf/tree/master/src/google/protobuf
Generated from current `master` of google/protobuf, 513b35dc4e73.
Ref google/protobuf#3803, python/typeshed#1705

Add generated stubs for google.protobuf, from its protobufs

---

stdlib/2and3/wsgiref/handlers.pyi
stdlib/2and3/wsgiref/simple_server.pyi
stdlib/2and3/wsgiref/types.pyi

* Add `wsgiref.handlers` and `wsgiref.simple_server`
* Add `StartResponse` to `wsgiref.types`

Complete wsgiref

---

stdlib/3/_ast.pyi

Fixes #2205
For reference https://docs.python.org/3/library/ast.html#abstract-grammar

Add FormattedValue and JoinedStr to ast for py3.6+

---

stdlib/3/_ast.pyi

Added AnnAssign
Added comprehension.is_async
Fixed typo on FormattedValue.format_spec

3.6+ Updates for ast module

---

stdlib/3/unittest/mock.pyi
third_party/2and3/mock.pyi

It works and is needed for code using the dreaded
'from __future__ import unicode_literals'.

mock.patch.object() attribute arg should be Text

---

third_party/2and3/pytz/__init__.pyi

https://github.com/stub42/pytz/blob/master/src/pytz/__init__.py#L187

add pytz.ZERO and pytz.HOUR

---

stdlib/2and3/socket.pyi

allow socket.recv_into to take a memoryview

---

stdlib/3.4/asyncio/tasks.pyi

- Use PEP 526-style variable annotations where possible
- Use FrameType instead of Any
- Remove workaround for mypy issue that was since fixed
- Remove private attributes

Improve asyncio.tasks stubs

---

stdlib/2/builtins.pyi

Fixes breakage caused by #2128.

Copy __builtin__.pyi to builtins.pyi

---

third_party/2and3/werkzeug/exceptions.pyi
third_party/2and3/werkzeug/wrappers.pyi

Two simple fixes, with details in commit messages.

Werkzeug stub fixes

---

third_party/2and3/requests/api.pyi

https://github.com/requests/requests/blob/7e297ed95bdbd1018657f5d6000379ecdfa54423/requests/models.py#L101

Values of `data` are Optional

---

tests/pytype_blacklist.txt
tests/pytype_test.py

* Test some parts of third_party/.
* Unblacklist files that we can now load.

Update pytype_test and pytype_blacklist

---

tests/mypy_test.py

add --show-traceback to mypy_test.py flags

---

README.md
tests/mypy_test.py

Drop support for Python 3.3

---

CONTRIBUTING.md

Updated CONTRIBUTING.md based on the discussion in #2275

Add a convention for platform-dependent APIs to CONTRIBUTING.md

---

stdlib/2and3/_bisect.pyi
stdlib/2and3/math.pyi
stdlib/2and3/numbers.pyi
stdlib/3.3/lzma.pyi
stdlib/3.4/_tracemalloc.pyi
stdlib/3.4/enum.pyi
stdlib/3.4/tracemalloc.pyi
stdlib/3/abc.pyi
stdlib/3/posix.pyi
stdlib/3/urllib/error.pyi
third_party/3/enum.pyi

I found some unused import statements, so I propose removing them.

Remove unused import statements

---

stdlib/2and3/shutil.pyi

See https://github.com/python/typing/issues/564 for background.

Use protocols for shutils.copyfileobj()

---

requirements-tests-py2.txt

Install pytype from PyPI

---

third_party/2and3/mypy_extensions.pyi

Typeshed companion diff to https://github.com/python/mypy/pull/5436

Add another undocumented mypy_extension that we are trying out

---

stdlib/2and3/mmap.pyi

From https://github.com/python/cpython/blob/master/Modules/mmapmodule.c

Add more mmap constants

---

stdlib/2/_io.pyi

Change `mode: unicode` to `mode: Text`

---

stdlib/2and3/argparse.pyi

Document required= argument for add_subparsers in py37+

---

tests/mypy_selftest.py

Now that the typeshed submodule has moved.

fix selftest

---

stdlib/2and3/decimal.pyi

I also alphabetized the typing imports while I was at it.

Fix the return type of decimal.Decimal.__new__.

---

stdlib/3/ipaddress.pyi

Return Any, not Union from IP parsing functions

---

stdlib/2/types.pyi

```
>>> InstanceType.__bases__
(<type 'object'>,)
```

Inherit `InstanceType` from `object`

---

.travis.yml
tests/pytype_test.py

Also, restructure .travis.yml and add names to the jobs.

Rework .travis.yml and run with Python 3.7 where possible

---

stdlib/2and3/zipfile.pyi

fixes https://github.com/python/typeshed/issues/2509
Add is_dir method to ZipInfo class

Add is_dir method to ZipInfo class

---

stdlib/3/unittest/__init__.pyi

This PR adds the regex arg into the assertRaisesRegex function
fixes https://github.com/python/typeshed/issues/2523

Unitest: Complete assertRaisesRegex

---

CONTRIBUTING.md

Remove label descriptions from CONTRIBUTING

---

.travis.yml

At least that's what I read. Let's find out whether that's true.

travis-ci: sudo is not required anymore

---

CONTRIBUTING.md

Reference black, split long functions

---

stdlib/2and3/logging/__init__.pyi

Add missing `currentframe` to `logging` module

---

stdlib/2and3/ssl.pyi

This one is kinda embarrassing. I totally forgot to define the fields of the exception in #2729. 🙈
Cross-check: https://docs.python.org/3.7/library/ssl.html#ssl.SSLCertVerificationError

Add SSLCertVerificationError fields

---

third_party/2/gflags.pyi

https://github.com/google/python-gflags/blob/4f06c3d0d6cbe9b1fb90ee9fb1c082b3bf9285f6/gflags/__init__.py#L800

gflags: Add DEFINE_multi_enum.

---

third_party/3/jwt/__init__.pyi

Use a more accurate type for jwt.decode

---

third_party/2and3/click/decorators.pyi

Fixes #1692 
Note: Just went by what @JelleZijlstra suggested. Not sure if this fixes the real issue.

decorators.pyi: Add overload to option()

---

stdlib/2/json.pyi

This matches what the 3 stub does

Make 2.7's json.load use a protocol for fp

---

third_party/2and3/attr/__init__.pyi

Update attrs stubs to 19.1.0

---

stdlib/3/email/mime/application.pyi
stdlib/3/email/mime/audio.pyi
stdlib/3/email/mime/image.pyi

email.mime.application.MIMEApplication data: bytes -> Union[str, bytes]

---

tests/pytype_test.py

Speeds up pytype by directly calling pytype.io.parse_pyi
rather than running `pytype --parse-pyi` in a subprocess.
The subprocess logic is still required to handle the one pyi file
marked `# parse only` in the pytype blacklist. Once
https://github.com/google/pytype/issues/242 is fixed, the test code
can be cleaned up considerably.

Speed up pytype_test by reducing subprocess calls.

---

third_party/2and3/werkzeug/wrappers.pyi

`user_agent` is a property and returns `UserAgent`.
https://github.com/pallets/werkzeug/blob/ab6150fa49afc61b0c5eed6d9545d03d1958e384/src/werkzeug/wrappers/user_agent.py#L10-L15

Fix werkzeug.UserAgentMixin annotation

---

third_party/2and3/dateutil/tz/__init__.pyi

See https://github.com/dateutil/dateutil/blob/9e95111c8169a34f22fbd64fa122364fcc8a7b4c/dateutil/tz/__init__.py#L8

Add missing dateutil.tz.UTC

---

third_party/2and3/click/types.pyi

click/types.pyi: Add case_sensitive wrt click 7.0

---

stdlib/3/enum.pyi
third_party/2/enum.pyi

This should resolve #2934
I think I followed the contributing steps correctly, but I'm more than happy to tweak things as needed!

Added defs for undocumented attrs on enums

---

third_party/2and3/click/decorators.pyi

add autocomplete to click decorators

---

stdlib/2and3/dis.pyi

allow callables in dis()

---

stdlib/2and3/threading.pyi

Make Timer args less restrictive

---

CONTRIBUTING.md
README.md

We get quite a few bug reports where after a maintainer writes
"Pull Requests Welcome" we get a PR by the submitter. Maybe this
badge will help a bit to encourage people directly submit PRs,
reducing maintainer workload.

Add a "pull requests welcome" batch

---

third_party/2and3/dateutil/rrule.pyi

https://github.com/dateutil/dateutil/blob/40924bd0392308914b01815f56d311c8478217b8/dateutil/rrule.py#L401-L411

dateutil: byweekday can take weekday

---

stdlib/3/importlib/util.pyi

Add missing path-like annotation

---

stdlib/3/urllib/request.pyi

request.pyi: Change Union[] -> Any for attributing status

---

stdlib/3/concurrent/futures/_base.pyi
stdlib/3/concurrent/futures/process.pyi
stdlib/3/concurrent/futures/thread.pyi
third_party/2/concurrent/futures/_base.pyi
third_party/2/concurrent/futures/process.pyi
third_party/2/concurrent/futures/thread.pyi

Add mp_context parameter to concurrent.futures.ProcessPoolExecutor

---

stdlib/3/email/generator.pyi

BytesGenerator requires BinaryIO

---

stdlib/2and3/curses/__init__.pyi

Add curses.COLORS and curses.COLOR_PAIRS

---

stdlib/2and3/curses/__init__.pyi

Re-export _curses._CursesWindow from curses

---

stdlib/2/__builtin__.pyi
stdlib/2and3/builtins.pyi

Make SyntaxError.text be Optional

---

stdlib/3/io.pyi

Added Optional encoding for TextIOWrapper

---

.travis.yml
tests/mypy_test.py

Now that the new analyzer is the default, this does exactly the same as the normal mypy self test.

Remove mypy new analyzer self test

---

stdlib/2/subprocess.pyi

Otherwise this causes a lot of spurious errors.

Fix python 2 subprocess.Popen to produce Popen[bytes]

---

stdlib/3/queue.pyi

Someone might want to check, if they are still incomplete, or if the comment at the top can be removed as well.

adds threading related members to queue.pyi

---

stdlib/2and3/zipfile.pyi

Undocumented but public naming: https://github.com/python/cpython/blob/657008ea0336ff4f275ed3f0c2b6dd2e52de2bba/Lib/zipfile.py#L1238

zipfile.ZipFile: Add start_dir attribute.

---

stdlib/3/http/server.pyi

It will resolve #3217 .
https://github.com/python/cpython/blob/e09359112e250268eca209355abeb17abf822486/Lib/http/server.py#L143-L144

Add ThreadingHTTPServer stub

---

third_party/2and3/click/termui.pyi

This is only relevant for Python 2.

Use Text for text arguments to click.[un]style

---

stdlib/2and3/errno.pyi

add missing errno member

---

stdlib/2/inspect.pyi
stdlib/3/inspect.pyi

Resolves https://github.com/python/typeshed/issues/3264

Fix inspect.FrameInfo/Traceback

---

stdlib/3/asyncio/tasks.pyi

Closes https://github.com/python/typeshed/issues/3266
I didn't find an example of how to format file when you need to add a line break after `->`, please review. Also, it makes sense to create a new alias, something like `_ExceptionalT = Union[_T, BaseException`, but I'm not sure. Thoughts?

switched return_exceptions from bool to Literal for asyncio.gather

---

stdlib/3/http/__init__.pyi

Related commit in CPython
https://github.com/python/cpython/commit/52ad72dd0a5a56414cc29b7c9b03259169825f35

Add http.MISDIRECTED_REQUEST introduced in 3.7

---

stdlib/2/UserDict.pyi
stdlib/2/UserList.pyi

Closes #1759 
Very small issue, as the `data` attributes for both other classes were added along the way at some point

Add `data` to UserList class in py2

---

stdlib/3/inspect.pyi

Fixes https://github.com/python/typeshed/issues/3361

Fixes for inspect.FullArgSpec

---

stdlib/2and3/select.pyi

Arbitrary iterables work just fine.

Change select() stub to accept iterables, not just sequences

---

third_party/3/jwt/__init__.pyi

__init__.pyi: Accept RSAPrivateKey or RSAPublicKey as the key

---

README.md

Clarify contributions are from people external to the project

---

stdlib/3/_ast.pyi

See https://greentreesnakes.readthedocs.io/en/latest/nodes.html#Dict

ast.Dict keys can be None

---

stdlib/3/compileall.pyi

Addresses #3475.   This is a quick first stab at the fix. If I should put the changes in stdlib/3.7 rather than 3, please let me know.

Py37 compileall add invalidation mode

---

stdlib/2and3/__future__.pyi

Documented under the "CompilerFlag" paragraph here:
https://docs.python.org/3/library/__future__.html

__future__: add _Feature.compiler_flag

---

stdlib/3/urllib/request.pyi

Unused since 8e7c32846fc2b07eff10296f815f053a5f6daaa5.

Remove unused type _HTTPResponse

---

stdlib/2and3/antigravity.pyi

Add antigravity module

---

third_party/2and3/jinja2/environment.pyi

Ref::
- https://jinja.palletsprojects.com/en/2.10.x/api/#jinja2.Template.name
- https://jinja.palletsprojects.com/en/2.10.x/api/#jinja2.Template.filename

jinja2: add Template.{name,filename}

---

stdlib/2and3/codecs.pyi

codecs: add literal overloads for bytes to bytes, str to str codecs

---

third_party/2/six/__init__.pyi
third_party/3/six/__init__.pyi

my actual code is (against better judgement) also using `_moved_items` -- but I felt like that's probably outside the bounds of typeshed
I was very not sure how to type annotate `__get__`, typeshed is very inconsistent in this regard:
```console
$ git grep 'def __get__' | cut -d: -f2- | sed 's/^ *//g' | sort | uniq -c
1 def __get__(self, instance: Any, owner: Any) -> Any: ...
2 def __get__(self, instance: Any, owner: Any) -> bool: ...
1 def __get__(self, instance: Any, owner: Any) -> bytes: ...
1 def __get__(self, instance: Any, owner: Any) -> datetime: ...
1 def __get__(self, instance: Any, owner: Any) -> float: ...
1 def __get__(self, instance: Any, owner: Any) -> List[_T]: ...
1 def __get__(self, instance: Any, owner: Any) -> None: ...
1 def __get__(self, instance: Any, owner: Any) -> …
```

Fill out more attributes in six

---

stdlib/2and3/socket.pyi

fix arg name to socket.getaddrinfo for py3

---

third_party/2and3/dateutil/easter.pyi

Added the stub as [documented](https://dateutil.readthedocs.io/en/stable/easter.html)

Add stub for dateutil.easter

---

stdlib/2/SocketServer.pyi
stdlib/3/socketserver.pyi

Give types to all attributes and methods. Addresses #3666.

socketserver: Add missing attributes and methods for ForkingMixIn and ThreadingMixin

---

stdlib/3/os/__init__.pyi

This one was way off, maybe something got changed in a late version of py37?

os.register_at_fork: fix signature

---

stdlib/2and3/modulefinder.pyi

Add types for modulefinder instance fields

---

third_party/3/orjson.pyi

This syncs https://github.com/ijl/orjson/blob/2.4.0/orjson.pyi.

Update orjson annotations to 2.4.0

---

stdlib/3/tokenize.pyi

https://github.com/python/cpython/blob/1246d892038a693304549f8574e6c2784b91589a/Lib/tokenize.py#L37-L38
cookie_re: since 3.0a4
blank_re: since 3.4b3

Add cookie_re / blank_re to py3 tokenize

---

stdlib/3/inspect.pyi

Let inspect._ParameterKind subclass from enum.IntEnum

---

stdlib/2and3/xml/sax/__init__.pyi
tests/stubtest_whitelists/py38.txt

https://bugs.python.org/issue34789

xml.sax: make_parser accepts iterables in py38

---

stdlib/2and3/logging/__init__.pyi

Add stubs for Logger._log() and LoggerAdapter._log()

---

stdlib/3/asyncio/__init__.pyi

Closes #3165. I should've think of it when proposing #3664, but let it slip through.

import SelectorEventLoop from asyncio.unix_events on unix platforms

---

stdlib/2and3/this.pyi

Clearly, the most important stub to have in typeshed. Didn't include the leaked loop variables

Add 'this' module

---

README.md
tests/stubtest_test.py

Document that the test will likely fail locally, to help cases like #3782

README.md: better document test_stubtest pitfall

---

stdlib/3/importlib/metadata.pyi

https://docs.python.org/3/library/importlib.metadata.html#entry-points

stdlib/3/importlib/metadata: add missing "group" attribute to EntryPoint

---

stdlib/2and3/argparse.pyi

argparse: allow passing a callable to ArgumentParser

---

stdlib/2and3/mimetypes.pyi

Add support for PathLike to mimetypes.guess_types()

---

stdlib/3/unittest/mock.pyi
third_party/2and3/mock.pyi

I forgot to subclass Mock and MagicMock on my quest to have the best stubs on PR  #3846
@srittau

Mock and MagickMock subclassing NonCallableMock

---

stdlib/3/importlib/machinery.pyi
tests/stubtest_whitelists/py3_common.txt

Add stub for PathFinder and remove whitelist

---

stdlib/2and3/zlib.pyi

Add array.array type to zlib.crc32

---

stdlib/2and3/socket.pyi

socket: fix default mode for makefile

---

third_party/2and3/dateparser.pyi

Based on PR #3704 by @xcthulhu (Matthew Doty)

Add dateparser module

---

CONTRIBUTING.md

@CraftSpider @hauntsaninja Please read the maintainer's section of the CONTRIBUTING file. All changes should go through PRs and need to be signed off by another maintainer. Thank you for your help and have fun!

Add @CraftSpider and @hauntsaninja as maintainers

---

stdlib/3/os/__init__.pyi

This member is documented at https://docs.python.org/3/library/os.html#os.stat_result.st_file_attributes and https://docs.python.org/3/whatsnew/3.5.html#os

Add st_file_attributes to stat_result for Windows

---

.github/workflows/stubtest-unused-whitelist.yml

This is a preliminary step to automatically creating a PR

Collate all stubtest runs into a single output

---

tests/pytype_test.py

This adds the ability to check single files or directories with
tests/pytype_test.py by specifying the paths to check on the
command line.

pytype tests: Specify files or dirs to check

---

stdlib/2and3/tarfile.pyi
tests/stubtest_whitelists/py35.txt
tests/stubtest_whitelists/py3_common.txt

And update whitelist since #4322 fixed a thing

tarfile: fix arg name

---

.github/workflows/stubtest-unused-whitelist.yml

Well, as I said, not easy to test. 🙄

Fix typo in yaml file

---

stdlib/3/asyncio/__init__.pyi

Resolves #4345
There's more discussion in https://github.com/microsoft/pyright/issues/859

asyncio: export submodules

---

stdlib/2and3/pydoc_data/topics.pyi

This appears to be used by jedi at least, so it would be great to have stubs for it.

Add pydoc_data

---

third_party/3/orjson.pyi

https://github.com/ijl/orjson/blob/master/orjson.pyi
Updated version of #4330.

Update orjson.pyi from upstream

---

third_party/2/six/moves/__init__.pyi

Add back six.moves.range (Python 2)

---

stdlib/3/tkinter/__init__.pyi

make tkinter.Canvas offset option optional

---

stdlib/3/signal.pyi

Mark the return type of singal._HANDLER Any instead of None

---

.github/workflows/tests.yml
.travis.yml

Part of the effort to move to GitHub Actions.

Run pytype and mypy self test using GitHub Actions

---

third_party/2and3/redis/client.pyi

Use overloads for Redis.sort()

---

stdlib/3/asyncio/runners.pyi
tests/stubtest_whitelists/py38.txt

Looks like my change to CPython broke typeshed

asyncio.run: fix type of debug

---

requirements-tests-py3.txt
third_party/2and3/yaml/__init__.pyi

CI failed on a recent PR due to my having a newer version. Might as well live on HEAD.

Upgrade isort

---

stdlib/3/os/__init__.pyi

statvfs_result: type structseq better

---

tests/stubtest_whitelists/py36.txt
tests/stubtest_whitelists/py37.txt
tests/stubtest_whitelists/py38.txt
tests/stubtest_whitelists/py39.txt

This should take care of #4598

stubtest whitelist: fix

---

tests/stubtest_whitelists/py39.txt

py39.txt: remove no longer needed comment

---

stdlib/2and3/contextlib.pyi
third_party/2and3/jinja2/defaults.pyi

Everything else seems unintended to be reexported.

pep 484: last reexports

---

stdlib/3/concurrent/futures/_base.pyi
third_party/2/concurrent/futures/_base.pyi

Using `_Collection` for Python 3 and above.
Using `Container` for Python 2.
Fixes #4613

Changed to types which implement len

---

stdlib/2and3/logging/handlers.pyi

Added missing SysLogHandler types

---

stdlib/2and3/ftplib.pyi

Fixes https://github.com/python/typeshed/issues/4632

Add various undocumented functions from ftplib

---

README.md

Add information about removing third-party packages

---

third_party/2and3/cachetools/decorators.pyi

fix(cachetools): fix decorators signature typing

---

.github/workflows/mypy_primer.yml

This will take some merge and debug...

mypy_primer: attempt to fix workflow

---

stdlib/2and3/contextlib.pyi

Make _GeneratorContextManager covariant

---

stdlib/3/configparser.pyi

Fixes #4709 
Are we still maintaining Python 2 stubs? If so, I'll add to those too

Added missing regexes

---

stdlib/3/ast.pyi

Added precise types for ast Constants

---

stdlib/3/typing.pyi

Derive Reversible from Iterable

---

README.md

README.md: update for the times

---

tests/mypy_test.py

I think this should help prevent issues like #4815

mypy_test: fix for stub deletions

---

stdlib/3/configparser.pyi

Overload defaults type when allow_no_value==True

---

.github/workflows/mypy_primer.yml
.github/workflows/mypy_primer_comment.yml

Much of the comment script is based off of https://github.com/dawidd6/action-download-artifact

Return mypy_primer to CI

---

stdlib/3/tkinter/constants.pyi

use bool for tkinter.FALSE and similar constants

---

stdlib/3/tkinter/__init__.pyi

Grid padx/pady accept tuple, issue 4830

Grid padx/pady accept tuple, issue 4830

---

stdlib/3/tkinter/__init__.pyi

fix for widget.grid(widget.grid_info())
fix for widget.pack(widget.pack_info())
fix for widget.place(widget.place_info())

Changed Dict with Mapping in grid/pack/place_configure #4836.2

---

.github/workflows/mypy_primer.yml
.github/workflows/mypy_primer_comment.yml

With the goal of making mypy_primer no longer the CI bottleneck

mypy_primer: shard across two CI jobs

---

stdlib/3/_ast.pyi

ast: remove docstring attribute

---

stdlib/3/tkinter/__init__.pyi

#4834 
I am not sure 100% this is the right thing, see issue.

Added children field to Misc #4834

---

stdlib/2and3/tarfile.pyi

Reference: https://github.com/python/mypy/issues/1362#issuecomment-752331292

Added missing path atribute to TarInfo class

---

stdlib/3/tkinter/__init__.pyi

#4872
_PlaceInfo and place_configure fix

_PlaceInfo and place_configure fix #4872

---

stdlib/3/tkinter/__init__.pyi

Based on https://www.tcl.tk/man/tcl8.6/TkCmd/event.htm

tkinter: event_foo method type hints

---

scripts/migrate_script.py

As suggested by Jukka in https://github.com/python/typeshed/issues/2491

migrate_script: prefix @ to python2

---

stdlib/3/tkinter/__init__.pyi

support widgets in _TextIndex

---

tests/pytype_test.py

I noticed that the pytype parse test was getting quite slow again. This
is a somewhat hacky change that caches pytype's internal pyi loader to
avoid parsing files multiple times. On my machine, the test goes from
taking ~6m to complete to ~30s.

Speed up pytype_test by reusing the pyi loader.

---

third_party/2and3/pyVmomi/vmodl/__init__.pyi
third_party/2and3/pyVmomi/vmodl/query.pyi

These classes have constructors that accept all arguments as kwargs.

pyVmomi: Add constructors for vmodl.query classes

---

.github/workflows/tests.yml
requirements-tests-py3.txt
tests/pytype_test.py

For now, the test requires changes that have been merged into the pytype master branch but not yet released. I'll update requirements-tests-py3.txt again once I've cut a new release (hopefully later this week).

Fix and re-enable pytype_test

---

.github/workflows/mypy_primer.yml
stdlib/functools.pyi

Trying to get mypy_primer going (at least for the stdlib)

Run mypy_primer with a newer mypy

---

stubs/six/six/__init__.pyi

Revert "A temporary change for integration testing. Will be removed soon"

---

stdlib/tkinter/__init__.pyi
stdlib/tkinter/ttk.pyi

relax tkinter bind callback return types

---

stdlib/tkinter/font.pyi

relax tkinter.font._FontDescription

---

stdlib/builtins.pyi

make WindowsError an alias of OSError (new in Python 3.3)

---

stdlib/builtins.pyi

Should not cause problems now that https://github.com/python/mypy/pull/10115 is merged

make WindowsError available only on windows

---

stdlib/_weakref.pyi

Updated: return type for getweakrefs

---

stdlib/optparse.pyi

https://github.com/python/cpython/blob/1e3c68246ee738b5ec5450b1eb39af2fca300cb9/Lib/optparse.py#L458

Type optparse.Option.default attribute

---

stubs/Werkzeug/werkzeug/wrappers.pyi

Changed: Expires argument type to support datetime and int values

---

stdlib/email/message.pyi

Add "policy" attribute to email.message.Message

---

stdlib/email/headerregistry.pyi

Make "addresses" argument to email.headerregistry.Group an Iterable

---

stdlib/@python2/logging/__init__.pyi
stdlib/@python2/logging/config.pyi
stdlib/@python2/logging/handlers.pyi
stdlib/VERSIONS
stdlib/logging/__init__.pyi
stdlib/logging/config.pyi
stdlib/logging/handlers.pyi

* Split Python 2 and Python 3 files
* Remove now obsolete branches
* `Text` -> `str` in Python 3 files
* Use built-in collections in Python 3 files

Modernize logging

---

stubs/Werkzeug/werkzeug/wrappers.pyi

Fixes https://github.com/python/typeshed/issues/5101 ... I hope! Having a hard time testing this.

Fix an incorrect type hint for werkzeug's BaseResponse class

---

stdlib/configparser.pyi

Fix constructor annotation for configparser.DuplicateOptionError

---

stdlib/tkinter/__init__.pyi

fix name attribute for Toplevel class

---

stdlib/typing.pyi

Fixes https://github.com/python/typeshed/issues/5125

Awaitable.__await__ should accept an Iterator rather than a Generator

---

stdlib/itertools.pyi
tests/stubtest_whitelists/py3_common.txt

Figured out what I did wrong when defining __new__ for these - I needed to make _T covariant or the return types won't be considered as subtypes.

itertools stubtest excpetions - product and combinations

---

stdlib/importlib/util.pyi

Changed: Return type of spec_from_loader and spec_from_file_location.

---

.github/workflows/mypy_primer.yml
.github/workflows/mypy_primer_comment.yml
.github/workflows/stubtest-unused-whitelist.yml
.github/workflows/tests.yml

This will also allow us to set the default permissions for workflow to read-only, if it works.

Add permissions to all workflows

---

stubs/requests/requests/adapters.pyi

This came up while reviewing #5266

fix requests.adapters.HttpAdapter.max_retries

---

stdlib/symbol.pyi

We still don't have a better way of doing this, right?

symbol: removed in py310

---

stdlib/asyncio/tasks.pyi

Just removing the loop argument from various places

asyncio.tasks: update for py310

---

stdlib/tkinter/font.pyi

tkinter.font nametofont root arg py3.10

---

stdlib/traceback.pyi

I think technically you need to pass both of value and tb or neither, so
let me know if you think it's worth all the overloads

traceback: update for py310

---

tests/stubtest_test.py

change positional-only test to use Python 3.10

---

.github/workflows/tests.yml
tests/pyright_test.py

Bump pyright

---

requirements-tests-py3.txt

Bump pytype

---

requirements-tests-py3.txt

Added in #5353 but no longer needed after #5358

delete pytype bug workaround

---

README.md

document pyright test better

---

.github/workflows/stubtest-unused-whitelist.yml
.github/workflows/tests.yml

This got broken during modular typeshed

Fix stubtest unused workflow

---

.github/workflows/stubtest-unused-whitelist.yml

#5372 and #5375 helped, but opening the PR still fails. Hopefully this fixes that.

Attempt to fix stubtest unused PR opening

---

.github/workflows/mypy_primer_comment.yml

GitHub enforces a limit of 64kB

Limit mypy primer comment to 30000 chars

---

.github/workflows/mypy_primer.yml

This will hopefully fix the mypy primer errors

Use newer mypy version for mypy_primer

---

.github/workflows/mypy_primer.yml
.github/workflows/mypy_primer_comment.yml

@Akuli was right in https://github.com/python/typeshed/pull/5407

Fix workflow path matching

---

.github/workflows/tests.yml

In #5420, @srittau said he already did this, but it didn't seem like that to me.

run pytype_test in python 3.9

---

stubs/jwt/METADATA.toml

pyjwt includes annotations since version 2.0.0

---

.flake8

flake8: do not exclude @python2 dirs

---

.github/workflows/mypy_primer.yml

@Akuli I think these are the permission we originally had.
Possibly, maybe closes #5459

Try to fix mypy_primer permissions

---

stdlib/VERSIONS

Describe sub-module versioning

importlib.resources was added in 3.7

---

.github/workflows/mypy_primer.yml

Give primer comment task all write permissions

---

.github/workflows/tests.yml

I don't have the bandwidth to fix this, at the moment, but this is a less important test anyway.

mypy test suite is broken, disable temporarily

---

README.md
stdlib/_typeshed/README.md
stdlib/_typeshed/__init__.pyi
stdlib/_typeshed/tkinter.pyi
stdlib/_typeshed/wsgi.pyi
stdlib/_typeshed/xml.pyi
tests/check_consistent.py

Closes: #5486
I have marked types I personally consider stable as such, but I'm open to changes.

Document _typeshed

---

.github/workflows/tests.yml
tests/pyright_test.py

Bump to pyright 1.1.142

---

.github/workflows/mypy_primer_comment.yml

Tested on https://github.com/Akuli/typeshed/pull/17

use comment-hider v0.3.0

---

.github/workflows/tests.yml
tests/mypy_test_suite.py

Fixes #5505, in combination with https://github.com/python/mypy/pull/10527

Re-enable mypy test suite

---

CONTRIBUTING.md
stdlib/types.pyi

Let's see if it works. See #4819.

Use PEP 604 in types.pyi

---

stdlib/__future__.pyi

Add `__all__` to `__future__.pyi`

---

stdlib/_typeshed/__init__.pyi

Remove AnyPath

---

.github/workflows/mypy_primer.yml
.github/workflows/stubtest-unused-whitelist.yml
.github/workflows/tests.yml
requirements-tests-py3.txt

Use stable mypy

---

scripts/generate_proto_stubs.sh

Fix generate protobuf script and run formatters

---

CONTRIBUTING.md

Metadata versions field now reflects the latest supported version

---

stubs/requests/requests/sessions.pyi

Add self type to requests.Session.__enter__

---

tests/README.md
tests/stubtest_third_party.py

Make stubtest_third_party.py executable

Add distributions arg to third-party stubtest

---

stubs/PyYAML/yaml/error.pyi

Signed-off-by: oleg.hoefling <oleg.hoefling@gmail.com>

Add stubs for yaml.error

---

CONTRIBUTING.md

And add a new "Partially supported" section

Update PEP 612 status in CONTRIBUTING.md

---

stdlib/logging/__init__.pyi

links to relevant docs: https://docs.python.org/3/library/logging.html#logging.basicConfig https://docs.python.org/3/library/functions.html#open

Add Python 3.9 support in logging.basicConfig

---

stubs/bleach/bleach/sanitizer.pyi

bleach: Loosen attribute dict type

---

CONTRIBUTING.md
tests/mypy_test.py
tests/stubtest_third_party.py

@python2 nits

---

stdlib/@python2/_typeshed/__init__.pyi
stdlib/_typeshed/__init__.pyi

Add Self type var to _typeshed

---

.github/workflows/tests.yml
tests/pyright_test.py

Been a bit since this was last done; update to this morning's release.

Update pyright to 1.1.152

---

stubs/Routes/METADATA.toml
stubs/enum34/METADATA.toml
stubs/fb303/METADATA.toml
stubs/futures/METADATA.toml
stubs/ipaddress/METADATA.toml
stubs/kazoo/METADATA.toml
stubs/pathlib2/METADATA.toml
stubs/pymssql/METADATA.toml
stubs/scribe/METADATA.toml
stubs/tornado/METADATA.toml

Re-add python2 keys to METADATA temporarily

---

CONTRIBUTING.md

Recommend `Self` in CONTRIBUTING.md

---

stdlib/types.pyi

Add __defaults__ to types.MethodType

---

stdlib/http/server.pyi

Add missing type hints in http.server

---

stdlib/ssl.pyi

add ssl.get_ciphers

---

stdlib/types.pyi

use new union syntax in stdlib/types.pyi

---

stdlib/_ast.pyi
stdlib/ast.pyi
stubs/typed-ast/typed_ast/ast27.pyi
stubs/typed-ast/typed_ast/ast3.pyi

change ast files to use new union syntax

---

tests/pytype_test.py

pytype is finally dropping Python 2 support (in the upcoming release
after 2021.08.03), so pytype_test can no longer run with
--python_version=2.

Stop running pytype_test on Python 2-only stubs.

---

requirements-tests-py3.txt

Signed-off-by: oleg.hoefling <oleg.hoefling@gmail.com>

bump black + isort

---

CONTRIBUTING.md

Explain adding new third-party stubs

---

CONTRIBUTING.md

Cf. #5633 and typeshed-internal/stub_uploader#23
Pinging @JelleZijlstra, @hauntsaninja, and @Akuli to take notice.

Commit messages for stubs are now used as changelog

---

stubs/psutil/psutil/_common.pyi

I will continue to improve it in the next PRs.

Improves several `NamedTuple`s in `psutil`

---

stdlib/types.pyi

Closes https://github.com/python/typeshed/issues/6086

fix: add __await__ to CoroutineType

---

.github/workflows/tests.yml
pyrightconfig.json
pyrightconfig.stricter.json
tests/pyright_test.py

Update pyright to 1.1.175

---

stubs/Markdown/markdown/inlinepatterns.pyi

markdown: fix type of Pattern

---

stdlib/types.pyi

https://docs.python.org/3/library/types.html#types.coroutine
resolves: #6126

Make types.coroutine return Awaitable

---

tests/README.md

Update Python version for pytype

---

stdlib/builtins.pyi

Fix `print` stub

---

stdlib/@python2/logging/__init__.pyi

Without this writing straddling code is quite tricky, as these are
generic in Python 3.

logging: Make LoggerAdapter and StreamHandler generic in Python 2

---

stdlib/http/client.pyi

See
https://github.com/python/cpython/blob/da20d7401de97b425897d3069f71f77b039eb16f/Lib/http/client.py#L256

Add HTTPResponse.fp as io.BufferedReader

---

.github/workflows/tests.yml

black and isort formatting is now handled by pre-commit.

Remove black/isort checks from CI

---

tests/stubtest_third_party.py

These should be f strings, but they weren't.

fix stubtest prints

---

requirements-tests-py3.txt

It is required to solve https://github.com/python/typeshed/pull/6361

Updates pytype version

---

stdlib/VERSIONS
stubs/six/six/moves/_dummy_thread.pyi
tests/check_consistent.py

https://bugs.python.org/issue37312

dummy_thread/ing: remove in 3.9

---

stdlib/token.pyi

Added as part of the changes made in https://bugs.python.org/issue43822

Add token(ize).SOFT_KEYWORD

---

tests/stubtest_allowlists/py36.txt
tests/stubtest_allowlists/py37.txt
tests/stubtest_allowlists/py38.txt

Broken by https://github.com/python/typeshed/pull/6439

Fix allowlists

---

tests/stubtest_allowlists/py310.txt
tests/stubtest_allowlists/py38.txt
tests/stubtest_allowlists/py39.txt

I noticed this while reviewing #6445

add comment about CodeType.replace to stubtest allowlists

---

pyrightconfig.stricter.json
tests/stubtest_third_party.py

get rid of remaining references to pallets stubs

---

.github/workflows/tests.yml
tests/pyright_test.py

Necessary to unblock #6469 (thanks to @erictraut for the quick fix!)

Bump pyright version to 1.1.192

---

stubs/simplejson/simplejson/errors.pyi

This type stub file was generated by pyright. Then filled in manually.

simplejson: create errors.pyi

---

stdlib/asyncio/__init__.pyi

This PR proposes purely cosmetic changes, to make `asyncio.__init__` a bit neater

Clean up `asyncio.__init__`

---

stdlib/signal.pyi

This PR proposes purely cosmetic changes to make `signal.pyi` a bit neater.

Clean up `signal.pyi`

---

tests/stubtest_allowlists/py3_common.txt

allowlists: add comment to hmac.HMAC.blocksize

---

stdlib/ast.pyi

This recently regressed in #6522

ast: allow non-literal strings

---

stdlib/inspect.pyi

https://github.com/python/cpython/blob/main/Lib/inspect.py#L2576
See related discussion in microsoft/pyright#2708.

inspect._ParameterKind.description is a property

---

.github/workflows/mypy_primer.yml

Doing so would have caught #6591

Run primer on latest Python version

---

stdlib/turtle.pyi

turtle: improve RawTurtle.screen(s) types

---

.github/workflows/stubtest.yml
.github/workflows/tests.yml
requirements-tests.txt

Temporily pin mypy used for stubtest checks to 0.910, until the stubtest
problems are addressed.

Upgrade mypy to 0.920

---

requirements-tests.txt
tests/mypy_test.py

Test third-party stubs with typeshed from mypy

Update to mypy 0.921

---

stdlib/tty.pyi

`tty` is not available on Windows

---

stdlib/_posixsubprocess.pyi

`_posixsubprocess` is not available on Windows

---

stdlib/crypt.pyi

`crypt` is not available on Windows

---

stdlib/fcntl.pyi

`fcntl` is not available on Windows

---

tests/stubtest_allowlists/py3_common.txt

Allowlists: move entries relating to `__all__` weirdness to their own section

---

stubs/six/@python2/six/moves/__init__.pyi
stubs/six/@python2/six/moves/copyreg.pyi
stubs/six/six/moves/__init__.pyi
stubs/six/six/moves/copyreg.pyi

Add six.moves.copyreg six stubs

---

stdlib/opcode.pyi

Definition: https://github.com/python/cpython/blob/main/Lib/opcode.py#L24

Improve `cmp_op` in `opcode`

---

stubs/urllib3/urllib3/__init__.pyi

Fixes https://github.com/python/typeshed/issues/6889

add "__version__" to urllib3

---

stubs/requests/@tests/stubtest_allowlist.txt

requests: Remove an unused allowlist entry

---

stdlib/builtins.pyi

fix typo in _SplitCondition definition

---

.github/workflows/tests.yml
stdlib/enum.pyi

If this works, the CI should fail because of #6902.

Enable pyright for Python 3.11

---

stdlib/@python2/typing.pyi
stdlib/typing.pyi

Unblocks https://github.com/PyCQA/flake8-pyi/pull/79

Add `# noqa` comments to `AnyStr`

---

stdlib/@python2/__builtin__.pyi
stdlib/@python2/_dummy_threading.pyi
stdlib/@python2/builtins.pyi
stdlib/@python2/cgi.pyi
stdlib/@python2/contextlib.pyi
stdlib/@python2/ftplib.pyi
stdlib/@python2/multiprocessing/pool.pyi
stdlib/@python2/socket.pyi
stdlib/@python2/threading.pyi
stdlib/@python2/weakref.pyi

Unblocks https://github.com/PyCQA/flake8-pyi/pull/83

Remove even more unused `TypeVar`s

---

stdlib/@python2/__builtin__.pyi
stdlib/@python2/builtins.pyi
stdlib/tkinter/__init__.pyi
stdlib/types.pyi
stdlib/zoneinfo/__init__.pyi
stubs/cryptography/cryptography/x509/__init__.pyi
stubs/polib/polib.pyi

remove quoted strings

---

.flake8

Dependent on PyCQA/flake8-pyi#101.

Disable Y026 from flake8-pyi

---

.flake8

disable Y026 in typing.pyi too

---

stdlib/urllib/request.pyi

Use MutableMapping for urllib.request.Request headers

---

stdlib/weakref.pyi

Source: https://github.com/python/cpython/blob/f1c6ae3270913e095d24ae13ecf96f5a32c8c503/Lib/weakref.py#L591

Use `ParamSpec` for `weakref.finalize`

---

requirements-tests.txt

If CI goes well on this PR I'll make a non-RC release of flake8-pyi and update this PR.
(And that's too many abbreviations in one sentence.)

use flake8-pyi 22.1.0

---

stdlib/bdb.pyi

Source: https://github.com/python/cpython/blob/270a09184d312856ca112396daec8f360cc5510e/Lib/bdb.py#L640

Use `ParamSpec` for `bdb.Bdb.runcall`

---

stdlib/curses/__init__.pyi

Source: https://github.com/python/cpython/blob/main/Lib/curses/__init__.py#L94

Add `TODO` to support `Concatenate` in `curses`

---

stdlib/sys.pyi

Docs: https://docs.python.org/3/library/sys.html#sys.path_hooks

Fix `sys.path_hooks` type

---

stdlib/asyncio/futures.pyi

See https://docs.python.org/3/library/asyncio-future.html#asyncio.isfuture

Improve `asyncio.Future` type

---

stubs/babel/babel/core.pyi

https://babel.pocoo.org/en/latest/api/core.html#babel.core.get_global

babel: Add babel.core.get_global

---

stdlib/@python2/typing.pyi
stdlib/typing.pyi

Don't use a literal for TYPE_CHECKING

---

stdlib/zoneinfo/__init__.pyi

Flagged by https://github.com/PyCQA/flake8-pyi/pull/161

Remove unused `TypeVar`

---

stubs/requests/requests/sessions.pyi

Fixes https://github.com/python/typeshed/issues/7088

Allow passing of a single hook instead of a list of hooks

---

stdlib/@python2/_osx_support.pyi
stdlib/_osx_support.pyi

Refs https://github.com/PyCQA/flake8-pyi/pull/176

Add `__all__` to `_osx_support`

---

stdlib/sched.pyi

Changes:
- Adds `__all__`
- Adds public attributes to `scheduler`
- `delayfunc` can return anything, returned value is ignored

Improve `sched` typings

---

stubs/requests/requests/__init__.pyi

Added missing import for requests.JSONDecodeError

---

stdlib/pstats.pyi
tests/stubtest_allowlists/py310.txt
tests/stubtest_allowlists/py39.txt

Let's try this out.
Refs https://github.com/python/typeshed/issues/7173

Improve `pstats` typing

---

stdlib/typing_extensions.pyi

Add more new typing-extensions features

---

stdlib/compileall.pyi

Add `compileall.__all__`

---

.github/workflows/stubtest.yml
.github/workflows/tests.yml
tests/stubtest_allowlists/py310.txt
tests/stubtest_allowlists/py36.txt
tests/stubtest_allowlists/py37.txt
tests/stubtest_allowlists/py38.txt
tests/stubtest_allowlists/py39.txt
tests/stubtest_allowlists/py3_common.txt
tests/stubtest_third_party.py

Update stubtest for submodule versions, typeddict fix

---

stubs/contextvars/contextvars.pyi
stubs/pycurl/pycurl.pyi

contextvars, pycurl: make classes final
