python/typeshed

stdlib/3/functools.pyi
Implements two "TODO" notes in `functools.pyi`.
- "TODO implement as class; more precise typing"
- "TODO cache_info and `__wrapped__` attributes"
But I wasn't able to figure out how to type the `Callable` as precisely as I would have liked, because you really want the signature to match callables of arbitrary arity and then have a callable of that arity as the return value.
PEP484 [says](https://www.python.org/dev/peps/pep-0484/#callable):
> Since using callbacks with keyword arguments is not perceived as a common use case, there is currently no support for specifying keyword arguments with Callable . Similarly, there is no support for specifying callback signatures with a variable number of argument of a specific type.
I'm not 100% sure, but I interpret this as ruling out the ability to …
=> Enhance type information for lru_cache

stdlib/2.7/re.pyi
From python 2.7 re, this should now be the correct full constants list:
```
I = IGNORECASE = sre_compile.SRE_FLAG_IGNORECASE # ignore case
L = LOCALE = sre_compile.SRE_FLAG_LOCALE # assume current 8-bit locale
U = UNICODE = sre_compile.SRE_FLAG_UNICODE # assume unicode locale
M = MULTILINE = sre_compile.SRE_FLAG_MULTILINE # make anchors look for newline
S = DOTALL = sre_compile.SRE_FLAG_DOTALL # make dot match newline
X = VERBOSE = sre_compile.SRE_FLAG_VERBOSE # ignore whitespace and comments
T = TEMPLATE = sre_compile.SRE_FLAG_TEMPLATE # disable backtracking
DEBUG = sre_compile.SRE_FLAG_DEBUG # dump pattern after compilation
```
=> Add missing re module constants for 2.7.

stdlib/3/builtins.pyi
This was missing for some reason while the Python 2.7 stubs have it.
Sample test code:
```
% cat testtype.py
A = type('A', (), {})
print(A.__name__)
```
Results before:
```
% python -m mypy --py2 testtype.py
% python -m mypy testtype.py
testtype.py:1: error: Too many arguments for "type"
%
```
Results after: type checking passes in both modes.
=> Define three argument type() overload (Python 3)

stdlib/3/inspect.pyi
This is follow-up to a similar commit improving Python 2.7 inspect stub[1].
Similarly, this commit consists of:
* Splitting and reordering the content into sections corresponding
to the module's documentation sections
* Implementing missing functions, classes etc.
* Adding TODOs for things that are either difficult to get or I can't
figure them out right now
* Making the existing code consistent with the newly added things
As suggested in pull request #108 I'm modifying the generic Python 3
stub even though some things changed and were added in various Python
3.x releases - the changes seem to be backwards compatible and the
additions, well, they should not break much except for some false
positives on older Python 3 versions.
Some of the types in this stub were not obvious so I either …
=> Improve Python 3 inspect stub

stdlib/2.7/contextlib.pyi, stdlib/3/contextlib.pyi
This reflects the fact that `contextlib.contextmanager` should be applied to functions that return an iterator and returns a function that makes a context manager.
I'm not sure where the best place is to put this ContextManager[T] concept.
=> Better stub for contextlib.contextmanager.

stdlib/3/fcntl.pyi
This patch:
* Adds some constants that although undocumented are exposed by the
module
* Modifies the signature of fcntl() to match reality
* Adds missing function stubs
* Modifies few existing constant declarations to match the repository
conventions
I believe the stub is complete now (and if it's not there isn't much
missing).
=> Improve Python 3 fcntl stub

stdlib/2.7/_functools.pyi, stdlib/2.7/functools.pyi
I believe that the signature in stdlib/3/functools.pyi is the correct model
for all versions of reduce.
=> Fix signature for reduce in some files.

stdlib/3/builtins.pyi
```python
class A:
pass
A().__dict__
```
is a valid python3 statement but mypy (more a typeshed issue I guess) gives me
```
file:3: error: "A" has no attribute "__dict__"
```
This PR resolves this (more documented in #132) (not a really nice fix but a working one, in the future, it would be nicer to have mypy being aware if a class is native or not).
=> add `__dict__` attribute to class instance

stdlib/2.7/typing.pyi, stdlib/3/typing.pyi
following https://github.com/python/typing/issues/179
I didn't add tests, because it looks like everything is checked automatically by typeshed/runtests.py
=> Enable typing.DefaultDict as an alias for collections.defaultdict

stdlib/2.7/os/__init__.pyi, stdlib/3/os/__init__.pyi
Add os.environ.copy() to Python 2 stubs. Fix return
type of os.environ.copy().
=> Fixes to os.environ

third_party/2.7/requests/__init__.pyi, third_party/3/requests/__init__.pyi
Not having `__version__` in requests' stub file was giving a mypy error [here](https://github.com/zulip/zulip/blob/5f053e0047f1f96303f0fe6498bada48aa444454/api/zulip/__init__.py#L49).
I haven't yet taken permission from requests' maintainers about this pull request.
=> Add __version__ to requests

stdlib/3/codecs.pyi
Add type to the `errors` argument in `codecs.EncodedFile.__init__`.
=> type `errors` in codecs.EncodedFile

stdlib/2.7/typing.pyi, stdlib/3/typing.pyi
This is one of the items we need to do before closing https://github.com/python/typing/issues/107
=> Add stub version of Type[C]

stdlib/3/sys.pyi
Mostly what the title say: avoid using `object` in sys, remplacing these by `Any`.
Also added that `sys.call_tracing` takes a `Callable` instead of `Any` and return correct type.
=> avoid using `object` in sys

stdlib/2.7/re.pyi
The type of the pattern doesn't affect the return type.
=> replace re patterns AnyStr with Union[str, unicode]

stdlib/2.7/xml/etree/ElementTree.pyi, stdlib/3.2/xml/etree/ElementTree.pyi, stdlib/3.3/xml/etree/ElementTree.pyi, stdlib/3.4/xml/etree/ElementTree.pyi, stdlib/3.5/xml/etree/ElementTree.pyi, stdlib/3/xml/etree/ElementTree.pyi
`xml.etree.ElementTree.Element`s can be iterated over, yielding their children. They're a `Sequence` since they use `__getitem__` as opposed to `__iter__`.
Presently there is no indication that this is the case in typeshed, so iterating over an `Element` gives an error on typechecking.
We ran into this in https://github.com/zulip/zulip/pull/875 (you can see the relevant error in the travis build [here](https://travis-ci.org/zulip/zulip/jobs/135110548)).
This PR adds the information that `Elements` are `Sequence`s to the stub, fixing this. The only thing I'm not quite sure about is if I did the right thing with `_ElementInterface ` under `3`.
cc @gnprice, who I talked about this with earlier. also @timabbott.
=> make xml.etree.ElementTree.Element a Sequence

stdlib/2.7/SocketServer.pyi, stdlib/3/socketserver.pyi
See #238.
Simply moved to `2and3`, also found some missing attributes.
=> add types to socketserver for py2

stdlib/3/configparser.pyi
=> Fix argument type for configparser.write

stdlib/3/os/__init__.pyi
`os.name` was previously wrongly typed as `Callable[[], str]` in the python 3 stdlib stubs. I changed it to `str`.
=> Make os.name a str in python 3.

stdlib/3/os/__init__.pyi
Using `sys.version_info` to define the stubs depending on the version.
=> Added os.sync, os.truncate and os.fwalk for Python version >= 3.3

.gitignore, stdlib/3/importlib/__init__.pyi
=> Add stubs for importlib.__init__

stdlib/3/importlib/_modulespec.pyi, stdlib/3/importlib/abc.pyi, stdlib/3/importlib/machinery.pyi, stdlib/3/types.pyi
=> Add stubs for importlib.machinery

stdlib/3/subprocess.pyi
https://docs.python.org/3/library/subprocess.html#subprocess.CalledProcessError says that `CalledProcessError`'s `output` is `None` if not specified.
I checked the source code of [subprocess.py](https://hg.python.org/cpython/file/3.5/Lib/subprocess.py#l380) and there `CalledProcessError`'s `__init__` took a default value of `None` for the parameter `output`.
=> Set a default value for output in CalledProcessError.__init__

tests/mypy_test.py
this reverts a change I introduced in 63cbe2dc3cde25109f2ad212dbf32aa21e3329c6
original flag change was just confusion on my part
=> revert unnecessary change to mypy_test from previous commit

stdlib/3/subprocess.pyi
`check_output`'s return type can be `str` if `universal_newlines=True`.
=> subprocess: Fix return type of check_output.

stdlib/3/builtins.pyi
The `message` attribute of `Exception` has been deprecated since python 2.6. It has been removed from python 3 afaik.
=> builtins: Remove Exception.message.

stdlib/3/importlib/__init__.pyi, stdlib/3/importlib/abc.pyi
Now that `importlib.abc` is implemented, we can resolve the return type of `find_loader`.
Also, `source_to_code` is a `static_method` so it should have any `self`.
=> add some types to importlib

stdlib/2and3/argparse.pyi
I looked through most of the 3.4 `argparse.py` code and all of these parameters are only used as iterables in `for` loops. So my impression from PEP484 is that they should all be `Sequence`s not `List`s.
=> argparse stub fix: List should probably be Sequence

stdlib/2and3/argparse.pyi
Currently the following code produces an error:
```py
import argparse
from typing import Any
class TestAction(argparse.Action):
pass
if __name__ == "__main__":
p = argparse.ArgumentParser()
p.add_argument("--test", action=TestAction)
```
The error message is:
```
test.py:11: error: Argument 2 to "add_argument" of "ArgumentParser" has incompatible type "TestAction"; expected "Union[str, Action]"
```
Imho the current stub in `stdlib/2and3/argparse.pyi` is wrong by declaring `action: Union[str, Action]` since that disallows subclasses of `Action`. This PR fixes that by using a bound TypeVar.
=> argparse stub fix: allow subclasses of Action in add_argument(action=...)

stdlib/3/socketserver.pyi
From the BaseRequestHandler documentation:
handle()
This function must do all the work required to service a request.
The default implementation does nothing. Several instance attributes
are available to it; the request is available as self.request; the
client address as self.client_address; and the server instance as
self.server, in case it needs access to per-server information.
The type of self.request is different for datagram or stream
services. For stream services, self.request is a socket object;
for datagram services, self.request is a pair of string and
socket.
I also added a union that expresses the fact that client_address can be
a string in case of using Unix domain sockets.
=> Add BaseRequestHandler instance attributes

stdlib/3/textwrap.pyi
Compare with https://docs.python.org/3/library/textwrap.html .
=> textwrap for py3: fixed stubs to include 'text' param

stdlib/2and3/mmap.pyi, tests/pytype_blacklist.txt
First was for mypy compatibility, but is no longer needed.
Second is removed by inheriting from (Iterable[bytes],
Container[bytes], Sized, Reversible[bytes]) instead of
Sequence[bytes]. Should presumably catch more errors when using __getattr__
=> 2and3/mmap.pyi : remove "type: ignore"

stdlib/2and3/zipfile.pyi
In 2.7, only BadZipfile exists. In 3.x, both exist.
=> Fix the definitions of BadZip{f,F}ile.

stdlib/2and3/pkgutil.pyi, stdlib/3/importlib.pyi
https://docs.python.org/3/library/pkgutil.html
I was unable to find a better type than any for importers, also `ImpLoader.__init__` was mainly based on code rather than documentation (deprecated anyway, new code should be based on importlib).
=> Add stubs for pkgutils

third_party/3/lxml/objectify.pyi
typing.AnyStr usage here was a mistake that I noticed too late,
from a GitHub comment[1]:
AnyStr is a type variable so in your version of
objectify.fromstring() the types if text and base_url have to
correspond -- but with unions they can each be either str or bytes,
and that's how the rest of the API is defined.
[1] https://github.com/python/typeshed/pull/436#issuecomment-237708512
=> Remove undesired type variable from lxml.objectify

stdlib/2.7/ast.pyi
This would break ast.Tuple, i.e. reveal_type(ast.Tuple) showed up as `object`
=> Fix Tuple being imported twice in ast.pyi

stdlib/2and3/keyword.pyi
I just found the most trivial python module.
https://docs.python.org/3/library/keyword.html
=> add keyword

third_party/2and3/ujson.pyi
This pull request adds stubs for [ujson](https://pypi.python.org/pypi/ujson). Note that the interface for ujson is a bit more restrictive then the interface for the json module in the standard library.
=> Add stubs for ujson

stdlib/2and3/logging/__init__.pyi
Adds several attributes which were missing from the Logger types,
including "name", "level", and "parent". Because the type of "parent"
is a union of Logger and PlaceHolder, we also define types for
PlaceHolder and all of it's methods.
=> Adds logging PlaceHolder class and Logger attributes

stdlib/2.7/urllib2.pyi, stdlib/3/urllib/error.pyi
HTTPError had the superclass of addinfourl in Python 2.7 stub but not in Python 3.
=> Added attributes for URLError and HTTPError

stdlib/3/json.pyi
These two classes were missing from the  json.pyi typeshed.
I added it only for python 3 because I'm not sure what's the correct way to handle the str/unicode duality of the Python 2 version.
=> Adde JSON encoder and decoder objects

stdlib/2.7/typing.pyi, stdlib/3/typing.pyi
In Python, it's possible to use the `next` builtin method on file objects produced by `open`. (This is particularly useful when you want to do some pre-processing on header lines before looping over the rest of the file). This change modifies `typing.IO` so this usage will successfully typecheck.
=> Make typing.IO inherit Iterator, not Iterable

third_party/3/typed_ast/ast27.pyi
This pull request adds a missing attribute from the `ast27.arguments` class.
=> Add missing `type_comments` attr to ast27.arguments

third_party/2and3/ujson.pyi
The ujson module apparently will accept both bytes and text format
input, however, it does always output a str (both on Python 2 and
Python 3).
Some discussion in: https://github.com/python/typeshed/pull/460
=> Fix ujson stubs to properly use AnyStr.

stdlib/2.7/typing.pyi, stdlib/3/typing.pyi
=> Add signatures for cast() and NewType

stdlib/3/time.pyi
Several functions and constants were added to [time](https://docs.python.org/3.3/library/time.html) in Python 3.3. I've added the type signatures for the functions and constants here.
Most of the functions are Unix only, but I have not indicated them as such. Should they be?
Also, the `get_clock_info()` function returns a `types.SimpleNamespace` object. However its docstring says it returns a `dict`. So I annotated the type here as `Dict[str, Any]`.
```python
>>> import time
>>> time.get_clock_info('clock')
namespace(adjustable=False, implementation='clock()', monotonic=True, resolution=1e-06)
>>> type(time.get_clock_info('clock'))
<class 'types.SimpleNamespace'>
>>> vars(time.get_clock_info('clock'))
{'resolution': 1e-06, 'implementation': 'clock()', 'monotonic': True, 'adjustable': …
```
=> Include time updates with Python 3.3

stdlib/2.7/difflib.pyi, stdlib/3/difflib.pyi
SequenceMatcher(None, a, b) is valid, so need to use Optional[] around Callable[].
Docs: https://docs.python.org/2/library/difflib.html#sequencematcher-objects
=> Allow the first argument to SequenceMatcher.__init__ to be None.

stdlib/2and3/locale.pyi
There is no "builtins" in Python 2.
=> Use the correct __builtin__/builtins module in Python 2/3.

stdlib/3/http/__init__.pyi
Added http.HTTPStatus definition which was introduced in python3.5 (https://docs.python.org/3/library/http.html#http.HTTPStatus)
fixes #576
=> Add HTTPStatus definition for python3.5+

stdlib/3/ssl.pyi
- `_create_default_https_context`
- `_create_unverified_context`
See https://github.com/python/typeshed/issues/582
```
$ ./tests/mypy_test.py 
running mypy --python-version 3.5 --strict-optional # with 341 files
running mypy --python-version 3.4 --strict-optional # with 341 files
running mypy --python-version 3.3 --strict-optional # with 326 files
running mypy --python-version 3.2 --strict-optional # with 325 files
running mypy --python-version 2.7 --strict-optional # with 382 files
```
```
$ ./tests/pytype_test.py --num-parallel=4
Running pytype tests...
Ran pytype with 242 pyis, got 0 errors.
```
=> [waiting for author] New type hints for ssl module.

stdlib/3/shutil.pyi
`SameFileError`: https://docs.python.org/3/library/shutil.html#shutil.SameFileError
Introduced in 3.4.
```
$ ./tests/mypy_test.py 
running mypy --python-version 3.5 --strict-optional # with 341 files
running mypy --python-version 3.4 --strict-optional # with 341 files
running mypy --python-version 3.3 --strict-optional # with 326 files
running mypy --python-version 3.2 --strict-optional # with 325 files
running mypy --python-version 2.7 --strict-optional # with 382 files
```
```
$ ./tests/pytype_test.py 
Running pytype tests...
Ran pytype with 242 pyis, got 0 errors.
```
=> Add stub for SameFileError.

stdlib/3/multiprocessing/__init__.pyi
I'm not sure how to test stub files (does mypy download them automatically? I couldn't see anything in `mypy --help` about using stubs) so this is untested, but I'm aiming to fix this error:
```
$ cat test.py
import multiprocessing
multiprocessing.Pool()
$ mypy test.py
test.py:2: error: "module" has no attribute "Pool"
```
=> [review] Add multiprocessing.Pool

stdlib/2.7/itertools.pyi, stdlib/3/itertools.pyi
`stop` parameter to `islice` can be `None`,
which is important when checking with --strict-optional
=> Improve `itertools.islice` type

stdlib/3/select.pyi
The original type definition was incorrect, because `select.select` doesn't return a tuple of lists of integers, it returns a tuple of subsets of the sequences provided as arguments. I wasn't sure how to handle that case (the documentation isn't explicit on all the kinds of objects allowed in the sequence, but mentions sockets and file descriptors. It also says custom wrapper classes are allowed as long as they define a `fileno` method), so I made it have a definition of type Any. 
Would it be more appropriate to have a Union type of the socket and file descriptor return values?
=> Allow Any in the tuple of lists returned by select

third_party/2and3/mypy_extensions.pyi
Supports pending PR https://github.com/python/mypy/pull/2206 .
=> [discussing] Add mypy_extensions.

stdlib/2.7/os/__init__.pyi, stdlib/3/os/__init__.pyi, tests/pytype_blacklist.txt
`os/` is a package, hence we don't need to declare `path` in `__init__.pyi`
for mypy or pytype to find `os/path.pyi`.
=> change 'path' import syntax

stdlib/3/concurrent/futures/_base.pyi
According to the doc for `concurrent.futures.wait`:
> Returns a named 2-tuple of sets. The first set, named done, contains the futures that completed (finished or were cancelled) before the wait completed. The second set, named not_done, contains uncompleted futures.
Here's my use case:
```
with ThreadPoolExecutor(threads) as e:
running = set()  # type: Set[Future]
while True:
while len(running) < threads:
future = e.submit(func)
running.add(future)
done, running = wait(running, return_when=FIRST_COMPLETED)
```
Mypy reports an error in the last line: `Incompatible types in assignment (expression has type Iterable[Future[Any]], variable has type Set[Future[Any]])`. This PR should fix that.
=> Improve concurrent.futures.wait function stub

stdlib/3/_importlib_modulespec.pyi, stdlib/3/importlib/abc.pyi
Added `from abc import ABCMeta` in importlib.
This change is needed for [mypy/#2365](https://github.com/python/mypy/pull/2365).
=> Direct import for metaclass ABCMeta

stdlib/3.4/asyncio/tasks.pyi
It returns a concurrent.futures.Future, not an asyncio.Future. (Admittedly a subtle distinction, but an important one!)
=> Fix signature of run_coroutine_threadsafe()

stdlib/3/collections/abc.pyi
[Abstract base classes have been moved in a `collections.abc` module since Python 3.3.][1]
[1]: https://docs.python.org/3.3/whatsnew/3.3.html#collections
=> Stubs for collections.abc module

stdlib/3.4/asyncio/__init__.pyi, stdlib/3.4/asyncio/futures.pyi, stdlib/3.4/asyncio/tasks.pyi
asyncio.wait for() should also accept Awaitable[_T] in the same way as asyncio.gather() does.
Maybe asyncio,ensure_future() needs to be fixed too. I didn't change it since my code did not fail there.
The asyncio.{Cancelled,Timeout,InvalidState}Error types are missing. I got the types from concurrent.futures as the implementation does - hope this is correct.
=> Fix asyncio.wait for() and missing asyncio.{Cancelled,Timeout,InvalidState}Error types

stdlib/3/typing.pyi
Awaitable is the return value, not the yielded value.
=> Fix AwaitableGenerator inheritance

stdlib/3/collections/abc.pyi
[`MutableSet`][1] is a mutable version of [`Set`][2].
[1]: https://docs.python.org/3/library/collections.abc.html#collections.abc.MutableSet
[2]: https://docs.python.org/3/library/collections.abc.html#collections.abc.Set
=> Add missing MutableSet abstract base class

stdlib/3/os/__init__.pyi
This isn't entirely correct because adding the fields should be conditional on 3.3 or later (http://bugs.python.org/issue14127). Is there a way to do that without repeating the entire stat_result definition?
=> Add ns accurate times in os.stat_result

stdlib/3/multiprocessing/__init__.pyi, stdlib/3/multiprocessing/pool.pyi
1. Fix type declarations for multiprocessing.pool.ThreadPool
The existing incomplete type declarations were replaced by a copy of
multiprocessing.Pool's declarations, suitably modified.
Fixes #683.
2. Change iterable type to Iterable[Iterable[Any]] in starmap
=> Multiprocessing fixes

stdlib/2and3/tarfile.pyi
Allows this example from the [Python documentation](https://docs.python.org/3/library/tarfile.html#examples) to type check:
```python
import tarfile
tar = tarfile.open("sample.tar.gz", "r:gz")
for tarinfo in tar:
print(tarinfo.name, "is", tarinfo.size, "bytes in size and is", end="")
if tarinfo.isreg():
print("a regular file.")
elif tarinfo.isdir():
print("a directory.")
else:
print("something else.")
tar.close()
```
=> Add Iterable base class to tarfile.TarFile

stdlib/2/collections.pyi
Rebasing and fixing the Werkzeug PR.
=> Add MutableSet to collections

third_party/2and3/pytz/__init__.pyi
pytz shadows UTC after declaring it with a singleton:
https://github.com/newvem/pytz/blob/master/pytz/__init__.py#L135
This fixes https://github.com/python/typeshed/issues/710
=> Expose pytz.UTC as an instance as opposed to as a class

stdlib/2and3/logging/__init__.pyi, stdlib/3/time.pyi
Fixes #720.
Related changes: used a NamedTuple for time.struct_time on Python 3, used
sys.version selectors for proper typing of #716, added missing *Style classes
to logging on Python 3.
=> logging.Formatter attributes fixed

stdlib/2/__builtin__.pyi, stdlib/3/builtins.pyi
This fixes the problem that a function like this:
def f(fs):
fs = frozenset(['a'])
would result in an error like this:
frozenset.py: note: In function "f":
frozenset.py:5: error: Incompatible types in assignment (expression has type frozenset[str], variable has type FrozenSet[str])
Originally reported at python/mypy#2514
=> Have frozenset inherit from FrozenSet

stdlib/3/urllib/parse.pyi
The implementation of this function calls str() on all arguments, so it accepts
any object (https://hg.python.org/cpython/file/3.5/Lib/urllib/parse.py#l801).
This was discussed on the mypy gitter chat.
=> urlencode: change parameters to Any instead of AnyStr

third_party/2/concurrent/futures/__init__.pyi
this fixes issue #538 
I looked more at the [documentation](https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.ProcessPoolExecutor) and found that you can initialize `ProcessPoolExecutor` with an int, None, or nothing at all, as shown in the below code that runs in python 2.7.
```
from concurrent.futures import ProcessPoolExecutor
test = ProcessPoolExecutor()
test2 = ProcessPoolExecutor(4)
test3 = ProcessPoolExecutor(None)
```
Before this fix, when running mypy with the --py2 flag, I got these errors:
```
test_concurrent.py:3: error: Too few arguments for "ProcessPoolExecutor"
test_concurrent.py:4: error: Argument 1 to "ProcessPoolExecutor" has incompatible type "int"; expected None
```
With this fix, the above code is now valid and it runs fine on python2.7.
=> #538 fixing concurrent.futures.ProcessPoolExecutor

stdlib/2and3/mimetypes.pyi
This issue fixes the bug in mimetypes for python2 referenced in #559
=> fixes #559

stdlib/2/json.pyi
=> Make object_hook of json.load and json.loads optional (Python 2)

stdlib/3/subprocess.pyi
setting the stdout attribute of CompletedProcess to be of type Any as mentioned in #581
=> set subprocess stdout to be type Any (#581)

stdlib/2/calendar.pyi, stdlib/3/calendar.pyi
Fixes #692
The calendar stub is not in 2and3 but has duplicates in 2 and 3, so I updated both.
As far as I can understand, the right type for those is Sequence (implements __len__ and __getitem__).
=> add calendar data attributes

stdlib/3/subprocess.pyi
@JukkaL this is a follow up to #761 and changes the return of subprocess `stderr` to be Any.
=> updating stderr to return type Any

stdlib/3/unittest/__init__.pyi
=> Correct return value type for TestRunner.run

third_party/3/dateutil/relativedelta.pyi
Improve operator methods for `dateutil.relativedelta` stubs:
* `__add__` operator method could return other types than `relativedelta` (`datetime.date` or `datetime.datetime`)
* use specific types of operators args instead of `Any`
* mypy currently does not handle `Union` in op methods (see python/mypy#2129, python/mypy#1442, python/mypy#1264 for details), so I've overloaded it directly
=> Use specific types in dateutil.relativedelta stubs

stdlib/2and3/plistlib.pyi, stdlib/3/unittest/__init__.pyi
Reverts python/typeshed#804
Reason: until https://github.com/python/mypy/issues/1551 is fixed this gives an error whenever `@skip()` is used.
=> Revert "Make all single-constraint TypeVars to use bounds"

stdlib/3.4/asyncio/events.pyi
create_future, create_task, set_task_factory, get_task_factory
=> AbstractEventLoop missing methods from 3.4.2 and up. 

stdlib/3/urllib/parse.pyi
- fix Too many arguments error
The following block is valid:
```python
from urllib.parse import SplitResult
print(SplitResult('http', 'host', 'api', '', ''))
```
however,`mypy` results in:
`error: Too many arguments for "SplitResult"`
Using `NamedTuple` is roughly similar to how py2 stubs are defined.
I have also noticed an issue with `urlunsplit` and `urlunparse` stubs, but not sure how to fix them.
`mypy` won't complain about the following block, but it will fail in runtime
```python
from urllib.parse import urlunsplit
print(urlunsplit(('http', 'host')))
```
Fails in runtime with:
`ValueError: not enough values to unpack (expected 6, got 3)`
The problem is the stubs are defined to accept `Sequence`, which doesn't enforce strict check for the args, and actually overrides the more strict …
=> Fix SplitResult and ParseResult stubs

stdlib/3/configparser.pyi
The corresponding line is already present in the Python 2 ConfigParser stubs.
Upstream docs: https://docs.python.org/3/library/configparser.html#configparser.ConfigParser.items
Source: https://github.com/python/cpython/blob/master/Lib/configparser.py#L828
=> RawConfigParser.items

stdlib/3/calendar.pyi
Fix for:
```python
timegm(time.strptime('2017-01-01 10:00:00', '%Y-%m-%d %H:%M:%S'))
```
Only needed in `3` stub.
=> Make calendar.timegm stub accept struct_time

stdlib/2/unittest.pyi
The python2 unittest `assertIsInstance` and `assertNotIsInstance` stub
did not allow using a tuple of classes, but that behavior is [in the
documentation][1]. This commit copies the type stub for the isinstance
built-in to the stubs for `assertIsInstance` and `assertNotIsInstance`
I made this commit in response to @gvanrossum's request in
python/typeshed#802 (which fixed this issue for python 3) that I apply
the same fix to python 2.
[1]: https://docs.python.org/2.7/library/unittest.html#unittest.TestCase.assertNotIsInstance
=> Match python2 assert*IsInstance signatures with isinstance

stdlib/2/wsgiref/types.pyi, stdlib/3/wsgiref/types.pyi
Fix a bug I introduced when attempting to clean up #825.
=> Remove trailing commas, pytype doesn't like them

stdlib/2/UserDict.pyi
This fixes MRO conflicts produced by mypy when using multiple
inheritance.
=> Make MRO of UserDict.DictMixin consistent with Mapping

stdlib/2and3/argparse.pyi
Change `str` to `Union[str, unicode]` where it seems safe.
I didn't change it in non-covariant contexts since that can
break user code.
I manually verified a subset of the changes by calling the
relevant function with unicode literals (ascii-only).
I'm using `Union[str, unicode]` instead of just `unicode`
so that the stub still works with tools that don't promote
`str` objects to `unicode`.
=> Update argparse to accept unicode in many contexts

third_party/2/requests/api.pyi, third_party/3/requests/api.pyi
Due to `Dict` / `Mapping` type invariance it's necessary to include other variants of `Union[str, bytes], Union[str, bytes]`. Also I changed from `Dict` to `Mapping` as `requests` should not modify passed mapping
=> Expansion of unions inside `params` definition

stdlib/3/os/__init__.pyi
This PR adds a stub for `os.get_terminal_size`. A quick search on the [typeshed repo](https://github.com/python/typeshed/search?utf8=%E2%9C%93&q=get_terminal_size) shows that its currently missing. The API has been available [since 3.3](https://docs.python.org/3/library/os.html#os.get_terminal_size).
Notice that the function actually returns `os.terminal_size`, a subclass of `Tuple`, but I wasn't sure if that should be stubbed out, too or if the simple `Tuple[int, int]` was enough. Let me know and I'll make changes accordingly.
=> add stub for os.get_terminal_size in python3

stdlib/2/codecs.pyi, stdlib/3/codecs.pyi
This prevents false alarms like:
```
"IncrementalEncoder" has no attribute "decode"; maybe "encode"?
```
=> Fix returned decoder/encoder types in codecs

stdlib/3.4/asyncio/subprocess.pyi
The code for this method starts as follows:
```
@coroutine
def communicate(self, input=None):
if input is not None:
stdin = self._feed_stdin(input)
```
=> input argument to Process.communicate is Optional

stdlib/2/typing.pyi, stdlib/3/typing.pyi
=> Add typing.ClassVar (fixes #888)

stdlib/3/subprocess.pyi
- The stdout and stderr arguments are optional and default to None.
- args can be any sequence that was passed in to run(), but it is always a sequence of strings. (Actually it seems like it can also be bytes, but I'd prefer to change that in another PR since it would affect a bunch of other functions in this module.)
- The stdout and stderr attributes of CompletedProcess are the same type as the constructor arguments.
For reference: https://github.com/python/cpython/blob/master/Lib/subprocess.py#L339
```
In [32]: subprocess.run(('true',))
Out[32]: CompletedProcess(args=('true',), returncode=0)
In [33]: cp = subprocess.run(('true',))
In [34]: cp.args
Out[34]: ('true',)
In [35]: cp.stdout
In [36]: cp.stderr
In [37]: cp.returncode
Out[37]: 0
```
=> Fixes to subprocess.CompletedProcess

third_party/2/six/__init__.pyi
This PR updates the type stub for `six.string_types` to `(Union[str, unicode], )`. This is _technically_ inaccurate, since `six.string_types[0] is basestring`, but as @JukkaL pointed out [here](https://github.com/python/typeshed/pull/138#issuecomment-219526689), expressing `basestring` as a union better expresses its semantics. 
While the caveats raised in #138 are valid, I think none of them apply to the six stub, since `text_type` already does not mention `basestring`.  See also https://github.com/python/mypy/issues/1537
```
$ cat getattr_six.py 
import six
from typing import Any
def c(a, b):  # type: (Any, Any) -> int
if isinstance(a, six.string_types):
return getattr(b, a)
else:
return b[a]
$ mypy --py2 getattr_six.py --custom-typeshed-dir=/Users/lucaswiman/opensource/typeshed
$ mypy …
```
=> Update type of six.string_types to Union[str, unicode]

stdlib/3.4/asyncio/streams.pyi
According to [`asyncio.start_server` doc](https://docs.python.org/3/library/asyncio-stream.html#asyncio.start_server)
> The client_connected_cb parameter is called with two parameters: client_reader, client_writer. client_reader is a StreamReader object, while client_writer is a StreamWriter object. The client_connected_cb parameter can either be a plain callback function or a coroutine function; [...].
With this change the following code passes.
```
import asyncio
MSG = b'hello'
def f1(reader: asyncio.StreamReader,
writer: asyncio.StreamWriter):
writer.write(MSG)
@asyncio.coroutine
def f2(reader: asyncio.StreamReader,
writer: asyncio.StreamWriter):
writer.write(MSG)
yield from writer.drain()
async def f3(reader: asyncio.StreamReader,
writer: asyncio.StreamWriter):
writer.write(MSG)
await …
```
=> Fix ClientConnectedCallback in asyncio.stream

stdlib/2/time.pyi
asctime and strftime take either a time.struct_time or a tuple of nine elements.
=> asctime/strftime take a tuple, too

stdlib/2/typing.pyi, stdlib/3/typing.pyi
From https://github.com/python/typing/pull/366, cc @ilevkivskyi. Deque was missing too; it was added to typing recently.
This will presumably also need some changes in mypy and pytype; I'll work on mypy next.
=> add Counter, Deque, ChainMap

third_party/3.6/click/decorators.pyi
Relevant code in click: https://github.com/pallets/click/blob/6.7/click/decorators.py#L225-L240
Example of failure: https://travis-ci.org/samuelcolvin/arq/jobs/207122505
=> correct version_option arguments in click

README.md, tests/mypy_test.py
It's now on by default, and the flag will eventually be removed.
=> Remove unnecessary --fast-parser flag to mypy

stdlib/3/urllib/response.pyi
`urllib.response.addinfourl` has several attributes.  Although these are undocumented, [many people][1] [have used][2] [it.][3]
[1]: https://github.com/search?utf8=%E2%9C%93&q=urlopen+resp.url+language%3Apython&type=Code&ref=searchresults
[2]: https://github.com/search?utf8=%E2%9C%93&q=urlopen%28%29.headers+language%3Apython&type=Code&ref=searchresults
[3]: https://github.com/search?utf8=%E2%9C%93&q=urlopen%28%29.code+language%3Apython&type=Code&ref=searchresults
=> Add missing attributes to urllib.response.addinfourl

CONTRIBUTING.md
I've seen some stubs like
```
class X:
def __init__(self, x: str) -> None:
self.x = x
self.y = 0
```
I think this should be written instead as
```
class X:
x: str
y: int
def __init__(self, x: str) -> None: ...
```
If the first style is preferred we should mention that in `CONTRIBUTING` instead.
=> Function bodies should be empty

stdlib/3/builtins.pyi
Otherwise mypy complains about ``MyClass.__annotations__`` etc.
(this is also necessary to typecheck mypy tests)
=> Add __annotations__ to Python 3

stdlib/3/subprocess.pyi, third_party/3.6/click/core.pyi, third_party/3.6/click/exceptions.pyi, third_party/3.6/click/formatting.pyi, third_party/3.6/click/parser.pyi, third_party/3.6/click/types.pyi, third_party/3.6/click/utils.pyi
* Fix click annotation syntax.
* Add the errors and encoding keyword argument to run and Popen in subprocess, those were added in python 3.6
=> Fix click annotation syntax and add missing keyword arguments to subprocess (new in 3.76)

stdlib/3/unittest/__init__.pyi
These are needed for a mypy PR that I'm preparing.
=> Fixes to unittest stubs

stdlib/2and3/tty.pyi
Adds Python 2 and 3 stubs for `tty` module.  Addresses one of the missing stubs mentioned in #1019.
=> Stub for tty

stdlib/2/unittest.pyi, stdlib/3/unittest/__init__.pyi
This declares the method to take the union of Set and FrozenSet rather than AbstractSet since that is where `difference()` (used by `assertSetEqual()`) is defined.
=> TestCase.assertSetEqual() should accept frozenset

stdlib/2/itertools.pyi
Add fallback for `itertools.izip`. Continuation of https://github.com/python/typeshed/pull/1042.
=> Add n-ary stub for `itertools.izip`

third_party/2and3/sqlalchemy/engine/interfaces.pyi
This isn't needed in typeshed, since the stubs aren't executed.
=> remove `if TYPE_CHECKING` in sqlalchemy stub

stdlib/2/select.pyi, stdlib/3/select.pyi
The TypeVars allow mypy to enforce that the returned lists are subsets of the arguments.
=> Improved annotations for select.select()

stdlib/2/subprocess.pyi, stdlib/3/subprocess.pyi
This adds union types in the constructor to account for parameters that
might be either byte strings or unicode strings. At the same time, this
*removes* specific types from the user-accessible fields, to avoid the
need for users to at every use site specify which types their particular
instance was instantiated with.
Fixes #1004
=> Improve types for subprocess module

stdlib/2/select.pyi, stdlib/3/select.pyi
This reverts commit 7e05d47b81316230b374fb9945430b880f3e77fc.
See discussion at https://github.com/python/typeshed/pull/1080
=> Revert "Improved annotations for select.select() (#1080)"

stdlib/3/subprocess.pyi
Python 3.6 introduced a new parameter to function subprocess.check_output(). Added support for it.
=> add encoding parameter for subprocess.check_output() function in Python 3.6+

third_party/3.6/click/decorators.pyi
This fixes the false positive with the following:
```python
class FooGroup(click.Group):
def __init__(self, msg, *args, **kwargs):
super().__init__(*args, **kwargs)
self.message = msg
@click.group(cls=FooGroup, msg='OK')
def cli():
pass
```
That, while still raising errors for regular arguments:
```python
@click.group(cls='Unexpected string', msg='OK')
def cli():
pass
```
```
test.py:10: error: Argument 1 to "group" has incompatible type "str"; expected "type"
```
=> Allow user-defined kwargs being passed to click.group

stdlib/3.4/asyncio/events.pyi
Looks like `create_server` and `create_datagram_endpoint` have supported `reuse_port`, `reuse_address`, and `sock` since 3.4.
https://docs.python.org/3.4/library/asyncio-eventloop.html
https://github.com/python/cpython/blob/ee51327a2329eb9c2bfbb6ea673cfab4299450b0/Lib/asyncio/events.py
=> Add missing kwargs for create_server and create_datagram_endpoint

stdlib/2/os/__init__.pyi, stdlib/3/os/__init__.pyi
The elements can be accessed as indexes or through attributes, so I chose to make them NamedTuples.
=> Make os.stat_result and friends NamedTuples

stdlib/2/types.pyi
(It's a type alias for int anyway, and it will cause a problem in the
initial import cycle once #886 is merged.)
=> Don't reference long in types.pyi

stdlib/3.4/asyncio/__init__.pyi
`async` is still present in 3.6 and `ensure_future` doesn't exist before 3.4.4
=> Add an alias for `ensure_future` as `async`

stdlib/3.4/enum.pyi
Fixes python/mypy#2305.
Example:
```
import enum
class Colors(enum.Enum):
RED = 0
BLUE = 1
print([color.name for color in Colors])  # This used to fail, now it works
```
(I found this unfinished project. Maybe it was waiting for some mypy improvement, or maybe I got distracted. Anyway, it seems to work now.)
=> Support enum iteration

stdlib/3.4/enum.pyi
See https://github.com/python/typeshed/pull/1136#discussion_r109727053
=> Use a separate type variable for unique()

stdlib/3.4/enum.pyi
Test with mypy:
```shell
$ cat ../bin/enumops.py 
import enum
class Foo(enum.Enum):
a = 1
b = 2
reveal_type(list(Foo))
reveal_type(Foo['a'])
reveal_type(Foo.a in Foo)
reveal_type(len(Foo))
$ mypy --custom-typeshed-dir . ../bin/enumops.py 
../bin/enumops.py:7: error: Revealed type is 'builtins.list[enum.Enum*]'
../bin/enumops.py:8: error: Revealed type is 'enumops.Foo'
../bin/enumops.py:9: error: Revealed type is 'builtins.bool'
../bin/enumops.py:10: error: Revealed type is 'builtins.int'
```
=> make enums support len()

stdlib/2and3/opcode.pyi
Fixes `error: Value of type "ellipsis" is not indexable` when trying to index into `opcode.opmap`.
=> Fix missing 'type: ' in opcode.pyi

.flake8, .gitignore, README.md, requirements-tests-py3.txt, runtests.sh
- Switch requirements-tests-py3.txt to use mypy GitHub master.
- Exclude .venv{2,3} (suggested in README.md) in .flake8 and .gitignore.
- Update instructions in README.md to be working.
- Remove runtests.sh script and mentions of it -- I can't get it to work
and the three steps are easily run by hand.
=> Update configs and instructions for running tests manually.

stdlib/3.4/asyncio/subprocess.pyi
Add typehints for the following `asyncio.subprocess.Process` attributes:
- `stdin`: `Optional[asyncio.streams.StreamWriter]`
- `stdout`: `Optional[asyncio.streams.StreamReader]`
- `stderr`: `Optional[asyncio.streams.StreamReader]`
- `pid`: `int`
=> Add missing attributes: asyncio.subprocess.Process

stdlib/2/_warnings.pyi, stdlib/3/_warnings.pyi
CPython _warnings module implementation accepts Warning subclasses and None, but not any subclass of BaseException
specified in the stub. The stub for warnings is correct.
=> Require warning categories to be subclasses of Warning (#343)

stdlib/2/macpath.pyi, stdlib/2/ntpath.pyi, stdlib/2/os2emxpath.pyi
Stubs are just soft links to posixpath.pyi, since the interfaces are identical.
=> Add stubs for *path.pyi in Python 2.7 stdlib

stdlib/3/macpath.pyi, stdlib/3/ntpath.pyi
Similar to #1166 but for python 3.
=> Add stubs for *path.pyi in Python 3 stdlib

stdlib/3/sqlite3/dbapi2.pyi
Read about the change [documented here](https://docs.python.org/3/library/sqlite3.html#sqlite3.connect).
The C code that implements it is [here](https://github.com/python/cpython/blob/3.4/Modules/_sqlite/module.c#L53-L72).
=> Add uri param for sqlite3.connect (Python 3.4+)

stdlib/3/collections/__init__.pyi, stdlib/3/collections/abc.pyi
This was missing for some reason. I'm pretty sure it needs to be added under the `>=3.6` section since it appears to have been added in 3.6.
=> Add collections.abc.Collection

stdlib/3/os/__init__.pyi, stdlib/3/os/path.pyi
- Add support for PathLike to _PathType for Python 3.6 Unions only
=> Support Python 3.6 PathLike Objects

stdlib/2and3/mmap.pyi
Fixes #1184 
The class doesn't actually support Container or Reversible, so I removed those base classes. It is in fact iterable, so I added `__iter__` to the class although it technically supports iteration only through the old `__getitem__`/`__len__` route.
=> fix parent classes of mmap

stdlib/3/abc.pyi
Fixes #304 
Also made the @abstractmethod stub slightly more meaningful. (It doesn't matter to mypy.)
=> add some missing names to abc.pyi

stdlib/2and3/cgi.pyi, stdlib/2and3/copy.pyi, stdlib/2and3/hmac.pyi
=> add some missing constants

stdlib/3.4/enum.pyi
Fixes #854 (unless there's more I'm missing).
Tested with this file:
```python
import enum
class A(enum.Enum):
b = 1
c = 2
reveal_type(reversed(A))
reveal_type(A.b in A)
reveal_type(A['a'])
reveal_type(A.__members__)
```
With mypy master this produces:
```
../bin/enum36.py:7: error: Revealed type is 'typing.Iterator[enum.Enum*]'
../bin/enum36.py:8: error: Revealed type is 'builtins.bool'
../bin/enum36.py:9: error: Revealed type is 'enum36.A'
../bin/enum36.py:10: error: Revealed type is 'typing.Mapping[builtins.str, enum36.A*]'
../bin/enum36.py:10: error: Invalid method type
```
The first line should be `Iterator[A]` but that's due to python/mypy#3210, and the last error is wrong but that's due to python/mypy#3223.
=> Add missing enum attributes

third_party/3/lxml/etree.pyi
Naming the alias "AnyStr" isn't a great idea since AnyStr normally means
the typevar.
Also removed some whitespace in accordance with typeshed style.
=> make type aliases in lxml.etree private

stdlib/2/collections.pyi, stdlib/3/collections/__init__.pyi
Fixes #709
I looked at dir(collections) in 2.7 and 3.6 and made sure the list of names matched the stubs.
=> review exported names in collections stubs

stdlib/3/hashlib.pyi
- Use `iterations` instead of `rounds` if running on 3.5
- Change `dklen` to `Optional`
Python 3.5 source:
https://github.com/python/cpython/blob/3626a505dbffc5539888bfdb596dc20560f0d2a1/Lib/hashlib.py#L157
=> Update pbkdf2_hmac argument names for 3.4+

tests/pytype_blacklist.txt, tests/pytype_test.py
For reasons I don't remember, we've only been running pytype on the Python 2 sources (`stdlib/2`). Now that we're looking into Python 3 compatibility more earnestly, let's also run pytype on `stdlib/3*`.
=> also run pytype tests for Python 3 modules

CONTRIBUTING.md
Mypy, pytype, and PyCharm now all allow variable annotations in stubs; I think we already have some.
=> allow PEP 526-style annotations in all stubs

CONTRIBUTING.md
This is fairly self-explanatory. Simply adds information on how the directory structure is used to target Python versions along with an extension of the existing best practices for which directory to put stubs in.
=> Add description of how the directory structure targets Python versions.

tests/mypy_test.py
This fixes the mypy_test by removing 3.2, as MyPy does not support this version.
=> Removes MyPy test for Python 3.2, as support for 3.2 has been removed.

stdlib/3/os/__init__.pyi
Also fixed the type for the `onerror` argument.
=> os.walk allows PathLike

stdlib/3/inspect.pyi
Compare https://docs.python.org/3.5/library/inspect.html#inspect.getmoduleinfo
and https://docs.python.org/3.6/library/inspect.html
=> inspect.getmoduleinfo was removed in 3.6

stdlib/3/importlib/__init__.pyi
at `typeshed/stdlib/3/importlib/__init__.pyi` added `from importlib import util` as it was missing.
=> add from importlib import util

stdlib/3/http/client.pyi
=> add http.client.error

stdlib/2and3/distutils/core.pyi
- add include_package_data (which setuptools accepts)
- allow arbitrary other kwargs, because distutils.core.setup allows arbitrary kwargs and just passes them through to commands
=> distutils.core.setup fixes

stdlib/2/unittest.pyi
Optionally, we could move ``unittest`` module to ``2and3``, but I think it would mean adding a whole lot of conditionals, which may make it too unreadable.
=> Fix unittest.main() parameters.

stdlib/3.4/enum.pyi
Full context: https://github.com/python/mypy/issues/3434
This diff is needed to properly exercise enum.auto when type-checking. Otherwise, enum.auto just renders out to Any().
The attached issue, along with the proposed changes here https://github.com/python/mypy/pull/3441 would suggest a proper method for testing this precise feature.
=> Completing functionality for enum.auto

stdlib/2/typing.pyi, stdlib/3/typing.pyi
Signature for `get_type_hints` function looks like `obj, globalns=None, localns=None`
=> Fix type stubs in typing.pyi

third_party/2and3/ujson.pyi
Fixes #1332 
```
>>> import ujson
>>> ujson.dumps({"float": 0.123456789}, double_precision=3)
'{"float":0.123}'
>>> ujson.dumps({"float": 0.123456789}, double_precision=3.4)
TypeError: integer argument expected, got float
```
=> Fix stub for ujson

stdlib/2and3/logging/__init__.pyi
Loggers accept any exceptions as the exc_info argument, not only Exception subclasses.
=> Made Logger methods accept BaseExceptions for exc_info

stdlib/2/subprocess.pyi, stdlib/3/subprocess.pyi
- Adding Optional to _FILE for stderr + stdout arguments to subprocess functions
- Sometimes you might want subprocess commands to be quiet and other time print the output
Example Code: https://pastebin.com/Ebr9qbch
=> Allow subprocess stdout + stderr to be Optional

stdlib/2and3/contextlib.pyi
Since ContextManager inherits from Generic, too, listing Generic first, in the list of base classes, results in a cyclic MRO.
=> switch order of ContextManager and Generic

third_party/2and3/click/decorators.pyi
`click.option` creates `Option` instance which is a subclass of `Parameter` https://github.com/pallets/click/blob/master/click/core.py#L1477
As `Parameter` supports `required` so do `Option`.
=> Add required to click.option decorator

stdlib/2and3/tarfile.pyi
- Many methods allow PathLike objects in Python 3.6
- Update type for path from `str` to ~`AnyStr`~ `Union[str, unicode]` in Python 2 or `Union[bytes, str]` in Python 3
=> Update stub for tarfile

stdlib/2/itertools.pyi, stdlib/3/itertools.pyi
This fixes typechecking of code like e.g.
```
import itertools
itertools.product([1], [u""])
```
which currently reports a type error.
=> make itertools.product more precise

third_party/2/enum.pyi
This PR's goal is to support the following in python 2:
```py
from enum import Enum
class Colors(Enum):
RED = 0
BLUE = 1
for color in Colors:
print(color.name)
```
Iteration over enums in python3 was supported in different [PR](https://github.com/python/typeshed/pull/1136). (this PR is pretty much a copy of the python 3 one)
=> Support iteration over enums with enum34

stdlib/3/multiprocessing/context.pyi, stdlib/3/multiprocessing/managers.pyi, stdlib/3/multiprocessing/pool.pyi
This will enable passing lambda expressions as init functions:
```
import signal
from multiprocessing import Manager
m = Manager()
m.start(lambda: signal.signal(signal.SIGINT, signal.SIG_IGN))
test.py:6: error: Argument 1 to "start" of "BaseManager" has incompatible type Callable[[], Union[Callable[[Signals, FrameType], None], int, Handlers]]; expected Callable[..., None]
```
=> Allow passing lambdas as init arguments in multiprocessing

stdlib/2/datetime.pyi
datetime_tz subclasses datetime.datetime and overrides __new__ (https://github.com/mithro/python-datetime-tz/blob/master/datetime_tz/__init__.py#L415), so for pytype to analyze datetime_tz correctly, datetime.datetime.__new__ needs to be in the pyi file.
=> Add a __new__ method to datetime.datetime.

stdlib/3/typing.pyi
Fixes #1396.
As requested in the issue #1396, here's an example demonstrating how the current stub is wrong:
```py
import asyncio
from typing import AsyncIterable
async def aproduce() -> AsyncIterable[int]:
for i in range(10):
yield i
class MyAsyncIterable(AsyncIterable[int]):
def __aiter__(self) -> AsyncIterable[int]:
print('PYTHON async for CALLED __aiter__')
return aproduce()
async def aconsume() -> None:
consumed = []
async for i in MyAsyncIterable():
consumed.append(i)
assert consumed == list(range(10))
if __name__ == '__main__':
loop = asyncio.get_event_loop()
loop.run_until_complete(aconsume())
```
When executed using CPython 3.6.1 it works, but `mypy` generates the failure:
```
t.py:19: error: Cannot instantiate abstract class 'MyAsyncIterable' with abstract attribute '__anext__' …
```
=> Typing.AsyncIterable should have __aiter__, not __anext__

stdlib/3/_importlib_modulespec.pyi
I'm sure there are many more like this, but this one drew my attention (maybe because it's part of the initial import cycle).
=> Use explicit Optional[] on argument types with default None

stdlib/3/subprocess.pyi
According to https://github.com/python/cpython/blob/master/Lib/subprocess.py#L374 timeout and input are Optional but they are not marked as such in the stubs.
=> [subprocess.run] Make timeout and input optional

stdlib/2/os/__init__.pyi, stdlib/3/os/__init__.pyi
And fix some TODOs.
This will help me check these stubs with my stubcheck tool, and is better for consistency anyway.
Part of #1427.
=> use PEP 526-style annotations in os stubs

third_party/3/typed_ast/ast27.pyi
Field `n` should be a `Union[int, float, complex]`, not just `Union[int, float]`.
=> Update Num stub for typed_ast 2.7

stdlib/2and3/numbers.pyi
This contradicts CPython, in `Lib/numbers.py`, because `Real` does not
actually inherit from `SupportsFloat`. But it suppresses errors from
mypy when passing sub-classes like `fractions.Fraction` to `float()`.
=> Indicate that `float()` accepts `Real` objects

stdlib/2and3/contextlib.pyi, stdlib/3/typing.pyi
Implements:
- https://github.com/python/typing/pull/438
- https://github.com/python/cpython/pull/360
https://github.com/python/cpython/pull/1412, which adds
contextlib.AbstractAsyncContextManager, has not yet been merged.
cc @ilevkivskyi
=> add typing.AsyncContextManager and contextlib.asynccontextmanager

stdlib/2and3/csv.pyi
Upgrading typeshed broke some of our code that was using `DictReader` and `unicode_literals`
=> Allow `csv` module to support both `str` and `unicode` types in Python 2

stdlib/2/types.pyi, stdlib/3/types.pyi
See https://github.com/python/cpython/blob/08c16016e2a2d1368d001ddebfe9ca92465773c4/Lib/types.py#L32-L34
```python
>>> class _C:
...     def _m(self): pass
...
>>> _C()._m.__name__
'_m'
```
=> Add __name__ field to MethodType

stdlib/3/os/__init__.pyi, stdlib/3/posix.pyi
`os.uname` changed in version 3.3: Return type changed from a tuple to
a tuple-like object with named attributes.
=> Support named attributes in `os.uname()` result

stdlib/2/user.pyi
Related to: https://github.com/python/typeshed/issues/1147
=> Added stub for user module

stdlib/2/typing.pyi, stdlib/3/typing.pyi
Fixes https://github.com/python/mypy/issues/2986
This is a simplest fix, and all other fixes will require complicated manual loading of ``collections`` (since it contains the actual class definitions for ``DefaultDict``, ``Deque`` etc).
The problem is that if ``collections`` are not in checked modules, then ``DefaultDict``, ``Deque`` etc. are automatically translated to ``Any`` thus potentially hiding some errors, see https://github.com/python/mypy/issues/2986 for an example.
=> Add collections import in typing for type aliases to always work

README.md
This documents, among others, the `unicode -> Union[bytes, unicode]` promotion that https://github.com/python/peps/pull/302 removes from PEP 484.
=> Add "conventions" section to README.md

stdlib/2/typing.pyi, stdlib/3/typing.pyi
The `NoReturn` type is in PEP 484 and in the actual typing module, so should probably exist in the typing stubs.
I copied the definition and comment from `mypy_extensions.pyi`.
=> Add NoReturn type to typing stubs

third_party/2and3/typing_extensions.pyi
This pull request adds stubs for the [`typing_extensions` module](https://github.com/python/typing/pull/443). The module is currently being reviewed, but its contents are mostly finalized at this point so I figured I might as well make this pull request now.
=> Add stubs for typing_extensions module

stdlib/2/fcntl.pyi, stdlib/2/io.pyi
This used to cause TextIOBase to subclass both BinaryIO and TextIO, even
though those two are incompatible.
=> Remove subclass IOBase from TextIOBase.

third_party/2/simplejson/__init__.pyi
Re-export these values, so that you can use them as `simplejson.JSONDecoder`, for example.
See #1515
=> Re-export values for simplejson library

.flake8
This commit disables following flake8 errors:
* F403: `‘from module import *’ used; unable to detect undefined names`
* F405: `name may be undefined, or defined from star imports: module`
We don't need to worry about flake8 not reporting undefined names since running mypy_test.py
should detect undefined names anyway.
=> Make flake8 not complain about star imports

third_party/2and3/emoji.pyi
This adds type annotations for [`emoji` library](https://github.com/carpedm20/emoji/)
=> Add type annotations for emoji

third_party/2and3/requests/auth.pyi
Adds signature for [`_basic_auth_str`](https://github.com/requests/requests/blob/master/requests/auth.py#L28).
As the comment within its definition says *this behaviour is dumb but we need to preserve it because people are relying on it*, there's no reason to not add it as people surely use it.
Not handling random types like `int` though as the support for them will be eventually removed, hence no point in allowing them.
=> Added private method _basic_auth_str

third_party/2and3/typing_extensions.pyi
This PR adds stubs for the changes to ``typing_extensions`` in https://github.com/python/typing/pull/464
=> Add Protocol and runtime to typing_extensions

stdlib/3/configparser.pyi
RawConfigParser.read has code explicitly supporting PathLike objects.
Also removed an unused import and widened the accepted type from
Sequence to Iterable.
=> configparser: support PathLike

stdlib/3/configparser.pyi
This allows subclasses that define get* methods to wrap _get_conv whilst
still typechecking correctly.
For example:
```py
class GetListConfigParser(ConfigParser):
def getlist(self, section: str, option: str) -> List[str]:
def commas_to_list(value: str) -> List[str]:
if not value:
return []
return [item.strip() for item in value.split(',')]
return self._get_conv(section, option, commas_to_list)
```
=> Add definition for RawConfigParser._get_conv

stdlib/3/builtins.pyi
This allows accessing properties on `range` (and `xrange` in py2) without an error.
https://docs.python.org/3/library/stdtypes.html#range.start
=> Add range attributes

stdlib/3/subprocess.pyi
This change modifies the `PIPE`, `STDOUT`, and `DEVNULL` constants in the subprocess module to be of type 'int'.
Interestingly, the Python 2 version of the subprocess module was already typed this way, so this commit only needs to change the Python 3 version.
=> Change subprocess constants to be type int

stdlib/3/ssl.pyi
See commit messages for details about how these were derived.
=> ssl: Add missing constants & classes

stdlib/3/fcntl.pyi
Anything that implements a fileno() method is acceptable (per https://github.com/python/cpython/blob/master/Objects/fileobject.c#L168-L173), and IOBase fits the bill.
Fixes #1548.
=> Add IOBase to types fcntl will accept as files

stdlib/3.4/asyncio/tasks.pyi
Since mypy/typing lacks a mechanism to describe variadic templates (See https://github.com/python/typing/issues/193), a temporary solution was proposed to at least support some common cases of 1-5 arguments. 
This PR mimics the current hack implemented for `zip`: https://github.com/python/typeshed/blob/4491e415f93b25177a69c966902ebd88dd167642/stdlib/3/builtins.pyi#L868-L886
=> More precisely typehint asyncio.gather up to 5 params

stdlib/3/multiprocessing/context.pyi
Basically just copy-pasted the signature from `multiprocessing.Process()` to `BaseContext.Process()`.
=> Add support for multiprocessing.get_context().Process()

stdlib/3.4/enum.pyi
Ad-hoc fix python/mypy#2824, avoiding #1595.
Quoting the comment:
> This is a temporary workaround to allow multiple creation of enums with builtins such as str as mixins, which due to the handling of ABCs of builtin types, cause spurious inconsistent metaclass structure.
This workaround is relatively harmless since enums are never subclassed further. It "adds" an incorrect `register` method to enums and Enum, and may cause incorrect `isinstance` checks, but I think it will be much less common and therefore less serious than the current problems.
=> Derive EnumMeta from ABCMeta

stdlib/3/shlex.pyi
Update shlex to be compatible with changes from python 3.6: https://docs.python.org/3/library/shlex.html
Those changes should fix issues I've encountered:
```
main.py:10: error: No overload variant of "list" matches argument types [shlex.shlex]
main.py:10: error: Unexpected keyword argument "punctuation_chars" for "shlex"
/usr/local/lib/mypy/typeshed/stdlib/3/shlex.pyi:29: note: "shlex" defined here
```
caused by
```python
list(shlex(string, posix=True, punctuation_chars=True))
```
=> update shlex (python 3.6 updates)

stdlib/2/symbol.pyi
The `sym_name` dictionary was accidentally named `symbol`.  (https://docs.python.org/2/library/symbol.html)
=> Correct a typo in stdlib/2/symbol.pyi

stdlib/3.4/asyncio/streams.pyi
I verified this with the module source code. All these loop arguments default to `None` and are set with events.get_event_loop()` if this is the case.
For quick reference:
https://github.com/python/cpython/blob/9b47af65375fab9318e88ccb061394a36c8c6c33/Lib/asyncio/streams.py#L70-L71
=> All `loop` kwargs in asyncio.streams are optional

tests/mypy_selftest.py
Mypy has issues with running its test suite with many processes
concurrently. This should reduce travis test failures, if not completely
resolve failures. See issue https://github.com/python/mypy/issues/3543
=> Decrease Mypy concurrent process count

stdlib/2/itertools.pyi
Hello, I suspect this issue also should have a documentation fix for python both 2 and 3. Here's the fix for the type declaration though.
The relevant case to repro is over at: https://github.com/python/mypy/issues/3953
Here's the inconsistency in the stdlib docs too:
=> Second param of islice should allow None.

stdlib/2/ast.pyi
Turns out that pytype is a bit more finicky about imports, and differentiates between `*` imports for export, and imports for use in the local pyi. This adjusts `ast.pyi` to make pytype understand it again, after https://github.com/python/typeshed/pull/1515
=> Adjust "ast" imports to make pytype happy.

stdlib/3.4/asyncio/streams.pyi
Fixes #1622:
- Missing attribute `LimitOverrunError.consumed`
- Missing attribute `IncompleteReadError.expected` and `.partial`
- `partial` argument to `IncompleteReadError` had incorrect type
=> Corrections to the asyncio exception stubs

stdlib/3/time.pyi
clock_settime expects a float as parameter, and returns nothing.
It would make sense that the "settime" function accepts what the "gettime" function returns.
It also returns nothing as experimentation shows.
In python 3.4:
```
>>> time.clock_settime(time.CLOCK_REALTIME, time.gmtime())
TypeError: an integer is required (got type time.struct_time)
>>> time.clock_settime(time.CLOCK_REALTIME, time.clock_gettime(time.CLOCK_REALTIME))
>>>
```
(Note that it accepts both a float and int, but figured the typing of a float makes more sense)
=> Bug: Fix the typing for clock_settime

stdlib/2/__builtin__.pyi, stdlib/2/types.pyi, stdlib/3/builtins.pyi, stdlib/3/unittest/mock.pyi
Reverts python/typeshed#1549.
See Guido's comments in the original PR.
=> Revert "make __class__ refer to the current object's class"

stdlib/3.4/asyncio/tasks.pyi
=> Add 3-argument overload for asyncio.gather.

stdlib/2and3/socket.pyi
Allows one to use `AddressFamily` et al. as enums without type checker errors. It also ensures that one can write functions like the following:
```python
def make_socket(family: socket.AddressFamily, kind: socket.SocketKind) -> socket.socket: ...
```
And a type checker (i.e., mypy) will complain when trying to call the function like this:
```python
make_socket(socket.SOCK_STREAM, socket.AF_UNIX)
```
=> Ensure AF_*, SOCK_*, AI_*, and MSG_* constants are the correct enum type

stdlib/3/datetime.pyi
As per the documentation for the latest version of Python 3: https://docs.python.org/3/library/datetime.html
=> `month`, `day` parameters to `datetime.datetime` are required

third_party/2and3/requests/api.pyi
It's not obvious from the documentation, but the data argument for post, put and push also accepts an iterable of tuples. It also says so in the docs for requests.request function that post, put and push are aliases for.
http://docs.python-requests.org/en/master/api/
=> requests.post data arg accepts an iterable of tuples

CONTRIBUTING.md
I disagree with the recommendation that users create incomplete stubs, because such stubs lead to false positive type checker errors (see for example #525). I would like to instead set a norm that all stubs should contain all public objects in the library they cover.
=> Recommend against creating incomplete stubs

stdlib/2/textwrap.pyi
Leave them alone in TextWrap.__init__(), since I don't want to make the whole class generic.
(I promise this is the last one. I'd like to sync typeshed after this to lock in my winnings.)
=> Make initial_indent and subsequent_indent AnyStr in wrap() and fill()

third_party/3/dateutil/tz/__init__.pyi
This was missed in #1669, and should completely fix #1665.
=> Re-export names in 3/dateutil.tz

stdlib/3.4/asyncio/futures.pyi, stdlib/3/collections/__init__.pyi, stdlib/3/concurrent/futures/_base.pyi, stdlib/3/http/__init__.pyi, stdlib/3/wsgiref/types.pyi, tests/pytype_blacklist.txt
Removes most of tests/pytype_blacklist
* Removes a lot of files that pytype has now added support for
* Modifies some typeshed files to use a pytype-friendly syntax
* Adds more explicit comments for the two files we still blacklist
=> Clean out the pytype blacklist

third_party/2/enum.pyi
Test program:
```py
import enum
@enum.unique
class MoveReason(enum.IntEnum):
ALLOWED = 0
TEAM_FOLDER_MOVE = 1
REMOVE_FROM_TEAM_FOLDER = 2
all_reason = list(MoveReason)  # Error here
```
This gave a confusing error **when run with `mypy -2`:**
```
__tmp__.py:7: error: No overload variant of "list" matches argument types [Overload(def (x: typing.SupportsInt =) -> __tmp__.MoveReason, def (x: Union[builtins.str, builtins.unicode, builtins.bytearray], base: builtins.int =) -> __tmp__.MoveReason)]
```
Some research suggested that `unique()` had the wrong signature in the PY2 stub. Just fixing that didn't seem to change anything, so I just copied the metaclass from the PY3.4 stub. Now the error is the same as for that code in PY3:
```
__tmp__.py:7: error: Need type annotation for variable …
```
=> Make PY2 enum more like PY3 enum, fixing bug in unique()

third_party/2and3/requests/sessions.pyi
Allow doing things like:
```py
s = requests.session()
s.headers['User-Agent'] = 'foo'
s.get('https://www.example.com/')
```
=> requests.Session.headers and proxies not optional

README.md
I suggest to add something similar to what is suggested in this PR to the README to clarify the default argument syntax (per PR #1686). Potentially the change to the example is enough, because the second list item already hints at using `...` over the actual default value.
=> Document default argument syntax

third_party/2/dateutil/tz/__init__.pyi
Typo introduced in #1669 (#1673 fixed this for python 3 only)
=> fix typo in dateutil.tz importing tzutc as tzutz in python 2

stdlib/2and3/threading.pyi
The 'args' argument to `threading.Thread.__init__` can be anything that can be expanded with *.
(https://github.com/python/cpython/blob/master/Lib/threading.py#L865)
=> Fix a parameter type in threading.Thread.__init__

stdlib/3/sre_constants.pyi
The existing py3 stub for `sre_constants` is directly from stubgen, which misses the dynamically-defined constants.  Fortunately, this is easy to add by hand!
Motivation: we need this stub filled out to typecheck Hypothesis' regex module, which generates strings matching the given regex (see HypothesisWorks/hypothesis-python#858).  We currently silence the many 'module has no attribute' errors by casting the module to `Any`, but obviously this isn't ideal.
Also relevant to #1019, by checking off one of the remaining modules.
=> Complete Py3 stub for sre_constants

third_party/2and3/click/decorators.pyi
This follows documentation and code which allows to use both bool and Text.
Update all the prompt arguments for all *option functions in click.decorators module
since they're mostly proxying the call to option setting desired defaults.
closes #1693
=> click.*option function parameter to accepts bool and Text

stdlib/3/_importlib_modulespec.pyi
List is used but not imported. According to PEP-484 "Suggested syntax for Python 2.7 and straddling code" it should be imports. 
"Like other type comments, any names used in the annotations must be imported or defined by the module containing the annotation.".
Also order the typing import list, because it looks nicer.
=> Add List to the typing imports and order the imports

CONTRIBUTING.md, README.md
For previous discussions, see PR #1687 and issue #1688.
=> Merge style guide from README.md into CONTRIBUTING.md

third_party/2and3/click/utils.pyi
str is not unicode on Python 2 while Text is a proper alias
for unicode on python 2 and str on python 3
closes #1691
=> click.echo message arg type to follow click's documentation

third_party/2and3/requests/sessions.pyi
Current code that initializes the things I've changed, to demonstrate that the
object is initialized this way:
* headers: https://github.com/requests/requests/blob/9713289e74/requests/sessions.py#L345
* proxies: https://github.com/requests/requests/blob/9713289e74/requests/sessions.py#L354
* hooks: https://github.com/requests/requests/blob/9713289e74/requests/sessions.py#L357
* params: https://github.com/requests/requests/blob/9713289e74/requests/sessions.py#L362
* cookies: https://github.com/requests/requests/blob/9713289e74/requests/sessions.py#L388
from what I can tell nothing in the official requests API ever creates a
session other than through `__init__`.
I suppose I should cc @kennethreitz since I'm making an assertion about his API.
=> Remove unnecessary optionality for requests.Session

stdlib/2and3/plistlib.pyi
Fixes a pytype issue from #1720.
=> don't import enum in Python 2

stdlib/2and3/traceback.pyi
To make this code valid:
```python
import traceback
for filename, lineno, name, line in traceback.extract_stack(stack):
pass
```
=> Make traceback.FrameSummary Iterable

stdlib/2/__builtin__.pyi
See also https://github.com/python/typeshed/issues/132
Follow up to https://github.com/python/typeshed/pull/134
Fixes https://github.com/python/mypy/issues/4242
This allows:
```python
class A(object):
pass
A().__dict__
```
=> Add __dict__ to object in Python 2

stdlib/2and3/logging/__init__.pyi
The missing colon in the variable type annotation means that the type of stream is currently incorrectly determined to be of type ellipsis, rather than IO[str].
=> Fix missing colon in StreamHandler.stream type annotation

stdlib/2/wsgiref/types.pyi, stdlib/3/wsgiref/types.pyi
Per PEP 3333, a WSGI environment can contain anything, not just strings.
WSGIEnvironment is a useful type on its own.
=> Extract WSGIEnvironment and change value type to Any

third_party/2and3/pynamodb/connection/__init__.pyi
It looks like in recent versions of mypy this stopped being exported.
=> Export Connection and TableConnection from pynamodb.connection

stdlib/2and3/argparse.pyi
Without this change, mypy fails to correctly type-check a program like:
```python
import argparse
if __name__ == "__main__":
parser = argparse.ArgumentParser()
print("Prog = {}".format(parser.prog))
```
With this change, the program type-checks as expected.
=> argparse: Add annotations for instance variables.

tests/pytype_blacklist.txt
Fixes Travis CI, which broke with
```
File "/home/travis/virtualenv/python2.7.14/bin/pytype", line 304, in <module>
sys.exit(main(sys.argv) or 0)
File "/home/travis/virtualenv/python2.7.14/bin/pytype", line 269, in main
return _convert_to_pickle(options)
File "/home/travis/virtualenv/python2.7.14/bin/pytype", line 249, in _convert_to_pickle
ast = loader.load_file(options.module_name, options.input)
File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pytype/load_pytd.py", line 130, in load_file
return self._process_module(module_name, filename, ast)
File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pytype/load_pytd.py", line 146, in _process_module
module.ast = self._postprocess_pyi(module.ast)
File …
```
=> add util.pyi to blacklist

stdlib/3/os/__init__.pyi
Rework of #1583. Fixes #1573.
See documentation in https://docs.python.org/3/library/os.html#os.scandir.
To test this, I used the following file:
```python
import os
with os.scandir() as it:
reveal_type(it)  # _ScandirIterator[str]
for f in it:
reveal_type(f)  # DirEntry[str]
with os.scandir(b'.') as bit:
reveal_type(bit)  # _ScandirIterator[bytes]
for bf in bit:
reveal_type(bf)  # DirEntry[bytes]
class BytesPath(os.PathLike[bytes]):
def __fspath__(self) -> bytes:
return b'ytes'
with os.scandir(BytesPath()) as bpit:
reveal_type(bpit)  # _ScandirIterator[bytes]
for bpf in bpit:
reveal_type(bpf)  # DirEntry[bytes]
```
I got
```
$ mypy --custom-typeshed-dir . samples/scandir.py
samples/scandir.py:3: error: Revealed type is 'os._ScandirIterator*[builtins.str*]'
samples/scandir.py:5: error: …
```
=> make os.scandir work as a context manager

stdlib/2and3/codecs.pyi
codecs.iterencode and codecs.iterdecode should both return Generators
rather than Iterators
=> codecs.iter(en|de)code fix return type

stdlib/2/textwrap.pyi
wrap() returns  a list of strings: https://docs.python.org/2/library/textwrap.html#textwrap.wrap
=> Fix the return type of textwrap.wrap

stdlib/3/os/__init__.pyi, stdlib/3/posix.pyi
This removes the circular dependency between the os and posix stub, which
is somehow triggering python/mypy#4442. We should ideally fix the mypy bug,
but since it's easy enough to fix the import cycle, we might as well do that
too.
=> move os.stat_result into posix stub

tests/pytype_test.py
We removed some flags. In particular, the typeshed location is now passed via the environment.
=> Fix tests to work with newest version of pytype

third_party/2/werkzeug/wrappers.pyi, third_party/3/werkzeug/wrappers.pyi
PEP 3333 explicitly calls for environ to be a built-in dict. Using a
Mapping will not only prevent the dict from being modified (which is
explicitly allowed by PEP 3333), it will also cause interaction
problems when the environment is passed to other WSGI handlers.
Also change the value type from object to Any for convenience. By
definition, the values can be anything and can't be type checked.
Using object instead of Any forces us to explicitly cast the value
whenever we access it.
Supersedes #1744, but conflicts with #1730.
=>  Fix werkzeug environ type

third_party/2and3/requests/sessions.pyi
Each key in `hooks` is a list, not a callable directly. Current error when using hooks is:
```
mypy: Callable[[Response], Any] has no attribute "append" (E)
```
https://github.com/requests/requests/blob/24092b11d74af0a766d9cc616622f38adb0044b9/requests/hooks.py#L18
=> Fix requests session hooks type

third_party/2and3/click/decorators.pyi
Click's version_option decorator allows the caller to specify the version message (http://click.pocoo.org/5/api/). This optional string option is missing in typeshed. If accepted, this also fixes #1773.
=> Add 'message' to click.decorators.version_option

stdlib/3.4/asyncio/events.pyi
The signature should match that of socket.getaddrinfo()
Maybe there are other APIs waiting for similar changes... I don't know.
=> improve asyncio.AbstractEventLoop.getaddrinfo()

stdlib/2/__builtin__.pyi
This is debatable: an ASCII-only unicode object is acceptable, but
non-ASCII characters will cause the message to be replaced with
'<exception str() failed>'.  However I found some internal code that
sometimes assigns unicode objects to .message, and I'd rather not
burden that code with .encode() calls -- especially since in Python 3
this is a text string.  Note that if you pass the unicode object to
the constructor it type-checks, and ditto if you assign to .args.
**UPDATE:** Actually it should be `Any`, see later comments.
=> Change the type of BaseException.message to Any

third_party/2and3/pynamodb/attributes.pyi
Previously we specified this as a Union type, which caused more problems than it helped with, namely when reading data off a Pynamo property
We still had to cast to the appropriate type.  Pynamo simply reads the type out of Dynamo, which more closely models a float as it can be an int or a float -
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.NamingRulesDataTypes.html
=> Treat all pynamodb Numbers as `floats`

stdlib/2and3/logging/__init__.pyi
Resolves https://github.com/python/typeshed/issues/1833
=> Add FileHandler properties

stdlib/3/configparser.pyi
=> Update configparser.ParsingError base class to match the source file

stdlib/3/builtins.pyi, stdlib/3/multiprocessing/__init__.pyi
* The problem in `multiprocessing` was just overlooked
* The change to `OSError`, while being technically correct, is problematic because conditional platform checks are sometimes hard to recognize.
=> Fix some problems introduced by recent commits.

third_party/2and3/attr/__init__.pyi
The following code is pretty typical when using attrs but would fail to typecheck:
```
from typing import Dict
import attr
@attr.s
class A:
a: Dict[str, str] = attr.ib(attr.Factory(dict))
```
This is because of https://github.com/python/mypy/issues/4554
This change to the typeshed works around the issue for the specific case of the first argument.  Which is the most common situation.
=> Work around mypy issue #4554 in attrs.

third_party/2and3/requests/api.pyi
Use case:
```python
import json
url = 'https://api.github.com/some/endpoint'
payload = {'some': 'data'}
r = requests.post(url, data=json.dumps(payload))
```
=>  Allow `requests.post` to accept `str` for `data`.

stdlib/3/multiprocessing/__init__.pyi
Fixes #1923.
Modules should import explicitly with `as X` to expose `X` in mypy (https://github.com/python/mypy/blob/8bbfef12d173303e3f4f9511901b88d23a10526f/mypy/semanal.py#L1440), but error classes such as `TimeoutError` in `multiprocessing` module in Python 3 stub lacks `as X` part, which was the cause of #1923. This PR adds missing `as X` to these imports.
=> Fix imports to expose error classes in multiprocessing module

CONTRIBUTING.md
Also add Ivan as a typeshed core dev (since he is in the group).
=> Add guideline for undocumented objects

stdlib/3.4/asyncio/streams.pyi
Not sure why it was `int` previously (maybe a copy-paste error from `limit` below?), but this makes it match the loop parameter to start_server.
I've run `python3 tests/mypy_test.py` over this and it passes.
=> Fix type of loop parameter to asyncio.start_unix_server

stdlib/2/__builtin__.pyi, stdlib/2/dummy_thread.pyi, stdlib/2/os/__init__.pyi, stdlib/2/pydoc.pyi, stdlib/2/sys.pyi, stdlib/2/unittest.pyi, stdlib/2and3/lib2to3/pgen2/pgen.pyi, stdlib/2and3/poplib.pyi, stdlib/2and3/sunau.pyi, stdlib/2and3/wave.pyi, stdlib/2and3/xml/sax/__init__.pyi, stdlib/3/_dummy_thread.pyi, stdlib/3/builtins.pyi, stdlib/3/os/__init__.pyi, stdlib/3/sys.pyi, stdlib/3/unittest/__init__.pyi, third_party/2/six/__init__.pyi, third_party/3/six/__init__.pyi
=> Switch usages of mypy_extensions.NoReturn over to typing.NoReturn.

third_party/2and3/mypy_extensions.pyi
In typeshed itself, we don't use mypy_extensions anymore. But there might be Python code that does. So we need to keep the file around.
=> add deprecation comment to mypy_extensions

third_party/2and3/click/decorators.pyi
Click's option decorator can take a cls= argument, which allows that class to parse arbitrary arguments from the decorator.
=> Update click.option to allow for user defined kwargs.

CONTRIBUTING.md
We (I) introduced the BLOCKED label ~2 years ago, but it never got much usage, and I remember it startled some developers (Ivan may recall...). A better convention seems to put [WIP] in the subject, so let's standardize on that and get rid of the BLOCKED label.
I already removed the BLOCKED label and edited the subject of the one issue under it.
We also don't make good use of the other labels, but they seem more useful and less controversial.
=> Get rid of BLOCKED label in favor of [WIP] subject prefix

stdlib/3/subprocess.pyi
See here:
https://docs.python.org/3/library/subprocess.html#subprocess.TimeoutExpired
Here is an example I did in the terminal
```
>>> e
TimeoutExpired(['sleep', '5'], 1)
>>> e.cmd
['sleep', '5']
>>> e.timeout
1
>>> e.output
b''
>>> e.stdout
b''
>>> e.stderr
>>> e.asdf
AttributeError: 'TimeoutExpired' object has no attribute 'asdf'
>>>
```
=> Add subprocess annotation for TimeoutExpired

stdlib/3/types.pyi
See https://docs.python.org/dev/reference/datamodel.html#traceback-objects
and python/cpython#4793.
Part of #1965.
=> allow instantiating TracebackType in 3.7

stdlib/2and3/logging/handlers.pyi
In python3 `RotatingFileHandler` is a subclass of `BaseRotatingHandler` which is a subclass of `FileHandler` which is a subclass of `StreamHandler` which has a `terminator` property but I'm getting a `"RotatingFileHandler" has no attribute "terminator"` error on my code.
=> RotatingFileHandler has a terminator property

stdlib/3/tempfile.pyi
`encoding` and `newline` have a default value of `None` in stdlib, for all of
the classes/functions that take these parameters.
=> Make encoding and newline optional in tempfile

stdlib/2and3/traceback.pyi
The first two arguments were already optional for Python 2, but they are also optional in Python 3:
```python
>>> import traceback
>>> traceback.print_exception(None, None, None)
NoneType: None
```
This should fix mypy warnings in the following line: `print_exception(*sys.exc_info())` (untested).
=> traceback.print_exception(): Arguments optional in Python 3

.flake8
This was introduced in a recent version (so it doesn't affect us right now but will if we upgrade the flake8 version used in tests). It gives errors like:
```
/home/travis/build/ambv/flake8-pyi/.tox/typeshed/tmp/typeshed/stdlib/3/re.pyi:21:9: E741 ambiguous variable name 'I'
/home/travis/build/ambv/flake8-pyi/.tox/typeshed/tmp/typeshed/stdlib/3/re.pyi:39:5: E741 ambiguous variable name 'I'
/home/travis/build/ambv/flake8-pyi/.tox/typeshed/tmp/typeshed/stdlib/3/re.pyi:58:5: E741 ambiguous variable name 'I'
/home/travis/build/ambv/flake8-pyi/.tox/typeshed/tmp/typeshed/third_party/2/OpenSSL/crypto.pyi:43:5: E741 ambiguous variable name 'O'
```
These aren't useful for typeshed, because regardless of whether it's good style, these libraries really do contain variables named `I` and `O`.
=> add E741 to ignored flake8 codes

stdlib/2and3/ctypes/__init__.pyi
* Make {C,WIN,PY}FUNCTYPE's restype argument optional (for void returns)
* Make WinError WindowsError
* Don't have Array explicitly inherit from Sized
(since inheriting from classes with different metaclasses causes problems)
* Have Array.__iter__ properly return an Iterator instead of an Iterable
If I hack around some platform detection woes (which still require some thought), I can get our internal codebase to typecheck with these fixes.
=> Fix some more ctypes issues

third_party/2and3/boto/compat.pyi
This passes the standard complement of tests (`mypy_selftest.py`, `mypy_test.py` and `pytype_test.py`) and fixes #1955
=> Fixup the boto stubs to allow `mypy --strict`.

stdlib/3.4/asyncio/streams.pyi
They have `getaddrinfo(3)` as their backend, and accept `port='http'` etc. You can even omit (pass `None` to) either of `host` or `port` for `start_server()` to effectively select `'localhost'` and an arbitrary ephemeral port, respectively.
=> Improve asyncio APIs which take TCP port

tests/mypy_test.py
=> try using `--no-site-packages`

third_party/2/enum.pyi
This fixes an error in Travis that seems to have been caused by python/mypy#4319.
The fix was taken from the stdlib/3.4/enum.pyi stub. Mypy no longer assumes
that classes whose metaclass is EnumMeta are subclasses of Enum, so we can't
bound the typevar on Enum.
=> fix third_party/2/enum.pyi

stdlib/3/sys.pyi
https://docs.python.org/3/library/sys.html#sys.base_exec_prefix
=> add sys.base_exec_prefix and sys.base_prefix

stdlib/3/subprocess.pyi
Fixes #2034.
See https://docs.python.org/3.7/library/subprocess.html#windows-popen-helpers. I don't have Windows to test, so I was conservative in assuming types for some of these.
=> add subprocess.STARTUPINFO and some associated constants

stdlib/2and3/argparse.pyi
add_argument's type argument was recently changed to be (approximately)
`Callable[[_Text], _T]`. Because of contravariant subtyping for functions,
this had the effect of requiring that add_argument *always*
be unicode, which is wrong.
Change it to be `Callable[[str], _T]`.
=> Fix py2 unicode handling for ArgumentParser.add_argument's text arg

third_party/2and3/click/types.pyi
path_type takes a type, not an instance of the type
Tested with a simple click app using click.Path:
```python
#!/usr/bin/env python3
import click
@click.command()
@click.argument(
'path',
required=True,
type=click.Path(
exists=True,
path_type=str
)
)
def testapp(path):
print(f'Hi: {path}')
if __name__ == '__main__':
testapp()
```
Passes typecheck with this change, before was failing with
```
clicktest.py:9: error: Value of type variable "_PathType" of "Path" cannot be "Type[str]"
```
=> Fix type of click.Path path_type arg

third_party/2/google/protobuf/descriptor.pyi
Found this by running mypy over some internal code. Apparently the code generator can generate code like this:
```
_descriptor.FieldDescriptor(
name='cookie_info', full_name='user_auth.UserAuthInfo.cookie_info', index=0,
number=1, type=11, cpp_type=10, label=1,
has_default_value=False, default_value=None,
message_type=None, enum_type=None, containing_type=None,
is_extension=False, extension_scope=None,
options=None, file=DESCRIPTOR),
],
```
=> Add 'file=...' to FieldDescriptor constructor.

third_party/2and3/attr/__init__.pyi
The first overload was catching all calls including take_self=True.
Fix it by modifying the overloads.
Fixes https://github.com/python-attrs/attrs/issues/366
=> Fix attr.Factory signature

third_party/2/enum.pyi
Currently the Python 2 stub for `IntEnum` just inherits from `Enum` without changing anything, meaning that its `value` has type `Any`. This changes it such that, if you know you have an `IntEnum` you get the more specific `int` type for the `value`. Note that this has already been done for Python 3 `IntEnum` (both in `third_party/3/enum.pyi` and `stdlib/3.4/enum.pyi`).
=> Have Python 2 IntEnum values be ints

stdlib/2and3/rlcompleter.pyi
This argument has been around since 2.3, and it's documented in the
rlcompleter docstring (although not on python.org).
=> Add missing namespace argument to rlcompleter.Completer

stdlib/2/ConfigParser.pyi, stdlib/2/multiprocessing/dummy/__init__.pyi, stdlib/2/multiprocessing/dummy/connection.pyi, stdlib/2/popen2.pyi, stdlib/2/tokenize.pyi, stdlib/3/multiprocessing/dummy/__init__.pyi, stdlib/3/multiprocessing/dummy/connection.pyi, stdlib/3/urllib/parse.pyi, third_party/2and3/dateutil/parser.pyi, third_party/2and3/dateutil/relativedelta.pyi
The presence of a __all__ causes everything to not get picked up by
import *, which among other things breaks the new six.moves stubs.
=> Remove __all__ = ... from stubs

stdlib/3/json/__init__.pyi
```python
import io
import json
json.load(io.BytesIO(b'{}'))
```
```console
$ mypy test.py
test.py:3: error: Argument 1 to "load" has incompatible type "BytesIO"; expected "IO[str]"
```
```
$ mypy --custom-typeshed-dir . test.py
$
```
=> json.load can also take IO[bytes] in py36+

stdlib/3/http/client.pyi
Though not documented, there's precedent from https://github.com/python/typeshed/pull/968
```python
import urllib.request
print(urllib.request.urlopen('https://example.com').headers['content-type'])
```
```console
$ mypy test.py
test.py:3: error: Item "HTTPResponse" of "Union[HTTPResponse, addinfourl]" has no attribute "headers"
```
```console
$ mypy test.py --custom-typeshed-dir .
$
```
=> Add headers attribute to HTTPResponse

stdlib/3.7/dataclasses.pyi
Type is a lie, but it reflects better the runtime magic (which is otherwise hard to fix in a plugin).
=> Update return type of dataclasses.field

stdlib/3.4/asyncio/futures.pyi, stdlib/3/typing.pyi
Fixes #1940.
This makes it so that mypy will infer the common base class of these
classes to be Awaitable instead of Iterable. I verified that this
fixes the errors in the script posted by @neilconway.
=> switch order of base classes on awaitable classes

stdlib/2/__builtin__.pyi, stdlib/3/builtins.pyi
Fixes #1853 
This is going to fail mypy_selftest in Travis because it needs a concurrent change to mypy. I'll send out a mypy PR for doing that.
=> remove Optional from type of __slots__

.travis.yml, tests/mypy_test.py
This was already the configuration in Travis and it's been working fine. It's
confusing that Travis was using a different configuration than the default
when you run tests/mypy_test.py yourself.
=> always run mypy with --no-implicit-optional

stdlib/2/typing.pyi
This is already how it works in the Python 3 stub.
`Iterator.__iter__` also exists at runtime: https://github.com/python/cpython/blob/2.7/Lib/_abcoll.py#L73.
=> `Iterator` provides a concrete `__iter__` in 2.7

stdlib/3/http/client.pyi
Matches the implementation in https://github.com/python/cpython/blob/3.4/Lib/http/client.py#L308
The ignore works around python/mypy#5027 (commented further up in the 3.5 branch).
Part of #1476.
=> make http.client.HTTPResponse concrete in 3.4

stdlib/3/concurrent/futures/thread.pyi, third_party/2/concurrent/futures/thread.pyi
The thread_name_prefix argument of ThreadPoolExecutor.__init__ was added
to the Python 2 backport in agronholm/pythonfutures#64.
=> Add thread_name_prefix to ThreadPoolExecutor stub

stdlib/2and3/zipfile.pyi
`zipfile.ZipFile` is typed to accept `Text` for local and archive file
paths. In Python 3.6, several `ZipFile` methods accept `pathlib.Path`
objects, not just `str` objects. Generalize `ZipFile`'s methods so code
using `pathlib.Path` with `ZipFile` type-checks.
I verified (using my own project) that the following methods work with
os.PurePath at runtime on CPython 3.6:
* zipfile.ZipInfo.__init__
* zipfile.ZipInfo.extractall
* zipfile.ZipInfo.write
=> Allow pathlib.Path in zipfile.ZipFile

third_party/2and3/requests/api.pyi
The change introduced in 395ab5abd1102d7db1f57cad4febe8fe977fd960
broke the signature of `requests.post`, among others, since
`MutableSequence` is invariant, and plain `Dict[str, str]` values
were no longer valid for the `data` argument.
This changes the signature to have `Any` components as a
compromise. Adding more items to the union seems a bit too much, since
the mypy error messages for invalid argument types are already pretty hard to
read.
Another option might be to use `Mapping` instead of `MutableMapping`
due to covariance, but I assume there's a reason why `MutableMapping`
is used here.
=> Fix requests.post signature

stdlib/2/__builtin__.pyi, stdlib/2/builtins.pyi
In short, this change makes sure calls like `map(None, a, b)` behave as
expected when using `--no-strict-optional` is enabled.
For additional context, see https://github.com/python/mypy/issues/5246
=> Make overloads in Python 2 builtins with a 'None' fallback come first

stdlib/2and3/imaplib.pyi
=> Fix type for imaplib.IMAP4.error and related

third_party/2and3/click/core.pyi, third_party/2and3/click/decorators.pyi, third_party/2and3/click/termui.pyi, third_party/2and3/click/types.pyi, third_party/2and3/click/utils.pyi
This works around https://github.com/python/mypy/issues/5275
It sadly introduces an `Any`, but I felt that it is an acceptable compromise. Let me know if you have a different opinion on where the `Any` should be introduced.
=> Remove type cycle in click

stdlib/2and3/tty.pyi
<https://docs.python.org/2/library/tty.html>
> ... requires the termios module ...
<https://docs.python.org/2/library/termios.html#module-termios>
> All functions in this module take a file descriptor fd as their first
> argument. This can be an integer file descriptor ... or a file object,
=> tty.set*() accepts fd or file object

stdlib/2/urllib2.pyi
<https://docs.python.org/2/library/urllib2.html#urllib2.build_opener>
> handlers can be either instances of BaseHandler, or subclasses of
> BaseHandler (in which case it must be possible to call the constructor
> without any parameters).
=> urllib2.build_open() accepts instances and classes

stdlib/2and3/logging/__init__.pyi
python2.7 -c 'from logging import BASIC_FORMAT;print(type(BASIC_FORMAT))'
=> logging.BASIC_FORMAT also for python2.7

stdlib/3/_ast.pyi
Also, mark AST._attributes and _fields as class vars
`lineno` and `col_offset` were previously defined on a few sub-classes of `AST`, e.g. `expr`, even though https://docs.python.org/3/library/ast.html explicitly states that `AST` has these two attributes. These attributes are only present if they were supplied as arguments to the constructor, but the same is true for the subclasses:
```
>>> AST(lineno=12).lineno
12
>>> AST().lineno
AttributeError: '_ast.AST' object has no attribute 'lineno'
>>> expr(lineno=12).lineno
12
>>> expr().lineno
AttributeError: 'expr' object has no attribute 'lineno'
```
=> Move lineno and col_offset to ast.AST

stdlib/3.4/asyncio/__init__.pyi, stdlib/3.4/asyncio/tasks.pyi
While this alias for `ensure_future` existed prior to Python 3.7, it causes a syntax error when parsing it with Python 3.7 or above. `ensure_future` was introduced in Python 3.4.4 and `asyncio` was deprecated at the same time. While this change makes valid code emit warnings, I see no other fix.
=> Remove asyncio.tasks.async

third_party/2and3/click/testing.pyi
Click already had stubs but not for the `testing` submodule.
I used stubgen and then narrowed the types when it was easy.  I left
`Any` where more work was necessary.
=> Add stub file for click.testing

stdlib/3/unittest/__init__.pyi
And also in assertNotRegex, assertRegexpMatches.
Closes #2312.
=> Accept AnyStr in unittest.assertRegex

third_party/2and3/dateutil/relativedelta.pyi
I have deduced the types from docstring & source code of the
relativedelta class.
Fixes #2269.
=> Add missing attributes to the dateutil/relativedelta stub

stdlib/2and3/imghdr.pyi
Ad defined in https://docs.python.org/3/library/imghdr.html.
=> Add stdlib/2and3/imghdr stubs

third_party/2and3/click/core.pyi, third_party/2and3/click/decorators.pyi, third_party/2and3/click/utils.pyi
Basically work around https://github.com/python/mypy/issues/3924
=> Make click decorators not modify the type

third_party/2and3/click/core.pyi
click.Context.exit() calls sys.exit() and hence should be a NoReturn return type.
=> Fix type for click.Context.exit

third_party/2and3/click/core.pyi
Both of these methods always raise Exceptions.
=> Change return type for click.Context.fail and click.Context.abort to NoReturn

third_party/2and3/boto/s3/key.pyi
- Cleanup (remove type comments, break up long lines)
- Add an overload for get_contents_as_string to that it returns bytes unless encoding is specified.
See the documentation at http://boto.cloudhackers.com/en/latest/ref/s3.html#boto.s3.key.Key.get_contents_as_string.
=> Fixes to boto.s3.key stub

third_party/2and3/pymysql/__init__.pyi
Using FrozenSet is I think preferred (because it works in general) and
I am about to propose a mypy PR that breaks this particular use.
=> Change a use of frozenset[int] to FrozenSet[int]

stdlib/3/curses/__init__.pyi
`curses.wrapper` returns the return value of the function it is passed,
but its function argument is declared as `Callable[..., Any]` while its
return type is `None`. This changes the definition of `curses.wrapper`
to use a `TypeVar` that relates the return type of its function argument
to its own return type.
=> Relate _curses.wrapper return type to its function arg

tests/check_consistent.py, third_party/3/dataclasses.pyi
This fixes python/mypy#5389, and implements the fix suggested by @gvanrossum 
I have manually tested the change, and it fixes the issue for me. 
I'm not sure if there is a way to write a automated test for the change?
I have not requested permission from the library owner, as I am assuming that this is not necessary for stdlib backports.
=> Make dataclasses availible as a backported third_party library.

third_party/2and3/mypy_extensions.pyi
`@trait` has special meaning to the experimental mypyc compiler,
slightly restricting the behavior of the class in exchange for
allowing it to be multiply inherited from.
=> Add undocumented `trait` decorator to mypy_extensions

stdlib/3/concurrent/futures/process.pyi, stdlib/3/concurrent/futures/thread.pyi, third_party/2/concurrent/futures/process.pyi, third_party/2/concurrent/futures/thread.pyi
Tests fail requiring files to be copied to third_party/2, but the third party concurrent.futures has not been updated with these changes yet even in git, so I don't think that would be appropriate.
=> concurrent.futures: Sync with Python 3.7

stdlib/2and3/csv.pyi
Fixes #2346.
I only opened #2346 a couple of hours ago so I'm still anticipating feedback on whether or not this is a correct way to go about fixing that problem, but since the diff was so simple I figured I might as well make the PR for it.
Tests pass locally ✔️
=> Allow DictReader values to be None (#2346)

stdlib/2and3/sqlite3/dbapi2.pyi
=> Allow sqlite3.connect to take PathLike object on Python 3.7+

stdlib/3/json/__init__.pyi
* loads() only accepts str as first argument for Python < 3.6
* Use a protocol for the first argument to load() (cf python/typing#564)
=> Improve annotations for json.load() and loads()

stdlib/2/collections.pyi, stdlib/3/collections/__init__.pyi
- The extra arguments aren't keyword-only in 2.7.
- Added the `defaults` argument in 3.7 (https://docs.python.org/3.7/library/collections.html#collections.namedtuple).
I'm hoping I'll be able to convince mypy to use these stubs to check calls to `namedtuple()`; see python/mypy#2127 and python/mypy#4788. Regardless, we should fix the namedtuple stubs in case other type checkers may be using them.
=> minor namedtuple fixes

stdlib/3/subprocess.pyi
Python 3.7 added:
- `text` as an alias of `universal_newlines`
- `capture_output` for `stdout=PIPE,stderr=PIPE`
cf. https://docs.python.org/3.7/library/subprocess.html
=> Add 3.7 variant of subprocess.run

third_party/2and3/requests/sessions.pyi
This causes an error in pytype.
=> Remove duplicate `adapters` import.

stdlib/2and3/codecs.pyi
This will enable checking positional and keyword parameters.
=> Use class with __call__ method instead of callable.

third_party/2/tornado/httpclient.pyi
Fixes #2423.
I followed https://github.com/tornadoweb/tornado/blob/master/tornado/httpclient.py and kept the `@property` where it exists in the implementation and the attribute where it doesn't.
=> fix duplicate definitions in tornado

stdlib/2/unittest.pyi, stdlib/3/unittest/__init__.pyi
Fixes #2388.
Inspection of the code shows that the argument can also be None or module (https://github.com/python/cpython/blob/master/Lib/unittest/main.py#L69), although the docs (https://docs.python.org/3/library/unittest.html#unittest.main) don't say anything much about the type of `module`.
=> fix module argument to unittest.main

stdlib/2and3/datetime.pyi
This PR solves: #2448
`datetime.datetime()` and `datetime.time()` have started to support `fold` arguments from 3.6.
- https://www.python.org/dev/peps/pep-0495/
- https://docs.python.org/3.5/library/datetime.html#datetime.datetime
- https://docs.python.org/3.6/library/datetime.html#datetime.datetime
- https://docs.python.org/3.5/library/datetime.html#datetime.time
- https://docs.python.org/3.6/library/datetime.html#datetime.time
=> Add type hint for fold arguments to datetime.datetime and datetime.time when Python >= 3.6 

third_party/2and3/typing_extensions.pyi
This complements:
* mypy PR https://github.com/python/mypy/pull/5522
* typing PR https://github.com/python/typing/pull/583
=> Add Final to typing_extensions

third_party/2/six/moves/urllib_request.pyi, third_party/2/six/moves/urllib_response.pyi, third_party/3/six/moves/urllib_request.pyi, third_party/3/six/moves/urllib_response.pyi
Like the other six.moves.urllib.{foo} modules, request and response can be imported as six.moves.urllib_{foo}.
There's a mypy_selftest failure that I'm also seeing in a couple other recent PRs (e.g., https://github.com/python/typeshed/pull/2433), so I don't think it's related to this change.
=> Add six.moves.urllib_request and six.moves.urllib_response.

stdlib/2and3/logging/__init__.pyi
This attribute has been a part of the `logging.Handler` for quite some time. Exists in [2.7](https://github.com/python/cpython/blob/2.7/Lib/logging/__init__.py#L699) and [onward](https://github.com/python/cpython/blob/3.6/Lib/logging/__init__.py#L798).
```python
file_handler = FileHandler(log_file_path)
file_handler.set_name("file")  # flake8 T484 - "FileHandler" has no attribute "set_name" (ignoring to encourage property syntax)
file_handler.name = "file"  # flake8 T484 - "FileHandler" has no attribute "name"
print(file_handler.name)  # flake8 T484 - "FileHandler" has no attribute "name"
console_handler = logging.StreamHandler()
console_handler.set_name("console")  # flake8 T484 - "StreamHandler" has no attribute "set_name" (ignoring to encourage property syntax)
console_handler.name = …
```
=> Add name attribute to logging.Handler

stdlib/2and3/logging/__init__.pyi
Looks like this was missed. It seems to have been there since at least 2.7.
=> Add exc_text to LogRecord

stdlib/2and3/codecs.pyi
A StreamReader "inherit[s] all other methods and attributes from the underlying stream" (https://docs.python.org/3/library/codecs.html#codecs.StreamReader), which includes an `__iter__` method for getting lines of text.
=> Add __iter__ method to codecs.StreamReader.

stdlib/3/subprocess.pyi
Previously, constructing a TimeoutExpired directly worked because Exception allowed arbitrary kwargs. We fixed that recently, but now mypy gives an error on creating a TimeoutExpired with legal arguments.
=> add constructor arguments for TimeoutExpired

stdlib/2and3/traceback.pyi
This is the non-controversial, non-have-to-think-about-it-for-a-bit portion of [pull request 2436](https://github.com/python/typeshed/pull/2436).
=> Fix traceback.FrameSummary's "line" parameter

stdlib/2/__builtin__.pyi, stdlib/2/builtins.pyi, stdlib/2/types.pyi, stdlib/3/builtins.pyi
This is just a direct rehash of #1549.
I checked this against our internal codebases and it caused two errors, both resolvable by deleting the type annotations that were conflicting.
=> make __class__ refer to the current object's class

stdlib/3/configparser.pyi
=> Add `bytes` as legal type for `RawConfigParser.read`.

stdlib/2and3/logging/__init__.pyi, stdlib/2and3/logging/config.pyi, stdlib/2and3/logging/handlers.pyi
Since Python 3.6 `logging.FileHandler`'s `filename` argument can be a `PathLike` object. Same for `FileHandler`'s subclasses.
`logging.basicConfig` passes its `filename` argument to a `FileHandler`, so this can be a `PathLike` object too.
Finally, `logging.config.fileConfig` passes its `fname` argument to `ConfigParser.read`, which also takes a `PathLike` since version 3.6.1.
Prior to this change, the following code did not pass mypy checks under Python 3.6:
```python
import logging
from pathlib import Path
p = Path("/foo/bar")
handler = logging.FileHandler(p)
```
=> Support PathLike arguments in the logging module

.flake8
Not sure why, but it did checked .git files and references in my .git  folder. I suppose branch naming might be the issue, but still ;)
```
ls -l .git/refs/remotes/upstream
razem 20
-rw-rw-r-- 1 fizyk fizyk 41 wrz  7 13:34 connectionpoll
-rw-rw-r-- 1 fizyk fizyk 41 paź  5 16:18 master
-rw-rw-r-- 1 fizyk fizyk 41 wrz  7 13:34 release-0.590
-rw-r--r-- 1 fizyk fizyk 41 paź 27  2017 release-mypy-0.521
-rw-rw-r-- 1 fizyk fizyk 41 wrz  7 13:34 setup.py
```
=> skip .git files from linting with flake8

stdlib/3/urllib/parse.pyi
The `url` argument to `urllib.parse.urljoin` can be `None`.
=> Set urllib.parse.urljoin url argument to optional

stdlib/2and3/difflib.pyi
difflib functions accept unicode as well.
=> Fix _StrType in difflib in Python 2.

stdlib/3/_ast.pyi
I've just found that the `level` attribute of `ImportFrom` is typed as an optional, so I have to test if it is None to gain static type safety. 
That's kind of confusing for the conflicts against my observations from `ast.parse` in Python2.7/3.5+.
Although in [Python-asdl](https://github.com/python/cpython/blob/master/Parser/Python.asdl) the  ASDL is defined as `ImportFrom(identifier? module, alias* names, int? level)`, this 
https://github.com/python/cpython/blob/97cf0828727ac2a269c89c5aa09570a69a22c83c/Python/ast.c#L3311
tells that `level` cannot be `None`(even if you assign it with a NULL).
`ImportFrom(identifier? module, alias* names, int level)` should be okay.
I wonder if there should be a change in Python-asdl?
=> ImportFrom level cannot be optional

stdlib/2/json.pyi
PR #2516 aimed to widen the accepted file argument to json.dump, but
since `IO` is invariant in its argument, it actually disallowed
passing binary files.
=> Allow json.dump to dump to BinaryIO again

stdlib/3/inspect.pyi
The documentation (https://docs.python.org/3/library/inspect.html#inspect.getfullargspec) says, "varargs is the name of the * parameter or None if arbitrary positional arguments are not accepted. varkw is the name of the ** parameter or None if arbitrary keyword arguments are not accepted."
=> Fix py3 types of inspect.FullArgSpec.var(args|kw)

third_party/build/METADATA.tmpl, third_party/build/WHEEL.tmpl, third_party/build/build-dist.py
Part of #2491 
This script allows to build third-party stubs packages as stubs-only distributions. Usage:
```
python3.7 build-dist.py <package>
```
A wheel will be built into `third-party/build/dist`.
=> Build script for third-party distributions

stdlib/2and3/tarfile.pyi
Working with `ExitStack.enter_context` was giving me:
```
Argument 1 to "enter_context" of "ExitStack" has incompatible type "TarFile"; expected "ContextManager[<nothing>]"
```
(hopes the formatting is fine and such)
=> Add context manager to tarfile.TarFile

stdlib/3/unittest/__init__.pyi
In Python 3, just as in Python 2, the expected exception argument to
assertRaises() and assertRaisesRegex() must be a subtype of
BaseException, not just of Exception.
Closes #2593
=> unittest.TestCase.assertRaises(): BaseException

stdlib/2/typing.pyi
See https://github.com/rominf/ordered-set-stubs/issues/1:
```
class OrderedSet(MutableSet[T], Sequence[T]): ...
```
works in Python 3, but not in Python 2 -- this fixes that.
(I haven't run the tests yet -- if they show problems with this I may just withdraw this.)
=> Move Sized earlier in the bases of Sequence

stdlib/2and3/struct.pyi
There does not seem to be an easy way to express that the array needs to be of a 1-byte type ('b', 'B', or 'c' in Python 2 only), so it is a bit more permissive than it should be.
=> Allow array[int] as a valid input to struct.unpack().

stdlib/2and3/ctypes/__init__.pyi
Fixes the issue discussed here: https://github.com/python/typeshed/pull/1906#discussion_r234798828
=> Let ctypes._CData.from_buffer[_copy] accept any buffer object

CONTRIBUTING.md
Also, don't explicitly ask for people to ask for missing packages.
Closes #2573
=> Accept upstream stubs when receiving no response

third_party/2and3/pytz/__init__.pyi
The `VERSION` variable was missing from the pytz stubs, but it can be useful for applications that want to report which version of pytz they are using, for troubleshooting purposes.
=> Add stub for pytz.VERSION

third_party/2and3/requests/adapters.pyi
There is a lot more that can be done here (a LOT of these types are implied `Any` which almost certainly too loose).  I do not have time at the moment to dig too deeply into the requests source to unravel all of the types, but `BaseAdapter.send` and `HTTPAdapter.send` should have the same signature anyway...
The docstrings are:
BaseAdapter:
```py
def send(self, request, stream=False, timeout=None, verify=True,
cert=None, proxies=None):
"""Sends PreparedRequest object. Returns Response object.
:param request: The :class:`PreparedRequest <PreparedRequest>` being sent.
:param stream: (optional) Whether to stream the request content.
:param timeout: (optional) How long to wait for the server to send
data before giving up, as a float, or a :ref:`(connect timeout,
read timeout) <timeouts>` …
```
=> Update types for requests.adapters

stdlib/2and3/zipfile.pyi
https://github.com/python/cpython/blob/2.7/Lib/zipfile.py#L310
https://github.com/python/cpython/blob/3.7/Lib/zipfile.py#L339
=> zipfile.ZipInfo.__init__ is the same on py2/py3

stdlib/3/posix.pyi
The posix module in Python 3 lacks some attributes that are present in both os/__init__.pyi and Python 2's posix.pyi.
We should probably consider in the future to just import all of posix with `from posix import *` in `os/__init__.pyi`.
=> Posix Attributes

stdlib/2/types.pyi, stdlib/3/types.pyi
`types.CodeType.co_filename` cannot be `None`.
=> types.CodeType.co_filename isn't Optional.

stdlib/2and3/logging/__init__.pyi
- The `args` argument of `makeRecord` is passed to `LogMessage`, so passing a `Tuple` in is fine as well.
- `LogRecord.args` can be any mapping, see https://bugs.python.org/issue21172
=> Fix handling of logging args

third_party/2and3/click/decorators.pyi
This adds `Optional` around `Callable[...]`.
Fixes https://github.com/python/typeshed/issues/2615
=> decorators.pyi: Add Any to Callable[]

stdlib/2/typing.pyi
This reverts commit 4dc21f04dd8c797c20325088837ccab182d5679c.
Fixes #2655.
=> Revert "Move Sized earlier in the bases of Sequence (#2602)"

CONTRIBUTING.md
This pull request modifies the contribution guidelines to state that pull requests should prefer using `object` over `Any` whenever possible.
In particular, I think there's never really a case where you'd want to use `Any` as a function argument type in stubs -- whenever you do, `object` should suffice instead.
Typing stubs this way probably won't impact most people, but does make life a bit easier for people (like me) who want to restrict/forbid the use of Any as much as possible.
I'm hoping that this is an uncontroversial change -- iiuc avoiding the use of `Any` is already a sort of informal guideline anyways. But if people think this needs more discussion first, I'd be happy to shelve this PR and open an issue for discussion instead.
=> Make contribution guidelines state when to use (and not use) 'Any'

stdlib/2/os/__init__.pyi, stdlib/2/os/path.pyi, stdlib/3/os/__init__.pyi, stdlib/3/os/path.pyi, stdlib/3/posix.pyi
In python 3, posix.stat_result is a re-export of os.stat_result, while
in python 2 it was the reverse. Update typeshed to reflect this.
In some sense this arguably should not matter? It impacts mypyc, though
which perhaps takes typeshed a little too seriously.
=> Move posix.stat_result to os.stat_result on python 3

stdlib/2and3/errno.pyi
`ENOTSUP` has the same value as `EOPNOTSUPP`, but is a fairly commonly-used alias and is present in both 2.7 and current 3.x.
=> Add missing ENOTSUP alias to errno

third_party/3/typed_ast/ast27.pyi, third_party/3/typed_ast/ast3.pyi
We recently cut a new-ish release of typed-ast that [adds a new field][0] named `kind` to the `ast27.Str` and `ast3.Str` classes. This field stores whatever string modifiers (like `b` or `u`) were present on the original string.
As a note, I've confirmed that this field is indeed a str (and not bytes) for ast27's Str class.
[0]: https://github.com/python/typed_ast/pull/49
=> Add Str.kind field to typed_ast stubs

stdlib/2and3/argparse.pyi
`_SubParsersAction` sets `choices` as an alias for `_name_parser_map`, see https://github.com/python/cpython/blob/a11d44056e4f9b64d28efec295e1c1c45d4cb9e1/Lib/argparse.py#L1097
=> Set correct type for _SubParsersAction.choices

stdlib/3/asyncio/streams.pyi
=> Fixing type for asyncio.StreamWriter reader init parameter (#2718)

stdlib/2and3/logging/__init__.pyi
On Python 3.7:
```
>>> import inspect, logging
>>> adapter = logging.LoggerAdapter(logger=logging.getLogger(None), extra={})
>>> inspect.signature(adapter.log)
<Signature (level, msg, *args, **kwargs)>
```
On Python 2.7:
```
>>> inspect.getargspec(adapter.log)
ArgSpec(args=['self', 'level', 'msg'], varargs='args', keywords='kwargs', defaults=None)
```
=> LoggerAdapter.log argument lvl -> level

stdlib/3/itertools.pyi
The only constraint on the return value of a predicate is to be "boolable".
Because `bool` recives an object in the constructor https://github.com/python/typeshed/blob/master/stdlib/2and3/builtins.pyi#L803 this is a more accurate description of a predicate.
=> Use a more accurate type for predicates in itertools

stdlib/2and3/zipfile.pyi
This makes it match ZipInfo.filename and also actual behavior.
=> Make ZipFile.NameToInfo use Text as the key type

stdlib/2/json.pyi
A None value for indent means the most compact representation (no newlines), it is also the default value.
=> Fix type of indent in JSONEncoder

stdlib/2and3/argparse.pyi
The default value of metavar in  `argparse.Action` is `None`, therefore `argparse.Action.metavar` and the metavar argument of `argparse.ArgumentParser.add_argument` should be `Optional`.
https://github.com/python/cpython/blob/master/Lib/argparse.py#L809
https://github.com/python/cpython/blob/2.7/Lib/argparse.py#L779
=> Make metavar in argparse be Optional.

stdlib/2and3/logging/handlers.pyi
I've noticed that the stub for `TimedRotatingFileHandler` from `logging.handlers` module does not inherit from the base `Handler` class in python 2 case, which causes mypy to report errors when, for example, you try to add an instance of this handler to a logger.
=> logging: inherit TimedRotatingFileHandler from Handler

third_party/3/pkg_resources/__init__.pyi
To avoid
```
error: "Distribution" has no attribute "PKG_INFO"
```
This is the corresponding implementation:
https://github.com/pypa/setuptools/blob/8f82e5077e2d3aab14aa3da636f79d37ff6d7ed7/pkg_resources/__init__.py#L2531
=> pkg_resources Add PKG_INFO str attribute for Distribution class

third_party/2and3/click/core.pyi, third_party/2and3/click/decorators.pyi
`click.Group` class and `click.command` / `click.option` decorators are affected as well
=> Add hidden and deprecated click.Command options

CONTRIBUTING.md
Now that stubgen is decently documented, we can point the link to the docs instead of the source code.
I also slightly rephrased the sentence to add a bit more info.
=> Update stubgen link and add a bit more info

stdlib/2/__builtin__.pyi, stdlib/2and3/builtins.pyi
This was originally done in #2557, but got lost in #2533.
=> Make SyntaxError.offset be optional (again)

stdlib/2and3/codecs.pyi
When mypy sees this code:
```python
codecs.getincrementaldecoder("utf-8")(errors="strict")
```
It triggers this spurious error:
```
Unexpected keyword argument "errors"
```
This PR fixes that problem.
=> Support the errors arg in codecs factory functions.

stdlib/3/email/charset.pyi
The python3 charset stubs didn't include certain necessary module level
constansts (like `QP`) and too-tightly defined the arguments to some of
the functions in the module. This is no longer the case.
Fixes #2767.
=> Improve the stubs in charset.pyi under python3.

stdlib/3/asyncio/events.pyi
* host may be None to bind to all interfaces.
* If sock is given, host and port shouldn't be specified.
=> Fix signature of asyncio.create_server.

stdlib/2/__builtin__.pyi, stdlib/2and3/builtins.pyi
Without this change, here's the problem I encountered:
```
$ cat testmypy.py
def is_c_contiguous(m: memoryview):
return m.c_contiguous
print(is_c_contiguous(memoryview(b'abc')))
```
```
$ python testmypy.py
True
```
```
$ mypy testmypy.py
testmypy.py:2: error: "memoryview" has no attribute "c_contiguous"
```
With this change, the problem is fixed.
I'm not sure why memoryview is defined in two modules. In doubt, I stuck with the existing style.
=> Support *contiguous attributes of memoryview.

stdlib/2/typing.pyi
Both type and field names of `NamedTuple` can be specified with unicode strings now.
This fixes #2761.
=> Make `NamedTuple` accept `Text` names (#2761).

third_party/3/orjson.pyi
=> orjson.pyi

requirements-tests-py3.txt, stdlib/2/os/__init__.pyi, stdlib/3/os/__init__.pyi
Pytype release 2019.02.13 fixed the bug that
necessitated this workaround.
=> Remove pytype workaround in os/__init__.pyi.

stdlib/3/posix.pyi
This caused problems with new semantic analyzer in mypy (and didn't match runtime)
=> Fix named tuple name in posix.pyi

third_party/2and3/yaml/cyaml.pyi
This pull request wants to resolve #2665. There are some details:
- `CDangerLoader` and `CDangerDumper` is not showed in [document](https://pyyaml.org/wiki/PyYAMLDocumentation). So I add `# undocumented` comment.
- `CEmitter` is defined in Cython extension file [_yaml.pyx#L935](https://github.com/yaml/pyyaml/blob/master/ext/_yaml.pyx#L935). Some variables like `canonical` is just used as a condition, I think it can be any type.
```Python
if canonical:
yaml_emitter_set_canonical(&self.emitter, 1)
```
- Others are defined in [cyaml.py](https://github.com/yaml/pyyaml/blob/master/lib3/yaml/cyaml.py#L36).
=> Add some missing annotations in cyaml

stdlib/2and3/socket.pyi
timeout=None puts the socket into blocking mode.
```
import socket
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
assert s.gettimeout() is None
s.settimeout(None)
assert s.gettimeout() is None
assert socket.getdefaulttimeout() is None
socket.setdefaulttimeout(None)
assert socket.getdefaulttimeout() is None
socket.setdefaulttimeout(0.01)
try:
s = socket.create_connection(('github.com', 443))
except socket.timeout:
pass
s = socket.create_connection(('github.com', 443), timeout=None)
```
Read <https://bugs.python.org/issue18417> and the referenced other
issues for more gory details.
This is split from <https://github.com/python/typeshed/pull/2688/commits/46d856847e5bcced97b974fa9060212e9cb71674>
=> socket: timeout may be None

stdlib/2and3/pdb.pyi
Add `Restart` class to `pdb.pyi`, which has no internal implementation.
|head|location|
|---|---|
|master|https://github.com/python/cpython/blob/master/Lib/pdb.py#L85
|3.7|https://github.com/python/cpython/blob/3.7/Lib/pdb.py#L85|
|2.7|https://github.com/python/cpython/blob/2.7/Lib/pdb.py#L18|
=> Add Restart to pdb.pyi

stdlib/3/asyncio/events.pyi
* local_addr and server_hostname are optional and default to None.
* If sock is given, none of host, port, family, proto, flags and
local_addr should be specified.
=> Fix signature of asyncio.create_connection.

README.md
The README suggests that when you've checked out `typeshed` as a submodule of `mypy` you can set `PYTHONPATH=..` before running tests ... but this causes slightly odd errors (like `ImportError: cannot import name 'WrapperDescriptorType' from 'types'`). It turns out that this is because we should instead be using the `MYPYPATH` variable.
=> README.md suggests running tests with PYTHONPATH instead of MYPYPATH

stdlib/3/enum.pyi, third_party/2/enum.pyi
This pull request wants to resolve #2766. Some details list here:
Python [enum doc](https://docs.python.org/3/library/enum.html#supported-sunder-names)
> Supported `_sunder_` names
> 
>  - `_name_` – name of the member
>  - `_value_` – value of the member; can be set / modified in `__new__`
>  - `_missing_` – a lookup function used when a value is not found; may be overridden
>  - `_ignore_` – a list of names, either as a `list(`) or a `str()`, that will not be transformed into members, and will be removed from the final class
>  - ` _order_` – used in Python 2/3 code to ensure member order is consistent (class attribute, removed during class creation)
>  - `_generate_next_value_` – used by the Functional API and by auto to get an appropriate value for an enum member; may be overridden
> …
=> feat: sunder names in enum

third_party/2and3/markupsafe/__init__.pyi
Removed extraneous import statement that was redefining three symbols in markupsafe/__init__.py. This redefinition triggered type checking/linting errors.
=> Removed extraneous import statement

stdlib/3/_ast.pyi, stdlib/3/ast.pyi
Specifically:
- New classes `TypeIgnore`, `FunctionType`, `Constant` and `NamedExpr`
- New `AST` attributes `end_lineno`, `end_col_offset`, and `type_comment`
- New attribute `Module.type_ignores`
- New attribute `Str.kind` (that's new in 3.7 actually)
- New keyword args for `ast.parse()`: `type_comments=<bool>` and `feature_version=<int>`
I had to adjust the return type of `ast.parse()` from Module to `AST`, which is more truthful anyways.
=> Support new ast features and node types introduced in Python 3.8

stdlib/2/__builtin__.pyi, stdlib/2and3/builtins.pyi
Also, use object instead of Any for values list
=> Use protocol for print() file argument

stdlib/3/importlib/__init__.pyi
pytype has trouble resolving unused imports, since it looks at usage
to distinguish submodules from other imports.
=> Remove an unused import from stdlib/3/importlib/__init__.pyi.

requirements-tests-py3.txt, tests/pytype_blacklist.txt
With version 2019.03.15, pytype is able to parse this file.
=> Remove asyncio.tasks from the pytype blacklist.

stdlib/2and3/tarfile.pyi
This function is defined up to Python 3.7 (albeit deprecated in Python 3):
https://github.com/python/cpython/blob/69785b212765f0943eb4611e1886436bdd01ade0/Lib/tarfile.py#L259.
While I was in the file, I removed extra blank lines around things.
=> Add tarfile.filemode.

stdlib/2and3/pdb.pyi
Based on: https://docs.python.org/3/library/pdb.html#pdb.Pdb,
with the one difference that the `skip` argument to the
constructor is present in 2.7 despite being listed as new in 3.1.
=> Add missing class pdb.Pdb.

stdlib/2/__builtin__.pyi, stdlib/2and3/builtins.pyi
See also PEP 415: https://www.python.org/dev/peps/pep-0415/
Fixes #2875.
=> Add missing BaseException.__suppress_context__ attribute

stdlib/3/re.pyi
This is only available before python 3.7 based on:
https://github.com/python/cpython/blob/3.6/Lib/re.py#L283
https://github.com/python/cpython/blob/3.7/Lib/re.py
=> [re] Add attribute '_pattern_type' to re.

third_party/2and3/click/exceptions.pyi
This was added to the 7.0 release of click ([PR for reference](https://github.com/pallets/click/pull/1098)).  This may not make sense, as the `__init__` stub for click appears to be setting the version to `6.6`.
=> [third_party/click] add Exit exception definition

stdlib/2/__builtin__.pyi, stdlib/2and3/builtins.pyi
This change is based on python 3 doc: https://docs.python.org/3/library/functions.html#compile
"source can either be a normal string, a byte string, or an AST object"
=> [builtins] Add 'AST' type to 'source' parameter for 'compile(source, filename, mode, flags=0, dont_inherit=False, optimize=-1)'

stdlib/2/_ast.pyi, stdlib/3/_ast.pyi
I've been working on adding type annotations to the pandas library and was running into:
```sh
error: Module has no attribute "excepthandler"
```
With mypy type checking. I think this was a simple oversight in the stub file and have added as such. 
Tests pass locally before and after. Let me know if there's anything else I need to do!
=> Added excepthandler to ast stubfiles

stdlib/2and3/struct.pyi
Currently seeing the following error from `mypy`, which I think this should solve:
foo.py:47: error: Argument 1 to "pack_into" of "Struct" has incompatible type "mmap"; expected "Union[array[Any], bytearray, memoryview]"
=> Add mmap as a valid buffer type.

third_party/2and3/simplejson/__init__.pyi
This puts the expected signature of `simplejson.loads` with what is accepted by the library in the same way that the standard `json` is defined.
=> Accept bytes as 1st argument of `simplejson.loads`

.travis.yml, requirements-tests-py3.txt, tests/pytype_blacklist.txt, tests/pytype_test.py
With today's release, pytype is able to fully load
`stdlib/3/collections/__init__.pyi`, so the test no longer needs the
ability to partially parse stubs using the pytd tool. Removing this
functionality allows the test code to be simplified considerably.
=> Update pytype_test to remove now-unnecessary parse-only functionality.

stdlib/3/types.pyi
Fixes #2898 with `f_frace_lines -> f_trace_lines`
=> Fix typo in FrameType 3.7 attributes

CONTRIBUTING.md
This hopefully reflects the consensus from the discussion we had at the typing meetup earlier today. The effect of the change is to make us more liberal in accepting undocumented objects in stubs.
I ended up rewriting the whole section to make it more concrete, and removed some extraneous material that wasn't directly relevant to the topic of the section. The text now has separate paragraphs detailing what should always and sometimes be included, and another paragraph of motivation.
=> reword "What to include"

third_party/2/six/moves/email_mime_base.pyi, third_party/2/six/moves/email_mime_multipart.pyi, third_party/2/six/moves/email_mime_nonmultipart.pyi
As a followup to the work done in #2767 and #2830, and to address a
piece of #66, most of the email_mime submodules aren't typed in six
under python2, only python3. Now they are.
=> Add six.moves types for email_mime sources.

stdlib/3/unittest/__init__.pyi
It looks `stream` property is `IO[str]` type, not `TextIO` because it calls `write` and other methods. So I changes it.
And I also add types for other attributes in `TextTestResult` and `TextTestRunner`.
=> Fix TextTestResult and TextTestRunner in unittest

stdlib/2/typing.pyi, stdlib/3/typing.pyi
=> Add @typing.type_check_only

stdlib/2/os/__init__.pyi, stdlib/2/os/path.pyi, stdlib/2/os2emxpath.pyi, stdlib/2and3/macpath.pyi, stdlib/2and3/ntpath.pyi, stdlib/2and3/posixpath.pyi, stdlib/3/os/__init__.pyi, stdlib/3/os/path.pyi
Keep it str on win32 to avoid breaking win32-specific code that relies
on it.
=> Make os.altsep Optional on non-win32 platforms

stdlib/3/unittest/__init__.pyi
assertRaisesRegexp is the old name of assertRaisesRegex, they are the
same, just that the old one is deprecated.
Closes #2925
=> Correct the type signature of assertRaisesRegexp

stdlib/3/http/cookiejar.pyi
Straightforward addition of `__init__` for `http.cookiejar.Cookie`. It looks like the `domain` attribute has also been missing? It seems to also be undocumented: https://docs.python.org/3/library/http.cookiejar.html#cookie-objects.
=> Add initializer for http.cookiejar.Cookie

third_party/2and3/requests/sessions.pyi
Not sure why it is annotated as a union. Union would lead to type errors when accessing any field that's presented in `RequestsCookieJar` but not `MutableMapping`.
=> Properly type `requests.Session.cookies`

stdlib/2and3/logging/handlers.pyi
`WatchedFileHandler` extends `FileHandler` in the cpython implementation and in the [language docs](https://docs.python.org/2/library/logging.handlers.html#watchedfilehandler).
Updating the type stub to reflect this
=> Change WatchedFileHandler to inherit from FileHandler

stdlib/3/urllib/request.pyi
It's not really documented (https://docs.python.org/3/library/urllib.request.html#urllib.request.HTTPRedirectHandler.redirect_request), but logically a message is a str, and reading the code for the stdlib confirms that it's intended to be a str.
=> fix type of msg argument to HTTPRedirectHandler.redirect_request

CONTRIBUTING.md
> Black, your uncompromising #Python code formatter, was a project
> created with the community in mind from Day 1. Today we moved it under
> the PSF umbrella. It's now available on GitHub under
> https://github.com/python/black/ . You install and use it just like
> before.
https://twitter.com/llanga/status/1123980466292445190
=> Update Black URL

stdlib/3/typing.pyi
According to Ivan, PEP 544 intentionally did not specify whether method conformance check in protocol inference should look at parameter names. For example, it's up to the type checker to decide whether a class with method defined as `def foo(self, x: int)` would implement a protocol with method `def foo(self, y: int)`.
Mypy decided to ignore parameter names altogether, but we Pyre team decided to be more strict and refuse to match different parameter names (as it is unsound to do so when those methods are invoked with named parameters). Since Pyre also rely on the typeshed stubs, we want to make sure at least the important stubs on typeshed conform to our standard. 
This PR changes `Container.__contains__` to use dunder (i.e. positional-only) parameter name specified in PEP484. This …
=> Use dunder parameter name in `Container.__contains__`

third_party/2and3/click/types.pyi
`click.types.DateTime` appears to have been added in 7.0, and as near as I can tell (from https://github.com/pallets/click/issues/693) the existing stubs are based on click 6.6. This is probably far from completely what has changed between 6 and 7, but I don't have time at the moment to do a more thorough check for what might have changed.
=> add click.types.DateTime to click stubs

third_party/2and3/bleach/__init__.pyi, third_party/2and3/bleach/linkifier.pyi, third_party/2and3/bleach/sanitizer.pyi
I mentioned [in a comment a few weeks ago](https://github.com/python/typeshed/pull/2709#issuecomment-483120729) that I was hitting some errors on my codebase from the new Bleach stubs. This was mostly due to the stubs being very specific and using `List[]` for various arguments. These arguments are generally used for `x in y` checks, so I switched all of them to use the `Container[]` protocol class instead.
There were also a couple of other minor, similar changes, and I fixed a couple of typos (in a separate commit to make it easier to see for review, but they could be squashed together if you like).
(I'll ping @srittau since he wrote the original stubs)
=> Bleach stubs: fix typos, use protocol classes

requirements-tests-py3.txt, tests/pytype_blacklist.txt
Removes files that are parseable with the most recent release.
=> Remove some files from pytype's third_party blacklist.

stdlib/3/asyncio/futures.pyi
Fix the annotation on `Future`'s `__init__` method.  Per the source code, this
is actually suppose to be `Optional`
Tested by running against IG's codebase and confirmed that the one instance
where we referencing the `__init__` no longer throws an error.
Also, this fixes the issue referenced in #2959
=> Fix Future.__init__'s loop variable annotation

tests/pytype_blacklist.txt, third_party/2/gflags.pyi
Having TODOs at a different level of indentation than
the surrounding lines trips up pytype.
=> Adjust indentation of TODOs in third_party/2/gflags.pyi.

stdlib/2/subprocess.pyi
This was already added for python 3 but not for python 2.
=> Add subprocess.list2cmdline for python 2

third_party/2and3/click/core.pyi, third_party/2and3/click/decorators.pyi, third_party/2and3/click/termui.pyi
This adds a new argument `show_choices` added to command options by click 7.0 :
- add the argument `show_choices` and the corresponding attribute to class `Option` annotation.
It is present in the class signature even if it is not yet in the list of described arguments: https://click.palletsprojects.com/en/7.x/api/#click.Option
- add same argument to overloaded annotations of decorator `option`  that has the same arguments as `Option`: https://click.palletsprojects.com/en/7.x/api/#click.option
=> Add new show_choices argument to click options

stdlib/2/__builtin__.pyi, stdlib/2and3/builtins.pyi
Fixes https://github.com/python/typeshed/issues/2976
cc @serhiy-storchaka
=> Add an optional opener parameter to open() function

third_party/2and3/click/termui.pyi
This previously was missing a return type and therefore defaulting to `Any`, but it actually returns a `str`.
=> Have click.style return a str

third_party/2and3/google/protobuf/descriptor_pb2.pyi, third_party/2and3/google/protobuf/map_unittest_pb2.pyi, third_party/2and3/google/protobuf/test_messages_proto2_pb2.pyi, third_party/2and3/google/protobuf/test_messages_proto3_pb2.pyi, third_party/2and3/google/protobuf/type_pb2.pyi, third_party/2and3/google/protobuf/unittest_custom_options_pb2.pyi, third_party/2and3/google/protobuf/unittest_no_arena_pb2.pyi, third_party/2and3/google/protobuf/unittest_pb2.pyi, third_party/2and3/google/protobuf/unittest_proto3_arena_pb2.pyi
The main purpose of this change is to get the stubs into a
form that pytype will support with its next release. Since
these stubs already mostly use fully qualified names, this
will also increase consistency.
=> Always use fully qualified names to refer to nested classes.

third_party/2/six/moves/urllib/request.pyi, third_party/3/six/moves/urllib/request.pyi
`parse_http_list` and `parse_keqv_list` were added to `six.moves.urllib.request`
in version 1.11 (see corresponding [pull request](https://github.com/benjaminp/six/pull/203)).
These functions should be added to the stubs for `six.moves.urllib.request`.
=> Add parse_{http,keqv}_list to six.moves.urllib.request

stdlib/2/_ast.pyi, stdlib/2/ast.pyi
These variables are already imported from `_ast.pyi`.
=> Remove redundant variable definitions in ast module

stdlib/3/inspect.pyi
The `arguments` attribute of the `BoundArguments` is specified as an "ordered, mutable mapping (collections.OrderedDict)"
not just a mutable mapping: https://docs.python.org/3/library/inspect.html#inspect.BoundArguments.arguments
=> Bound arguments are ordered

stdlib/2and3/csv.pyi
resolves #2987 
- make `csv.DictReader` accepting a subclass of `csv.Dialect` as dialect argument.
- fix the return type of `Sniffer.sniff`, change from `Dialect` to`Type[Dialect]`.
From the example code and the doc of `Sniffer.sniff`, https://docs.python.org/3/library/csv.html#csv.Sniffer.sniff
>  sniff(sample, delimiters=None)
> 
>  Analyze the given sample and return a `Dialect` subclass reflecting the parameters found. If the optional delimiters parameter is given, it is interpreted as a string containing possible valid delimiter characters.
```Python
with open('example.csv', newline='') as csvfile:
dialect = csv.Sniffer().sniff(csvfile.read(1024))
csvfile.seek(0)
reader = csv.reader(csvfile, dialect)
```
The return type of Sniffer.sniff should be `Type[Dialect]` instead of `Dialect`. …
=> Improve typing of dialect parameter in csv module

third_party/2and3/click/README.md, third_party/2and3/click/core.pyi, third_party/2and3/click/exceptions.pyi, third_party/2and3/click/termui.pyi, third_party/2and3/click/testing.pyi
Closes #3020.
---
This is mostly based on differences I noticed in `git diff`, not sure if there's an easy way to verify that I've got them all.
Also, this is my first PR here so please let me konw if I've missed something 😄
=> Update Click to 7.0

third_party/2and3/click/core.pyi, third_party/2and3/click/parser.pyi
Since these properties do not have a setter, be explicit with the
`@property` decorator. This will allow type checkers to see that
assignment of these attributes is an error.
See https://github.com/python/typeshed/pull/3027#discussion_r289623016
for some related context.
=> click: Use property decorator for read-only properties

stdlib/2and3/pwd.pyi
I believe the CPython structseq type is slightly better represented by a custom tuple subclass.
=> Improve typing of pwd.struct_passwd.

.travis.yml, stdlib/2and3/curses/__init__.pyi, tests/mypy_test.py
cc @JukkaL
This also removes two redundant definitions star-imported from `_curses`.
=> Add new semantic analyzer to mypy tests

stdlib/2/cookielib.pyi, stdlib/3/http/cookiejar.pyi
The method is defined here:
https://github.com/python/cpython/blob/e36ed475ea429f7cc80a4d65f80b44686a74b246/Lib/http/cookiejar.py#L1864
=> Add undocumented but used method LWPCookieJar.as_lwp_str.

stdlib/2/types.pyi
The py3 stub already has this constructor, but it was missing from the py2 stub.
I got the argument order from
https://github.com/python/cpython/blob/2bfc2dc214445550521074f428245b502d215eac/Objects/codeobject.c#L263
and the types from the attributes already in the stub.
=> Add missing constructor to types.CodeType.

stdlib/2and3/traceback.pyi
This looks like a last example where type comment syntax is still used (apart from some commented-out code in `pydoc`).
=> Use type annotation syntax in traceback module

third_party/2and3/pyre_extensions.pyi
Because it was decided (in https://github.com/python/typing/pull/636) that CallableParametersVariable (now renamed ParameterSpecification) wasn't quite ready for inclusion in `typing_extensions` we went ahead and published our implementation under a new PyPI package, `pyre_extensions` (https://pypi.org/project/pyre-extensions/).  
This is the corresponding typeshed stub.
=> Adding stubs for pyre_extensions

stdlib/2and3/select.pyi, stdlib/3/selectors.pyi
At the time of creating type stubs for the stdlib `select.pyi` and `selectors.pyi`, there was no support for structural subtyping via protocols. So, the stubs had to use `Any` (no type safety) and `socket.socket` (only a subset of supported types).
Now that protocols are widely supported (https://www.python.org/dev/peps/pep-0544/ and https://mypy-lang.blogspot.com/2017/10/mypy-0530-released.html), the exact types can be expressed properly.
Here, we use the naming convention established in `faulthandler.pyi`:
https://github.com/python/typeshed/blob/1f740a7926049cbddc8d1b795c66381104a96aa6/stdlib/3/faulthandler.pyi#L5-L6
This properly fixes https://github.com/python/typeshed/issues/482.
=> Update select and selectors to use _HasFileno protocol

stdlib/2and3/ssl.pyi
The `cadata` argument can be a bytes-like object to load DER-encoded certificates.
https://docs.python.org/3.7/library/ssl.html#ssl.create_default_context
=> ssl.pyi: fix types of cadata argument

stdlib/3/ast.pyi
With `mode="exec"` (which is the default mode), `ast.parse` always returns an `ast.Module`. It's irritating to always have to `cast` this.
Verified this change with a small file:
```
import ast
def foo() -> ast.Module:
return ast.parse("a = 1")
```
This raises an error (expected Module, got AST) on typeshed master, passes with this PR.
Also added explicit `mode="exec"`, same results.
With `mode="eval"`, error on both master and this PR.
=> Overload ast.parse to recognize that mode=exec means Module return.

stdlib/2and3/socket.pyi
The Pull Request #1121 added the `AddressFamily` type to `socket.pyi` for Python 3.4+, so constants such as `AF_INET` are correctly represented as being an enum member rather than an int.
Various functions in the socket module can accept either an int or an `AF_*` enum member as arguments, which is allowed by the int argument type. However the `getaddrinfo` function returns an `AddressFamily` member rather than an int in the first position of its list members, so code that access enum specific members such as the `name` attribute causes a typing error to be found.
This change corrects the return type of `getaddrinfo` but leaves the family parameters as int, given that `AddressFamily` members are `IntEnum` and only ever treated as `int`s internally.
=> Represent the use of AddressFamily in socket.getaddrinfo

stdlib/3/http/cookies.pyi
Morsel does cast any value to string and therfor any is the correct
typehint. For some keys other types then strings are more
appropiate anyway, max-age can take an integer (unix time) and http-only
a boolean.
Closes #3059
=> Change http.cookie.Morsel to Dict[str, any]

tests/pytype_test.py
While working on https://github.com/python/typeshed/pull/3062, the `tests/pytype_test.py` file has been failing and it was realized that the file could be refactored (https://github.com/python/typeshed/pull/3062#issuecomment-502501728).
This does the following to try to improve the readability while preserving all original behavior:
* Mark as Python 3.
* Use `.format()` instead of `%` for string interpolation.
* Apply Black and isort.
* Add type hints.
* Use `raise SystemExit()` rather than manually managing return codes and calling `sys.exit()`.
* Move the high level logic into `main()` instead of `pytype_test()`.
* Make `run_pytype()` less generic. It no longer accepts generic `args`, because it does not need that much flexibility. This allowed removing `_parse()`.
* Extract out …
=> Refactor tests/pytype_test.py

stdlib/2and3/ssl.pyi
resolves #2770
In 2.7, https://github.com/python/cpython/blob/2b578479b96aa3deeeb8bac313a02b5cf3cb1aff/Lib/ssl.py#L337-L342
```Python
class Purpose(_ASN1Object):
"""SSLContext purpose flags with X509v3 Extended Key Usage objects
"""
Purpose.SERVER_AUTH = Purpose('1.3.6.1.5.5.7.3.1')
Purpose.CLIENT_AUTH = Purpose('1.3.6.1.5.5.7.3.2')
```
In 3.4, https://github.com/python/cpython/blob/3101b7076270756f8be699358c69c5d15ea2cc48/Lib/ssl.py#L313-L317
```Python
class Purpose(_ASN1Object, _Enum):
"""SSLContext purpose flags with X509v3 Extended Key Usage objects
"""
SERVER_AUTH = '1.3.6.1.5.5.7.3.1'
CLIENT_AUTH = '1.3.6.1.5.5.7.3.2'
```
=> ssl.pyi: fix ssl.Purpose definition in py3

stdlib/2/_functools.pyi, stdlib/2/functools.pyi, stdlib/3/functools.pyi
Reverts python/typeshed#2878
Caused problems in many real-world codebases. Proper support for `partial` will have to come from a plugin instead.
I've seen the following problems reported:
- Keyword arguments to partial() functions no longer work
- isinstance() checks on functools.partial no longer work
- Access to .func and other attributes no longer works
=> Revert "Define functools.partial as overloaded function instead of its own class"

stdlib/3/asyncio/base_events.pyi, stdlib/3/asyncio/events.pyi
I ran into a place in our code where we pass a (host, port) tuple to sock_connect. According to https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.sock_connect, the address argument is the same as that to socket.connect (https://docs.python.org/3/library/socket.html#socket.socket.connect), so I use the same type alias used for socket.
socket.connect also takes bytes according to our annotations, but from my experiments it seems that asyncio's version does not.
=> fix type of loop.sock_connect

stdlib/3/typing.pyi
Both are `None` if there were no groups matched. Also `lastgroup` will be `None` if the matched group was nameless.
The Python 2 versions of these annotations already used `Optional`.
=> Fix annotation of re.Match 'lastindex' and 'lastgroup' in Python 3

stdlib/2/__builtin__.pyi, stdlib/2and3/builtins.pyi
It is correctly marked as optional in python 3+, but not in python 2.7.  
I test this with 2.7.10:
```
chad$ python
Python 2.7.10 (default, Oct  6 2017, 22:29:07) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)] on darwin
>>> sorted([1,4,67,8], key=None)
[1, 4, 8, 67]
>>>
```
=> "key" argument of builtin function sorted should be optional in python 2.7

pyproject.toml, requirements-tests-py3.txt
The first stage of adding auto-formatters (https://github.com/python/typeshed/issues/3058), as described by https://github.com/python/typeshed/pull/3062#issuecomment-502809479. This allows users to use Black and isort, but we do not yet document how to do so nor do we enforce it.
We configure isort to work with Black and instruct both tools to use a line length of 130, per the consensus described in https://github.com/python/typeshed/issues/3058#issuecomment-502433305.
=> Install Black and isort autoformatters

third_party/2and3/click/termui.pyi
This resolves #3089, by restoring the default value to the `color` argument.
=> Restore default value to click.echo_via_pager

stdlib/3.7/dataclasses.pyi, third_party/3/dataclasses.pyi
If `metadata` is `None` the Field constructor replaces it with an empty mapping object, so this value can never be None.
https://github.com/python/cpython/blob/v3.7.3/Lib/dataclasses.py#L243
=> Make dataclasses.Field.metadata non-optional

stdlib/3/subprocess.pyi
This gives better types to subprocess.check_output and subprocess.run
by laboriously overloading using literals.
To support `run`, I turned `CompletedProcess` into `_CompletedProcess[T]`
with `CompletedProcess = _CompletedProcess[Any]`. I could pretty easily
be convinced that it would be better to just make `CompletedProcess`
generic, though.
I'd like to do the same for Popen but need to make mypy support
believing the type of `__new__` in order for that to work.
=> Use Literal overloads to give better types to subprocess

stdlib/2/sys.pyi, stdlib/3/sys.pyi
I believe that either all of the items are None or none of them are.
Reflect that in the type.
This was attempted initially in
https://github.com/python/typeshed/pull/246
but apparently mypy didn't allow unpacking given such a union, but it
does now (checked with mypy 0.711).
The (incorrect) TODO from that PR was removed in commit
25ac4d6af46104d0c7cb134ed09a61ca7092b62a but the commit message noted
that this change is desirable.
=> sys: refine the return type of sys.exc_info()

stdlib/2/subprocess.pyi
This makes it consistent with the changes in #3113
=> Make python 2 subprocess consistent with python 3

stdlib/3/_ast.pyi
It has been introduced in 3.5.2 in https://github.com/python/cpython/commit/f2c1aa1661edb3e14ff8b7b9995f93e303c8acbb
=> Fix ast.Constant availability

stdlib/2and3/warnings.pyi
See https://docs.python.org/3.7/library/warnings.html#warnings.warn_explicit
This fixes code which does
warnings.warn_explicit(warning, category=None, ...)
The stub for `warn` is already OK, but I think it's clearer to have an
overload there too.
=> warnings: ignore the type of category when message is a Warning

stdlib/2and3/xml/etree/ElementTree.pyi
If a literal "unicode" is passed, we can know statically that it's going
to be an str; otherwise it might still be "unicode" so can return either
str or bytes.
See:
https://docs.python.org/3/library/xml.etree.elementtree.html#xml.etree.ElementTree.tostring
=> xml.etree.ElementTree: use literal type for a more precise return value for tostring()

stdlib/2and3/zipfile.pyi
The `ZipFile.filename` data attribute is documented, but not included in the type stubs.
=> Add zipfile.ZipFile.filename

.travis.yml, tests/mypy_test.py
This runs mypy both with Python 3.7 and 3.8. In Python 3.8,
mypy switched from using typed-ast to using Python's built-in ast.
This patch ensures that both are tested.
=> Travis: run mypy with Python 3.8 as well

tests/pytype_test.py
This is a small cosmetic change. I want to encourage use of the
nicer-lookng pytype.config.Options.create() rather than
direct construction of the command-line args, so I'm changing
over all occurrences of the latter that I can find.
=> Use pytype.config.Options.create() for prettier code.

stdlib/2/__builtin__.pyi, stdlib/2and3/builtins.pyi
The following code works:
```py
>>> print(sys.version)
2.7.16 (default, Mar 11 2019, 18:59:25)
>>> def f(): pass
>>> print(f.__code__)
<code object f at 0x7f8534ecc8a0, file "<stdin>", line 1>
>>> isinstance(f.__code__, types.CodeType)
True
```
but it didn't type-check with `mypy --python-version 2.7`.
=> Allow function.__code__ in Python 2

stdlib/3/typing.pyi
Python 3.7.2 added missing type hint for the collections.OrderedDict which is missing the stub in the typeshed.
https://docs.python.org/3/library/typing.html#typing.OrderedDict
=> [stdlib][3] Add missing typing.OrderedDict generic stub

third_party/2and3/dateutil/rrule.pyi
`dateutil.rrule.rrule`'s `dtstart` and `until` flags are both compatible with `date` as well as `datetime` and will convert from the former to the latter. See [here](https://github.com/dateutil/dateutil/blob/master/dateutil/rrule.py#L439). 
I'm assuming that the typeshed should reflect the types as actually implemented, as opposed to how they're documented - `dtstart` is passingly referred to in the docs as a "date", which is a bit ambiguous but doesn't create any problems. But `until` is mis-documented, saying:
> If given, this must be a datetime instance specifying the upper-bound limit of the recurrence.
... even though the code will happily convert from a date to a datetime.
=> dateutil.rrule.rrule can take dates

stdlib/2and3/xml/etree/ElementTree.pyi
`xml.etree.ElementTree.ParseError`, in addition to the attributes inherited from `SyntaxError` includes a integer `code` (from xml.parsers.expat) and a `position` tuple containing the line and column of the error.
This adds both of these missing attributes.
See https://docs.python.org/3.7/library/xml.etree.elementtree.html#xml.etree.ElementTree.ParseError
*These attributes exist (undocumented) in Python 2.7.*
=> Add missing attributes to xml.etree.ElementTree.ParseError.

stdlib/2and3/logging/__init__.pyi
- `logThreads`
- `logMultiprocessing`
- `logProcesses`
All three are publicly documented (https://docs.python.org/3/howto/logging.html#optimization)
and have existed since Python 2.  (They were int in Python 2.)  Their cousin, `raiseExceptions`, is already present in `logging/__init__.pyi`.
=> Add hints for 3 globals from logging/__init__.py

requirements-tests-py3.txt
For https://github.com/python/typeshed/pull/3149.
=> Require the newest pytype version, with a pyi parser fix.

third_party/2and3/flask/app.pyi
[flask 1.1 changelog](
https://flask.palletsprojects.com/en/1.1.x/changelog/):
> Allow returning a dictionary from a view function. Similar to how returning a string will produce a text/html response, returning a dict will call jsonify to produce a application/json response.
See https://github.com/pallets/flask/pull/3111
=> flask: allow view func body to be dict

stdlib/2/htmlentitydefs.pyi
The code and documentation specifies the values specifically as
dictionaries.
=> Precise the type of Python 2 htmlentitydefs module

stdlib/3/asyncio/tasks.pyi
The stub for asyncio.as_completed declared it as taking a Sequence of
Futures. This was unnecessarily strict.
Just like asyncio.wait, asyncio.as_completed can be declared to take
an Iterable of Futures instead. Both these functions iterate over
their argument only once to store its items in a set, so an Iterable
is sufficiently strict. This has been true since the initial
implementation of the functions.
=> Declare asyncio.as_completed() as taking an Iterable

stdlib/2and3/token.pyi, stdlib/3/tokenize.pyi
In Python 3.7, tokenize.{COMMENT,NL,ENCODING} were moved to token and
imported into tokenize rather than defined there.
(https://docs.python.org/3.7/library/token.html#token.COMMENT)
=> Move some constants from tokenize to token in Python 3.7+.

third_party/2and3/werkzeug/exceptions.pyi
* Use Text for HTTPException.description
* Add Unauthorized.www_authenticate
* Remove wrong get_headers() overrides
=> Improve werkzeug exceptions slightly

third_party/2/tornado/testing.pyi
gen_test can accept a timeout parameter. See https://www.tornadoweb.org/en/branch5.1/testing.html#tornado.testing.gen_test.
=> Improve type of tornado.testing.gen_test.

stdlib/2/__builtin__.pyi, stdlib/2and3/builtins.pyi
Per the docs, globals/locals is an optional argument.
https://docs.python.org/3/library/functions.html#__import__
https://docs.python.org/2/library/functions.html#__import__
Additionally, globals/locals can be any mapping type, not only a dict.
Likewise, fromlist can be any sequence (the docs mention a tuple, not a
list).
The function returns a ModuleType, not Any.
Now matches the definition in stdlib/3/importlib/__init__.pyi.
=> Update __import__ function annotations

stdlib/2/SocketServer.pyi, stdlib/3/socketserver.pyi
This fixes #3187 by changing the parameter annotations of the `BaseServer`, `UnixStreamServer` and `UnixDatagramServer` in the socketserver module.
I chose `Any` for the parameter in the `BaseServer`, because the documentation lists some more protocols, that accepts different parameters, so a `Union[Tuple[str, int], AnyStr]` would only work for *TCP* and Unix sockets.
=> Fix #3187 : Wrong Signatures in socketserver

stdlib/3/typing.pyi
This partially reverts https://github.com/python/typeshed/pull/3172
=> Partially restore old (imprecise) signature of Match.group()

stdlib/2and3/argparse.pyi, stdlib/2and3/cProfile.pyi, stdlib/2and3/contextlib.pyi, stdlib/2and3/distutils/version.pyi, stdlib/2and3/profile.pyi, stdlib/2and3/pstats.pyi, stdlib/3/io.pyi, stdlib/3/multiprocessing/pool.pyi, stdlib/3/pathlib.pyi, third_party/2/pathlib2.pyi, third_party/2and3/pynamodb/attributes.pyi
I happened to notice these while working on an unrelated change to pytype's pyi parser.
=> Remove unnecessary quotes around forward references.

stdlib/2/CGIHTTPServer.pyi, tests/mypy_selftest.py, third_party/2/six/moves/CGIHTTPServer.pyi, third_party/2/six/moves/__init__.pyi
This commit adds:
* Stubs for CGIHTTPServer in the Python 2 standard library, as requested in #1147.
* Stubs for six.moves.CGIHTTPServer in Python 2, as requested in #22.
=> Add stubs for CGIHTTPServer

stdlib/3/unittest/mock.pyi, third_party/2and3/mock.pyi
> First, the z: Any situation looks like a bug or accidental feature to me.
This is definitely meant (and works) as a variable declaration; that it
also allows using z as a type seems wrong. I can't find any evidence in
PEP 484 that this was intended; in mypy it's likely the accidental result
of other design choices meant to shut up errors about Any.
Ideally these classes could be declared as empty class stubs, but since the comments suggest this isn't possible yet, let's update these to be type aliases to Any rather than global variables of type Any. This would avoid invalid type errors when the implementation of type checkers respect the intention that `z: Any` does not make `z` a valid type.
=> Update how mock classes alias to Any

stdlib/3/sys.pyi
This is new in Python 3.7:
https://docs.python.org/3/library/sys.html#sys.flags
=> Add sys.flags.utf8_mode.

third_party/2and3/requests/api.pyi
Since the custom type was only used in argument types, it was effectively only an alias for `typing.Text`.
I added a second commit that runs the file through black, so it's probably easier to review the first commit.
=> Remove custom _Text type

third_party/2and3/click/core.pyi
[Here's](https://github.com/pallets/click/blob/master/click/types.py#L67-L69) the relevant source code in Click:
```
def fail(self, message, param=None, ctx=None):
"""Helper method to fail with an invalid value message."""
raise BadParameter(message, ctx=ctx, param=param)
```
This function just raises an exception with the supplied arguments, so we should mark it as such.
=> Mark click.ParamType.fail() as NoReturn

stdlib/3/tempfile.pyi
The `mode` parameter of these functions defaults to 'w+b'
(https://docs.python.org/3.7/library/tempfile.html), so I've added an
overload for explicit text mode, a second for explicit binary mode or
omitting the mode, and a third for a non-literal mode.
=> Use Literal to improve tempfile.[Named]TemporaryFile.

stdlib/3/multiprocessing/pool.pyi
It will resolve #3006
`MapResult` is not included.
https://github.com/python/cpython/blob/e09359112e250268eca209355abeb17abf822486/Lib/multiprocessing/pool.py#L674
The attributes of `MapResult` are private. If needed, I will add them and mark as `undocumented`.
=> Feat: Add stub of  MapResult

third_party/2and3/requests/api.pyi, third_party/2and3/requests/sessions.pyi
The type signature for the data arg to the `requests.Session.request` (and `get`, `post`, etc.) call accepts an iterable of tuples.
This was already corrected in #1660 for `requests.request`.
(Is there a better place to put this definition so it doesn't get out of sync again?)
=> requests.Session.request data arg accepts an iterable of tuples

stdlib/2/abc.pyi
At this point, it only matters for a few more months, but the Python 2
definition was less precise.
=> Copy a better definition of abstractmethod from 3/abc to 2/abc.

stdlib/3/subprocess.pyi
In https://docs.python.org/3/library/subprocess.html, the default value
of `timeout` is always None, so its type should be Optional[float], not
float. The one exception is that I left the type as float in
TimeoutExpired because (I assume) a timeout of None does not expire.
=> Make the type of `timeout` Optional[float] everywhere in subprocess.

stdlib/2and3/csv.pyi
Changed type of fieldname parameter in DictWriter __init__ method from Sequence[str] to Iterable[str]. This allows it to work with the following code:
my_dict = dict(a=2, b=3)
a = DictWriter(my_file, my_dict.keys())
=> Changed type of fieldname parameter in DictWriter __init__ method

third_party/2and3/click/__init__.pyi
This just re-exports `DateTime` and `FloatRange` from click top-level. As it is done by the project:
https://github.com/pallets/click/blob/7.x/click/__init__.py#L28
=> Added missing top-level exports to click

third_party/2and3/click/types.pyi
This just adds the constructor arguments to `click.FloatRange`.
=> Type annotated `click.FloatRange`'s constructor

third_party/2and3/click/core.pyi, third_party/2and3/click/testing.pyi, third_party/2and3/flask/testing.pyi
These are two simple changes to the click API.
First, instead of only primitive types being convertible in tuples, this recognizes that custom types are convertible as well. [Here's](https://github.com/pallets/click/blob/master/click/types.py#L578) the relevant click code. Ideally, this would be `Tuple[_ConvertibleType]` instead, but until mypy allows recursive types this supports most common usecases.
Second, this changes the `input` parameter of `CliRunner.invoke` and `CliRunner.isolation` to support Text and bytes, to match the signature of `make_input_stream`. Under the hood, `invoke` calls `isolation` which calls `make_input_stream`, so there's no reason for `invoke` and `isolation` to have more restrictive types.
=> click: Support tuples of _ParamTypes, CliRunner fixes

stdlib/2and3/logging/__init__.pyi
Updated/slightly corrected several type annotations in the `logging` module, primarily surrounding the built-in handlers (which are confusingly documented with the `logging.handlers` module). The most significant changes are the addition of the `StreamHandler.setStream` method (new as of 3.7) and making `FileHandler` a proper subclass of `StreamHandler`—it's documented as such (and, well, implemented as such), so I have to assume it's just an oversight in the stub. I don't think there's anything too controversial there.
=> Updated core handlers in logging

stdlib/3/asyncio/events.pyi
`ssl_handshake_timeout` actually has `None` as the default value.
=> Add missing default for ssl_handshake_timeout agrument

stdlib/3/tempfile.pyi
Resolves #2749
see also https://github.com/python/cpython/pull/11644
=> dir argument to tempfile functions may take PathLike

stdlib/2and3/logging/__init__.pyi
PR #3269 added some version checks for the argument type to setLevel
and the existence of NullHandler. While these features weren't present
in early versions of Python 3, they *are* present in Python 2.7, which
leads to false positives.
We could expand the check to include Python 2, but since the affected
Python 3 versions are super old and unsupported, I'm just removing the
checks.
=> Remove some spurious version checks in logging

.flake8, requirements-tests-py3.txt
* Limit Python 2 builtins to ones actually used.
* Update flake8-bugbear
* Leave a reminder about F811 not needed in the future (fixed in PyCQA/pyflakes#435, but not released yet).
=> Minor flake8 improvements

stdlib/2and3/csv.pyi
From the Lib/csv.py source, 'f' is passed directly to _csv.reader, which
expects Iterable[Text]
=> Fix an argument to csv.DictReader()

README.md
=> Update 'format' README section -- don't imply it is executable

tests/pytype_test.py
Use the os path separator in the `_is_version` function, fixes #3373. Tested on both Win10 and Ubuntu 18, should be generic cross-platform
=> Make path separator based on OS separator

stdlib/3/ast.pyi
I'm also going to create a branch with the typeshed version from mypy 0.740 and cherry-pick this onto it
=> Don't shadow ast.Tuple with typing.Tuple

stdlib/2/__builtin__.pyi, stdlib/2and3/builtins.pyi
From python/mypy#7582.
This partially reverts back the change in
0ee7c3c to have `__import__` return
`Any` instead of `ModuleType`.
=> Revert __import__ function annotation to return type back to Any

third_party/2and3/click/decorators.pyi
Similar to https://github.com/python/typeshed/issues/1693 / https://github.com/python/typeshed/pull/1699, but for `show_default`...
Using `show_default='not a bool'` should be permitted according to [the Click documentation](https://click.palletsprojects.com/en/7.x/options/#dynamic-defaults-for-prompts); however, Mypy trips on it:
```
error: No overload variant of "option" matches argument types "str", "str", "int", "Path", "str", "str"
note: Possible overload variants:
note:     def option(*param_decls: str, cls: Type[Option] = ..., show_default: bool = ..., prompt: Union[bool, str] = ..., confirmation_prompt: bool = ..., hide_input: bool = ..., is_flag: Optional[bool] = ..., flag_value: Optional[Any] = ..., multiple: bool = ..., count: bool = ..., allow_from_autoenv: bool = ..., type: …
```
=> Fix show_default type in click.option signatures

requirements-tests-py3.txt
Yesterday's release contains a number of pyi parser fixes, such as
support for the syntax in #3321.
=> Require a more recent pytype version.

stdlib/3/_ast.pyi
I have decided to put it on top to follow the implementation order.
=> Adds `posonlyargs` property to `arguments` for python3.8+

third_party/2and3/werkzeug/exceptions.pyi
Available since werkzeug==0.15.0
https://github.com/pallets/werkzeug/blob/e7ba08f209477cb453f15113f9a4d527a6e81bfe/src/werkzeug/exceptions.py#L561-L573
=> Add werkzeug.exceptions.FailedDepdency

third_party/2and3/tabulate.pyi
Updates the stubs for the `tabulate` module. In particular, the main function (`tabulate()`) was missing several possible types for its arguments.
=> Update stubs for tabulate

stdlib/3/sre_parse.pyi
It seems in Python 3.8, the 'Pattern' object in the (undocumented?) sre_parse module was renamed to 'State', along with a few associated parameters. For example, try taking the diff of:
- https://github.com/python/cpython/blob/3.7/Lib/sre_parse.py
- https://github.com/python/cpython/blob/3.8/Lib/sre_parse.py
=> Update sre_parse module for Python 3.8

third_party/2and3/click/core.pyi
None seems to be an expected type for this variable, as can be seen from the handling here: https://github.com/pallets/click/blob/6944450c5331f2d652d342650b6d9b3b52404baa/click/core.py#L519
=> Allow None for click.core.Context.default_map

stdlib/3/unittest/case.pyi
This makes it match the signature of assertRaisesRegex() which is the modern name for the same function.
=> Add missing expected_regex parameter to TestCase.assertRaisesRegexp().

stdlib/2and3/zipfile.pyi
=> Add missing ZipFile constructor arguments

stdlib/3/asyncio/__init__.pyi
See python/mypy#7819.
On Unix this name is defined in unix_events.py, which we don't have a stub for yet.
=> asyncio: fix windows stubs

stdlib/3/http/client.pyi
The equivalent httplib.HTTPConnection class already include it for Python
2, despite the attribute not being documented for either version.
=> Add `sock` attribute for http.client.HTTPConnection in Python 3.

stdlib/3/unittest/case.pyi
Fixes mypy false positive `"None" has noattribute "__enter__"` here:
```
class Foo(unittest.TestCase):
def test_foo(self) -> None:
with self.assertRaisesRegexp(Exception, "foo"):
1 / 0
```
Fixes regression introduced in e6c467af8260d9569ca1d3bcb40c3b4bea3fe606.
=> Fix signature of assertRaisesRegexp in unittest

stdlib/2/unittest.pyi, stdlib/3/unittest/case.pyi
While the documentation does not seem to make this particularly
obvious, it is allowed.
=> Allow datetime() with a timedelta() in assert(Not)AlmostEqual(s).

CONTRIBUTING.md
This was discussed on the typing-sig mailing list and in
python/peps#1218, has met the approval of the steering council, and
was incorporated into PEP 484.
PEP 484 does not require the submitter to actively contact the library
owners, but I believe we should require this courtesy.
=> New libs: Change permission requirement to notification

stdlib/3/sys.pyi
New in Python 3.8:
https://docs.python.org/3.8/library/sys.html#sys.pycache_prefix
=> sys: add pycache_prefix

stdlib/2and3/formatter.pyi, stdlib/3/asyncio/__init__.pyi
Fix errors discovered by running typeshed check on Windows. This is a temporary fix for https://github.com/python/typeshed/issues/3446 (in long term we should figure out why these were not caught by typeshed CI).
I also remove an outdated comment while I am at it.
=> Fix errors discovered by running typeshed check on Windows

stdlib/2and3/warnings.pyi
=> Add warnings.catch_warning type hints with Literal.

stdlib/2and3/distutils/fancy_getopt.pyi
Per [`distutils.fancy_getopt`](https://github.com/python/cpython/blob/143a97f64128070386b12a0ee589bdaad5e51f40/Lib/distutils/fancy_getopt.py#L47-L49) sources.
=> distutils.fancy_getopt short option is optional

stdlib/3/multiprocessing/dummy/__init__.pyi
`multiprocessing.dummy` exports names that were not yet listed in the typeshed stub:
```python
>>> from multiprocessing import dummy as mpdummy
>>> imported_objects = (
...     (name, obj) for name, obj in vars(mpdummy).items()
...     if name in mpdummy.__all__ and not obj.__module__.startswith("multiprocessing.dummy")
... )
>>> print(*(f"{name}: {obj.__module__}" for name, obj in sorted(imported_objects)), sep="\n")
Barrier: threading
BoundedSemaphore: threading
Condition: threading
Event: threading
JoinableQueue: queue
Lock: _thread
Queue: queue
RLock: threading
Semaphore: threading
current_process: threading
```
Of these, only `JoinableQueue` was listed.
=> Add missing elements for multiprocessing.dummy

stdlib/3/io.pyi
`io.FileIO` has a `name` parameter with is the path to the file to operate on: https://docs.python.org/3.7/library/io.html#io.FileIO
In practice this doesn't seem to exist and the parameter is actually named `file`: https://github.com/python/cpython/blob/master/Modules/_io/clinic/fileio.c.h#L52
```
In [1]: import io
In [2]: io.FileIO(name="test", mode="wb")
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-0ef63f53ae00> in <module>
----> 1 io.FileIO(name="test", mode="wb")
```
=> fix incorrect param name in FileIO

stdlib/2and3/warnings.pyi
Make `warnings.catch_warnings` to be a class, preserving benefits from #3464
=> Refactor warnings.catch_warning to be a class.

stdlib/2/BaseHTTPServer.pyi, stdlib/2/SocketServer.pyi, stdlib/3/http/server.pyi, stdlib/3/socketserver.pyi
It's not uncommon to pass functions rather than actual types into the servers.
=> Type socketserver's RequestHandlerClass as a callable.

stdlib/3/re.pyi
Makes it so that re.pyi exports typing.Pattern and typing.Match in more recent versions
Fixes #3447
=> Export Pattern and Match

third_party/2and3/cryptography/hazmat/primitives/asymmetric/padding.pyi
Not sure how to "type" this better.  The PSS interface takes salt_length as an int or an "object", which is a class variable.  I couldn't figure out any way to indicate PSS.MAX_LENGTH is the only acceptable value.
Looking for a better way to do this, but a fix is needed (MAX_LENGTH is probably a more common case then a specific int)
sample code (taken from https://cryptography.io/en/latest/hazmat/primitives/asymmetric/rsa/)
```
>>> chosen_hash = hashes.SHA256()
>>> hasher = hashes.Hash(chosen_hash, default_backend())
>>> hasher.update(b"data & ")
>>> hasher.update(b"more data")
>>> digest = hasher.finalize()
>>> public_key.verify(
...     sig,
...     digest,
...     padding.PSS(
...         mgf=padding.MGF1(hashes.SHA256()),
...         salt_length=padding.PSS.MAX_LENGTH
...     ),
... …
```
=> padding can take an int or an object (PSS.MAX_LENGTH)

stdlib/2and3/logging/handlers.pyi
In 2.7 the signature is:
```python
def __init__(self, filename, mode='a', encoding=None, delay=0):
```
And in 3.7:
```python
def __init__(self, filename, mode='a', encoding=None, delay=False):
```
Even in 2.7 the `delay` argument is morally a bool even though it still has an int default, so I kept it as a bool.
Fixes #3502
=> Simplify `WatchedFileHandler.__init__`

third_party/3/orjson.pyi
PR just updates the orjson.pyi file to the latest version from https://github.com/ijl/orjson/blob/master/orjson.pyi .  This includes new options for dumps.
=> Update orjson stub

stdlib/2and3/csv.pyi
The Python docs specify that `fieldnames` in `csv.DictReader` can be set to `None` to use the
first row of a CSV file as the field names:
https://docs.python.org/3.8/library/csv.html#csv.DictReader
Therefore, this pull request changes `fieldnames: Sequence[str] = ...` to  `fieldnames: Optional[Sequence[str]] = ...`.
A `git blame` of CPython's source states it's been like
that since Python 2.4,
see https://github.com/python/cpython/blame/3.8/Lib/csv.py#L81
I've also ran the file through `black` and `isort` (so that #3329 gets slightly easier), but I've put it into a separate commit, so it is easier to see the changes I made.
```python3
import csv
with open("test.csv", "r") as file:
csv.DictReader(file, fieldnames=None) #  should be valid
```
=> Make fieldnames of csv.DictReader Optional

third_party/2and3/jinja2/nodes.pyi
I only added the fields to `Macro` because that's all I needed (and in the interest of keeping this minimal). I'd be happy to go through and add the appropriate fields to the other node types if that's desirable - it should be pretty simple, just have to look at the `fields` in the actual jinja types.
I had to use `typing.List` because this file actually defines its own `List` - that appears to be the pattern in typeshed.
=> add jinja macro fields

stdlib/2and3/shutil.pyi
unpack_archive accepts a PathLike object as of 3.7.
=> Update shutil.unpack_archive for 3.7 and up

stdlib/2/__builtin__.pyi, stdlib/2and3/builtins.pyi
Running `int.from_bytes(iter([1, 0]), 'little'))` returns 1 as
expected.
=> Update int.from_bytes to allow Iterable[int]

stdlib/3/http/client.pyi
`HTTPConnection.timeout` is passed down to `socket.settimeout()` which supports `Optional[float]` and has a specific action for `None`.
=> Fix HTTPConnection timeout type

stdlib/2and3/shutil.pyi
See https://bugs.python.org/issue32689.
This bug only affects `src`s which are directory
Paths in Python 3.5 to 3.8 inclusive.
Comes at the cost of restricting
`src` to str even where a Path would work but
this might be preferable to exposing the bug.
=> Restrict shutil.move src argument to str

stdlib/3/http/server.pyi
Following the merge of #3422 the following code fails to typecheck using python 3.7 (e.g with mypy .760 and .0761) 
```python
import socketserver
if __name__ == "__main__":
import http.server
with socketserver.TCPServer(("", 8000), http.server.SimpleHTTPRequestHandler) as httpd:
pass
```
```
error: Argument 2 to "TCPServer" has incompatible type "Type[SimpleHTTPRequestHandler]"; expected "Callable[..., BaseRequestHandler]"
```
The change in this pr fixes that. The same change was made against `BaseHTTPRequestHandler` in the python 2 standard library as part of #3422 but it looks like it is missing from the python 3 library.
=> BaseHTTPRequestHandler is a subclass of StreamRequestHandler

stdlib/2and3/token.pyi
flake8 is a little picky about how we do checks against
sys.version_info
=> token: add TYPE_COMMENT, remove AWAIT, ASYNC for py37

stdlib/3/os/__init__.pyi
According to python document, `os.link`/`os.symlink` has signature with name `src` and `dst`
https://docs.python.org/3/library/os.html#os.link
https://docs.python.org/3/library/os.html#os.symlink
=> Fix argument name of os.link/symlink

stdlib/2/unittest.pyi
This makes the pyi file match the implementation:
https://github.com/python/cpython/blob/249706c1fbce04125d81bd9993e6c010ae30f8e4/Lib/unittest/case.py#L1019.
I also removed a now-redundant `run` method from FunctionTestCase
because the mypy test complained about it having a different signature
from TestCase.run().
Context:
https://github.com/python/typeshed/pull/3550#issuecomment-572702513.
=> Make unittest.FunctionTestCase inherit from TestCase in Python 2.

stdlib/2/posix.pyi, stdlib/3/os/__init__.pyi
https://github.com/python/cpython/blob/abdc634f337ce4943cd7d13587936837aac2ecc9/Modules/posixmodule.c#L2025
says, "This object may be accessed either as a tuple of [...] or via the
attributes [...]". Making the class a namedtuple allows tuple access.
The Python 2 stub included three undocumented attributes on
statvfs_result. These attributes were introduced by a Googler in the initial
checkin of posix.pyi without explanation
(https://github.com/python/typeshed/commit/14cbfb0dea2b1d24bba13bad9403eda8fd8e863f#diff-7f2796ce2ddcdc17984163a4a6fc4a74R80-R82),
and I don't see them used anywhere in Google's Python codebase, so my
guess is that they were added because they happen to be present at
runtime and can be removed.
Since I was modifying the typing imports line in 2/posix.pyi anyway, I …
=> Make os.statvfs_result inherit from typing.NamedTuple.

stdlib/3/os/__init__.pyi
This adds `f_fsid: int` to the stub for `os.statvfs_result` for Python >= 3.7. This attribute was added to cPython in https://github.com/python/cpython/pull/4571.
=> add f_fsid: int to os.statvfs_result for >= 3.7

third_party/2and3/requests/models.pyi
This fixes a type error when doing `response.headers.lower_items()`, a method
present on CaseInsensitiveDict
=> Change Response.headers from MutableMapping to CaseInsensitiveDict

third_party/2and3/requests/adapters.pyi, third_party/2and3/requests/sessions.pyi
`timeout=(5.0, None)`, set a 5s connect timeout and an unlimited read timeout. This is useful in some corner cases. Setting the second parameter to 0 doesn't do the same as requests then throws a `ValueError`. (special float values like `nan`, `inf`, etc also don't work)
This is based on `urllib3.util.timeout`. Reading the docs for that also suggets that `(None, None)` is valid, but that is the same as a single `None` and doesn't make a lot of sense in practice. It also says int's instead of float's are valid, but as casting int to float is easy that's less of a practical issue.
Another option would be to define a `timeout_value` to be `Union[float, int, None]` and then have something like `timeout: Union[timeout_value, Tuple[timeout_value, timeout_value]]`.
Ref:
* …
=> Allow requests to have timeout: Tuple[float, None]

stdlib/2and3/zipfile.pyi
This was changed in bpo-38334 and backported to Python 3.7.6 and 3.8.1
Not quite sure on what our policy on backports to patch releases is, but
don't think ZipExtFile isn't really meant to be external facing, so it
shouldn't matter much.
I found this while making improvements to mypy's scripts/stubtest.py
=> zipfile: fix ZipExtFile parameter

stdlib/3/asyncio/base_events.pyi, stdlib/3/asyncio/events.pyi
In asyncio local_addr is used for IP address, which is `(host, port)` pair.
Thus, `str` should be replaced with `Tuple[str, int]`
=> Fix local_addr type

stdlib/2and3/argparse.pyi
- `add_subparsers` uses keyword-only args
- `required` parameter is new in py37
=> argparse: various fixes

README.md
This was discussed a while ago on typing-sig. Consequently the
requirement of asking third-party maintainers for permission was
removed from PEP 484.
=> Remove consent requirement for third-party stubs

stdlib/3/subprocess.pyi
This addresses this issue:
https://github.com/python/typeshed/issues/3646
Jase
=> subprocess: Make stdin, stdout & stderr Optional for py3 to match py2

third_party/2and3/jinja2/loaders.pyi
FileSystemLoader now supports PathLike objects as provided by pathlib.
https://github.com/pallets/jinja/pull/1064
This aims to address #3682 
Looking forward to feedback!
Side note: Tests are passing but I get a "not subscriptable" error as pointed out in https://github.com/python/mypy/issues/6052 and the relevant docs when editing. I'd like to understand how this is handled when working on typeshed.
=> Support for PathLike objects in Jinja2 2.11.0

stdlib/2and3/xml/sax/__init__.pyi
sample program:
```python
import io
import xml.sax.handler
class Handler(xml.sax.handler.ContentHandler):
def startElement(self, name, attrs):
print(f'got <{name}>')
bio = io.BytesIO(b'<x><y/></x>')
xml.sax.parse(bio, Handler())
OUTPUT = '''\
got <x>
got <y>
'''
```
```
=> xml.sax.parse may also take IO[bytes]

stdlib/2and3/distutils/cmd.pyi
based on code of `Command.get_sub_commands()`
=> fix type of distutils.cmd.Command.sub_commands

stdlib/2and3/plistlib.pyi
```python
import collections
import plistlib
with open('f', 'rb') as f:
data1 = plistlib.load(f)
reveal_type(data1)
with open('f', 'rb') as f:
data2 = plistlib.loads(f.read())
reveal_type(data2)
with open('f', 'rb') as f:
data3 = plistlib.load(f, dict_type=collections.OrderedDict)
reveal_type(data3)
with open('f', 'rb') as f:
data4 = plistlib.loads(f.read(), dict_type=collections.OrderedDict)
reveal_type(data4)
```
```console
$ mypy t.py
t.py:5: error: Need type annotation for 'data1'
t.py:6: note: Revealed type is 'Any'
t.py:9: error: Need type annotation for 'data2'
t.py:10: note: Revealed type is 'Any'
t.py:14: note: Revealed type is 'collections.OrderedDict*[Any, Any]'
t.py:18: note: Revealed type is 'collections.OrderedDict*[Any, Any]'
Found 2 errors in 1 file (checked 1 source file) …
```
=> Fix typing for plistlib.load{,s}

stdlib/3/types.pyi
According to https://docs.python.org/3.8/reference/datamodel.html#frame-objects
the attribute `f_back` on a `FrameType` can be `None`.
=> Make `FrameType.f_back` optional

stdlib/2and3/distutils/dist.pyi
I was going to add more options but there were far too many in `__init__`
=> Add cmdclass to distutils.dist.Distribution

stdlib/2and3/distutils/ccompiler.pyi
Source: https://github.com/python/cpython/blob/a4ba8a3983356fceb4aedabe0c338180666a79aa/Lib/distutils/ccompiler.py#L86-L116
I only needed `library_dirs` but figured I'd add the others in that area as well
=> Add a few attributes to distutils.ccompiler.CCompiler

stdlib/2and3/csv.pyi
Fixes #3713.
Copied offending test code from issue above and ran `mypy test.py --warn-unreachable --custom-typeshed-dir .` => no issues found.
=> stdlib: csv.DictReader.fieldnames should be Optional[Sequence[str]]

stdlib/3/fcntl.pyi
- use overload for fcntl.ioctl
- use overload for fcntl.fcntl 
- mark positional-only args
=> fcntl: various improvements

stdlib/3/enum.pyi, third_party/2/enum.pyi
Based on the behavior here: https://github.com/python/cpython/blob/0b41a922f95f62b620d5a197b9f2ed8e4bb70730/Lib/enum.py#L91
the `__order__` attribute should be treated the same as `_order_`
=> Include typing for Enum __order__ attribute

tests/stubtest_whitelists/py37.txt, tests/stubtest_whitelists/py38.txt
travis seems to have just updated from 3.7.5 to 3.7.6 and 3.8.0 to
3.8.1. The stubs match the newer versions, so we remove the previously
whitelisted error
=> stubtest: remove entry from whitelist for travis update

stdlib/2and3/_dummy_threading.pyi, stdlib/2and3/threading.pyi
=> Change annotation of 'function' in Timer.__init__ from Callable[..., None] to Callable[..., Any]

stdlib/2and3/warnings.pyi
Looks like types for attributes of `warnings.WarningMessage` were accidentally dropped in #3543; this PR amends that.
=> bring back attribute types in warnings.WarningMessage

stdlib/3/asyncio/base_events.pyi
Not particularly useful. However, I fixed a stubtest false negative regarding missing keyword-only arguments, so might as well fix.
=> asyncio: add arguments to subprocess_shell

stdlib/3/configparser.pyi
It's technically an Optional callback protocol, but the return type of the callback affects this return type. Since it's undocumented, seems easier to call it Optional[Any]
=> configparser: add undocumented parameter to SectionProxy.get

stdlib/2and3/datetime.pyi
This is more faithful to the implementation:
https://github.com/python/cpython/blob/3.5/Lib/datetime.py.
When these classes define `__init__`, pytype has trouble type-checking
classes that inherit from datetime.datetime (done in, e.g., the third party
datetime_tz library) because it gets confused about what arguments the
constructor expects.
=> Have datetime.{date,datetime} define __new__ instead of __init__.

tests/pytype_test.py
This should be generic, and uses re.escape because backslashes are special characters in regex. Tested locally, and with this, pytype passes on windows
closes #3836
=> Make PathMatcher correctly exclude paths on windows

stdlib/3/inspect.pyi
This makes them consistent with Python 2 stubs.
The attributes are documented here:
https://docs.python.org/3/library/inspect.html#inspect.getargspec
=> Make attributes of inspect.ArgSpec optional in Python 3

stdlib/3/tokenize.pyi
The all uppercase tokens, as well as `tok_name` mentioned in the comment
actually come from the `from token import *`.
The LibCST project uses constants like `Intnumber` in its parsing, https://github.com/Instagram/LibCST/blob/master/libcst/_parser/conversions/expression.py
=> Expand tokenize stub to include Intnumber etc

third_party/2and3/chardet/__init__.pyi, third_party/2and3/chardet/universaldetector.pyi
Started adding files for chardet. Hopefully others will hop in to finish.
=> add universaldetector

.travis.yml, tests/stubtest_whitelists/py36.txt, tests/stubtest_whitelists/py37.txt
Will need to wait for #3827 to be merged to prevent CI failures
=> travis: update stubtest version

stdlib/2and3/filecmp.pyi
=> Add type annotations for Pathlike arguments

stdlib/2and3/ssl.pyi
Hi there!
This PR makes `typeshed` aware of `ssl.PROTOCOL_TLS` for Python 2.7.
Indeed, `ssl.PROTOCOL_TLS` was added in Python 3.5, and then [backported in Python 2.7.13](https://docs.python.org/2/library/ssl.html#ssl.PROTOCOL_TLS). Since I assume most Python 2 codebases nowadays are on 2.7.13+, and as per the guidelines [here](https://github.com/python/typeshed/blob/master/CONTRIBUTING.md#stub-versioning), it should be fine to add `ssl.PROTOCOL_TLS` for Python 2.7 as a whole, so that we can use it on Python 2/3 codebases that target eg 2.7.17. (Currently we need to `# type: ignore` when running in `--py2` mode.)
Let me know if there's anything I should add to the test setup for this :-)
=> Add `ssl.PROTOCOL_TLS` for Python 2.7

stdlib/2and3/xml/dom/minidom.pyi, stdlib/2and3/xml/dom/pulldom.pyi
While this does not add any interface in the modules, it tells mypy that
the modules _exist_, which is a starting point.
=> Add empty stubs for xml.dom.* modules.

stdlib/2and3/distutils/command/config.pyi
Add some initial typing to `distutils.command.config`. Many of the member variables are initialized to `None` and then later set to their true value outside of `__init__.py`. I have declared these to be `Optional` as a result - please let me know if this is not correct.
=> Add types for distutils.command.config

stdlib/2/__builtin__.pyi, stdlib/2and3/builtins.pyi
The Python source (Objects/exceptions.c) explicitly checks for null
pointers before using the filename and lineno members. Some libraries,
e.g. pkg_resources, set filename and lineno to undefined values if
indeed none are appropriate.
Thanks in advance for your time, and keep up the great work!
=> SyntaxError's filename and lineno may be undefined.

stdlib/2and3/tarfile.pyi
This adds more constants from `tarfile` and reorders them to match the source file.
=> add more constants to tarfile

stdlib/2/SocketServer.pyi, stdlib/3/http/server.pyi, stdlib/3/socketserver.pyi
the `rfile` and `wfile` members are already implemented by
StreamRequestHandler. In addition to them several (undocumented)
class and instance variables exist according to
<https://github.com/python/cpython/blob/master/Lib/socketserver.py#L742>:
- `rbufsize`
- `wbufsize`
- `timeout`
- `disable_nagle_algorithm`
- `packet` and `socket` for datagrams
The already exist with Python 2.7
<https://github.com/python/cpython/blob/2.7/Lib/SocketServer.py#L677>
```mermaid
classDiagram
BaseRequestHandler <|-- DatagramRequestHandler
BaseRequestHandler <|-- StreamRequestHandler
StreamRequestHandler <|-- BaseHTTPRequestHandler
```
=> sockeserver: Add undocumented internal variables

stdlib/3/asyncio/subprocess.pyi
https://docs.python.org/3/library/asyncio-subprocess.html#asyncio.create_subprocess_shell
and from the code:
https://github.com/python/cpython/blob/482259d0dcf27714a84cf56b93977320bea7e093/Lib/asyncio/subprocess.py#L202
=> create_subprocess_shell takes a single positional argument

tests/stubtest_whitelists/py3_common.txt
Fixes the build failures on master.
=> Add msilib and _msi to stubtest whitelist

.flake8, requirements-tests-py3.txt, tests/check_consistent.py
* Update to flake8 3.7.9.
* Update to flake8-bugbear 20.1.4.
* Only ignore errors in stub files.
* Remove obsolete error counts.
* Sort error codes alphabetically.
* Don't ignore the following errors (unneeded):
* E704 Multiple statements on one line (def)
* W504 Line break occurred after a binary operator
* B303 `__metaclass__` used
=> flake8 updates and cleanups

third_party/2and3/werkzeug/wrappers.pyi
The PR #2740 added __setattr__ and __getattr__ to the
werkzeug.wrappers.BaseRequest definition to silence mypy when
monkeypatching this class.
The change disabled the errors for monkeypatching, but disabled disabled the
important check attr-defined.
=> Fix attr-defined check for werkzeug.wrappers.BaseRequest (fixes #3913)

stdlib/3/asyncio/transports.pyi
In #1447 resp. #1450, the `addr` parameter was set to `Tuple[str,int]` to support IPv4 addresses. This change was wrong, as `str` is still allowed for AF_UNIX sockets, while AF_INET6 sockets need `Tuple[str, int, int, int]`. Since this parameter is passed directly to socket.sendto, I instead suggest to use the same parameter specification.
=> use socket.sendto argument type for DatagramTransport.sendto

stdlib/2and3/ctypes/__init__.pyi
:wave: `ctypes.CDLL` first argument should be an optional string but it's currently typed as a string. Passing `None` [is a usual way of getting the current process' libc](https://bugs.python.org/issue34592).
**Repro**: 
```shell
(.venv3) ➜  mypy --command "from ctypes import CDLL; CDLL(None)"
<string>:1: error: Argument 1 to "CDLL" has incompatible type "None"; expected "str"
Found 1 error in 1 file (checked 1 source file)
```
**Versions**:
```shell
(.venv3) ➜  mypy --version
mypy 0.770
(.venv3) ➜  python3 --version
Python 3.6.10
```
Cheers!
=> ctypes.CDLL name can be None

stdlib/3/gettext.pyi
This is my first time looking at typeshed, so hopefully this is right.
The gettext module allows Path objects for localedir arguments (it appears to just pass it through `os.path.join()`). I've copied the types used in `os.path`, so I think the changes are correct.
=> Allow Path in gettext.

third_party/2and3/tornado/web.pyi
This diff refines the types on `RequestHandler` by porting types directly from the `tornado` repo:
https://github.com/tornadoweb/tornado/blob/712d61079defdad23b0a5e9fe0090b54e55cf7d0/tornado/web.py#L200-L201
https://github.com/tornadoweb/tornado/blob/712d61079defdad23b0a5e9fe0090b54e55cf7d0/tornado/web.py#L206-L207
=> Refine types on `tornado.web.RequestHandler`

third_party/3/orjson.pyi
Updated orjson.pyi to support two new added flags `OPT_INDENT_2` and `OPT_NON_STR_KEYS`.
Renamed `__obj` to `obj` to allow using named parameter `obj` instead of positional, without getting errors.
=> Update orjson.pyi to support two new flags

stdlib/3/io.pyi
Didn't check C code, but the _pyio implementation explicitly checks for
None
=> io: StringIO seems happy enough to take None

stdlib/3/multiprocessing/connection.pyi
`multiprocessing.connection.Connection` definition is not complete and causes errors when creating an instance with a named parameter:
```python
multiprocessing.connection.Connection(handle=10)
```
=> added multiprocessing.connection.Connection constructor definition

third_party/2and3/tornado/httputil.pyi
Porting type information directly from the tornado repository:
https://github.com/tornadoweb/tornado/blob/712d61079defdad23b0a5e9fe0090b54e55cf7d0/tornado/httputil.py#L340-L384
=> New attributes and types on `HTTPServerRequest`

stdlib/2and3/array.pyi
Allows for the following:
```
reveal_type(array('d')) # note: Revealed type is 'array.array[builtins.float]'
reveal_type(array('b')) # note: Revealed type is 'array.array[builtins.int]'
reveal_type(array('u')) # note: Revealed type is 'array.array[builtins.str]'
reveal_type(array('foo-bar')) # note: Revealed type is 'array.array[builtins.int*]'
```
Uses https://mypy.readthedocs.io/en/stable/more_types.html#advanced-self
fixes: https://github.com/python/typeshed/issues/3946
rel: http://docs.python.org/3.6/library/array.html
=> Update array with more precise type for typecodes

stdlib/2and3/uuid.pyi
Otherwise, pytype tries to import enum in Python 2 and complains that
the library doesn't exist.
=> uuid: import enum inside version check.

stdlib/3/tokenize.pyi
These constants were removed in
https://github.com/python/typeshed/pull/3839 because they are imported
from token. However, that is only true in Python 3.7+.
=> Add mistakenly removed constants back to tokenize.

stdlib/3/queue.pyi
This attribute was removed in
https://github.com/python/typeshed/pull/3879 because it is undocumented
and was annotated incorrectly. Unfortunately, a surprising (?) amount of
Google code uses this attribute and assumes it is a deque, so it needs
to exist but can't have a more general annotation like Collection[Any].
I also removed a no-longer-used typing.Deque import.
=> Add undocumented attribute queue.Queue.queue with type Any.

third_party/2and3/click/decorators.pyi
This is currently encoding 
```
def pass_context(_T: Any) -> _T:
```
=> [pyre] Fix typo in click/decorators

third_party/3/orjson.pyi
After submitting a pull request to orjson repository, the author has changed the library and "obj" parameter is now positional only.
Not this behavior is aligned with the stub file and the change can be reverted.
https://github.com/ijl/orjson/releases/tag/3.0.1
=> revert orjson.pyi obj parameter

stdlib/3/unittest/runner.pyi
Add missing type hints for attributes in unittest.TextTestResult.
=> Improve unittest.TextTestResult stubs

stdlib/2/multiprocessing/pool.pyi
This is opened as suggested and should be able to fix GH-4055.  Have a good weekend!
=> Remove context manager hints in multiprocessing.pool in Python 2

third_party/2and3/werkzeug/exceptions.pyi
Added in werkzeug 1.0.0
While the implementation accepts any value for retry_after, the docstring
allows only datetime and int. Using any other value could lead to an
invalid HTTP response.
=> Add retry_after to TooManyRequests and ServiceUnavailable

stdlib/2and3/tarfile.pyi
Add type hints for undocumented tarfile.TarFile file methods called via
_extract_member() when extract() is called.
=> Improve undocumented TarFile method type hints

stdlib/2and3/mmap.pyi
madvise only exists on platforms with that syscall, not sure if any besides windows lack it
=> Fix stubtest failures for mmap on windows

stdlib/2and3/xml/etree/ElementTree.pyi
`xml.etree.ElementTree` uses `open` on filenames (e.g. [1]), so `os.PathLike` has been supported as filenames since Python 3.6.
[1] https://github.com/python/cpython/blob/285ff63351bb5a42099527c283f65434e761be83/Lib/xml/etree/ElementTree.py#L584
=> xml.etree.ElementTree: add support for os.PathLike for py36+

stdlib/2and3/logging/__init__.pyi
- While this appears to be private by convention, it's also documented as available
to set here: https://docs.python.org/3/howto/logging.html#optimization and in source
- Did *not* update `logging.logThreads` et al to match the
documentation as it may be more appropriate to update the
documentation to set to `False` rather than to `0` based on how these
are used and I have not asked about this yet.
=> Add stub entry for logging._srcfile

third_party/2and3/google/protobuf/message.pyi
From my experiments (protobuf 3.8.0), `MergeFromString` accepts `bytes`, `bytearray`, and `memoryview` objects in Python 3.
I've reflected this in the types by using `typing`'s `ByteString` alias (which is effectively `Sequence[int]`, thus capturing `memoryview[int]`, and explicitly includes `bytes` and `bytearray`).
=> Broaden _Serialized type in protobufs to ByteString.

stdlib/3/functools.pyi
Per [docs](https://docs.python.org/3/library/functools.html#functools.lru_cache):
Since a dictionary is used to cache results, the positional and keyword arguments to the function must be hashable.
=> lru_cache-wrapped function args must be Hashable

CONTRIBUTING.md
=> Add review guidelines

stdlib/2and3/socket.pyi, tests/stubtest_whitelists/py3_common.txt
=> socket.create_connection source_address is optional.

stdlib/2and3/socket.pyi
Add typing for CAN_J1939 sockets implementing support for the SAE J1939
protocol. This is available in Python 3.9+ on Linux 5.4+.
=> Add typing for CAN_J1939 sockets

tests/stubtest_whitelists/linux-py35.txt, tests/stubtest_whitelists/linux-py36.txt, tests/stubtest_whitelists/win32-py35.txt, tests/stubtest_whitelists/win32-py36.txt
This got duplicated a little during the merge. The source of the
confusion is that the issue was fixed in CPython and the changes were
backported to 3.7 and 3.8. However, the micro versions we currently use
in CI on Linux don't have this fix.
Typeshed policy is to support the latest micro version, so I don't want
to hardcode micro versions into .travis.yml, since they'll never get
updated.
=> stubtest whitelists: clean up duplicate entries

stdlib/2/typing.pyi, stdlib/3/typing.pyi
Closes #2882
Most type checkers don't really care, but I agree that it's better to be more accurate, and it doesn't seem to cause any errors.
=> Improve TypeVar stub

stdlib/2and3/socket.pyi
The SocketCAN BCM option flag constants were added in version 3.9,
and only backported to version 3.8, despite the documentation's claims
of supporting all BCM-related constants starting from version 3.4.
Note: The CAN_FD_FRAME flag option was only introduced in the 4.8.x
kernel series, while the rest of the constants were available since the
Broadcast Manager was mainlined in the kernel as part of the SocketCAN
patches.
=> socket: Add missing CAN_BCM option flag constants

.travis.yml
I can't find a way to pin it to beta, and if they're going to make
changes that will break typeshed CI we shouldn't run it in CI.
I would like to make this run with Travis' allow_failures, but I can't
seem to make it work.
=> CI: remove py39

.github/workflows/stubtest-unused-whitelist.yml, .travis.yml, tests/stubtest_test.py, tests/stubtest_unused.py
This is currently a GitHub workflow that runs daily and lists all unused
whitelist entries found by running stubtest against current Python
versions on Linux and Windows. The workflow run will succeed if there
are no such entries, and fail otherwise.
In a second step, this should collate the output of the various runs and
create a PR to remove the entries. In that case, the workflow should
probably only run weekly or even monthly to keep the noise down.
Cf. #3728
=> Find unused stubtest whitelist entries

stdlib/2/__builtin__.pyi, stdlib/2and3/builtins.pyi
(I am sorry to create another PR, but I made the mistake of deleting the fork of typeshed that I had when I started this work, and I could not find a way to tell Github to continue the previous PR #4155.)
This PR introduces the `_SupportsLessThan` protocol and a type variable bounded to it to check arguments to `list.sort` and `sorted` on Python 3 (on Python 2, everything supports `__lt__`, even `None` and `object`).
When this PR is merged, I will send another one using `_SupportsLessThan` to check arguments to min and max, fixing #4051 with several overloads.
=> protocol, overloads to list.sort, sorted; WIP to fix #4051 (replaces #4155)

stdlib/3/typing.pyi
write() is inherited from IO[bytes], where it's defined as
`def write(self, s: AnyStr) -> int: ...`. If AnyStr is bytes,
this should accept bytes, bytearray, and memoryview, so the
overload is unnecessary.
Closes: #4201
=> Remove BinaryIO.write()

third_party/2and3/werkzeug/exceptions.pyi
Match the 1.0.0 API: https://werkzeug.palletsprojects.com/en/1.0.x/exceptions/#werkzeug.exceptions.InternalServerError
Correct:
```
Unexpected keyword argument "original_exception" for "InternalServerError"mypy(error)
```
Question: what about legacy compliance with werkzeug <1.0.0, this field will be visible in the stub even if it actually does not exist ?
=> Update the werkzeug InternalServerError constructor to match 1.0.0 API

stdlib/2/__builtin__.pyi, stdlib/2and3/builtins.pyi
=> builtins: NotImplemented is not callable

.github/workflows/stubtest-unused-whitelist.yml, .github/workflows/stubtest.yml, .travis.yml, tests/stubtest_whitelists/linux.txt, tests/stubtest_whitelists/py38.txt
This ensures that the Python version used matches the one used in the
scheduled extraneous stubtest whitelist check.
See also PR #4206.
=> Move stubtest CI to GitHub Actions

.github/workflows/stubtest-unused-whitelist.yml, tests/stubtest_whitelists/linux-py35.txt, tests/stubtest_whitelists/py3_common.txt
=> Remove unused stubtest entries

CONTRIBUTING.md
=> Protocol naming guidelines

stdlib/2and3/warnings.pyi
- `warnings.WarningMessage` message argument accepts both `str` and `Warning`
- `warnings.showwarning` message argument accepts both `str` and `Warning`
- `warnings.formatwarning` message argument accepts both `str` and `Warning`
Resolves #4211
=> Allow Warning message in showwarning and formatwarning

.github/workflows/stubtest-unused-whitelist.yml
Without this check, it is run on daily on every personal fork.
=> Run the unused stubtest check only on python/typeshed

stdlib/2and3/time.pyi
=> Added missing properties to struct_time

stdlib/2/__builtin__.pyi, stdlib/2and3/builtins.pyi
This reverts commit e857ad6ba97dcd757b251659e5b15e2acc5a6262.
Fixes #4226.
=> Revert "zip: add some overloads for heterogeneous tuples (#3830)"

stdlib/2and3/argparse.pyi
https://github.com/python/typeshed/pull/4144 and
https://github.com/python/cpython/pull/11478#pullrequestreview-423968410
resulted in the issue being fixed upstream.
A fix in time saves a branch in typeshed :-)
=> argparse: fix for latest py39

third_party/2and3/click/decorators.pyi
We are trying to strictify the type variable scoping semantics in Pyre such that `class`es and the parameters of `def`s are the only places in which new type variable scopes can be created.
This would mean that things like 
```	
from typing import Callable, TypeVar
T = TypeVar("T")
def produce_no_op_decorator() -> Callable[[T], T]:...
```
would be rejected with ```Invalid type variable [34]: The type variable `Variable[T]` isn't present in the function's  parameters.```
We currently don't error here, but don't handle this consistently correctly.
MyPy currently supports this (mod https://github.com/python/mypy/issues/3924), and we don't necessarily need that behavior to change.  Instead we'd just like typeshed to reflect the lowest common denominator between our two semantics: callback …
=> Replacing Callable[[T], T] with callback protocol in click

third_party/3/pytest_mock/__init__.pyi, third_party/3/pytest_mock/_version.pyi, third_party/3/pytest_mock/plugin.pyi
These can certainly be improved in the future, especially since `unittest.mock` can be improved as well.
See pytest-dev/pytest-mock#152 for a discussion on adding stubs to pytest-mock directly: It will most likely happen when they drop support for Python 2.
=> Add pytest_mock stubs

stdlib/2and3/contextlib.pyi
This matches the implementation, even though this behaviour isn't actually documented yet. (https://bugs.python.org/issue41147 aims to fix the documentation issue though.)
Fixes https://github.com/python/typeshed/issues/4283.
=> Make redirect_std{out,err} yield new stream as context var

README.md, tests/mypy_test.py, tests/pytype_exclude_list.txt, tests/pytype_test.py
This replaces all uses of ‘blacklist’ with ‘exclude list’. Benefits:
- It is racially neutral terminology; see e.g. [1]
- It makes the meaning more clear. In fact, with the popular Python
autoformatter called ‘black’, also used by this project, files can be
‘blackened’ which is something completely different from them being on
a blacklist.
[1] https://chromium.googlesource.com/chromium/src/+/master/styleguide/inclusive_code.md#racially-neutral
=> Use ‘exclude list’ instead of ‘blacklist’

README.md
The description, as it was, did not work with an older version of pip,
as the installation errored.
e.g. Ubuntu 18.04. ships `pip 9.0.1`, which is too old.
An updated version of pip fixes the installation problem.
modified:   README.md
=> Update `test setup` description

.github/workflows/stubtest-unused-whitelist.yml
Now runs weekly instead of daily, but also add the ability to trigger
manually.
Weekly is a more sensible interval, daily was mainly used for testing. Testing can now more easily be done by triggering actions manually.
=> Update unused stubtest whitelist action trigger

third_party/2and3/cryptography/x509.pyi
Fix for the cryptography library:
``get_extension_for_class`` is supposed to return an extension for which the value has the ``ExtensionType`` that was given.
```python
from cryptography import x509
def test(cert: x509.Certificate,) -> None:
cert.extensions.get_extension_for_class(x509.AuthorityKeyIdentifier).value.key_identifier
```
```
/tmp/test.py:4: error: "ExtensionType" has no attribute "key_identifier"
```
=> Fix for cryptography Extensions.get_extension_for_class.

stdlib/2and3/tarfile.pyi
``TarFile.tarinfo`` should be a type, not an instance.
Fixes:
```python
import tarfile
class CustomTarInfo(tarfile.TarInfo):
pass
if __name__ == '__main__':
tarfile.TarFile(tarinfo=CustomTarInfo)
```
which causes:
```
test.py:8: error: Argument "tarinfo" to "TarFile" has incompatible type "Type[CustomTarInfo]"; expected "Optional[TarInfo]"
```
=> Fix: TarFile.tarinfo is a Type instead of instance.

third_party/2and3/requests/sessions.pyi
As far as I can see, requests doesn't mutate the mapping that's passed as data.
Tried to unsderstand how tjhe MutableMapping type came to be, and found it was suggested by an automated linter. Perhaps it was wrong?
=> Use Mapping for requests _Data

stdlib/3/multiprocessing/__init__.pyi
Partial revert of #4289. Fixes #4313
=> multiprocessing: revert changes to queue classes

third_party/2and3/cryptography/x509.pyi
A small fix for the cryptography library:
`dotted_string` on `x509.ObjectIdentifier`  is a string property, not a method:
https://cryptography.io/en/latest/x509/reference/?highlight=ObjectIdentifier#cryptography.x509.ObjectIdentifier
The problem:
```
from cryptography import x509
def get_extension_name(oid: x509.ObjectIdentifier):
oid_names = {"1.2.3": "testname"}
return oid_names[oid.dotted_string]
```
```
testulf.py:6: error: Invalid index type "Callable[[], str]" for "Dict[str, str]"; expected type "str"
```
=> Small cryptography fix

third_party/2and3/requests/models.pyi
`requests` module defines `_content` as https://github.com/psf/requests/blob/8149e9fe54c36951290f198e90d83c8a0498289c/requests/models.py#L819-L836 and `pyre` was complaining about this missing
```
def foo(...) -> None:
response = requests.Response()
response._content = content
```
=> [requests] Add _content to Response

stdlib/2and3/logging/handlers.pyi
Add support for the following syslog facilities:
- LOG_NTP
- LOG_SECURITY
- LOG_CONSOLE
- LOG_SOLCRON
In addition, reorder the entries to match the CPython implementation to
make it easier to read.
=> Add missing syslog facility codes

tests/stubtest_whitelists/py38.txt
@hauntsaninja It looks this was caused by GitHub Actions upgrade from Python 3.8.4 to 3.8.5. This is one change that might be relevant:
```
-"register($self, fd, eventmask=POLLIN | POLLPRI | POLLOUT, /)\n"
+"register($self, fd,\n"
+"         eventmask=select.POLLIN | select.POLLPRI | select.POLLOUT, /)\n"
```
(Repeated a few times.)
=> Add select.epoll.register to stubtest whitelist

stdlib/3/inspect.pyi, tests/stubtest_whitelists/py3_common.txt
This makes mypy think that conditions like
parameter.kind is Parameter.POSITIONAL_OR_KEYWORD
are always false, which triggers `unreachable` warnings, among other
problems.
=> stdlib/3/inspect: fix _ParameterKind being an empty enum

third_party/2and3/Crypto/Cipher/AES.pyi, third_party/2and3/Crypto/Cipher/ARC2.pyi, third_party/2and3/Crypto/Cipher/ARC4.pyi, third_party/2and3/Crypto/Cipher/DES.pyi, third_party/2and3/Crypto/Cipher/XOR.pyi, third_party/2and3/atomicwrites/__init__.pyi, third_party/2and3/bleach/sanitizer.pyi, third_party/2and3/boto/compat.pyi, third_party/2and3/boto/connection.pyi, third_party/2and3/boto/s3/bucketlistresultset.pyi, third_party/2and3/chardet/universaldetector.pyi, third_party/2and3/click/_termui_impl.pyi, third_party/2and3/click/core.pyi, third_party/2and3/click/termui.pyi, third_party/2and3/click/testing.pyi, third_party/2and3/click/utils.pyi, third_party/2and3/cryptography/hazmat/primitives/asymmetric/utils.pyi, third_party/2and3/cryptography/hazmat/primitives/poly1305.pyi, third_party/2and3/datetimerange/__init__.pyi, third_party/2and3/dateutil/parser.pyi, third_party/2and3/dateutil/relativedelta.pyi, third_party/2and3/singledispatch.pyi, third_party/2and3/toml.pyi, third_party/2and3/ujson.pyi
Removed imported symbols that are not accessed or re-exported from within third_party stubs (part 1 of 4). These were all identified as unused symbols by the pyright type checker and language server.
=> Removed imported symbols that are not accessed or re-exported (third_party part 1 of 4)

third_party/2and3/flask/app.pyi, third_party/2and3/flask/cli.pyi, third_party/2and3/flask/ctx.pyi, third_party/2and3/flask/debughelpers.pyi, third_party/2and3/flask/helpers.pyi, third_party/2and3/flask/logging.pyi, third_party/2and3/flask/templating.pyi, third_party/2and3/flask/views.pyi, third_party/2and3/google/protobuf/descriptor_pb2.pyi, third_party/2and3/google/protobuf/internal/containers.pyi, third_party/2and3/google/protobuf/internal/enum_type_wrapper.pyi, third_party/2and3/google/protobuf/json_format.pyi, third_party/2and3/google/protobuf/map_proto2_unittest_pb2.pyi, third_party/2and3/google/protobuf/map_unittest_pb2.pyi, third_party/2and3/google/protobuf/message.pyi, third_party/2and3/google/protobuf/struct_pb2.pyi, third_party/2and3/google/protobuf/test_messages_proto2_pb2.pyi, third_party/2and3/google/protobuf/test_messages_proto3_pb2.pyi, third_party/2and3/google/protobuf/type_pb2.pyi, third_party/2and3/google/protobuf/unittest_custom_options_pb2.pyi, third_party/2and3/google/protobuf/unittest_import_pb2.pyi, third_party/2and3/google/protobuf/unittest_mset_pb2.pyi, third_party/2and3/google/protobuf/unittest_no_arena_pb2.pyi, third_party/2and3/google/protobuf/unittest_no_generic_services_pb2.pyi, third_party/2and3/google/protobuf/unittest_pb2.pyi, third_party/2and3/google/protobuf/unittest_proto3_arena_pb2.pyi, third_party/2and3/google/protobuf/util/json_format_proto3_pb2.pyi, third_party/2and3/jinja2/_compat.pyi
Removed imported symbols that are not accessed or re-exported within third_party stubs (part 2 of 4). These were all identified as unused symbols by the pyright type checker and language server.
=> Removed imported symbols that are not accessed or re-exported (third_party part 2 of 4)

third_party/2and3/markupsafe/__init__.pyi, third_party/2and3/markupsafe/_compat.pyi, third_party/2and3/markupsafe/_constants.pyi, third_party/2and3/markupsafe/_native.pyi, third_party/2and3/markupsafe/_speedups.pyi, third_party/2and3/maxminddb/compat.pyi, third_party/2and3/nmap/nmap.pyi, third_party/2and3/pyVmomi/vim/__init__.pyi, third_party/2and3/pyVmomi/vmodl/__init__.pyi, third_party/2and3/pymysql/__init__.pyi, third_party/2and3/requests/__init__.pyi, third_party/2and3/requests/adapters.pyi, third_party/2and3/requests/api.pyi, third_party/2and3/requests/auth.pyi, third_party/2and3/requests/compat.pyi, third_party/2and3/requests/cookies.pyi, third_party/2and3/requests/models.pyi, third_party/2and3/requests/packages/urllib3/connection.pyi, third_party/2and3/requests/packages/urllib3/connectionpool.pyi, third_party/2and3/requests/packages/urllib3/fields.pyi, third_party/2and3/requests/packages/urllib3/filepost.pyi, third_party/2and3/requests/packages/urllib3/util/retry.pyi, third_party/2and3/requests/status_codes.pyi, third_party/2and3/simplejson/decoder.pyi, third_party/2and3/simplejson/encoder.pyi, third_party/2and3/werkzeug/contrib/fixers.pyi, third_party/2and3/werkzeug/contrib/testtools.pyi, third_party/2and3/werkzeug/datastructures.pyi, third_party/2and3/werkzeug/middleware/dispatcher.pyi, third_party/2and3/werkzeug/wrappers.pyi
Removed imported symbols that are not accessed or re-exported within third_party stubs (part 3 of 4). These were all identified as unused symbols by the pyright type checker and language server.
=> Removed imported symbols that are not accessed or re-exported (third_party part 3 of 4)

stdlib/2and3/cgi.pyi
PEP 484 says that type checkers should assume that all types used in a stub should use forward declarations even though they are not quoted. This stub is using the symbol "type" within the context of a class scope. The "type" symbol is declared within this scope, so pyright assumes that the forward declaration should be used. The solution is to define a symbol with a different name in the outer scope to avoid the name conflict.
=> Fixed symbol redefinition in cgi.pyi stub

tests/pytype_exclude_list.txt, third_party/2and3/yaml/__init__.pyi, third_party/2and3/yaml/composer.pyi, third_party/2and3/yaml/constructor.pyi, third_party/3/docutils/parsers/rst/states.pyi, third_party/3/pkg_resources/py31compat.pyi, third_party/3/six/__init__.pyi, third_party/3/six/moves/__init__.pyi, third_party/3/typed_ast/ast27.pyi, third_party/3/typed_ast/ast3.pyi, third_party/3/waitress/__init__.pyi, third_party/3/waitress/adjustments.pyi, third_party/3/waitress/channel.pyi, third_party/3/waitress/parser.pyi, third_party/3/waitress/proxy_headers.pyi, third_party/3/waitress/receiver.pyi, third_party/3/waitress/rfc7230.pyi, third_party/3/waitress/runner.pyi, third_party/3/waitress/server.pyi, third_party/3/waitress/task.pyi, third_party/3/waitress/utilities.pyi, third_party/3/waitress/wasyncore.pyi
Removed imported symbols that are not accessed or re-exported within third_party stubs (part 4 of 4). These were all identified as unused symbols by the pyright type checker and language server.
=> Removed imported symbols that are not accessed or re-exported (third_party part 4 of 4)

third_party/2/six/__init__.pyi
=> Add back six.StringIO (Python 2)

third_party/2/six/moves/urllib/parse.pyi
=> Add back six.moves.urllib.parse.unquote (Python 2)

stdlib/2/md5.pyi
=> Add back md5.md5

stdlib/3/typing.pyi
Closes #3561.
I've taken a quite naive approach as I am unclear if these attributes should be applied higher up (say to `Awaitable`?). Happy to make changes if there is a better way to fix this.
=> Add __name__ & __qualname__ to Coroutine

stdlib/3/http/server.pyi
`directory` has a default value:
https://docs.python.org/3/library/http.server.html#http.server.SimpleHTTPRequestHandler.
=> Mark http.server.SimpleHTTPRequestHandler's `directory` arg as optional.

stdlib/3/tkinter/font.pyi
It's possibly to specify e.g. `('Helvetica', 12, 'bold italic')` instead of `('Helvetica', 12, ['bold', 'italic'])`
=> more permissive type for tkinter font descriptions

requirements-tests-py3.txt, stdlib/3/tkinter/__init__.pyi, tests/pytype_exclude_list.txt
The latest pytype release fixes two pyi parser bugs that allow files
affected by them to be taken off the pytype exclude list. I removed two
`total=False` declarations in tkinter/__init__ that pytype does not like
(because it checks that `total` is present only when TypedDict is a
class's immediate parent) and which shouldn't be needed because
_InMiscNonTotal already specifies totality. I double-checked that mypy
reports no errors in 3.7 on a .py file containing:
from typing_extensions import TypedDict
Foo = TypedDict('Foo', {'x': int}, total=False)
class Bar(Foo): pass
x: Foo = {}
showing that it doesn't require `total` to be repeated.
=> Upgrade the pytype version to one that can parse the tkinter stubs.

stdlib/3/http/cookiejar.pyi
Documenting these aids in the creation of correct serialisation code.
There's nothing to suggest that these attributes are private, and given that they are required constructor arguments, we would need these to round-trip a Cookie through serialisation/deserialisation.
=> Fix missing attributes on Cookie

stdlib/3/re.pyi
No prior issue was created as this seems like a simple fix to an obvious mistake (or probably just forgetting to update)
Adds
* `msg`
* `pattern`
* `pos`
* `lineno`
* `colno`
https://docs.python.org/3/library/re.html#re.error
These were all added in Python 3.5
=> Added additional attributes to re.error

stdlib/3/tkinter/__init__.pyi
All tkinter widgets have a master attribute. Tk is the only widget whose master attribute can be None (and Tk's master is always None). This is because of the way master widgets work in Tcl/Tk: a widget whose name in Tcl is `.foo.bar` has a master named `.foo`, and the master of `.foo` is the root widget named `.`, corresponding to an instance of `tkinter.Tk`.
You can also try running this to see the master attributes:
```
import tkinter.ttk
print(tkinter.Tk().master)
print(tkinter.Toplevel().master)
print(tkinter.Button().master)
print(tkinter.Canvas().master)
print(tkinter.Checkbutton().master)
print(tkinter.Entry().master)
print(tkinter.Frame().master)
print(tkinter.Label().master)
print(tkinter.Listbox().master)
print(tkinter.Menu().master)
print(tkinter.Menubutton().master) …
```
=> fix tkinter master attributes

third_party/3/six/moves/__init__.pyi
=> Add back six.moves.range (Python 3)

stdlib/3/tkinter/__init__.pyi, stdlib/3/tkinter/ttk.pyi
I didn't know that this is the best practice when I wrote these type hints
=> use Any for ignored callback return types in tkinter

stdlib/3/tkinter/__init__.pyi
=> fix assigning to tkinter.Tk().report_callback_exception

tests/pytype_test.py
pytype hasn't needed the python_exe argument for a while, and getting
rid of it allows some code to be deleted.
=> Stop passing python_exe to pytype_test.

third_party/3/six/moves/__init__.pyi
=> Add back six.moves.cStringIO (Python 3)

stdlib/3/configparser.pyi
> When default_section is given, it specifies the name for the special section holding default values for other sections and interpolation purposes (normally named "DEFAULT"). This value can be retrieved and changed on runtime using the default_section instance attribute.
> ~ [configparser.ConfigParser](https://docs.python.org/3/library/configparser.html#configparser.ConfigParser)
=> Add missing default_section to RawConfigParser

stdlib/3/platform.pyi, tests/stubtest_whitelists/py39.txt
platform.DEVNULL seemed undocumented, but is eg, still mentioned in the
header comment of platform.py. So feels surprising this was removed
without much warning.
=> platform: update for py39

tests/stubtest_whitelists/py35.txt, tests/stubtest_whitelists/py36.txt, tests/stubtest_whitelists/py37.txt, tests/stubtest_whitelists/py38.txt
Downstream of the reintroduction of py39 to CI / running the unused whitelist entry flow in #4512
=> stubtest: fix whitelists

stdlib/3/asyncio/base_futures.pyi
contextvars are only available in 3.7+.
=> Made contextvars import in asyncio.base_futures conditional

stdlib/2and3/pstats.pyi
=> Add type hints for pstats.SortKey available in Python >= 3.7

third_party/2and3/google/protobuf/descriptor.pyi
Newer versions of protoc use this kwarg in generated code, even if it has the default `None` value, which breaks typechecking
=> protobuf: add serialized_options kwarg

requirements-tests-py3.txt
The latest version recognizes the @runtime_checkable
decorator, required for #4442.
=> Upgrade pytype

third_party/2and3/typing_extensions.pyi
This was added to typing_extensions in python/typing#724.
=> Add SupportsIndex stub to typing_extensions

stdlib/2and3/pkgutil.pyi, stdlib/3/sys.pyi
I think the Union type is what we want here? At least for
iter_importers. Maybe for ModuleInfo people sometimes assume they're
going to get a FileFinder.
My experience with pkgutil is fairly limited, happy to make changes.
=> pkgutil, sys: make types more precise

stdlib/3/posix.pyi
The constants were found by running dir(posix) on a Debian 10.5 (x86_64)
system.
Also mark module as incomplete.
Partly addresses #616.
=> Add more constants and attributes to posix

stdlib/2/__builtin__.pyi, stdlib/2and3/builtins.pyi
I made PathLike a protocol in #4447, but it should also be
runtime_checkable.
Caught by mypy_primer:
src/werkzeug/utils.py:646: error: Only @runtime_checkable protocols can be used with instance and class checks
=> PathLike: make runtime_checkable

stdlib/3/fcntl.pyi
Add support for the following open file description lock constants:
- F_OFD_GETLK
- F_OFD_SETLK
- F_OFD_SETLKW
=> fcntl: Add fcntl.F_OFD_XXXX constants

stdlib/2/collections.pyi, stdlib/2/future_builtins.pyi, stdlib/2/md5.pyi, stdlib/2/os/__init__.pyi, stdlib/2and3/_dummy_threading.pyi, stdlib/2and3/threading.pyi, stdlib/3/collections/__init__.pyi, stdlib/3/os/__init__.pyi, stdlib/3/platform.pyi, third_party/2/six/__init__.pyi, third_party/2/six/moves/__init__.pyi, third_party/2/six/moves/urllib/parse.pyi, third_party/3/six/moves/__init__.pyi
See discussion on typing-sig.
This doesn't take care of some third_party libraries, will follow up on
those.
=> pep 484: explicit reexport as intended

third_party/2and3/boto/compat.pyi, third_party/2and3/click/types.pyi, third_party/2and3/jinja2/_compat.pyi, third_party/2and3/werkzeug/_compat.pyi, third_party/3/aiofiles/__init__.pyi, third_party/3/jwt/contrib/algorithms/__init__.pyi, third_party/3/jwt/contrib/algorithms/py_ecdsa.pyi, third_party/3/jwt/contrib/algorithms/pycrypto.pyi, third_party/3/waitress/compat.pyi
There are still a couple more, but hopefully this fixes CI. It's a
little bit of a chore to track down some of these; it looks like master
differs from latest release for a number of them.
=> pep 484: more reexports

stdlib/2and3/contextlib.pyi, tests/stubtest_whitelists/py3_common.txt
This dates back three years to https://github.com/python/typeshed/pull/1249
It seems pretty unused in practice, so I think this is fine:
https://grep.app/search?q=from%20contextlib%20import%20ContextManager&case=true
https://grep.app/search?q=contextlib.ContextManager&case=true
=> contextlib: get rid of a TODO

third_party/2and3/requests/api.pyi
I was getting this error message from mypy:
`error: Argument "params" to "get" has incompatible type "Dict[str, Optional[str]]"; expected <union: 9 items>`
but it looks like requests allows this:
```python
>>> import requests
>>> resp = requests.get('https://example.com', params={'q': None, 'r': 'a'})
>>> resp.url
'https://example.com/?r=a'
```
=> Allow request.get params values to be None

README.md
I've noticed that the status badge points to travis.org while the project doesn't use TravisCI anymore, so the status badge displays the status of last build on Travis, remaining green on build errors. This PR replaces the status badge with the one supplied by GH actions.
=> replace travis status badge with gh actions one

stdlib/2and3/pstats.pyi
I'm trying to pull the latest version of typeshed into Google, and
pytype chokes on pstats in Python 2 because the enum module was
introduced in 3.4.
=> Add a version guard for importing enum in pstats.

stdlib/3/io.pyi
This came up in https://github.com/python/mypy/pull/9275
Note that the perennial "str is an iterable of str" concern doesn't matter here, since things work even if you get it "wrong"
=> io: loosen writelines type to iterable

third_party/2and3/markdown/core.pyi
`extension_configs` are by definition unpredictable and an example that
isn't str → str would be:
extension_configs={"codehilite": {"guess_lang": False}}
=> markdown: no assumptions about ext cfg types

.github/workflows/stubtest-unused-whitelist.yml, .github/workflows/tests.yml
* Use 3.9 final instead of 3.9-dev
* Remove explicit Python versions from utility scripts
* Use mypy 0.790 for stubtests
=> CI: Update Python and mypy versions

third_party/2and3/retry/api.pyi
When checking `retry()` with `backoff` as a float, it gives an error:
```
error: Argument "backoff" to "retry" has incompatible type "float"; expected "int"  [arg-type]
```
After [looking at the code](https://github.com/invl/retry/blob/master/retry/api.py), `backoff` is not limited to `int`, so the use of `float` is permitted, which means the error is a false-positive.
While checking out the code vs the stubs I also noticed that the argument for `jitter` accepts `(float, float)` tuples (and is also not limited to `int`).
=> retry: loosen type for backoff, correct type for jitter

stdlib/3/urllib/error.pyi
The fifth argument to `HTTPError.__init__()`, `fp`, can be `None`, according to [the source code](https://github.com/python/cpython/blob/3.7/Lib/urllib/error.py#L49-L50). Right now, passing `None` results in this error:
```
error: Argument 5 to "HTTPError" has incompatible type "None"; expected "IO[bytes]"  [arg-type]
```
=> Allow None in fp argument to HTTPError

stdlib/2and3/termios.pyi
Returning a union from tcgetattr forces the caller to use isinstance or
a type: ignore comment if they modify the returned list. Return
`List[Any]` instead.
The cc field has ints at `cc[termios.VTIME]` and `cc[termios.VMIN]` if
`lflag & termios.ICANON` is zero. Change _Attr to allow this.
Fixes #4661
The goal is to avoid false positives like this:
```
example.py:6: error: Unsupported operand types for & ("List[bytes]" and "int")  [operator]
new[3] = new[3] & ~termios.ECHO          # lflags
^
example.py:6: note: Left operand is of type "Union[int, List[bytes]]"
example.py:7: error: Unsupported target for indexed assignment ("Union[int, List[bytes]]")  [index]
new[6][termios.VMIN] = 0
^
example.py:7: error: No overload variant of "__setitem__" of "list" matches argument types "int", "int" …
```
=> termios: Fix type of tcgetattr and tcsetattr attributes

third_party/2and3/requests/api.pyi
Fixes [#3218](https://github.com/python/typeshed/issues/3218)
I went through requests implementation, looks like we can replace `Mapping` with `SupportsItems`. That way we also get covariance. Let me know if I should make that change.
=> Added Iterable of tuples support

requirements-tests-py3.txt
This fixes things on Python 3.9, which we've started using since #4656
=> Upgrade flake8-pyi to fix CI

third_party/2and3/jinja2/environment.pyi
The Environment `select_template` and `get_or_select_template` methods accept an sequence. Thus to make the following work:
```python
from typing import List
from jinja2 import Environment
names: List[str] = ['example.html']
Environment().select_template(names)
```
- [Environment.select_template](https://github.com/pallets/jinja/blob/9b718ed3d26fc2f80ab58f3249b517a65db9cc7b/src/jinja2/environment.py#L841)
- [Environment.get_or_select_template](https://github.com/pallets/jinja/blob/9b718ed3d26fc2f80ab58f3249b517a65db9cc7b/src/jinja2/environment.py#L877)
Before:
```
(venv) $ mypy test.py --custom-typeshed .
test.py:5: error: Argument 1 to "select_template" of "Environment" has incompatible type "List[str]"; expected "List[Union[Template, str]]"
test.py:5: note: "List" is invariant -- see …
```
=> Allow sequence as `names` in jinja2 Environment

third_party/3/typed_ast/ast27.pyi
The original type was too narrow.
=> Fix type of typed_ast.ast27.Str.s

.github/workflows/tests.yml, README.md, tests/mypy_selftest.py, tests/mypy_test_suite.py
Rename mypy_selftest to mypy_test_suite
Cf. #4333
=> Add a mypy self test

third_party/2and3/markdown/core.pyi
These are defined in https://github.com/Python-Markdown/markdown/blob/6b6cd8bc2f0a870ed309f8b8036492af535e75a1/markdown/core.py#L103-L107, and are required when creating extensions.
=> Markdown:  Add missing processor attributes

.github/workflows/stubtest-unused-whitelist.yml, tests/stubtest_unused.py
In #4696 I bumped stubtest to a commit that hasn't been released. We
should have these stubtest versions match. In
https://github.com/python/mypy/pull/9426 I changed the output of
stubtest here; it's good to get this change in before I forget and this
action silently stops working.
=> stubtest unused: match stubtest version, add fix

.flake8, scripts/migrate_script.py, tests/check_consistent.py, tests/mypy_selftest.py, tests/mypy_test.py, tests/mypy_test_suite.py, tests/pytype_test.py, tests/stubtest_test.py, tests/stubtest_unused.py
I often run black and isort in typeshed root and then have to undo these
changes. The line length is long, but these tests aren't frequently read,
so I haven't bothered to sprinkle two more pyproject.tomls in places.
=> tests / scripts: blacken and isort

.github/workflows/tests.yml, tests/mypy_self_check.py
This better disambiguates it from mypy_test_suite and is more inline
with how mypy refers to it internally.
=> mypy_selftest: rename to mypy_self_check

stdlib/2and3/math.pyi, stdlib/3/gzip.pyi
I ran stubtest and spotted 2 things missing in 3.8 stdlib
- added `BadGzipFile` new exception for gzip:
https://docs.python.org/3/library/gzip.html#gzip.BadGzipFile
- added `math.perm()` new method:
https://docs.python.org/3/library/math.html#math.perm
=> update math and gzip stubs for Python 3.8

tests/mypy_test_suite.py
Only a subset of mypy's test suite should be relevant to typeshed:
https://github.com/python/mypy/pull/9638
This should make things faster.
(Also the -n12 argument to pytest is weird; note mypy's pytest.ini
automatically specificies -nauto which is what we should want)
Resolves https://github.com/python/typeshed/issues/4333
=> mypy_test_suite: run a subset of tests

stdlib/3/resource.pyi
The current annotations specify the `limits` argument as an `Optional[Tuple[int, int]]`; this is incorrect. The real `resource.prlimit()` function does not accept `None` for the `limits` argument; it is only possible to avoid specifying new resource limits by omitting `limits` completely.
=> Fix annotations for resource.prlimit()

.github/workflows/mypy_primer.yml
Use a version pip recognises so that we can install mypyc compiled mypy
from PyPI
We use tee and no longer try to delete the file based on exit code,
since we use data.trim now.
mypy_primer started failing silently because of changes in aiohttp, so
now we'll fail if the exit codes are not 0 or 1.
Note mypy_primer has --project-date to get around the problem of
breaking changes in projects, but I want to try and keep mypy_primer up
to date / get a feel for how bad this problem actually is.
=> mypy_primer: speed up, clean up

stdlib/3/_ast.pyi
Based on ast module document, None is allowed in arguments.kw_defaults list.
> `kw_defaults` is a list of default values for keyword-only arguments. If one is None, the corresponding argument is required.
This PR fix kw_defaults annotation.
=> Fix kw_defaults field type for ast.argument

.github/workflows/stubtest-unused-whitelist.yml, .github/workflows/tests.yml, stdlib/3/asyncio/windows_utils.pyi, tests/stubtest_whitelists/py3_common.txt
Includes changes from https://github.com/python/mypy/pull/9680
I've already fixed all the true positives on typeshed.
=> typeshed: update stubtest version
