python/typeshed

third_party/2and3/google/protobuf/compiler/plugin_pb2.pyi

Add `Feature` enum and `supported_features` field to CodeGeneratorResponse
These are related to the optional proto3 fields introduced in 3.12.0, see https://github.com/protocolbuffers/protobuf/releases/tag/v3.12.0 and https://github.com/protocolbuffers/protobuf/blob/214c77e1b76e63e512bd675d1c300c80438642b6/src/google/protobuf/compiler/plugin.proto#L112
Note that I've typed this differently than the stubs for other enums in `google.protobuf`. As pointed out in https://github.com/python/typeshed/issues/2521, the current enum stubs are incorrect. I can however change it if you would prefer these stubs to be consistent with the existing ones and fixed together with those at a later point.

Update stub for CodeGeneratorResponse protobuf message

---

stdlib/3/typing.pyi

At this point, it is too late to add methods to these semi-protocols as
it would break lots of existing code. Additionally, we are moving away
from these classes to finer-grained protocols anyway.

Remove some TODOs from IO classes

---

stdlib/3/typing.pyi

We added these in #4695, but obviously you don't want them in your Protocols.

typing: remove __class_getitem__ from Protocols

---

third_party/2and3/requests/__init__.pyi

Using `requests.ReadTimeout` currently gives a TypeError. I am updating the requests stub to allow using the ReadTimeout exception.

Update requests stubs with ReadTimeout exception

---

stdlib/3/typing.pyi

get_type_hints works on more object
Fixes #4678

fix(typing): allow any object as first argument for get_type_hints

---

stdlib/3/tkinter/__init__.pyi

I'm in the process of pulling a newer version of typeshed into Google
and seeing a lot of new errors due to code that passes 0 or 1 into
functions that are annotated as expecting bools.
Based on the fact that tk.{YES,NO,TRUE,FALSE} are defined as ints
(https://github.com/python/typeshed/blob/20a847218ac085ad691ea8d99155ee8ac7005479/stdlib/3/tkinter/constants.pyi#L3-L6)
and that the usage example in the source code also uses an int as a bool
(https://github.com/python/cpython/blob/cc75ab791dd5ae2cb9f6e0c3c5f734a6ae1eb2a9/Lib/tkinter/__init__.py#L25),
I think the annotations should be expanded.

Change some tkinter function parameter types from bool to int.

---

stdlib/2and3/_dummy_threading.pyi
stdlib/2and3/threading.pyi
stdlib/3/_thread.pyi
tests/stubtest_whitelists/py38.txt
tests/stubtest_whitelists/py39.txt

The previous typing meant `threading.ExceptHookArgs` could not be used to type a value.
The new typing follows what cpython does in the happy path (`_thread` exists rather than the pure-python fallback being used), a bit different than @srittau's suggestion in the issue.
Also, `ExceptHookArgs` is a `PyStructSequence` rather than an actual namedtuple, so stubtest complained about it. I changed it to tuple+properties instead. I can also add `n_fields`, `n_sequence_fields`, `n_unnamed_fields` properties which some other structseqs in typeshed use, but seems like obscure internal detail to me so I omitted those.
Fixes #4767.

threading: fix ExceptHookArgs being a function instead of a type

---

tests/pytype_test.py

[tests/pytype_test.py](../tree/master/tests/pytype_test.py#L176) is still referencing Python `3.6` explicitly:
> python_version="2.7" if version == 2 else "3.6",
The test fails to run if `python3.6` is unavailable (for example on Debian 10 Buster, which has 3.7).
According to https://devguide.python.org/#status-of-python-branches `3.6` is still maintained until end of 2021.
`pytype` itself [claims](https://github.com/google/pytype#requirements) to run on `2.7`, `3.5`-`3.8`.
Change the script to use the version of Python from the invoking interpreter. This should work as the [hash-bang line](../tree/master/tests/pytype_test.py#L1) uses `#!/usr/bin/env python3` anyway.

Fix hard-coded pytype version

---

.github/workflows/stubtest-unused-whitelist.yml

Looks like it's failing at https://github.com/python/typeshed/runs/1434747694
I think this should fix it? At least it should get rid of the red things that say ERROR :-)

Fix stubtest unused cron job

---

third_party/2and3/cryptography/x509.pyi

The `ExtensionOID` class is simply a namespace for constants, there are no instances of that class.

cryptography: Fix 'oid' field hints to ObjectIdentifier

---

stdlib/3/subprocess.pyi

The default being `None`, it makes sense to declare it optional.

fix(subprocess): make executable kwarg optional

---

stdlib/2and3/_dummy_threading.pyi
stdlib/2and3/threading.pyi

Fixes the issue pointed out in https://github.com/python/typeshed/pull/4768#issuecomment-736782337
---
An `import X as Y` where X != Y no longer exports, so 27a45df479ff2685e376d04894fffdacc3fcaa7e caused them to be un-exported.

threading: properly export excepthook, ExceptHookArgs

---

stdlib/3/concurrent/futures/thread.pyi

`ThreadPoolExecutor` assigns a `queue.SimpleQueue` to `_work_queue` in
it's `__init__` method.
https://github.com/python/cpython/blob/7cf0aad96d1d20f07d7f0e374885f327c2d5ff27/Lib/concurrent/futures/thread.py#L144

concurrent.futures: add _work_queue property to ThreadPoolExecutor

---

third_party/2and3/click/decorators.pyi
third_party/2and3/click/termui.pyi
third_party/2and3/click/types.pyi

Helps Python 2 code using:
form __future__ import unicode_literals
On Python 2, these interfaces are compatible with both str and unicode.

Allow Python 2 unicode for some click interfaces

---

third_party/2and3/tabulate.pyi

[`tabulate`](https://pypi.org/project/tabulate/) supports dictionaries in the `headers` argument of `tabulate.tabulate`:
```python
import tabulate
table = [{"name": "row 1", "val": 5}, {"name": "row 2", "val": 3}]
headers = {"name": "row names", "val": "number"}
print(tabulate.tabulate(table, headers=headers))
```
Dictionaries were removed from the possible types of `headers` in #3391 (cc @ilai-deutel). This PR adds them back, as they are a [supported by `tabulate`](https://github.com/astanin/python-tabulate/blob/2552e6dfb23cac990aeabb27b86745878d62247e/tabulate.py#L1078-L1081).
fixes #4829

tabulate: support dictionaries as table headers

---

tests/stubtest_whitelists/linux.txt

This reverts commit fcc2416d43a3d505af7ad99e90401f69a13b6ba7.

Revert "Remove unused stubtest whitelist entries (#4839)"

---

third_party/2and3/click/types.pyi

This PR adds attribute type hints for known attributes of `click.types`.
Current release [click 7.1.2](https://pypi.org/project/click/7.1.2/) was used as reference.
PR in response to mypy errors experienced in https://github.com/DataDog/mkdocs-click/pull/25

Add missing attribute hints for click.types

---

tests/stubtest_whitelists/linux-py36.txt
tests/stubtest_whitelists/linux-py37.txt
tests/stubtest_whitelists/linux-py38.txt
tests/stubtest_whitelists/linux.txt

See https://bugs.python.org/issue16396 for the CPython change.
Fixes https://github.com/python/typeshed/pull/4857

ctypes.wintypes can be imported on linux in 3.9.1

---

stdlib/3/distutils/command/install.pyi

Used by pip, but currently requires an ignore:
https://github.com/pypa/pip/blob/20.3.3/src/pip/_internal/locations.py#L15
The distutils code:
https://github.com/python/cpython/blob/1e5d33e9b9b8631b36f061103a30208b206fd03a/Lib/distutils/command/install.py#L70

Add type for distutils.command.install.SCHEME_KEYS

---

stdlib/3/tkinter/__init__.pyi

Issue: #4861
From Tcl manual:
ipadx amount must be a valid screen distance, such as 2 or .5c.

Pack ipadx ipady do not accept tuple #4861

---

stdlib/3/socketserver.pyi

This is to guarantee the classes that inherit `BaseServer` (e.g.,
`HTTPServer`) to have a proper return type of `__enter__`. For example,
with HTTPServer() as httpd:
pass
`httpd` should be of type `HTTPServer`, not `BaseServer`.

Use generic self for socketserver.BaseServer.__enter__

---

stdlib/3/tkinter/__init__.pyi
stdlib/3/tkinter/font.pyi

tkinter: use bool instead of Literal[0, 1]

---

stdlib/3/http/cookies.pyi

Add _quote and _unquote to http.cookies stub

---

stdlib/3/tkinter/__init__.pyi

Fixes a typo introduced in #4923 
Without `= ...`, these arguments would be keyword-only and **required**, but all of them should be optional. I think `mypy_primer` didn't complain because `BitmapImage` seems to be old and not very commonly used.

make tkinter.BitmapImage keyword arguments optional

---

stdlib/2/urllib2.pyi
stdlib/3/urllib/request.pyi

`urllib.request::Request.unredirected_hdrs` is missing with Python 3.
<https://github.com/python/cpython/blob/d9b8f138b7df3b455b54653ca59f491b4840d6fa/Lib/urllib/request.py#L330>
See my previous conntribution 25c96400f6b9144fbc1f6dd775b60b448562f7c1 which did this for Python 2 only.

Add some urllib annotations also for Python 3

---

tests/stubtest_whitelists/linux-py38.txt

The unused cronjob removed this for unclear reasons in #4935

allowlist ctypes.wintypes

---

stdlib/3/tkinter/__init__.pyi
stdlib/3/tkinter/ttk.pyi

Fixes #4959
I only allow `IntVar` and `DoubleVar` instead of allowing any `Variable`, because even though using `StringVar` works for this, using it is likely a programming error since the value is always a float or an int.

tkinter: allow IntVar in tkinter.Scale, ttk.Scale and ttk.Progressbar

---

stdlib/3/unittest/mock.pyi

None of the arguments to `__init__()` are optional, so leaving out `new` is not possible.

Remove unnecessary overloads from _patch.__init__()

---

stubs/cryptography/cryptography/hazmat/primitives/serialization/__init__.pyi
stubs/cryptography/cryptography/hazmat/primitives/twofactor/hotp.pyi
stubs/cryptography/cryptography/hazmat/primitives/twofactor/totp.pyi

This was changed in cryptography 3.1: https://cryptography.io/en/latest/changelog.html#v3-1
Most places in typeshed were already correct, fixed few remaining omissions.

cyptography: Add default, optional to few remaining backend= arguments

---

requirements-tests-py3.txt

pytype-2021.01.28 contains the changes needed to support the new
typeshed directory structure.

Switch back to installing the released version of pytype.

---

stdlib/zlib.pyi

I think their presence depends on zlib version, but said version predates Py3.

zlib: Add Z_FIXED and Z_RLE

---

tests/check_consistent.py

Closes https://github.com/python/typeshed/issues/4988

More consistency checks for dependencies

---

stdlib/json/__init__.pyi

`json.detect_encoding` is undocumented but first appeared in v3.6.0

Add support for json.detect_encoding

---

stubs/requests/requests/sessions.pyi

steps to reproduce:
```
>>> import requests
>>> def auth(r):
...     print(type(r))
...     return r
...
>>> requests.request(method="get", url="http://google.com", auth=auth)
<class 'requests.models.PreparedRequest'>
```

auth uses PreparedRequest not Request

---

stdlib/shelve.pyi
stdlib/types.pyi

This is enough to get stubtest working (note that it's a little annoying
to install mypy currently since typed-ast seems to have broken again on
Python 3.10)

Small fixes for Python 3.10

---

stubs/protobuf/google/protobuf/descriptor.pyi

Updated file to match:
https://github.com/protocolbuffers/protobuf/blob/master/python/google/protobuf/descriptor.py
This code is mostly accessed by generated files from protos, however, having type completeness match is important if those files are exported or referenced within a project.
Changes:
- added `create_key` parameter to most descriptor constructors.
- exposed `_internal_create_key`  
- Added missing `__new__` call
- broke up long lines

Updated descriptor.pyi in protobuf stubs.

---

stdlib/cgi.pyi
stdlib/urllib/parse.pyi
tests/stubtest_whitelists/py3_common.txt

A security fix added a "separator" argument to several URL parsing
functions and method in point releases:
* 3.6.13
* 3.7.10
* 3.8.8
* 3.9.2
Until all these versions are available on the GitHub Actions runners,
we need to whitelist the functions in the stubtests.

Fix stubtest errors

---

stubs/cryptography/cryptography/hazmat/primitives/serialization/__init__.pyi
stubs/cryptography/cryptography/hazmat/primitives/serialization/pkcs7.pyi

Docs: https://cryptography.io/en/latest/hazmat/primitives/asymmetric/serialization.html#pkcs7
Source: https://github.com/pyca/cryptography/blob/main/src/cryptography/hazmat/primitives/serialization/pkcs7.py

Add PKCS7 support for cryptography

---

stubs/Flask/flask/app.pyi
stubs/Flask/flask/logging.pyi

`Flask().logging` is a pretty frequently used property (based on some data I have surrounding editor completion failures), but was missing its type. Add it; it's always a standard lib `Logger`
The `flask.logging` module it depends on is pretty small, so complete that too based on the flask docs and code. The original types seemed to be a skeleton generated from the real source code, but ignored the fact that `wsgi_errors_stream` used a werkzeug proxy decorator so is not really a function (but an IO stream at runtime).

Add types for Flask().logger and flask.logging

---

stdlib/tarfile.pyi

Solves #5027 
Changed type of `name` argument to support `None` values in all the `classmethods` [gzopen, bz2open, taropen, and xzopen].

Changed: Name argument type to support None values.

---

stdlib/xmlrpc/client.pyi

The type of `faultCode` was declared as `str`, but it has to be an `int`.
see e.g. http://xmlrpc.com/spec.md
The wrong typing may have slipped in, as the Python's official
documentation also erroneously claims it has to be a string.
This has been wrong since at least 2007 (the initial checkin of the
documentation).
There is an open issue on the cpython issue tracker:
https://bugs.python.org/issue43354
Right after this commit/PR, a PR to the official Python documentation
will be created and there is already approval by a cypthon core dev, so
the PR for cpython will be merged then.

fix type for xmlrpc.client.Fault.faultCode

---

tests/stubtest_whitelists/py3_common.txt

In Python 3.10 these were updated to use Argument Clinic, but CPython might take a bug fix patch for 3.9 if someone wanted to try

comment on memoryview.cast

---

README.md

Any command that includes the "(.venv3) $" prompt is hard to read when
it's set inline. So put them all into triple-backtick blocks.

Format shell commands in README consistently

---

stdlib/cmath.pyi

because `complex` doesn't have an attribute `__complex__`.
Due to this issue, I got strange diagnostics on pyright.
```py
Argument of type "complex" cannot be assigned to parameter "__z" of type "_C" in function "exp"
Type "complex" cannot be assigned to type "_C"
"__float__" is not present
"__complex__" is not present
```
Reference: https://github.com/microsoft/pyright/issues/1679

Add `complex` in `_C`

---

tests/stubtest_whitelists/py37.txt
tests/stubtest_whitelists/py38.txt
tests/stubtest_whitelists/py39.txt
tests/stubtest_whitelists/py3_common.txt

stubtest now checks this for overloads as well (previously it didn't,
due to some combination of laziness, that this used to short circuit and
prevent signature checking, and the fact that these are all not super
helpful)
https://github.com/python/typeshed/issues/5145 is the issue discussing
whether we should actually fix these

allowlist new "not a function" errors

---

CONTRIBUTING.md

One might think that Akuli goes first, but the rest of the list is sorted by last name, not by first name.

sort contributor list

---

.github/workflows/tests.yml
tests/pyright_test.py

Pyright hasn't been updated in a while; update it.
Enable testing 3.10 with pyright; there have been some changes in typeshed recently for 3.10 that should be getting checked. We don't actually need 3.10 to be out to check these.

Bump pyright to 1.1.126, enable 3.10 testing

---

requirements-tests-py3.txt

Not a big deal, but when running `pip install -r requirements-tests-py3.txt`, I got:
```
WARNING: isort 5.5.3 does not provide the extra 'pyproject'
```

don't require isort[pyproject]

---

stdlib/tkinter/__init__.pyi

Fixes #5127 
For `BitmapImage`, the data "must adhere to X11 bitmap format" (`bitmap` manual page), and that format seems to be a subset of C. I allowed bytes for that too in case someone reads a bitmap file with `open(file, "rb")` or something like that.

allow bytes in tkinter.PhotoImage

---

stdlib/xmlrpc/client.pyi

These constants are in this module since Python3.0.

[stdlib] Add MININT and MAXINT for xmlrpc.client

---

stdlib/subprocess.pyi

- Python 3.8 and later allow a single PathLike for the subprocess cmd
- Windows subprocess env only allows str
- POSIX subprocess env allows any combination of str/bytes/Pathlike
Created to solve #5181

Improve PathLike handling for subprocess cmd/env

---

stdlib/resource.pyi

Fixes #5183
As per [this comment](https://github.com/python/typeshed/issues/5183#issuecomment-813044704), I have also changed it from `NamedTuple` to `Tuple[...]`, and have added a `__new__` function similar to [`statvfs_result`](https://github.com/python/typeshed/blob/master/stdlib/os/__init__.pyi#L298).

[stdlib] Fix `resource.struct_rusage`

---

stubs/requests/requests/sessions.pyi

From source:
```python
#: Dictionary of querystring data to attach to each
#: :class:`Request <Request>`. The dictionary values may be lists for
#: representing multivalued query parameters.
self.params = {}
```

Allow List[str] for requests.Session.request(params=)

---

stdlib/_weakref.pyi

As requested in https://github.com/python/typeshed/issues/3445.
Admittedly, it doesn't help much with type checking since typing doesn't really have a way to model a wrapper, but a mypy plugin could probably verify stuff here.

Make ProxyType and CallableProxyType Generic

---

stdlib/_compression.pyi
stdlib/gzip.pyi

Use protocols for gzip and _compression

---

tests/mypy_test.py

As requested by https://github.com/python/typeshed/issues/1526.
This addition takes mypy configuration from each distribution metadata file and constructs a single mypy.ini to run with. It assumes there is no mypy.ini but in case we ever need one, it would be simple to add these on top of an existing configuration file.
Might be relevant for #2852
As the issue did not really specify how the configuration would look, I added the following:
- You may add a mypy-tests section to the metadata file.
It looks like this:
[mypy-tests]
[mypy-tests.yaml]
module_name = "yaml"
[mypy-tests.yaml.values]
disallow_incomplete_defs = true
disallow_untyped_defs = true
- module_name can be of the form "a.*" like in mypy.ini.
- You can add several module sections for complex distributions with several …

Allow per distribution mypy strictness options 

---

CONTRIBUTING.md

Suggest splitting Python 2 stubs

---

stdlib/typing.pyi

Reverts python/typeshed#5194
Interacts poorly with mypy

Revert "Awaitable.__await__ should accept an Iterator rather than a Generator"

---

stubs/click/click/core.pyi
stubs/click/click/decorators.pyi

fix(stubs/click): add the `no_args_is_help` argument annotaion for click

---

CONTRIBUTING.md

I ran into this in #5204. This is already our de facto convention. I think it's confusing enough if not followed that it makes sense to standardize on this rule.
Should we add an example? It might be useful but it's not in line with the rest of the section.

Add a suggestion to CONTRIBUTING.md

---

stdlib/tarfile.pyi

Add TarFile.offset, which is an undocumented property. Fixes https://github.com/python/typeshed/issues/5209

Add TarFile.offset

---

.github/workflows/mypy_primer_comment.yml

This way, runs without output after runs with output can be clearly
determined. This also makes it easier to recognize when a run was not
completed.

Always generate a comment for mypy_primer

---

stubs/protobuf/google/protobuf/json_format.pyi

Add arguments: `descriptor_pool ` and `float_precision`
Closes #5225
References:
* https://github.com/protocolbuffers/protobuf/blob/d16bf914bc5ba569d2b70376051d15f68ce4322d/python/google/protobuf/json_format.py
* https://github.com/protocolbuffers/protobuf/blob/d16bf914bc5ba569d2b70376051d15f68ce4322d/python/google/protobuf/internal/json_format_test.py#L862

Fix protobuf json_format signatures.

---

stubs/click/click/exceptions.pyi

Some exceptions already had their properties annotated, but these didn't.

Annotate properties on exceptions in click.exceptions

---

stdlib/_ast.pyi

This attribute was [added in 3.8]. This change lets mypy resolve the
type correctly instead of failing with an attr-defined error.
[added in 3.8]: https://github.com/python/cpython/pull/13479

Add missing tag attribute to TypeIgnore stub

---

stubs/docopt/METADATA.toml
stubs/docopt/docopt.pyi

Add the single stub for the simple, but fairly well-used
[docopt](https://github.com/docopt/docopt) package.
It looks like that project is not very well maintained,
so I thought it would be easier to add the type annotations
here, as opposed to there, upstream. This has even been requested a few
times in https://github.com/docopt/docopt/issues/471. It appeared to me
that only the `docopt()` function is the public API, so I didn't include
the rest of the module's functions and attributes.
I believe that this stub is totally correct, except for one edge case: In https://github.com/docopt/docopt/blob/20b9c4ffec71d17cee9fd963238c8ec240905b65/docopt.py#L569
you can see that the `argv` argument can not only be a list, but `argv`
could also be a type which supports a `split()` function:
```
from …
```

Add stubs for `docopt` package

---

stdlib/fractions.pyi

This patch corrects the annotations in case Fraction is subclassed.
```
import fractions
class MyFraction(fractions.Fraction):
pass
def foo() -> MyFraction:
return MyFraction(1, 2)
```

Correct Fraction.__new__ typing for subclasses.

---

.github/workflows/mypy_primer_comment.yml

It was failing in #5252. Based on https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#permissions, seems like we should give permission on `pull-requests` instead.

Fix permissions for mypy-primer-comments

---

stubs/protobuf/google/protobuf/text_format.pyi

Examples of how the implementation handles bytes:
https://github.com/protocolbuffers/protobuf/blob/master/python/google/protobuf/text_format.py#L692
https://github.com/protocolbuffers/protobuf/blob/master/python/google/protobuf/text_format.py#L730

Allow bytes in addition to str in google.protobuf.text_format

---

stubs/click/click/decorators.pyi

I.e. the autocompletion function is basically guaranteed to receive `click.Context` in it's `ctx` parameter. So it doesn't have to accept `Any`.
Additionally it's enough if it's return value is `Iterable` (e.g. a generator). Because it will only be iterated over...

fix(stubs/click): don't force autocompleter to accept anything as context

---

.github/workflows/tests.yml
tests/pyright_test.py

I recently published https://github.com/marketplace/actions/run-pyright, which wraps pyright and uses GHA magic to leave diagnostics on commits / PRs (like https://github.com/jakebailey/pyright-action-test/pull/1/files), plus a faster startup time thanks to GHA tool caching and piggy backing off of the `node` install used in GHA itself (so no `setup-node` needed).
This PR switches to that action and leaves a comment noting that the version number is pinned in two places.
This action is a prototype, but I'm pretty confident in it so far.

Use pyright-action to run pyright, bump pyright

---

.github/workflows/mypy_primer_comment.yml

Fixes https://github.com/python/typeshed/issues/5270
The comment workflow waits for the mypy primer to run. I think with
Github's changes to workflow running, these runs get marked as
completed, but have the conclusion "action_required".
E.g., see https://github.com/python/typeshed/pull/5269/checks

mypy_primer: check conclusion field as well

---

.github/workflows/mypy_primer_comment.yml

This should cut down the API rate limiting we see when large numbers of
PRs are submitted.
Note when we used mypyc-compiled mypy in mypy_primer, this took <10m.
This is currently not the case, but hopefully will once again be.

mypy_primer: reduce polling frequency

---

stdlib/enum.pyi

I remember there are some subtleties around Enum.__new__, that might be
relevant to StrEnum, but I'm forgetting the details.
I wasn't sure how best to handle the new enum.property. I could also
re-export, or take a more literal interpretation.

enum: update for py310

---

stdlib/_collections_abc.pyi

In this context, "mypy and pytest" makes no sense. I assume "mypy and pytype" was intended.

delete old comment

---

stubs/protobuf/google/protobuf/text_format.pyi

Python 2 `unicode` values are supported. For example:
https://github.com/protocolbuffers/protobuf/blob/master/python/google/protobuf/text_format.py#L843

Change some str types to Text in google.protobuf.text_format

---

.github/workflows/tests.yml
tests/pyright_test.py

Per https://github.com/jakebailey/pyright-action/issues/1, the comments are too noisy when run in a job matrix.
I added an option to disable the comments while I think about how this should actually work.

Bump pyright, disable PR/commit commenting for all but one job

---

CONTRIBUTING.md
README.md

This may be a bit controversial, but I have always found the guidelines misleading. Most pull requests we receive are small, and running many different tests locally is just unnecessary, since the CI runs them anyway.
I remember running tests locally only two times: when pytype got stuck in an infinite loop and I wanted to interrupt it with Ctrl+C, and when I was working on stubtest whitelists for Python 3.10. Most typeshed contributors never come across situations like this.
I added several reviewers, because contribution guidelines are important. Feel free to add more.

do not require running tests locally

---

stdlib/typing_extensions.pyi

typing_extensions 3.10 now includes OrderedDict for all Python versions

Add OrderedDict to typing_extensions

---

CONTRIBUTING.md

To me, it seems like many new contributors don't realize that `--amend` is called "squashing" in our CONTRIBUTING.md. See #5248 and #5370 for example. I tried to clarify it a bit.

CONTRIBUTING.md: explicitly avoid --amend

---

.github/workflows/mypy_primer_comment.yml

For whatever reason, looks like GA mandates full SHA
This was added in #5364

Use full SHA for comment hiding

---

stdlib/functools.pyi

#5370 added `functools._make_key`. Its purpose is to return a hashable object to represent `args` and `kwargs`, so even though it returns two different things, returning `Hashable` works in both cases.
@Harmouch101 What do you think?

return Hashable from functools._make_key

---

stdlib/builtins.pyi

This is consistent with the runtime behaviour, where
`isinstance(memoryview(b"test"), Sequence) == True`

Make memoryview inherit from Sequence

---

stdlib/csv.pyi

Fixes #4800 
To check that this works:
```python
import csv
import enum
from typing import TYPE_CHECKING
class Foo(enum.Enum):
X = 1
Y = 2
def main() -> None:
with open('foo.csv', 'w') as file:
writer = csv.DictWriter(file, list(Foo))
writer.writeheader()
writer.writerow({Foo.X: "lol", Foo.Y: "wat"})
with open('foo.csv', 'r') as file:
foo_reader = csv.DictReader(file, list(Foo))
print(list(foo_reader))
if TYPE_CHECKING:
reveal_type(next(foo_reader))
with open('foo.csv', 'r') as file:
string_reader = csv.DictReader(file)
print(list(string_reader))
if TYPE_CHECKING:
reveal_type(next(string_reader))
main()
```
Output: 
```
[{Foo.X: 'X', Foo.Y: 'Y'}, {Foo.X: 'lol', Foo.Y: 'wat'}]
[{'X': 'lol', 'Y': 'wat'}]
```
mypy on master:
```
foo.py:13: error: Dict entry 0 has incompatible type "Foo": …
```

non-string fieldnames for csv.DictReader and csv.DictWriter

---

.github/workflows/stubtest-unused-whitelist.yml

After creating #5401, I found a way to run the action manually (click "Actions" at top, then "Select workflow"). Turns out that the permissions we have are not enough for `create-pull-request` action. Minimal example:
```yaml
on:
workflow_dispatch:
permissions:
contents: read
pull-requests: write
jobs:
foobar:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- run: |
echo lol > foo
- name: Create pull request
uses: peter-evans/create-pull-request@v3.8.2
with:
commit-message: Asdf
title: Asdf2
```
Deleting the `permissions:` part makes this work.
@srittau Permissions were added in #5255. Why? I understand restricting permissions of stuff that runs when people make pull requests, but why also do it for something that can be started with cron or a maintainer?

fix stubtest-unused-whitelist permissions

---

stubs/Flask/METADATA.toml
stubs/Jinja2/METADATA.toml
stubs/MarkupSafe/METADATA.toml
stubs/Werkzeug/METADATA.toml
stubs/click/METADATA.toml
stubs/itsdangerous/METADATA.toml
tests/check_consistent.py

Deprecate pallets stubs

---

CODE_OF_CONDUCT.md
README.md

The file CODE_OF_CONDUCT.md is the standard location for it and
is treated specially by GitHub, for example by linking to it directly
when opening issues and PRs.

Move code of conduct to separate file

---

CONTRIBUTING.md
pre-commit
tests/README.md

Move and consolidate venv setup and running isort/black/flake8 into
separate sections and link those sections from the ToC. Also extend
those sections slightly.
Move the tests section into a separate file.
Make venv name in pre-commit match name in CONTRIBUTING.

Split the tests section, extend ToC

---

stubs/PyYAML/yaml/loader.pyi

Closes #5390. Adds `yaml.UnsafeLoader` stub.

Add yaml.UnsafeLoader

---

stdlib/VERSIONS

It was called ConfigParser in Python 2.
Split out from #5442.

configparser available since Python 3.0

---

stdlib/inspect.pyi
stdlib/py_compile.pyi
stdlib/ssl.pyi

Python 2.7 doesn't have enum in the stdlib, in particular, so we
shouldn't import it.
It would probably be a better long-term fix to move the Python 2 stubs
to `@python2` and simplify them there.

Don't import enum in Python 2 stubs

---

stubs/click/click/testing.pyi

The method returns a tuple of io.BytesIO objects that hold the temporary
stdin and stdout. By correcting the type, it allows usages of
io.BytesIO.getvalue() to pass type checking.
The method is defined at:
https://github.com/pallets/click/blob/7.1.2/src/click/testing.py#L160
Its return is at:
https://github.com/pallets/click/blob/7.1.2/src/click/testing.py#L256
Where bytes_output is defined at:
https://github.com/pallets/click/blob/7.1.2/src/click/testing.py#L196

Correct return type of click.testing.CliRunner.isolation()

---

stdlib/multiprocessing/__init__.pyi

Add aliases for 'function classes' to multiprocessing

---

.github/workflows/tests.yml
tests/pyright_test.py

This actually fails on my machine at the moment with a real interpreter selected due to `click` being installed globally on my Arch machine with a `py.typed` file; the fix we applied in pyright/pylance to ensure that `py.typed` libraries are picked over typeshed when possible appears to break checking typeshed itself.
I have a hunch that CI will pass (as we don't install any python-related deps in this mode), but opening as a draft to check anyway.
I'll have to look into this once I'm back on a work machine and can debug it (sending this from a personal machine...).

Bump pyright to 1.1.140

---

CONTRIBUTING.md

To help contributors keep track of which features can be used in stubs.

Add section on supported type-system features

---

stdlib/@python2/genericpath.pyi

The more specific overload item should come first. Also
fix the return type.

Fix Python 2 genericpath.commonprefix

---

stdlib/pickle.pyi

These are the pure-Python pickle implementation, and are sometimes used
by code that wants to extend or override parts of the
pickling/unpickling process.

Add _Pickler and _Unpickler to stdlib/pickle

---

stdlib/zipfile.pyi

This uses my original idea. Why this is currently doesn't work in corner cases due to a mypy bug, I think this is the best solution:
* Is it correct.
* It is very unlikely to be an issue in practice as this is an internal constructor, and the `close_fileobj` argument is most likely provided as a literal anyway.
* The mypy bug is easily worked around by using `# type: ignore` or `Literal[True, False]` in case it comes up in practice.
* We don't need to remember to fix this when mypy gets fixed.

Use only literal overloads for ZipFile.__init__()

---

stdlib/pickle.pyi

Came up in #5506 
These are only present on `_Pickler` and `_Unpickler`, but stubtest doesn't seem to complain about it either way. @hauntsaninja Is `ClassVar` support planned?

add _Pickler.dispatch and _Unpickler.dispatch

---

stdlib/sys.pyi

`sys.stdlib_module_names` was introduced in Python 3.10
- [bpo-42955][1]: Add sys.stdlib_module_names: list of stdlib module names (Python and extension modules)
- PR1 python/cpython#24238: Add sys.modules_names
- PR2 python/cpython#24332: Rename module_names to sys.stdlib_module_names
[1]: https://bugs.python.org/issue42955

Add sys.stdlib_module_names for Python 3.10

---

stdlib/sys.pyi

`sys.orig_argv` is a new addition in Python 3.10
- [`sys.orig_argv` in Python 3.10 documentation][1]
- [bpo-23427][2]: Add sys.orig_argv: original command line arguments passed to the Python executable
- PR python/cpython#20729: Add sys.orig_argv attribute
[1]: https://docs.python.org/3.10/library/sys.html#sys.orig_argv
[2]: https://bugs.python.org/issue23427

Add sys.orig_argv for Python 3.10

---

stdlib/@python2/datetime.pyi
stdlib/datetime.pyi

* Use `__new__` instead of `__init__` for `datetime.timedelta`
* Remove invalid parameter
Closes #5529

Use __new__ for datetime.timedelta

---

stdlib/unittest/mock.pyi

Fixes #5533. This changes the order and in some cases removes default
values from new.

mock: fix overloads

---

stdlib/contextlib.pyi

Yet another Python 3.10 addition - `AsyncContextDecorator`.
- [Documentation][1]: `contextlib.AsyncContextDecorator`
- [bpo-40816][2]: Add missed AsyncContextDecorator to contextlib
- PR python/cpython#20516: Add AsyncContextDecorator class
I wasn't sure how to properly type annotate the `func` parameter. In the end, I followed
- python/typing#424: Document how to type hint for an async function used as a callback
- https://github.com/python/typeshed/blob/33ea64898873ef8e254779c1f9754827af43e9ae/stdlib/contextlib.pyi#L91
Existing `ContextDecorator` [annotation][3] for comparison
```python
_F = TypeVar("_F", bound=Callable[..., Any])
class ContextDecorator:
def __call__(self, func: _F) -> _F: ...
```
[1]: https://docs.python.org/3.11/library/contextlib.html#contextlib.AsyncContextDecorator …

Add contextlib.AsyncContextDecorator

---

.github/workflows/mypy_primer.yml
.github/workflows/tests.yml
requirements-tests-py3.txt
tests/pyright_test.py

- New pytype should pull in google/pytype#925 (support for `|` Union)
- New mypy should pull in python/mypy#10496 (improved TypeGuard support)
- Black and pyright didn't make changes relevant to typeshed as far as I'm aware, but better to keep them up to date

bump various dependencies

---

stubs/Markdown/markdown/extensions/codehilite.pyi

I'm a regular contributor @Zulip, and I've added a commit that overrides the [`_parseHeader` function](https://github.com/Python-Markdown/markdown/blob/3ea29f9d9b7d201269444dccedc0383065532b7e/markdown/extensions/codehilite.py#L164), and while working, I found that this attribute is missing here. (Related PR: https://github.com/zulip/zulip/pull/18608)
This attribute is defined here: https://github.com/Python-Markdown/markdown/blob/3ea29f9d9b7d201269444dccedc0383065532b7e/markdown/extensions/codehilite.py#L113.

markdown: Add missing attribute to Markdown stub.

---

stdlib/importlib/metadata.pyi

`packages_distributions()` is a new addition to `importlib.metadata` in Python 3.10.
I basically copied [function signature with annotation][1] from the source code
- [What's new in Python 3.10 - importlib.metadata][2]
- [importlib-metadata v3.7.0 changelog][3]
- The corresponding `importlib-metadata` [commit 466cd3c][4]
[1]: https://github.com/python/importlib_metadata/blob/5fb702911718a58f617bc774d846e6e4084da5d2/importlib_metadata/__init__.py#L1011
[2]: https://docs.python.org/3.10/whatsnew/3.10.html#importlib-metadata
[3]: https://importlib-metadata.readthedocs.io/en/latest/history.html#v3-7-0
[4]: https://github.com/python/importlib_metadata/commit/466cd3c8e6036cbd16584629fa0e54d6c0d6b027

Add importlib.metadata.packages_distributions() for Python 3.10

---

stdlib/VERSIONS

Adds some version ranges for submodules that are available in different
versions than their parent modules.
I noticed these while updating pytype's pinned typeshed commit. pytype
can't actually use this submodule version information yet, but from what
I understand, all type checkers at least handle this information
gracefully (by ignoring it), so it doesn't hurt to add it.
* collections.abc is available in Python 3.3 and later. _collections_abc
is imported by the collections.abc stub, so its version range is also
changed from 3.6- to 3.3-.
* _typeshed.tkinter needs to be 3.0-, since it imports tkinter, which is
marked as 3.0-.
* importlib.metadata is available in 3.8 and later.

Add some submodule versions to stdlib/VERSIONS.

---

stdlib/argparse.pyi

```py
import argparse
parser = argparse.ArgumentParser()
parser.add_argument('--a', choices=None)
parser.add_argument('--b', choices=[])
parser.add_argument('--c', choices=['1', '2'])
args = parser.parse_args()
```
Run:
```bash
> python3 test.py -h
usage: test.py [-h] [--a A] [--b {}] [--c {1,2}]
optional arguments:
-h, --help  show this help message and exit
--a A
--b {}
--c {1,2}
```

argparse#add_argument: make choices optional

---

stubs/click/click/core.pyi

Click uses tuples for this internally ([1], [2]), so typing as `List` was incorrect, not just overly restrictive.
[1]: https://github.com/pallets/click/blob/d09ef712972df060080a43cade589405f777369d/src/click/core.py#L2039
[2]: https://github.com/pallets/click/blob/d09ef712972df060080a43cade589405f777369d/src/click/decorators.py#L247

Click parameter declarations work with any iterable

---

stdlib/tkinter/filedialog.pyi

Fixes #5571 
The options are documented in `tk_getOpenFile` and `tk_getSaveFile` manual page (they are both in the same manual page), but to figure out which options actually apply, it turns out to be easiest to give an invalid option:
```
>>> import tkinter.filedialog
>>> tkinter.filedialog.askopenfilename(lol="wat")
File "/usr/lib/python3.7/tkinter/filedialog.py", line 375, in askopenfilename
return Open(**options).show()
File "/usr/lib/python3.7/tkinter/commondialog.py", line 43, in show
s = w.tk.call(self.command, *w._options(self.options))
_tkinter.TclError: bad option "-lol": must be -defaultextension, -filetypes, -initialdir, -initialfile, -multiple, -parent, -title, or -typevariable
```

add types to tkinter.filedialog.ask*

---

stdlib/random.pyi

Per [documentation of `random.choices()`](https://docs.python.org/3/library/random.html#random.choices):
> The *weights* or *cum_weights* can use any numeric type that interoperates with the `float` values returned by `random()` (that includes integers, floats, and fractions but excludes decimals)
I've also ensured that the type `Sequence[Union[...]]` is correct rather than `Union[Sequence[...], ...]`.

Update `random.choices` to include other types supported by `weights`

---

stdlib/_ast.pyi

`MatchSingleton` can only ever be `True`, `False`, or `None`.
The current `Optional[bool]` is inaccurate for that as it also allows implicit booleans: `1 != 2`.
https://docs.python.org/3.10/library/ast.html#ast.MatchSingleton

Use Literal for MatchSingleton

---

stubs/Flask/METADATA.toml
stubs/Jinja2/METADATA.toml
stubs/MarkupSafe/METADATA.toml
stubs/Werkzeug/METADATA.toml
stubs/click/METADATA.toml
stubs/itsdangerous/METADATA.toml
stubs/jwt/METADATA.toml

To latest version pre obsoletion. While the minor versions are not necessarily 100% correct (it's possible that some stubs haven't been updated to the latest version), this is a clearer marker that these stubs are not intended to be used with the latest version that includes stubs.

Bump versions of obsolete packages

---

stdlib/signal.pyi

Closes #5621.
In the `Callable` variant of `signal._HANDLER`, change `Signals` to `int` and `FrameType` to `Optional[FrameType]`.

Signal handler callables take `int`, not `Signals`

---

stubs/cryptography/METADATA.toml

Bump version to 3.3 (last version before Python 2 removal)

Mark cryptography as obsolete

---

stdlib/sys.pyi

Hey I ran across this since my [sys.stdout.reconfigure](https://docs.python.org/3/library/io.html#io.TextIOWrapper.reconfigure) call wasn't recognized.
If this is incorrect and I'm misunderstanding/missing something, please let me know :)
```py
>>> import sys
>>> [type(getattr(sys, x)) for x in ['stdin', 'stdout', 'stderr', '__stdin__', '__stdout__', '__stderr__']]
[<class '_io.TextIOWrapper'>, <class '_io.TextIOWrapper'>, <class '_io.TextIOWrapper'>, <class '_io.TextIOWrapper'>, <class '_io.TextIOWrapper'>, <class '_io.TextIOWrapper'>]
```

use TextIOWrapper for sys.__stdin__, sys.__stdout__, sys.__stderr__

---

stdlib/contextlib.pyi

#4827 doesn't have all boxes checked yet, but I want to see what CI has to say about this.

use ParamSpec for @contextmanager

---

stdlib/logging/__init__.pyi

* Use PEP 604, instead of Optional.
* Override FileHandler.stream and setStream to require a TextIOWrapper
instead of a SupportsWrite object.
* FileHandler._open() now returns a TextIOWrapper instead of IO. Using
a file opened in binary mode would not work.
See also pytest-dev/pytest#8764.

Improve logging.StreamHandler and FileHandler

---

stdlib/logging/__init__.pyi

Make logging.StreamHandler generic over stream

---

stdlib/logging/__init__.pyi

documented for style parameter: https://docs.python.org/3/library/logging.html#logging.Formatter

stdlib logging: specify style type as literal choice

---

stdlib/json/encoder.pyi

Both functions are undocumented, but not private.

Add json.py_encode_basestring stubs

---

requirements-tests-py3.txt
tests/mypy_test.py

This is part of #5751. It runs the mypy tests for stdlib and third-party stubs separately and has the option of running third-party stubs with the distributed typeshed package. This option is currently not enabled, because we already ship third-party stubs using `_typeshed` features not shipped with latest mypy.
This is best reviewed commit by commit.

Run mypy tests for stdlib and third-party separately

---

stubs/protobuf/google/protobuf/internal/extension_dict.pyi

Proto itself supports primitives, not just messages.
See https://github.com/dropbox/mypy-protobuf/issues/244 for an example
motivating this change.
Test Plan: I was able to use MYPYPATH to test an updated version of
mypy-protobuf with this change.

Support arbitrary values for extension values

---

scripts/create_baseline_stubs.py

This tool is a simple wrapper around stubgen and other tools that simplifies the
creation of "baseline" stubs with minimal annotation coverage. These stubs allow
basic type checking (e.g. number of arguments, whether X is valid as a base class),
and once we have baseline stubs, it's easy to contribute incremental changes that
add type annotations.
Here's a summary of what the tool does:
1. Check that the package is installed
2. Run stubgen
3. Copy generated stubs to the correct directory under `stubs/`
4. Run black
5. Run isort
6. Generate basic metadata with correct package version
7. Update pyright exclusions (needed since there are missing types)
8. Print suggestions about next steps needed to contribute stubs to typeshed
For example, to generate stubs for `iso8601`, you can run it …

Add simple tool for creating baseline stubs

---

scripts/create_baseline_stubs.py

The isort `--recursive` option doesn't recognize `.pyi` files, so find all
`.pyi` files explicitly.
Run isort before black since changes made by isort don't follow stub
conventions.

Fix import sorting in create_baseline_stubs script

---

stubs/protobuf/google/protobuf/internal/extension_dict.pyi

See https://github.com/dropbox/mypy-protobuf/issues/244 for the
inspiration for this. Repeated extensions are allowed by protobuf,
and they generate to extension values with repeated fields.
Notably map fields (ScalarMap and MessageMap) are NOT allowed to be
extension values - producing errors as such - so those are omitted.
testproto/test_extensions3.proto:19:6: Map fields are not allowed to be extensions.

Supported repeated field containers for extensions

---

stdlib/http/cookiejar.pyi

I think that's the last, what `stubtest` was showing for the http package.

add missing type hints in http.cookiejar

---

scripts/generate_proto_stubs.sh
stubs/protobuf/@tests/stubtest_allowlist.txt
stubs/protobuf/METADATA.toml
stubs/protobuf/google/protobuf/any_pb2.pyi
stubs/protobuf/google/protobuf/api_pb2.pyi
stubs/protobuf/google/protobuf/compiler/plugin_pb2.pyi
stubs/protobuf/google/protobuf/descriptor_pb2.pyi
stubs/protobuf/google/protobuf/duration_pb2.pyi
stubs/protobuf/google/protobuf/empty_pb2.pyi
stubs/protobuf/google/protobuf/field_mask_pb2.pyi
stubs/protobuf/google/protobuf/source_context_pb2.pyi
stubs/protobuf/google/protobuf/struct_pb2.pyi
stubs/protobuf/google/protobuf/timestamp_pb2.pyi
stubs/protobuf/google/protobuf/type_pb2.pyi
stubs/protobuf/google/protobuf/wrappers_pb2.pyi

Includes features from 2.7 and 2.8
https://github.com/dropbox/mypy-protobuf/blob/master/CHANGELOG.md
Notably
- propagate comments
- Field ordering in original order
- remove type-ignore used on enums

Update protobuf generated stubs from mypy-protobuf 2.8

---

stdlib/pickle.pyi

I added the new protocol version 5 attributes, which were added in 3.8.

add missing protocol version 5 in pickle

---

stubs/beautifulsoup4/bs4/element.pyi

Modified definitions of _SimpleStrainable and _SimpleNormalizedStrainable to include Callable[[Tag], bool] (see https://www.crummy.com/software/BeautifulSoup/bs4/doc/#a-function)

Fix for _SimpleStrainable type def (issue #5809)

---

stubs/termcolor/METADATA.toml
stubs/termcolor/termcolor.pyi

I also raised the version to the latest release version.

add missing type hints in termcolor

---

stubs/requests/@tests/stubtest_allowlist.txt
stubs/requests/requests/packages/urllib3/util/retry.pyi

For reference, here is the corresponding source code in urllib3 repo:
https://github.com/urllib3/urllib3/blob/13603ecb4be3bbcd7bd2fd1d650ac659f85a959d/src/urllib3/util/retry.py#L225-L243

Update `urllib3.util.retry.Retry.__init__()` to match the latest version released on PyPI

---

stdlib/ssl.pyi

I actually wanted to add just some missing type hints, but then ended up refactoring the enum type hints 😄 
The enum types are dynamically created by collecting the different constants.

refactor enum type hints in ssl

---

stdlib/subprocess.pyi

Although the parameter is called 'seq', the implementation shows that it
can be anything that can be passed to map(), which takes iterables:
https://github.com/python/cpython/blob/0f42b726c87f72d522893f927b4cb592b8875641/Lib/subprocess.py#L565.

Broaden the signature of subprocess.list2cmdline.

---

stdlib/typing.pyi

It's already imported at the top level.
Fixes quora/pyanalyze#221.

remove redundant import from typing

---

stubs/tabulate/METADATA.toml
stubs/tabulate/tabulate.pyi

Just some missing attributes and I also adjusted the version to reflect the current released one.

add missing type hints in tabulate

---

stdlib/@python2/tempfile.pyi

Reference: https://docs.python.org/2.7/library/tempfile.html#tempfile.TemporaryFile (similar for the others).
As for `TemporaryDirectory`, I don't think it actually exists on Python 2 (at least I get an import error), so didn't touch it.

python2/tempfile: dir argument can be None

---

stubs/requests/requests/__init__.pyi

These two are missing from this file even though they are present in the requests package's `__init__.py`.
There is one other missing exception, `JSONDecodeError`, but I wasn't sure how best to handle that so I've omitted it.
It would require something in `compat.pyi` which inherits differently in certain conditions.

Add missing exceptions to requests __init__.pyi

---

stdlib/logging/__init__.pyi

This bug was discovered in https://github.com/pypa/build/pull/339; we shipped build 0.6.0 with a usage of `log(logging.INFO, message, stacklevel=2)`, which is not supported in Python 3.6 and 3.7, but incorrectly reported as passing in MyPy, since there is a `**kwargs` here. This is incorrect; these functions all simply accept `*args` and `**kwargs`, but just pass them on to `_log`, which does not support `**kwargs` - see https://github.com/python/cpython/blob/af441df3ff0eab7bce782011cf702a8a9005da1f/Lib/logging/__init__.py#L1565, for example.
If, like me, you wondered about named placeholders for the formatting string, those are done with dicts, just like with `%`.
```pycon
>>> logging.warning("%(foo)s", foo="bar") …
```

fix: arbitrary keyword arguments are not accepted in logging functions

---

stubs/selenium/selenium/webdriver/remote/webdriver.pyi

Docstring description of the argument includes this text:
> Either a string representing URL of the remote server or
> a custom remote_connection.RemoteConnection object.

Fix annotation in selenium.webdriver.remove.webdriver

---

stdlib/logging/__init__.pyi

Follow up to #5849 - Logger instances do not support arbitrary keywords, only modified LoggerAdaptor instances may. It does not seem to be supported to manually set `logger.root`, and it's not publicly documented, and it's a slightly customized RootLogger class anyway, so it should be safe to assume no one is setting it with a LoggerAdaptor instance. Also, `logger.root` is allowed to be written to in typeshed, but it's statically typed as RootLogger, so setting it to a LoggerAdaptor is a type error already.

fix: standalone logger functions also do not accept arbitrary keywords

---

stdlib/tkinter/__init__.pyi

Fixes #5861 
Even though `tags="foo"` works at runtime, it seems like a bad idea to support it in the stubs, and it would be more readable to just specify `tags=["foo"]`. For example, `tags="foo bar"` creates two separate tags, just like the more readable `tags=["foo", "bar"]` or `tags=("foo", "bar")`. I can change this if we want to instead follow our "avoid false positives" guideline.

fix tkinter.Canvas tags option

---

CONTRIBUTING.md

The new syntax has been used on changed lines for a while now, and #5872 changed most stubs to use it.

new union syntax in CONTRIBUTING.md

---

stubs/croniter/@tests/stubtest_allowlist.txt
stubs/croniter/METADATA.toml
stubs/croniter/croniter.pyi

add missing arguments to croniter

---

stdlib/_warnings.pyi
stdlib/warnings.pyi

@bluetech [suggested](https://github.com/urllib3/urllib3/pull/2359#discussion_r684765611) adding `filters` to `warnings.pyi`.

Add filters to stdlib.warnings.pyi

---

stubs/bleach/METADATA.toml
stubs/bleach/bleach/__init__.pyi
stubs/bleach/bleach/callbacks.pyi
stubs/bleach/bleach/html5lib_shim.pyi
stubs/bleach/bleach/linkifier.pyi
stubs/bleach/bleach/sanitizer.pyi
stubs/bleach/bleach/utils.pyi

bleach 4 has no API changes, but dropped support for old Python
versions.

Upgrade bleach version to 4 and drop Python 2

---

.github/workflows/tests.yml

Seemed to be getting a little slow :-)
I'm really excited for https://github.com/python/mypy/pull/10922 to land and speed up mypy primer and stubtest

More shards for stubtest_third_party

---

requirements-tests-py3.txt

This version contains a fix for a pytype bug that is blocking
https://github.com/python/typeshed/pull/5896.

Bump pytype version to 2021.08.11.

---

stubs/simplejson/@tests/stubtest_allowlist.txt
stubs/simplejson/METADATA.toml
stubs/simplejson/simplejson/__init__.pyi
stubs/simplejson/simplejson/raw_json.pyi

Available as `simplejson.RawJSON` since 3.10.0, available also as `simplejson.raw_json.RawJSON` since 3.12.0.
I checked if there are any other features that might be missing in these stubs and the only other new feature I found is `int_as_string_bitcount` encoded option (https://github.com/simplejson/simplejson/blob/16f362cacd53abee3e60b14d18536cf32e4219f0/CHANGES.txt#L242), but these stubs currently just use `Any` for `**kwargs` so I skipped it.

Add `RawJSON` to `simplejson` stubs

---

stubs/docutils/@tests/stubtest_allowlist.txt
stubs/docutils/METADATA.toml
stubs/docutils/docutils/frontend.pyi
stubs/docutils/docutils/parsers/rst/__init__.pyi

The `OptionParser` and `Directive` classes had no `__init__` method stubs which was causing mypy to claim my valid arguments were not expected.
For the `Directive` class I used the documentation from https://docutils.sourceforge.io/0.4/docs/howto/rst-directives.html as my guide.
For the `OptionParser` class I referred to the [original source code: ](https://sourceforge.net/p/docutils/code/HEAD/tree/trunk/docutils/docutils/frontend.py#l591) and some [implementation examples from Sphinx](https://github.com/sphinx-doc/sphinx/blob/9e1b4a8f1678e26670d34765e74edf3a3be3c62c/tests/test_search.py#L38).
It's worth calling out the `components` parameter as it expects a _class_ rather than an object to be passed in (see the Sphinx example for confirmation).
I have read the [contribution …

docutils - added missing stubs for __init__ methods

---

README.md

Tiny PR to fix the malformed URL in the readme for the Python Type School.
Was: https://github.com/python/typeshed/blob/master/python/typing/discussions
Now: https://github.com/python/typing/discussions

Fix malformed typeschool URL

---

CONTRIBUTING.md

Built-in generics not possible in type aliases

CONTRIBUTING: Use PEP 604 syntax

---

stdlib/ssl.pyi

This improves the type annotations for the ‘ssl’ module:
- Various APIs taking file names (e.g. keyfile=, certfile=, cafile=,
capath=, ...) were annotated as accepting only strings, while actually
they accept str, bytes, and os.PathLike (such as pathlib.Path).
CPython's _ssl.c module has always used PyUnicode_FSConverter to
handle (normalize) these. Change the annotations accordingly using the
internal _typeshed.StrOrBytesPath alias.
- Tighten the ‘purpose=’ argument in various functions to use the
already defined ‘Purpose’ enum instead of accepting ‘Any’.

Improve ssl module annotations

---

stdlib/unittest/signals.pyi

After working on the other `ParamSpec` PR I think this should be a `TypeVar` rather than `Any` as type hint.

add ParamSpec to unittest.signals

---

tests/pytype_test.py

We deleted this method as part of our Python 2 cleanup efforts.

Stop using pytype.pytd.typeshed.get_python_major_versions.

---

stdlib/importlib/util.pyi

all three functions are marked as deprecated, but as long as they exist, they can enjoy better type hints 😄

add ParamSpec to importlib.util

---

stubs/six/six/__init__.pyi

```python
import six
def hello(name: six.text_type) -> None:
print(f"Hello {name}!")
hello("Johan")
```
```
(env) /t/dom $ mypy code.py
code.py:2: error: Variable "six.text_type" is not valid as a type
code.py:2: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases
Found 1 error in 1 file (checked 1 source file)
(env) /t/dom [1] $ fd six
```
```
(env) /t/dom $ mypy code.py
Success: no issues found in 1 source file
(env) /t/dom $ 
```
```
(env) /t/dom $ mypy --version
mypy 0.910
(env) /t/dom $ python --version
Python 3.9.6
(env) /t/dom $ pip freeze|grep six
six==1.16.0
types-six==1.16.0
(env) /t/dom $ 
```
There may be other cases like this in the same file, I'm fixing this particular one because I got burned by it.

text_type should be a type alias, not a variable

---

stubs/mock/METADATA.toml
stubs/mock/mock.pyi

- AsyncMock is available in 3.6+ with the third party mock package
- The 3.8+ restriction only exists in stdlib unittest.mock

Make AsyncMock stubs available for python 3.6+

---

stubs/geoip2/@tests/stubtest_allowlist.txt
stubs/geoip2/METADATA.toml

I chose version 3.0 instead of 4.0, since this 4.0 dropped Python 2
support and the stubs are marked as still supporting Python 2.

Add version and obsolete since field

---

pyrightconfig.json
pyrightconfig.stricter.json

tornado was removed in 5a7f25584ed720be571879b5aa416f5dde6fcf46.

Remove leftover pyright tornado configuration

---

pyrightconfig.json
pyrightconfig.stricter.json

The package was renamed in a98fceca2f6e6b9af84f467288a9e52d8c459417.

Remove leftover openssl-python in pyright configuration

---

tests/check_pep_604.py

- Make the script easier to run locally by not checking irrelevant files (such as `.pyi` files inside virtualenvs)
- Make protobuf check work on windows

clean up tests/check_pep_604.py

---

.github/workflows/tests.yml

This makes it easier to see, in which version(s) an error occured.

CI: use one runner per mypy version

---

stdlib/enum.pyi

```python
import enum
class C(enum.Enum):
D = 1
reveal_type(C._member_names_)
```
**before**:
```console
$ mypy t.py
t.py:6: note: Revealed type is "Literal[t.C._member_names_]?"
```
**after**:
```console
$ mypy t.py --custom-typeshed .
t.py:6: note: Revealed type is "builtins.list[builtins.str]"
```

fix types of enum _member_names, etc.

---

stdlib/csv.pyi

I think this might actually work if you pass just an `Iterable`, however since that would allow passing a generator (which would definitely not work correctly) I've kept this as `Collection`.
Fixes https://github.com/python/typeshed/issues/5993

Relax DictWriter.fieldnames closer to implementation

---

stdlib/zipfile.pyi
tests/stubtest_allowlists/py310.txt

Couple of different improvements I made.
There are several changes connected to Python 3.10. I also changed the `mode` parameter type to a `Literal`.

Improve typing in zipfile

---

stubs/python-slugify/METADATA.toml
stubs/python-slugify/slugify/slugify.pyi

According to the [documentation](https://github.com/un33k/python-slugify#options) (and [source code](https://github.com/un33k/python-slugify/blob/master/slugify/slugify.py#L100)) of python-slugify the type of the replacements parameter is not an iterable of strings, but an iterable of 2-tuple strings. This PR fixes the argument type.

Fix python-slugify replacements argument type

---

stubs/Deprecated/deprecated/sphinx.pyi

The signature was changed in Deprecated 1.2.13.

Update deprecated.sphinx.deprecated signature

---

stubs/Pillow/PIL/ImageDraw.pyi

TypeError Exception is raised if stroke_width is supplied as float.
Why: https://github.com/python-pillow/Pillow/blob/2bc754e1021081615e821acc1cd5d928e31d6d1d/src/_imagingft.c#L769
Happy to have my first contribution here! :smile:

Fix type of stroke_width parameter in Pillow's ImageDraw.*text* functions

---

stubs/redis/redis/lock.pyi

This fixes wrong type annotation on `blocking_timeout` argument to `redis.lock.Lock` object.

Fix type of blocking_timeout argument to redis.lock.Lock

---

.github/workflows/tests.yml
requirements-tests-py3.txt
tests/check_consistent.py
tests/mypy_test.py
tests/stubtest_third_party.py

Switches from `toml` to `tomli`

---

stdlib/_typeshed/__init__.pyi
stdlib/builtins.pyi

Add SupportsNext and SupportsAnext protocols
Offshoot of #6035

(a)next only requires __(a)next__, not Iterator

---

stdlib/concurrent/futures/_base.pyi

Fix set annotations in concurrent.futures._base

---

stdlib/@python2/logging/handlers.pyi
stdlib/logging/handlers.pyi

As per CPython logging handlers source:
https://github.com/python/cpython/blob/main/Lib/logging/handlers.py#L835
The `SysLogHandler` has attribute `address` that is not included in the typeshed.
This pull request fixes that.

Fix stdlib logging SysLogHandler missing attribute

---

stdlib/multiprocessing/process.pyi

A user filed an issue against pytype about this attribute being missing:
https://github.com/google/pytype/issues/1010. I determined its type from
the source code:
https://github.com/python/cpython/blob/3.9/Lib/multiprocessing/process.py.

Add undocumented attribute multiprocessing.process.BaseProcess._identity

---

stubs/atomicwrites/METADATA.toml
stubs/backports_abc/METADATA.toml
stubs/boto/METADATA.toml
stubs/characteristic/METADATA.toml
stubs/chardet/METADATA.toml
stubs/first/METADATA.toml
stubs/paramiko/METADATA.toml
stubs/python-dateutil/METADATA.toml
stubs/python-gflags/METADATA.toml
stubs/pyvmomi/METADATA.toml
stubs/retry/METADATA.toml
stubs/singledispatch/METADATA.toml
stubs/toml/METADATA.toml

This updates the third-party package versions of all packages still marked with "0.1" and supporting Python 2 to the latest version available on pypi, with the following exceptions:
* `backports` has the wrong package name.
* `click-spinner` actually has version `0.1.10` on pypi.
* The latest version on pypi of the remaining packages only support Python 3 and are outdated in typeshed.

Update third-party package versions

---

CONTRIBUTING.md
tests/check_consistent.py

Allow three-component third-party versions

---

scripts/create_baseline_stubs.py

I have now used the script a few times. It's awesome, but I have always found the message it prints when done to be quite misleading. I changed it like this:
- Show the command for running stubtest. When using the script, I didn't know how to stubtest locally, so I just created the PR and waited for CI errors.
- Combine PR creation into a single step to shorten the list. We don't want the list to be too intimidating. Our contribution process is simple, and we shouldn't make it look more complicated than it really is.
- Run `flake8` after `black` and `isort`, so that it won't complain about style. It will still complain about unused imports, for example. We could use pyright for that, but then you would need to have node installed just to create new stubs (and again, it is nicer to run it …

change prints in scripts/create_baseline_stubs.py

---

stubs/ttkthemes/ttkthemes/themed_style.pyi

It works at runtime. The arguments get passed to `ttk.Style` which uses tkinter's default root window as the master widget when it is not given.

ttkthemes: allow constructing ThemedStyle with no arguments

---

stubs/requests/requests/sessions.pyi

`requests` supports not only passing binary file-like objects for multi-part file uploads but also additionally passing a name,  content-type and headers. This adds type hints for those options.
See https://docs.python-requests.org/en/master/user/quickstart/#post-a-multipart-encoded-file.

Support name, content-type and headers in file upload

---

stdlib/locale.pyi

Source: https://github.com/python/cpython/blob/bb3e0c240bc60fe08d332ff5955d54197f79751c/Modules/_localemodule.c#L555-L556
Related https://github.com/python/mypy/issues/11183

Adds `AM_STR` and `PM_STR` to `locale.py`

---

stubs/beautifulsoup4/bs4/element.pyi

PageElement.find_all() can return both PageElement and any subclass of PageElement on the latest version of bs4 and ResultSet already accounts for this so find_all() should be typed with the same generic TypeVar.

Improves BeautifulSoup4 typing.

---

stubs/dateparser/dateparser/date.pyi

Considering `dict[Locale, None]`: looks like it is a hack of some kind: https://github.com/scrapinghub/dateparser/issues/457

More specific types in `dateparser/date.pyi::DateDataParser`

---

stdlib/inspect.pyi

resolve #6068 
`inspect.Parameter.empty`/`inspect.Signature.empty` is same as class `_empty` but not instance of `_empty`

Fix error type for inspect Parameter/Signature empty

---

stdlib/traceback.pyi

Currently, `StackSummary.extract(walk_stack(frame))` is a typecheck error, because the annotation calls for a generator but `walk_stack()` returns an iterable.  Since we never `.send()`, I've updated the type hint on `extract()`.

`StackSummary.extract()` takes an `Iterable`

---

stubs/redis/redis/lock.pyi

The Lock class as a property local that has a token property that sometimes
needs be accessed / set.
```python
lock = redis.lock(key)
lock.local.token = token
lock.extend(10)
```
Technically the type of `local` is `SimpleNamespace | threading.local`
but I think this setup is a bit stricter but satisfies the API.

redis: include local property on Lock class

---

stdlib/plistlib.pyi

issue: #6032
- added new types to `plistlib` stub according to the following
[plistlib python docs](https://docs.python.org/3/library/plistlib.html#module-plistlib)
[accepted types in cpython implementation](https://github.com/python/cpython/blob/e046aabbe386fdf32bae6ffb7fae5ce479fd10c6/Lib/plistlib.py#L327)

FIX: types for value attribute in dump and dumps

---

stdlib/unittest/mock.pyi

The _T annotation for **kwargs would seem to imply that each of the kwarg values would be of the same type. However the interface conveys no such constraint: Any key can be mocked with any value, including DEFAULT.
A simple case that is improperly handled is `mock.patch.multiple(settings, A=1, B='foo')` since `1` and `'foo'` aren't consistent types.

Remove covariance in mock.patch.multiple

---

stubs/psutil/psutil/_compat.pyi

For #6110.
These are circular definitions; export them directly from the builtins instead (like other modules).

Properly export types from psutil._compat

---

stubs/paramiko/paramiko/py3compat.pyi

For #6110.
Like in #6112, these are circular type definitions. Use the correct builtins from below (for Python 2/3).

Properly export bytes from paramiko.py3compat

---

stdlib/multiprocessing/context.pyi

For #6110.
`pool` isn't exported from `multiprocessing`. Import `Pool` from `multiprocessing.pool` directly rather than relying on the side effect of it being loaded by `multiprocessing` at some point.

Fix use of unexported Pool type in multiprocessing.pool

---

stdlib/string.pyi

Adds the following attributes to `string.Template`.
```
$ stubtest --custom-typeshed-dir . string --concise
string.Template.braceidpattern is not present in stub
string.Template.delimiter is not present in stub
string.Template.flags is not present in stub
string.Template.idpattern is not present in stub
string.Template.pattern is not present in stub
```
Also just wanted to say thanks for the fantastic [Good ways to contribute](https://github.com/python/typeshed/issues/4641) issue.

Add the rest of string.Template's class attributes

---

stubs/freezegun/@tests/stubtest_allowlist.txt
stubs/freezegun/freezegun/api.pyi

Stubs for freezegun were missing the `as_kwarg` argument, which [was added](https://github.com/spulec/freezegun/commit/c48b04fba5d8a829f3c5d2b05aa602231dc3254a) in freezegun version 1.0.0.

freezegun: Add missing argument

---

requirements-tests-py3.txt
stdlib/functools.pyi

This PR uses `ParamSpec` to make `lru_cache` preserve the signature of the wrapped function.
Unfortunately this removes the constraint that `*args` and `**kwargs` must be `Hashable` at least until the meaning of the `bound` parameter in `ParamSpec` is decided, but I feel that preserving the function signature is a worthy trade-off.

lru_cache preserves signature of wrapped function

---

stdlib/types.pyi

Per the Python documentation, `ModuleType.__file__` is `Optional`: 
> __file__ is optional. If set, this attribute’s value must be a string. The import system may opt to leave __file__ unset if it has no semantic meaning (e.g. a module loaded from a database).
Source: https://docs.python.org/3/reference/import.html#file__

Update ModuleType.__file__ to be Optional

---

tests/mypy_test.py

This is a first step towards #5952. For each third-party distribution, a separate mypy call is started. This has a few advantages, but also a few drawbacks:
* Missing dependencies in `METADATA.toml` are now spotted, since only the dependencies listed there are being added to the list of files to test.
* It's possible to add a custom configuration for a distribution to `METADATA.toml`. Previously, all configurations were merged before mypy was run, therefore all configurations applied to all files. Now, only the configurations of a distribution and its dependencies are merged when testing a distribution.
* Adding a non-stub dependency will crash the tests. (But this wouldn't work anyway, at the moment. This is actually a first step towards allowing this.)
* Stubs are now tested multiple …

Test third-party stubs in isolation

---

tests/mypy_test.py

The list hasn't been used since 2016 and I don't think we should add files that mypy can't parse anyway at this point.
This simplifies `mypy_test.py` quite a bit.

Remove mypy excludes

---

CODE_OF_CONDUCT.md

By removing this, the code of conduct from the Python organization
(https://github.com/python/.github/blob/master/CODE_OF_CONDUCT.md)
should be picked up.

Remove our custom code of conduct link

---

stubs/Markdown/markdown/blockprocessors.pyi

markdown.blockprocessors.ReferenceProcessor was missing from this stub.
https://github.com/Python-Markdown/markdown/blob/master/markdown/blockprocessors.py#L559

Add missing class to Markdown

---

tests/mypy_test.py

Only print the mypy command twice per version: Once for the stdlib and
once for the stubs. Use a dummy /tmp path. Add a header for each tested
Python version and remove the Python version from the individual stubs.

Reduce mypy_test output

---

pyrightconfig.json
pyrightconfig.stricter.json

Done with quick and dirty script, with manual cleanup afterwards:
```bash
#!/bin/bash
set -e
git checkout pyrightconfig.json
grep '        ".*/.*",' pyrightconfig.json | while read -r line; do
cp pyrightconfig.json old.json
python3 -c 'import sys; s=open("pyrightconfig.json").read(); open("pyrightconfig.json","w").write(s.replace(sys.argv[1],""))' "$line"
if npx -p pyright@1.1.184 pyright -p pyrightconfig.json &>/dev/null; then
echo "ok without:  $line"
rm old.json
else
echo "need:        $line"
mv old.json pyrightconfig.json
fi
done
```

Remove unnecessary pyrightconfig excludes

---

stdlib/builtins.pyi

I'm aware that mypy and others already special-case ``builtins.callable``, but it might be nice to formally state this property of the function in the stubs.

Return ``TypeGuard[Callable[..., object]]`` from ``builtins.callable``

---

stdlib/builtins.pyi

These attributes have all been added in Python 3.10+; see https://github.com/python/cpython/pull/25268

Add `__name__`/`__qualname__`/`__wrapped__` to `staticmethod`/`classmethod`

---

stdlib/typing_extensions.pyi

Code is https://github.com/python/typing/blob/master/typing_extensions/src_py3/typing_extensions.py#L1126 and a little way down.

typing_extensions.get_type_hints exists only in 3.7+

---

CONTRIBUTING.md
requirements-tests-py3.txt
tests/README.md

This PR:
- Modifies `CONTRIBUTING.md` and `tests/README.md` to add instructions for running tests on Windows, and clarify that pytype tests cannot be run on Python 3.10.
- Modifies  `requirements-tests-py3.txt` so that running `pip install -r requirements-tests-py3.txt` does not fail on Windows.
- Closes #6282

Improve support for running tests on Windows

---

stdlib/builtins.pyi

This proposal is basically "make `classmethod` and `staticmethod` generic in such a way that we get more type specificity now, and it will also be easy to add `ParamSpec` once mypy supports it".
Slightly different to @srittau's approaches in #5703 and #5682

Make `staticmethod`/`classmethod` generic in their return type

---

stdlib/builtins.pyi

None of these classes can be subclassed at runtime.

Add `@final` to `slice`/`memoryview`/`range`

---

stdlib/builtins.pyi

These aren't subclassable at runtime. (Missed these two in my previous PR due to the fact that they're exposed in the `types` module, rather than builtins, at runtime. Also they're both a little weird to say the least, so let's see what the CI thinks...)

Add `@final` to `NotImplementedType` and `ellipsis`

---

stdlib/builtins.pyi
stdlib/importlib/__init__.pyi
stdlib/types.pyi
tests/stubtest_allowlists/py3_common.txt

This PR is an attempt at solving #6295 by adding `__getattr__` to `types.ModuleType` and changing the return type of `builtins.__import__` so that it now returns `types.ModuleType` rather than `Any`.

Harmonise return type of `builtins.__import__` and `importlib.import_module`

---

tests/mypy_test.py

* Remove --strict-optional: This has been the default since mypy 0.600.
* Remove --disallow-subclassing-any: When we subclass Any in typeshed,
we do so deliberately. This just causes us to add unncessary ignores.

Clean up mypy flags

---

stdlib/builtins.pyi
stdlib/importlib/__init__.pyi

This corrects an oversight from #6292, in which I changed the annotation for the `globals` and `locals` arguments of `builtins.__import__`, but not for `importlib.__import__`, which should have the same signature as `builtins.__import__`.

Resolve builtins/importlib inconsistencies

---

stdlib/_collections_abc.pyi
stdlib/builtins.pyi
stdlib/collections/__init__.pyi

Currently, the following code succeeds at runtime, but [fails mypy](https://mypy-play.net/?mypy=latest&python=3.10&flags=show-error-codes&gist=4671377be6f6e4fa6601f13e41cdfbb4):
```python
from _collections_abc import dict_keys
```
This PR proposes several changes to bring the `_collections_abc` stub closer to its runtime definition. The significant change is moving the definitions of `dict_keys`, `dict_values` and `dict_items` from `builtins` to `_collections_abc`.
I have also added `@final` to these classes, as they cannot be subclassed at runtime, and added `# type: ignore` comments to `_OrderedDictKeysView`/`_OrderedDictValuesView`/`_OrderedDictItemsView`. (These are indeed subclasses of `dict_keys`/`dict_values`/`dict_items`, even though the three classes cannot be subclassed _at …

Bring `_collections_abc` closer to runtime definition

---

pyproject.toml
stdlib/@python2/ast.pyi
stdlib/@python2/warnings.pyi
stdlib/ast.pyi
stdlib/builtins.pyi
stdlib/collections/__init__.pyi
stdlib/tracemalloc.pyi
stdlib/warnings.pyi

With the current configuration settings in pyproject.toml, isort has not been recognising these modules as standard-library modules. This PR adds them to the "extra_standard_library" list in the isort settings, and reformats the stdlib accordingly.

Fix isort w.r.t. `_ast`/`_collections_abc`/`_tracemalloc`/`_warnings`

---

.github/workflows/stubtest.yml
.github/workflows/tests.yml
stubs/Pillow/METADATA.toml

On PRs, stubtest now only runs for stdlib and the third-party stubs that changed. In addition, once a day, stubtest is run against stdlib and all third-party stubs to find potential problems with new upstream releases.

Rework stubtest tests

---

stdlib/types.pyi

Hi!
I hope it is OK to start adding stuff from Python 3.11. I am ready to update the code in case of any changes to the API in the following alpha/beta versions.
`co_positions()` is the new `codeobject` method introduced in PEP 657 to retrieve source code positions of bytecode instructions. See
- [Data Model - codeobject.co_positions()](https://docs.python.org/3.11/reference/datamodel.html#codeobject.co_positions)
- [PEP 657 - Include Fine Grained Error Locations in Tracebacks](https://www.python.org/dev/peps/pep-0657/)
- [What’s New In Python 3.11 - Enhanced error locations in tracebacks](https://docs.python.org/3.11/whatsnew/3.11.html#enhanced-error-locations-in-tracebacks)
Thank you 🙇‍♂️

Add codeobject.co_positions() for Python 3.11

---

stdlib/sys.pyi

Going off the documentation at https://docs.python.org/3/library/importlib.html#importlib.abc.MetaPathFinder.find_spec.

Adjust `MetaPathFinder`

---

stdlib/contextlib.pyi

This PR refactors `contextlib.pyi` so that classes inside the stub file use `contextlib.AbstractContextManager` and `contextlib.AbstractAsyncContextManager`, instead of the deprecated aliases from the `typing` module.

Use `contextlib` classes inside `contextlib`

---

stdlib/functools.pyi

This reverts commit 8bda66a73725ff98919b8b57e600178591e948c2.
The change causes issues with ParamSpec implementations in type
checkers, at least pyright and my work-in-progress support for
ParamSpec in mypy. It's not yet clear how to fix the issues, so I
think that it's best to revert this, at least temporarily until we've
found a good solution. See #6347 for context.

Revert "lru_cache preserves signature of wrapped function (#6221)"

---

tests/check_new_syntax.py

Unnecessary uses of these aliases have now been eradicated across typeshed, meaning we can now check for uses of the deprecated aliases in `check_new_syntax.py`.
(This PR doesn't attempt to check for `typing.Set` and `typing.ContextManager`, as they are more complex. `typing.Set` has a name clash with `collections.abc.Set` (a different class!), and `typing.ContextManager` cannot be substituted with `contextlib.AbstractContextManager` where 2.7 compatibility is required. I might do these in a separate PR.)

Check for `typing.Deque`, `typing.FrozenSet` and `typing.DefaultDict` in `check_new_syntax.py`

---

tests/stubtest_allowlists/py3_common.txt

`stubtest_allowlists/py3_common.txt` previously repeated this line 3 times. I removed the one repetition that was not directly above `Coroutine` and `Generator` entries.

delete duplicate comment

---

stdlib/typing.pyi
stdlib/typing_extensions.pyi

It looks like a couple people are using this in the wild.
Resolves https://github.com/python/typeshed/issues/6393

typing: add _ProtocolMeta

---

stdlib/ipaddress.pyi

Discovered by running `stubtest_stdlib` without the `--ignore-missing-stubs` option. Added to cpython in [this BPO issue](https://bugs.python.org/issue34788). Documentation for the function is [here](https://docs.python.org/3/library/ipaddress.html#ipaddress.IPv6Address.scope_id).

Add missing `scope_id` property to `IPv6Address`

---

stdlib/ssl.pyi

The documentation assures me that these were both added in 3.10: https://docs.python.org/3/library/ssl.html

ssl: Add missing VerifyFlags

---

stdlib/sre_constants.pyi

These were added in 3.7: https://bugs.python.org/issue31690

Add missing sre_constants opcodes

---

stdlib/socketserver.pyi

It looks like an int in the source code: https://github.com/python/cpython/blob/8d1a5800645575ec876932bbb9aed3aa65d18f46/Lib/socketserver.py#L524.
Stubtest flagged it as being missing in all supported Python versions, on all platforms: https://github.com/python/typeshed/pull/6403/files

Add socketserver.UDPServer.max_packet_size

---

stdlib/os/__init__.pyi

Documentation here: https://docs.python.org/3/library/os.html#os.waitstatus_to_exitcode
In reality, it only accepts a positive integer, but there's no way of succinctly expressing that.

Add `os.waitstatus_to_exitcode`

---

stubs/psycopg2/psycopg2/errors.pyi

Psycopg2: inherit `Error` and `Warning` from `Exception`
I don't know why stubgen got it wrong, but:
```python
Python 3.10.0 (default, Oct  4 2021, 22:09:55) [GCC 9.3.0] on linux
>>> import psycopg2
>>> psycopg2.__version__
'2.9.2 (dt dec pq3 ext lo64)'
>>> psycopg2.errors.Error.__mro__
(<class 'psycopg2.Error'>, <class 'Exception'>, <class 'BaseException'>, <class 'object'>)
>>> psycopg2.errors.Warning.__mro__
(<class 'psycopg2.Warning'>, <class 'Exception'>, <class 'BaseException'>, <class 'object'>)
```
`Error` and `Warning` classes are `Exception` and not presenting them as such leads to mypy saying:
```
error: Exception type must be derived from BaseException
```

psycopg2: Error and Warning are Exceptions

---

.github/workflows/tests.yml

`foo && bar` as a short way to `if foo; then bar; fi` wasn't great, because it makes the CI fail when `foo` is false.

ci: fix stubtest_third_party while loop

---

stdlib/traceback.pyi

https://docs.python.org/3/library/traceback.html#traceback.print_exception
The first arg of `print_exception` accepts an exception object in 3.10.

Correct print_exception for 3.10.

---

stdlib/asyncio/__init__.pyi
tests/stubtest_allowlists/py310.txt
tests/stubtest_allowlists/py37.txt
tests/stubtest_allowlists/py38.txt
tests/stubtest_allowlists/py39.txt

I added these to `asyncio.tasks` in #6418, but evidently forgot to add the import in `asyncio.__init__`.

Add missing `asyncio` functions, part II

---

tests/stubtest_allowlists/py3_common.txt

It does "exist" at runtime, but it's a GetSetDescriptor object that always raises `AttributeError`. It does more useful things in `OSError` subclasses such as `BlockingIOError`.

Allowlists: Mark `OSError.characters_written` as "wontfix"

---

stdlib/signal.pyi
tests/stubtest_allowlists/win32.txt

On Windows, `signal.CTRL_C_EVENT` and `signal.CTRL_BREAK_EVENT` are global-variable aliases for members of the `Signals` enum, not integers. Correcting this means we can take them off the allowlist.

Correct `signal.pyi`

---

tests/stubtest_allowlists/py3_common.txt

`distutils` is deprecated in its entirety, slated for removal in 3.12. It makes sense to move these entries to their own section.

Allowlists: move `distutils` entries to their own section

---

stdlib/traceback.pyi

There are now two ways to call `print_exception` or `format_exception`: you either provide the first argument as an exception object, leaving `value` and `tb` unspecified (`None` won't work, since it uses an internal sentinel object), or you call it like in earlier versions, with an exception class or `None` as the first argument.
This was partially fixed in #6487.

correct traceback.print_exception and traceback.format_exception on python 3.10

---

stdlib/tkinter/__init__.pyi
tests/stubtest_allowlists/py3_common.txt

Tkinter is complicated. It does this at runtime:
```python3
class Misc:
...
def grid_rowconfigure(self, ...): ...
rowconfigure = grid_rowconfigure
def grid_size(self): ...
size = grid_size
...
class Grid:
...
rowconfigure = grid_rowconfigure = Misc.grid_rowconfigure
size = grid_size = Misc.grid_size
...
class BaseWidget(Misc):
...
class Widget(BaseWidget, Pack, Place, Grid):
...
```
The intent with `rowconfigure = Misc.grid_rowconfigure` is that you can do `tkinter.Grid.rowconfigure(widget, blah)` instead of `widget.grid_rowconfigure(blah)`, but nobody seems to be doing that in practice.
It is even worse with some methods: **each** of `Pack`, `Grid`, `Place` and `Misc` has a method named `configure`, and they all do different things!
If someone wants to use the weird aliases of the …

tkinter Pack,Grid,Place: delete commented-out aliases, explain in allowlist

---

tests/stubtest_allowlists/py3_common.txt

The note next to `asyncore` and `asynchat` is no longer strictly accurate following the decision of the steering Council to revert the removal of these modules in 3.11: https://github.com/python/steering-council/issues/86#issuecomment-987412171

Correct allowlist notes

---

tests/stubtest_allowlists/py310.txt
tests/stubtest_allowlists/py37.txt
tests/stubtest_allowlists/py38.txt
tests/stubtest_allowlists/py39.txt
tests/stubtest_allowlists/py3_common.txt

`py3_common.txt` includes a `collections.abc.*` entry, with the comment:
> Types are re-exported from _collections_abc, so errors should be fixed there
This seems correct, but means that we should be able to delete many `collections.abc` entries as redundant

Allowlists: delete redundant `collections.abc` entries

---

stubs/paramiko/paramiko/hostkeys.pyi

See https://github.com/paramiko/paramiko/blob/14fd03ec45fed0546aa01b1ef5ccf84508680e02/paramiko/hostkeys.py#L354-L375
`names = names.split(',')` implies that when `names` is passed to `cls` in line 375, it is no longer a string; it is now an array.
More evidence can be seen in [line 78](https://github.com/paramiko/paramiko/blob/14fd03ec45fed0546aa01b1ef5ccf84508680e02/paramiko/hostkeys.py#L78) where the constructor is passed a singleton list.

fix: paramiko.HostKeyEntry.hostnames is a list

---

stdlib/pydoc.pyi
tests/stubtest_allowlists/py3_common.txt

Several method definitions in the `pydoc` stub differ from how they are at runtime. These methods violate LSP, but we should work around that by adding relevant `# type: ignore` comments rather than having incorrect method signatures in the stub.

Improve `pydoc` stubs

---

stdlib/ast.pyi

Got a report about incomplete `ast.parse()` stub in PyCharm: [PY-49663](https://youtrack.jetbrains.com/issue/PY-49663).
`ast.parse()` has four modes affecting the return type (see docs for [`ast.parse()`](https://docs.python.org/3/library/ast.html#ast.parse) and [`compile()`](https://docs.python.org/3/library/functions.html#compile))
| mode | return type | note |
|---|---|---|
| `exec` | `Module` |  |
| `eval` | `Expression` |  |
| `func_type` | `FunctionType` | Python >= 3.8 |
| `single` | `Interactive` |  |
The fix looks trivial but `mypy` doesn't like the extra overrides (as was discovered in #3039) and complains about
```
Overloaded function signatures X and Y overlap with incompatible return types
```
I would appreciate any help while I am struggling to make it right. Atm looks like …

Add more ast.parse() mode overrides

---

stdlib/enum.pyi

`EnumMeta` is an alias to `EnumType`.
Source: https://github.com/python/cpython/blob/4fe5585240f64c3d14eb635ff82b163f92074b3a/Lib/enum.py#L946

Adds `EnumType` class to `enum.pyi`

---

stdlib/enum.pyi
tests/stubtest_allowlists/py3_common.txt

These attributes are read-only properties at runtime; they should be read-only properties in the stub, also.
The following snippet currently fails at runtime, but passes mypy:
```python
from enum import Enum
class Menu(Enum):
SPAM = 1
HAM = 2
Colours = Enum('Colours', 'RED YELLOW BLUE')
Menu.SPAM.name = 'BACON'
Menu.HAM.value = 4
Colours.RED.name = 'PURPLE'
Colours.YELLOW.value = 5
```
With this proposed patch applied, mypy yields the following true-positive errors for the above snippet:
```
test_enum.py:9: error: Property "name" defined in "Enum" is read-only
test_enum.py:10: error: Property "value" defined in "Enum" is read-only
test_enum.py:11: error: Property "name" defined in "Enum" is read-only
test_enum.py:12: error: Property "value" defined in "Enum" is read-only
```

Make `name` and `value` read-only for `Enum`s

---

stdlib/enum.pyi

A `StrEnum` can only have strings as values.

Improve `enum.StrEnum`

---

stubs/pytz/@tests/stubtest_allowlist.txt
stubs/pytz/pytz/tzinfo.pyi

While these abstract methods don't exist at runtime, all sub-classes of
BaseTzInfo implement them. It can be useful to annotate variables with
BaseTzInfo and being able to call these methods on it.
Cf #6551

Add abstract methods to BaseTzInfo

---

.github/workflows/stubtest.yml
.github/workflows/tests.yml

Together with #6600, should make the CI green.
We should fix the stubs instead of sticking to an older version of Python 3.10, but for now I just want the CI to work again.

stubtest: temporary pin to python 3.10.0

---

stdlib/unittest/case.pyi

_LoggingWatcher and _AssertLogsContext were moved to unittest._log in
Python 3.9, but were in unittest.case until 3.8.

Fix unittest.case for Python < 3.9

---

.github/workflows/stubtest.yml

This will most likely cause this workflow to fail, but only during the daily run or when manually triggered. Together with #6613, we can easily work on stubtest failures.

Upgrade daily stubtest workflow to stubtest 0.920

---

stdlib/@python2/_typeshed/xml.pyi
stdlib/@python2/contextlib.pyi
stdlib/_typeshed/xml.pyi
stdlib/asyncio/proactor_events.pyi
stdlib/contextlib.pyi
stdlib/dataclasses.pyi
stubs/click-spinner/click_spinner/__init__.pyi
stubs/redis/redis/lock.pyi
stubs/toposort/toposort.pyi

To be consistent, don't import from typing_extensions.
In #6614, I wasn't sure whether to `from typing import Protocol` or `from typing_extensions import Protocol` because I saw both in the stubs. This changeset replaces every case of the latter with the former.
It's a very minor uniformity thing, but for new contributors to typeshed, every little bit counts! 😄 
I updated library stubs, stdlib stubs, and `@python2` stdlib stubs. If one of these categories should be omitted, or causes some issue, please let me know and I can revert part of the change.

Always import Protocol from typing in stubs

---

stdlib/enum.pyi

We override the name and value properties in `IntEnum`, `auto`, `Flag` and `StrEnum`. Therefore, we should also override the private, mutable versions of these attributes, since we define `_name_` and `_value_` on the base `Enum` class.
Apologies: I accidentally closed this PR; here is a fresh PR...

Add `_name_`/`_value_` overrides for specialised enums 

---

stdlib/logging/__init__.pyi

According to PEP 586:
> Literal may also be parameterized by other literal types, or type aliases to other literal types. For example, the following is legal:
> ```py
> ReadOnlyMode         = Literal["r", "r+"]
> WriteAndTruncateMode = Literal["w", "w+", "wt", "w+t"]
> WriteNoTruncateMode  = Literal["r+", "r+t"]
> AppendMode           = Literal["a", "a+", "at", "a+t"]
> 
> AllModes = Literal[ReadOnlyMode, WriteAndTruncateMode,
>                    WriteNoTruncateMode, AppendMode]
> ```
> This feature is again intended to help make using and reusing literal types more ergonomic.
Having the above in mind, I've ran into an issue with MyPy while trying to implement an argument parser with arguments setting different logging levels, and trying to type a variable with `Literal[logging.NOTSET, …

Use Literal instead of int for logging levels

---

stdlib/urllib/parse.pyi

resolves #6009
I opted to change `safe` to `_Str` (which is `str | bytes`) since that more closely matches the default parameter.   for `quote_via` I changed the first parameter to `AnyStr` to match the overloaded `quote_*` functions

improve urlencode(...) annotation for quote_via

---

stdlib/logging/__init__.pyi

Fixes #6132 
This does not exist by default, only when a method on a different object is called. There is no indication that people rely on its existence.

Add comment to LogRecord.message

---

stdlib/typing.pyi

Widen MutableMapping.update type

---

stdlib/argparse.pyi

Remove duplicate type from `ArgumentParser.add_argument`

---

stdlib/_markupbase.pyi

As this is an abstract method, NoReturn is problematic as deriving
classes (for example in beautifulsoup4 or fpdf2) have an incompatible
return type.

Fix return type of ParserBase.error

---

stubs/psutil/psutil/_common.pyi

here's some example output:
```python
import psutil
for conn in psutil.net_connections():
print(conn.raddr, type(conn.raddr))
```
```console
$ python3 t.py 
() <class 'tuple'>
addr(ip='192.168.1.254', port=67) <class 'psutil._common.addr'>
() <class 'tuple'>
() <class 'tuple'>
```

fix typing for psutil sconn

---

stdlib/webbrowser.pyi

I've removed all duplicate fields, now it relies on inheritance.
I've also added a comment about this problem: https://bugs.python.org/msg409087
Source: https://github.com/python/cpython/blame/main/Lib/webbrowser.py#L668-L670

Simplify `webbrowser.pyi` definition

---

stdlib/tkinter/__init__.pyi
stdlib/tkinter/ttk.pyi

Nobody reads long comments, and I hadn't fully internalized that yet when I rewrote the tkinter stubs.

shorten tkinter's comments

---

stubs/python-dateutil/dateutil/parser/__init__.pyi

Fixes #6682.
As mentioned in the issue the `MONTHS` attribute on `parserinfo` can have three variations on the name. Likewise `WEEKDAYS` has TODO comments indicating that additional variations will be added in the future.
Updated both to `list[tuple[str, ...]]`

python-datetutil: update WEEKDAYS and MONTHS attributes

---

pyrightconfig.stricter.json
stubs/mock/@tests/stubtest_allowlist.txt
stubs/mock/mock/mock.pyi

Removed a few "Any" annotations that could be typed. (There are more.) Add
package to pyrightconfig.stricter.json ignore list.
Also removed a few unused private classes and methods. They can be re-added
if a user reports them missing.

Fix stubtest for third-party mock package

---

.flake8

* Improve documentation on why which attributes are ignores.
* Add links to issues where appropriate.
* Ignore E501 (handled by black) in script files and remove max-line-length.
* Limit Python 2 builtins to those actually used.
* Don't ignore W503, which was removed from the list of default rules.

Update flake8 config

---

stdlib/stat.pyi

`S_IF*` constants have platform-specific values. For example, `S_IFDOOR` is zero on everything except Solaris (source code https://github.com/reingart/cpython/blob/3229d9d7167b6e71078ad2ac9bf8fed50ddce9aa/Modules/_stat.c#L70-L72 ), and because `sys.platform` checks currently only work with win32, linux and darwin, we can't check for that and use a `Literal`.

Fix CI failure

---

.github/workflows/stubtest.yml
.github/workflows/tests.yml
tests/get_apt_packages.py
tests/stubtest_third_party.py

Having a script do `sudo apt -y install foo` felt weird to me, even with a command-line option named `--sudo-install-apt`. This PR introduces a separate script that prints the names of packages to install instead. The scripts no longer need root privileges.

stubtest_third_party: do not install apt packages in the same script

---

stdlib/bz2.pyi

This is consistent with the provided options for `gzip.open` and `lzma.open`. Gzip and lzma both provide the `Literal['rb']` etc. mode options as well as an overload that accepts `str` for mode. `bz2.open` does not have this. This PR makes the code consistent by also adding such an overload to the `bz2.open` method.

Add a generic overload for bz2.open as exists in gzip.open and lzma.open

---

tests/check_new_syntax.py

Relax check_new_syntax.py to allow elif statements for old versions

---

stdlib/winreg.pyi

Things that I left out of scope:
1. Undocumented values
2. `HKEY_*` values that are really big (not sure that they are constants at all)
```python
HKEY_CLASSES_ROOT: Literal[18446744071562067968]
HKEY_CURRENT_CONFIG: Literal[18446744071562067973]
HKEY_CURRENT_USER: Literal[18446744071562067969]
HKEY_DYN_DATA: Literal[18446744071562067974]
HKEY_LOCAL_MACHINE: Literal[18446744071562067970]
HKEY_PERFORMANCE_DATA: Literal[18446744071562067972]
HKEY_USERS: Literal[18446744071562067971]
```

Use `Literal` types in `winreg`

---

stdlib/inspect.pyi

Source: https://github.com/python/cpython/blob/82c2b54a35f85d87639201d1431ae6584b079e13/Lib/inspect.py#L2677-L2691

`name`, `default`, `kind`, and `annotation` in `Parameter` are read-only

---

stdlib/inspect.pyi

Sorry, I've messed something up in https://github.com/python/typeshed/pull/6765/files and `int` was restored
Refs https://github.com/python/typeshed/pull/6764

Once again, set `CO_*` flags as `Literal` types

---

stdlib/typing.pyi

Another tweak to `re` that I spotted when working through the `regex` stubs.
`re.Match.lastgroup` is derived from `indexgroup` (inverse of `groupindex`) and therefore must be a str:
https://github.com/python/cpython/blob/0b58bac3e7877d722bdbd3c38913dba2cb212f13/Modules/_sre.c#L2375-L2388
Group names are always stored as strings, even if the pattern and string are bytes:
```
>>> import re
>>> re.compile(b"(?P<letter>\w)").match(b"a1").lastgroup
'letter'
```

re.Match.lastgroup is str rather than AnyStr

---

stdlib/asyncio/tasks.pyi

Basically, these are redefinitions of `concurrent` values:
```python
FIRST_COMPLETED = concurrent.futures.FIRST_COMPLETED
FIRST_EXCEPTION = concurrent.futures.FIRST_EXCEPTION
ALL_COMPLETED = concurrent.futures.ALL_COMPLETED
```
Refs https://github.com/python/typeshed/pull/6780

Use `Literal` type for constans in `asyncio/tasks`

---

stdlib/@python2/types.pyi
stdlib/types.pyi

In very rare (error?) cases, f_lineno can actually be None.

fix(stdlib/types): FrameType.f_lineno can be None

---

stdlib/sys.pyi

You can't actually instantiate this one at runtime, but that's a little difficult to express in the type system.

`sys._version_info` is a `structseq` class

---

requirements-tests.txt

Noticed that pytype doesn't support python 3.10 yet

Add python310 marker to test requirements for pytype

---

stdlib/multiprocessing/pool.pyi

Source: https://github.com/python/cpython/blob/f4c03484da59049eb62a9bf7777b963e2267d187/Lib/multiprocessing/pool.py

Use `Literal` type in `multiprocessing/pool` and add `__all__`

---

stdlib/builtins.pyi

`builtins.function` is a mypy-specific hack, and removing it breaks mypy. Rewrite comments to make this clear.

Improve comments of builtins.function

---

stdlib/calendar.pyi

Note that constants are now documented https://docs.python.org/3/library/calendar.html#calendar.setfirstweekday

Use `Literal` types in `calendar`

---

stdlib/_ast.pyi

Again, `_ast` constants are re-exported in `ast`

Use `Literal` types in `ast`

---

stdlib/_csv.pyi

These constants are re-exported in `csv.pyi`, so it is fine! 👍

Use `Literal` types in `csv`

---

stdlib/_typeshed/__init__.pyi

As discussed in https://github.com/python/typeshed/pull/6816, for some `structseq` classes these attributes are writeable `ClassVar`s, but for other classes, they're read-only `ClassVar`s. Either way, however, it's probably a bad idea to be modifying these attributes, so it makes sense to simply annotate them with `Final` rather than `ClassVar`.
Note that [PEP 591](https://www.python.org/dev/peps/pep-0591/) specifically states:
> Type checkers should infer a final attribute that is initialized in a class body as being a class variable. Variables should not be annotated with both ClassVar and Final.
As such, annotating these attributes as `Final[ClassVar[int]]` would be neither necessary nor possible.

`_typeshed.structseq`: Use `Final` instead of `ClassVar`

---

stdlib/bz2.pyi
stdlib/imp.pyi
stdlib/multiprocessing/pool.pyi
stdlib/socketserver.pyi
stdlib/types.pyi
stdlib/weakref.pyi
stubs/redis/redis/client.pyi
tests/check_new_syntax.py

These were found by applying the following diff to `check_new_syntax.py`:
```diff
--- a/tests/check_new_syntax.py
+++ b/tests/check_new_syntax.py
@@ -2,6 +2,7 @@
import ast
import sys
+from collections import defaultdict
from itertools import chain
from pathlib import Path
@@ -152,6 +153,30 @@ def check_new_syntax(tree: ast.AST, path: Path) -> list[str]:
)
self.generic_visit(node)
+    if "_typeshed" not in path.parts:
+        typevar_defs: dict[str, int] = {}  # Mapping of TypeVar names to the linenos where they're defined
+        all_name_occurences: defaultdict[str, int] = defaultdict(int)  # Mapping of each name in the file to the no. of occurences
+
+        class UnusedTypeVarFinder(ast.NodeVisitor):
+            def visit_Assign(self, node: ast.Assign) -> None:
+ …
```

Remove several unused `TypeVar`s

---

stdlib/builtins.pyi
stdlib/collections/__init__.pyi
stdlib/os/__init__.pyi

Found by running `codespell stdlib/ stubs/ *.md`, installed with `pip install codespell==2.1.0`.
It would be possible to add codespell to our CI, but it doesn't seem like a good idea to me:
- It flags several false positives.
- stubtest already ensures that most things are spelled correctly.
- Outside comments, the only typo I have seen is misspelling `suite_mask` as `suite_mast`, fixed in #6816. It was in code that isn't very stubtest-friendly. But codespell doesn't flag it either, because `mast` is also a valid word.

fix several typos

---

stdlib/asyncio/tasks.pyi

Since these names do not exist in runtime, we need to hide these names

`asyncio.gather` should use pos-only arguments

---

stdlib/concurrent/futures/_base.pyi

Local test:
Sample:
```python
from concurrent.futures import ThreadPoolExecutor
def test(a, b):
return a + b
with ThreadPoolExecutor() as e:
future = e.submit(test, 3, b=4)
print(future.result())  # prints `7`
```
Docs: https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.Executor.submit

Use `ParamSpec` for `concurent.futures.Executor.submit`

---

stdlib/urllib/parse.pyi

This is causing ParseResultBytes.geturl() to be labelled with the return type str when it returns bytes by pyright.

Fix bytes mixin labled as str in urllib.parse.pyi stub

---

stdlib/fcntl.pyi
tests/stubtest_allowlists/darwin.txt
tests/stubtest_allowlists/linux.txt

Not all constants in `fcntl` are available on macos

---

stdlib/shutil.pyi

Closes #6831. Thorough example included in the issue.
TLDR: `shutil.move` can take bytes arguments

Adjust shutil.move stubs to allow bytes/Pathlike[bytes] args

---

scripts/create_baseline_stubs.py

With mypy 0.930, `python3 -m mypy.stubgen` no longer works, but `stubgen` does work:
```
(env) akuli@akuli-desktop:~/typeshed$ mypy --version
mypy 0.930
(env) akuli@akuli-desktop:~/typeshed$ python3 -m mypy.stubgen -p requests
/home/akuli/typeshed/env/bin/python3: No code object available for mypy.stubgen
(env) akuli@akuli-desktop:~/typeshed$ stubgen -p requests
Processed 18 modules
Generated files under out/requests/
```

scripts/create_baseline_stubs.py: Fix invoking stubgen

---

stdlib/_socket.pyi
stdlib/socket.pyi

Hello!
In Python 3.10 a new option to create MPTCP sockets has been added (https://bugs.python.org/issue43571).
This simple PR adds that missing option.

Add IPPROTO_MPTCP option

---

stdlib/@python2/__builtin__.pyi
stdlib/@python2/builtins.pyi
stdlib/builtins.pyi

I invite everyone to discuss this problem 🙂 
Technically, `object` does not have `__slots__` defined:
```python
>>> object.__slots__
AttributeError: type object 'object' has no attribute '__slots__'. Did you mean: '__class__'?
>>> object().__slots__
AttributeError: 'object' object has no attribute '__slots__'. Did you mean: '__class__'?
```
And its subclasses do not have `__slots__`:
```python
>>> class Bar(object):
...     ...
... 
>>> Bar.__slots__
AttributeError: type object 'Bar' has no attribute '__slots__'. Did you mean: '__class__'?
>>> Bar().__slots__
Traceback (most …
```

Remove `__slots__` from `builtins.object`

---

stubs/redis/redis/client.pyi
stubs/redis/redis/commands/core.pyi

* The ``score_cast_func`` parameter accepted by various ZSET methods is a method which will be passed a str or bytes parameter, rather than a float (the default value of the parameter is the float class constructor)
* ``scan_iter`` and related methods take a ``match`` parameter which was declared as str, but can actually be either bytes or str (the ``_Key`` type)
* Added return type annotations for ``sscan_iter``, ``hscan_iter``, ``zscan`` and ``zscan_iter`` which were missing

Improved type hints for redis scan and zset methods

---

stubs/redis/redis/client.pyi

#6829 removed it as unused but #6790 added a usage.

put redis.client._ScoreCastFuncReturn back

---

stdlib/_py_abc.pyi

Looks like it is supported by pytype now: https://github.com/google/pytype/issues/597

Change `get_cache_token` to return a `NewType` in `_py_abc`

---

stubs/requests/@tests/stubtest_allowlist.txt

It's causing stubtest to fail, e.g. https://github.com/python/typeshed/runs/4755528470?check_suite_focus=true

Remove unused `requests` allowlist entry

---

stdlib/builtins.pyi

Thay are also valid as regular calls:
```python
def func(arg: int) -> int:
return arg
class Some(object):
x = staticmethod(func)
y = classmethod(func)
```

Remove misleading comment from `staticmethod` and `classmethod`

---

stubs/urllib3/urllib3/util/retry.pyi

This is explicitly documented at https://github.com/urllib3/urllib3/blob/1.26.8/src/urllib3/util/retry.py#L179. See https://github.com/python/typeshed/commit/6907d7f7c6c2aca7d1653e524ac4f690d47feb1b#r63815945.

urllib3: allow allowed_methods to be False

---

stdlib/types.pyi

Use `int | Any` for `types.FrameType.f_lineno`

---

stdlib/typing.pyi

Arguments like bound= accept type forms like unions, which are not themselves types.

fix TypeVar argument annotations

---

stdlib/opcode.pyi

We are going to use `__all__` here: https://github.com/python/typeshed/blob/master/stdlib/dis.pyi#L3-L18
Because in real life `dis` re-exports all `opcode` public defs:
```python
from opcode import *
from opcode import __all__ as _opcodes_all
from opcode import _nb_ops
__all__ = ["code_info", "dis", "disassemble", "distb", "disco",
"findlinestarts", "findlabels", "show_code",
"get_instructions", "Instruction", "Bytecode"] + _opcodes_all
del _opcodes_all
```

Add `__all__` to `opcode` and use `Literal` for constants

---

stdlib/gc.pyi

Types of `callback` arguments are well-defined: https://docs.python.org/3/library/gc.html#gc.callbacks
Checked that mypy is ok with that:
```python
from typing import Any, Callable, Literal, TypedDict
class _CallbackInfo(TypedDict):
generation: int
collected: int
uncollectable: int
_C  = Callable[[Literal["start" | "stop"], _CallbackInfo], Any]
x: list[_C]
def some(arg: str, other):
pass
x.append(some)
```

Use `Literal` type and improve callbacks in `gc`

---

stubs/redis/@tests/stubtest_allowlist.txt
stubs/redis/METADATA.toml

Reverts python/typeshed#6952
This is causing all uploads to fail (#6956). As a quick fix, let's restore the previous version.

Revert "Temporarily fix redis version to 4.1.0"

---

.github/workflows/stubtest.yml
.github/workflows/tests.yml

I assume that by now all workers should have upgraded to 3.10.1 or even 3.10.2.

Unpin 3.10.1

---

stdlib/contextvars.pyi

```python
>>> import contextvars
>>> class My(contextvars.Context):
...   pass
... 
TypeError: type '_contextvars.Context' is not an acceptable base type
>>> class My(contextvars.Token): ...
... 
TypeError: type '_contextvars.Token' is not an acceptable base type
>>> class My(contextvars.ContextVar): ...
... 
TypeError: type '_contextvars.ContextVar' is not an acceptable base type
```

Make all types in `contexvars` explicitly `@final`

---

.flake8
stdlib/contextlib.pyi

Refs https://github.com/PyCQA/flake8-pyi/pull/104
There are a number of stubs in typeshed that still support Python 2. Each subdirectory of stubs specifies whether or not it supports Python 2 in the `METADATA.toml` file. However, there's no easy way for flake8 to read those files, and I don't particularly like the idea of duplicating that information in the `.flake8` config file. As such, I think it's easiest if we just globally ignore this check for the whole of typeshed. We can still keep the equivalent check in `check_new_syntax.py`, where it's easier to dynamically specific filepaths that we want to check things for.

Add Y027 to list of ignored `.flake8` error codes

---

.github/workflows/stubtest.yml

Fixes #6972 
Example issue: https://github.com/Akuli/typeshed/issues/21
It would be nice to include the name of the failing library in the issue title. This isn't as easy as I expected, because we can't give the `issues: write` permission to the same job that runs stubtest (and executes code from pypi). We could do this with upload-artifact and download-artifact, or by downloading raw logs of the failed jobs. But this is already much better than a script that runs only on my computer, and can be improved later.

Automatically create an issue if the nightly stubtest run fails

---

stdlib/functools.pyi

Do I need to add a line about typing immutable `tuple`s into https://typing.readthedocs.io/en/latest/source/stubs.html ?

Use `tuple` of `Literal` types in `functools.pyi`

---

stdlib/_collections_abc.pyi

Completely orthogonal to the other issues around the dict views classes that have been discussed recently — but something I noticed.

Make `mapping` attribute read-only on dict views classes

---

stubs/Flask-Cors/flask_cors/core.pyi

Refs https://github.com/PyCQA/flake8-pyi/pull/133

Use class-based syntax for `TypedDict` in `Flask-Cors/flask_cors/core.pyi`

---

stdlib/tkinter/ttk.pyi

There's some `>>>` prompt experimentation on https://github.com/PyCQA/flake8-pyi/pull/135. This is inconsistent, because tkinter returns the objects however Tcl happens to represent them internally, and Tcl's internal representations are meant to be a transparent optimization that can be ignored.
I also realized that it's possible to distinguish "no `**kwargs` arguments given" and "at least one keyword argument given" with overloads, and used that to get rid of a union return type.

improve tkinter.Treeview.heading and tkinter.Treeview.item

---

stubs/beautifulsoup4/bs4/__init__.pyi

These are mentioned in https://www.crummy.com/software/BeautifulSoup/bs4/doc/index.html?highlight=soupstrainer as public objects.
See microsoft/pyright#2922.

bs4: Expose bs4.SoupStrainer and bs4.Tag

---

stdlib/email/message.pyi

Use import instead of type alias in `email/message.pyi`

---

stdlib/@python2/curses/__init__.pyi
stdlib/@python2/sqlite3/__init__.pyi
stdlib/@python2/xml/etree/cElementTree.pyi
stdlib/curses/__init__.pyi
stdlib/sqlite3/__init__.pyi
stdlib/tokenize.pyi
stdlib/xml/etree/cElementTree.pyi

Since `F403` is ignored for all `.pyi` files, it is not required to be inline ignored as well.
https://github.com/python/typeshed/blob/0238956f909fca5f60a60f715314974c06ac3918/.flake8#L29

Removed unused `# noqa: F403`

---

stdlib/sunau.pyi

Source: https://github.com/python/cpython/blob/b1a3446f077b7d56b89f55d98dadb8018986a3e5/Lib/sunau.py#L515-L526

Use `@overload` for `sunau.open`

---

stdlib/asyncio/base_events.pyi
stdlib/asyncio/events.pyi

asyncio pipes and subprocess methods return specific transport types (which are documented). Currently it's necessary to use casts to access correct method, this patch makes casts unnecessary.

Use stricter transport types in asyncio subprocess methods

---

stubs/decorator/decorator.pyi

There may be other places in this package where `ParamSpec` could be used, but this one is the most clear-cut.

Add `ParamSpec` to `decorator.contextmanager`

---

stdlib/@python2/unittest.pyi

This brings the signature in line with the signature of `removeHandler` in Python 3:
https://github.com/python/typeshed/blob/a54e21992c26485edb374e1287a7e9c073d6a9ae/stdlib/unittest/signals.pyi#L11-L14

Improve `unittest.removeHandler` in Python 2

---

stdlib/asyncio/base_futures.pyi

Docs https://docs.python.org/3/library/asyncio-future.html#asyncio.isfuture

Make `asyncio.isfuture` a `TypeGuard`

---

scripts/generate_proto_stubs.sh
stubs/protobuf/google/protobuf/any_pb2.pyi
stubs/protobuf/google/protobuf/api_pb2.pyi
stubs/protobuf/google/protobuf/duration_pb2.pyi
stubs/protobuf/google/protobuf/source_context_pb2.pyi
stubs/protobuf/google/protobuf/struct_pb2.pyi
stubs/protobuf/google/protobuf/timestamp_pb2.pyi
stubs/protobuf/google/protobuf/type_pb2.pyi
stubs/protobuf/google/protobuf/wrappers_pb2.pyi

Per the suggestion in https://github.com/dropbox/mypy-protobuf/issues/344
This generates more permissive constructors (which protobuf itself actually
accepts).
Philosophically, I think it makes sense for the generated code hosted on
typeshed to be most permissive, while the generated code of individual
projects can make individual decisions (defaulting to less permissive).

Use relax_strict_optional_primitives on protobuf generated code

---

stdlib/@python2/typing.pyi
stdlib/@python2/typing_extensions.pyi
stdlib/typing.pyi
stdlib/typing_extensions.pyi

One possible solution to the issue raised in https://github.com/python/typeshed/pull/7036#discussion_r791847978.
cc. @JelleZijlstra

Clarify why some module-level objects in `typing` have default values

---

stdlib/shelve.pyi

`shelve.open` passes its args to `dbm.open`, so args must be the same: https://github.com/python/cpython/blob/8fb36494501aad5b0c1d34311c9743c60bb9926c/Lib/shelve.py#L218-L243

Use `dbm._TFlags` in `shelve.open`

---

stdlib/contextlib.pyi

This is used here: https://github.com/python/cpython/blob/8fb36494501aad5b0c1d34311c9743c60bb9926c/Lib/contextlib.py#L576
I found a place in our codebase where we push a function that returns None. That's pretty normal for `__exit__` functions, so I think we should allow it.

Allow ExitStack.push callbacks to return None

---

stdlib/_typeshed/__init__.pyi

It is no longer used anywhere, following #7093

Delete `SupportsAnyComparison` type in `_typeshed`

---

stdlib/pydoc.pyi

Closes #7099. The class has not existed since 2013.

Delete commented-out `pydoc.Scanner` class

---

stdlib/_bisect.pyi

See https://github.com/python/cpython/pull/20556/files#r432997024 for reference.

bisect: insort_*, unlike bisect_*, expects x to match type of elements of a

---

stubs/ldap3/ldap3/core/connection.pyi

The ldap3 package Connection class supports additional types in the server parameter. These can be either a ServerPool instance or an iterable containing Server instances.
See the source implementation [here](https://github.com/cannatag/ldap3/blob/dev/ldap3/core/connection.py#L310)

Add iterable and ServerPool types to ldap3 Connection.server parameter 

---

stubs/google-cloud-ndb/google/cloud/ndb/model.pyi

The types for these class methods were mixed up. The async method
returned an optional `Model`, while the synchronous method returned a
`Future`. It should be the other way around.
Fixes #7103

Fix mistyped `get_by_id` class methods

---

stdlib/typing_extensions.pyi

Changed typing_extensions.pyi to declare its own private version of `Protocol` rather than re-exporting the symbol imported from `typing`. This allows pyright to warn users about runtime exceptions when they attempt to use typing.Protocol on versions of Python prior to 3.7.

Changed typing_extensions.pyi to declare its own private version of `Protocol`

---

stdlib/dataclasses.pyi

The goal of this change is to fix the behavior of `dataclasses.Field`. Several attributes of a `Field` may have a value of `MISSING` (a sentinel value). As a result, attributes of Field may be checked against `MISSING` as in
[f for f in fields(obj) if f.default is MISSING]
`default`, `default_factory`, and `kw_only` are the attributes which may have a value of `MISSING`.
This workaround of defining `_MISSING_TYPE` as an enum, and `MISSING` as its only member, allows `... | Literal[MISSING]` to be used in type annotations for these attributes. This is very slightly inaccurate -- primarily in that `_MISSING_TYPE` isn't really an enum -- but this allows for use in `Literal`. After PEP 661 (Sentinel Values), there may be a more accurate way of writing this, but for now this works.
This …

Use enum trick for dataclasses.MISSING

---

stdlib/@python2/copy_reg.pyi
stdlib/@python2/copyreg.pyi
stdlib/copyreg.pyi

Refs https://github.com/PyCQA/flake8-pyi/pull/176

Add `__all__` to `copyreg` stubs

---

stdlib/queue.pyi

It is `deque` in `Queue` and `list` in `LifoQueue` and `PriorityQueue`
Source: 
- https://github.com/python/cpython/blob/3a5afc14e16370c1f4f72d43cb553298ad9a1fa4/Lib/queue.py#L207
- https://github.com/python/cpython/blob/3a5afc14e16370c1f4f72d43cb553298ad9a1fa4/Lib/queue.py#L230
- https://github.com/python/cpython/blob/3a5afc14e16370c1f4f72d43cb553298ad9a1fa4/Lib/queue.py#L246
Refs https://github.com/python/typeshed/issues/3472
Refs https://github.com/python/typeshed/pull/3879

`queue.Queue.queue` is a `MutableSequence`

---

stubs/paramiko/paramiko/client.pyi
stubs/paramiko/paramiko/transport.pyi

Fixes #6983.
Note: I also updated the typing of `paramiko.transport.Transport`, as that made sense to me after taking a look at the source code of `paramiko.client.SSHClient` - see [these](https://github.com/paramiko/paramiko/blob/88f35a537428e430f7f26eee8026715e357b55d6/paramiko/client.py#L370-L371) and [these](https://github.com/paramiko/paramiko/blob/88f35a537428e430f7f26eee8026715e357b55d6/paramiko/transport.py#L371-L372) lines).

Improve `sock` typing in Paramiko stub

---

stubs/google-cloud-ndb/google/cloud/ndb/model.pyi

This function was mistakenly typed as `Callable[[Property], object] |
None`, however the actual function accepts two parameters of type
`Property, value`. The value can be of any type. Strictly speaking, the
type corresponds to the type of the property which is defined at runtime.
Relates to #7103

Fix incorrect type definition for `validator`

---

stdlib/builtins.pyi

It is typed as `int` instead of `Any` after this PR.
Followup to https://github.com/python/typeshed/pull/6325#discussion_r797710621

Fix zero exponent for `int`s

---

stdlib/enum.pyi

Most Python objects evaluate as falsey if they have length 0, but an enum class is truthy even if it has length 0.
Source code: https://github.com/python/cpython/blob/841c77d802e9ee8845fa3152700474021efe03fd/Lib/enum.py#L353

Add `EnumMeta.__bool__`

---

stdlib/urllib/request.pyi

Fixes #7208
This is what urllib.request claims to support over here:
https://github.com/python/cpython/blob/ad4e8d2b871c4f5bce27520627bbb2e0e544bc24/Lib/urllib/request.py#L1276
There is additional validation logic (e.g. strs don't work), but a lot
of what determines what works is over here:
https://github.com/python/cpython/blob/ad4e8d2b871c4f5bce27520627bbb2e0e544bc24/Lib/http/client.py#L1039

urllib.request: loosen data type

---

stubs/babel/@tests/stubtest_allowlist.txt
stubs/requests/@tests/stubtest_allowlist.txt

Fixes #7232
All stubtest failures caused here were caused by https://github.com/python/typeshed/pull/7228, which corrected several positional-only errors in the stub for `collections.OrderedDict`.

Remove unused allowlist entries in `babel` and `requests`

---

tests/mypy_test.py

This can possibly catch if we apply `(*Any, **Any) -> Any` to some existing typed function.
Right now, we don't do that anywhere in the code base 🙂

Add `--disallow-untyped-decorators` to `mypy_test`

---

stubs/beautifulsoup4/bs4/element.pyi

I keep getting errors like: `"Mapping[str, str]" has no attribute "__delitem__"; maybe "__getitem__"?`
Real type is a python `dict`.
```py
>>> type(item.attrs)
<class 'dict'>
```
So I need to add `isinstance(tag.attrs, dict)` to force the type (maybe there is a better way? I haven't written python mypy in about 8 months)
For example, without `and isinstance(tag.attrs, dict)` this would result in the above error:
```py
if 'style' in tag.attrs and isinstance(tag.attrs, dict):
del tag.attrs['style']
```

Tag.attrs are Mutable

---

stdlib/nntplib.pyi

It was always a protected name, but it was removed from CPython 2 years ago.
See https://github.com/python/cpython/blob/2945f5a7c51200bfc5c493ccb626fc414e1385b1/Lib/nntplib.py#L490

Remove `_NNTPBase` from `nntplib`

---

stdlib/asyncio/runners.pyi

Add `asyncio.runners.__all__`

---

scripts/create_baseline_stubs.py

In current version, the `create_baseline_stubs.py` script defaults to the project name as the package name. This is not always the best choice (e.g. `PyYAML` and `yaml`), and the `--package` can be used in that case.
In this PR, I'm improving the default package detection when there is no `--package` flag. Because this script is run manually, I feel like it is ok to display a message saying to use `--package` flag if the detected package is not the wanted one.
I checked with the following projects:
- `redis` defaults to `redis`
- `python-nmap` defaults to `nmap`
- `PyYAML` defaults to `yaml` (note that `PyYAML` also exports a `_yaml` module)
The improvement relies on `importlib.metadata` module, and fallbacks to current default (i.e. project name) if that fails or for Python < 3.8 (where …

create_baseline_stubs: improve package detection

---

stubs/Flask-Cors/@tests/stubtest_allowlist.txt

Helps with https://github.com/python/typeshed/issues/7307

flask-cors: remove unused allowlist

---

stdlib/enum.pyi

I don't really understand why this needs the `# type: ignore`s, but mypy seems absolutely convinced that this method breaks LSP!

Add `EnumMeta.__prepare__`

---

stdlib/argparse.pyi
tests/stubtest_allowlists/py3_common.txt

As has previously been discussed in https://github.com/python/typeshed/pull/6826#issuecomment-1005654071 the `argparse` module sometimes compares `argparse.SUPPRESS` with `is` meaning `Literal["==SUPPRESS=="]` is not suited. This PR solves this using `NewType`.
As reported by [mypy_primer](https://github.com/hauntsaninja/mypy_primer) the following fails with mypy:
```python
import argparse
x = argparse.SUPPRESS
x = "test"
```
because of:
```
foo.py:4: error: Incompatible types in assignment (expression has type "str", variable has type "_SUPPRESS_T")
```
This however seems to be due to a limitation in mypy not understanding that a newtype is backwards compatible with the original type as can be observed in the following example:
```python
import typing
X = typing.NewType('X', int)
def …
```

argparse: Use Literal for action & nargs add_argument parameter types

---

.flake8

Unblocks https://github.com/PyCQA/flake8-pyi/pull/186

Add Y034 to list of ignored flake8 error codes for `typing.pyi`

---

stdlib/unittest/runner.pyi

`showall` -> `showAll` - it has always been camel-cased and didn't change - [python 2.7 source](https://github.com/python/cpython/blob/2.7/Lib/unittest/runner.py) , [main](https://github.com/python/cpython/blob/main/Lib/unittest/runner.py)

Fix unittest.TextTestResult showAll name

---

stdlib/unittest/runner.pyi

This function is passed either `self.errors` or `self.failures` which are defined as `list`s of such tuples: https://github.com/python/typeshed/blob/4d169eaa83bfde68e0abc55670b73c1f0f408043/stdlib/unittest/result.pyi#L16-L17
This can be seen from [Python 2.7 source](https://github.com/python/cpython/blob/2.7/Lib/unittest/runner.py#L105) and up.
(Sorry for not merging in #7340 - I was still untangling some type check errors 😅)

Fix unittest.TextTestResult.printErrorList()

---

stdlib/builtins.pyi
stdlib/re.pyi

Add comments about mypy limitation regarding TypeVar constraints

---

CONTRIBUTING.md
stubs/SQLAlchemy/METADATA.toml
tests/check_consistent.py
tests/stubtest_third_party.py

Some distributions can't be tested with stubtest for a variety of
reasons or because of bugs in stubtest. This key:
* let's us keep metadata about a distribution in one place,
* prevents us from modifying the scripts because of issues with a
specific distribution, and
* will trigger tests if only the key is changed.

Re-introduce the 'stubtest' key for third-party packages

---

stdlib/logging/__init__.pyi

See #7258 for an extended discussion. In summary, for mypy these
would be better written as follows, but this would not work with
every type checker:
```
CRITICAL: Final = 50
```

Replace some literal types in logging with int

---

stdlib/asyncio/base_futures.pyi
stdlib/asyncio/futures.pyi

`asyncio.base_futures.isfuture()` has a correct typeguard signature already but it was hidden by `asyncio.futures.isfuture()` redefinition.
Now `asyncio.futures.isfuture` is an alias to `asyncio.base_futures.isfuture()`. The same structure is used in original asyncio source.

Sync asyncio.isfuture definitions by sharing asyncio.base_futures.isfuture definition

---

stdlib/_csv.pyi
stdlib/csv.pyi
tests/stubtest_allowlists/py3_common.txt

We previously discussed this in #6398, and decided not to include it in the stub. However, it is declared as a publicly exported object in the module's `__all__` at runtime, so not including it in the stub creates an inconsistency in the stub's `__all__` (see https://github.com/python/typeshed/pull/7356). Moreover, there doesn't really seem to be any harm in adding it to the stub. So, I think we should add it.

Add `csv.__version__`

---

stdlib/re.pyi

- Add `NO_FLAG`, new in 3.11
- Delete very old comment
- Several members in `RegexFlag` are aliases of other members; the stub should reflect that

Improve `re` stubs

---

stubs/stripe/@tests/stubtest_allowlist.txt
stubs/stripe/stripe/api_resources/abstract/deletable_api_resource.pyi

Fixes stripe/stripe-python#770
`stripe`'s `DeletableAPIResource.delete` [instance method](https://github.com/stripe/stripe-python/blob/cf794375df6e1d1adaef5ff5d12b9bcb31a845c0/stripe/api_resources/abstract/deletable_api_resource.py#L14) has a [wrapper](https://github.com/stripe/stripe-python/blob/cf794375df6e1d1adaef5ff5d12b9bcb31a845c0/stripe/util.py#L213) that effectively overloads the method to add a class method version.
Both
```python
s = stripe.Subscription.create(...)
s.delete()
```
and
```python
s = stripe.Subscription.create(...)
stripe.Subscription.delete(s.id)
```
should work, but the latter raises a type error.

Add overload annotation for stripe DeletableAPIResource delete classmethod

---

stdlib/asyncio/base_events.pyi
stdlib/builtins.pyi
stdlib/enum.pyi

If you apply @hauntsaninja's patch to `mypy_test.py` in https://github.com/python/mypy/issues/12220, here is the output when running `python tests/mypy_test.py -p3.11` on the master branch (using Python 3.10, mypy 0.931):
```
stdlib\typing.pyi:1166: error: Variable "typing.Never" is not valid as a type  [valid-type]
stdlib\typing.pyi:1166: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases
stdlib\builtins.pyi:1713: error: Value of type "Type[type]" is not indexable  [index]
stdlib\builtins.pyi:1721: error: Variable "builtins._SplitCondition" is not valid as a type  [valid-type]
stdlib\builtins.pyi:1721: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases
stdlib\builtins.pyi:1722: error: Variable …
```

Fix several mypy errors when run on the 3.11 stdlib

---

stdlib/asyncio/__init__.pyi
stdlib/asyncio/taskgroups.pyi
stdlib/asyncio/unix_events.pyi

Now that all `asyncio` submodules have accurate `__all__`s, we can drastically simplify the imports in `asyncio.__init__.pyi` and do something much more similar to what's done at runtime.

Add `__all__` for `asyncio.unix_events` & `asyncio.taskgroups`, and simplify `asyncio.__init__`

---

stdlib/builtins.pyi
stdlib/types.pyi
tests/stubtest_allowlists/py3_common.txt

- Add `types.FunctionType.__builtins__` (and `types.LambdaType.__builtins__`), currently missing from the stub.
- Make many fields on many classes read-only, as they are at runtime.
- All parameters in `types.MethodType.__init__` are positional-only.

Improve `types.pyi`

---

stubs/urllib3/urllib3/util/ssl_.pyi

This constant is missing from type stubs but present in the source.
Importing it works, and it's used in various different places.

Add missing constant from urllib3.util.ssl_

---

stdlib/typing.pyi

These look somewhat like implementation details, but no more so than any of the other dunder attributes that are already on the class.

Add two missing `ForwardRef` attributes

---

stubs/beautifulsoup4/bs4/__init__.pyi

This is generally useful. It's also imported in the source without being
used in bs4/__init__.py which in well maintained packages is a pretty
good marker of intention to export

bs4: expose bs4.PageElement

---

CONTRIBUTING.md

"At least 6-12 months" is equivalent to "at least six months" and we
usually remove after six month, unless there are issues.

6-12 months -> six months

---

stdlib/copyreg.pyi

The callback passed to `pickle_function` should accept an instance of a to-be pickled object; not the respective type object itself.

Fix the `pickle_function` parameter from `copyreg.pickle`

---

stdlib/asyncio/windows_utils.pyi
tests/stubtest_allowlists/win32.txt

As requested in #7356, cc @AlexWaygood.﻿

Add asyncio.windows_utils.Popen

---

.github/workflows/daily.yml
.github/workflows/tests.yml
tests/stubtest_third_party.py

Related: #7445 
I noticed that the URLs in auto-generated issues (e.g. #7444) were wrong, and `git grep` showed a few other places  too.

Finish renaming stubtest.yml to daily.yml

---

stubs/setuptools/setuptools/__init__.pyi

Alternative to https://github.com/python/typeshed/pull/7418.
As pointed out in abovementioned PR, classes that one might pass to the `cmdclass` parameters (such as the setuptools `build_ext` class) are not guaranteed to inherit from `setuptools.Command`, resulting in type check errors when one attempts to do so. This PR fixes the relevant false positives by relaxing value-type from `setuptools.Command` to the `distutils.core.Command` superclass.
``` python
from setuptools import setup, Extension
from setuptools.command.build_ext import build_ext
class build_test_ext(build_ext):
def build_extension(self, ext: Extension) -> None: ...
setup(
cmdclass={"build_ext": build_test_ext},
)
```

Widen the `cmdclass` parameter of `setuptools.setup`

---

stdlib/mmap.pyi

It returns `Self` at runtime, not `mmap.mmap`, so inheriting from `AbstractContextManager` doesn't really do anything for us.

Improve `mmap.mmap.__enter__`

---

stdlib/ssl.pyi

See #7459 and https://docs.python.org/3/library/ssl.html#ssl.SSLContext.sslsocket_class
This change will mark `SSLContext.sslobject_class` and `SSLContext.sslsocket_class` as Instance-Variable, which is correct according to its documentation.
Fixes #7459

ssl: mark ssl{object,socket}_class as Instance-Var

---

stubs/urllib3/METADATA.toml

They use http.client, which is Python 3-only. Another catch from #7478.

urllib3: stubs are not Python 2 compatible

---

stubs/parsimonious/parsimonious/nodes.pyi

It has to be imported from `typing` in <3.7. Refs https://github.com/python/typeshed/pull/7478.

`parsimonious`: `re.Match` does not exist in Python 3.6

---

stubs/requests/METADATA.toml

See https://github.com/python/typeshed/pull/7478#issuecomment-1066083307: `types-requests` imports `types-urllib3`, and `types-urllib3` is incompatible with Python 2.

`requests` stubs are not Python 2-compatible

---

.github/workflows/tests.yml
tests/mypy_test.py

- Run mypy on the 3.11 stdlib in CI, as a regression test for https://github.com/python/mypy/issues/12220
- Correct the docstring at the top of the file following the changes made in https://github.com/python/typeshed/pull/7478
- Stop the test from crashing when run locally if there's an extra file/folder in the `stubs` directory. (I had a few `.mypy_cache` folders and extra codemodding scripts in various places, which meant that the test was crashing. The `dist_path / "METADATA.toml"` call in the `is_supported` function was evaluating to a nonexistent filepath.)

Further improve `mypy_test.py`

---

stubs/jsonschema/jsonschema/validators.pyi

`RefResolver.referrer` is a `dict[str, Any]`
resolves #7398

Minor stub fix for jsonschema RefResolver

---

.github/workflows/tests.yml
stubs/SQLAlchemy/sqlalchemy/dialects/mssql/pyodbc.pyi
stubs/SQLAlchemy/sqlalchemy/dialects/mysql/pyodbc.pyi
stubs/SQLAlchemy/sqlalchemy/dialects/postgresql/hstore.pyi
stubs/SQLAlchemy/sqlalchemy/sql/sqltypes.pyi
tests/pyright_test.py

Use pyright 1.1.230 in CI, temporarily pin pyright-action to 1.0.4

---

pyrightconfig.json
pyrightconfig.stricter.json
stubs/SQLAlchemy/sqlalchemy/dialects/mssql/pyodbc.pyi
stubs/SQLAlchemy/sqlalchemy/dialects/mysql/pyodbc.pyi
stubs/SQLAlchemy/sqlalchemy/dialects/postgresql/hstore.pyi
stubs/SQLAlchemy/sqlalchemy/sql/sqltypes.pyi

These overrides are inherited from the implementation and are out of
typeshed's control.

pyright: Don't report incompatible overrides

---

stdlib/typing.pyi

python/cpython#31021 and python/cpython#30843.

Add typing.TypeVarTuple, Unpack, assert_type

---

stdlib/@python2/pkgutil.pyi
stdlib/pkgutil.pyi

Partial fix for #6650
According to the Python docs `pkgutil.extend_path` returns either a modified list if a list is passed or the path unchanged.
https://docs.python.org/3.10/library/pkgutil.html#pkgutil.extend_path
[cpython/pkgutil.py -> extend_path](https://github.com/python/cpython/blob/8714b6fa27271035dd6dd3514e283f92d669321d/Lib/pkgutil.py#L539-L542)

Use TypeVar for `pkgutil.extend_path`

---

stdlib/asyncio/base_events.pyi
stdlib/asyncio/events.pyi

The types should match `socket.getaddrinfo()`.

Fixed type of the "host" parameter in asyncio getaddrinfo()

---

stubs/invoke/invoke/tasks.pyi

The decorator can be called with and without (). The current types only consider the first case

Fix invoke task decorator

---

stdlib/socket.pyi

As pointed out by @srittau in #7517, `bytearray` [is redundant](https://docs.python.org/3/library/typing.html#typing.ByteString) in a union where `bytes` is also in the union.

Improve `host` parameter of `socket.getaddrinfo()`

---

.github/workflows/mypy_primer_comment.yml

When changes are really disruptive, like #7430, we truncate output.
Mention this, so that it's known that the change is even more disruptive
than it might appear.

mypy_primer: mention if output is truncated

---

stdlib/email/message.pyi

Let's see if this is fixed in mypy 0.942.
This reverts the changes made in #7022, which was a hack to fix #7019

Revert "Use import instead of type alias in `email/message.pyi`"

---

stdlib/asyncio/streams.pyi

From the asyncio [documentation](https://docs.python.org/3/library/asyncio-stream.html#asyncio.start_server), the start_server function passes the host argument directly through to the underlying `create_server()` function. Since 3.5.1, the `create_server()` function accepts a `Sequence[str]` for the host, this should be mirrored in the `start_server()` function as-well.

allow `asyncio.start_server()` to accept a Sequence of hosts

---

tests/mypy_test.py

- `--enable-error-code ignore-without-code` means that mypy will ignore any `type: ignore` comments that don't have mypy error codes. It doesn't appear to have any effect on `type: ignore` comments that `mypy_test` doesn't use (e.g. because they're pyright- or stubtest-specific).
- `--strict-equality` means that mypy will raise errors if we do something silly like `if sys.version_info == "linux"`. flake8-pyi should also check this for us, but I don't see any reason not to have mypy check this as well.

`mypy_test`: Add two more config options

---

stdlib/unittest/mock.pyi

The signatures of `_patcher.__call__` and `_patcher.object` are identical in Python 3.7 and Python 3.8, except for the return type of the second overload in both functions.

Use type alias to simplify overloads in `unittest.mock`

---

stdlib/logging/handlers.pyi

It is marked as having type `datetime.datetime` but `atTime`
refers to a time of day; only the fields on `datetime.time`
are used. The [docs](https://docs.python.org/3/library/logging.handlers.html#timedrotatingfilehandler)
clearly state that it is a `time`.
One unfortunate problem is that `datetime.datetime` only inherits
from `datetime.date`, not `datetime.time` even though it exposes
the same API as `datetime.time`.
As a result, even though it is possible to pass a `datetime.datetime`
due to duck-typing, this change will causes code that does so to
not type check.
We could use a union type to allow passing either, or even create
a protocol for a "time-like interface". I'll leave that up to reviewers.

logging/handlers.pyi: atTime is datetime.time

---

.flake8

We should hopefully be getting rid of this entire subdirectory soon anyway (#7367). This will make PRs to flake8-pyi a lot easier.

Exclude the Python-2 stdlib from the flake8 CI check

---

.flake8
stubs/humanfriendly/humanfriendly/compat.pyi

flake8 no longer runs on the Python-2 stdlib in CI

flake8 config: remove line that exists only for Python-2 checking

---

stdlib/types.pyi

This exists on builtins.function but not here.

Add `types.FunctionType.__module__`

---

.pre-commit-config.yaml
requirements-tests.txt

black 22.3.0 contains [a patch](https://github.com/psf/black/pull/2966) by somebody called "Jelle Zijlstra", which should fix the CI failure in #7558

Upgrade `black` version

---

stdlib/_dummy_threading.pyi

This matches the runtime (see #7586)

Make several fields on `_dummy_threading` classes read-only properties

---

stdlib/datetime.pyi

Since Python 3.6, the `replace()` methods support subclasses - the return
type is the subclass being replaced.
Link to Python issue: https://bugs.python.org/issue31222

Use Self return type for the 'replace()' methods in datetime classes

---

stubs/pyvmomi/pyVmomi/vim/option.pyi
stubs/pyvmomi/pyVmomi/vmodl/__init__.pyi
stubs/pyvmomi/pyVmomi/vmodl/query.pyi

- Add generic base class `DynamicData`
- Add missing `key` prop to `OptionValue` 
- Fix `MethodFault` not inheriting from `Exception`
- Fix `RetrieveOptions` default `maxObjects` type and default

Update pyVmomi stubs

---

tests/pytype_test.py

This should fix the pytype_test failure in
https://github.com/python/typeshed/pull/7608.

pytype_test: Don't mix up stdlib and stub packages starting with stdlib.

---

stubs/six/six/moves/configparser.pyi

It got removed as an unintended side effect of #7300.
It's available at runtime:
```
>>> import configparser
>>> configparser.Error
<class 'configparser.Error'>
>>> import six.moves
>>> six.moves.configparser.Error
<class 'configparser.Error'>
```

Add back six.moves.configparser.Error

---

stdlib/argparse.pyi

These were introduced in #7329 and they cause false positives
in code that used to be accepted before. There was a false
positive in https://github.com/pycqa/pylint (encountered in
https://github.com/python/mypy/pull/12321) and I also saw
false positives in an internal codebase.
I suggest not using literal types here, since they can be kind of
awkward to annotate in callers that don't pass a literal string.
Requiring callers to write annotations like
`Literal["?", "*", "+", "...", "A...", "==SUPPRESS=="]` is not
very user friendly.

Drop some literal types from argparse (add_argument)

---

stdlib/linecache.pyi

The mtime in linecache entries can be set to `None` fir files loaded via a `__loader__` (cf: https://github.com/python/cpython/blob/3.10/Lib/linecache.py#L70)

Accept `mtime=None` in `linecache.cache` entries.

---

stdlib/typing_extensions.pyi

Hasn't been released yet but I'd like it to be in the next mypy release.

Add typing_extensions.assert_type

---

stdlib/imaplib.pyi
stubs/requests/requests/sessions.pyi

Use re-exports instead of TypeAliases in several places

---

stdlib/itertools.pyi

Our stub for zip_longest just returned Any for everything. This PR creates a
more precise stub inspired by that for zip(). I had to add additional
overloads to account for the fillvalue parameter.

improve type for zip_longest

---

stdlib/collections/__init__.pyi

For some reason I excluded this in the script I used in #7635. I think I remember the last time I tried refactoring typeshed to use PEP 585 syntax everwhere (#6688), it caused mypy crashes if I imported from `collections.abc` inside `collections/__init__.pyi`. But it doesn't seem to now, anyway :)

Use PEP 585 syntax in `collections`

---

stdlib/builtins.pyi

I appear to have accidentally broken mypy.
When running mypy 0.942 against typeshed master, there are no problems.
But I have just (accidentally) discovered that if you run mypy master with `--custom-typeshed-dir` set to typeshed master, you get this:
```
C:\Users\alexw\coding\typeshed\stdlib\abc.pyi: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.960+dev.9cab2964a186d7e71567a1528fcc956f9eecebac
File "C:\Users\alexw\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
return _run_code(code, main_globals, None,
File …
```

Fix crash when running mypy master against typeshed master

---

stdlib/email/__init__.pyi
stdlib/email/feedparser.pyi
stdlib/email/parser.pyi

- Simplifies the code
- More closely matches the runtime: https://github.com/python/cpython/blob/main/Lib/email/parser.py
- Reduces the risk of issues like #7632 cropping up.

Use re-exports instead of TypeAliases in email.parser

---

tests/pytype_exclude_list.txt

Pytype appears to be able to parse these now.

Remove paramiko stubs from pytype_exclude_list.

---

stdlib/unittest/mock.pyi

See [the CPython source](https://github.com/python/cpython/blob/eaa85cb22fa2d9e7cd31c2eac29a56cd3a8f2f65/Lib/unittest/mock.py#L1754). It calls `_get_target`, and [that](https://github.com/python/cpython/blob/eaa85cb22fa2d9e7cd31c2eac29a56cd3a8f2f65/Lib/unittest/mock.py#L1594) does `target.rsplit('.', 1)`.

unittest.mock: target must be a str

---

stdlib/subprocess.pyi

Debatable whether to include these, but they are now documented: python/cpython#91490

subprocess: Add _USE_VFORK and _USE_POSIX_SPAWN

---

stdlib/socket.pyi

socket: add all_errors param to create_connection

---

stubs/requests/requests/sessions.pyi

Resolves https://github.com/python/typeshed/issues/7720
As noted in the issue, the first argument of the tuple here should be optional.

Fix requests files typealias stub

---

stubs/requests/requests/sessions.pyi

Some people are having issues with this one, see https://github.com/python/typeshed/issues/7724
[Documentation](https://docs.python-requests.org/en/latest/api/) says to pass a "file-like-object". [Implementation](https://github.com/psf/requests/blob/v2.27.1/requests/models.py#L158) allows for `str`, `bytes`, `bytearray` or anything that implements `.read()`. 
Left `bytearray` out for now because urllib3 documents `str` and `bytes` as valid in [RequestField](https://urllib3.readthedocs.io/en/latest/reference/urllib3.fields.html) in the next major version.
Resolves #7724

requests: allow str and bytes for fileobj in files parameter

---

tests/mypy_test.py

- Remove the `--warn-unused-ignores` command-line option (it doesn't work, see #6307).
- Add more type hints.
I am planning a second PR after this one, to add new functionality to `mypy_test.py` so that it runs on files in the `tests` and `test_cases` directories.

Cleanup `mypy_test.py`

---

stdlib/inspect.pyi

inspect: Add positions attributes that will be new in 3.11

---

tests/check_consistent.py
tests/mypy_test.py
tests/pytype_test.py
tests/stubtest_third_party.py

- Add several type hints to untyped functions.
- While we're at it, upgrade several annotations to use modern syntax by using `from __future__ import annotations`. This means that the tests can't be run on Python 3.6, but 3.6 is EOL, and it is already the case that some scripts in this directory can only be run on more recent Python versions. E.g. `check_new_syntax.py` uses `ast.unparse`, which is only available in Python 3.9+.
- Fix a few pieces of code that didn't type check.

Make test scripts pass `mypy --strict`

---

.github/workflows/tests.yml
tests/README.md
tests/mypy_test.py

- `mypy_test` and pyright no longer just test the stubs, they now also test other parts of typeshed as well.
- `pytype_test.py` can now be run on 3.10, meaning the whole test suite can now also be run on 3.10.
- Various test scripts now have `from __future__ import annotations`, meaning they can now only be run on 3.7+.
- Clean up the description of `pyright_test.py`, which had a slightly confusing wording.
- Also fix the `--dry-run` config option in `mypy_test.py`, which I accidentally broke in #7746

Improve test-suite documentation

---

stdlib/dataclasses.pyi

The `fields` arg of `dataclass.make_dataclass` should have type:
```
Iterable[str | tuple[str, type] | tuple[str, type, Any]]
```
Previously the 3-tuple had type `tuple[str, type, Field[Any]]`, which
was incorrect for two reasons:
- The third element in the tuple doesn't have to be a ``Field``, it can
be any RHS value valid when defining a dataclass field (e.g.
``myfield: type = ...``). This may be a ``Field``, but it may also be a
default value like ``0``. ``Any`` is the proper type here.
- The type stubs for ``dataclass.field`` lie and say that this function
returns a value with the same type as ``default``. This avoids the need
for a mypy/pyright plugin that understands dataclasses, but also means
there is no way to create a ``Field`` object that these tools
understand, since they …

Fix `fields` arg type in `dataclass.make_dataclass`

---

stdlib/logging/__init__.pyi

Not clear why we're using a constrained TypeVar here.

logging.LoggerAdapter: Use a bound TypeVar

---

stdlib/urllib/error.pyi

Add missing 'headers' property to urllib.error.HTTPError.
Seen here: https://docs.python.org/3/library/urllib.error.html#urllib.error.HTTPError.headers

Add missing 'headers' property to urllib.error.HTTPError.

---

stdlib/_csv.pyi
stdlib/csv.pyi

- `_csv._Writer` is a confusing name for a protocol, given that there's also `_csv._writer` and `_csv.writer`. It's exactly the same as `_typeshed.SupportsWrite[str]`, so we may as well just use that.
- The `strict` field of a `_csv.Dialect` object is documented as being a `bool`, not an `int`: https://docs.python.org/3/library/csv.html#csv.Dialect.strict
- `_QuotingType` should really be a union of literal types: the runtime raises an exception if we pass in anything that's not `QUOTE_ALL`, `QUOTE_MINIMAL`, `QUOTE_NONE` or `QUOTE_NONNUMERIC`. It's probably unwise to use a union of literals here right now due to #7258, but we should use a type alias to indicate that `int` isn't really the correct type here.
- `_csv._reader.dialect` and `_csv._writer.dialect` are read-only properties at …

`_csv.pyi`: minor cleanup

---

stdlib/http/__init__.pyi

https://github.com/python/cpython/pull/91997
`description` isn't actually read-only at runtime, but I don't think there's any other way of telling type checkers "this is an attribute that the members have, not a member itself". And pretending it's a property is already what we do for `HTTPStatus`, which has the same issue.

Add `http.HTTPMethod`

---

stdlib/csv.pyi

- Add a comment about `_csv.Dialect` and `csv.Dialect` (they're two different classes at runtime, but in the stub we re-export for simplicity).
- Instantiating a `DictWriter` fails at runtime if the object passed to the `f` parameter doesn't have a `write()` method.
- Instantiating a `DictWriter` fails at runtime if the string passed to the `extrasaction` parameter is not either "raise" or "ignore".

`csv.pyi`: minor cleanup

---

tests/check_new_syntax.py

`check_new_syntax` should have emitted an error for this commit, but didn't: https://github.com/python/typeshed/pull/7806/commits/b9893473964d8451078a180c5539b4f13a1066e4
(It was almost certainly me who introduced this bug, so, uh, my bad!)

Fix bugs in `check_new_syntax.py`

---

stdlib/subprocess.pyi

According to [the document](https://docs.python.org/3/library/subprocess.html#subprocess.Popen.returncode), the `Popen.returncode` should be `Optional[int]`:
>The child return code, set by [poll()](https://docs.python.org/3/library/subprocess.html#subprocess.Popen.poll) and [wait()](https://docs.python.org/3/library/subprocess.html#subprocess.Popen.wait) (and indirectly by [communicate()](https://docs.python.org/3/library/subprocess.html#subprocess.Popen.communicate)). **A None value indicates that the process hasn’t terminated yet.**

Fix stdlib `subprocess.Popen.returncode` typing

---

stdlib/_ast.pyi
tests/stubtest_allowlists/py39.txt
tests/stubtest_allowlists/py3_common.txt

```
In [4]: ast.dump(ast.parse('f"{x!r}"'))
Out[4]: "Module(body=[Expr(value=JoinedStr(values=[FormattedValue(value=Name(id='x', ctx=Load()), conversion=114)]))], type_ignores=[])"
In [5]: ast.dump(ast.parse('f"{x}"'))
Out[5]: "Module(body=[Expr(value=JoinedStr(values=[FormattedValue(value=Name(id='x', ctx=Load()), conversion=-1)]))], type_ignores=[])"
```
(On 3.9 but I don't think this has changed since 3.6.)
The stdlib also assumes this: https://github.com/python/cpython/blob/main/Lib/ast.py#L1211 (`chr(None)` doesn't work).

ast: FormattedValue.conversion cannot be None

---

stubs/protobuf/google/protobuf/internal/message_listener.pyi

These stubs no longer support Python 2, and explicit inheritance from `object` is never necessary in Python 3.
Unblocks https://github.com/PyCQA/flake8-pyi/pull/217

Remove explicit inheritance from `object`

---

stdlib/gettext.pyi

I saw an override of CONTEXT in an internal library, so maybe it
makes sense to modify it.

gettext: Make GNUTranslations.CONTEXT not final

---

.github/workflows/mypy_primer.yml

Only changes to files in `stdlib` or `stubs` will ever have any effect on the checked open-source code. But also run primer on changes to files in `.github/workflows` so that we can see the effect of changes to the `mypy_primer.yml` file itself.

Don't run mypy_primer on changes to test files

---

stdlib/types.pyi

Although the specific format of the bytes is opaque and undocumented, the fact that it will be bytes is stable.
This is necessary in order for type checkers to allow creating one code object from another, since the `lnotab`
positional argument to `__init__` is typed as bytes.

CodeType.co_linetable is of type `bytes`

---

.github/workflows/tests.yml

Currently, when a maintainer opens a pull request from a branch in the
typeshed repository (instead of a fork), CI is run twice: once for the
PR and once for the push. This not only wastes CI minutes (and it seems
we're running into some limits lately), but also makes CI output twice
as large and more difficult to process.
The disadvantage is that a PR needs to be opened to run CI.
Alternatively, CI can be triggered manually.

Only run CI on pushes to main/master and pull requests

---

.github/workflows/stubtest_stdlib.yml

The script doesn't import tomli

CI: Don't install tomli for stubtest_stdlib

---

stdlib/types.pyi
tests/stubtest_allowlists/py311.txt

- New attributes in 3.11
- Arguments to CodeType.__init__ are always positional (have fun)
- co_consts can use object instead of Any

types: 3.11 (and earlier) fixes

---

stubs/docopt/docopt.pyi

`docopt.printable_usage`: https://github.com/docopt/docopt/blob/5f08e0b412fc9fec3a73dd47bc26044dae66a013/docopt.py#L464-L471
Usage of this annotation: https://github.com/jjjake/internetarchive/blob/5897fb9d86b1321d9568600afed13b10bb137f83/internetarchive/cli/ia.py#L64

docopt.printable_usage

---

stdlib/fileinput.pyi

Fixes #7922, part of #7928.
Also discovered an apparent CPython bug in the process: python/cpython#93157

fileinput: Fix TypeVar usage

---

stubs/mock/mock/mock.pyi

The first overload covers the case where `new` is not given.
Part of #7928

mock: Fix unconstrained TypeVar

---

stubs/requests/requests/sessions.pyi

Fixes a problem reported by @rpdelaney in  https://github.com/python/typeshed/pull/7773#issuecomment-1134888216
I spent a while looking at requests source code, and I'm quite convinced that the headers can't be mutated. Each request is prepared before auth etc headers are applied, and the headers are copied when preparing.

requests: allow immutable headers

---

stdlib/gettext.pyi

gettext: fix unconstrained TypeVar

---

stubs/redis/redis/commands/core.pyi

redis: Fix unconstrained TypeVars in a few redis commands

---

stubs/Pillow/PIL/Image.pyi

This PR adds all of the image modes documented [here](https://pillow.readthedocs.io/en/stable/handbook/concepts.html#concept-modes) to the `_Mode` type alias in the `PIL.Image` type stub

Pillow: Add missing image modes to `_Mode` type alias in `Image.pyi` stub (issue #7956)

---

stdlib/tempfile.pyi

The name `_DirT` implies that it is a `TypeVar`, but it isn't; it's a generic `TypeAlias` that can be parameterised with a `TypeVar`. Rename it to just `_Dir` instead.
Also, use aliases instead of repeating incredibly long `Literal` annotations six times.

`tempfile.pyi`: readability improvements

---

stubs/Pillow/PIL/Image.pyi

As mentioned by @Julian-O in [their comment](https://github.com/python/typeshed/pull/7960#issuecomment-1139252724) on the previous PR, support for various image types is inconsistent.
This PR changes the `_Mode` type alias to simply be `str`

Pillow: change `_Mode` type alias to `str` in `Image.pyi` stub

---

tests/mypy_test.py

Ever since we upgraded to mypy 0.960, I've hit https://github.com/python/mypy/issues/11899 every second time I run `mypy_test.py` locally. Mypy always crashes on `Flask-SQLAlchemy`, so I propose we skip `mypy_test` on those stubs for now, unless and until https://github.com/python/mypy/pull/12324 is merged.

`mypy_test.py`: Skip `Flask-SQLAlchemy`

---

stubs/dj-database-url/dj_database_url.pyi

Hey. It's me again.
I've happily installed `types-dj-database-url`, but it seems I've made a small mistake with the PR from earlier. For reference: #7972 .
Required key is ENGINE and not NAME. This fixes that issue.
A question, I have, you might be able to answer me: I have a project that uses dj-database-url. If I wanted to test these stubs against my project, how would I go about doing so? 
Thanks.

Fix dj_database_url required key

---

stubs/jsonschema/jsonschema/exceptions.pyi

In https://github.com/matrix-org/synapse/issues/12901 I noticed an problem with the changes to the jsonschema stubs in #7950.
This change remedies that by teaching mypy that paths, relative paths and absolute paths on Error objects can hold strings, ints, or a mixture of the two. For evidence that this is the case, see e.g. https://github.com/python-jsonschema/jsonschema/blob/2e2832463e8de7977217d377ca0553c10f6fb48c/jsonschema/tests/test_exceptions.py#L246-L247 or the test case I provided in https://github.com/python/typeshed/pull/7950#discussion_r884279863.

jsonschema: {relative,absolute}_path can hold ints

---

stubs/jsonschema/jsonschema/exceptions.pyi

Related to #7980, I checked for more attributes where I had made the mistake of introducing a `<container>[str]` annotation which should read `<container>[str | int]`
I didn't have an example usage in mind, so I tried adding a `for x in schema_path: assert isinstance(x, str)` to the error init and running jsonschema's tests. It failed (as expected) on ints, so I'm certain that the original annotation I added has an error in it and I'm reasonably confident that `str | int` is the correct form.
schema_path, relative_schema_path, and absolute_schema_path are all (related) attributes of `jsonschema` errors which contain `str | int` but were accidentally annotated as containing `str`. Fix them for accuracy.

Fix jsonschema exception str|int containers

---

pyrightconfig.json
pyrightconfig.stricter.json

It doesn't usually find real issues in stubs.
https://github.com/python/typeshed/pull/7964#discussion_r884106104

pyright: turn off reportPropertyTypeMismatch

---

tests/check_new_syntax.py

There's a few places in #8013 where `check_new_syntax.py` should be complaining that the author isn't using PEP 604 syntax, but it isn't. This PR fixes that bug.

`check_new_syntax.py`: Fix bug in `visit_AnnAssign`

---

stubs/dateparser/dateparser/date.pyi

It doesn't exist at runtime:
```python
>>> import dateparser.date
>>> dateparser.date.Self
AttributeError: module 'dateparser.date' has no attribute 'Self'
```
...and it's not used in the stub either.
I'm not sure why stubtest didn't pick it up. My stubtest patch over at https://github.com/python/mypy/pull/12214 _does_ pick it up (and I'm not sure why that is, either... but it's a true positive!)

`dateparser`: Remove redundant import of `_typeshed.Self`

---

stubs/frozendict/METADATA.toml

No changelog kept, but https://github.com/Marco-Sulla/python-frozendict/commit/7fcdd3aa990aa323fbcecea4b33733468c97cc27
So removable come July 15

frozendict: mark as obsolete since 2.2.0

---

.flake8

black fixes these for us in `pre-commit.ci`. See #8064 for an example.

flake8 config: Ignore more error codes in `.py` files

---

stdlib/_typeshed/__init__.pyi
stdlib/builtins.pyi
test_cases/stdlib/builtins/test_sum.py

Closes #7574 (cc. @jpy-git). I think this is just about the best we can do without introducing many false-positive errors.

`builtins.sum`: Items in the iterable must support addition with `int` if no `start` value is given

---

.pre-commit-config.yaml
requirements-tests.txt

This makes it easier to lint your own work with `pre-commit`, but doesn't change the CI config by adding this to the pre-commit.ci skip list.
There's no way to automatically reflect the additional dependencies from the requirements file, so the flake8 plugin list needs to be a verbatim copy.
resolves #7991
---
Two asides:
- Sorry this took me so long to put in. I meant to do it right away and got distracted.
- If there's any discomfort about copying the requirements data, let's just nix this and close #7991 as a wontfix (at least for now). I think it's worth keeping the copy, but I also understand not wanting duplicate configs.

Add pre-commit config for flake8

---

test_cases/stdlib/builtins/test_pow.py
test_cases/stdlib/builtins/test_sum.py
test_cases/stdlib/test_codecs.py
test_cases/stdlib/test_unittest.py
tests/mypy_test.py

This PR removes mypy error codes from the `test_cases` directory, and alters `mypy_test` so that it no longer enforces that `type: ignore`s in the `test_cases` directory have mypy error codes.
When I created the first test cases, it seemed like a good idea to enforce mypy error codes, as we use mypy error codes in most of the rest of typeshed. But `type: ignore`s in the `test_cases` directory serve a different purpose to those in the rest of typeshed -- whereas in the rest of typeshed we use them to stop a type checker complaining where we're doing something it doesn't quite understand, in the `test_cases` directory we use them to signify "this code is meant to fail a type checker". As a result, whereas the error codes in the rest of typeshed help make the stubs more self-documenting, it …

Remove mypy error codes from the `test_cases` directory

---

stubs/redis/redis/commands/core.pyi

`redis`: fix more unconstrained `TypeVar`s

---

stubs/protobuf/@tests/stubtest_allowlist.txt
stubs/protobuf/google/protobuf/descriptor.pyi

Refs #6905.
Pyright points out that two classes in the stubs for `protobuf` have `__init__` and `__new__` methods that contradict. However, neither of these classes can be directly instantiated anyway:
```python
>>> from google.protobuf.descriptor import Descriptor
>>> Descriptor()
File "C:\Users\alexw\coding\protobuf\lib\site-packages\google\protobuf\descriptor.py", line 313, in __new__
_message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
1. Downgrade the protobuf …
```

`protobuf`: Delete some `__new__` and `__init__` methods

---

stdlib/imaplib.pyi

`mypy` would complain when trying to sub-class the `imaplib`
exceptions.
Change the exceptions from a `type` to a `class`
Closes: #8094

fix: type-hints for imaplib exceptions

---

CONTRIBUTING.md
stubs/JACK-Client/METADATA.toml
stubs/gdb/METADATA.toml
stubs/pyaudio/METADATA.toml
stubs/pycurl/METADATA.toml
stubs/pynput/METADATA.toml
tests/check_consistent.py
tests/get_apt_packages.py
tests/stubtest_third_party.py

I want to start enabling `--ignore-missing-stub` on third party packages, like we do for stdlib, since this helps ensure type completeness. I thought it might make sense to separate out the metadata little bit.

stubtest: use separate table in METADATA.toml

---

stdlib/socket.pyi
tests/stubtest_allowlists/darwin.txt
tests/stubtest_allowlists/linux.txt
tests/stubtest_allowlists/win32-py310.txt
tests/stubtest_allowlists/win32-py311.txt
tests/stubtest_allowlists/win32-py37.txt
tests/stubtest_allowlists/win32-py38.txt
tests/stubtest_allowlists/win32-py39.txt
tests/stubtest_allowlists/win32.txt

This matches what happens at runtime, from `Enum._convert_`
Helps with #8098. Fixes #5696.

socket: consistency between constants and enums

---

stdlib/_socket.pyi
stdlib/socket.pyi

socket: add TCP_KEEPALIVE

---

stdlib/typing.pyi

`typing.AwaitableGenerator` is a type-time only member, it should be decorated with `type_check_only` (despite the fact that mypy doesn't support it python/mypy/issues/9531 :trollface:)
`type_check_only` was moved to the top of `typing` so that it can be used within the file.

`typing.AwaitableGenerator` add `type_check_only`

---

stdlib/asyncio/tasks.pyi

At runtime, the signature for `asyncio.gather()` has `return_exceptions=False` as the default. As such, the `asyncio.gather()` overloads with `return_exceptions: bool` should only be chosen if a user actually specifies a value for `return_exceptions`. The `= ...` isn't needed for these overloads.

`asyncio.gather`: Remove default values for `return_exceptions: bool` overloads

---

stdlib/asyncio/tasks.pyi

And move the fallback `list[Any]` overload to the end, to improve readability

`asyncio.gather`: Add overload for if no positional arguments are provided

---

tests/README.md
tests/mypy_test.py

Currently, the argument-parsing for the `--python-version` option is a little broken. If you try to pass more than one value to `--python-version` when running the test locally, it doesn't work.
This PR means that either of the following two invocations will work:
```
python tests/mypy_test.py -p3.6 -p3.7
```
```
python tests/mypy_test.py --python-version 3.6 3.7
```

mypy_test.py: Fix argument-parsing for `--python-version`

---

stdlib/xml/sax/__init__.pyi

fix(`stdlib.xml`): re-export ContentHandler

---

tests/mypy_test.py

This makes it easy to run mypy on, for example, only the `test_cases` directory. The following invocation would test the test cases on Python 3.6 and 3.9, on platforms linux and darwin:
```
python tests/mypy_test.py -d test_cases --python-version 3.6 3.9 --platform linux darwin
```
Refs #8139

mypy_test.py: Add command-line argument to enable selecting which parts of the test to run

---

stdlib/urllib/request.pyi

to mitigate typechecker complains about unknown module members. [cpython/#94204](https://github.com/python/cpython/issues/94204)

re-exporting `HTTPError` in `urllib.request`

---

stubs/requests/METADATA.toml

[stubsabot] Bump requests to 2.28.*

---

stubs/entrypoints/METADATA.toml

Release: https://pypi.org/project/entrypoints/0.4/
Homepage: https://github.com/takluyver/entrypoints

[stubsabot] Bump entrypoints to 0.4.*

---

scripts/stubsabot.py

See https://github.com/python/typeshed/pull/8157 for an example

stubsabot: add project links

---

stubs/pycurl/METADATA.toml

Release: https://pypi.org/project/pycurl/7.45.1/
Homepage: http://pycurl.io/

[stubsabot] Bump pycurl to 7.45.*

---

stdlib/typing_extensions.pyi

This wasn't possible prior to https://github.com/google/pytype/commit/6b1fee04f8e040be59b9787228abaa4bb48cd407

`typing_extensions`: harmonise `__all__` with `__all__` at runtime

---

stubs/jsonschema/METADATA.toml
stubs/jsonschema/jsonschema/protocols.pyi
stubs/jsonschema/jsonschema/validators.pyi

Release: https://pypi.org/project/jsonschema/4.6.0/

[stubsabot] Bump jsonschema to 4.6.*

---

.github/workflows/daily.yml
.github/workflows/mypy_primer.yml
.github/workflows/mypy_primer_comment.yml
.github/workflows/stubtest_stdlib.yml
.github/workflows/tests.yml

The actions/setup-python now always requires a version specified.

Update GitHub actions to their latest versions

---

stubs/python-nmap/METADATA.toml

Release: https://pypi.org/project/python-nmap/0.7.1/
Homepage: http://xael.org/pages/python-nmap-en.html

[stubsabot] Bump python-nmap to 0.7.*

---

stubs/xmltodict/METADATA.toml
stubs/xmltodict/xmltodict.pyi

Release: https://pypi.org/project/xmltodict/0.13.0/
Homepage: https://github.com/martinblech/xmltodict

Bump xmltodict to 0.13.*

---

stdlib/multiprocessing/pool.pyi

Relevant to PyCQA/flake8-pyi/issues/237.

`multiprocessing`: audit callback annotations

---

stubs/aws-xray-sdk/METADATA.toml
stubs/aws-xray-sdk/aws_xray_sdk/core/recorder.pyi

Release: https://pypi.org/project/aws-xray-sdk/2.9.0/
Homepage: https://github.com/aws/aws-xray-sdk-python

[stubsabot] Bump aws-xray-sdk to 2.9.*

---

stubs/jmespath/METADATA.toml

Release: https://pypi.org/project/jmespath/1.0.1/
Homepage: https://github.com/jmespath/jmespath.py

[stubsabot] Bump jmespath to 1.0.*

---

stubs/tzlocal/METADATA.toml

Release: https://pypi.org/project/tzlocal/4.2/

[stubsabot] Bump tzlocal to 4.2

---

stdlib/_typeshed/__init__.pyi
stdlib/unittest/case.pyi
test_cases/stdlib/test_unittest.py

Fix `assertAlmostEqual` regression on mixed numeric types

---

stdlib/inspect.pyi

Relevant to PyCQA/flake8-pyi/issues/237

Improve `inspect` callbacks

---

stdlib/shelve.pyi

This makes it possible to write
```python
s: shelve.Shelf[MyClass] = shelve.open(...)
c = s[k]  # inferred as MyClass
```
instead of being forced to write runtime checks
```python
s = shelve.open(...)
c = s[k]
assert isinstance(c, MyClass)
```
or
```python
s = shelve.open(...)
c = cast(MyClass, s[k])
```

shelve.open should return Any

---

stubs/python-slugify/METADATA.toml
stubs/python-slugify/slugify/slugify.pyi

Release: https://pypi.org/project/python-slugify/6.1.2/
Homepage: https://github.com/un33k/python-slugify

[stubsabot] Bump python-slugify to 6.1.*

---

stubs/aws-xray-sdk/METADATA.toml

Release: https://pypi.org/project/aws-xray-sdk/2.10.0/
Homepage: https://github.com/aws/aws-xray-sdk-python

[stubsabot] Bump aws-xray-sdk to 2.10.*

---

stubs/stripe/METADATA.toml

Release: https://pypi.org/project/stripe/3.5.0/
Homepage: https://github.com/stripe/stripe-python
Changelog: https://github.com/stripe/stripe-python/blob/master/CHANGELOG.md

[stubsabot] Bump stripe to 3.5.*

---

stdlib/builtins.pyi
test_cases/stdlib/builtins/test_sum.py

Add a tiny bit more special-casing for `sum`

---

scripts/create_baseline_stubs.py

Since stubgen will usually create definition complete stubs, we should have
stubtest check missing definitions so we can know to reflect any future
additions.

create_baseline_stubs: check all defs by default

---

stubs/ujson/METADATA.toml

Release: https://pypi.org/project/ujson/5.4.0/
Homepage: https://github.com/ultrajson/ultrajson

[stubsabot] Bump ujson to 5.4.*

---

stdlib/imaplib.pyi

Add type-hints for `imaplib.Commands` which is defined here in
imaplib.py:
https://github.com/python/cpython/blob/6442a9dd212fa18343db21849cf05c0181662c1f/Lib/imaplib.py#L58-L102
Closes: #8261

stdlib(imaplib): add type-hint for `imaplib.Commands`

---

stubs/jsonschema/METADATA.toml
stubs/jsonschema/jsonschema/exceptions.pyi

Release: https://pypi.org/project/jsonschema/4.7.2/
Homepage: https://github.com/python-jsonschema/jsonschema
Changelog: https://github.com/python-jsonschema/jsonschema/blob/main/CHANGELOG.rst

[stubsabot] Bump jsonschema to 4.7.*

---

stubs/tqdm/tqdm/contrib/discord.pyi
stubs/tqdm/tqdm/contrib/slack.pyi
stubs/tqdm/tqdm/contrib/telegram.pyi
stubs/tqdm/tqdm/notebook.pyi

Fixes a few issues I noticed after merging #8235. These `__init__` overrides in the subclasses currently have the effect of making type checkers unable to perform type inference for instances of these subclasses, unless we tediously copy/paste the whole overload stack like I propose in this PR. Some of the existing `__init__` overrides are also missing a few optional parameters that are present for the subclasses, but not the superclass.

`tqdm`: Improve a few `__init__` methods

---

.github/workflows/tests.yml
CONTRIBUTING.md
requirements-tests.txt
tests/README.md
tests/check_consistent.py

packaging is the standard tool for dealing with versions and
requirements. This allows us to easily support all PEP 508 specs.
packaging also has good error messages, so I don't create our own here.
This lets us get rid of our handrolled half parser and sanity checks.
I kept the whitespace consistency check, since that's just a formatting
lint and isn't testing the correctness of parsing (which we now
definitely do correctly).

Use packaging to parse versions

---

.github/workflows/daily.yml
.github/workflows/stubtest_stdlib.yml

The `macos-10.15` Actions runner image [is deprecated, and will be removed on 30th August](https://github.blog/changelog/2022-07-20-github-actions-the-macos-10-15-actions-runner-image-is-being-deprecated-and-will-be-removed-by-8-30-22/). The `tkinter` thing doesn't seem to be an issue any more, so we should be good to use `macos-latest` now.

CI: Use `macos-latest` for stubtest

---

CONTRIBUTING.md

I don't think that we ever should use one-tuples (like `(3,)`) in our current setup.
I think that this is a legacy from times when python2 stubs were a thing.
This might confuse people.

Change `Stub versioning` wording in `CONTRIBUTING.md`

---

CONTRIBUTING.md

With https://github.com/python/typeshed/issues/4913 closed, `TypeAlias` is allowed to be used from `typing`

Update `CONTRIBUTING.md` as `TypeAlias` is now allowed

---

stubs/chardet/chardet/__init__.pyi

`__version__` is part of the `__all__` of `chardet` here:
https://github.com/chardet/chardet/blob/main/chardet/__init__.py#L27
`__version__` is a string, as seen on:
https://github.com/chardet/chardet/blob/main/chardet/version.py#L8

Add missing `__version__` to `chardet.__init__`

---

stubs/mysqlclient/MySQLdb/release.pyi

The `mysqlclient.release.version_info` variable is a 5-tuple. This is generated dynamically but is verified as a tuple in the unit tests seen here and a length of five:
https://github.com/PyMySQL/mysqlclient/blob/180c9df4ab8325b75f6b26070951fd852ec76614/tests/test_MySQLdb_nonstandard.py#L33-L34
This is not tested in other locations.
This can also be verified against the runtime behavior:
```
In [1]: from MySQLdb.release import version_info
In [2]: version_info
Out[2]: (2, 1, 1, 'final', 0)
```
Version info is set from metadata.cfg during the build, so this corresponds to:
https://github.com/PyMySQL/mysqlclient/blob/dac24e7b05b83eb1511e25e3cd8f8c20b7fbe112/metadata.cfg#L3

refactor: fix type of `mysqlclient.release.version_info`

---

stdlib/http/client.pyi

It can be either:
- `None`: https://github.com/python/cpython/blob/310f94871a923f6cf3dc9259e732ce2376578b26/Lib/http/client.py#L856
- or `socket.socket`: https://github.com/python/cpython/blob/310f94871a923f6cf3dc9259e732ce2376578b26/Lib/http/client.py#L955-L956

Type `http.client.HTTPConnection.sock`

---

stdlib/curses/__init__.pyi

This merge request updates the `wrapper` `__func` parameter to use ParamSpec and Concatenate to address a todo.

Fix stdlib/curses.pyi TODO RE: Concatenate usage

---

stdlib/multiprocessing/popen_forkserver.pyi
tests/stubtest_allowlists/win32.txt

X-Ref: https://github.com/python/typeshed/issues/6799
This adds best-effort types to multiprocessing.popen_fork to continue to address issue https://github.com/python/typeshed/issues/6799
The source file can be viewed here:
https://github.com/python/cpython/blob/main/Lib/multiprocessing/popen_forkserver.py
Note that the forkserver version inherits from `popen_fork`, so `_launch` is called explicitly as was the case there. This only includes new or overriding attributes on the `Popen` class, ignoring attributes like `pid` which are identical with the parent. `sentinel` is defined here even though it matches `popen_fork.Popen` because it doesn't have the same condition as the comment in the other stub.

fix: add missing multiprocessing.popen_forkserver.pyi stubs

---

stdlib/multiprocessing/popen_spawn_posix.pyi
tests/stubtest_allowlists/win32.txt

X-Ref: https://github.com/python/typeshed/issues/6799
This adds the missing stubs for multiprocessing.popen_spawn_posix from:
https://github.com/python/cpython/blob/main/Lib/multiprocessing/popen_spawn_posix.py

fix: add missing multiprocessing.popen_spawn_posix stubs

---

test_cases/README.md

`test_cases`: Improve README

---

test_cases/README.md

`test_cases` README: fix typos

---

stdlib/io.pyi

`io.IOBase` has `ABCMeta` as the metaclass at runtime: https://github.com/python/cpython/blob/75a6441718dcbc65d993c9544e67e25bef120e82/Lib/io.py#L71
But not currently in the stub. This is causing an unexpected stubtest failure for a `urllib3` PR here: https://github.com/python/typeshed/runs/7633083101?check_suite_focus=true

`io.IOBase`: correct metaclass

---

stubs/DateTimeRange/datetimerange/__init__.pyi
stubs/DateTimeRange/datetimerange/__version__.pyi

Fix a few missing variables from https://github.com/thombashi/DateTimeRange and clean up the re-export from the other file rather than re-definition

fix: add missing stubs in datetimerange

---

scripts/create_baseline_stubs.py
scripts/stubsabot.py
tests/mypy_test.py
tests/pyright_test.py
tests/stubtest_stdlib.py

Use f-strings for concatenating strings instead of `'+'` or `.format`
Python added f-strings in version 3.6, with [PEP 498](https://www.python.org/dev/peps/pep-0498/). F-strings are a flexible and powerful way to concatenate strings. They make the code shorter and more readable, since the code now looks more like the output. In addition, they also come with performance benefits as they reduce the number of times the string must be processed, resulting in faster string processing.
This aligns with the desire to ensure that scripts and tests should support currently supported versions of Python outlined [here](https://devguide.python.org/versions/#versions)

refactor: prefer f-strings to other format/concatentation styles

---

requirements-tests.txt

Picks up a fix for the pytype test failure in
https://github.com/python/typeshed/pull/8469.

Bump pytype version.

---

stdlib/multiprocessing/context.pyi

Two main changes:
1. I think it is better to use assignment in case of alises where possible. For example, `Process` is simply defined as `Process = Process` in [cpython's `DefaultContext`](https://github.com/python/cpython/blob/75a6441718dcbc65d993c9544e67e25bef120e82/Lib/multiprocessing/context.py#L231). This is more accurate: it is set as an explicit classvar and we have full type info (`type[Process]` is wider)
2. There's no need to redefine `SpawnContext` and `SpawnProcess` in `if`. They are the same in case of typing. Only implementation details differ: 
- https://github.com/python/cpython/blob/75a6441718dcbc65d993c9544e67e25bef120e82/Lib/multiprocessing/context.py#L283-L288
- https://github.com/python/cpython/blob/75a6441718dcbc65d993c9544e67e25bef120e82/Lib/multiprocessing/context. …

Improve `multiprocessing.context` module

---

stubs/stripe/@tests/stubtest_allowlist.txt
stubs/stripe/stripe/api_resources/payment_intent.pyi

Similar to #7230, `stripe.PaymentIntent.confirm` can be called as an
instance method or a `classmethod`.

Add classmethod to stripe.PaymentIntent.confirm.

---

.github/workflows/daily.yml
.github/workflows/stubtest_stdlib.yml

Refs #8510 (but let's keep that issue open as a reminder to us to unpin ASAP)

Temporarily pin stubtest to 3.10.5

---

stubs/chardet/chardet/__init__.pyi
stubs/emoji/emoji/core.pyi
stubs/redis/redis/asyncio/connection.pyi

Unblocks https://github.com/PyCQA/flake8-pyi/pull/271

Remove a few unused `TypedDict`s

---

stdlib/email/headerregistry.pyi

Source: https://github.com/python/cpython/blob/325ae93b6b7113cd4a4c2ce441615ae7def779e2/Lib/email/headerregistry.py#L562-L567
Refs https://github.com/python/mypy/pull/13367#issuecomment-1210311506

Improve `email.headerregistry.HeaderRegistry` definition

---

stdlib/builtins.pyi

Not all type checkers support this decorator (mypy notably doesn't), but adding the decorator doesn't interfere with them at all, it's nice to explicitly mark these as works of fiction, and it could plausibly help out IDEs/autocompletion tools such as PyCharm/Jedi that have to patch typeshed to remove these symbols (https://github.com/python/typeshed/issues/2999#issue-445807418)

Add `@type_check_only` to a few fictional classes in `builtins.pyi`

---

test_cases/README.md

Refs https://github.com/python/typeshed/pull/8520

Add "Naming convention" to `test_cases/README.md`

---

stdlib/socketserver.pyi

This is documented and implemented as such, and means that the signatures of some of the methods (notably `__init__`) actually differ from those on `BaseServer`.
This also fixes the definition of the (new in Python 3.11, via https://github.com/python/cpython/pull/30072) `allow_reuse_port` attribute on these classes that would otherwise have been in conflict with the inheritance change.

Fix `UDPServer` to correctly inherit from `TCPServer`

---

stubs/cryptography/@tests/stubtest_allowlist.txt
stubs/cryptography/cryptography/hazmat/primitives/serialization/pkcs12.pyi

It seems that an invalid parameter name was used for `serialize_key_and_certificates`.
`encryption_algorithm` should be used instead of `enc`.
Documentation: https://cryptography.io/en/latest/hazmat/primitives/asymmetric/serialization/#cryptography.hazmat.primitives.serialization.pkcs12.serialize_key_and_certificates
Source code: https://github.com/pyca/cryptography/blob/4a4f4d94ce5a641de3020042c70c1734af265d5e/src/cryptography/hazmat/primitives/serialization/pkcs12.py#L171

cryptography: Rename parameter of serialize_key_and_certificates

---

stubs/ldap3/ldap3/core/connection.pyi

The ldap3 `Connection` class `client_strategy` parameter is missing `SAFE_RESTARTABLE` value
See the source implementation [here](https://github.com/cannatag/ldap3/blob/dev/ldap3/core/connection.py#L332)

Add SAFE_RESTARTABLE strategy to ldap3 Connection client_strategy parameter

---

stdlib/xml/dom/minidom.pyi

This adds missing nodeType type hints. Each node uses one of these:
https://github.com/python/cpython/blob/157aef79b07e07bf115e49cdf5ff25e74c66354e/Lib/xml/dom/__init__.py#L18
This continues to address #6886
As seen here:
* https://github.com/python/cpython/blob/main/Lib/xml/dom/minidom.py#L328
* https://github.com/python/cpython/blob/main/Lib/xml/dom/minidom.py#L348
* https://github.com/python/cpython/blob/main/Lib/xml/dom/minidom.py#L666
* https://github.com/python/cpython/blob/main/Lib/xml/dom/minidom.py#L991
* https://github.com/python/cpython/blob/main/Lib/xml/dom/minidom.py#L1093
* https://github.com/python/cpython/blob/main/Lib/xml/dom/minidom.py#L1200
* https://github.com/python/cpython/blob/main/Lib/xml/dom/minidom.py#L1216
* …

fix: add missing `xml.dom.minidom.*.nodeType` type

---

stdlib/argparse.pyi

A drive-by. I grepped for TODO and this one seemed easy enough.

argparse: type subparser helper's `add_parser`

---

stubs/Flask-SQLAlchemy/flask_sqlalchemy/__init__.pyi

`SQLAlchemy().session` will always be of type `Session`: https://github.com/pallets-eco/flask-sqlalchemy/blob/2d9257e79b8246632b7518c613fb24bc523f9b1d/src/flask_sqlalchemy/__init__.py#L760 (technically a `ScopedSession`, but just `Session` will go a hell of a long way for type hinting).

Flask-SQLAlchemy: type session as Session

---

tests/check_consistent.py

This would lead to confusion. The types prefix is special cased in
various ways in stub_uploader

Disallow adding stubs for types- packages

---

stubs/psycopg2/psycopg2/__init__.pyi

When a `connection_factory` argument is provided to psycopg2's `connect` function, the function's return type now matches that of the factory output class. However, if `cursor_factory` is set and has a non-`None` value and/or `connection_factory` is not set or is `None`, the return type is simply `connection`, as before.

Improve return type for psycopg2 connect function

---

stubs/redis/redis/client.pyi

Source: https://github.com/redis/redis-py/blob/b5ebada842c715e9ee74ea638a7e6d11afcddae1/redis/client.py#L683

Do not override `AbstractRedis.RESPONSE_CALLBACKS`

---

stubs/six/six/__init__.pyi

Mypy will (correctly, I think) start flagging `type[type[Any]]` as an illegal annotation when mypy 0.980 comes out. Let's fix it now, before it comes out.

`six`: Fix incorrect `type[type[Any]]` annotation

---

stdlib/_ctypes.pyi
tests/stubtest_allowlists/py311.txt

After reviewing https://github.com/python/typeshed/pull/8582 I've noticed that `_ctypes` right now misses quite a few definitions.
Let's start adding them.
`CTYPES_MAX_ARGCOUNT` is always defined in `_ctypes` since 3.11: https://github.com/python/cpython/blob/3.11/Modules/_ctypes/ctypes.h#L21-L27

Add `CTYPES_MAX_ARGCOUNT` to `_ctypes`

---

tests/check_consistent.py

- Fixes bug in checking directories in stubs/
- Use pathlib for convenience
- Share more logic between check_stubs and check_stdlib
- Better recursive checking, e.g. if a README.md is in the wrong place
- Test distribution names are valid
- Errors now contain full paths
- I believe pathlib normalises separators, but someone with Windows
might want to double check this continues to work

Improve check_consistent

---

tests/mypy_test.py

Currently, the testsuite early exits if it's filtering on a single
package. With this change, it will correctly complete.
For example `tests/mypy_test.py protobuf`

Support tests/mypy_test.py [package]

---

tests/mypy_test.py

As discussed in #8139, the `--dry-run` option doesn't really seem to be that useful

`mypy_test.py`: Remove `--dry-run` option

---

stdlib/_ctypes.pyi
tests/stubtest_allowlists/win32.txt

I added win32-specific constants to `_ctypes`.
(related to #8582 that `stdlib/_ctypes.pyi` was added)

Add win32-specific constants to `_ctypes`

---

requirements-tests.txt
tests/check_consistent.py

Add tests to make sure that:
- All files in `test_cases` are `.py` files.
- All `.py` files in `test_cases` have names starting with `test_`.
- All requirements listed in `.pre-commit.config.yaml` also appear in `requirements-tests.txt`
- All requirements listed in `.pre-commit.config.yaml` have the same version specifier as the ones in `requirements-tests.txt`
Also rename the `check_same_files()` function to `check_no_symlinks()`, which is more accurate these days.

Further enhance `check_consistent.py`

---

stubs/typed-ast/typed_ast/ast3.pyi

```python
>>> from typed_ast import ast3
>>> print(ast3.dump(ast3.parse('def foo(*, arg: int) -> None: ...')))
Module(body=[FunctionDef(name='foo', args=arguments(args=[], vararg=None, kwonlyargs=[arg(arg='arg', annotation=Name(id='int', ctx=Load()), type_comment=None)], kw_defaults=[None], kwarg=None, defaults=[]), body=[Expr(value=Ellipsis())], decorator_list=[], returns=NameConstant(value=None), type_comment=None)], type_ignores=[])
```
This bug was discovered in https://github.com/python/mypy/pull/13547

`typed_ast.ast3`: `arguments.kw_defaults` should be `list[expr | None]`

---

stdlib/_ctypes.pyi
stdlib/ctypes/__init__.pyi
tests/pytype_exclude_list.txt
tests/stubtest_allowlists/py3_common.txt

I have moved some constants in `ctypes/__init__.pyi` to `_ctypes.pyi` as defined in the implementation.
I also added some constants defined in `_ctypes`.
I will move other stuffs eventually, but I will try to do it little by little.
- related to #8571 and #8633

add and migrate constants from `ctypes/__init__.pyi` to `_ctypes.pyi`

---

.flake8
.pre-commit-config.yaml
CONTRIBUTING.md
requirements-tests.txt

[flake8-noqa](https://github.com/plinss/flake8-noqa) is a plugin for validating `noqa` comments. Mypy recently added it to their CI, and I think it would be good for us to add it as well.
Unfortunately, we cannot enable `NQA102`, probably the most useful `flake8-noqa` check, which detects unused `noqa` comments. This is because we quite often have unused `noqa` comments in typeshed for unreleased flake8-pyi checks.
Nonetheless, flake8-noqa has a number of other useful checks, so I think it would be a worthy addition to our CI anyway.

Run `flake8-noqa` in CI

---

stdlib/_ast.pyi

ast.ImportFrom module field should be `str | None`.
`from ..a.b import f` dumps `ImportFrom(module='a.b', ..., level=2)`
So _identifier typing is incorrect

stdlib/_ast.pyi: Fix ast.ImportFrom arg module _identifier to str

---

stubs/fpdf2/fpdf/fpdf.pyi

Refs https://github.com/PyCQA/flake8-pyi/pull/279.
I think it's probably best to just use `Literal["DEPRECATED"]` here. If you put anything else, you get an annoying warning, and the parameter is now entirely unused: https://github.com/PyFPDF/fpdf2/blob/a14c93fc747de39121047efafeffcca7272eda9e/fpdf/fpdf.py#L381-L386

`fpdf2`: Remove redundant `str | Literal['DEPRECATED']` union

---

tests/typecheck_typeshed.py

It's annoying to have to go `python tests/typecheck_typeshed.py --dir tests` to run mypy on the `test` directory. `python tests/typecheck_typeshed.py tests` is faster to type :)

`typecheck_typeshed.py`: Make `dir` command-line argument positional-only

---

stdlib/tkinter/__init__.pyi
stdlib/tkinter/ttk.pyi

Remove redundant `str | Literal[foo]` unions, and clean up the formatting of a few type aliases.
Unblocks https://github.com/PyCQA/flake8-pyi/pull/279. See @Akuli's comments here: https://github.com/PyCQA/flake8-pyi/pull/279#issuecomment-1232100333.

Improve some `tkinter` unions

---

stubs/redis/redis/sentinel.pyi

1. `ConnectionPool` super-class has better typing of `kwargs`: https://github.com/python/typeshed/blob/master/stubs/redis/redis/connection.pyi#L195 So, I removed it from a child
2. Other changes are trivial: `kwargs` are always `dict[str, *]`

redis: Improve `kwargs` typing in `sentinel`

---

.gitignore
scripts/create_baseline_stubs.py

On windows, the stub path is generated with a backslash, which of course is not valid when added to the json file.  
`create_baseline_stubs.py` also creates a `out` folder at the root which was not gitignored.

`create_baseline_stubs.py`: Fix path separator on windows and ignore root `/out`

---

stubs/jsonschema/@tests/stubtest_allowlist.txt
stubs/jsonschema/METADATA.toml
stubs/jsonschema/jsonschema/_format.pyi

This updates the types in jsonschema._format.pyi to match the upstream source's type hints:
https://github.com/python-jsonschema/jsonschema/blob/main/jsonschema/_format.py
JSONSchema's typeshed version is 4.15.*:
https://github.com/python/typeshed/blob/master/stubs/jsonschema/METADATA.toml
which was released two days ago:
https://github.com/python-jsonschema/jsonschema/releases/tag/v4.15.0
So the use of master as a reference is not a big concern here.

Fix jsonschema._format.pyi to match upstream

---

.github/workflows/stubtest_stdlib.yml
.github/workflows/tests.yml
.github/workflows/typecheck_typeshed_code.yml

This change means that new pushes to a PR branch will cancel old jobs in CI for our `tests`, `stubtest_stdlib` and `typecheck_typeshed_code` workflows. Mypy did this a few weeks ago in https://github.com/python/mypy/pull/13249, and it seems to be working pretty well. On days with a lot of PRs, our CI still occasionally gets backed up, so I think it would be good for us to make this change as well.
Docs here: https://docs.github.com/en/actions/using-jobs/using-concurrency

Cancel old test jobs in CI

---

stubs/PyAutoGUI/@tests/stubtest_allowlist.txt
stubs/PyAutoGUI/METADATA.toml

I realised immediately after merging the pyautogui PR that there's not much point running stubtest on this package, since stubtest isn't able to import any of PyAutoGUI without access to a display screen

`pyautogui`: just skip stubtest

---

scripts/stubsabot.py

We tend to merge stubsabot PRs pretty quickly if stubtest passes in CI, but if stubtest is skipped for a certain distribution, there's a danger that there might be major changes to the library that we haven't noticed. For these packages, we should be more careful in reviewing PRs from stubsabot.

stubsabot: Add a warning to the PR message if stubtest is skipped for a distribution

---

scripts/stubsabot.py

Before:
```
(.venv) C:\Users\alexw\coding\typeshed>python scripts/stubsabot.py --action-level 2
File "C:\Users\alexw\coding\typeshed\scripts\stubsabot.py", line 441, in <module>
asyncio.run(main())
File "C:\Users\alexw\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
return loop.run_until_complete(main)
File "C:\Users\alexw\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
return future.result()
File "C:\Users\alexw\coding\typeshed\scripts\stubsabot.py", line 389, in main
args = parser.parse_args()
File "C:\Users\alexw\AppData\Local\Programs\Python\Python310\lib\argparse.py", line 1826, in parse_args
args, argv = self.parse_known_args(args, namespace)
File …
```

stubsabot: Improve argument-parsing for `--action-level`

---

stdlib/argparse.pyi

_ExtendAction was added to argparse since python 3.8. I am adding it here, since it is missing
Reference of the addition to the standard library: python/cpython@aa32a7e

Added _ExtendAction to argparse

---

stdlib/string.pyi

They are all used as `cls.ATTR_NAME`: https://github.com/python/cpython/blame/a36235d5c7863a85fa323b2048d3d254116a958e/Lib/string.py#L69-L85

Use `ClassVar` in `string.Template`

---

stdlib/tarfile.pyi

It is used as `cls.OPEN_METH` in https://github.com/python/cpython/blame/a36235d5c7863a85fa323b2048d3d254116a958e/Lib/tarfile.py#L1627

Use `ClassVar` for `tarfile.TarFile`

---

stubs/pynput/@tests/stubtest_allowlist.txt
stubs/pynput/pynput/keyboard/_base.pyi

Our stubs for `pynput` now have stubtest run on them in CI, following #8719 (hooray!). This PR gets rid of two allowlist entries, and adds better comments for the remaining entries.

Small fixes for `pynput` stubs

---

.github/workflows/daily.yml

1. Make it easier to run the workflow from a typeshed fork using the `workflow_dispatch` trigger. This is something I do sporadically if a mypy release is coming up, so we don't get blindsided by loads of very disruptive stubtest changes when the release is cut. Making this change means I don't have to manually edit the workflow to run it from my private fork, which is a pain :)
2. Auto-add the "help wanted" label to issues created by the bot when the daily test fails. @kkirsche brought up in https://github.com/python/typeshed/issues/8481#issuecomment-1221384969 that it's sometimes pretty difficult for contributors to know which typeshed issues we'd welcome help on, and which issues aren't really actionable, or are pretty out of date. I think that's a very reasonably criticism, and I've …

Improve the `daily.yml` workflow

---

stdlib/pstats.pyi

The annotation in CPython was fixed thanks to @ruancomelli in https://github.com/python/cpython/pull/96741!

`pstats`: delete outdated comment

---

scripts/stubsabot.py

Having the PR body as part of the commit message makes it easier to test changes to the stubsabot PR messages if you're hacking on stubsabot locally. (As it currently is, it's difficult to test changes to the PR message unless you run stubsabot with `--action-level everything`, which will actually create a PR against typeshed.)

stubsabot: Add the PR body to the commit message

---

stubs/Pillow/PIL/ImageDraw.pyi

https://github.com/python-pillow/Pillow/blob/87ecd01fc042bb67b11bfcff3db99fc2b61e702d/src/PIL/ImageDraw.py#L650
I don't think it's necessary, but pillow do return float sometimes.

fix: pillow.ImageDraw.textlength may return float

---

stdlib/_socket.pyi

Per the Python docs and socketmodule.c source, the address argument can be None.

sendmsg can accept None for the address

---

scripts/stubsabot.py

Fixes #8754.
In order to fix that bug, this PR introduces a new abstraction, a `PypiReleaseDownload` class. Instances of this class represent specific releases of a PyPI distribution, and various pieces of information relevant to that specific release. The `version` and `upload_date` attributes have been moved from the `PypiInfo` class to this new class, since now we potentially need to download multiple versions of the same package from PyPI.

Link earliest version with py.typed in stubsabot obsoletion PRs

---

tests/pyright_test.py

Fix the npx command for npx 8:
`'pyright@1.1.270' is not recognized as an internal or external command,`
Also ensures that the right version of pyright will be used if https://pypi.org/project/pyright/ is installed
Found these issues while investigating the work needed for #8686 and #8770

Support for npx 8 and pyright PyPI package

---

stubs/pyinstaller/PyInstaller/building/build_main.pyi
stubs/pyinstaller/PyInstaller/utils/hooks/__init__.pyi

Changed StrOrBytesPath to StrPath when used with strings.
`TypeError: Can't mix strings and bytes in path components` https://github.com/python/typeshed/pull/8770#discussion_r975969682

Pyinstaller: use `StrPath` over `StrOrBytesPath`

---

stubs/requests/requests/sessions.pyi

This allows to pass an `Iterable[bytes]`, which is useful for streaming request data:
```python
>>> def gen() -> Iterable[bytes]:
...     yield b"foo"
...     yield b"bar"
... 
>>> requests.post("http://httpbin.org/anything", data=gen()).json()["data"]
"foobar"
```
While still maintaining other usecases:
```python
>>> requests.post("http://httpbin.org/anything", data=b"foobar").json()["data"]
"foobar"
>>> requests.post("http://httpbin.org/anything", data="foobar").json()["data"]
"foobar"
>>> requests.post("http://httpbin.org/anything", data=open("/tmp/foobar", "rb")).json()["data"]
"foobar\n"
>>> requests.post("http://httpbin.org/anything", data=open("/tmp/foobar", "r")).json()["data"]
"foobar\n"
>>> requests.post("http://httpbin.org/anything", data={b"foo": b"bar"}).json()["form"] …
```

`requests`: improve `_Data` type

---

stdlib/_typeshed/__init__.pyi
stdlib/typing.pyi

See https://github.com/python/mypy/issues/13713 for details

Fix intransitive subtyping issue with SupportsGetItem

---

stubs/gdb/gdb/__init__.pyi

When GDB has just started, several `gdb` submodules are automatically loaded, so user code does not have to manually import them (for instance `import gdb.events`). Reflect that in `gdb` stubs.

gdb: add missing automatic imports

---

stubs/six/six/__init__.pyi

Mypy does not process `print_function` future import anymore, because python2 is not supported.

Remove unused `__future__` import

---

stubs/boto/METADATA.toml
stubs/boto/boto/connection.pyi

For https://github.com/typeshed-internal/stub_uploader/pull/61#discussion_r979327370

boto: drop dependency on types-six

---

stubs/google-cloud-ndb/METADATA.toml

For https://github.com/typeshed-internal/stub_uploader/pull/61#discussion_r979327370

google-cloud-ndb: drop dependency on types-six

---

stdlib/inspect.pyi

We can use more permissive `Mapping` in these cases:
- https://github.com/python/cpython/blob/feb4be1553c947ddb2bd8307419451bfdfc0a6a3/Lib/inspect.py#L1151-L1159
- https://github.com/python/cpython/blob/feb4be1553c947ddb2bd8307419451bfdfc0a6a3/Lib/inspect.py#L1419-L1429
- https://github.com/python/cpython/blob/feb4be1553c947ddb2bd8307419451bfdfc0a6a3/Lib/inspect.py#L1449-L1452

Use `Mapping` instead of `dict` in `inspect.py`

---

requirements-tests.txt
tests/check_consistent.py
tests/mypy_test.py
tests/utils.py

I often have `.mypy_cache` folders hanging around in odd places in my local typeshed clone. It's annoying that `check_consistent.py` starts failing locally whenever I have one of these folders in the `stubs/` or `stdlib/` directories. Having these folders around locally is harmless; since they're globally `gitignore`d, they'll never be committed as part of a PR.
This PR uses the `pathspec` third-party library to skip checking all `gitignore`d files in the `check_consistent.py` functions `assert_consistent_filetypes()` and `check_stubs()`. It also reuses this logic to get rid of some existing hacks in `mypy_test.py`.
`pathspec` is the library `black` uses to identify which files it should skip when it does its autoformatting. This means that we all already have it installed in our virtual …

`check_consistent.py`: ignore `.gitignore`d files

---

.github/workflows/daily.yml
.github/workflows/tests.yml
stubs/appdirs/appdirs.pyi

Fixes #8805
I believe it's fine to just install all dependencies, because stubtest uses venvs that don't "inherit" the dependencies installed here. If this isn't correct, we can grep the dependencies we actually need (I actually implemented and reverted this already).

Fix installing dependencies for 3rd party stubtest

---

stdlib/multiprocessing/managers.pyi

Fix multiprocessing.DictProxy.values()

---

scripts/create_baseline_stubs.py

I was looking into pywin32 stubs, which has multiple packages. And I couldn't specify multiple packages to `create_baseline_stubs.py`, or run it multiple times with different packages.
This adds support for that, but still ensures we don't overwrite existing stubs.
An example of existing stub that has multiple packages is PyInstaller.
I could also make the `pyrightconfig.stricter.json` "exclude" more granular by specifying the package as well. I feel this would be especially important when adding a package to an existing stub, and help with coverage by not having too wide of an exclude.

Allow `create_baseline_stubs.py` to add packages to existing stub

---

scripts/create_baseline_stubs.py

This seems to work pretty well, from playing around with it locally. Closes #8837

Use stubgen's `--export-less` option in `create_baseline_stubs.py`

---

tests/mypy_test.py

Accidentally broken in #8800 (#8841 would help prevent this kind of thing!)

`mypy_test.py`: restore previous behaviour where all third-party stubs are tested by default

---

.github/workflows/stubsabot.yml

I think stubsabot has been a really big success. Let's change it to a daily workflow, so that we don't get an avalanche of PRs every Friday, and so that we can see more quickly if a PR changing stubsabot has accidentally broken the script. (If that _does_ happen, it should be pretty easy to just revert the commit that accidentally broke stubsabot, and go back to a version that works pretty well.)

Run stubsabot daily, not weekly

---

.github/workflows/stubsabot.yml

Fixes #8434.
This uses a new ssh key that @JelleZijlstra just set up for our repo ([this option](https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#push-using-ssh-deploy-keys) in Peter Evans's guide to getting checks to run on automated PRs. It seems to be a good option in terms of both security and usability. It's also the option used by `oddbird/MetaDeploy` [here](https://github.com/oddbird/MetaDeploy/blob/main/.github/workflows/upgrade-deps.yml#L20), and they seem pretty happy about it (they wrote a nice blog post about their automated PRs for uprading dependencies [here](https://www.oddbird.net/2022/06/01/dependabot-single-pull-request/).)

stubsabot: use an ssh-key when checking out typeshed

---

tests/mypy_test.py

I think we used to use this variable in a previous version of this script, but it's now unused.

`mypy_test.py`: Remove unused `seen` variable/parameters

---

scripts/stubsabot.py

stubsabot: add some debug logs

---

scripts/stubsabot.py

Currently, if there are no non-stubsabot commits on a stubsabot branch associated with an open PR, stubsabot will force-push to that branch on a daily basis to update the PR.
This PR proposes tweaking that logic so that stubsabot will only update the PR branch if it would change the diff between the PR and master.

stubsabot: only update existing branches if the diff relative to `master` would be different

---

stdlib/asyncio/tasks.pyi

Discovered while working on https://github.com/python/mypy/pull/13831
Mypy does also complain about the covariance introduced in #8781.
To reproduce a simple test case from mypy
```py
from asyncio import Future, wait
from typing import List
async def foo() -> None:
f = []  # type: List[Future[None]]
await wait(f)
```
```
mypy --no-silence-site-packages test.py
```
```
mypy/typeshed/stdlib/asyncio/tasks.pyi:273: error: Variance of TypeVar "_T_co" incompatible with variance in parent type  [type-var]
```
/CC: @hauntsaninja

Use general type ignore for asyncio.Task

---

stubs/pep8-naming/pep8ext_naming.pyi

I am using these two methods in: https://github.com/wemake-services/wemake-python-styleguide/blob/534008bb26577ebad9da6cbbf2b15cdc42c6ecb9/wemake_python_styleguide/transformations/ast_tree.py#L25
Source: https://github.com/PyCQA/pep8-naming/blob/b3492eeede12a26d35c0ee9e6b9c37a7e5484bf6/src/pep8ext_naming.py#L195-L242

Add two more methods to `pep8-naming` stub

---

.github/workflows/mypy_primer.yml
.github/workflows/mypy_primer_comment.yml

Several changes:
1. Now old `mypy_primer` builds are auto-canceled on new commits
2. `mypy_primer_comment` is only executed if `mypy_primer` succeeded
3. `pre-commit.ci` can run `mypy_primer` now, because it cancels the previous build
4. I moved `permissions` on the top level for better visibility
Docs: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-a-workflow-based-on-the-conclusion-of-another-workflow
Refs https://github.com/python/mypy/pull/13846
CC @hauntsaninja

Cancel old `mypy_primer` builds 

---

stubs/Pillow/PIL/Image.pyi

`_decompression_bomb_check()` explicitly checks for `None` and handles it as "unlimited".

Allow PIL.Image.MAX_IMAGE_PIXELS to be None

---

scripts/create_baseline_stubs.py
scripts/runtests.py
scripts/stubsabot.py
stubs/requests/@tests/test_cases/check_post.py
tests/check_consistent.py
tests/check_new_syntax.py
tests/mypy_test.py
tests/stubtest_third_party.py
tests/utils.py

See https://peps.python.org/pep-0597/
This also happened to me on Windows in #8879 because of mathematical unicode characters as part of the comments:
```py
(.venv) PS C:\Users\Avasam\Documents\Git\typeshed> python .\tests\check_new_syntax.py
File "C:\Users\Avasam\Documents\Git\typeshed\tests\check_new_syntax.py", line 110, in <module>
main()
File "C:\Users\Avasam\Documents\Git\typeshed\tests\check_new_syntax.py", line 100, in main
stub = f.read()
File "C:\Program Files\Python39\lib\encodings\cp1252.py", line 23, in decode 
return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 176166: 
character maps to <undefined>
```
There are linters to catch this, namely [pylint …

Specify file encoding

---

stdlib/subprocess.pyi

See https://github.com/python/cpython/pull/97685
The union type should be acceptable given https://github.com/python/cpython/issues/87597#issuecomment-1207402415. In general I'd like us to be able to type this, since these being bytes can be surprising if you pass text=True, but we'll see what mypy_primer says

subprocess: use narrower types for TimeoutExpired.std*

---

scripts/create_baseline_stubs.py
scripts/runtests.py

1. Stop the script early if the path doesn't exist (case insensitive).
2. The check for the pyright config was case sensitive, it is no longer.
3. Fixed some typos.

Fix issues with finding stubs in scripts/runtest

---

CONTRIBUTING.md

I think that `# incomplete` comment is no longer needed.
Plus, I removed all of them in the recent PR :)

Fix `incomplete` stubs wording in `CONTRIBUTING.md`

---

stubs/SQLAlchemy/METADATA.toml
stubs/SQLAlchemy/sqlalchemy/dialects/postgresql/ext.pyi

And pin `SQLAlchemy` to a micro version, so that it stops breaking typeshed's CI every other week.
Fixes #8909.

Fix stubtest failures on `SQLAlchemy`

---

stdlib/typing.pyi

#8726 proposed to make these properties abstract, but it would have broken half the typed-Python ecosystem, and we've since decided that it's not worth taking action on this (https://github.com/python/typeshed/issues/2146#event-7450564547). This PR rephrases the comments to make clear that there isn't really anything actionable that can be done here.

`typing.pyi`: Improve comments for `IO`/`TextIO`

---

stubs/atomicwrites/METADATA.toml

[`atomicwrites`](https://github.com/untitaker/python-atomicwrites) is a package that's only really useful for Python 2/3 compatibility. It's now deprecated, archived, and unmaintained. Prior to #8883 a few days ago, marking the stubs as complete, the typeshed stubs hadn't received any significant updates for several years.
I propose we mark the stubs as no longer updated, and then remove them.

Mark `atomicwrites` as no longer updated

---

stubs/pywin32/METADATA.toml
stubs/pywin32/win32comext/adsi/adsi.pyi
stubs/pywin32/win32comext/authorization/authorization.pyi
stubs/pywin32/win32comext/axcontrol/axcontrol.pyi
stubs/pywin32/win32comext/axdebug/axdebug.pyi
stubs/pywin32/win32comext/axscript/axscript.pyi
stubs/pywin32/win32comext/bits/bits.pyi
stubs/pywin32/win32comext/directsound/directsound.pyi
stubs/pywin32/win32comext/ifilter/ifilter.pyi
stubs/pywin32/win32comext/mapi/exchange.pyi
stubs/pywin32/win32comext/mapi/mapi.pyi
stubs/pywin32/win32comext/propsys/propsys.pyi
stubs/pywin32/win32comext/shell/shell.pyi
stubs/pywin32/win32comext/taskscheduler/taskscheduler.pyi

pywin32: Remove IID that doesn't exist at runtime

---

tests/stubtest_stdlib.py

I like to be extra careful about statements in `try` body.
If it cannot raise an exception we are looking for - it is better to move it out.

`print` cannot raise `subprocess.CalledProcessError`

---

stubs/python-crontab/@tests/stubtest_allowlist.txt
stubs/python-crontab/METADATA.toml
stubs/python-crontab/cronlog.pyi

It was just added in https://github.com/python/typeshed/pull/8917

Mark `python-crontab` as completed

---

.github/workflows/daily.yml
.github/workflows/stubtest_stdlib.yml

The stdlib stubtest run has started to fail on `master` (e.g. https://github.com/python/typeshed/actions/runs/3289534785/jobs/5421187095#step:6:250), due to `macos-latest` starting to default to macOS-12 in CI (https://github.com/actions/runner-images/issues/6384). `tkinter` doesn't seem to import on macOS 12, so pin to macOS-11 for now.

CI: Use macOS-11 for stdlib stubtest

---

scripts/generate_proto_stubs.sh
stubs/protobuf/METADATA.toml
stubs/protobuf/google/protobuf/descriptor_pb2.pyi
stubs/protobuf/google/protobuf/empty_pb2.pyi

Bumping rev of mypy-protobuf incoming next
This change is fairly minor - just some comment changes in the generated stubs.

Bump the rev of protobuf supported to 4.21.8

---

stubs/invoke/@tests/test_cases/check_task.py
stubs/invoke/invoke/tasks.pyi

Refs #8936.
This implements @Akuli's suggested idea in https://github.com/python/typeshed/issues/8936#issuecomment-1285748131. I've added a test case (@kasium's snippet in https://github.com/python/typeshed/issues/8936#issue-1416013788), which fails without this change.
@kasium, are you able to do any additional testing of this PR, to check that this doesn't have any unintended side effects?

Fix `invoke` regression

---

stdlib/datetime.pyi

`datetime.timedelta`: Remove explicit inheritance from `SupportsAbs`

---

stdlib/builtins.pyi
stdlib/typing.pyi
test_cases/stdlib/typing/check_aliases.py

See https://github.com/python/cpython/blob/ad1dc3ebb6aadaeeeacde13d4ed2d62bf302bf62/Lib/_collections_abc.py#L431﻿

`Collection` is `Sized`

---

stubs/protobuf/@tests/stubtest_allowlist.txt
stubs/protobuf/google/protobuf/descriptor.pyi

`google.protobuf.descriptor.Descriptor` was missing a type hint for its `__init__` function. 
This causes `typing` to look at its parent, `_NestedDescriptorBase`'s `__init__` function, which requires a different set of arguments and causes failures.

google.protobuf: Add an __init__ stub to fix type checking

---

stdlib/_posixsubprocess.pyi

Based on the code on CPython's 3.11 branch. This is an internal module
and frequently gets new parameters, so keeping it precise and up to
date is probably not high value.

_posixsubprocess: improve types

---

stdlib/json/__init__.pyi

`dumps` and `detect_encoding` support `bytearray`:
```python
>>> import json
>>> json.loads(bytearray(b'false'))
False
>>> json.detect_encoding(bytearray(b''))
'utf-8'
```
But, not `memoryview`:
```python
>>> json.loads(memoryview(b'false'))
File "/Users/sobolev/.pyenv/versions/3.10.0/lib/python3.10/json/__init__.py", line 339, in loads
raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not memoryview
```

json: improve bytes handling

---

stdlib/plistlib.pyi

```python
>>> import plistlib
>>> plistlib.dumps(bytearray())
b'<?xml version="1.0" encoding="UTF-8"?>\n<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n<plist version="1.0">\n<data>\n</data>\n</plist>\n'
>>> plistlib.dumps(memoryview(b''))
File "/Users/sobolev/.pyenv/versions/3.10.0/lib/python3.10/plistlib.py", line 901, in dumps
dump(value, fp, fmt=fmt, skipkeys=skipkeys, sort_keys=sort_keys)
File "/Users/sobolev/.pyenv/versions/3.10.0/lib/python3.10/plistlib.py", line 894, in dump
writer.write(value)
File "/Users/sobolev/.pyenv/versions/3.10.0/lib/python3.10/plistlib.py", line 325, in write
self.write_value(value)
File …
```

plistlib: improve bytes handling

---

.github/workflows/tests.yml
requirements-tests.txt

Fixes #9067 (I've run CI several times on my fork, to check)

Bump various test dependencies; pin Python to <3.11 in CI to workaround pytype incompatibility

---

.flake8
.pre-commit-config.yaml
requirements-tests.txt

flake8-bugbear now has 2 checks that cause a lot of false positives for stubs, but don't have any true positives: B024 and B027. But actually, none of flake8-bugbear's checks are really relevant for stub files. Keep it in CI for linting our scripts, but just ignore it for our stubs.

Bump flake8-bugbear; ignore flake8-bugbear in stub files

---

stdlib/http/server.pyi

The stub currently implies that the index_pages parameter has been removed in 3.12. Actually, it was only added in 3.12 :)
See https://github.com/python/cpython/pull/31985. (This is a follow-up to https://github.com/python/typeshed/pull/9055 — cc. @JelleZijlstra.)

http.server.SimpleHTTPRequestHandler: Fix version branching

---

stdlib/unittest/case.pyi

```pycon
>>> from unittest.case import TestCase
>>> c = TestCase()
>>> with c.assertRaisesRegex(Exception, b"x"): 1/0
...
ZeroDivisionError: division by zero
During handling of the above exception, another exception occurred:
File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 274, in __exit__
if not expected_regex.search(str(exc_value)):
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot use a bytes pattern on a string-like object
```

unittest: cannot use bytes regexes

---

pyrightconfig.stricter.json

Looks like I've missed it in https://github.com/python/typeshed/commit/10f05d3fb60c4972f91fbb098f7cbe32d5d190a8

Remove `aiofiles/aiofiles/threadpool/utils.pyi` from pyright exclude

---

scripts/stubsabot.py

Fixes a bug in #8681. The logic currently is broken; there should have been a warning message in the PR body for #9118, but there wasn't.

stubsabot: warn if stubtest is skipped in CI (for real this time)

---

.github/workflows/daily.yml

I've missed it in https://github.com/python/typeshed/pull/9132

Do not run `create-issue-on-failure` on PRs

---

stdlib/builtins.pyi

```pycon
>>> class Foo: ...
...
>>> vars(Foo)
mappingproxy({'__module__': '__main__', '__dict__': <attribute '__dict__' of 'Foo' objects>, '__weakref__': <attribute '__weakref__' of 'Foo' objects>, '__doc__': None})
```

Improve `builtins.vars()`

---

tests/regr_test.py

It used to be:
```
-p [{3.11,3.10,3.9,3.8,3.7} ...], --python-version [{3.11,3.10,3.9,3.8,3.7} ...]
Run mypy for certain Python versions (defaults to
sys.version_info[:2])Note that this cannot be specified if
--all is also specified.
```

`regr_test.py`: fix typo in `--help`

---

stdlib/inspect.pyi

Change `Attribute.kind` to literal as `inspect.classify_class_attrs` docstring said.

inspect: improve `Attribute.kind` to literal type

---

tests/stubtest_allowlists/darwin.txt
tests/stubtest_allowlists/linux.txt
tests/stubtest_allowlists/py3_common.txt

These modules don't exist on Windows

Stubtest: Don't allowlist `termios` and `posix` constants on Windows

---

stdlib/termios.pyi

I just got the list in termios.c of all constants that can potentially exist.

termios: improve comments, add more constants

---

.github/workflows/stubtest_third_party.yml

Testing the CI after https://github.com/python/typeshed/actions/runs/3445520575/jobs/5749332275

Fix CI failure when no third-party stubs were updated

---

stubs/paramiko/@tests/stubtest_allowlist.txt
stubs/paramiko/@tests/stubtest_allowlist_darwin.txt
stubs/paramiko/@tests/stubtest_allowlist_linux.txt
stubs/paramiko/@tests/stubtest_allowlist_win32.txt
stubs/paramiko/METADATA.toml

Thanks to #8923 , I was able to fix running stubtest on Windows for paramiko.
I did not add `darwin` to `platforms` because it would be redundant with `linux`. But I still added a `stubtest_allowlist_darwin.txt` for those who would like to run it locally on macos. (This is the edge case mentioned in #9173 )

Fix paramiko stubtest on Windows

---

stubs/ldap3/ldap3/core/server.pyi

`AF_UNIX` seems like an incidental re-export from `socket` (source: https://github.com/cannatag/ldap3/blob/dev/ldap3/core/server.py#L47). Some implementation detail is also hidden behind `socket`. Meaning that stubtest for this stub should be the same on all platforms.

Make the `ldap3` stubs platform-agnostic

---

stdlib/_decimal.pyi

Source code: https://github.com/python/cpython/blob/db115682bd639a2642c617f0b7d5b30cd7d7f472/Lib/_pydecimal.py#L1049-L1053
Closes #9191

`DecimalTuple` can have string exponent

---

stubs/keyboard/METADATA.toml
stubs/tzlocal/@tests/stubtest_allowlist.txt
stubs/tzlocal/tzlocal/windows_tz.pyi

Added comments explaining:
- Why `tzlocal.unix`, and `tzlocal.win32` have no stub files and  `tzlocal` doesn't require running stubtest on multiple platforms (it's implementation details, the final exposed types are the same)
- Why we stub `tzlocal/windows_tz.pyi` despite being autogenerated implementation details
- Why we don't need to run `keyboard` on multiple OS despite having platform-specific elements in its stub
The keyboard comment probably doesn't need to be that verbose.
And whit this, there's only a single stub with platform-specific code left to do: `requests`. The only platform difference is the following. Is it worth?
```py
if sys.platform == "win32":
def proxy_bypass_registry(host: str) -> bool: ...
def proxy_bypass(host: str) -> bool: ...
```

Comments explaining why `keyboard` and `tzlocal` are not run on multiple platforms

---

.github/workflows/daily.yml

Since now `daily` CI jobs can be executed on PRs, I think we need to cancel old builds on new commits. This will be in line with other CI workflows.
`cron` and `workflow_dispatch` triggers are not affected by this, because they usually don't have parallel execution. (Technically sequential `workflow_dispatch` actions will be canceled as well, but I think this is also a good thing).

Cancel old `daily` CI jobs on PRs

---

.pre-commit-config.yaml
CONTRIBUTING.md
pyproject.toml
requirements-tests.txt

- Bump mypy to 0.991
- Bump pytype to 2022.11.10
- Bump pycln to 2.1.2
- Enable the new `disable_all_dunder_policy` flag for pycln.
This flag means that pycln treats `__init__.py(i)` files just like normal `.py(i)` files. By default, pycln is much more cautious when removing imports from `__init__.py(i)` files due to the fact that many projects use "redundant" imports in `__init__.py` files for implicit reexports. But it doesn't make sense for pycln to apply the same level of caution to `__init__.pyi` files in stubs, where all imports are "private to the stub" except imports using the `import foo as foo` idiom. So it makes sense to enable this flag for typeshed.
- Put all pycln config in the `pyproject.toml` file instead of hardcoding it into the `.pre-commit-config.yaml` file.

Bump test dependencies; improve `pycln` config

---

stubs/urllib3/urllib3/util/url.pyi

I maintain urllib3 and can confirm the [port is an int](https://github.com/urllib3/urllib3/blob/8b8e4b5a148d0eb706daf5ac48b4423b434495f5/src/urllib3/util/url.py#L381).
Thankfully, the upcoming 2.0 release is fully type annotated!

Fix urllib3 Url.port type

---

stubs/pyaudio/@tests/stubtest_allowlist.txt
stubs/pyaudio/METADATA.toml
stubs/pyaudio/pyaudio.pyi

Split off from #9187
Turned off `ignore_missing_stub` for pyaudio stubs.
Ensured it's valid for Windows and MacOS.

Add missing symbols in `pyaudio` stubs

---

stdlib/asyncio/base_events.pyi
stdlib/asyncio/events.pyi

- Change the return type of create_connection, start_tls, connect_accepted_socket, create_unix_connection to Transport rather than BaseTransport (closes #9199).
- Change the return type of create_datagram_endpoint to DatagramTransport rather than BaseTransport.
- Change the argument of sendfile to WriteTransport rather than BaseTransport.
I considered also changing the argument of start_tls to Transport, but I think that will give false positives for code that implements a custom transport class that inherits from both ReadTransport and WriteTransport but not from Transport, and I'm not sure if typing has a way to express an intersection of types. Since users are not normally expected to implement transports that may be overthinking things.

Refine types for asyncio transports

---

stubs/python-dateutil/dateutil/parser/__init__.pyi

Sorry, @JelleZijlstra for taking this over, but I had a similar task: converting `python-dateutil` to a completed package.
Source https://github.com/dateutil/dateutil/blob/322fa34bc5fafb2e1c725e97909bf490a9dec1c8/src/dateutil/parser/_parser.py
Closes https://github.com/python/typeshed/issues/9122

Add exact `**kwargs` types to `dateutil.parser.parse`

---

stubs/colorama/colorama/__init__.pyi

Added here: https://github.com/tartley/colorama/pull/352
Re-export can be seen here:
https://github.com/tartley/colorama/blob/21c4b94fe21ce29c85c896ace828da24b7527641/colorama/__init__.py#L2
I don't know why all the exports are "X as X" instead of just "X", but I followed the same style for consistency.

colorama: re-export just_fix_windows_console at top level

---

test_cases/README.md
tests/regr_test.py

It's currently impossible to add a test case for `ExceptionGroup` or `BaseExceptionGroup`: see #9230. You'd think that you'd be able to just put the test behind an `if sys.version_info >= (3, 11)` guard, and pyright is indeed fine with that. Mypy, however, is not: when you run the test case with `--python-version 3.10`, it complains about many "unused type ignore" comments (it detects the `type: ignore` comments behind the `if sys.version_info >= (3, 11)` guard, even though it considers the whole block unreachable with `--python-version 3.10`, meaning it considers all `type: ignore`s within that block to be "unused").
This PR works around that mypy annoyance. If this PR is merged, the test-case file can simply be renamed to be `test_cases/stdlib/builtins/check_exception_group-py311.py`, …

Allow adding test cases testing version-dependent Python features

---

stubs/redis/METADATA.toml

We're about to get a daily test failure with 63 stubtest errors (see the Ubuntu stubtest failure in #9187) due to the release of redis-py 4.3.5, and I'd rather that didn't happen.

Pin `redis` to 4.3.4 in CI

---

stubs/tqdm/tqdm/std.pyi

I'm not entirely sure why this was not caught before as the class variable has been there since 2016.

tqdm: Add missing tqdm.monitor class variable

---

stubs/pynput/@tests/stubtest_allowlist.txt
stubs/pynput/@tests/stubtest_allowlist_linux.txt
stubs/pynput/@tests/stubtest_allowlist_win32.txt
stubs/pynput/METADATA.toml
stubs/pynput/pynput/keyboard/_base.pyi
stubs/pynput/pynput/mouse/_base.pyi

Source: https://github.com/moses-palmer/pynput/tree/master/lib/pynput/_util

Mark pynput as completed

---

test_cases/README.md

Otherwise, pyright won't work correctly.

Add a note that `if sys.version_info` is still required in test_cases

---

pyrightconfig.json

As far as I understand `stubs/cryptography` are outdated.
We ignore it in our `stubtest` runs, but not in our `pyright` runs.
I think these stubs should be ignored for now. And removed later on.
Refs
- https://github.com/python/typeshed/issues/5618
- https://github.com/python/typeshed/issues/9127

Exclude `stubs/cryptoghraphy` from CI to fix pyright

---

stubs/regex/regex/regex.pyi

There are two type stubs for `Scanner` in the regex module:
- `regex._regex.Scanner`
- `regex._regex_core.Scanner`
Currently, the typeshed stubs for `regex` use `regex._regex_core.Scanner`, but it should be `regex._regex.Scanner`.
This can be seen by inspecting the properties of the returned objects of the `regex` runtime:
```python
>>> import regex
>>> dir(regex.compile(".*").finditer("foo"))
[..., '__iter__', '__next__', 'match', 'pattern', 'search']
>>> dir(regex.compile(".*").scanner("foo"))
[..., '__iter__', '__next__', 'match', 'pattern', 'search']
>>> dir(regex.finditer(".*", "foo"))
[..., '__iter__', '__next__', 'match', 'pattern', 'search']
```
---
This PR is the minimal change to make mypy happy with, e.g.
```python
import regex
rx = regex.compile("foo|bar")
matches = …
```

regex: fix type signatures using Scanner

---

stubs/regex/@tests/test_cases/check_finditer.py

As @sobolevn says, the fact that there are two `Scanner` classes in the `regex` package is pretty confusing. Let's add a test case to ensure that #9263 doesn't happen again.

Add test case for recent `types-regex` regression

---

tests/check_consistent.py
tests/get_packages.py
tests/utils.py

I've missed this during review, good ideas always come late.
Right now we can install deps if they are specified for any platform.
Even if it is not tested. This can consume time of workers and lead to errors.
This PR allows:
```toml
platforms = ["linux", "win32"]
apt_dependencies = ["one"]
```
```toml
platforms = ["linux", "win32"]
brew_dependencies = []
```
(I can remove ^ this)
But not:
```toml
platforms = ["linux", "win32"]
brew_dependencies = ["some"]
```
Refs https://github.com/python/typeshed/pull/9187

check_consistent.py: Add check ensuring packages are not installed for unspecified platforms

---

.github/workflows/tests.yml
tests/regr_test.py

As the number of third-party stubs with test cases grows, the output in CI is getting kind of noisy (e.g. https://github.com/python/typeshed/actions/runs/3547587578/jobs/5957872274). Add a `--quiet` option, and use it in CI, to limit the amount of stuff that's printed to the terminal.
Also add slightly better error handling in a few places. Lastly, add the `--pretty` flag when running mypy, so it's easy to see where the errors are, if there are any.

Minor improvements to `tests/regr_test.py`

---

tests/pytype_test.py

A simple improvement to make errors more readable
Before (hard to know when a new error starts):
After:

Space out pytype errors

---

stubs/passlib/@tests/stubtest_allowlist.txt
stubs/passlib/METADATA.toml
stubs/passlib/passlib/handlers/digests.pyi
stubs/passlib/passlib/handlers/misc.pyi

I wanted to propose `__all__` fixes to the upstream project, but it is hosted on some strange GitLab fork: https://foss.heptapod.net/python-libs/passlib
I don't want to register there, sorry :(
Related https://github.com/python/mypy/pull/14217

Mark `passlib` as completed

---

stubs/Pillow/PIL/Image.pyi

This option is covered in https://github.com/python-pillow/Pillow/blob/6a2545f628b13bc4888f687c1028482fc93fafcf/docs/handbook/tutorial.rst#batch-processing
but it is pulled out of the `**params` by the `jpeg` plugin (and probably others as well)
example usage:
```python
im.save(path, optimize=True)
```
rel: https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html#jpeg-saving

PIL: add optimize param to save

---

stubs/Pillow/PIL/Image.pyi

Hello,
The `PIL.Image.Image.convert` method should accept `Palette.WEB` or `Palette.ADAPTIVE` as possible values for the `palette` parameter.

PIL: fix image convert palette type

---

stdlib/types.pyi

According to Python [doc](https://docs.python.org/3/library/typing.html#typing.Generator), type parameters for `Generator` should be `Generator[YieldType, SendType, ReturnType]`
An example of wrong diagnostics emitted by a downstream type checker: https://github.com/microsoft/pylance-release/issues/3716

types: fix signature of coroutine

---

.github/workflows/mypy_primer.yml

We can be fairly confident that PRs updating only a `METADATA.toml` file will never produce an interesting `mypy_primer` diff.

Don't run `mypy_primer` on stubsabot PRs

---

stdlib/builtins.pyi
stdlib/typing.pyi
test_cases/stdlib/typing/check_regression_issue_9296.py

As per discussion in #9296, this PR reverts the commits in #8977 and #9058 that resulted in false positive errors when e.g. calling register() on a KeysView subclass, until a non-buggy implementation is landed. This also adds a regression test.

Fix issue #9296 (calling register on KeysView subclass causes false positive error)

---

test_cases/stdlib/typing/check_regression_issue_9296.py
tests/regr_test.py

`regr_test.py`: improve interaction between `--all` and `--quiet` flags

---

stdlib/_ast.pyi

Closes #9287.
I also decided to type ast.Assign. The new hint for it is still less broad then `expr`

Improve typing for ast nodes which represent assignment behaviour

---

stdlib/zipfile.pyi

According to [docs](https://docs.python.org/3/library/zipfile.html?highlight=zipfile#zipfile.ZipFile):
> compression is the ZIP compression method to use when writing the archive, and should be [ZIP_STORED](https://docs.python.org/3/library/zipfile.html?highlight=zipfile#zipfile.ZIP_STORED), [ZIP_DEFLATED](https://docs.python.org/3/library/zipfile.html?highlight=zipfile#zipfile.ZIP_DEFLATED), [ZIP_BZIP2](https://docs.python.org/3/library/zipfile.html?highlight=zipfile#zipfile.ZIP_BZIP2) or [ZIP_LZMA](https://docs.python.org/3/library/zipfile.html?highlight=zipfile#zipfile.ZIP_LZMA); unrecognized values will cause [NotImplementedError](https://docs.python.org/3/library/exceptions.html#NotImplementedError) to be raised.
`Literal` could be used for the `compresslevel` parameter as well:
> …

Use `Literal` for `compression` in `zipfile`

---

.github/workflows/daily.yml
.github/workflows/stubtest_stdlib.yml

Python 3.10.9 and 3.11.1 were recently released. They have some differences to 3.10.8 and 3.11.0, which have been causing our stdlib stubtest to intermittently fail today:
- https://github.com/python/typeshed/actions/runs/3697681779/jobs/6262969113
- https://github.com/python/typeshed/actions/runs/3693960198/jobs/6254570009
Pin Python to 3.10.8 and 3.11.0 in CI for now, until we can rely on GitHub runners picking up 3.10.9 and 3.11.1 when "3.10" and "3.11" are specified.

Stdlib stubtest: Temporarily pin Python to 3.10.8 and 3.11.0 in CI

---

stdlib/shutil.pyi
tests/stubtest_allowlists/py3_common.txt

shutil.rmtree: add avoids_symlink_attacks attribute

---

stdlib/zipfile.pyi

This reverts commit 034cfab4d6b25b2d3da2fe72e6839a61b2bf5e2c.
The commit exposed the value of the compression constants, which seem to be implementation details, in the public API. I don't see anything in the documentation about the values of the constants such as `ZIP_STORED`:
https://docs.python.org/3/library/zipfile.html?highlight=zipfile#zipfile.ZipFile
Example where this makes a difference:
```
from typing import Literal
import zipfile
def f1(p: str, compression: int) -> None:
zipfile.ZipFile(p, compression=compression)
def f2(p: str, compression: Literal[0, 8, 12, 14]) -> None:
zipfile.ZipFile(p, compression=compression)
```
The integer values of named constants need to be explicitly specified if somebody wants to wrap `zipfipe.ZipFile`, which arguably exposes implementation details …

Revert "Use `Literal` for `compression` in `zipfile` (#9346)"

---

.github/workflows/daily.yml
.github/workflows/stubtest_stdlib.yml

Example of a failing run before: 
Example of a failing run after:

Colorize output of stdlib stubtest in CI

---

stubs/editdistance/@tests/stubtest_allowlist.txt
stubs/editdistance/editdistance/bycython.pyi

This submodule is undocumented and appears to just be an implementation detail of the fact that the package is cythonized. Deleting this file fixes a third-party stubtest failure seen in #9368 that will cause the daily test to fail this evening: https://github.com/python/typeshed/actions/runs/3725223267/jobs/6317896104

`editdistance`: delete the `bycython` submodule

---

stdlib/json/__init__.pyi

Instead of requiring `fp` be an object of type `IO[str]`, this weakens the annotation to only require `fp` be of type `SupportsWrite[str]`.
This is all [the documentation requires](https://docs.python.org/3/library/json.html#json.dump) and is all [the implementation requires](https://github.com/python/cpython/blob/3e715e0cc811ebccce4234c3e25ef30787151d00/Lib/json/__init__.py#L180).

Update `json.dump` to only require `fp: SupportsWrite[str]`

---

stubs/requests/requests/sessions.pyi

Resolves #9390.
The session.headers may be set to any mapping according to the project, and mutable mapping appears to be the most correct annotation.

set session.headers to MutableMapping

---

stdlib/json/encoder.pyi

Allow `indent` to be a `str`, as is the case for `json.dump` and `json.dumps`.

Allow `indent` to be ` str` in `JSONEncoder`

---

stdlib/builtins.pyi

Proof: https://github.com/python/cpython/blob/f10f503b24a35a43910a632ee50c7568bedd6664/Python/Python-ast.c#L12247-L12269
```python
>>> import ast
>>> compile(ast.Not(), 'test', 'exec')
TypeError: expected Module node, got Not
>>> compile(ast.Not(), 'test', 'eval')
TypeError: expected Expression node, got Not
>>> compile(ast.Not(), 'test', 'single')
TypeError: expected Interactive node, got Not
```
We can also have specific overloads later.

`compile` can only work with `ast.Module | ast.Expression | ast.Interactive`

---

.github/workflows/mypy_primer.yml

This was suggested by @Avasam in https://github.com/hauntsaninja/mypy_primer/issues/64, and by @Akuli in https://github.com/hauntsaninja/mypy_primer/issues/66. It could conceivably yield much more interesting diffs for some PRs. For example, `comtypes` makes heavy use of `pywin32`, so it shows up a lot in primer diffs for PRs affecting our `pywin32` stubs. But the diffs usually aren't very interesting, because the vast majority of `comtypes`'s functions are untyped, so mypy just ignores them.
I think this is worth experimenting with, and if it doesn't work for whatever reason, we can always revert it.

Use `--additional-flags='check-untyped-defs'` when running mypy_primer

---

scripts/runtests.py
tests/utils.py

`utils.colored`'s signature now correctly reflects `termcolor.colored`
Attempt in `scripts/runtests.py` to deduplicate the same fallback (using utils module in an outside folder).
~~I think the solution is fine, but you tell me.~~ VSCode can pick-up the source just fine, ~~mypy might need an extra `mypy_path="tests"` to remove `# type: ignore[import]` at line 13.~~
Edit: Apparently it wasn't a great solution (see comments below)

Accurate, deduplicated, `termcolor.colored` fallback

---

requirements-tests.txt

From the following comment: https://github.com/python/typeshed/pull/9434#discussion_r1059690783
> I think typing_extensions is only available here because mypy depends on it, and we have mypy in our requirements-tests.txt file. We should probably add it to requirements-tests.txt, since implicit dependencies are generally a bad idea, and we also need the dependency for e.g. stubtest_stdlib.py. Want to make another PR adding it to requirements-tests.txt?

Add typing-extensions to `requirements-tests.txt`

---

tests/regr_test.py
tests/typecheck_typeshed.py

- Remove redundant flags that are now enabled by default.
- Add `--pretty` to `typecheck_typeshed.py`.
`mypy_test.py` flags are being reworked in #9408.

Improve mypy flags for regr_test.py and typecheck_typeshed.py

---

CONTRIBUTING.md
tests/README.md

- Using bash by default, powershell for Windows-specific
- Added missing start-of-line markers
Please read https://github.com/python/typeshed/pull/9434#discussion_r1060189157 as for the motivation why, as well as why use `bash` specifically (mainly for semantic reasons)
As for using powershell for Windows-specific commands over cmd/batch:
- powershell is meant to [replace Command Prompt](https://support.microsoft.com/en-us/windows/powershell-is-replacing-command-prompt-fdb690cf-876c-d866-2124-21b6fb29a45f)
- is the default in Microsoft's own IDEs
<details>
<summary>Full explanation with examples (linked comment)</summary>
As far as https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L6204 is concerned, `shell`, `sh`, `shell-script`, `bash` and `zsh` are all the same, …

Add syntax highlight to all shell code blocks

---

.github/workflows/daily.yml
.github/workflows/mypy_primer.yml
.github/workflows/stubtest_stdlib.yml
.github/workflows/stubtest_third_party.yml
.github/workflows/tests.yml
.github/workflows/typecheck_typeshed_code.yml
.pre-commit-config.yaml
tests/check_consistent.py

A quick formatting run of YAML files for things like consistent single vs double quotes, spacing before comments and indentation.
Adds a pre-commit hook to autoformat YAML files. I don't have a strong opinion on which formatter to use for YAML.
<details>
<summary>Old PR description</summary>
Just a quick formatting run of YAML files. Consistent single vs double quotes, spacing before comments and indentation. I don't think there's an established preference for YAML style so I let [redhat.vscode-yaml](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml) use its default settings.
I'm open to suggestions for a formatter to add to pre-commit. (vscode-yaml itself uses prettier, which I'm not a great fan of personally, at least in JS environments where I prefer …

Autoformat YAML files

---

.github/workflows/mypy_primer.yml

Reverts python/typeshed#9433.
I think 15+ minutes for `mypy_primer` is too long. The slowdown seems primarily caused by `manticore` (see #9443), and we don't want to skip `mypy_primer` on `manticore` (https://github.com/python/typeshed/pull/9433#issuecomment-1369375446). The performance situation may well be significantly improved when mypy 1.0 comes along, but that could still be a few weeks away. Let's revert #9433 for now so that we can have `mypy_primer` runs that are <10 minutes in the meantime.

Revert "Use `--additional-flags='check-untyped-defs'` when running mypy_primer"

---

stubs/setuptools/METADATA.toml
stubs/setuptools/setuptools/_distutils/command/check.pyi

Reference the docutils stub.
As far as I understand, there's no issue with this if docutils isn't installed. And gives proper type when it is.
Fixes 3 subclassing errors (the same error in setuptools, pyinstaller and Pygments stubs)

Fix Any subclassing in setuptools

---

README.md

- Added pyright mention in readme (since typeshed actively supports it and works with it)
- Add links to help navigate away readers looking for type-checkers
- Add missing code-block

Update actively supported type-checkers list in readme

---

.gitattributes
.gitignore
.vscode/extensions.json
.vscode/settings.default.json

Offer sensible default VSCode settings.
These are the workspace settings, specific to typeshed, that I've been using and filling in over the past few months.
Workspace settings override user settings, so we can offer sensible, all-ready configurations for the typeshed workspace, reducing a lot of the pains a new contributor can have if their favorite editor is VSCode.
These settings obviously won't configure any extension not specified in `.vscode/extensions.json > recommendations`, and will assume the user may not have all recommended extensions installed or set as the formatter. Hence I've also configure some basic VSCode settings.
---
The recommended extensions include:
- The full python extensions suite needed for typeshed
- `.editorconfig` support and syntax highlighter
- A yaml …

Offer sensible default VSCode settings

---

stdlib/_typeshed/__init__.pyi

Closes #9297 and see https://github.com/python/typeshed/pull/9470#discussion_r1063745593
I found myself using a `_Unused` TypeAlias a lot for semantic reasons.
Of course they can't be used everywhere until the next mypy update.

Add `FileDescriptorOrPath` and `Unused` type aliases

---

tests/mypy_test.py

This is a cleanup PR, removing logic from `mypy_test.py` that's no longer necessary.
This logic was introduced in #8800 to ensure that running e.g. `python tests/mypy_test.py stubs/caldav` locally would work, fixing #8797. However, following #8360 (for which the logic was reworked somewhat in #9408), we now add typeshed dependencies of a stubs package to `MYPYPATH` when testing that stubs package. That means this logic is no longer necessary; `python tests/mypy_test.py stubs/caldav` still works fine when run locally with this logic removed. If you want to see exactly which directories are being added to `MYPYPATH`, you can run `python tests/mypy_test.py stubs/caldav --verbose --verbose` for a detailed log to the terminal.

`mypy_test.py`: Simplify `add_third_party_files()`

---

stdlib/compileall.pyi

See https://github.com/python/cpython/pull/19883

Update compileall stripdir type

---

stubs/pyinstaller/PyInstaller/utils/hooks/conda.pyi

This one was easy to fix without having to resort to external requires. Plus it's Python 3.7 only
Ref: #9491

Fix Any subclassing in pyinstaller

---

.flake8

https://github.com/python/typeshed/issues/8988 based on this discussion simple default values seem to be fine to allow now. Y011 is default value rule for function arguments. Y015 is default attribute rule for things like Enums/class constants. There's also Y014 a variation of Y011 that I'm neutral on.

Allow default values in stubs.

---

stdlib/urllib/parse.pyi

The runtime defaults are None. Found in #9501.

urllib.parse.urlencode: encoding and errors can be None

---

stdlib/venv/__init__.pyi

Not particularly useful but unreleased stubtest will require this:
https://github.com/python/typeshed/actions/runs/3898630022/jobs/6657546205

venv: add logger

---

.github/workflows/tests.yml
tests/mypy_test.py
tests/utils.py

Currently, if a stubs package declares a dependency on `numpy`, the latest version of `numpy` will be installed in CI when testing that package. However, the CI will then fail, because mypy will detect that `numpy` is using PEP-570 syntax, and accordingly will emit errors when run with the `--python-version=3.7` flag, since PEP 570 is new in Python 3.8.
The solution is to actually run mypy _on_ 3.7 in CI, rather than simply running mypy with the `--python-version=3.7` flag. If we run mypy _on_ 3.7, pip's dependency resolver will understand that the latest version of `numpy` isn't compatible with the version of Python we're using, and will give us an older version of `numpy` that's compatible with Python 3.7.
A few tweaks to `tests/mypy_test.py` and `tests/utils.py` are required in order …

Allow stubs to depend on `numpy`

---

.github/workflows/daily.yml
.github/workflows/stubtest_stdlib.yml
.github/workflows/tests.yml
requirements-tests.txt

From https://github.com/python/typeshed/pull/8974#discussion_r1067873831
Use of environment marker to indicate that a dependency isn't usable with Python 3.7
- More obvious than grepping
- Reduces duplication
- Keeps the CI the same as others
- Works locally
- pip will event log why it's not installing flake8

Use environment marker to restrict flake8 install

---

tests/stubtest_third_party.py

Currently, if we're running stubtest on our stubs for `caldav`, we `pip install` all the requirements for `types-caldav` into the virtual environment before running the test. However, for typeshed-internal requirements, this is unnecessary: we can add the typeshed-internal requirements for `caldav` to MYPYPATH instead. This has two advantages:
- `pip install`ing stuff is slow; this should be faster. Some of our stubs have a lot of internal dependencies: when testing `caldav`, we currently have to `pip install` `types-requests`, `types-urllib3` and `types-vobject`.
- Currently it's impossible to e.g. add two stubs packages in one pull request, with one depending on the other. Instead, you have to add stubs package A, wait for the stub-uploader to push the new stubs to PyPI, and then add …

3rd-party stubtest: use MYPYPATH for internal dependencies

---

stubs/setuptools/@tests/stubtest_allowlist.txt
stubs/setuptools/setuptools/msvc.pyi

I'm fairly certain that's just a shim for implementation details.
Fixes stubtest on windows. Stub on windows and linux should be equivalent now.

Fix setuptools stubtest on windows

---

stubs/Pillow/@tests/stubtest_allowlist.txt
stubs/keyboard/@tests/stubtest_allowlist.txt
stubs/keyboard/@tests/stubtest_allowlist_darwin.txt
stubs/keyboard/@tests/stubtest_allowlist_linux.txt
stubs/pywin32/@tests/stubtest_allowlist_win32.txt
stubs/tree-sitter-languages/@tests/stubtest_allowlist.txt
stubs/tree-sitter-languages/@tests/stubtest_allowlist_darwin.txt
stubs/tree-sitter-languages/@tests/stubtest_allowlist_linux.txt

Batch of changes in allowlist entries (no stub change) to fix some third party stubtest runs on windows.

Allowlist-only fixes for stubtest windows

---

stubs/fpdf2/METADATA.toml

They will need some updates to become compatible with `fpdf2` 2.6.1.
Closes #9524

Pin `fpdf2` stubs to 2.6.0

---

stubs/tensorflow/METADATA.toml
stubs/tensorflow/tensorflow/__init__.pyi

Fixes stubtest failure in [stubsabot](https://github.com/python/typeshed/pull/9539).

Update tensorflow to 2.11

---

stubs/python-xlib/Xlib/display.pyi

Refs https://github.com/PyCQA/flake8-pyi/pull/324

`Xlib`: Import `Pattern` from `re`, not `typing`

---

.flake8
.pre-commit-config.yaml
requirements-tests.txt
stdlib/_collections_abc.pyi
stdlib/array.pyi
stdlib/builtins.pyi
stdlib/types.pyi
stdlib/typing_extensions.pyi
tests/utils.py

- Bump `packaging` to 23.0
- Bump `flake-pyi` to 23.1.0, which I just released. This requires changing a few `# noqa` codes. It will also mean that we can reenable Y011 and Y015, but we can do that in another PR.
- Bump `pycln` to 2.1.3. Thanks to @Avasam's recent PR https://github.com/hadialqattan/pycln/pull/186, this means we can use the latest version of `pathspec`, which includes inline types, thus meaning we can get rid of a few `type: ignore` comments in our test suite!

Bump various test dependencies

---

tests/mypy_test.py

Implements @srittau's idea in https://github.com/python/typeshed/issues/9537#issuecomment-1384096983, which seems worth a shot. Timings locally are the same as with using a threadpool for setting up the venvs.

`mypy_test.py`: Try using a process pool instead of a thread pool

---

stdlib/asyncio/base_events.pyi
stdlib/asyncio/events.pyi

Since python 3.7, [`asyncio.loop.create_datagram_endpoint`](https://docs.python.org/3.8/library/asyncio-eventloop.html#asyncio.loop.create_datagram_endpoint) expects the arguments `local_addr` and `remote_addr` to be `str` or `None` when the argument `family` is `socket.AF_UNIX` (and if when `sock` is not `None`, it is also a unix socket). Here is a link to the relevant line in the standard library: https://github.com/python/cpython/blob/main/Lib/asyncio/base_events.py#L1319
Here is a link to the pull request on the cpython repository which effected this change: https://github.com/python/cpython/pull/3164
i'm not at all sure if I've made the changes correctly. is there a way to represent the dependency on the `family` argument that i'm missing?

create_datagram_endpoint expects a str when family=AF_UNIX

---

stdlib/ssl.pyi

Python 3.10 added the property `security_level` which returns an `int` and is read-only.

Add SSLContext.security_level property for Python 3.10

---

stdlib/lib2to3/pygram.pyi
stubs/decorator/decorator.pyi
stubs/dockerfile-parse/dockerfile_parse/parser.pyi
stubs/playsound/playsound.pyi
stubs/pyinstaller/PyInstaller/__main__.pyi
stubs/pyinstaller/PyInstaller/utils/hooks/__init__.pyi
stubs/retry/retry/api.pyi
stubs/vobject/vobject/base.pyi

This adds some missing objects to various stdlib and third-party stubs. Stubtest doesn't complain about these now, but will do when mypy 1.0 is released; this should make upgrading to mypy 1.0 easier when that happens.

Fix some stubtest complaints before they happen

---

stubs/python-xlib/Xlib/xobject/resource.pyi

Xlib/xobject/resource.pyi declared a fake `_BaseDisplay` class, marked as `@type_check_only`, used as the type of `Resource.display` instance attribute and the associated `display` parameter `Resource.__init__()`. An in-code comment indicated the reason for the incorrect class typing:
> Workaround for pytype crash. Should be Xlib.display._BaseDisplay
However, the workaround causes issues with `mypy` in code performing comparisons between `Xlib.xobject.drawable.Window.display` (affected by the workaround) and `Xlib.display.Display.display` (using the original, correct class) objects:
> error: Non-overlapping identity check (left operand type: "Xlib.xobject.resource._BaseDisplay", right operand type: "Xlib.display._BaseDisplay")  [comparison-overlap]
Also, I could not reproduce the …

python-xlib: remove workaround for pytype
