requirements-tests.txt

Unblocks https://github.com/python/typeshed/pull/7279

Use flake8-pyi 22.2.0

---

stdlib/smtpd.pyi

smtpd: MailmanProxy was removed in 3.11

---

requirements-tests.txt

Upgrade pytype to 22.2.23

---

stubs/six/@tests/stubtest_allowlist.txt

Add six.create_bound_method dunders to allowlist

---

stdlib/threading.pyi

Add `threading._profile_hook` to `threading.pyi`

---

MAINTAINERS.md

Inactive maintainers policy

---

stubs/passlib/passlib/pwd.pyi

passlib: Fix MutableMapping import

---

stdlib/multiprocessing/process.pyi

https://github.com/python/cpython/blob/main/Lib/multiprocessing/process.py#L91

multiprocessing: args can be any Iterable

---

stubs/invoke/invoke/tasks.pyi

Fix wrong return type of invoke decorator

---

stdlib/asyncio/base_events.pyi
tests/stubtest_allowlists/py310.txt
tests/stubtest_allowlists/py39.txt

Add Server to asyncio.base_events' __all__

---

requirements-tests.txt

Use flake8-pyi 22.3.0

---

stubs/pyvmomi/pyVmomi/vmodl/__init__.pyi
stubs/pyvmomi/pyVmomi/vmodl/fault.pyi

Add some missing pyVmomi stubs. Not all, but some I'm missing

Update pyVmomi stubs

---

stdlib/asyncio/unix_events.pyi

Found downstream in mypy (https://github.com/python/mypy/pull/12495)

Fix source comment typo

---

.flake8

Unblocks https://github.com/PyCQA/flake8-pyi/pull/202

Exclude Y037 in `.flake8` config, for now

---

.github/workflows/daily.yml

Unpin Python micro versions

---

.github/workflows/daily.yml
.github/workflows/tests.yml

remove old comments about pinned Python versions

---

stdlib/typing.pyi
stdlib/typing_extensions.pyi

- get_overloads
- clear_overloads
- dataclass_transform updates

typing updates for 3.11

---

.github/workflows/tests.yml

This was the first step to figure out the issue in #7635. The stack trace was still pretty mysterious, but it helps more than just "AssertionError".

Run pytype test with --print-stderr

---

stdlib/_collections_abc.pyi
stdlib/array.pyi
stdlib/builtins.pyi
stdlib/types.pyi

Unblocks https://github.com/PyCQA/flake8-pyi/pull/213

Add a few `# noqa`s

---

stdlib/_collections_abc.pyi

Add one more `# noqa` to unblock PyCQA/flake8-pyi#213

---

stdlib/typing.pyi
stdlib/typing_extensions.pyi

typing: Add dataclass_transform

---

stdlib/_typeshed/__init__.pyi

Add PickleBuffer to _typeshed.WriteableBuffer

---

requirements-tests.txt

Upgrade to pytype 2022.4.26

---

stubs/croniter/METADATA.toml
stubs/croniter/croniter.pyi

Drop Python 2 support from croniter

---

.github/workflows/daily.yml
.github/workflows/tests.yml

As suggested by @hauntsaninja 
Also pin Ubuntu version when installing apt packages.

Run apt-get update before installing packages

---

stdlib/_socket.pyi

Add socket.TCP_CONNECTION_INFO

---

stdlib/types.pyi

Add `GenericAlias.__unpacked__`

---

stdlib/datetime.pyi

CPython PR Reference:  https://github.com/python/cpython/pull/91973

Add datetime.UTC alias

---

stubs/Flask-Cors/flask_cors/decorator.pyi

Per https://github.com/corydolphin/flask-cors/blob/79bb3721f72ff540ac2575e810f9bfd6c3380432/flask_cors/decorator.py#L29

flask-cors: add regex to decorator

---

stdlib/_socket.pyi
stdlib/socket.pyi

socket: add SO_INCOMING_CPU for 3.11

---

stdlib/sys.pyi

sys.flags: add safe_path for 3.11

---

.github/workflows/mypy_primer.yml

It now works even for third-party stubs. https://github.com/hauntsaninja/mypy_primer/pull/31

Run mypy_primer in all pull requests

---

stubs/SQLAlchemy/@tests/stubtest_allowlist.txt
stubs/SQLAlchemy/sqlalchemy/testing/engines.pyi

Update testing_engine() annotations

---

requirements-tests.txt

https://github.com/python/typeshed/pull/7680#issuecomment-1122887515

upgrade pytype

---

tests/stubtest_third_party.py

Help with debugging things like #7815

stubtest_third_party: show package versions on failure

---

stubs/redis/redis/__init__.pyi

https://github.com/redis/redis-py/blob/master/redis/__init__.py#L48-L54

Add version to redis

---

tests/stubtest_allowlists/darwin-py310.txt
tests/stubtest_allowlists/darwin-py36.txt
tests/stubtest_allowlists/darwin-py37.txt
tests/stubtest_allowlists/darwin-py38.txt
tests/stubtest_allowlists/darwin-py39.txt
tests/stubtest_allowlists/darwin.txt
tests/stubtest_allowlists/linux-py310.txt
tests/stubtest_allowlists/linux-py36.txt
tests/stubtest_allowlists/linux-py37.txt
tests/stubtest_allowlists/linux-py38.txt
tests/stubtest_allowlists/linux-py39.txt
tests/stubtest_allowlists/linux.txt
tests/stubtest_allowlists/py310.txt
tests/stubtest_allowlists/py311.txt
tests/stubtest_allowlists/py36.txt
tests/stubtest_allowlists/py37.txt
tests/stubtest_allowlists/py38.txt
tests/stubtest_allowlists/py39.txt
tests/stubtest_allowlists/py3_common.txt
tests/stubtest_allowlists/win32-py310.txt
tests/stubtest_allowlists/win32-py311.txt
tests/stubtest_allowlists/win32-py36.txt
tests/stubtest_allowlists/win32-py37.txt
tests/stubtest_allowlists/win32-py38.txt
tests/stubtest_allowlists/win32-py39.txt
tests/stubtest_allowlists/win32.txt

Organise so that it's more clear what should and should not be fixed, paste comments into py311.txt, several minor changes

stubtest: organise allowlists

---

requirements-tests.txt

Upgrade flake8-pyi to 22.5.1

---

.github/workflows/mypy_primer.yml
.github/workflows/stubtest_stdlib.yml
.github/workflows/tests.yml

Also, refine a little more the paths that `mypy_primer` runs on

CI: Don't run stubtest_stdlib on PRs that don't touch the stdlib

---

stdlib/pydoc.pyi
tests/stubtest_allowlists/py311.txt

https://github.com/python/cpython/commit/c91b6f57f3f75b482e4a9d30ad2afe37892a8ceb

pydoc: 3.11 changes

---

stdlib/random.pyi

https://github.com/python/typeshed/pull/7906#discussion_r878750404
I felt this better documents how seed is used in practice

random: explicitly mention int for seed

---

stdlib/urllib/request.pyi
tests/stubtest_allowlists/py311.txt

https://github.com/python/cpython/commit/c379bc5ec9012cf66424ef3d80612cf13ec51006

urllib.request: add code 308 handler for 3.11

---

tests/stubtest_allowlists/py311.txt

https://github.com/python/cpython/blob/748c83d96da735f8210167d676469860d4e11b80/Lib/inspect.py#L2631

inspect: cannot fix this one

---

stdlib/concurrent/futures/process.pyi
tests/stubtest_allowlists/py311.txt

https://github.com/python/cpython/commit/fdc0e09c3316098b038996c428e88931f0a4fcdb

concurrent.futures: new params in 3.11

---

stubs/invoke/invoke/tasks.pyi

Part of #7928 
https://github.com/pyinvoke/invoke/blob/f34c6c9413146a34ede3a5b529916b4cee649887/invoke/tasks.py#L328

invoke: Fix unconstrained TypeVar

---

stdlib/builtins.pyi

`builtins.sum`: Add overload for `bool` special case

---

CONTRIBUTING.md

Hopefully helps with #7991.
Two notes:
- This file is getting really long :( but @srittau's #7594 will help a lot with that.
- There's some other bits in this doc that are really outdated (lines 235-257), but I didn't want to cause merge conflicts for @srittau's #7594.

`CONTRIBUTING`: improve docs on running tests locally

---

CONTRIBUTING.md

CONTRIBUTING.md: Fix broken link

---

stubs/SQLAlchemy/sqlalchemy/orm/context.pyi

SQLAlchemy 1.4.37 fixes

---

tests/stubtest_allowlists/py311.txt

Fix CI for Python 3.11 beta 2

---

stdlib/unittest/__init__.pyi
stdlib/unittest/async_case.pyi
stdlib/unittest/case.pyi
tests/stubtest_allowlists/py311.txt

https://github.com/python/cpython/commit/086c6b1b0fe8d47ebd15512d7bdcb64c60a360f0

Add `unittest` features new in Python 3.11

---

stdlib/csv.pyi

Fixes #7953 (fixes the stuff typeshed can fix, anyway).

Improve `csv.DictReader`

---

stdlib/threading.pyi

Signed-off-by: Oleg Hoefling <oleg.hoefling@gmail.com>

add undocumented attributes for threading.Timer

---

stubs/paramiko/METADATA.toml

[stubsabot] Bump paramiko to 2.11.*

---

tests/stubtest_allowlists/darwin-py310.txt

Fixes #8098 (along with #8099)

Silence mysterious 3.10.5 stubtest failure

---

stdlib/socket.pyi

Slipped through the net in #8099

socket.AddressFamily: Fix AF_LINK

---

stubs/mysqlclient/METADATA.toml
stubs/mysqlclient/MySQLdb/__init__.pyi

Bump mysqlclient to 2.1.*

---

stubs/humanfriendly/METADATA.toml

[stubsabot] Bump humanfriendly to 10.0.*

---

stubs/parsimonious/METADATA.toml
stubs/parsimonious/parsimonious/expressions.pyi

Bump parsimonious to 0.9.*

---

stubs/editdistance/METADATA.toml

[stubsabot] Bump editdistance to 0.6.*

---

stubs/tabulate/tabulate.pyi

tabulate: Add maxcolwidths arguments

---

tests/mypy_test.py

This PR makes it possible to specify multiple platforms on the command line, e.g.:
```
python tests/mypy_test.py --platform win32 linux --python-version 3.11 3.10
```
would run mypy on typeshed with the following combinations in succession:
- `--platform win32`, `--python-version 3.11`
- `--platform linux`, `--python-version 3.11`
- `--platform win32`, `--python-version 3.10`
- `--platform linux`, `--python-version 3.10`

mypy_test.py: Allow passing in multiple platforms from the command line

---

stubs/redis/redis/asyncio/client.pyi

There are other things that can be improved. But, I went with types I am 100% sure.
Source: https://github.com/redis/redis-py/blob/master/redis/asyncio/client.py

Improve `redis/asyncio/client.pyi`

---

stubs/chardet/METADATA.toml

[stubsabot] Bump chardet to 5.0.*

---

stdlib/subprocess.pyi
tests/stubtest_allowlists/py3_common.txt

`subprocess.Popen`: `__new__` -> `__init__`

---

stubs/dataclasses/METADATA.toml

Mark the dataclasses stubs as no longer updated

---

stubs/Pygments/pygments/__init__.pyi

https://github.com/pygments/pygments/blob/2.12.0/pygments/__init__.py#L29

Pygments: add pygments.__version__

---

MAINTAINERS.md

According to our maintainer policy
Cc @CraftSpider

Move Rune Tynan to former maintainers

---

stdlib/urllib/parse.pyi

Improve `urllib.parse.urldefrag`

---

stdlib/socketserver.pyi

socketserver: Set StreamRequestHandler.connection to SSLSocket

---

stubs/retry/@tests/stubtest_allowlist.txt
stubs/stdlib-list/@tests/stubtest_allowlist.txt
stubs/tzlocal/@tests/stubtest_allowlist.txt
stubs/xxhash/@tests/stubtest_allowlist.txt

These are the ones I chose not to add from #8321
Fixes most of #8339

Allowlist useless modules

---

stdlib/VERSIONS

stdlib/VERSIONS: fix crusty comment

---

stdlib/unittest/case.pyi

Fixes https://github.com/python/typeshed/issues/8372

Fix hints for TestCase.assertRaises

---

stubs/redis/redis/crc.pyi

Ref: https://github.com/redis/redis-py/blob/master/redis/crc.py

Improve `redis.crc` types

---

stubs/requests/requests/compat.pyi

This adds missing items from https://github.com/psf/requests/blob/main/requests/compat.py

refactor: add missing imports and vars to requests.compat

---

stdlib/http/client.pyi
stdlib/importlib/abc.pyi
stdlib/types.pyi
stdlib/urllib/request.pyi

Unblocks https://github.com/PyCQA/flake8-pyi/pull/253

Move some protocol definitions closer to their usage sites

---

stdlib/lib2to3/pgen2/__init__.pyi
stdlib/lib2to3/pgen2/driver.pyi
stdlib/lib2to3/pgen2/parse.pyi
stdlib/lib2to3/pytree.pyi
stdlib/sqlite3/dbapi2.pyi
stdlib/sys.pyi
stubs/SQLAlchemy/sqlalchemy/ext/mypy/infer.pyi
stubs/SQLAlchemy/sqlalchemy/orm/persistence.pyi
stubs/SQLAlchemy/sqlalchemy/orm/query.pyi
stubs/psutil/psutil/__init__.pyi
stubs/psutil/psutil/_common.pyi
stubs/requests/requests/api.pyi
stubs/requests/requests/sessions.pyi
stubs/urllib3/urllib3/connection.pyi
stubs/urllib3/urllib3/response.pyi

Unblocks https://github.com/PyCQA/flake8-pyi/pull/255

Remove or move several `TypeAlias` declarations

---

stubs/requests/@tests/stubtest_allowlist.txt

requests: fix stubtest

---

stdlib/asyncio/proactor_events.pyi

Source: https://github.com/python/cpython/blob/a525f2ada407d6677bf8ca708f104694de0525e4/Lib/asyncio/proactor_events.py#L604

`_sendfile_compatible` is a class variable

---

stubs/requests/requests/__init__.pyi
stubs/requests/requests/__version__.pyi

Focused partial from #8439
Fixes missing __version__ file data from:
https://github.com/psf/requests/blob/main/requests/__version__.py

fix: add requests.__version__ and fix __init__.pyi

---

stubs/requests/requests/help.pyi

Partial: #8439
Adds support for requests.help

feat: add support for requests.help

---

stdlib/multiprocessing/context.pyi

Refs https://github.com/python/typeshed/pull/8466

Simplify `multiprocessing.context.{SpawnProcess,SpawnContext}`

---

stubs/setuptools/setuptools/_distutils/command/check.pyi

setuptools: delete _distutils.command.check.HAS_DOCUTILS

---

requirements-tests.txt
tests/pytype_test.py

Update pytype_test to be compatible with the latest pytype version.

---

stdlib/cgi.pyi

Fixes #8559.
(Draft for now to see how stubtest and other CI works)

`cgi.FieldStorage` headers accepts `Message`s

---

.github/workflows/stubsabot.yml

Broken by #8605 and the issue creation code was always broken

Fix stubsabot action

---

stdlib/os/__init__.pyi

Fix os.{,p}{read,write}v to take Sequence of ReadableBuffer / WriteableBuffer

---

.flake8

Accidentally introduced in #8612

flake8 config: fix typo

---

.github/workflows/tests.yml
.pre-commit-config.yaml
requirements-tests.txt

And move all comments in `requirements-tests.txt`/`.pre-commit-config.yaml` inline

Alphabetise items in `requirements-tests.txt`

---

stubs/aiofiles/aiofiles/os.pyi

Found using the [flake8-noqa](https://github.com/plinss/flake8-noqa) plugin

Delete some unused `# noqa` comments

---

CONTRIBUTING.md

Closes #8667 . Please do validate this is accurate.

Removed outdated mypy exceptions

---

stdlib/gzip.pyi

https://github.com/python/cpython/blob/837ce6460d6554e9d7a847951ca5108ac6926ee5/Lib/gzip.py#L16

Add more undocumented constants to gzip.pyi

---

test_cases/README.md

Thanks @kkirsche for the review of #8688!

`test_cases` README: Address post-merge review of #8688

---

stubs/protobuf/google/protobuf/json_format.pyi

See https://github.com/protocolbuffers/protobuf/issues/10518

[protobuf] Optional MessageToJson indent parameter

---

scripts/stubsabot.py

I keep on doing this thing where I'll:
1. make experimental changes to the stubsabot script
2. then run stubsabot to check if the changes work
3. find out that my changes to the stubsabot script were committed to one of the random stubsabot branches that the script creates locally, because I forgot to commit my changes to the stubsabot script before running stubsabot.
This PR makes it so that stubsabot just refuses to run if you forget to commit your changes locally before running it.

stubsabot: refuse to run if uncommitted changes are present locally

---

requirements-tests.txt
scripts/stubsabot.py
tests/utils.py

Upgrade to termcolor>=2

---

scripts/stubsabot.py

Two separate bugs would have meant that stubsabot would not have been able to find the GitHub-diff link for `emoji`

stubsabot: Fix two GitHub-diff-link bugs

---

stubs/redis/redis/asyncio/lock.pyi

Source: https://github.com/redis/redis-py/blob/master/redis/asyncio/lock.py

[redis] Improve `redis.asyncio.lock` types

---

requirements-tests.txt
stdlib/builtins.pyi

Refs https://github.com/python/typeshed/pull/8796#discussion_r980582293

Bump mypy to 0.982

---

test_cases/stdlib/asyncio/check_task.py

Add a test case for covariant asyncio.Task

---

.github/workflows/stubsabot.yml

stubsabot: try and fix change detection logic

---

stdlib/dataclasses.pyi
stdlib/string.pyi

Refs https://github.com/python/typeshed/pull/8497

Add metaclasses for `string.Template` and `dataclasses.InitVar`

---

stubs/pyinstaller/@tests/stubtest_allowlist.txt
stubs/pyinstaller/METADATA.toml
stubs/pyinstaller/PyInstaller/compat.pyi

Closes #8871
@AlexWaygood 
No other change affect the stubs.

Bump PyInstaller-stubs to 5.5

---

stubs/entrypoints/@tests/stubtest_allowlist.txt
stubs/entrypoints/METADATA.toml
stubs/entrypoints/entrypoints.pyi

Source: https://github.com/takluyver/entrypoints

Mark `entrypoints` as complete

---

stdlib/datetime.pyi

Refs https://github.com/python/typeshed/pull/8908#issuecomment-1280377066

Remove `ABCMeta` from `tzinfo`

---

stubs/python-dateutil/dateutil/tz/_common.pyi

Refs https://github.com/python/typeshed/pull/8908#issuecomment-1280370814

`dateutil`: Add comment explaining the use of `ABCMeta`

---

scripts/generate_proto_stubs.sh
stubs/protobuf/METADATA.toml
stubs/protobuf/google/protobuf/any_pb2.pyi
stubs/protobuf/google/protobuf/api_pb2.pyi
stubs/protobuf/google/protobuf/compiler/plugin_pb2.pyi
stubs/protobuf/google/protobuf/descriptor_pb2.pyi
stubs/protobuf/google/protobuf/duration_pb2.pyi
stubs/protobuf/google/protobuf/empty_pb2.pyi
stubs/protobuf/google/protobuf/field_mask_pb2.pyi
stubs/protobuf/google/protobuf/source_context_pb2.pyi
stubs/protobuf/google/protobuf/struct_pb2.pyi
stubs/protobuf/google/protobuf/timestamp_pb2.pyi
stubs/protobuf/google/protobuf/type_pb2.pyi
stubs/protobuf/google/protobuf/wrappers_pb2.pyi

Use latest version of mypy-protobuf.

Bump mypy-protobuf to 3.4.0

---

pyrightconfig.json

Add `$schema` to `pyrightconfig.json`

---

tests/stubtest_allowlists/py37.txt
tests/stubtest_allowlists/py38.txt
tests/stubtest_allowlists/py39.txt
tests/stubtest_allowlists/py3_common.txt

Update distutils stubtest allowlists for Python 3.11 release

---

.github/workflows/daily.yml
.github/workflows/stubtest_stdlib.yml
tests/stubtest_allowlists/py310.txt
tests/stubtest_allowlists/py37.txt
tests/stubtest_allowlists/py38.txt
tests/stubtest_allowlists/py39.txt
tests/stubtest_allowlists/py3_common.txt

Use `3.11` instead of `3.11-dev`

---

stdlib/ast.pyi

parse() is basically just a wrapper around compile(), which we
already have as taking ReadableBuffer.

ast: parse takes a ReadableBuffer

---

CONTRIBUTING.md

CONTRIBUTING: Note no bytearray promotion

---

stdlib/dis.pyi

`_get_code_object` cannot take bytes

dis: fix types

---

stubs/dateparser/dateparser/parser.pyi

dateparser: add new parameter

---

stubs/zxcvbn/@tests/stubtest_allowlist.txt
stubs/zxcvbn/METADATA.toml

Source: https://github.com/dwolfhub/zxcvbn-python

Mark `zxcvbn` as completed

---

stdlib/zipimport.pyi

3.11+: https://github.com/python/cpython/blob/3.11/Lib/zipimport.py#L65-L66
3.10: https://github.com/python/cpython/blob/3.10/Lib/zipimport.py#L65-L67
I've also removed `Any` usage.

zipimport: improve bytes handling

---

.github/workflows/daily.yml
.github/workflows/stubtest_stdlib.yml
requirements-tests.txt

Closes #9128
Let's test it, plan:
1. Now `daily` must not run
2. Next, I will add something to the requirements
3. It must run 🎉 
4. I will add `daily.yml` itself to `paths:`, because when it is changed, we need to validate the correctness of the change

Run stubtest on all third party stubs if requirements.txt is changed

---

.github/workflows/stubtest_third_party.yml

Similar to https://github.com/python/typeshed/blob/main/.github/workflows/stubtest_stdlib.yml

Do not run `stubtest_third_party` on requirements change

---

stubs/paramiko/METADATA.toml
stubs/paramiko/paramiko/client.pyi

Docs: https://github.com/paramiko/paramiko/blob/bbb8d57e917f5a9fefd25a85f3d10cd0c1a52ef5/paramiko/client.py#L318-L323
Closes https://github.com/python/typeshed/pull/9093

Bump paramiko to 2.12.*

---

stubs/toml/@tests/stubtest_allowlist.txt
stubs/toml/METADATA.toml

Source: https://github.com/uiri/toml/blob/master/toml/decoder.py

Mark `toml` as complete

---

stubs/python-slugify/@tests/stubtest_allowlist.txt
stubs/python-slugify/METADATA.toml
stubs/python-slugify/slugify/__version__.pyi

Source: https://github.com/un33k/python-slugify

Mark `python-slugify` as completed

---

stubs/python-slugify/slugify/__init__.pyi

Fixes https://github.com/python/typeshed/pull/9224#discussion_r1027053364

python-slugify: use explicit re-exports

---

tests/check_consistent.py

A followup to #9238 (see the CI failure in #9230)

`check_consistent.py`: Allow having weird filenames in the `test_cases` directory

---

stubs/dateparser/dateparser/languages/locale.pyi

dateparser: delete DIGIT_USE_PATTERN

---

stubs/pika/METADATA.toml

Disable pika uploads for now

---

stdlib/marshal.pyi

See w_object and w_complex_object in https://github.com/python/cpython/blob/main/Python/marshal.c

marshal: specify allowed types

---

.github/workflows/daily.yml
.github/workflows/stubtest_third_party.yml
.github/workflows/tests.yml
.github/workflows/typecheck_typeshed_code.yml

Add color back to CI output

---

stubs/PyAutoGUI/@tests/stubtest_allowlist.txt
stubs/PyAutoGUI/METADATA.toml

Source https://github.com/asweigart/pyautogui/

Mark `PyAutoGUI` as complete

---

stubs/humanfriendly/@tests/stubtest_allowlist.txt
stubs/humanfriendly/METADATA.toml

Source: https://github.com/xolox/python-humanfriendly/blob/master/humanfriendly/compat.py

Mark `humanfriendly` as complete

---

MAINTAINERS.md

Add Nikita Sobolev to maintainers

---

stdlib/asyncio/runners.pyi

As per the comment at https://github.com/python/cpython/blob/71b032635d757348cb915c2e8d99392f5bbcb059/Lib/asyncio/runners.py#L47

Mark asyncio.Runner as final

---

stubs/pika/METADATA.toml

Distribute our pika stubs under an alternate name

---

stdlib/netrc.pyi

https://github.com/python/cpython/pull/26330/files#diff-87cec79ce2fd75ede2a71354fbe60ac44f62c77e847b5dc427aa3cd47f7da5ebR120

_NetrcTuple for 3.11

---

tests/stubtest_third_party.py

Catch venv creation failure and print a helpful error message

---

stubs/python-xlib/@tests/stubtest_allowlist.txt
stubs/python-xlib/METADATA.toml
stubs/python-xlib/Xlib/support/unix_connect.pyi

Bump python-xlib to 0.33

---

.github/workflows/daily.yml
.github/workflows/stubtest_third_party.yml

Split off from https://github.com/python/typeshed/pull/9374/files#r1060179921
Makes the command to run have a single source of truth

Deduplicate stubtest command in actions

---

stubs/beautifulsoup4/METADATA.toml
stubs/beautifulsoup4/bs4/builder/_html5lib.pyi

Fixes 2 subclassing errors by referencing the html5lib stub

Fix Any subclassing in beautifulsoup4

---

stubs/jmespath/jmespath/exceptions.pyi
stubs/jmespath/jmespath/functions.pyi
stubs/jmespath/jmespath/parser.pyi

Bring `types-jmespath` on par with https://github.com/microsoft/python-type-stubs/tree/main/jmespath

Merge `jmespath` from microsoft/python-type-stubs

---

tests/mypy_test.py

Some fairly subtle logic was added in #9408, and I'm immediately regretting not having documented it slightly better. This PR adds some more comments to make maintaining this code easier in the future.

`mypy_test.py`: Add more comments

---

stubs/passlib/@tests/stubtest_allowlist_win32.txt
stubs/passlib/passlib/hosts.pyi

Not sure about darwin/macos though

Fix passlib stubtest on windows

---

stdlib/logging/__init__.pyi

The default Filter returns a bool and not an int
Closes #5700

Update FilterType to retuning bool

---

stubs/croniter/@tests/stubtest_allowlist.txt
stubs/croniter/croniter/croniter.pyi

Fix a few complaints that stubtest will have when the next release of mypy comes out. Delete the stubtest allowlist while we're about it.

Complete `croniter` stubs

---

stdlib/ctypes/__init__.pyi

ctypes._CData: Fix field name

---

stubs/PyAutoGUI/pyautogui/__init__.pyi

1. ran https://github.com/JelleZijlstra/stubdefaulter
2. manually added default kwarg parameters and constants

Add defaults for params and constants in PyAutoGUI

---

stubs/PyScreeze/pyscreeze/__init__.pyi

1. Ran https://github.com/JelleZijlstra/stubdefaulter
2. Manually added default kwarg parameters
3. Manually added defaults and Final for constants

Add defaults for params and constants in pyscreeze

---

stubs/cachetools/METADATA.toml
stubs/cachetools/cachetools/__init__.pyi

Update `cachetools` stubs to 5.3.*

---

stubs/mypy-extensions/@tests/stubtest_allowlist.txt
stubs/mypy-extensions/METADATA.toml
stubs/mypy-extensions/mypy_extensions.pyi

Some context about how mypy and mypyc use the added types:
https://github.com/python/mypy_extensions/pull/31

Update `mypy_extensions` stubs to 1.0.x

---

stdlib/keyword.pyi

`keyword`: Improve types of `kwlist` and `softkwlist`

---

stdlib/urllib/error.pyi

Code: https://github.com/python/cpython/blame/main/Lib/urllib/error.py#L61-L67

`urllib.HTTPError.headers` is a settable property

---

CONTRIBUTING.md

Remove note about Optional still being necessary sometimes

---

.github/workflows/daily.yml
.github/workflows/stubtest_third_party.yml

Following the same rationale as https://github.com/python/cpython/pull/102074

Add some more environment variables to speedup brew installs in CI

---

scripts/stubsabot.py
stdlib/_typeshed/__init__.pyi
stdlib/socketserver.pyi
stdlib/tkinter/__init__.pyi
stubs/pyinstaller/PyInstaller/depend/analysis.pyi
stubs/python-xlib/@tests/stubtest_allowlist.txt
stubs/tensorflow/@tests/stubtest_allowlist.txt
tests/regr_test.py

Fix some typos in comments

---

requirements-tests.txt

Bump pytype dependency to 2023.3.13

---

.pre-commit-config.yaml
requirements-tests.txt

There's nothing major in the changelogs for any of these.

Bump various test dependencies

---

stubs/pika/pika/spec.pyi

See the first commit for the workaround I used for the [pyright issue](https://github.com/microsoft/pyright/issues/4856) I encountered in #9957. (The pyright issue has already been closed as expected behaviour by Eric).

Add default values to `pika.spec`

---

stubs/colorama/colorama/winterm.pyi

See https://github.com/python/typeshed/pull/9972#discussion_r1152304880

colorama.winterm: ClassVar -> Final for WinColor and WinStyle

---

stubs/beautifulsoup4/bs4/__init__.pyi

Release: https://pypi.org/project/beautifulsoup4/4.12.2/
Error: https://github.com/python/typeshed/actions/runs/4647756507/jobs/8224937814#step:5:199
Refs https://github.com/python/typeshed/issues/10022

bs4: update for 4.12.2

---

stubs/croniter/@tests/stubtest_allowlist.txt
stubs/croniter/croniter/croniter.pyi

Fixing https://github.com/python/typeshed/actions/runs/4647756507/jobs/8224937971
Closes https://github.com/python/typeshed/issues/10022

Update `croniter` to `1.3.10`

---

stubs/ujson/ujson.pyi

Reference from ujson 5.7.0:
https://github.com/ultrajson/ultrajson/blob/5.7.0/python/objToJSON.c#L797 https://github.com/ultrajson/ultrajson/blob/5.7.0/tests/test_ujson.py

Update stubs with new ujson features

---

stubs/croniter/@tests/stubtest_allowlist.txt

Delete allowlist for croniter

---

stubs/ujson/ujson.pyi

fix ujson.dump signature

---

stubs/Pillow/METADATA.toml
stubs/Pillow/PIL/ImageDraw.pyi

Most changes were linting, formatting or tests related
Closes #9998

Bump Pillow to 9.5.*

---

stubs/psutil/psutil/_psutil_windows.pyi

psutil: fix stubtest

---

stubs/requests/@tests/stubtest_allowlist.txt
stubs/requests/METADATA.toml
stubs/requests/requests/adapters.pyi

Update `requests` for v2.29

---

stubs/aiofiles/aiofiles/os.pyi

aiofiles: use ReadableBuffer

---

requirements-tests.txt
scripts/create_baseline_stubs.py

Add `stubdefaulter` to `create_baseline_stubs.py`

---

stdlib/sys.pyi

Document sys.std* typing

---

stubs/pyvmomi/METADATA.toml

Pin pyvmomi more tightly

---

requirements-tests.txt
stubs/dj-database-url/@tests/stubtest_allowlist.txt
stubs/redis/@tests/stubtest_allowlist.txt

New version was recently released 🎉

Bump `mypy` to `1.3.0`

---

stubs/requests/@tests/stubtest_allowlist.txt

Allowlist requests.compat.bytes.__buffer__

---

stdlib/tempfile.pyi

Source: https://github.com/python/cpython/blob/3.12/Lib/tempfile.py#L864

py312: Add `delete=True` parameter to `tempfile.TemporaryDirectory`

---

stdlib/fcntl.pyi
tests/stubtest_allowlists/darwin-py311.txt
tests/stubtest_allowlists/darwin-py312.txt
tests/stubtest_allowlists/darwin.txt
tests/stubtest_allowlists/py3_common.txt

Apparently my laptop is not the same as the Github Actions runners

Make stubtest work better on macOS

---

stdlib/functools.pyi
tests/stubtest_allowlists/py312.txt

I am not sure that my `_assigned` hack is correct, another option is to use `if` for the whole function (but, I don't like this idea).

Update functools.pyi for Python3.12

---

stdlib/token.pyi
stdlib/tokenize.pyi
tests/stubtest_allowlists/py312.txt

Source: https://github.com/python/cpython/blob/3.12/Lib/token.py

Update token.pyi and tokenize.pyi for Python3.12

---

stdlib/_winapi.pyi
tests/stubtest_allowlists/py312.txt

Refs https://github.com/python/typeshed/pull/10290

Fix CI for the python@3.12.0-beta.2

---

pyproject.toml

Update pyright to 1.1.314

---

stdlib/unittest/mock.pyi
test_cases/stdlib/check_unittest.py
tests/utils.py

unittest.mock: use ParamSpec in patch

---

test_cases/stdlib/check_unittest.py

See https://github.com/python/typeshed/pull/10325#issuecomment-1598684045

Replace static assertion that fails with pyright

---

stubs/PyMySQL/METADATA.toml
stubs/PyMySQL/pymysql/charset.pyi
stubs/PyMySQL/pymysql/connections.pyi

Docs for `collation`: https://github.com/PyMySQL/PyMySQL/blob/dbf1ff52a695278cd80e179641f67bb6e2a83326/pymysql/connections.py#L116
Closes https://github.com/python/typeshed/pull/10365

Bump PyMySQL to `1.1.*`

---

stubs/contextvars/METADATA.toml

https://github.com/python/typeshed/issues/10418

Mark contextvars stubs as no longer updated

---

stdlib/errno.pyi
tests/stubtest_allowlists/linux.txt

Remove errnos that don't seem to exist on any platform

Mark some errnos as darwin-only

---

stdlib/asyncio/taskgroups.pyi
stdlib/json/__init__.pyi

Stubtest: fixes for py312beta4

---

scripts/stubsabot.py

Also, get GitHub repository for diff from METADATA.toml, instead of
scraping it from PyPI.

[stubsabot] Include repository in issue text

---

.pre-commit-config.yaml
requirements-tests.txt

Bump pytype and ruff test dependencies

---

pyproject.toml

https://github.com/microsoft/pyright/releases/tag/1.1.319

Bump `pyright` version

---

scripts/stubsabot.py
tests/parse_metadata.py

And remove duplicated checks from stubsabot

Add more checks in `parse_metadata.py` for the `upstream_repository` field

---

stdlib/asyncio/tasks.pyi

It was missing some params.
3.10: https://github.com/python/cpython/blob/3.10/Lib/asyncio/tasks.py#L93
3.11: https://github.com/python/cpython/blob/3.11/Lib/asyncio/tasks.py#L96
3.12: https://github.com/python/cpython/blob/3.12/Lib/asyncio/tasks.py#L101-L102

Fix `asyncio.Task.__init__` signature

---

stdlib/asyncio/constants.pyi
tests/stubtest_allowlists/py312.txt

Source: https://github.com/python/cpython/blob/9564e31cbc95a723f2414537231bc4611b56644f/Lib/asyncio/constants.py#L30

Update `asyncio.constants` module for python3.12

---

stdlib/logging/__init__.pyi
tests/stubtest_allowlists/py312.txt

Source: https://github.com/python/cpython/blob/3.12/Lib/logging/__init__.py

Update `logging` to 3.12

---

stdlib/asyncio/base_events.pyi
tests/stubtest_allowlists/py312.txt

Source: 
1. https://github.com/python/cpython/blob/3.12/Lib/asyncio/base_events.py#L1006
2. https://github.com/python/cpython/blob/3.12/Lib/asyncio/base_events.py#L564

Update `asyncio.base_events` to 3.12

---

stubs/tqdm/tqdm/utils.pyi

Fix stubtest for `tqdm`

---

stdlib/enum.pyi

Fixes https://github.com/python/mypy/issues/15870

Don't pretend `EnumMeta` inherits from `ABCMeta`

---

CONTRIBUTING.md
README.md

Note that Python 3.7 support is limited

---

stdlib/unittest/mock.pyi
stubs/mock/mock/mock.pyi
tests/stubtest_allowlists/py312.txt

Source: https://github.com/python/cpython/blob/4dc07d2bde2e219f3b6995891b8cda3e8094804a/Lib/unittest/mock.py#L420

Update `unittest.mock` to 3.12

---

stdlib/asyncio/tasks.pyi
tests/stubtest_allowlists/py312.txt

Runtime implementation added in https://github.com/python/cpython/commit/a474e04388c2ef6aca75c26cb70a1b6200235feb

Update `asyncio.tasks` for py312

---

stubs/tree-sitter/METADATA.toml

Pin `tree-sitter` to 0.20.1

---

stdlib/builtins.pyi

removed type_check_only marker from EllipsisType in python >=3.10

---

pyproject.toml

https://github.com/microsoft/pyright/releases/tag/1.1.328

Bump pyright to 1.1.328

---

stdlib/_ctypes.pyi

[ctypes] Add note about atypical classmethod behavior

---

pyproject.toml

Release: https://github.com/microsoft/pyright/releases/tag/1.1.330

Bump pyright version

---

pyproject.toml
stdlib/locale.pyi

This problem existed before #10859, but #10859 made it a bit worse

`locale`: put all the imports together at the top

---

stubs/openpyxl/openpyxl/cell/cell.pyi
stubs/openpyxl/openpyxl/chart/label.pyi
stubs/openpyxl/openpyxl/chartsheet/properties.pyi
stubs/openpyxl/openpyxl/descriptors/sequence.pyi
stubs/openpyxl/openpyxl/styles/alignment.pyi
stubs/openpyxl/openpyxl/styles/fills.pyi
stubs/openpyxl/openpyxl/styles/protection.pyi
stubs/openpyxl/openpyxl/worksheet/_reader.pyi

Various minor improvements extracted from #9511 to reduce the amount of files changed. These were missed in previous PRs.

openpyxl: Various minor improvements / previous PR fixes

---

.github/workflows/tests.yml

It looks like we no longer need the workarounds I introduced in #10152 🎉

Simplify how we run mypy_test.py on Python 3.12

---

stdlib/hashlib.pyi
tests/stubtest_allowlists/py3_common.txt

fix nullability of scrypt params

---

pyproject.toml

https://github.com/microsoft/pyright/releases/tag/1.1.334

Bump pyright to 1.1.334

---

test_cases/stdlib/itertools/check_itertools_recipes.py

This is another simple one lifted straight from the itertools docs -- I think I just accidentally omitted it from #10992

Add the `nth_combination` itertools recipe as a test case

---

stubs/Pygments/METADATA.toml
stubs/Pygments/pygments/lexer.pyi
stubs/Pygments/pygments/lexers/javascript.pyi
stubs/Pygments/pygments/lexers/jsx.pyi
stubs/Pygments/pygments/lexers/kusto.pyi
stubs/Pygments/pygments/lexers/ldap.pyi
stubs/Pygments/pygments/lexers/lean.pyi
stubs/Pygments/pygments/lexers/lisp.pyi
stubs/Pygments/pygments/lexers/prql.pyi
stubs/Pygments/pygments/lexers/vip.pyi
stubs/Pygments/pygments/lexers/vyper.pyi
stubs/Pygments/pygments/style.pyi

* Add some previously missing lexers.
* Improve lexer type annotations.
Closes: #11045

Bump pygments to 2.17

---

MAINTAINERS.md

maintainers += Avasam

---

MAINTAINERS.md

It's not pining for the fjords anymore

typing-sig is no more, it's bereft of life, it's an ex-list

---

stdlib/io.pyi
stdlib/sre_parse.pyi
tests/stubtest_allowlists/py312.txt

Stubtest fixes for the latest patch release of py311

---

stubs/fanstatic/fanstatic/injector.pyi

Small improvement that should no longer be blocked.

fanstatic: Use `Unpack` in `fanstatic.injector.Injector`

---

stdlib/email/_policybase.pyi
stdlib/email/policy.pyi

add email._policybase

---

stubs/seaborn/METADATA.toml

Pin seaborn to 0.13.0

---

stubs/netaddr/@tests/stubtest_allowlist.txt
stubs/netaddr/METADATA.toml
stubs/netaddr/netaddr/__init__.pyi
stubs/netaddr/netaddr/core.pyi
stubs/netaddr/netaddr/ip/__init__.pyi

netaddr: Bump to 0.10.*

---

stubs/passlib/@tests/test_cases/check_bcrypt_using_rounds.py
stubs/passlib/passlib/utils/handlers.pyi

Fix passlib.utils.handlers.TruncateMixin.using

---

stubs/pexpect/pexpect/spawnbase.pyi

See documentation https://github.com/pexpect/pexpect/blob/master/pexpect/pty_spawn.py#L136-L150

fix pexpect delaybeforesend_type

---

CONTRIBUTING.md

Issues appear to have been fixed.

Update `CONTRIBUTING.md` to add full support for `@deprecated`

---

stubs/pika/@tests/stubtest_allowlist.txt

Micro-PR just to update a link (and only reference to the issue). https://github.com/python/mypy/issues/13975 was duplicate of https://github.com/python/mypy/issues/6700

Update mypy issue reference to duplicated original issue

---

stubs/tensorflow/tensorflow/math.pyi

@hmc-cs-mdrissi If you have time to review it.

`tensorflow`: add `tensorflow.math.reduce_variance`

---

stubs/peewee/METADATA.toml

Pin peewee more tightly for stubtest

---

stdlib/tkinter/ttk.pyi

Add annotations and defaults for `tkinter.ttk.OptionMenu`.

Add annotations and defaults for `tkinter.ttk.OptionMenu`

---

.github/workflows/tests.yml
.pre-commit-config.yaml
requirements-tests.txt

(And Ruff because why not.)
This should fix CI on main (#11333).

deps: upgrade pytype

---

CONTRIBUTING.md
tests/README.md

Also, make it reference `partial_stub` rather than vice versa

Document `ignore_missing_stub` in CONTRIBUTING.md

---

stubs/tensorflow/tensorflow/__init__.pyi
stubs/tensorflow/tensorflow/_aliases.pyi
stubs/tensorflow/tensorflow/linalg.pyi

Add incomplete stubs taken from [here](https://github.com/hmc-cs-mdrissi/tensorflow_stubs/blob/main/stubs/tensorflow/linalg.pyi).

`tensorflow`: add `tf.linalg` module

---

stubs/openpyxl/@tests/stubtest_allowlist.txt

openpyxl: Add stubtest allowlist entry

---

stubs/html5lib/html5lib/_inputstream.pyi

Pretty sure this is what I meant to write in the first place.
Fixes #11478

html5lib: Fix type alias

---

pyproject.toml
scripts/runtests.py
stdlib/asyncio/tasks.pyi
stdlib/builtins.pyi
stubs/openpyxl/@tests/test_cases/check_base_descriptors.py
stubs/openpyxl/@tests/test_cases/check_nested_descriptors.py
stubs/pyasn1/pyasn1/type/base.pyi
tests/utils.py

There are multiple releases after the current one: https://github.com/microsoft/pyright/releases/

Update `pyright` version to 1.1.350

---

.github/workflows/daily.yml
.github/workflows/meta_tests.yml
.github/workflows/mypy_primer.yml
.github/workflows/stubsabot.yml
.github/workflows/stubtest_stdlib.yml
.github/workflows/stubtest_third_party.yml
.github/workflows/tests.yml

Update actions/setup-python to v5

---

stubs/pyinstaller/METADATA.toml
stubs/pyinstaller/PyInstaller/compat.pyi

Had a look at the changelog and changed files. Closes #11555

Bump pyinstaller to 6.5.*

---

.github/renovate.json

fix renovate config

---

stubs/requests-oauthlib/METADATA.toml
stubs/requests-oauthlib/requests_oauthlib/oauth1_auth.pyi
stubs/requests-oauthlib/requests_oauthlib/oauth2_session.pyi

Needed just a couple of minor tweaks

Bump requests-oauthlib to 1.4.*

---

stubs/croniter/croniter/croniter.pyi

[croniter] Update to 2.0.3

---

.github/renovate.json
scripts/stubsabot.py

Update label names used by bots

---

stdlib/dataclasses.pyi
test_cases/stdlib/check_dataclasses.py

Use `Any` for field type in `make_dataclass`

---

.github/workflows/daily.yml
.github/workflows/mypy_primer_comment.yml
.github/workflows/stubsabot.yml

Update actions/github-script to v7

---

.github/workflows/mypy_primer.yml
.github/workflows/mypy_primer_comment.yml

Compatibility with actions/upload-artifact@v4
Cf. #11684

Use separate artifact name per step

---

stubs/uWSGI/@tests/stubtest_allowlist_darwin.txt

Also wow, some of the logs that come from uwsgi are quite interesting
Fixes #11753

uwsgi: remove unused allowlist entry

---

stubs/setuptools/distutils/_modified.pyi
stubs/setuptools/distutils/command/install_lib.pyi
tests/check_consistent.py

Ensure that distutils and setuptools._distutils stay consistent

---

stdlib/_typeshed/__init__.pyi

@srittau Thanks for all the quick help! I randomly noticed this inconsistency in #11827

Fix comment referencing incorrect type name

---

.github/workflows/daily.yml
.github/workflows/stubtest_third_party.yml
scripts/generate_proto_stubs.sh
scripts/sync_tensorflow_protobuf_stubs.sh
stdlib/tkinter/__init__.pyi

This fixes a warning about using apt in script.

Use apt-get to install packages

---

stdlib/ast.pyi

The ``optimize`` parameter was added in https://github.com/python/cpython/commit/2dfbd4f36dd83f88f5df64c33612dd34eff256bb

Update list of ``ast.parse`` parameters

---

stdlib/ast.pyi

Add `show_empty` to `ast.dump`

---

tests/stubtest_third_party.py

It's already a relative path.
https://github.com/python/typeshed/actions/runs/9026494865/job/24803886128?pr=11848

stubtest: fix path

---

stubs/pynput/METADATA.toml

Pin pynput more tightly

---

stdlib/wsgiref/util.pyi

wsgiref: update __all__ for py313

---

stubs/influxdb-client/METADATA.toml
stubs/influxdb-client/influxdb_client/client/exceptions.pyi
stubs/influxdb-client/influxdb_client/rest.pyi

[influxdb-client] Update to 1.43.*

---

stdlib/threading.pyi

It seems not fully intentional that these are now exposed, but harmless enough. ~Commented in https://github.com/python/cpython/issues/114315#issuecomment-2118986998~

threading: add new lock methods

---

.github/workflows/tests.yml
stdlib/logging/__init__.pyi
stubs/WebOb/webob/multidict.pyi
stubs/WebOb/webob/request.pyi
tests/mypy_test.py
tests/regr_test.py
tests/runtests.py
tests/typecheck_typeshed.py

(Except for stubtest, which deserves to be its own PR)

Add 3.13 to our CI

---

stdlib/dis.pyi

https://github.com/python/cpython/blob/3b908072578d44673b8f278117c9d4c3d42a3127/Lib/dis.py#L286

dis: Update for Python 3.13

---

stdlib/@tests/test_cases/asyncio/check_task_factory.py
stdlib/asyncio/__init__.pyi
stdlib/asyncio/events.pyi

asyncio: fix task factory types

---

stubs/pynput/METADATA.toml
stubs/pynput/pynput/_util.pyi
stubs/pynput/pynput/keyboard/_base.pyi

Closes https://github.com/python/typeshed/pull/11902

Bump pynput to 1.7.7

---

stubs/openpyxl/METADATA.toml

pin `openpyxl` to 3.1.2

---

stubs/tensorflow/tensorflow/_aliases.pyi
stubs/tensorflow/tensorflow/keras/models.pyi

See https://numpy.org/devdocs/release/2.0.0-notes.html#numpy-2-0-python-api-removals

Replace `np.float_` alias removed in numpy 2.0

---

stubs/networkx/METADATA.toml
stubs/seaborn/METADATA.toml
stubs/shapely/METADATA.toml
stubs/tensorflow/METADATA.toml

Pin various stubs to numpy to < 2

---

stdlib/@tests/stubtest_allowlists/linux-py312.txt
stdlib/@tests/stubtest_allowlists/linux-py313.txt
stdlib/@tests/stubtest_allowlists/linux.txt
stdlib/os/__init__.pyi

Document the availability of the os.CLONE_ constants

---

stubs/openpyxl/openpyxl/worksheet/dimensions.pyi
stubs/openpyxl/openpyxl/worksheet/worksheet.pyi

[openpyxl] Fix key of Worksheet.row_dimensions

---

stubs/fpdf2/fpdf/fpdf.pyi
stubs/fpdf2/fpdf/image_datastructures.pyi
stubs/fpdf2/fpdf/table.pyi
stubs/fpdf2/fpdf/text_region.pyi

Closes https://github.com/python/typeshed/issues/12109

fpdf2: improve `text_align` types and `.table()` method signature

---

stdlib/@tests/test_cases/check_functools.py

These tests demonstrate the issue described in #10653.

Add  tests to functools.wraps

---

stdlib/tarfile.pyi

fix: preset type for tarfile.open

---

scripts/generate_proto_stubs.sh
stubs/protobuf/METADATA.toml
stubs/protobuf/google/protobuf/descriptor_pb2.pyi

Closes #12026
Glad to see the updated script hold up for at least 1 version ^^

Bump protobuf to 5.27.*

---

stubs/reportlab/METADATA.toml

Pin reportlab to version 4.2.0

---

stubs/tensorflow/METADATA.toml

[tensorflow] Pin keras to 3.3.*

---

stubs/openpyxl/METADATA.toml
stubs/openpyxl/openpyxl/packaging/extended.pyi
stubs/openpyxl/openpyxl/styles/named_styles.pyi

Closes https://github.com/python/typeshed/pull/12237

Bump openpyxl to 3.1.5

---

stubs/networkx/networkx/algorithms/shortest_paths/generic.pyi

Never contributed types before so please let me know if I somehow messed this up...

add stubs for networx.has_path

---

stdlib/@tests/stubtest_allowlists/py313.txt
stdlib/turtle.pyi

Finalize removals in stubs for `turtle` in 3.13.

Resolve 3.13 `turtle` issues

---

scripts/stubsabot.py

[stubsabot] Improve error message

---

stubs/pygit2/METADATA.toml

Pin pygit2 to 1.15.0

---

stubs/flake8/flake8/statistics.pyi

Source: https://github.com/PyCQA/flake8/blob/65a38c42a7f1a05ff8d99b313160754fc9b7a0d8/src/flake8/statistics.py#L102-L117

[flake8] Improve `Statistic` typing

---

stdlib/@tests/stubtest_allowlists/py313.txt
stdlib/trace.pyi

Add new `ignore_missing_files` flag.

Update `CoverageResults` for 3.13

---

scripts/generate_proto_stubs.sh
scripts/sync_s2clientprotocol_protobuf_stubs.sh
scripts/sync_tensorflow_protobuf_stubs.sh

It only has `-i`, see https://stackoverflow.com/questions/7573368/in-place-edits-with-sed-on-os-x

macos does not have `sed --in-place` argument

---

requirements-tests.txt
stdlib/@tests/test_cases/builtins/check_pow.py

Bump pyright to 1.1.372

---

stubs/docker/docker/models/containers.pyi

https://github.com/docker/docker-py/blob/main/docker/models/containers.py#L743

[docker] Add restart_policy type annotation to Container model

---

stdlib/@tests/stubtest_allowlists/darwin-py313.txt
stdlib/@tests/stubtest_allowlists/linux-py313.txt
stdlib/readline.pyi

https://github.com/python/cpython/pull/112511

Add `readline.backend` for 3.13

---

stdlib/@tests/stubtest_allowlists/linux-py313.txt
stdlib/@tests/stubtest_allowlists/win32-py313.txt
stdlib/_stat.pyi

The following constants are only defined on osx.

Fix `_stat` for 3.13

---

stubs/croniter/METADATA.toml
stubs/croniter/croniter/croniter.pyi

Closes https://github.com/python/typeshed/pull/12358

Bump croniter to 2.0.*

---

stubs/croniter/METADATA.toml
stubs/croniter/croniter/croniter.pyi

Closes https://github.com/python/typeshed/pull/12417

Bump croniter to 3.0.*

---

stubs/croniter/METADATA.toml

Pin croniter to 3.0.0

---

stdlib/logging/__init__.pyi
stdlib/logging/handlers.pyi

Use `Final` for logging constants.

Final for logging constants

---

stdlib/_osx_support.pyi
stdlib/argparse.pyi
stdlib/email/charset.pyi
stdlib/gzip.pyi
stdlib/logging/config.pyi
stdlib/modulefinder.pyi
stdlib/pyexpat/__init__.pyi
stdlib/subprocess.pyi
stdlib/tty.pyi
stdlib/xmlrpc/client.pyi

Use `Final` for undocumented/private constants.

Use Final for undocumented constants

---

stubs/seaborn/METADATA.toml
stubs/shapely/METADATA.toml
stubs/tensorflow/METADATA.toml

Remove numpy version pin

---

stdlib/pty.pyi

Add `pty` deprecations, and removal for 3.14.

Add `pty` deprecations

---

stdlib/_ast.pyi
stdlib/ast.pyi

The following are removed in 3.14.

`ast` removals for 3.14

---

stdlib/tarfile.pyi

Allow `float` for `TarInfo.mtime`

---

stdlib/@tests/stubtest_allowlists/py312.txt

Ignore incompatible changes introduced in Python 3.12.5

---

stdlib/distutils/command/install.pyi
stdlib/distutils/debug.pyi
stubs/setuptools/setuptools/_distutils/sysconfig.pyi

I noticed these while reviewing https://github.com/python/typeshed/pull/12454 , but it felt possibly out of scope for that PR.
CC @max-muoto feel free to add these changes to your PR if you'd like. Otherwise we can merge this afterward (so that I'm the one dealing with conflicts)

Update incorrect or incomplete constants in distutils

---

stdlib/distutils/cmd.pyi
stdlib/distutils/dist.pyi
stubs/setuptools/setuptools/_distutils/cmd.pyi
stubs/setuptools/setuptools/_distutils/dist.pyi

Noticed whilst fixing mypy `attr-defined` in setuptools

distutils: expose `Command.dry_run` + make `0|1` attrs `bool`

---

stdlib/_locale.pyi

Mark constants as Final in _locale.pyi

Use TypedDict for return type of localeconv()

---

stubs/influxdb-client/influxdb_client/client/write/point.pyi

[influxdb-client] Use SupportsContainsAndGetItem

---

stdlib/@tests/stubtest_allowlists/py313.txt
stdlib/doctest.pyi

Fix doctest issues for Python 3.13.

Fix doctest for 3.13

---

stubs/python-datemath/METADATA.toml

Closes: #12640
Part of: #12642

[python-datemath] Pin and mark as obsolete

---

stdlib/@tests/stubtest_allowlists/py313.txt

These aren't issues that need to be triaged.

Move `__replace__` issues out of triage

---

stubs/paramiko/METADATA.toml
stubs/paramiko/paramiko/packet.pyi

Diff: https://github.com/paramiko/paramiko/compare/3.4.0...3.5.0
Closes https://github.com/python/typeshed/pull/12666

Bump paramiko to 3.5.*

---

stubs/gevent/@tests/stubtest_allowlist.txt

Fixes a CI failure seen in  #12725

gevent: remove unused allowlist entry

---

stubs/docutils/docutils/frontend.pyi

see https://github.com/sphinx-doc/sphinx/pull/12960#discussion_r1787752638

improve type annotations in 'docutils.frontend'

---

stdlib/@tests/stubtest_allowlists/linux-py310.txt
stdlib/@tests/stubtest_allowlists/linux-py311.txt
stdlib/@tests/stubtest_allowlists/linux-py312.txt
stdlib/@tests/stubtest_allowlists/linux-py38.txt
stdlib/@tests/stubtest_allowlists/linux-py39.txt

It doesn't exist on Ubuntu 24.04.

Add 'nis' to stubtest allowlist

---

CONTRIBUTING.md

Update third-party removal policy

---

stdlib/warnings.pyi

Fix `warnings.filters` type

---

pyrightconfig.stricter.json

Fixes AlexWaygood/typeshed-stats#274.

netifaces: apply stright pyright settings

---

stdlib/email/policy.pyi

Add `email.policy.EmailPolicy.clone`

---

stdlib/os/__init__.pyi

This is my first PR - please let me know if I've done it right!

Add os.process_cpu_count() for 3.13

---

stubs/croniter/METADATA.toml
stubs/croniter/croniter/__init__.pyi
stubs/croniter/croniter/croniter.pyi

[croniter] Update to 3.0.4 and use compatible release scheme

---

stubs/humanfriendly/@tests/stubtest_allowlist.txt
stubs/pika/@tests/stubtest_allowlist.txt
stubs/six/@tests/stubtest_allowlist.txt

fallout from https://github.com/python/typeshed/pull/12947
fixes https://github.com/python/typeshed/issues/12954

remove unused io-related allowlist entries

---

stubs/setuptools/METADATA.toml
stubs/setuptools/setuptools/command/bdist_wheel.pyi
stubs/setuptools/setuptools/command/easy_install.pyi
stubs/setuptools/setuptools/msvc.pyi

closes https://github.com/python/typeshed/pull/12999

Update setuptools to 75.4.*

---

stubs/gevent/METADATA.toml
stubs/gevent/gevent/events.pyi

closes https://github.com/python/typeshed/pull/12998

Update gevent to 24.11.*

---

stubs/Deprecated/METADATA.toml
stubs/Deprecated/deprecated/classic.pyi
stubs/Deprecated/deprecated/sphinx.pyi

[Deprecated] Update to 1.2.15

---

stdlib/@tests/stubtest_allowlists/common.txt
stdlib/email/__init__.pyi

I read through https://github.com/python/typeshed/issues/6523. If there's a reason why we shouldn't work around the issue this way until a better option is available, it wasn't clear to me from that thread.

add `email.__all__`

---

stubs/gevent/@tests/stubtest_allowlist.txt
stubs/gevent/@tests/stubtest_allowlist_linux.txt

From the daily test failure: https://github.com/python/typeshed/issues/13055

clean up allowlist for gevent

---

stdlib/@tests/stubtest_allowlists/darwin.txt
stdlib/@tests/stubtest_allowlists/linux.txt
stdlib/_ctypes.pyi

add missing _ctypes functions

---

stubs/bleach/@tests/stubtest_allowlist.txt
stubs/bleach/METADATA.toml

[bleach] Update to 6.2.*

---

stdlib/@tests/stubtest_allowlists/common.txt
stdlib/json/scanner.pyi

[Link to CPython](https://github.com/python/cpython/blob/main/Lib/json/scanner.py)

add json.scanner module

---

stdlib/@tests/stubtest_allowlists/common.txt
stdlib/ctypes/macholib/__init__.pyi
stdlib/ctypes/macholib/dyld.pyi
stdlib/ctypes/macholib/dylib.pyi
stdlib/ctypes/macholib/framework.pyi

[Link to CPython ](https://github.com/python/cpython/tree/main/Lib/ctypes/macholib)

add the undocumented `ctypes.macholib` module

---

stdlib/@tests/stubtest_allowlists/linux.txt
stdlib/fcntl.pyi

remove broad allowlist entry

---

stdlib/@tests/stubtest_allowlists/common.txt
stdlib/turtle.pyi

At first I thought this wouldn't work, but that was because I'd just done too many MRs recently with a type conflict on an assignment within a class and it's subclasses. This is a method though, so I believe it's fine once the ignore is in place.

add turtle.TNavigator.speed

---

stdlib/argparse.pyi

Set `None` as default value for `prog` in `add_subparsers`

---

stubs/Markdown/markdown/core.pyi

Use _ReadableStream from codecs

---

stubs/fpdf2/fpdf/fpdf.pyi

this if from the comment on https://github.com/py-pdf/fpdf2/blob/674164ca53e13ad13d877b7e731a6a62cdfdebb6/fpdf/fpdf.py#L271

Inline Fonts to 2 types accoridng to source

---

stdlib/@tests/stubtest_allowlists/common.txt

Just what seemed pretty obvious

Move a couple allowlist entries to "don't fix"

---

stubs/python-gflags/METADATA.toml

Fixes https://github.com/python/typeshed/issues/13185

Mark gflags as no longer updated

---

stubs/ibm-db/METADATA.toml

pin ibm-db to 3.2.3

---

stubs/setuptools/@tests/stubtest_allowlist.txt
stubs/setuptools/setuptools/compat/py310.pyi
stubs/setuptools/setuptools/compat/py311.pyi
stubs/setuptools/setuptools/compat/py312.pyi
stubs/setuptools/setuptools/compat/py39.pyi

See https://github.com/python/typeshed/pull/10919#issuecomment-2558557458

setuptools: Remove problematic private module compat

---

.github/workflows/mypy_primer.yml
.github/workflows/mypy_primer_comment.yml

These actions diverged, making them more closely match makes it easier to maintain

Match mypy primer comment code

---

stdlib/tkinter/filedialog.pyi

Partially fixes issue: https://github.com/python/typeshed/issues/11482
Source of fixes based on the @akuli comment: https://github.com/python/typeshed/issues/11482#issuecomment-1981710718

Add some defaults to tkinter.filedialog

---

stubs/zstd/METADATA.toml

zstd: pin version

---

stubs/dateparser/dateparser/calendars/__init__.pyi
stubs/dateparser/dateparser/calendars/hijri_parser.pyi
stubs/dateparser/dateparser/calendars/jalali_parser.pyi

Fix stubtest for `dateparser`

---

stubs/icalendar/icalendar/__init__.pyi
stubs/requests/requests/__init__.pyi

Should enable us to update pyright (#13198).

Fix conflicting imports

---

stubs/pynput/METADATA.toml
stubs/pynput/pynput/keyboard/_base.pyi

Bump pynput to 1.8.*

---

stubs/gdb/METADATA.toml
tests/stubtest_third_party.py

Remove LD_LIBRARY_PATH before running gdb

---

stdlib/heapq.pyi

Use `Generator` for `heapq.merge`

---

stubs/humanfriendly/METADATA.toml

Mark humanfriendly as no longer updated

---

stubs/pywin32/@tests/stubtest_allowlist_win32.txt
stubs/pywin32/METADATA.toml

Bump pywin32 to 310.*

---

stdlib/logging/config.pyi

logging.config: Add @type_check_only markers

---

stubs/gdb/gdb/__init__.pyi

[gdb] Remove unused import

---

stdlib/@tests/test_cases/check_importlib_resources.py

Move imports into version_info branch

---

stubs/croniter/METADATA.toml

Cf. #13260 pallets-eco/croniter#144

Update croniter repository URL

---

pyrightconfig.stricter.json

Remove humanfriendly from pyrightconfig.stricter.json

---

stubs/commonmark/METADATA.toml

Ref https://github.com/python/typeshed/issues/13725

Mark commonmark as no_longer_updated

---

stdlib/_ast.pyi
stdlib/ast.pyi

drop py38 support in `ast`

---

stdlib/os/__init__.pyi
stdlib/sys/__init__.pyi

drop py38 support in `os` and `sys`

---

stubs/click-web/METADATA.toml
stubs/click-web/click_web/__init__.pyi
stubs/click-web/click_web/resources/cmd_exec.pyi
stubs/click-web/click_web/resources/index.pyi
stubs/click-web/click_web/resources/input_fields.pyi
stubs/click-web/click_web/web_click_types.pyi

~~I'm not sure about the need to annotate the `jinja_env` var but if `click-web` already has `Jinja2` as a dependency then it shouldn't cost us much (i'm just haven't added new deps to requires before)~~

Complete stubs for `click-web`

---

stubs/mypy-extensions/mypy_extensions.pyi

CC @AlexWaygood
Refs https://github.com/python/typeshed/pull/13874

Update `mypy_extensions` deprecation messages

---

stubs/ExifRead/METADATA.toml

Mark ExifRead as obsolete

---

CONTRIBUTING.md

And integrate the "Code Style" chapter there. This makes the actual chapter structure follow the overview structure.

Rename "Preparing Changes" to "Making Changes"

---

stubs/pep8-naming/METADATA.toml
stubs/pep8-naming/pep8ext_naming.pyi

Bump pep8-naming to 0.15.*

---

stubs/setuptools/METADATA.toml
stubs/setuptools/setuptools/command/install.pyi

Bump setuptools to 80.1.*

---

stubs/grpcio/grpc_channelz/v1/channelz_pb2.pyi
stubs/grpcio/grpc_reflection/v1alpha/reflection_pb2.pyi

CC @srittau 
This is just because https://github.com/python/typeshed/pull/13930 and https://github.com/python/typeshed/pull/13932 were merged without the CI being re-triggered.

Run Black after grpcio merge

---

stdlib/ast.pyi

#13954
--- TEST SUMMARY: All tests passed! ---
pre-commit Success
Check structure: Success
Pyright: Success
mypy: Success
stubtest: Success
pytype: Success
Pyright regression tests: Success
mypy regression test: Success

remove _Identifier: typing_extensions.TypeAlias = str (#13954)

---

.github/workflows/tests.yml

[CI] Fix "mypy: Check stubs" when using specific Python version

---

stdlib/ast.pyi
stdlib/asyncio/events.pyi
stdlib/sqlite3/__init__.pyi
stdlib/typing.pyi

Fix errors when type checking stdlib with Python 3.14

---

stdlib/@tests/stubtest_allowlists/py314.txt
stdlib/datetime.pyi

Add strptime for `datetime.time` and `datetime.date` (3.14)

---

stdlib/tkinter/__init__.pyi

This PR addresses:
- issue1: https://github.com/python/typeshed/issues/13931
- issue2: https://github.com/python/typeshed/issues/13962
for reference: https://www.tcl-lang.org/man/tcl8.6/TkCmd/photo.htm#M30

Fix tkinter.PhotoImage.put arguments

---

stdlib/@tests/stubtest_allowlists/py314.txt
stdlib/logging/handlers.pyi

Add context manager support for 3.14

Add context manager support for QueueListener (3.14)

---

stubs/requests/requests/api.pyi
stubs/requests/requests/models.pyi
stubs/requests/requests/sessions.pyi

[requests] Add a _JSON type alias

---

requirements-tests.txt

Update uv to 0.7.4

---

stdlib/@tests/stubtest_allowlists/py314.txt
stdlib/sys/__init__.pyi

Add new `is_remote_debug_enabled` and `remote_exec` functions.

Update `sys` for 3.14

---

stdlib/@tests/test_cases/typing/check_MutableMapping.py

Add tests for MutableMapping.update()

---

tests/pytype_test.py

This small PR evaluates and displays the `req_name` on error.

Display req name on error

---

stdlib/@tests/stubtest_allowlists/linux-py314.txt
stdlib/select.pyi

https://github.com/python/cpython/blob/366d95d86239e62baf99b9cedb461e64d5dce057/Modules/selectmodule.c#L2751-L2754

Update `select` module for 3.14

---

stubs/python-jose/@tests/stubtest_allowlist.txt
stubs/python-jose/METADATA.toml
stubs/python-jose/jose/backends/__init__.pyi
stubs/python-jose/jose/backends/cryptography_backend.pyi
stubs/python-jose/jose/jws.pyi
stubs/python-jose/jose/jwt.pyi

Bump python-jose to 3.5.*

---

stubs/atheris/METADATA.toml

[atheris] Mark as no longer updated

---

stubs/aiofiles/aiofiles/threadpool/__init__.pyi

https://github.com/python/typeshed/issues/14224

Fix aiofiles.open is partially unknown

---

stdlib/ast.pyi

ast: Remove 3 `TypeAlias`. Fix identifier collision. 

---

stubs/croniter/croniter/croniter.pyi

Had to stare at this stub for a while to notice the bug...

croniter: fix typo

---

pyrightconfig.stricter.json

Fixes https://github.com/AlexWaygood/typeshed-stats/issues/350

Use stricter pyright settings for all of `click-web`

---

stubs/Pygments/pygments/formatters/other.pyi

RawTokenFormatter always returns bytes

---

.github/workflows/meta_tests.yml

[CI] Run pyright tests with Python 3.13

---

stubs/django-import-export/import_export/templatetags/import_export_tags.pyi
stubs/networkx/networkx/utils/__init__.pyi
stubs/seaborn/seaborn/_core/groupby.pyi
stubs/seaborn/seaborn/_stats/aggregation.pyi
stubs/tensorflow/tensorflow/_aliases.pyi
stubs/tensorflow/tensorflow/io/__init__.pyi

Remove pytype workarounds from third-party stubs

---

stubs/channels/METADATA.toml
stubs/channels/channels/testing/live.pyi

[channels] Bump to `4.3.*`

---

stdlib/fcntl.pyi

Source: https://github.com/python/cpython/blob/main/Modules/fcntlmodule.c

[fcntl] Use Final for constants

---

stubs/yt-dlp/METADATA.toml
stubs/yt-dlp/yt_dlp/extractor/common.pyi
stubs/yt-dlp/yt_dlp/utils/__init__.pyi
stubs/yt-dlp/yt_dlp/utils/_deprecated.pyi
stubs/yt-dlp/yt_dlp/utils/_utils.pyi

[yt-dlp] Update to 2025.8.20

---

stubs/Authlib/METADATA.toml
stubs/Authlib/authlib/jose/errors.pyi

[Authlib] Update to 1.6.4
