python/typeshed

- scripts/stubsabot.py
Addresses some of the confusion seen in #9595
> Improve stubsabot logic for finding the first release with a `py.typed` file

- tests/parse_metadata.py
> Fix typo in `parse_metadata.read_stubtest_settings`

- stdlib/_bisect.pyi
Refs #9608
- If no value is provided for the `key` parameter by the user, we actually want the type checker to specify the first overload (not this overload, which is the second overload). Specifying a default value for this parameter in this overload is confusing.
- If the type checker did select this overload, the `_T` TypeVar would go unsolved if no value was specified for the key parameter.
- If we try to add the default value for this parameter (`None`), mypy will (correctly) complain that we're using an implicit optional type for the type annotation.
> `_bisect`: Remove incorrect `= ...`s for several overloads

- stdlib/sre_constants.pyi
Stubtest will complain about these being missing once mypy 1.0 is released.
(On Python 3.11, these constants are _actually_ defined in `re/_constants.py`, and reexported from the deprecated-in-3.11 `sre_constants` module. But I'd rather not reflect that right now, as that will be a much larger and more complicated change.)
> Add some missing py311+ constants to `sre_constants.pyi`

- .github/workflows/mypy_primer_comment.yml
To be exact, we only need to reserve 170 characters to truncate over a thousand lines. But I figured that `65300` was a nice round number with a good buffer.
Sources:
and https://github.com/orgs/community/discussions/27190#discussioncomment-3254953
> Increase `mypy_primer` comment length

- .pre-commit-config.yaml
- requirements-tests.txt
Fixes the CI failure seen in #9616 (see https://github.com/PyCQA/isort/issues/2077 for an explanation of the issue, fixed in the latest isort release)
> Bump isort to 5.12.0

- tests/regr_test.py
It looks like in #9382, I reintroduced the bug that I previously fixed in #9349
> Fix typo in `tests/regr_test.py`

- stdlib/tempfile.pyi
We want the type checker to always pick the `_BytesMode` overload if no value is passed for the `mode` parameter, so specifying a default value for the other overloads is incorrect. Fixing this unfortunately requires adding two new overloads.
Refs #9608.
> `tempfile.SpooledTemporaryFile`: fix overloads

- stubs/PyAutoGUI/pyautogui/__init__.pyi
Missing methods were the ones imported directly from PyScreeze:
`from pyscreeze import center, grab, pixel, pixelMatchesColor, screenshot`
> `PyAutoGui`: Add more reexports from pyscreeze

- stdlib/_tkinter.pyi
- stdlib/tkinter/__init__.pyi
On 3.8+, the second argument of `_tkinter.create` defaults to `""` rather than `None`, and `TypeError` is raised if a non-`str` is passed in:
```pycon
>>> import _tkinter
>>> _tkinter.create("foo", None)
TypeError: create() argument 2 must be str, not None
```
Meanwhile, on 3.9+, `tkinter.Tk.__init__` and `tkinter.Tcl` have `bool` defaults, which can be added to the stub. But on <=3.8, these functions have `int` defaults, which can't be added to the stub (since the parameters are annotated with `bool`, and I don't think we should change that).
> Improve a few version-dependent tkinter functions

- stubs/pyserial/serial/tools/list_ports_common.pyi
Some USB specific attributes in pyserial's [`serial.tools.list_port_common.ListPortInfo`](https://github.com/python/typeshed/blob/main/stubs/pyserial/serial/tools/list_ports_common.pyi#L11-L24) class are not always available and should be marked as optional. They depend on the USB device and its driver correctly reporting these attributes. I discovered this recently with a new device that does not report its serial number. Only the Vendor ID `vid` and Product ID `pid` are guaranteed (This can be seen [here](https://github.com/pyserial/pyserial/blob/master/serial/tools/list_ports_linux.py#L52-L62) where `vid` and `pid` are always cast as `int` while other attributes are left as `str | None` for USB devices).
This is a follow up to #9347 and the discussion at …
> Fix optional USB attributes in pyserial's `ListPortInfo`

- stubs/setuptools/pkg_resources/__init__.pyi
Hi,
First, thanks a lot for maintaining mypy, typeshed, and friends!
Now, I realize that the setuptools and pkg_resources stubs need a bit more work (I just found a work-in-progress change I had forgotten about that was supposed to fix some of the Distribution fields and methods), but what do you think about this simple first step? The `pkg_resources.Requirement.parse()` method has been able to parse PEP508 dependency specifications containing a "@ url" part ever since setuptools-20.2, so I guess it ought to be safe to add it unconditionally.
Thanks in advance, and keep up the great work!
G'luck,
Peter
> Add `setuptools.pkg_resources.Requirement.url`

- CONTRIBUTING.md
Also move it to the "Conventions" section due its scope change.
Closes: #8955
> Rework the "Incomplete stubs" section

- stdlib/_winapi.pyi
Use hexadecimal where applicable, to reduce the number of 'random numbers' in the file
> Improve readability of `stdlib/_winapi.pyi`

- stubs/colorama/colorama/initialise.pyi
Implementation looks like this:
```python
def wrap_stream(stream, convert, strip, autoreset, wrap):
if wrap:
wrapper = AnsiToWin32(stream,
convert=convert, strip=strip, autoreset=autoreset)
if wrapper.should_wrap():
stream = wrapper.stream
return stream
```
> colorama: Preserve input type for `wrap_stream`

- stdlib/builtins.pyi
- stdlib/typing.pyi
Some PEP 604 bugs were fixed in mypy 1.0, unblocking these changes
> Remove a no-longer-needed `# noqa`

- .github/workflows/tests.yml
- pyrightconfig.json
- pyrightconfig.stricter.json
- pyrightconfig.testcases.json
- stubs/invoke/@tests/test_cases/check_task.py
- stubs/protobuf/@tests/test_cases/check_struct.py
- stubs/regex/@tests/test_cases/check_finditer.py
- stubs/requests/@tests/test_cases/check_post.py
- tests/check_consistent.py
As seen in #9623, following some recent changes to our pyright config, pyright no longer verifies our checks against false-negative errors that we have in our third-party test cases. (Our standard-library test cases are fine.) Luckily, the latest release of pyright means that we can use the same pyright config for our third-party test cases as we do for our standard-library test cases, by using wildcards in `include` and `exclude` patterns. This means that we can remove a no-longer-necessary test from `check_consistent.py`, and it means that we no longer have to have `# pyright: reportUnnecessaryTypeIgnoreComment=true` comments at the top of every third-party test-case file.
Also in this PR:
- Add a new test to `check_consistent.py`, ensuring that `.py` files are only found in the …
> Improve pyright verification of third-party test cases in CI

- stdlib/subprocess.pyi
This argument is forwarded on to `Popen.__init__`, like most of the other arguments. It can be `None`, just like the `executable` parameter for all the other `subprocess` functions:
```pycon
>>> import subprocess
>>> subprocess.check_call(["python", "-c", "1/1"], executable=None)
0
>>> subprocess.check_call(["python", "-c", "1/0"], executable=None)
File "<string>", line 1, in <module>
ZeroDivisionError: division by zero
File "C:\Users\alexw\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 369, in check_call
raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', '-c', '1/0']' returned non-zero exit status 1.
```
> `subprocess.check_call`: `executable` defaults to `None`

- stubs/pyserial/@tests/stubtest_allowlist.txt
- stubs/pyserial/@tests/stubtest_allowlist_darwin.txt
- stubs/pyserial/@tests/stubtest_allowlist_linux.txt
- stubs/pyserial/@tests/stubtest_allowlist_win32.txt
- stubs/pyserial/METADATA.toml
- stubs/pyserial/serial/win32.pyi
> Enable stubtest for `pyserial`

- stubs/Pillow/PIL/BlpImagePlugin.pyi
- stubs/Pillow/PIL/FtexImagePlugin.pyi
- stubs/Pillow/PIL/Image.pyi
- stubs/Pillow/PIL/ImageCms.pyi
- stubs/Pillow/PIL/ImageFont.pyi
- stubs/Pillow/PIL/PngImagePlugin.pyi
https://pillow.readthedocs.io/en/stable/releasenotes/9.1.0.html#constants
Related:
- python-pillow/Pillow#5954
- #8419
> Pillow: Add missing enums from 9.1.0

- stubs/Markdown/markdown/treeprocessors.pyi
This replaced the deprecated `markdown.postprocessors.UnescapePostprocessor` in https://github.com/Python-Markdown/markdown/pull/1272.
> Add markdown.treeprocessors.UnescapeTreeprocessor

- .github/workflows/daily.yml
- .github/workflows/stubtest_third_party.yml
As the inline comment says: Speedup brew install. Environments are isolated, no need to cleanup old versions.
While working on a PR that touched pyaudio, I noticed this from runs like https://github.com/python/typeshed/actions/runs/4148676771/jobs/7176901691#step:5:54
I also moved the `NONINTERACTIVE` under `env`
> Set HOMEBREW_NO_INSTALL_CLEANUP to speedup brew installs

- stubs/PyYAML/yaml/__init__.pyi
The dump_all functions actually accept any iterable ([the docs](https://pyyaml.org/wiki/PyYAMLDocumentation) say: "`yaml.dump_all` accepts a list or a generator producing Python objects to be serialized into a YAML document.").
> Update PyYAML dump_all functions

- stubs/pyOpenSSL/OpenSSL/crypto.pyi
This value was added in v23.0.0:
https://github.com/pyca/pyopenssl/commit/1cafac4d8fc5301d4e58bedbac45722bf7cdfd32
Signed-off-by: Andy Doan <andy@foundries.io>
> pyOpenSSL: Introduce PARTIAL_CHAIN constant

- stdlib/distutils/command/check.pyi
- stdlib/unittest/mock.pyi
- stubs/Pillow/PIL/ImageQt.pyi
- stubs/mock/mock/mock.pyi
- tests/mypy_test.py
Since maintainers seems to be in favor of keeping `--allow-subclassing-any`, this adds a few comments on the few cases left and closes #9491
Everything else have been completed in different PRs (except one, but I'm fine closing #9491 with 1 left)
> Add comments when subclassing Any

- .pre-commit-config.yaml
This doesn't autofix, see #9742
> GitHub prevented pre-commit.ci from autofixing this pr due to autofixes to a workflow file
Life is too short to spend it being yelled at by robots because line length in some YAML is too long.
> Remove prettier from pre-commit

- .pre-commit-config.yaml
Hi,
I found some areas of improvement in the `pre-commit` configuration.
> Fix pre-commit configuration

- .pre-commit-config.yaml
- scripts/stubsabot.py
Fixes "potentially unbound" type issues in stubsabot.
Simplify a bit the section about finding the first `py.typed` version and whether the stub is obsolete.
> Fix potentially unbound issues in stubsabot

- stubs/pyserial/@tests/stubtest_allowlist_darwin.txt
- stubs/pyserial/@tests/stubtest_allowlist_linux.txt
- stubs/pyserial/@tests/stubtest_allowlist_win32.txt
- stubs/pyserial/serial/tools/list_ports_linux.pyi
- stubs/pyserial/serial/tools/list_ports_windows.pyi
- stubs/pyserial/serial/win32.pyi
Stubtest was enabled for the pyserial stubs recently in #9692 and it surfaced some errors especially on Windows that were allow-listed temporarily to get the CI green. This is a fix for these errors.
> Fix stubtest of pyserial

- .flake8
The in-code comment explains the rationale:
Some flake8 plugins are stubbed by typeshed. When working on a stub, it is useful to install it in your venv for intellisense and reference reasons. Because of this, it can be expected to find said plugins in the local python environment, which are automatically picked-up by flake8. Resulting in a bunch of extra flake8 errors that only appear locally.
Also simplified configs a bit by de-duplicating violations that are ignored in all files.
> Ignore flake8 extensions stubbed by typeshed

- scripts/stubsabot.py
Fixes #9759
I tested this locally: with this patch, `DateTimeRange` is correctly marked as obsolete if I run it locally. Without it, stubsabot just tries to bump `DateTimeRange` to the latest version, without noticing that `DateTimeRange` added a `py.typed` file in the latest version, released in the last 24 hours.
> Fix broken stubsabot logic in `find_first_release_with_py_typed`

- stdlib/functools.pyi
Docs are here: https://docs.python.org/3/library/functools.html#functools.lru_cache
> lru_cache.cache_info().maxsize can be None for infinite cache size

- stdlib/textwrap.pyi
All keyword arguments are delegated to `TextWrapper.__init__`: https://github.com/python/cpython/blob/59e86caca812fc993c5eb7dc8ccd1508ffccba86/Lib/textwrap.py#L373-L396
> `textwrap.{wrap, fill}`: `max_lines` defaults to `None`

- requirements-tests.txt
Should fix a pytype issue in #9781 and #9642 thanks to https://github.com/google/pytype/commit/a7cd226ec76fe9f64487054e1d2e9cdb32fc9f3f / https://github.com/google/pytype/issues/1369
> Bump `pytype` to 2023.2.17

- stubs/tabulate/tabulate/__init__.pyi
- stubs/tabulate/tabulate/version.pyi
Reran stubgen, then I still had to manually add missing constants to resolve #9700
> Manually add missing symbols to `tabulate`

- scripts/stubsabot.py
We can use `typing_extensions.Self` now
> [Minor] Simplify some type hints in stubsabot

- stdlib/ssl.pyi
- tests/stubtest_allowlists/py3_common.txt
The comment in the allowlist is incorrect: `ssl._ASN1Object` isn't actually a namedtuple class at runtime. It's a *subclass* of a namedtuple class at runtime, and it's fine to override `__new__` in a subclass of a namedtuple class. https://github.com/python/cpython/blob/95f4e2ca03efbe020ae590108c022219008bbaf3/Lib/ssl.py#L452
> Fix an unnecessary allowlist entry in `ssl.pyi`

- stdlib/urllib/parse.pyi
- tests/stubtest_allowlists/py3_common.txt
Delete the fictitious classes `_ResultMixinBase`, `_SplitResultBytesBase` and `_ParseResultBytesBase`.
> Use generic `NamedTuple`s to clean up `urllib.parse`

- stdlib/argparse.pyi
I think we can reduce the number of overloads from 5 to 3 while still allowing all valid calls.
> `argparse`: simplify `parse_args` overloads

- stubs/influxdb-client/influxdb_client/client/write_api.pyi
And improve a few types, while we're about it. Fixes #9805.
> Fix stubtest for `influxdb-client`

- stdlib/_bisect.pyi
This PR changes the type of the first argument of `bisect_left` and `bisect_right` (and by design `bisect` as well) from the `bisect` module.
Indeed, a full `Sequence` is not needed, only the following is needed:
- If the `hi` parameter is `None`, only `__getitem__` and `__len__`
- Else, only `__getitem__`
I'm asking for `SupportsLenAndGetItem` instead of only `SupportsGetItem` in the second case to avoid an exponential number of `@overload`.
---
You can check that only these attributes are needed with the following code:
```py
from bisect import bisect, bisect_left, bisect_right
class Minimal:
content = 'abbbbcd'
def __len__(self):
return len(self.content)
def __getitem__(self, pos):
return self.content[pos]
obj = Minimal()
assert bisect(obj, 'b') == 5
assert bisect_left(obj, 'b') == 1 …
```
> bisect: don't require Sequences

- tests/stubtest_stdlib.py
Following #9734, there's now some fairly noisy output from pip if you run `stubtest_stdlib.py` locally, which I do quite a lot. This makes the output of the script hard to read. This PR suppresses the output from pip.
Prior to this PR:
```
(.venv) C:\Users\alexw\coding\typeshed>python tests/stubtest_stdlib.py
Collecting mypy==1.0
Using cached mypy-1.0.0-cp311-cp311-win_amd64.whl (8.8 MB)
Collecting typing-extensions>=3.10
Using cached typing_extensions-4.5.0-py3-none-any.whl (27 kB)
Collecting mypy-extensions>=0.4.3
Using cached mypy_extensions-1.0.0-py3-none-any.whl (4.7 kB)
Installing collected packages: typing-extensions, mypy-extensions, mypy
Successfully installed mypy-1.0.0 mypy-extensions-1.0.0 typing-extensions-4.5.0
[notice] A new release of pip available: 22.3.1 -> 23.0.1 …
```
> `stubtest_stdlib.py`: suppress output from pip

- stubs/pika/@tests/stubtest_allowlist.txt
- stubs/pika/METADATA.toml
- stubs/pika/pika/adapters/twisted_connection.pyi
Split off from #9494 , these changes are beneficial on their own, and necessitate less review.
> Add entries to `pika`'s stubtest_requirements

- stubs/babel/METADATA.toml
Babel now includes inline types with py.typed
Removal issue - #9829
Release: https://github.com/python-babel/babel/releases/tag/v2.12.0
Homepage: https://github.com/python-babel/babel
Diff: https://github.com/python-babel/babel/compare/v2.11.0...v2.12.0
> babel: Mark babel as obsolete since 2.12.0

- stubs/babel/METADATA.toml
Reverts python/typeshed#9830. We shouldn't mark the stubs as obsolete until the upstream package includes a `py.typed` file in wheels published to PyPI.
(A `py.typed` file exists on the GitHub `master` branch and in the tag for the latest release, but there's a packaging bug in `babel`: see https://github.com/python-babel/babel/pull/975.)
> Revert "babel: Mark babel as obsolete since 2.12.0"

- stubs/babel/METADATA.toml
I believe this is correct now that https://github.com/python-babel/babel/pull/975 is merged
Removal issue - https://github.com/python/typeshed/issues/9829
Release: https://github.com/python-babel/babel/releases/tag/v2.12.1
Homepage: https://github.com/python-babel/babel
Diff: https://github.com/python-babel/babel/compare/v2.12.0...v2.12.1
> babel: Mark babel as obsolete since 2.12.1

- stdlib/functools.pyi
- test_cases/stdlib/check_functools.py
There can be scenarios where `__name__` isn't set, as pointed out here: https://github.com/python/mypy/pull/14815#issuecomment-1453509611 but the same is true for `Callable`, so this has precedent.
> Add `__name__` to `_Wrapped` in functools

- stubs/tqdm/METADATA.toml
- stubs/tqdm/tqdm/std.pyi
Closes #9838
The diff between the two releases is here: https://github.com/tqdm/tqdm/compare/v4.64.1...v4.65.0
> Update `tqdm` stubs to 4.65.*

- requirements-tests.txt
- tests/pytype_test.py
Follow up to #9747
Superseeds https://github.com/python/typeshed/pull/9847#discussion_r1126830446 ( Closes #9847 ) by fixing the potentially `None` type error in a more principled way. The code already implicitly made this assert assumption.
CC. @AlexWaygood
> pytype_test.py: Fix typechecking errors following #9747

- stdlib/typing_extensions.pyi
This is included in typing_extensions as of v4.5.0 (which came out on the 15th of Feb)
> Add deprecated to typing_extensions

- stubs/psutil/psutil/_common.pyi
Found out about this the hard way.
The code path that allows None is here: https://github.com/giampaolo/psutil/blob/2da99502238852f18f74db05304e67a01ee77005/psutil/_pslinux.py#L923
> psutil: sconn.pid can be None

- .github/workflows/typecheck_typeshed_code.yml
- scripts/stubsabot.py
- tests/parse_metadata.py
- tests/typecheck_typeshed.py
- Remove an unnecessary `pyright: ignore` in stubsabot. It's fine to have slightly less strict typing here, since the types in `METADATA.toml` files are verified in `check_consistent.py`.
- Enable pyright's `reportUnknownMemberType` setting in `tests/parse_metadata.py`.
- Use more explicit `object` annotations in `parse_metadata.py`, to enforce stricter mypy typechecking.
- Use the lowest supported Python version as the default for mypy's `--python-version` argument in `tests/typecheck_typeshed.py`, rather than the version of Python you're running locally.
Cc. @Avasam, for interest :)
> Improve typechecking of the test suite

- stdlib/importlib/abc.pyi
Reason for this PR is that `InspectLoader.source_to_code` is just a wrapper around `compile`, so it supports a broader range of argument types than what is typed right now.
> importlib: align input data types in InspectLoader.source_to_code with invoked compile func inputs

- scripts/stubsabot.py
New `packaging` is strict and doesn't like paramiko's pokemon versioning scheme from 2004
Fixes #9865
> stubsabot: fix legacy version parsing

- stubs/redis/redis/lock.pyi
I added missing properties for `redis.lock.Lock`. If anything other needs to be done let me know.
Fixes #9851
> add missing properties for redis.lock.Lock (#9851)

- stubs/typed-ast/typed_ast/ast3.pyi
```pycon
>>> import typed_ast.ast3 as ast3
>>> x = ast3.parse('def foo(): ... # type: ignore[attr-defined]')
>>> ast3.dump(x)
"Module(body=[FunctionDef(name='foo', args=arguments(args=[], vararg=None, kwonlyargs=[], kw_defaults=[], kwarg=None, defaults=[]), body=[Expr(value=Ellipsis())], decorator_list=[], returns=None, type_comment=None)], type_ignores=[TypeIgnore(lineno=1, tag='[attr-defined]')])"
>>> y = ast3.parse('def foo(): ... # type: ignore')
>>> ast3.dump(y)
"Module(body=[FunctionDef(name='foo', args=arguments(args=[], vararg=None, kwonlyargs=[], kw_defaults=[], kwarg=None, defaults=[]), body=[Expr(value=Ellipsis())], decorator_list=[], returns=None, type_comment=None)], type_ignores=[TypeIgnore(lineno=1, tag='')])"
```
> Add missing field to `typed_ast.ast3.TypeIgnore`

- stdlib/signal.pyi
- tests/stubtest_allowlists/linux-py311.txt
I hope I added it in the right spot. It was added with Python 3.11 is only available on Linux, not MacOS.
> add signal.SIGSTKFLT

- .flake8
Several flake8 error codes are currently ignored for all `.pyi` files _except_ those ending with `_pb2.pyi`. This caused a bit of confusion in #9873. This PR makes it so that all codes ignored generally across typeshed are also ignored in `*_pb2.pyi` files
> flake8: ignore pyflakes codes in `*_pb2.pyi` files that are ignored in all other `.pyi` files

- stubs/appdirs/METADATA.toml
`appdirs` has officially been deprecated in favour of `platformdirs`, a fork of `appdirs` that is maintained and ships with a `py.typed` file.
See https://github.com/ActiveState/appdirs/commit/8734277956c1df3b85385e6b308e954910533884
> Mark `types-appdirs` as no longer updated

- stubs/backports.ssl_match_hostname/METADATA.toml
> Mark stubs for backports.ssl_match_hostname as no longer updated

- stubs/appdirs/METADATA.toml
- stubs/gdb/METADATA.toml
As spotted by @Akuli in https://github.com/python/typeshed/pull/9877#discussion_r1135654570
> Fix typos in `extra_description` fields

- stdlib/distutils/cmd.pyi
- stubs/setuptools/setuptools/_distutils/cmd.pyi
This is the first thing `__init__` does with distribution, and it was missing.
> fix: add missing distribution to distutils cmd

- stubs/setuptools/@tests/stubtest_allowlist.txt
- tests/stubtest_allowlists/py3_common.txt
These entries are causing more functions to be allowlisted than was intended: for example, none of these methods are generated methods, but they're all currently included by the `distutils.dist.Distribution.get_.*` entry:
https://github.com/python/typeshed/blob/2d990ee2f714c1902620586efed576b4f7edaba7/stdlib/distutils/dist.pyi#L106-L108
This caused a bit of confusion for me, as I was fiddling around with a stubtest patch, and expected stubtest to emit an error if I deleted this allowlist entry:
https://github.com/python/typeshed/blob/2d990ee2f714c1902620586efed576b4f7edaba7/tests/stubtest_allowlists/py3_common.txt#L89
...But stubtest didn't emit an error, because `distutils.dist.Distribution.get_command_obj` was _still_ allowlisted, even with that entry deleted, due to these regex entries …
> distutils/setuptools: Don't use wildcards for allowlist entries

- stdlib/logging/__init__.pyi
Closes https://github.com/python/typeshed/issues/9913
> Update logging LogRecord msg attribute

- stdlib/datetime.pyi
Note, that `fromisocalendar` does not support objects with `__index__` method.
> Support `SupportsIndex` in constructors for all `datetime` objects

- stubs/termcolor/termcolor.pyi
Follow up to https://github.com/python/typeshed/pull/9959#issuecomment-1485748287 CC @AlexWaygood
All defaults are `None`  https://github.com/termcolor/termcolor/blob/1.1.0/termcolor.py (also double-checked locally)
> Add default arguments for termcolor 1

- stubs/redis/redis/client.pyi
These parameters work and are passed down, but were not present in the type for from_url
> Add retry parameters to redis.client.from_url

- stubs/redis/redis/__init__.pyi
Resolves #9980
Adds the missing classes `CredentialProvider` and `UsernamePasswordCredentialProvider` to `__init__.py`, so using `redis.CredentialProvider` like written in the redis.py docs does not result in a type error.
> [redis] Add CredentialProvider types to __init__.pyi

- stubs/D3DShot/METADATA.toml
Link: https://github.com/SerpentAI/D3DShot
> [April 2023] `D3DShot` is an archived repo

- stdlib/dataclasses.pyi
Source https://github.com/python/cpython/blob/810d365b5eb2cf3043957ca2971f6e7a7cd87d0d/Lib/dataclasses.py#L1403
> `dataclasses.make_dataclass` has a new parameter in 3.12

- stdlib/sys.pyi
- tests/stubtest_allowlists/py3_common.txt
Adds a stub for [sys.thread_info](https://docs.python.org/3/library/sys.html#sys.thread_info)
This property was added in 3.3, should I add a version check? I haven't found any check for versions this old..
> Add a stub for sys.thread_info

- .github/workflows/mypy_primer.yml
`mypy_primer` currently runs on Python 3.10 in CI, meaning we don't have any `mypy_primer` coverage for PRs fiddling with `ExceptionGroup`s or other new features added in Python 3.11
> `mypy_primer`: Run on Python 3.11

- stdlib/unittest/mock.pyi
See the first entry in https://docs.python.org/3/whatsnew/3.9.html#removed
> unittest.mock.__version__ was removed in 3.9

- pyproject.toml
Mainly motivated to remove this [false positive](https://github.com/python/typeshed/pull/10052#discussion_r1167765606).
> Bump pyright version to 1.1.304

- stdlib/xml/dom/minidom.pyi
- test_cases/stdlib/check_xml.py
Fixes #10060.
This commit adds overloads for `xml.dom.minidom.Node.toxml` and `xml.dom.minidom.Node.toprettyxml` to return `str` when `encoding=None` and `bytes` otherwise. I also added return types when evaluating in Python < 3.9, which the stubs previously lacked; AFAICT the same return types should be valid there.
> stdlib/xml: fix return types for toxml/toprettyxml methods

- stdlib/logging/config.pyi
There's no need in `if sys.version` check here, all other places just use `typing_extensions` directly
> Simplify `logging.config` type imports

- stubs/hdbcli/hdbcli/dbapi.pyi
The name should be user and not username
> Fix wrong connection argument name

- stdlib/functools.pyi
- tests/stubtest_allowlists/py310.txt
- tests/stubtest_allowlists/py311.txt
- tests/stubtest_allowlists/py39.txt
The docs says that `cache_parameters()` function was added in 3.9: https://docs.python.org/3/library/functools.html#functools.lru_cache Source: https://github.com/python/cpython/blob/af530469954e8ad49f1e071ef31c844b9bfda414/Lib/functools.py#L512 But, `typeshed` does not have it.
Demo:
```python
>>> import functools
>>> functools.lru_cache(sum).cache_parameters()
{'maxsize': 128, 'typed': False}
```
> Add `cache_parameters` method to `_lru_cache_wrapper`

- stubs/paramiko/paramiko/client.pyi
- stubs/paramiko/paramiko/transport.pyi
Use Mapping instead of dict for better covariance.
Right now, mypy rejects a `dict[str, list[str]]` for the `disabled_algorithms` parameter of `connect`, because of the invariance of the `dict` type.
> Fix paramiko client parameter types

- stubs/influxdb-client/@tests/stubtest_allowlist.txt
- stubs/influxdb-client/METADATA.toml
Fixes #10089. The error was caused by the release of `urllib3==2.0.0`, which includes a `py.typed` file and inline type hints
> influxdb-client: fix stubtest

- scripts/runtests.py
CC @AlexWaygood 
This was changed in https://github.com/python/typeshed/pull/10002#discussion_r1157443671, but results in the following:
> Restore error output in runtests.py

- stdlib/_ctypes.pyi
- stdlib/ctypes/__init__.pyi
- tests/stubtest_allowlists/py3_common.txt
related to #8633 and https://github.com/python/typeshed/issues/8571#issuecomment-1221316973
#10111 and google/pytype#1411 (commit; https://github.com/google/pytype/commit/2e2088fcae3767802fe60f419499090db59f6c4f) have enabled us to move definitions from `__init__.pyi` to `_ctypes.pyi`.(https://github.com/python/typeshed/issues/8633#issuecomment-1528833567)
There are no longer causes CI to fail
So I'm going to contribute for the first time in several months.
I have moved the following stuffs.
- `_CDataMeta`
- `_CData`
- `_SimpleCData`
- `Array`
And I fixed `stubtest_allowlist` for `_ctypes.Array.`
> move some stuffs related to `_SimpleCData` from `ctypes/__init__.pyi` to `_ctypes.pyi`, as at runtime.

- stdlib/_ctypes.pyi
- stdlib/ctypes/__init__.pyi
- tests/stubtest_allowlists/py3_common.txt
related to #8633 and https://github.com/python/typeshed/issues/8571#issuecomment-1221316973
As in #10118, I would change the typestub definitions to the equivalent location as runtime.
I moved stuffs related to `Structure` and `Union`.
> move some stuffs related to `Structure` and `Union` from `ctypes/__init__.pyi` to `_ctypes.pyi`, as at runtime.

- .github/workflows/tests.yml
- pyrightconfig.json
- pyrightconfig.stricter.json
- pyrightconfig.testcases.json
Helps with https://github.com/python/typeshed/issues/10112 (an alternative fix to #10120). Install 3rd-party stub dependencies into an isolated environment, and use that for running pyright on typeshed, rather than installing the 3rd-party stub requirements into the same environment all our test requirements are installed in.
As with #10120, this doesn't fix the issue encountered in #9989 or #10090, but it does unblock #10058.
> Alternative fix for pyright CI issues

- stubs/Markdown/markdown/core.pyi
This instance variable is part of the API.
Changing it is [tested by Markdown's own test suite](https://github.com/Python-Markdown/markdown/blob/07b8b2c90a92c20fb0740d5527c6a219d2afb7ae/tests/test_apis.py#L884-L893) and used by [an included extension](https://github.com/Python-Markdown/markdown/blob/07b8b2c90a92c20fb0740d5527c6a219d2afb7ae/markdown/extensions/tables.py#L229-L230). It is also used by third-party extensions, for example by [pymdown-extensions](https://github.com/facelessuser/pymdown-extensions/blob/a8fb9666566dfb7e86094082860b5616885d35f4/pymdownx/util.py#L87-L100).
> Add Markdown.ESCAPED_CHARS to Markdown stubs

- stdlib/_ctypes.pyi
- stdlib/ctypes/__init__.pyi
- tests/stubtest_allowlists/py3_common.txt
related to #8633 and https://github.com/python/typeshed/issues/8571#issuecomment-1221316973
As in #10118, I would change the typestub definitions to the equivalent location as runtime.
I moved some classes and functions. They are byref-related-stuffs.
> move some byref-related-stuffs from `ctypes/__init__.pyi` to `_ctypes.pyi`, as at runtime.

- .flake8
- .pre-commit-config.yaml
- requirements-tests.txt
- Bump flake8-pyi to 23.5.0
- Reenable pyflakes's F821 check. With the latest flake8-pyi updates, there's no longer any false positives from this check when checking stub files.
- Exclude generated protobuf files from flake8 for now, until https://github.com/nipunn1313/mypy-protobuf/issues/523 is fixed and our protobuf stubs are regenerated. (I've filed https://github.com/nipunn1313/mypy-protobuf/pull/525 to fix it.)
> Bump flake8-pyi to 23.5.0; re-enable F821

- .flake8
Following https://github.com/PyCQA/flake8-pyi/pull/364, it seems like pyflakes's F822 check no longer has any false positives on stub files when flake8-pyi is installed!
Also, remove an outdated comment that I forgot to remove in #10143.
> flake8: Enable F822

- stubs/pyvmomi/METADATA.toml
This reverts commit 853d01d55ef5b5c7f0733e62c2e214be1d472657.
As per https://github.com/python/typeshed/issues/10149#issuecomment-1542015902, it seems like the stubs bundled with the upstream `pyvmomi` package aren't currently usable due to syntax errors. Given that marking the stubs as obsolete causes a line to be added to the PyPI description instructing users to uninstall `types-pyvmomi`, it seems like we should probably _not_ mark the stubs as obsolete until the upstream types are free of syntax errors.
> Revert "[stubsabot] Mark pyvmomi as obsolete since 8.0.1.0 (#10148)"

- stdlib/asyncio/tasks.pyi
Previously it was possible to pass `Awaitable` objects and `Generator`s into `Task.__init__`:
```python
>>> from asyncio import Task
>>> def gen():
...    yield
... 
>>> Task(gen())
<stdin>:1: DeprecationWarning: There is no current event loop
<Task pending name='Task-1' coro=<gen() running at <stdin>:1>>
```
Starting from `3.12` Python does not allow anything but coroutines in `Task.__init__`.
Proof:
```python
Python 3.12.0a7+ (heads/main-dirty:3cba61f111, May 15 2023, 12:56:55) [Clang 11.0.0 (clang-1100.0.33.16)] on darwin
>>> from asyncio import Task
>>> def gen():
...    yield 
... 
>>> Task(gen())
<stdin>:1: DeprecationWarning: There is no current event loop
File "<stdin>", line …
```
> Change `asyncio.Task.__init__` signature

- stubs/tzlocal/@tests/stubtest_allowlist.txt
- stubs/tzlocal/METADATA.toml
I don't see a reason to add stubs for this object: https://github.com/regebro/tzlocal/blob/2bd083aa15b642b23197ee55a82838877da481e6/tzlocal/utils.py#L15
It is not used, might be removed, should not be used by users of this lib.
Closes https://github.com/python/typeshed/pull/10186
> Bump `tzlocal` to `5.0.1`

- tests/pytype_test.py
This works around the pytype errors in https://github.com/python/typeshed/pull/10122.
> Treat entries on pytype_exclude_list as missing modules for pytype_test.

- stdlib/typing.pyi
- stdlib/typing_extensions.pyi
I'm deliberately updating `typing.TypedDict` and `typing_extensions.TypedDict`, but not `mypy_extensions.TypedDict`. The runtime implementation of `mypy_extensions.TypedDict` does not have the `__orig_bases__` attribute (and is quite out of date with the CPython `main` implementation in several other ways, as well).
> Add `__orig_bases__` to `TypedDict` classes

- stdlib/typing.pyi
- stdlib/typing_extensions.pyi
- The `_source` attribute was removed in Python 3.7. Delete it from the stubs.
- A bunch of attributes should be marked as `ClassVar`s, but currently aren't
- Add the `__orig_bases__` attribute to `typing_extensions.NamedTuple`
- Add the `__orig_bases__` attribute to `typing.NamedTuple` on py312+. It sometimes exists on Python <=3.11, but not always, so it's only safe to directly access it on py312+.
> Improve `NamedTuple` stubs

- stdlib/pathlib.pyi
- tests/stubtest_allowlists/win32-py310.txt
- tests/stubtest_allowlists/win32-py311.txt
- tests/stubtest_allowlists/win32-py37.txt
- tests/stubtest_allowlists/win32-py38.txt
- tests/stubtest_allowlists/win32-py39.txt
- tests/stubtest_allowlists/win32.txt
It was implemented in https://github.com/python/cpython/commit/29650fea9605bf1f48320487c6d5d6d70d97ad95
> `pathlib`: `is_mount()` is implemented on Windows on py312+

- stdlib/tempfile.pyi
- tests/stubtest_allowlists/py312.txt
Followup to https://github.com/python/typeshed/pull/10244#pullrequestreview-1459388192
> `tempfile`: more updates for py312

- stdlib/distutils/__init__.pyi
- tests/stubtest_stdlib.py
> Remove venv for stubtest stdlib

- tests/stubtest_allowlists/py311.txt
- tests/stubtest_allowlists/py312.txt
- tests/stubtest_allowlists/py3_common.txt
Mostly moves a bunch of things from the "should be fixed" to the "cannot be fixed" section and does some light alphabetisation
> Some light reorganisation of stubtest allowlists

- stdlib/dis.pyi
- stdlib/opcode.pyi
- tests/stubtest_allowlists/py312.txt
Demo:
```python
>>> import opcode
>>> opcode.hasarg
[90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 149, 150, 151, 152, 155, 156, 157, 162, 163, 164, 165, 168, 169, 170, 171, 172, 173, 174, 175, 176, 230, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 260, 261, 262, 263, 264, 265, 266]
>>> opcode.hasexc
[256, 257, 258]
>>> opcode.hasnargs
AttributeError: module 'opcode' has no attribute 'hasnargs'. Did you mean: 'hasarg'?
```
Source: …
> Update dis.pyi and opcode.pyi for Python3.12

- stdlib/_thread.pyi
- tests/stubtest_allowlists/py312.txt
```python
>>> import _thread
>>> _thread.daemon_threads_allowed
<built-in function daemon_threads_allowed>
>>> _thread.daemon_threads_allowed()
True
```
Source: https://github.com/python/cpython/blob/e830289c52cecd99e5e2291972d648e9b3452a51/Modules/_threadmodule.c#L1105
> Update _thread.pyi for Python3.12

- stdlib/_ctypes.pyi
- stdlib/ctypes/__init__.pyi
- tests/stubtest_allowlists/py312.txt
Source: https://github.com/python/cpython/blob/3.12/Lib/ctypes/__init__.py#L572-L577
Basically, it depends on `SIZEOF_TIME_T` value to set a proper alias type.
> Update ctypes stubs for Python3.12

- stdlib/http/__init__.pyi
- tests/stubtest_allowlists/py312.txt
I would prefer to leave `http.client` for later when https://github.com/python/cpython/pull/105628 is merged / rejected.
Source: https://github.com/python/cpython/blame/3.12/Lib/http/__init__.py#L34-L52
> Update `http/__init__.pyi` for Python3.12

- stdlib/email/feedparser.pyi
- stdlib/email/generator.pyi
I noticed that `email.feedparser.BytesFeedParser` and `email.generator.BytesGenerator` do not inherit from `email.feedparser.FeedParser` and `email.generator.Generator`, respectively, although they do in the actual stdlib module implementation. This PR amends that.
Update: reverted changes in `email.feedparser`, will try it again in a different PR.
> fix: use correct base classes for classes in email.generator

- stubs/psutil/psutil/__init__.pyi
The 'pio' named tuple is defined in tree variants: we import it depending on the platform so that io_counters() has the correct return type (following up on commit 85a6dd14e1e6c9c68d6de19294775b325ad903e1).
> psutil: import platform-specific 'pio' definitions

- .vscode/extensions.json
- .vscode/settings.default.json
It's been a while, and I've kept accumulating changes. I figured with the new `ms-python.mypy-type-checker` extension it might be a good time to provide an update to these recommendations.
> Update vscode recommended settings

- tests/stubtest_allowlists/py3_common.txt
- tests/stubtest_allowlists/win32.txt
It looks like the GitHub runners on MacOS and Linux now consistently get Python versions that include the CVE-2020-10735 patches, but the GitHub runners on Windows still don't.
> Make CVE-2020-10735 allowlist entries Windows-only

- .github/workflows/daily.yml
- .github/workflows/stubtest_stdlib.yml
Temporary workaround to resolve #10333.
Also, while we're here:
- Run stubtest on 3.12 as part of the daily tests, not just on PR runs
- Use the new `allow-prereleases` key with the setup-python action, so we won't need to manually drop the `-dev` suffix when 3.12.0 is released in the autumn.
> CI: Pin Python to 3.7.16 for stubtest runs on macos

- stubs/mock/mock/mock.pyi
This copies over the change from https://github.com/python/typeshed/pull/10325 to the unittest.mock backport library's stubs
> use ParamSpec in patch in mock stubs

- stdlib/enum.pyi
- tests/stubtest_allowlists/py312.txt
`enum` added a few new things; an allowlist entry is now unused
> Fix stubtest for py312b3

- stdlib/codecs.pyi
introduced in https://bugs.python.org/issue19619
> add `_is_text_encoding` attribute of CodecInfo (3.4+)

- scripts/stubsabot.py
flake8-plugin-utils released a new version with a `py.typed` file yesterday. However, stubsabot didn't file a PR to mark our stubs for flake8-plugin-utils as obsolete, because the `py.typed` file was added in v1.3.3. Our stubs are pinned to `1.3.*`:
https://github.com/python/typeshed/blob/93b4060cd4a6bd45a48fc70c16adc4a69edc9114/stubs/flake8-plugin-utils/METADATA.toml#L1
This led stubsabot to conclude that our stubs were up to date with the runtime package, so stubsabot exited early from the `determine_action` function before it even got to the bit where we try to figure out if the stubs package is obsolete or not.
> Stubsabot: mark stubs as obsolete, even if the `py.typed` file was added in a micro version

- stdlib/asyncio/base_events.pyi
- stdlib/asyncio/events.pyi
This just returns `_app_transport`:
https://github.com/python/cpython/blob/dba72175116373c1d15e25d84c88b516daf9f5c4/Lib/asyncio/base_events.py#L1288
Which will be set to `None` on init and after connection lost:
https://github.com/python/cpython/blob/dba72175116373c1d15e25d84c88b516daf9f5c4/Lib/asyncio/sslproto.py#L412
Related bug report:
https://github.com/aio-libs/aiohttp/issues/3355
> Fix return type of start_tls()

- requirements-tests.txt
Our CI is very red on `main` at the moment, due to the release of typing_extensions 4.6.3 (see #10383). #10344 is the fix for this, but that PR breaks pytype. For now, let's just pin to 4.6.3 to get CI green again.
> Pin typing_extensions to 4.6.3

- .github/workflows/typecheck_typeshed_code.yml
- requirements-tests.txt
- tests/README.md
- tests/pytype_test.py
- tests/typecheck_typeshed.py
My hope is that this will resolve the pytype failures in #10389. It's probably a good idea to do this anyway, though, since `pkg_resources` is deprecated.
> pytype_test.py: Use importlib.metadata instead of pkg_resources

- .github/workflows/typecheck_typeshed_code.yml
- tests/README.md
- tests/pytype_test.py
- tests/typecheck_typeshed.py
Another attempt at resolving the pytype CI errors in #10389. I've done a lot of testing via GitHub Actions on my fork, and I'm _pretty_ sure this gets the CI green on #10389. I don't know why these importlib APIs seem to be able to find the packages associated with `Flask-SQLAlchemy` when `importlib.metadata.packages_distributions()` doesn't seem able to, but that does seem to be the case.
Happily, these changes mean that our test suite can once again be run on Python 3.9, which is a nice-to-have.
> Further improve non-types dependency handling in `pytype_test.py`

- stdlib/http/client.pyi
- tests/stubtest_allowlists/py312.txt
Source: https://github.com/python/cpython/blob/3.12/Lib/http/client.py#L1441-L1443
I will change `http.client.HTTPConnection.get_proxy_response_headers` after we will decide on https://github.com/python/cpython/pull/105628
> Fix signature of `http.client.HTTPSConnection` for Python3.12

- stdlib/inspect.pyi
- tests/stubtest_allowlists/py312.txt
Source: https://github.com/python/cpython/blob/3.12/Lib/inspect.py
> Update `inspect` for Python3.12

- stdlib/socket.pyi
- tests/stubtest_allowlists/darwin-py311.txt
- tests/stubtest_allowlists/darwin-py312.txt
```
Python 3.11.3 (main, Jun 21 2023, 16:11:30) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
>>> import socket
>>> socket.TCP_CONNECTION_INFO
262
```
> Add missing `TCP_CONNECTION_INFO` to `socket` module

- stubs/Pillow/PIL/Image.pyi
The `color` value can be a `tuple[int, int]` as seen in the test case [1] from the Pillow project.
For example when using the `LA` mode in a call to `PIL.Image.new()`:
PIL.Image.new("LA", size=(200, 200), color=(0xFF, 0))
`color` can be a `tuple[int, int]`
[1] https://github.com/python-pillow/Pillow/blob/3ee925915085ee0f7ad72fbede5d9a9e6ea902a7/Tests/test_image_access.py#L376
> Pillow: Add `tuple[int, int]` to `_Color` TypeAlias

- stubs/typed-ast/METADATA.toml
The [`typed-ast` repo](https://github.com/python/typed_ast) has been archived, and has a notice on its README saying that it is no longer maintained. Mypy no longer depends on typed-ast, and black is about to drop its dependency (https://github.com/psf/black/pull/3765).
> Mark `types-typed-ast` as no longer updated

- stubs/stripe/stripe/api_resources/__init__.pyi
This is a quick follow up to #10323. I failed to add the new type to `__init__.py` preventing the new type to be exposed for type checking.
> Stripe: add shipping_rate to `__init__.py`

- stubs/Pillow/PIL/Image.pyi
I don't think it was correct for #10411 to mark MAX_IMAGE_PIXELS as final. Quoting my reasoning from https://github.com/python/typeshed/pull/10411#discussion_r1261206232:
> According to [pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.open](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.open):
>
>>    This threshold can be changed by setting [MAX_IMAGE_PIXELS](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.MAX_IMAGE_PIXELS). It can be disabled by setting Image.MAX_IMAGE_PIXELS = None.
>
> I can't see any mention of this [MAX_IMAGE_PIXELS] in [pillow.readthedocs.io/en/stable/releasenotes/10.0.0.html](https://pillow.readthedocs.io/en/stable/releasenotes/10.0.0.html) either.
> Pillow: mark MAX_IMAGE_PIXELS as non-final

- stdlib/linecache.pyi
An entry of linecache.cache is either a lazy entry or a full entry. The full entries are typed correctly but the lazy entry is supposed to be a one-tuple consisting of a function that takes zero arguments and returns either a string or None:
Here you can see that the assigned value is a one-tuple with a callable: https://github.com/python/cpython/blob/v3.11.4/Lib/linecache.py#L178-L181
Here you can see that the callable is invoked with zero arguments and the expected output is a string or None:
https://github.com/python/cpython/blob/v3.11.4/Lib/linecache.py#L105-L115
> Fix type of linecache.cache

- stdlib/tkinter/ttk.pyi
added Iterable[int] to Treeview columns typing hint
> Accept ints for tkinter.ttk.Treeview columns

- stdlib/unittest/mock.pyi
- test_cases/stdlib/check_unittest.py
> Fix @patch when `new` is missing

- stubs/stripe/@tests/stubtest_allowlist.txt
- stubs/stripe/stripe/api_resources/__init__.pyi
- stubs/stripe/stripe/api_resources/payment_link.pyi
Adds type checking for the [PaymentLink](https://stripe.com/docs/api/payment_links/payment_links) resource, which is defined in stripe-python [here](https://github.com/stripe/stripe-python/blob/4829b884cf817dacd4d3217e40560693e26a7f8f/stripe/api_resources/payment_link.py).
Similar to https://github.com/python/typeshed/pull/10323 and https://github.com/python/typeshed/pull/10416
> [stripe] Add type for PaymentLink

- pyproject.toml
It was just released: https://github.com/microsoft/pyright/releases/tag/1.1.318
> Bump `pyright` version to `1.1.318`

- stdlib/unittest/mock.pyi
- stubs/mock/mock/mock.pyi
Related https://github.com/python/typeshed/pull/10472
> Add a more precise signature for `AsyncMock.reset_mock()`

- .pre-commit-config.yaml
- CONTRIBUTING.md
- pyproject.toml
- requirements-tests.txt
- scripts/create_baseline_stubs.py
- scripts/generate_proto_stubs.sh
- scripts/runtests.py
- stdlib/typing_extensions.pyi
- tests/check_consistent.py
The aim of this PR is to make it easier for new contributors to typeshed to comply with our -- at times fairly stringent! -- style guide. For large PRs (e.g. #10446, or #10355), this can be quite difficult. Ruff has a number of autofixes that we can use to help out with this task, and it's extremely fast.
Unlike most projects, we're not likely to ever _switch_ from flake8 to ruff -- even if ruff implemented the full set of flake8-pyi rules and had exactly the same behaviour as flake8-pyi for all of them, it's useful for us to be able to add new rules to our own linter whenver we want to. However, there's nothing stopping us from having ruff as part of our CI _as well as_ flake8.
Since (in my opinion) we're _only_ interested in the autofixes here, I've only enabled a few rules that have …
> Add some ruff autofixes to CI

- pyproject.toml
- scripts/create_baseline_stubs.py
Using a slightly-tweaked version of @Akuli's script from #10489 (which was itself a slightly tweaked version of @srittau's script from #10488!).
> Auto-add upstream URLs in `create_baseline_stubs.py`

- stdlib/http/client.pyi
From https://docs.python.org/3/library/urllib.request.html#module-urllib.response:
> Functions defined by this module are used internally by the [urllib.request](https://docs.python.org/3/library/urllib.request.html#module-urllib.request) module. The typical response object is a [urllib.response.addinfourl](https://docs.python.org/3/library/urllib.request.html#urllib.response.addinfourl) instance:
The response of a [`urllib.request.urlopen`](https://docs.python.org/3/library/urllib.request.html#urllib.request.urlopen) for HTTP/HTTPS urls is a [`http.client.HTTPResponse`](https://docs.python.org/3/library/http.client.html#http.client.HTTPResponse).  Thus, I think `HTTPResponse` needs to conform to the interface of `addinfourl`.  Currently, `HTTPResponse` is missing the `url` field, which …
> Added `url: str` to `http.client.HTTPResponse`

- .pre-commit-config.yaml
- CONTRIBUTING.md
- pyproject.toml
- requirements-tests.txt
- scripts/runtests.py
- tests/check_consistent.py
Pycln pins its dependencies very tightly, which is annoying when you want to install all your tools into a single environment, as we do, and has caused us minor issues in the past.  It's currently blocking us from upgrading to the latest version of pytype (see https://github.com/python/typeshed/pull/10344#issuecomment-1646200943), which in turn is blocking us from updating our typing_extensions stubs.
Ruff also provides this autofix functionality, so let's stop using pycln and just enable the relevant ruff rule in CI.
> Use ruff, not pycln, for removing unused imports

- stubs/s2clientprotocol/METADATA.toml
These stubs were added yesterday in #10372, and I forgot that we had just added this new metadata field
> Add `upstream_repository` to metadata for `s2clientprotocol`

- tests/check_consistent.py
Following https://github.com/python/typeshed/commit/e86c61da86f564b39a8c4415a2d513758e62b0fd, pyright now complains that the second argument to `hook.get` is of type `list[Unknown]`, because we have extremely strict pyright settings in CI for checking our own test suite.
> Fix typechecking of our own test suite following change to `dict.get`

- stdlib/argparse.pyi
The argument `nargs` in stdlib `argparse.ArgumentParser.add_argument` could be `None`, according to the documentation
https://docs.python.org/3/library/argparse.html#nargs 
and also the source code https://github.com/python/cpython/blob/3.11/Lib/argparse.py 
The the absence of `None` cause false negative in code that is accepted
> `nargs` could be `None` in `add_argument` method

- stdlib/socket.pyi
PR moved from https://github.com/python/mypy/pull/15811
Looks like this was backported from 3.7 to 3.6: https://bugs.python.org/issue26273 and https://github.com/python/cpython/blob/46366ca0486d07fe94c70d00771482c8ef1546fc/Doc/whatsnew/3.6.rst
> Add missing `TCP_USER_TIMEOUT` to `socket` module

- stubs/JACK-Client/METADATA.toml
- stubs/WebOb/METADATA.toml
- stubs/beautifulsoup4/METADATA.toml
- stubs/braintree/METADATA.toml
- stubs/cffi/METADATA.toml
- stubs/docopt/METADATA.toml
- stubs/docutils/METADATA.toml
- stubs/gdb/METADATA.toml
- stubs/hdbcli/METADATA.toml
- stubs/humanfriendly/METADATA.toml
- stubs/ibm-db/METADATA.toml
- stubs/inifile/METADATA.toml
- stubs/paho-mqtt/METADATA.toml
- stubs/passlib/METADATA.toml
- stubs/pexpect/METADATA.toml
- stubs/protobuf/METADATA.toml
- stubs/pyaudio/METADATA.toml
- stubs/pycurl/METADATA.toml
- stubs/python-nmap/METADATA.toml
- stubs/pytz/METADATA.toml
- stubs/untangle/METADATA.toml
- tests/parse_metadata.py
I was navigating https://alexwaygood.github.io/typeshed-stats/stats-csv/ for unrelated reasons and noticed a lot of missing upstream source / url, and decided it'd be fun to go on a hunt.
The only actually closed-source project seems to be SAP's hdbcli.
Most of these were linked in their docs (although sometimes very obscure). Except for python-ini which has no documentation and no link on PyPI. But it's the same author so I assume it's the right repository.
I've updated the `upstream_repository` field validation to make the GDB change pass. I believe this respects the original intent of avoiding extra query params and fragments that may have accidentally been copied. And added more detailed error messages.
> Fill in all missing `upstream_repository`

- .vscode/extensions.json
- .vscode/settings.default.json
I recently noticed typeshed started using Ruff. This will ensure that Ruff' autofixes are run correctly and automatically by the IDE VSCode. As well as automatically recommending the extension for users.
I've been using these configurations for a few days now without issues. They are also the same configuration I use in my own projects that use Ruff all the way (except for `"ruff.organizeImports": false`, which is specific to typeshed relying on isort for its import sorting)
> Configure Ruff for VSCode

- stubs/openpyxl/openpyxl/cell/text.pyi
- stubs/openpyxl/openpyxl/chart/area_chart.pyi
- stubs/openpyxl/openpyxl/chart/axis.pyi
- stubs/openpyxl/openpyxl/chart/bar_chart.pyi
- stubs/openpyxl/openpyxl/chart/chartspace.pyi
- stubs/openpyxl/openpyxl/chart/label.pyi
- stubs/openpyxl/openpyxl/chart/line_chart.pyi
- stubs/openpyxl/openpyxl/chart/pie_chart.pyi
- stubs/openpyxl/openpyxl/chart/series.pyi
- stubs/openpyxl/openpyxl/chart/surface_chart.pyi
- stubs/openpyxl/openpyxl/drawing/effect.pyi
- stubs/openpyxl/openpyxl/drawing/spreadsheet_drawing.pyi
- stubs/openpyxl/openpyxl/drawing/xdr.pyi
- stubs/openpyxl/openpyxl/worksheet/_read_only.pyi
- stubs/openpyxl/openpyxl/worksheet/_write_only.pyi
- stubs/openpyxl/openpyxl/worksheet/merge.pyi
- stubs/openpyxl/openpyxl/worksheet/pagebreak.pyi
Has overlap with #9511, so should reduce changes there.
I searched the openpyxl source code for instances of a class attribute being explicitly set as another class'.
In most cases, those will be descriptors, which pyright will have issues with re-assigning. Luckily, they'll also mostly refer to parent definitions. For typing purposes, this can be simplified to just not including them. I still left them in as comments to make it a bit more explicit.
Similarly, mypy has issues with re-assigning properties (see https://github.com/python/mypy/issues/13975) so I explicitly redefined those when they came from a non-parent class.
> openpyxl: Class attributes set explicitly as another class'

- stdlib/ssl.pyi
SSLContext `wrap_socket` and `wrap_bio` functions accept `bytes` as well as strings.
> SSL `wrap_socket` and `wrap_bio` accept `bytes` as well

- scripts/runtests.py
We only support running mypy using 3.8+ up, since mypy 1.5 dropped support for running with Python 3.7.
Closes: #10599
> Use Python 3.8 in runtests.py

- tests/parse_metadata.py
- tests/stubtest_third_party.py
**(1) Give a nicer error message if you try to run stubtest on non-existent stubs.**
Before:
```pytb
typeshed>python tests/stubtest_third_party.py fpdf
File "C:\Users\alexw\coding\typeshed\tests\stubtest_third_party.py", line 263, in <module>
main()
File "C:\Users\alexw\coding\typeshed\tests\stubtest_third_party.py", line 256, in main
if not run_stubtest(dist, verbose=args.verbose, specified_platforms_only=args.specified_platforms_only):
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\alexw\coding\typeshed\tests\stubtest_third_party.py", line 21, in run_stubtest
metadata = read_metadata(dist_name)
^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\alexw\coding\typeshed\tests\parse_metadata.py", line …
```
> Minor improvements to `stubtest_third_party.py`

- stdlib/asyncio/tasks.pyi
See also comment on https://github.com/python/typeshed/pull/10532#issuecomment-1693670617 how this was introduced.
> The name param in asyncio.Task.__init__ is optional

- scripts/stubsabot.py
It looks like all the timeouts are happening in the get_diff_info code. I don't think we really need to validate the URL exists. In any case, we probably end up hitting a very similar endpoint later in analyze_diff.
> stubsabot: avoid validating diff info url

- stdlib/asyncio/tasks.pyi
https://docs.python.org/3.10/library/asyncio-task.html#asyncio.wait
> Run awaitable objects in the aws iterable concurrently and block until the condition specified by `return_when`.
https://docs.python.org/3.11/library/asyncio-task.html#asyncio.wait
> Run Future and Task instances in the aws iterable concurrently and block until the condition specified by `return_when`.
https://github.com/python/cpython/blob/v3.11.0/Lib/asyncio/tasks.py#L414-L415
```python
if any(coroutines.iscoroutine(f) for f in fs):
raise TypeError("Passing coroutines is forbidden, use tasks explicitly.")
```
> `asyncio.wait()` no longer allows awaitables in 3.11

- scripts/create_baseline_stubs.py
Currently any contributors adding stubs generated using `create_baseline_stubs.py` have the pre-commit bot instantly pushing to their PR branch to add a newline at the end of the METADATA.toml file. See https://github.com/python/typeshed/pull/10614 for an example!
> `create_baseline_stubs.py`: ensure generated METADATA.toml files end with a newline

- scripts/runtests.py
- tests/README.md
This is an attempt to clear up some of the confusion in https://github.com/python/typeshed/pull/10612#discussion_r1306440772 (cc. @josephcourtney). `tests/README.md` already has a note to this effect in the section on `stubtest_stdlib.py`, so this just adds a note to the `scripts/runtests.py` docs
> runtests.py: note that stdlib stubtest might fail

- stdlib/_ctypes.pyi
- stdlib/ctypes/wintypes.pyi
- stubs/pyserial/serial/tools/list_ports_windows.pyi
- stubs/pyserial/serial/win32.pyi
> `_CField` as a generic descriptor protocol

- tests/check_new_syntax.py
We don't want to start using PEP-570 syntax in typeshed yet, because we don't want to unnecessarily break compatibility with Python 3.7 (#10113) -- mypy users will not be able to check their code using `--python-version 3.7` after we start using PEP-570 syntax in typeshed. However, now that we no longer run mypy or stubtest in CI using Python 3.7, none of our CI fails if somebody proposes using PEP-570 syntax in a PR (e.g. https://github.com/python/typeshed/pull/10646#discussion_r1312919259 wouldn't have been caught if it hadn't been for @srittau's sharp eye!).
This PR proposes adding a simple lint to `check_new_syntax.py` so that we don't accidentally start using PEP-570 syntax in typeshed before we formally drop support for Python 3.7.
> Add a lint forbidding PEP-570 syntax

- stubs/Pillow/PIL/ImageFont.pyi
`FreeTypeFont.getlength` in Pillow is returned as float
Reference: https://github.com/python-pillow/Pillow/blob/main/src/PIL/ImageFont.py#L263
> Fix typing of FreeTypeFont.getlength

- scripts/stubsabot.py
Fixes #10666
If our specifier was an exact match, we now exact match everything
> Fix stubsabot handling of post releases

- tests/stubtest_allowlists/darwin-py312.txt
- tests/stubtest_allowlists/linux-py312.txt
- tests/stubtest_allowlists/py312.txt
Fixes the stdlib parts of #10675
> Delete unused allowlist entries

- stubs/openpyxl/openpyxl/worksheet/cell_range.pyi
> Fix: pyopenxl: CellRange: title should not be required

- pyrightconfig.stricter.json
- stubs/requests-oauthlib/METADATA.toml
- stubs/requests-oauthlib/requests_oauthlib/__init__.pyi
- stubs/requests-oauthlib/requests_oauthlib/compliance_fixes/__init__.pyi
- stubs/requests-oauthlib/requests_oauthlib/compliance_fixes/douban.pyi
- stubs/requests-oauthlib/requests_oauthlib/compliance_fixes/ebay.pyi
- stubs/requests-oauthlib/requests_oauthlib/compliance_fixes/facebook.pyi
- stubs/requests-oauthlib/requests_oauthlib/compliance_fixes/fitbit.pyi
- stubs/requests-oauthlib/requests_oauthlib/compliance_fixes/instagram.pyi
- stubs/requests-oauthlib/requests_oauthlib/compliance_fixes/mailchimp.pyi
- stubs/requests-oauthlib/requests_oauthlib/compliance_fixes/plentymarkets.pyi
- stubs/requests-oauthlib/requests_oauthlib/compliance_fixes/slack.pyi
- stubs/requests-oauthlib/requests_oauthlib/compliance_fixes/weibo.pyi
- stubs/requests-oauthlib/requests_oauthlib/oauth1_auth.pyi
- stubs/requests-oauthlib/requests_oauthlib/oauth1_session.pyi
- stubs/requests-oauthlib/requests_oauthlib/oauth2_auth.pyi
- stubs/requests-oauthlib/requests_oauthlib/oauth2_session.pyi
These are mostly still baseline stubs since the same is true for `types-oauthlib`, however some simple things have been filled in/copied over from `types-requests`.
Source can be found at: https://github.com/requests/requests-oauthlib/blob/v1.3.1/requests_oauthlib/__init__.py
Docs here: https://requests-oauthlib.readthedocs.io/en/v1.3.1/
> Add stubs for requests-oauthlib

- stubs/google-cloud-ndb/METADATA.toml
> Always install `six` when stubtesting `types-google-cloud-ndb`

- stubs/redis/METADATA.toml
> [redis] Don't recommend uninstalling types-redis

- stdlib/csv.pyi
Fixes https://github.com/python/typeshed/issues/10145
I'm not sure about the `Any` part, but as iterating over the `DictReader` gives a `dict[_T | Any, str | Any]`, figured I would use the same types
> Update `restval`/`restkey` types in `csv.DictReader`

- requirements-tests.txt
- stdlib/typing_extensions.pyi
- tests/stubtest_allowlists/py310.txt
- tests/stubtest_allowlists/py311.txt
- tests/stubtest_allowlists/py38.txt
- tests/stubtest_allowlists/py39.txt
- tests/stubtest_allowlists/py3_common.txt
This fixes the stdlib stubtest failures seen on the `main` branch, e.g. https://github.com/python/typeshed/actions/runs/6220458928
> Update `typing_extensions` stubs for v4.8.0

- stdlib/abc.pyi
Add `__slots__` to the declaration of `abc.ABC` to properly reflect its implementation.
This allows Pyright to properly check ABCs, see https://github.com/microsoft/pyright/issues/5976 for more details
> define slots on abc.ABC

- tests/pytype_test.py
From my reading of https://peps.python.org/pep-0561/#stub-only-packages, I _think_ this is all the normalisation we need to do here in order to get `pytype_test.py` passing when a typeshed stubs package has `pandas-stubs` as a dependency. It's a somewhat more principled solution than the special-casing @hamdanal currently has in https://github.com/python/typeshed/pull/10721/files#diff-b08f977b5767c8fef257d9641aa0e00aa67abbc5fac2ad25824880c7a50995c4R153-R154 :D
> pytype_test.py: Handle non-typeshed requirements that are stub-only packages

- stdlib/logging/handlers.pyi
This seems like a small change so I've skipped opening an issue.
The only way of knowing whether a `logging.handlers.QueueListener` has already been started is by checking that the `_thread` attribute has been set to a non-`None` value. This attribute is not included in type stubs, so running `mypy` on a code like this will raise a `"QueueListener" has no attribute "_thread"` error, even though it's perfectly valid:
```python
import logging.handlers
import queue
LOG_QUEUE: queue.Queue = queue.Queue(-1)
QUEUE_LISTENER: logging.handlers.QueueListener = logging.handlers.QueueListener(LOG_QUEUE, logging.StreamHandler())
def check():
assert hasattr(QUEUE_LISTENER, "_thread")
if QUEUE_LISTENER._thread is None:  # error: "QueueListener" has no attribute "_thread"
QUEUE_LISTENER.start()
``` …
> feat: Add _thread attribute for logging.handlers.QueueListener

- stdlib/os/__init__.pyi
- tests/stubtest_allowlists/win32-py311.txt
- tests/stubtest_allowlists/win32-py312.txt
closes https://github.com/python/typeshed/issues/10242
> Add os.EX_OK for Python 3.11

- stubs/PyScreeze/pyscreeze/__init__.pyi
Noticed the union was incomplete in https://github.com/python/typeshed/pull/10707#issuecomment-1728217932
`_locateAll_python` no longer exists and is no longer relevant to mention in a comment
Fixed the location of the first `# _locateAll_opencv` comment
Update comment about cv2 Mat alias now that it properly exists in opencv-python
> Update pyscreeze methods reusing `locateAll`

- stubs/psycopg2/METADATA.toml
- stubs/psycopg2/psycopg2/__init__.pyi
```python
>>> import psycopg2
>>> psycopg2.extensions
<module 'psycopg2.extensions' from '/tmp/.venv/lib/python3.10/site-packages/psycopg2/extensions.py'>
>>> psycopg2.errors
<module 'psycopg2.errors' from '/tmp/.venv/lib/python3.10/site-packages/psycopg2/errors.py'>
```
> Complete psycopg2

- stdlib/sys.pyi
It is documented as `Literal`: https://docs.python.org/3/library/sys.html#sys.version_info
> Use `Literal` values for `sys.version_info.release_level`

- CONTRIBUTING.md
Replace `libraryname` with `''` in the script of CONTRIBUTING.md to avoid installation of [`libraryname`](https://pypi.org/project/libraryname/).
> CONTRIBUTING.md: Avoid user mistake in the script; small fixes

- stubs/jsonschema/METADATA.toml
> Declare that `types-jsonschema` requires Python 3.8+

- stdlib/os/__init__.pyi
- stdlib/posix.pyi
- tests/stubtest_allowlists/darwin-py312.txt
Docs:
```
.. data:: PRIO_DARWIN_THREAD
PRIO_DARWIN_PROCESS
PRIO_DARWIN_BG
PRIO_DARWIN_NONUI
Parameters for the :func:`getpriority` and :func:`setpriority` functions.
.. availability:: macOS
.. versionadded:: 3.12
```
> Update `os` and `posix` to python 3.12 on darwin

- stdlib/ssl.pyi
- tests/stubtest_allowlists/linux-py312.txt
Docs say:
```
.. data:: OP_ENABLE_KTLS
Enable the use of the kernel TLS. To benefit from the feature, OpenSSL must
have been compiled with support for it, and the negotiated cipher suites and
extensions must be supported by it (a list of supported ones may vary by
platform and kernel version).
Note that with enabled kernel TLS some cryptographic operations are
performed by the kernel directly and not via any available OpenSSL
Providers. This might be undesirable if, for example, the application
requires all cryptographic operations to be performed by the FIPS provider.
This option is only available with OpenSSL 3.0.0 and later.
```
> `ssl.OP_ENABLE_KTLS` should exist on linux

- .github/workflows/daily.yml
We skip 2/3 jobs in the daily test when running on forks:
https://github.com/python/typeshed/blob/b23042e854e79b54c4d2c609cf1e12a2357335a9/.github/workflows/daily.yml#L33
https://github.com/python/typeshed/blob/b23042e854e79b54c4d2c609cf1e12a2357335a9/.github/workflows/daily.yml#L59
But we missed this condition for the stub-uploader job
Fixes #10781
> Skip all parts of the daily test on forks of typeshed

- stdlib/tty.pyi
- tests/stubtest_allowlists/darwin-py312.txt
- tests/stubtest_allowlists/linux-py312.txt
Source: https://github.com/python/cpython/blob/3.12/Lib/tty.py
> Update `tty` to python 3.12

- stdlib/mmap.pyi
- tests/stubtest_allowlists/linux-py311.txt
- tests/stubtest_allowlists/linux-py312.txt
Source:
```c
#ifdef MAP_STACK
// Mostly a no-op on Linux and NetBSD, but useful on OpenBSD
// for stack usage (even on x86 arch)
ADD_INT_MACRO(module, MAP_STACK);
#endif
```
Docs:
```rst
.. versionadded:: 3.11
Added :data:`MAP_STACK` constant.
```
> Add `MAP_STACK` to `mmap` module

- stdlib/termios.pyi
- stdlib/tty.pyi
Also add `termios._AttrReturn` type alias to be used in tty
> [tty] py312: Fix return types of set(raw|cbreak)

- stdlib/socket.pyi
- tests/stubtest_allowlists/darwin.txt
Local demo:
```python
Python 3.13.0a0 (heads/main:98c0c1de18e, Sep 28 2023, 09:21:43) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
>>> import socket
>>> socket.SYSPROTO_CONTROL
2
>>> socket.PF_SYSTEM
32
```
> Re-export `SYSPROTO_CONTROL` and `PF_SYSTEM` in `socket` on macos

- stdlib/_ast.pyi
```pycon
>>> import ast
>>> m = ast.parse("type ListOrSet[T] = list[T] | set[T]")
>>> print(m.body[0].__match_args__)
('name', 'type_params', 'value')
```
> fix `__match_args__` attribute name

- stubs/openpyxl/openpyxl/descriptors/serialisable.pyi
From https://github.com/python/typeshed/issues/8217#issuecomment-1742239764
Unless you think there's documentation/semantic value in keeping the union. kindof like how sometimes we have redundant unions with `None` or `Any`. In which case I'll update the comment to make that obvious. Although pyright/Pylance seem to completely strip it out.
Not going with `def tagname(self) -> NoReturn: ...` for the reason listed in the comment.
> Remove redundant `NoReturn` union in openpyxl

- stdlib/select.pyi
- tests/stubtest_allowlists/darwin.txt
```
» ./python.exe
Python 3.13.0a0 (heads/main:98c0c1de18e, Sep 28 2023, 09:21:43) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
>>> import select
>>> select.POLLRDHUP
AttributeError: module 'select' has no attribute 'POLLRDHUP'. Did you mean: 'POLLHUP'?
```
And stable Python:
```
Python 3.11.5 (main, Aug 24 2023, 15:09:45) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
>>> import select
>>> select.POLLRDHUP
AttributeError: module 'select' has no attribute 'POLLRDHUP'. Did you mean: 'POLLHUP'?
```
See …
> `select.POLLRDHUP` does not exist on macos

- stdlib/os/__init__.pyi
- stdlib/posix.pyi
- tests/stubtest_allowlists/darwin.txt
- tests/stubtest_allowlists/linux.txt
Mac demo:
```
>>> import posix
>>> posix.NGROUPS_MAX
16
>>> posix.EX_NOTFOUND
AttributeError: module 'posix' has no attribute 'EX_NOTFOUND'
>>> 
```
> Fix allowlists on linux and macos for `posix` module

- stubs/bleach/bleach/html5lib_shim.pyi
The missing __init__ method caused `Filter` to be incompatible with the `_Filter` protocol, preventing valid initialization of `Cleaner` instances.
Closes: #10834
> [bleach] Add html5lib_shim.Filter__init__/__iter__

- stubs/influxdb-client/METADATA.toml
- stubs/requests/METADATA.toml
As requested in https://github.com/python/typeshed/issues/10825#issuecomment-1748635927
> `types-requests`, `types-influxdb-client`: add note to the PyPI readme about the `urllib3` pin

- stubs/pyinstaller/@tests/stubtest_allowlist.txt
This prevents stubtest from ignoring errors in modules that are stubbed.
> stubtest: List ignored `building` sub-modules explicitly

- .github/workflows/daily.yml
> Use Python 3.11 for the stub_uploader tests in the daily test

- .github/workflows/daily.yml
- .github/workflows/meta_tests.yml
- .github/workflows/mypy_primer.yml
- .github/workflows/stubsabot.yml
- .github/workflows/stubtest_stdlib.yml
- .github/workflows/stubtest_third_party.yml
- .github/workflows/tests.yml
- .pre-commit-config.yaml
- requirements-tests.txt
- stdlib/argparse.pyi
We could possibly also upgrade our `aiohttp` pin to 3.9.0b0, which supports Python 3.12. Looks like there are one or two regressions in the beta, though (https://github.com/aio-libs/aiohttp/issues/7675), so I'm inclined to say we should hold off on that for now.
> Bump various test dependency pins

- scripts/runtests.py
This makes the script usable for packages that do not support the minimum python version hardcoded in the script.
Another part of #10722
> Allow specifying python version in runtests script

- stubs/pywin32/win32com/client/__init__.pyi
Resolve type of `constants` to allow type-checkers to trace this back to the `Constants` class. Under normal circumstances, no extra type errors should be introduced, because `Constants` has a dynamic `__getattr__`.
**Motivation**: This type annotation can be used to infer a more precise type for attribute accesses by third-party static analysis plugins, e.g. mypy's [`get_attribute_hook`](https://mypy.readthedocs.io/en/stable/extending_mypy.html#current-list-of-plugin-hooks).
See implementation at https://github.com/mhammond/pywin32/blob/main/com/win32com/client/__init__.py:
```python
class Constants:
"""A container for generated COM constants."""
...
constants = Constants()
```
> pywin32: Annotate `win32com.client.constants`

- .pre-commit-config.yaml
- requirements-tests.txt
Release post: https://astral.sh/blog/ruff-v0.1.0
> Bump `ruff` to `0.1.0`

- .github/workflows/tests.yml
- requirements-tests.txt
- tests/pytype_test.py
As of version 2023.10.17, pytype now supports 3.11.
> Run pytype_test in Python 3.11.

- .flake8
- .github/workflows/tests.yml
- .vscode/extensions.json
- CONTRIBUTING.md
- pyproject.toml
- scripts/create_baseline_stubs.py
- scripts/generate_proto_stubs.sh
- scripts/runtests.py
- stdlib/_winapi.pyi
- test_cases/stdlib/builtins/check_exception_group-py311.py
- tests/check_consistent.py
A small documentation nitpick I had. Now using proper name capitalization of tooling (Ruff, Black and Flake8), which wasn't done consistently. Unless of course it's used in a command.
Also added some anchors.
If you disagree with any of those, lmk, I can update.
> Doc: Use proper name capitalization of tooling (Ruff, Black, Flake8)

- .editorconfig
- .gitattributes
- .vscode/settings.default.json
This solves a couple Windows-Linux consistency issues. Namely:
- Running bash scripts using WSL on Windows
- git thinking the entire repository changed EOF when opening VSCode in WSL context.
- git changing EOF to CRLF on checkout on Windows
Fixed VSCode defaults not using 4-spaces for tom while I'm at it (since I have the `editorconfig.editorconfig` extension installed, it was correctly using the value in `.editorconfig` for me)
> Configure editors to explicitly use `LF` / `\n` line endings

- stubs/WebOb/webob/cookies.pyi
- stubs/WebOb/webob/response.pyi
I noticed that the `samesite` parameter for cookies only accepted the documented lowercase spelling of the values, but it probably should also accept the official title case spelling from the specification. The implementation accepts either spelling too.
Given this opportunity I also finished the stubs for the cookies module.
> Finishes stubs for `webob.cookies` and improves `samesite` type

- stdlib/io.pyi
See https://discuss.python.org/t/type-checkers-complain-about-io-text-encoding/37187/1 for discussion. The function is documented, even though it's not included in `io.__all__` (which is why stubtest hasn't been complaining about it being missing): https://docs.python.org/3/library/io.html#io.text_encoding
> Add `io.text_encoding` on py310+

- pyproject.toml
This takes us back to how things worked prior to https://github.com/python/typeshed/commit/49ba409da8906d7950dfedc7b34c3dea67bb0db9. See https://github.com/python/typeshed/pull/10939#pullrequestreview-1702764114 for an explanation of what's going on here.
> Skip ruff's isort rules on files generated with mypy-protobuf

- test_cases/README.md
- tests/README.md
- tests/regr_test.py
* Add instructions on how to run the tests to the `test-cases` directory.
* Add instruction on how to test stdlib to the `regr_test.py --help` output.
> Improve regression test documentation

- stdlib/multiprocessing/pool.pyi
The typehints for callback function in `pool.Pool` methods are incorrect
> Fix incorrect typehint for callbacks in multiprocessing.Pool

- stdlib/xml/sax/saxutils.pyi
Fixes #10550.
I've checked that `TextIOWrapper` (in addition to docs saying it wraps a binary stream) indeed doesn't work with a str-based stream so keeping `SupportsWrite[str]` indeed is wrong.
> Fix the hint for XMLGenerator.__init__().

- stdlib/_typeshed/__init__.pyi
- stdlib/builtins.pyi
`flush()` is a standard I/O method. This allows us to construct I/O protocols using composition. (I.e. using base classes at the moment and hopefully using the `&` operator at some point in the future.)
> Introduce _typeshed.SupportsFlush

- stubs/Pygments/pygments/__init__.pyi
This adds type annotations to the `pygments.lex` helper.
The return type is the same as what we use in `pygments.Lexer.get_tokens`.
> Add types for `pygments.lex`.

- stubs/pexpect/pexpect/fdpexpect.pyi
- stubs/pexpect/pexpect/popen_spawn.pyi
- stubs/pexpect/pexpect/pty_spawn.pyi
- stubs/pexpect/pexpect/pxssh.pyi
- stubs/pexpect/pexpect/run.pyi
- stubs/pexpect/pexpect/spawnbase.pyi
We can set the logfile for pexpect's spawn using sys.stdout, but the type hint shows an error.
> Support for pexpect.spawn(..., logfile=sys.stdout)

- requirements-tests.txt
- test_cases/stdlib/check_dataclasses.py
This mypy release means that mypy now supports PEP-646 and PEP-692 (`TypeVarTuple` and `Unpack`) by default 🥳
X-ref:
- #8708
- #9710
> Bump mypy to 1.7.0

- stubs/PyScreeze/METADATA.toml
To stop the "stubtest failed" bot opening a new issue every night until we have a chance to look at the stubtest failures (stubsabot will just open a PR instead)
Closes #11016
> Pin PyScreeze more tightly

- stubs/pyinstaller/@tests/stubtest_allowlist.txt
- stubs/pyinstaller/METADATA.toml
Closes #11021 .
Just a false-positive from stubtest. `autocomplete` is for internal use for the CLI app. About as useful as exposing "logger"
> Bump pyinstaller to 6.2.*

- stdlib/logging/__init__.pyi
Closes #5700 
As discussed in the related issue, starting with comment https://github.com/python/typeshed/issues/5700#issuecomment-1806718877.
> stdlib: Add a _FilterProtocol type to logging's Filterer.addFilter() filter argument.

- stdlib/itertools.pyi
- test_cases/stdlib/itertools/check_itertools_recipes.py
And add a test case (an adapted version of the `unique_justseen` itertools recipe) that otherwise fails.
> Make `itertools.groupby` covariant

- CONTRIBUTING.md
Fixes #11002.
I started out just documenting conventions with `@deprecated`, but
found some other things in need of updates.
- PEP 585 and 612 are now fully supported
- Add several other PEPs that we fully support
- Use updated links to PEPs
- Split off a few sections from the long "Conventions" section
- PEP 688 was accepted
> CONTRIBUTING: Add @deprecated, other updates

- scripts/stubsabot.py
This would have made interactively debugging #11049 a bit easier -- some of these dataclass fields have huge reprs
> Improve a few dataclass reprs in stubsabot

- tests/mypy_test.py
Before:
```
*** Testing Python 3.9 on darwin
Testing stdlib (557 files)...success
Testing third-party packages...
testing Deprecated (3 files)... success
testing ExifRead (17 files)... success
testing Flask-Cors (5 files)... success
```
After:
```
*** Testing Python 3.9 on darwin
Testing stdlib (557 files)... success
Testing third-party packages...
testing Deprecated (3 files)... success
testing ExifRead (17 files)... success
testing Flask-Cors (5 files)... success
```
> Use consistent mypy output spacing

- stdlib/http/client.pyi
Fix an apparent typo in the type of this field.
Closes #11057
> stdlib: HTTPSConnection(port=) is int|None

- scripts/stubsabot.py
An attempt to fix the bug that resulted in #11049.
~~The approach is this:~~
- ~~If there are no directories at the top level of a wheel or sdist (except for the `.dist-info` directory), none of the packages for this distribution can be `py.typed`~~
- ~~Else, return True if all top-level directories (except for `.dist-info`) are marked as `py.typed`:~~
- ~~for each directory, if it contains at least one file, consider it marked as `py.typed` if it has a `py.typed` file at the top-level~~
- ~~Else, if it only contains subdirectories, consider it marked as `py.typed` if all subdirectories are marked as `py.typed` (applying the same logic recursively).~~
Edit: all the above is out of date. The PR now uses the better approach suggested by Akuli in …
> Teach stubsabot to be smarter about the required locations of `py.typed` files

- stubs/psycopg2/psycopg2/_range.pyi
The pgrange and pyrange arguments should be a string or a class object derived from RangeAdapter and Range, respectively. See
https://github.com/psycopg/psycopg2/blob/2.9.9/lib/_range.py#L313 https://github.com/psycopg/psycopg2/blob/2.9.9/lib/_range.py#L330
> psycopg2: fix RangeCaster.__init__ annotation

- stdlib/logging/config.pyi
it is already NotRequired due to total=False
see #6193
> set `root` for logging dict config to be non-None

- stdlib/asyncio/subprocess.pyi
Duplicate for the _exec case what has already been duplicated for the _shell case in 38dfb57adf7404fdf7419c472c08e3f0670b72f3 and follow-ups.
Except for the `shell: bool` argument: that one is the whole point of having two; that one needs to be flipped.
> asyncio: create_subprocess_exec is the same as create_subprocess_shell, except where it isnt

- stdlib/trace.pyi
This will be useful for https://github.com/python/cpython/issues/109413
> Add some missing attribute annotations to `trace.pyi`

- .vscode/settings.default.json
- pyrightconfig.scripts_and_tests.json
Since `pyright@1.1.303` the default value of `useLibraryCodeForTypes` has been updated to `true` to be the same as Pylance. So it doesn't need to be configured in Pylance anymore to have the same default as Pyright.
Having the value to `false` atm differs from our pyright configs and can lead to wild desyncs with partial `Unknowns` (see https://github.com/microsoft/pylance-release/issues/5202#issuecomment-1839272649)
The rest of the python settings removed are settings that *were* deprecated, but now no longer even exists since https://github.com/microsoft/vscode-python/pull/22266. (also see for more info: https://github.com/microsoft/vscode-python/wiki/Migration-to-Python-Tools-Extensions )
> Go back to default for `useLibraryCodeForTypes` & delete removed vscode-python configs.

- stdlib/_typeshed/__init__.pyi
- stdlib/pstats.pyi
- stdlib/tkinter/__init__.pyi
- tests/stubtest_allowlists/py310.txt
- tests/stubtest_allowlists/py38.txt
- tests/stubtest_allowlists/py39.txt
- tests/stubtest_allowlists/py3_common.txt
Creating StrEnum in _typeshed avoids needing to repeat the enum, nearly unchanged, in both branches of the version check. I hope I haven't missed something.
> update two classes to use StrEnum as their base class, when available.

- stubs/psycopg2/psycopg2/__init__.pyi
- stubs/psycopg2/psycopg2/_psycopg.pyi
- stubs/psycopg2/psycopg2/extras.pyi
Change originating from: https://github.com/python/typeshed/pull/11084#issuecomment-1831274491
idk if specifying the possible kwarg is necessary here. If not, then the tests in `stubs/psycopg2/@tests/test_cases/check_extensions.py` are still accurate. @JelleZijlstra I believe you last looked at this in https://github.com/python/typeshed/pull/7964/files#diff-0f425c352331e97f72634f6e626545d46059d6744c3b7e6a439119482869c8eeR91
> psycopg2: improve `cursor_factory` params

- stdlib/socketserver.pyi
This should be pretty minor as far as I can see; TCPServer and UDPServer are both subclasses of BaseServer. I couldn't find any prior discussion or clear reason why they weren't used in the first place here, so it's quite possible I missed something.
> fix superclass for UnixDatagramServer and UnixStreamServer

- stdlib/os/__init__.pyi
Both mypy and pyright are able to precisely type check heterogenous `*args` types in `os.execle` and `os.execlpe` now.
> stdlib: Use PEP646 tuple unpack for precise `os.execl(p)e` typing

- stdlib/asyncio/locks.pyi
- stdlib/asyncio/queues.pyi
> use _LoopBoundMixin in asyncio when appropriate

- stubs/seaborn/seaborn/algorithms.pyi
- stubs/seaborn/seaborn/axisgrid.pyi
- stubs/seaborn/seaborn/distributions.pyi
- stubs/seaborn/seaborn/rcmod.pyi
- stubs/seaborn/seaborn/utils.pyi
Note that I intentionally left out deprecated parameters of the big API functions as they would require overloads with very long signatures.
> seaborn: mark simple deprecations with typing_extensions.deprecated

- stdlib/importlib/metadata/__init__.pyi
- tests/stubtest_allowlists/py310.txt
- tests/stubtest_allowlists/py311.txt
- tests/stubtest_allowlists/py312.txt
Generally speaking these classes print warnings and then call super().method() without changing anything's type signature, so they don't need much to be filled out here.
> Add deprecation classes in importlib.metadata

- stdlib/dis.pyi
related (vaguely) to https://github.com/python/typeshed/issues/3968
> follow implementation details of dis.Instruction

- stdlib/pyclbr.pyi
> add pyclbr._Object

- pyproject.toml
Hello,
There are a few duplicated items in the `exclude` list of `ruff` at the `pyproject.toml`.
I suppose they might be removed safely.
Best regards!
> Remove duplicated items from ruff's exclude list

- stdlib/lzma.pyi
> use _compression.BaseStream for lzma.LZMAFile

- .editorconfig
* 130 matches what the linter and formatter are told for Python files.
* 79 appears to be the limit for README.md.
> Set the maximum line length in .editorconfig

- pyproject.toml
We've missed 3 new versions: https://github.com/microsoft/pyright/releases/tag/1.1.342
> Bump pyright to 1.1.342

- stdlib/_ast.pyi
> Make attributes required on AST type_param classes

- stdlib/typing.pyi
To be consistent with the rest of the file
> Use `type` instead of `Type` in `typing.pyi`

- stdlib/_typeshed/__init__.pyi
~~This was never marked as "stable" and all uses have been replaced with `typing_extensions.Self`.~~
> Update description of `_typeshed.Self`

- .github/workflows/tests.yml
- CONTRIBUTING.md
- README.md
- pyproject.toml
- stubs/gevent/METADATA.toml
- stubs/jsonschema/METADATA.toml
- stubs/pyinstaller/METADATA.toml
- test_cases/README.md
- tests/check_new_syntax.py
- tests/regr_test.py
> Drop support for Python 3.7

- stdlib/_socket.pyi
- stdlib/socket.pyi
- tests/stubtest_allowlists/py3_common.txt
Match the documentation more closely
Fixes some of #8101 , in particular I no longer see any missing constants on the Linux machines I have access to
> socket: rework to match docs more closely, improve accuracy on linux

- .flake8
Temporary workaround to unblock https://github.com/PyCQA/flake8-pyi/pull/459. Longer term, we can create issues/PRs over at mypy-protobuf so that the generated stubs import these things from typing rather than typing_extensions.
> Ignore Y023 in generated `*_pb2.pyi` files

- stubs/polib/polib.pyi
> `POEntry.msgstr_plural` is mistyped in polib

- stdlib/distutils/ccompiler.pyi
- stubs/setuptools/setuptools/_distutils/ccompiler.pyi
Fixed types for `setuptools._distutils.CCompiler.compile`, fixes #11271.
Also fixed the types in the `distutils` in `stdlib`, let me know if I should undo changing the one in `stdlib` (see the comment in the `__init__.pyi`):
https://github.com/python/typeshed/blob/8e8204b83f68d807c2a8bb9df3298fe92f5684df/stdlib/distutils/__init__.pyi#L1-L5
> Fix types for `setuptools._distutils.ccompiler.CCompiler.compile`

- stdlib/plistlib.pyi
Since https://github.com/python/cpython/pull/113363 and https://github.com/python/cpython/pull/113582 have been merged, the `plistlib` module in upcoming Python3.13 release, will have a new optional parameter `aware_datetime` in most of it's functions.
In addition, the `plistlib.loads` also accepts `str` type as inputs value.
> Add `aware_datetime` option to plistlib functions

- stubs/defusedxml/defusedxml/minidom.pyi
This is a follow-up to #11179 (thanks again @solkaz)
This PR just adds the return types to the minidom methods [as discussed](https://github.com/python/typeshed/pull/11179#issuecomment-1893201330).
> `defusedxml`: Add xml.dom.minidom.Document return type annotation

- .github/workflows/meta_tests.yml
- .github/workflows/tests.yml
I just bumped the action's major version to upgrade it to node20; no changes to the API were made (but it's standard to bump major if the runtime used changes).
Not sure if you use a bot to upgrade these, so here's a PR 😄
> Bump pyright-action to v2

- stubs/ldap3/ldap3/core/connection.pyi
Earlier ldap3 versions only accepted booleans as auto_bind values, and
they are still supported and used in various places in upstream
documentation (e.g. at [0]).
[0]: https://ldap3.readthedocs.io/en/latest/bind.html?highlight=auto_bind
> ldap3: Connection: auto_bind also supports booleans

- stdlib/tkinter/font.pyi
- test_cases/stdlib/check_tkinter.py
> tkinter: font size must be integer

- stubs/Pillow/PIL/ImageStat.pyi
These are created in the original source with what looks like an unusual way of creating properties:
```python
def __getattr__(self, id):
"""Calculate missing attribute"""
if id[:4] == "_get":
raise AttributeError(id)
v = getattr(self, "_get" + id)()
setattr(self, id, v)
return v
```
See https://github.com/python-pillow/Pillow/blob/main/src/PIL/ImageStat.py#L124, for example.
> Add a number of properties to PIL.ImageStat.Stat

- stdlib/asyncio/locks.pyi
> Correct `_waiters` type

- stubs/tensorflow/tensorflow/__init__.pyi
Add the [convert_to_tensor](https://www.tensorflow.org/api_docs/python/tf/convert_to_tensor) TensorFlow function.
The actual return type of the function is `Union[EagerTensor, SymbolicTensor]` (cf [the tensorflow function](https://github.com/tensorflow/tensorflow/blob/ac478d8173f9c0c63b1d215e6f6aa85b10d5cb7e/tensorflow/python/framework/ops.py#L685)), however those are not present in the stub yet, should they be added ?
I would like to help complete the TensorFlow stubs, so I would be thankful if you could tell me anything I would need to know in order to contribute.
> Add `convert_to_tensor` to `tensorflow`

- stubs/tensorflow/tensorflow/__init__.pyi
See documentation [here](https://www.tensorflow.org/api_docs/python/tf/VariableAggregation)
@hmc-cs-mdrissi
> `tensorflow` fix `tensorflow.VariableSynchronization`

- stdlib/concurrent/futures/_base.pyi
- test_cases/stdlib/check_concurrent_futures.py
Fixes #11285. I think this works? Not quite sure the best way to describe this, feel free to edit PR title.
> concurrent.futures: allow as_completed to act covariantly

- stdlib/types.pyi
> Generalise attribute `__func__` of class `MethodType` from `FunctionType` to `Callable`

- stubs/psycopg2/psycopg2/_psycopg.pyi
Fix https://github.com/python/typeshed/issues/11282
> issue-11282: psycopg2 ReplicationConnection.cursor() return type

- stubs/tensorflow/tensorflow/data/__init__.pyi
Sorry open this just after [the PR to bump the tensorflow version](https://github.com/python/typeshed/pull/11352) got merged, but I just realized that if `Dataset[Any]` is not present in the function's signature, then only nested structures of datasets can be passed to the zip method.
Related comments in the previous PR [here](https://github.com/python/typeshed/pull/11352#discussion_r1477044838) and [here](https://github.com/python/typeshed/pull/11352#discussion_r1477044359).
> `tensorflow` fix `tensorflow.data.Dataset`'s zip

- stdlib/_ast.pyi
This isn't necessarily always an identifier:
```pycon
>>> print(ast.dump(ast.parse('from typing import *'), indent=2))
Module(
body=[
ImportFrom(
module='typing',
names=[
alias(name='*')],
level=0)],
type_ignores=[])
>>> '*'.isidentifier()
False
```
> Fix annotation for ast.alias.name

- stubs/influxdb-client/influxdb_client/service/tasks_service.pyi
flake8 is failing on `main`, due to a merge race between  #11116 and #11249
> influx-db: fix flake8

- stdlib/sys/__init__.pyi
- tests/stubtest_allowlists/py312.txt
https://docs.python.org/3/library/sys.html#sys.last_exc
> sys: add `last_exc` on Python>=3.12

- stdlib/tkinter/ttk.pyi
Fix `ttk`'s `compound` argument, fixes #11392
> Fix `ttk`'s `compound` argument

- stdlib/tkinter/ttk.pyi
Add annotations for `tkinter.ttk.LabeledScale`. This [doesn't seem the be documented](https://docs.python.org/3/search.html?q=labeledscale) in the official Python documentation so I just took the types from [the source code](https://github.com/python/cpython/blob/b1043607884d774acabd255ecdcebb159f76a2fb/Lib/tkinter/ttk.py#L1492-L1527).
> Add annotations for `tkinter.ttk.LabeledScale`

- stubs/Pillow/PIL/ImageOps.pyi
Updates the type hint for the `cutoff` argument of `ImageOps.autocontrast()` to allow for functionality added in Pillow 8.0.0.
https://pillow.readthedocs.io/en/stable/releasenotes/8.0.0.html#imageops-autocontrast-cutoffs
> Previously, the cutoff parameter of [ImageOps.autocontrast()](https://pillow.readthedocs.io/en/stable/reference/ImageOps.html#PIL.ImageOps.autocontrast) could only be a single number, used as the percent to cut off from the histogram on the low and high ends.
>
> Now, it can also be a tuple (low, high).
This is a recreation of https://github.com/python/typeshed/pull/11376
> Pillow: ImageOps.autocontrast can set low and high cutoffs separately

- stubs/Pillow/PIL/ImageOps.pyi
This is an extension of https://github.com/python/typeshed/pull/11376 to permit float values (and 2-tuple values containing 1 or 2 floats) as the value of `cutoff` for the `autocontrast` function in the `ImageOps` module.
The previous pull request only permits `int`s, but the documentation doesn't stipulate `int`s (only "number"), and passing `float`s could be desirable if a more specific cutoff is required. Using a `float` type also permits `int` (see [&ldquo;The numeric tower&rdquo; in PEP 484](https://peps.python.org/pep-0484/#the-numeric-tower)).
> Pillow: Allow float(s) for cutoff param of autocontrast

- stdlib/tkinter/__init__.pyi
This is a less disruptive version of #11394.
In general, passing 0 or 1 is less readable and just not the right thing to do in new code. Users should just use the new and readable thing instead of the confusing legacy thing. Tkinter (and much of its documentation) was created before `bool` was added to Python.
That said, there's still plenty of example code around (e.g. stackoverflow answers, tkinter docstrings) that use 0 and 1. IMO we should apply `Literal[0, 1]` to tkinter booleans **only** when someone needs it in a specific place, not blindly to all boolean parameters.
This is also why I don't want yet another type alias, e.g. `_TkBool = bool | Literal[0, 1]`. In most cases, it's not the right thing to use, so I don't want a convenience thing for it.
> Use `bool | Literal[0, 1]` instead of `int` in some tkinter bool parameters

- stdlib/ftplib.pyi
It is more consistent with the official document.
<https://docs.python.org/3/library/ftplib.html>
> ftplib: Correct timeout option to `float | None`

- stubs/tensorflow/tensorflow/raw_ops.pyi
Stubs taken from [here](https://github.com/hmc-cs-mdrissi/tensorflow_stubs/blob/main/stubs/tensorflow/raw_ops.pyi).
> `tensorflow`: Add some `tf.raw_ops` members.

- stubs/requests/requests/api.pyi
https://github.com/python/typeshed/pull/7773 changed `requests.session.Session` methods to accept None for header values, but didn't do quite the same for the functions in `requests.api`.  I think this was a mistake.  The functions in `requests.api` just pass through the `headers` argument without doing anything in particular to it.
Furthermore, it's useful to be able to pass None as a header value: because `requests.utils.default_headers` sets an `Accept-Encoding` header by default, the easiest way to send a request with no `Accept-Encoding` header is something like `requests.get(url, headers={"Accept-Encoding": None})`.  It's annoying to have to construct a `Session` just to pass type-checking.
It's a little confusing for the type alias to be called `_HeadersUpdateMapping` in …
> requests: Allow passing None header values

- stdlib/typing_extensions.pyi
- tests/stubtest_allowlists/py3_common.txt
I just released 4.10.0rc1. Getting this into typeshed now is helpful for fixing python/typing_extensions#339.
> Update for typing_extensions 4.10

- stdlib/shlex.pyi
Whilst working on a setuptools stubs update (namely in `setuptools.command.easy_install.CommandSpec.from_param`), I noticed that `shlex.split` didn't allow `TextIO` like `shlex.shlex.__init__` does. And that passing `None` can be allowed (but deprecated) until Python 3.12.
Unless `s` being anything else than a `str` is an accidental implementation detail that should be hidden away.
> `shlex.split`: allow `TextIO` and deprecate `None`

- stdlib/os/__init__.pyi
- stdlib/posix.pyi
- tests/stubtest_allowlists/linux.txt
Closes https://github.com/python/typeshed/issues/11259
> Update `os. EX_NOTFOUND` not available in Linux

- .github/workflows/meta_tests.yml
- .github/workflows/tests.yml
to fix CI failures (see #11474)
> pin pyright-action to 2.0.2

- stdlib/tarfile.pyi
Fixes #11472.
As noted in the issue, it is possible to set the filter on the class, but that will still cause type checkers to show deprecation warnings. Therefore, we unfortunately cannot enforce this deprecation in the type system.
> tarfile: Remove @deprecated

- .github/workflows/meta_tests.yml
- .github/workflows/tests.yml
Reverts python/typeshed#11475
Closes #11474
The CI failures should be fixed now that pyright-action 2.1.1 has been released
> Revert "pin pyright-action to 2.0.2"

- scripts/runtests.py
- scripts/stubsabot.py
- test_cases/stdlib/typing/check_all.py
- tests/mypy_test.py
- tests/pytype_test.py
- tests/regr_test.py
- tests/stubtest_third_party.py
- tests/typecheck_typeshed.py
- tests/utils.py
Unless you find potential issues with these changes, they seemed valid on their own, even if not correctly checked for. Extracted from https://github.com/python/typeshed/pull/11496 . Overlaps with #11499
https://docs.astral.sh/ruff/rules/collection-literal-concatenation/
https://docs.astral.sh/ruff/rules/raise-without-from-inside-except/
https://docs.astral.sh/ruff/rules/lru-cache-without-parameters/
https://docs.astral.sh/ruff/rules/module-import-not-at-top-of-file/
https://docs.astral.sh/ruff/rules/f-string/
> Code improvements from new Ruff checks

- .github/workflows/tests.yml
`no-comments` is deprecated: 
- https://github.com/python/typeshed/actions/runs/8092167409/job/22112427113?pr=11501#step:10:1
- https://github.com/jakebailey/pyright-action/blob/b8ffdb7aa4a15fab942303261611eaa541f3f8b0/action.yml#L83-L88
> Replace `no-comments` with `annotate` in `jakebailey/pyright-action`

- .flake8
- .pre-commit-config.yaml
- CONTRIBUTING.md
- pyproject.toml
- pyrightconfig.testcases.json
- requirements-tests.txt
- scripts/stubsabot.py
- stubs/s2clientprotocol/s2clientprotocol/query_pb2.pyi
- tests/check_consistent.py
Replaces flake8-bugbear with https://docs.astral.sh/ruff/rules/#flake8-bugbear-b
Extracted from #11496
> Replace flake8-bugbear with Ruff

- pyproject.toml
> make pyproject.toml valid TOML again

- .github/workflows/daily.yml
- .github/workflows/meta_tests.yml
- .github/workflows/stubsabot.yml
- .github/workflows/tests.yml
Using [`uv`](https://github.com/astral-sh/uv) rather than pip means our requirements are installed almost instantly in CI, compared to around 10s to install our `requirements.txt` file currently on each job.
I've only changed the jobs that are Linux-only in this PR. `uv` works fine on Windows, but it's slightly fiddly to install `uv` in a workflow that runs on both Windows and Linux without using pip (which is slow, defeating the point of the exercise). It's [possible](https://github.com/AlexWaygood/typeshed-stats/blob/f55c5bee175a97a345209df3fdb86bb611956168/.github/workflows/test.yml#L59-L64C14) to install uv in a cross-platform workflow without using pip, but I wasn't sure it was worth the added complexity for us here.
> Use `uv` for installing dependencies on all Linux-only CI jobs

- stdlib/builtins.pyi
- stdlib/importlib/metadata/__init__.pyi
- stdlib/weakref.pyi
https://github.com/python/typeshed/issues/8280 removed some redundant `#type: ignore`, but not the associated comments.
> Remove old type-ignore explanation comments not removed in #8280

- .github/workflows/tests.yml
- requirements-tests.txt
- tests/mypy_test.py
- tests/regr_test.py
- tests/stubtest_third_party.py
- tests/utils.py
The execution time of `mypy_test.py` goes down from around 2m10s to around 1m30s in CI
> Use `uv` for installing dynamic dependencies in `mypy_test.py` and `regr_test.py`

- .github/workflows/tests.yml
- .pre-commit-config.yaml
- CONTRIBUTING.md
- pyproject.toml
- requirements-tests.txt
- scripts/generate_proto_stubs.sh
- scripts/runtests.py
- scripts/sync_tensorflow_protobuf_stubs.sh
- tests/check_consistent.py
- Do all our linting via pre-commit, rather than doing ruff and flake8 via GitHub Actions. This has several advantages:
- It's less code/configuration for us to worry about
- We only have to have our `ruff` version pin in 2 places, rather than 3
- pre-commit.ci is faster due to better caching
- It's easier to do multiple runs of ruff with slightly different CLI arguments, which is useful if we only want to use `--unsafe-fixes` for one specific rule
- It means we can simplify and reduce duplication in our protobuf-generation scripts
- Bump ruff to the latest version
- Add a new pre-commit hook `check-hooks-apply`. This will error out if a regex passed to the `files` parameter for any individual pre-commit hook matches 0 files
- Move ruff before black in our pre-commit config file. It's …
> Rework our linting setup

- stdlib/concurrent/futures/_base.pyi
> Fix type of `concurrent.futures.wait` for Python <= 3.8

- stubs/libsass/METADATA.toml
- stubs/passlib/METADATA.toml
- stubs/redis/METADATA.toml
- stubs/tree-sitter/METADATA.toml
These two packages depend on setuptools at runtime without declaring that dependency properly. Historically, setuptools has been automatically installed into virtual environments by default, but that isn't the case anymore on py312+
> Make stubtest pass on libsass/passlib/redis/tree-sitter if you're using Python 3.12

- stdlib/email/message.pyi
- test_cases/stdlib/email/check_message.py
The allowed value depends on the used policy. For example,
`EmailPolicy` allows objects with a `name` attribute, which the
compat policy does not allow.
This can be improved in the future, especially when TypeVar defaults become available.
> email.message: Allow any header value

- stubs/networkx/networkx/classes/reportviews.pyi
It's common to call the 'edges' property of a DiGraph with an 'nbunch' argument and no other arguments (see the Examples section of https://networkx.org/documentation/stable/reference/classes/generated/networkx.DiGraph.out_edges.html). None of the existing overloads allow this.
> networkx: add another overload to OutEdgeView.__call__().

- stubs/pygit2/pygit2/repository.pyi
They are not initialized directly in `__init__`, hence missing from the auto-generated stub.
> pygit2: Add missing Repository fields

- stubs/PyScreeze/METADATA.toml
Same principle as with https://github.com/python/typeshed/pull/11561, though this one's a little strange...
> Make stubtest work on pyscreeze if you're using py312

- pyrightconfig.stricter.json
According to `typeshed-stats`, these stubs are fully annotated: https://github.com/AlexWaygood/typeshed-stats/actions/runs/8257791235/job/22588952236
> Use stricter pyright settings for `pygit2`

- .github/renovate.json
This should make the sentences in https://github.com/python/typeshed/issues/11588#issue-2183664294 make more sense...
> Renovate config: give the dependency groups better names

- requirements-tests.txt
- tests/stubtest_third_party.py
Workaround for https://github.com/astral-sh/uv/issues/2450, which seems to be a GitHub Actions-specific problem (I can't reproduce locally). Fixes #11594
> pin uv to 0.1.18

- CONTRIBUTING.md
> CONTRIBUTING.md: Add PR closing policy

- .github/workflows/tests.yml
See #11590. (But let's keep that issue open, as I still haven't had a chance to properly investigate yet.)
> Go back to using py311 for `regr-test.py` for now

- stdlib/logging/__init__.pyi
Add `taskName` to `LogRecord` (it got added in Python 3.12.0).
related cpython issue: https://github.com/python/cpython/issues/91513
> Add taskName to LogRecord

- CONTRIBUTING.md
- Document the `requires_python` metadata field
- Remove obsolete mentions of `_typeshed.Self`
- Minor formatting improvements
- Modernize the examples
> Improvements to the contributing guide

- stubs/pygit2/@tests/stubtest_allowlist.txt
- stubs/pygit2/pygit2/__init__.pyi
To fix the signatures of `clone_repository` and `init_repository` as seen by type checkers.
> pygit2: Workaround python/mypy#16972

- stubs/paho-mqtt/METADATA.toml
> Mark types-paho-mqtt as obsolete since v2.0.0

- scripts/stubsabot.py
An attempt to address the false negatives seen in https://github.com/python/typeshed/issues/11633#issuecomment-2008975395
> stubsabot: Skip over empty `__init__.py` files when determining if all Python files are covered by `py.typed` markers

- .github/workflows/tests.yml
> Fix pyright CI job

- stubs/python-xlib/Xlib/_typing.pyi
- stubs/python-xlib/Xlib/ext/composite.pyi
- stubs/python-xlib/Xlib/ext/dpms.pyi
- stubs/python-xlib/Xlib/ext/ge.pyi
- stubs/python-xlib/Xlib/ext/nvcontrol.pyi
- stubs/python-xlib/Xlib/ext/record.pyi
- stubs/python-xlib/Xlib/ext/res.pyi
- stubs/python-xlib/Xlib/ext/security.pyi
- stubs/python-xlib/Xlib/ext/xfixes.pyi
- stubs/python-xlib/Xlib/ext/xinerama.pyi
- stubs/python-xlib/Xlib/ext/xinput.pyi
- stubs/python-xlib/Xlib/ext/xtest.pyi
- stubs/python-xlib/Xlib/protocol/rq.pyi
- stubs/python-xlib/Xlib/support/unix_connect.pyi
- stubs/python-xlib/Xlib/support/vms_connect.pyi
A long overdue update I had forgotten about. There's been many mypy releases with stdlib stubs updates since then.
> python-xlib: use `_typeshed.Unused`

- stdlib/typing_extensions.pyi
> Update `typing_extensions.deprecated` decorator to use `LiteralString`

- .github/workflows/daily.yml
- .github/workflows/stubtest_stdlib.yml
A quick fix to stop the bleeding, since it looks like there's a fair few changes in 3.11.9 for us to grapple with. Fixes #11712.
> Use Python 3.11.8 for stdlib stubtest for now

- stubs/requests/requests/__init__.pyi
[These lines](https://github.com/psf/requests/blob/main/src/requests/__init__.py#L147) has been in `requests` for [at least 7 years](https://github.com/psf/requests/blame/main/src/requests/__init__.py#L147).
For me, this PR allows the following code, which make life easier (not having to import `requests.utils`):
```python
import requests
requests.utils.cookiejar_from_dict(...)
```
> requests: export `packages` and `utils`

- .vscode/settings.default.json
I had to redo my local setup on a new laptop recently and noticed these were due for an update.
- `editor.codeActionsOnSave.source.*` settings now have 3 possible values represented by a string
- Ensure only Ruff sorts imports (something else was hooking the "organizeImports" option)
> Update vscode `editor.codeActionsOnSave.source.*` settings

- .pre-commit-config.yaml
Unnecessary `sys.version_info` blocks removal should be run first as it can leave unused imports behind.
Realistically this can probably be removed after #11694 and #11696 as the mypy-protobuf update no longer generate files with `UP036` violations. But that's a later consideration.
> Re-order ruff runs in pre-commit

- tests/check_consistent.py
We should also rename this script. The original purpose of checking whether certain files are consistent between the Python 2 and 3 directories is long gone.
Maybe just "check_typeshed", or "check_structure", or even "check_typeshed_structure"?
> Improve documentation of the check_consistent script

- stubs/pyinstaller/METADATA.toml
- stubs/pyinstaller/PyInstaller/building/build_main.pyi
Closes #11751
The only public API change is a new "Bytecode Optimization Level" option for `Analysis` (the values `None`, `-1`, `0`, `1`, `2` are explicitly being checked for)
> Bump pyinstaller to 6.6.*

- scripts/stubsabot.py
- tests/stubtest_third_party.py
- tests/utils.py
Mostly changes to enable us to directly click through from the GitHub logs if the daily test fails, rather than having to manually figure out what the upstream repository is or where the typeshed stubs are located.
<details>
<summary>Previous output if it failed:</summary>
```
(typeshed) (main)⚡ % py tests/stubtest_third_party.py requests                                                                       ~/dev/typeshed
requests... Note: requests is not currently tested on darwin in typeshed's CI.
fail
/var/folders/gd/1czdxc454j15y8gns2krv8vc0000gn/T/tmpq5w04nqe/bin/pip install requests[socks]==2.31.* mypy==1.9.0 urllib3>=2
MYPYPATH=/Users/alexw/dev/typeshed/stubs/requests /var/folders/gd/1czdxc454j15y8gns2krv8vc0000gn/T/tmpq5w04nqe/bin/python -m mypy.stubtest --custom-typeshed-dir …
```
> Improve the output of `tests/stubtest_third_party.py` when it fails

- .flake8
- .pre-commit-config.yaml
- pyproject.toml
- requirements-tests.txt
- stdlib/typing.pyi
- stubs/hdbcli/hdbcli/dbapi.pyi
Thanks to @AlexWaygood 's work on https://github.com/astral-sh/ruff/issues/3011 , we no longer need to ignore `F821` in Ruff configs, whilst still preferring to avoid forward-references.
I've left in `F821` from Flake8 as per my in-code comment: typeshed being a testing ground for F821, it's great to catch changes to the monkeypatching of `F821`
> Update Ruff and enable F821 in stubs

- .pre-commit-config.yaml
- pyproject.toml
Spotted in https://github.com/python/typeshed/pull/11777#discussion_r1569249303
This has the following advantages:
- Picked up by IDEs for autofix commands
- Is included when running `ruff check`
- Less overhead in pre-commit runs
> Move Ruff unsafe-fixes from pre-commit to config

- scripts/stubsabot.py
- tests/stubtest_third_party.py
- tests/utils.py
Fixes https://github.com/python/typeshed/pull/11763#issuecomment-2067622376. Things were appearing out of order in CI because some things were being printed to `stderr` and other things to `stdout`. Also stubsabot is giving the wrong URL to the typeshed stubs in its PR summaries due to a silly typo that was also introduced in https://github.com/python/typeshed/pull/11763 (see https://github.com/python/typeshed/pull/11727 for an example of the bad link in the PR description).
Demonstration that proves printing everything to `sys.stderr` fixes the bug: https://github.com/AlexWaygood/typeshed/pull/30
> Fix divider lines in `stubtest_third_party.py`

- tests/stubtest_third_party.py
- tests/utils.py
In GitHub Actions, all stderr appears above stdout, even if things are printed to stdout chronologically earlier than being printed to stderr. That is, if you have something like
```py
print("foo")
print("bar", file=sys.stderr)
```
The output in GitHub Actions will be
```
bar
foo
```
Recent changes I made to `stubtest_third_party.py` made the output go funny because some things were being printed to stderr in CI and some things to stdout. I fixed most of that in #11799, but not all of it (the output still isn't quite right in https://github.com/python/typeshed/actions/runs/8776498752), and now the output of `mypy_test.py` is all screwed up because of that fix (https://github.com/python/typeshed/actions/runs/8782468512/job/24096628717?pr=11808).
I think it's easier if we just print …
> `stubtest_third_party.py`, `mypy_test.py`: just print everything to stdout

- stubs/tensorflow/METADATA.toml
- stubs/tensorflow/tensorflow/keras/layers/__init__.pyi
> Fix stubtest errors in tensorflow with `keras>=3.3.2`

- stubs/JACK-Client/METADATA.toml
- stubs/pyaudio/METADATA.toml
- stubs/uWSGI/METADATA.toml
- tests/parse_metadata.py
- tests/stubtest_third_party.py
Fixes #11813
Just opening this as an option, feel free to close if there's some better fix
> Disable uwsgi, pyaudio, jack-client stubtest on macOS

- stubs/pyinstaller/PyInstaller/building/splash.pyi
pyinstaller: allow `Splash(text_pos = None)`. Closes #11834.
> pyinstaller: allow `Splash(text_pos = None)`

- stdlib/asyncio/coroutines.pyi
- stdlib/asyncio/futures.pyi
> Use TypeIs for asyncio function

- stubs/beautifulsoup4/bs4/formatter.pyi
Does what the title says.
This should fix issues like this:
```
formatter = bs4.formatter.HTMLFormatter(indent=4)
```
The code above does not pass e.g. mypy checks, because the tools think HTMLFormatter does not support the indent parameter, which is rather annoying.
> Add indent argument to HTMLFormatter and XMLFormatter inits

- stubs/regex/regex/regex.pyi
- Corrected types for `pos` and `endpos` arguments to `int | None = None`
- Corrected type for `timeout` argument to `float | None = None`
- Added default value `None` for `concurrent` and `timeout` parameters
- Added default value `0` for `maxsplit` parameter
- Added `partial` parameter where applicable
- Removed invalid `flags` parameter from `sub` methods
The documentation for some of these is incorrect. I checked everything against the C [source code](https://github.com/mrabarnett/mrab-regex/blob/bc73ebb5d794668fe272c6f869cfa01add91ed83/regex_3/_regex.c).
> regex: improve Pattern annotations

- tests/README.md
- tests/check_typeshed_structure.py
- tests/regr_test.py
- tests/runtests.py
- tests/stubtest_third_party.py
- tests/utils.py
Previously, handling of test directories (`@tests` and `test_cases`) was
distributed over multiple files and redundant. This unifies the handling
in the `utils` module. This also fixes some instances where "package"
was used instead of "distribution". And in a few instances paths were
joined by using a `/` in a string, which is incompatible with Windows.
Also move `runtests.py` from `scripts` to `tests`. This is required so that
we can import `utils`, but it's also arguably the better fit. The only
mention of the script is actually in the `tests/README.md` file.
Helps with #11762.
> Unify test directory handling

- stdlib/typing.pyi
This is in response to: https://github.com/python/cpython/pull/118681
> [3.13] `typing.(Async)ContextManager` adds second type parameter

- stubs/Pillow/PIL/WalImageFile.pyi
Source: https://github.com/python-pillow/Pillow/blob/0cad346fc960bc07cde9d1d9135421978e2f28e8/src/PIL/WalImageFile.py#L61-L71
It calls `is_path` here (in the base class `__init__`): https://github.com/python-pillow/Pillow/blob/0cad346fc960bc07cde9d1d9135421978e2f28e8/src/PIL/ImageFile.py#L123-L127 
`is_path` returns `TypeGuard[StrOrBytesPath]`: https://github.com/python-pillow/Pillow/blob/0cad346fc960bc07cde9d1d9135421978e2f28e8/src/PIL/_util.py#L8-L11
> Add typehints for `open` in `PIL.WallImageFile`

- stdlib/socket.pyi
It seems #10247/#11219 missed a couple identifiers in the `socket` stub (the `_socket` stub seems good, though). This PR adds `socket.ETH_P_ALL` (https://docs.python.org/3/library/socket.html#socket.ETH_P_ALL).
There's also [`AF_DIVERT`](https://docs.python.org/3/library/socket.html#socket.AF_DIVERT) and [`PF_DIVERT`](https://docs.python.org/3/library/socket.html#socket.PF_DIVERT) missing from the `socket` stub, as well, but I've omitted those from this PR for a couple reasons. These are only available on FreeBSD systems, which was correctly noted in the comment above their type annotations in `_socket`, but the condition to check for this availability is (or at least seems to be) logically incorrect:
```python
if sys.version_info >= (3, 12) and sys.platform != "linux" and sys.platform != …
```
> Add missing `ETH_P_ALL` identifier to `socket`

- stubs/regex/regex/regex.pyi
Calling these functions with a `bytearray` raises `TypeError: unhashable type: 'bytearray'`, calling them with a `memoryview` raises `TypeError: first argument must be a string or compiled pattern`
> regex: functions do not accept any buffer for pattern

- stubs/docker/docker/models/containers.pyi
The docstring says that this must be a string, but the implementation explicitly allows an Image:
https://github.com/docker/docker-py/blob/b6464dbed92b14b2c61d5ee49805fce041a3e083/docker/models/containers.py#L850-L851
```python
if isinstance(image, Image):
image = image.id
```
> Allow Image type for docker container run image parameter

- stdlib/types.pyi
- stubs/setuptools/pkg_resources/__init__.pyi
Ref: https://github.com/python/typeshed/pull/11890#discussion_r1597690434
Must be kept until next mypy release.
CC @AlexWaygood or @srittau
> Avoid using new `_typeshed` protocol in `pkg_resources` for now

- stdlib/typing.pyi
Make use of `TypeVar` defaults, so that `Generator[int, None, None]` and `AsyncGenerator[int, None, None]`  can simply be represented as `Generator[int]` and `AsyncGenerator[int]` as recommended in PEP 696: https://peps.python.org/pep-0696/
There might be good reasons to push this back, but mostly wanted to put this out to get the ball rolling, and see if there was any discussion/thoughts around this.
> Use TypeVar defaults for `Generator` and `AsyncGenerator`

- pyrightconfig.stricter.json
Fixes https://github.com/AlexWaygood/typeshed-stats/issues/225
> Use stricter pyright settings in CI for `assertpy`

- stdlib/typing.pyi
- stdlib/typing_extensions.pyi
- Add the `__default__` property, the `default` parameter and the `has_default` method to the `typing.pyi` versions of `TypeVar`, `ParamSpec` and `TypeVarTuple`
- Change the `__default__` property in `typing_extensions` from `Any | None` to `Any`, now that it defaults to `NoDefault` rather than `Any`
- Add the `__typing_prepare_subst__` method to the typevarlike classes in `typing_extensions`. These are implementation details, but we included them in the `typing.pyi` versions of these classes; we should probably be consistent between `typing` and `typing_extensions` here
- Import `ContextManager` and `AsyncContextManager` from `contextlib` rather than `typing` in our `typing_extensions` stubs. The versions in `contextlib` always have defaults for the type parameters in our stubs (matching …
> More PEP-696 updates to `typing(_extensions)` stubs

- stdlib/distutils/dist.pyi
- stubs/setuptools/@tests/stubtest_allowlist.txt
- stubs/setuptools/setuptools/_distutils/dist.pyi
Addresses these setuptools TODOs: https://github.com/pypa/setuptools/blob/main/setuptools/command/editable_wheel.py#L250-L251 & https://github.com/pypa/setuptools/blob/main/setuptools/command/editable_wheel.py#L450-L451
so it can start running mypy on Python 3.12: https://github.com/pypa/setuptools/pull/4352#issuecomment-2116537842
> Make `distutils.dist.Distribution.get_command_obj` not return `None` by default

- stdlib/calendar.pyi
- stdlib/http/__init__.pyi
- stdlib/re.pyi
I was pointed recently to this issue https://github.com/python/typing-council/issues/11 which suggests changing the interpretation of annotated but not assigned attributes of enums to no longer be considered members of the enumeration so I looked in the stdlib for places where this exists and changed the annotations to assignments.
Note that there is a PR implementing this change in mypy https://github.com/python/mypy/pull/17207
> stdlib: fix some enum definitions

- tests/stubtest_stdlib.py
- tests/stubtest_third_party.py
- tests/utils.py
This is a preparation for #11762
> Unify allowlist handling

- stdlib/_ast.pyi
- tests/stubtest_allowlists/py310.txt
- tests/stubtest_allowlists/py311.txt
- tests/stubtest_allowlists/py312.txt
- tests/stubtest_allowlists/py3_common.txt
Fixes #8378
- `ast.AST` no longer owns attributes which may not exist on all subclasses (node locations, `type_comment`). These are all shifted to subclasses which actually own the attributes (https://github.com/python/typeshed/commit/d5e0838348559641ddc02b5495dd84bb0a00aea4, https://github.com/python/typeshed/commit/75a2e8e1af712de4fb3a81c0edfc9a40223120a9, https://github.com/python/typeshed/commit/f9a2cb9ee8b93a9d8daa4f6afab5ad4d6567f58b)
- `ast.AST` no longer has the constructor `__init__(self, *args: Any, **kwargs: Any)`.
- All subclasses of `ast.AST` which have a non-empty `_fields: ClassVar[tuple[str, ...]]` or `_attributes: ClassVar[tuple[str, ...]]` now have their own `__init__` constructor (https://github.com/python/typeshed/commit/d886a4511043fb531ee261d688dbaca9454f4ba4). The …
> improvement: Add AST subclass constructors

- stubs/antlr4-python3-runtime/antlr4/atn/ATNType.pyi
- stubs/antlr4-python3-runtime/antlr4/atn/LexerAction.pyi
- stubs/antlr4-python3-runtime/antlr4/atn/PredictionMode.pyi
- stubs/flake8/flake8/options/manager.pyi
- stubs/flake8/flake8/style_guide.pyi
- stubs/fpdf2/fpdf/enums.pyi
- stubs/regex/regex/_regex_core.pyi
Follow up to #11956.
This PR handles all third party stubs except Pillow and pygit2 that I'll change in a follow up.
> Use assignment instead of annotation in third party enums

- stdlib/gzip.pyi
These were changed to str in py313
> gzip: change type of undocumented constants

- tests/regr_test.py
- uv's cache is (nearly always) threadsafe, unlike pip's, so we don't need the `--no-cache-dir` argument (unless we're using a very old version of Windows).
- Fix a deadlock on KeyboardInterrupt where the printer thread would never be joined and the script would never exit unless you pressed CTRL+C several times in quick succession
> regr_test.py: improve several concurrency details

- tests/README.md
- tests/stubtest_stdlib.py
- tests/stubtest_third_party.py
- tests/utils.py
This makes it trivial to consistently extend supported allowlists in the future.
> Unify stubtest allowlist handling more

- stubs/Flask-Cors/flask_cors/extension.pyi
`flask_cors.CORS` accepts `flask.Blueprint` objects, so update the stub to support that. Example from Flask-Cors' docs [here](https://flask-cors.readthedocs.io/en/latest/api.html#using-cors-with-blueprints).
> Update `Flask-Cors` extension stubs to accept Flask Blueprints

- stdlib/shutil.pyi
- stubs/setuptools/setuptools/compat/py311.pyi
Noticed while adding pyright checks to setuptools (https://github.com/pypa/setuptools/pull/4192)
Doc reference: https://docs.python.org/3/library/shutil.html#shutil.rmtree
I also tested locally that the parameter is indeed optional.
---
I also changed the `Exception` type in `_OnExcCallback` for `baseException` so it works with `ExcInfo`:
```
Argument of type "_OnExcCallback | None" cannot be assigned to parameter "onexc" of type "_OnExcCallback" in function "__call__"
Type "_OnExcCallback | None" is incompatible with type "_OnExcCallback"
Type "None" is incompatible with type "_OnExcCallback"
```
`Argument 3 has incompatible type "BaseException"; expected "Exception"`
```py
def shutil_rmtree(
path: StrOrBytesPath,
ignore_errors: bool = False,
onexc: shutil._OnExcCallback | None = None,
) …
```
> Make `shutil.rmtree.onexc` parameter optional

- .pre-commit-config.yaml
This is causing pre-commit to fail for me locally on my newish macbook because it's trying to use a python3.10 executable for the hook, and I don't have a python3.10 executable available locally. I don't think we need this setting in .pre-commit-config.yaml, as we already have it set in pyproject.toml here; and removing it from .pre-commit-config.yaml makes pre-commit runnable for me locally:
https://github.com/python/typeshed/blob/fca4da54b1fe59e84560b682aa9155c4bfd96fb3/pyproject.toml#L3
> Remove `language_version` from black hook in `.pre-commit-config.yaml`

- .github/workflows/daily.yml
- .github/workflows/stubtest_stdlib.yml
I got this email the other day, indicating that we need to move off macos-11:
I tried macos-14 and macos-13, but various extension modules like `_tkinter` still can't be imported on Python with those runners. macos-12 seems best for now.
> Use macos-12 for stdlib stubtest in CI

- stdlib/@tests/stubtest_allowlists/darwin-py313.txt
- stdlib/@tests/stubtest_allowlists/linux-py313.txt
- stdlib/@tests/stubtest_allowlists/py313.txt
This is an internal-only module; I don't think we should add stubs for any of the submodules
> py313: Consolidate `_pyrepl` allowlist entries

- stubs/pyserial/serial/serialutil.pyi
Fixes #12034 
Reference: https://pyserial.readthedocs.io/en/latest/pyserial_api.html#serial.Serial
> pyserial: serial: serialutil.pyi: fix excuslive float -> bool

- stubs/docker/docker/api/container.pyi
This is a dictionary with the response described in:
https://docs.docker.com/engine/api/v1.45/#tag/Container/operation/ContainerWait
> Add return type for Docker Container wait

- stubs/shapely/shapely/_typing.pyi
- stubs/shapely/shapely/wkb.pyi
- stubs/shapely/shapely/wkt.pyi
This was changed in response to https://github.com/python/typeshed/pull/12033#discussion_r1614535925. It caused some tests to fail in my repo when I tested the typeshed stubs.
/cc @srittau
> Fix shapely SupportsRead protocol

- stdlib/@tests/stubtest_allowlists/darwin-py313.txt
- stdlib/@tests/stubtest_allowlists/linux-py313.txt
- stdlib/time.pyi
Update `time` module changes for Python3.13
> `time`: Python3.13 updates

- stdlib/logging/handlers.pyi
Similar to [this issue](https://github.com/python/typeshed/issues/6130), which lead to [this PR](https://github.com/python/typeshed/pull/6128).
Just a few lines below `maxBytes` has type set to `int`.
>  Change type of `logging.RotatingFileHandler.maxBytes` from str to int

- stdlib/itertools.pyi
Fix typing errors when itertools.product is called with more than 6 arguments.
> Extend itertools.product to 10 arguments

- stubs/docker/METADATA.toml
- stubs/docker/docker/api/client.pyi
Closes https://github.com/python/typeshed/pull/12025
I propose removing the default value from this param, because it is version specific.
> Update docker to 7.1.x

- stdlib/@tests/stubtest_allowlists/py313.txt
- stdlib/enum.pyi
Ref: https://github.com/python/cpython/pull/112514
> `enum`: Python 3.13 update

- pyproject.toml
VS Code's json schema for pyproject.toml warned me about these fields. They are currently allowed but may get deprecated (see https://github.com/psf/black/issues/4178).
> Use hyphenated options in black config in pyproject.toml

- stubs/shapely/shapely/_geometry.pyi
- stubs/shapely/shapely/constructive.pyi
- stubs/shapely/shapely/strtree.pyi
> Update shapely enums

- tests/mypy_test.py
- tests/regr_test.py
Before this change, mypy tests were printing a warning about seaborn requiring Python >= 3.9 even when the test invoked did not target seaborn (eg `python tests/mypy_test.py stubs/shapely`). With this change, the mentioned command does not warn about seaborn while both `python tests/mypy_test.py stubs/s*` and `python tests/mypy_test.py stubs/seaborn` still print the warning.
> `mypy_test.py`: warn about incompatible python version only on tested files

- stubs/greenlet/greenlet/__init__.pyi
> greenlet: Adds missing `__version__` variable

- stdlib/enum.pyi
Fixed definitions of EnumCheck and FlagBoundary enum members so they conform to the recently updated typing standard.
This was reported as a [bug in pyright 1.1.366](https://github.com/microsoft/pyright/issues/8079), which implements the recent changes in the typing spec related to enums. I thought we had found and fixed all Enum class definitions in typeshed, but these two were missed.
> Fixed definitions of EnumCheck and FlagBoundary enum members

- stdlib/types.pyi
`FunctionType.__kwdefaults__` can be `None` on 3.8 through 3.13 from my minimal checking. Should be reproducible by running the code below:
```py
def ex():
...
print(ex.__kwdefaults__)  # Output should be 'None'
```
Side note, unrelated to typeshed: The Python [docs](https://docs.python.org/3/reference/datamodel.html#function.__kwdefaults__) don't really indicate this attribute can be `None` either, so a slight clarification there might be warranted too. I might attempt that if this goes through.
>  `function.__kwdefaults__` - A dictionary containing defaults for keyword-only parameters.
> Make `FunctionType.__kwdefaults__` optional.

- stdlib/shutil.pyi
- Adjust wording: the `onerror` parameter is no longer expected to be removed in Python 3.14
- Fix it so that type checkers only emit an error if an argument is actually passed for the `onerror` parameter. If no argument is passed, there's no need for type checkers to emit a diagnostic.
Fixes #12103
> Fix false positives from `@deprecated` for `shutil.rmtree`

- stubs/jsonschema/METADATA.toml
> Ensure stubtest gets an older version of `webcolors` when testing `jsonschema` in CI

- .github/workflows/daily.yml
- .github/workflows/stubtest_stdlib.yml
If you manually trigger a stubtest run on the main branch, it's very red right now due to the setup-python builds for 3.12.4 and 3.13.0b2 being very broken: https://github.com/actions/setup-python/issues/886
> Pin to older micro versions of Python for stdlib stubtest

- stdlib/@tests/stubtest_allowlists/py313.txt
- stdlib/VERSIONS
From [What's new in Python 3.13](https://docs.python.org/3.13/whatsnew/3.13.html) ...
> Also removed were the `tkinter.tix`
> `tkinter.tix` is removed in Python 3.13

- stubs/Flask-SocketIO/@tests/stubtest_allowlist.txt
- stubs/Flask-SocketIO/flask_socketio/__init__.pyi
Reference: 
- https://flask-socketio.readthedocs.io/en/latest/getting_started.html#class-based-namespaces
- https://github.com/miguelgrinberg/Flask-SocketIO/blob/main/src/flask_socketio/__init__.py#L26
- https://flask-socketio.readthedocs.io/en/latest/api.html#flask_socketio.SocketIOTestClient
Otherwise, [the example](https://flask-socketio.readthedocs.io/en/latest/getting_started.html#initialization) will complain about these arguments.
Also, they are [derived from `debug` argument](https://github.com/miguelgrinberg/Flask-SocketIO/blob/main/src/flask_socketio/__init__.py#L569-L581), so I have no idea how a better type hinting could be given.
Reference: 
- https://github.com/miguelgrinberg/Flask-SocketIO/blob/main/src/flask_socketio/__init__.py#L559
(Please squash merge, as useless …
> Flask-SocketIO: fix type hints

- stdlib/tarfile.pyi
Fix issues detailed in https://github.com/python/typeshed/issues/5491 by adding an appropiate overload when the tar file is being opened in a write mode.
> Add missing `tarfile.open` overload for writable objects

- stdlib/asyncio/tasks.pyi
It is not allowed in Python 3.12+.
Closes https://github.com/python/typeshed/issues/10116
> remove Generator from _FutureLike

- stubs/aiofiles/aiofiles/tempfile/__init__.pyi
Add missing `delete_on_close` per https://github.com/python/typeshed/issues/12091.
> Add missing delete on close arg for `aiofiles.NamedTemporaryFile` 

- stubs/openpyxl/openpyxl/worksheet/_read_only.pyi
> Copy `openpyxl`'s `Worksheet.__getitem__()` and `.__iter__()` to `ReadOnlyWorksheet`

- stubs/docker/docker/models/containers.pyi
See implementation at
https://github.com/docker/docker-py/blob/a3652028b1ead708bd9191efb286f909ba6c2a49/docker/models/containers.py#L534 which includes in the docstring:
```
If the ``detach`` argument is ``True``, it will start the container
and immediately return a :py:class:`Container` object, similar to
``docker run -d``.
```
> Add return types to docker container run

- stubs/assertpy/assertpy/extracting.pyi
The `extracting` method support 2 kwargs: [`sort` and `filter`](https://github.com/assertpy/assertpy/blob/main/README.md#extracting-and-filtering). Each accepts different value types. `sort` accepts `str | Iterable | Callable` and `filter` accepts `str | dict | Callable`. Using a value type other than `dict` with the current stubs requires lots of `# type: ignore[arg-type]` comments in test code. So we change to use `Any` as the `kwargs` value type.
> assertpy: improve type for extracting

- stubs/docker/docker/_types.pyi
- stubs/docker/docker/api/container.pyi
- stubs/docker/docker/models/containers.pyi
Also, improve type for the API layer.
Previously, the type accounted for a 404 response. However, in the 404 case, a `docker.errors.NotFound` exception is raised.
> Add Container wait return type at Docker model layer

- scripts/stubsabot.py
> Replace `Github` -> `GitHub` in `scripts/stubsabot.py`

- .github/workflows/mypy_primer.yml
I'd like for us to cover projects that use Python 3.12 only syntax
> Use Python 3.12 for mypy_primer

- stubs/assertpy/assertpy/extracting.pyi
The recent change to better type the `sort` and `filter` kwargs had the side effect of making them required. So we fix to supply a default argument.
> Update assertpy/extracting.pyi so that kwargs are not required

- stdlib/mmap.pyi
Per the documentation, always returns true: https://docs.python.org/3.13/library/mmap.html#mmap.mmap.seekable
> More accurate `mmap.seekable` type for 3.13

- stdlib/abc.pyi
Noticed this in primer output from python/mypy#17476.
> abc: Shorten `@deprecated` messages

- stubs/pytest-lazy-fixture/pytest_lazyfixture.pyi
Source code: https://github.com/TvoroG/pytest-lazy-fixture/blob/18ec85edb5e27c933733f748c685b2fd083198d7/pytest_lazyfixture.py#L185-L186
> `is_lazy_fixture` in `pytest-lazy-fixture` is a `TypeIs` function

- scripts/stubsabot.py
Let's test this :)
Closes #12272
> Fix str2bool failure on stubsabot dry-run

- stubs/docutils/docutils/parsers/rst/__init__.pyi
- stubs/docutils/docutils/parsers/rst/states.pyi
removes an unneeded generic from docutils `RSTState`.
see the discussion in https://github.com/sphinx-doc/sphinx/pull/12511
> remove generic 'context' from 'docutils.parsers.rst.RSTState'

- stdlib/@tests/test_cases/check_io.py
- stdlib/io.pyi
Let's try this :)
Refs https://github.com/python/typeshed/pull/11420
Refs https://github.com/python/typeshed/issues/11418
> Add a typevar with a default to `io.TextIOWrapper`

- stdlib/@tests/stubtest_allowlists/py313.txt
- stdlib/zipfile/__init__.pyi
- stdlib/zipfile/_path.pyi
Add in the new `inject` method, and the a new `compress_level` property for `ZipInfo`.
> Update `zipfile` for 3.13

- stdlib/@tests/stubtest_allowlists/py313.txt
- stdlib/sre_constants.pyi
Remove unused constant in 3.13.
> `SRE_FLAG_TEMPLATE` removed in 3.13

- stubs/requests/requests/models.pyi
This PR is a type fix for the `requests` library to add `connection: HTTPAdapter` to `Response`.
The `Response` instance is built by `HTTPAdapter`. When built, a property called [`connection` is added to the `Response`](https://github.com/psf/requests/blob/0e322af87745eff34caffe4df68456ebc20d9068/src/requests/adapters.py#L392) that points back to the `HTTPAdapter` that created it. For example, the `requests` library's [`HTTPDigestAuth` class remakes requests](https://github.com/psf/requests/blob/0e322af87745eff34caffe4df68456ebc20d9068/src/requests/auth.py#L276) with credentials after authorization is requested by a server.
> requests: Add connection property (type HTTPAdapter) to the Response class

- stdlib/warnings.pyi
"all" as a valid alias for "always" action has been added in the https://github.com/python/cpython/pull/121164
> [warnings]: Update `_ActionKind` to match Python 3.14

- tests/_utils.py
- tests/check_typeshed_structure.py
- tests/mypy_test.py
Preliminary refactoring for fixing #12298.
> Extract VERSIONS parsing to _utils.py

- stubs/openpyxl/openpyxl/drawing/image.pyi
`Image` has `height` and `width` set in the constructor, but they are missing from the stub.
> Add dimensions for openpyxl Image.

- stdlib/@tests/stubtest_allowlists/darwin-py313.txt
- stdlib/os/__init__.pyi
`os.waitid` and `os.waitid_result` were added for MacOS in 3.13
> Add `os.waitid` for macos in 3.13

- stdlib/@tests/stubtest_allowlists/linux-py313.txt
- stdlib/syslog.pyi
The following constants don't exist in the Linux kernel, and the constant definitions match what we have in xnu: https://opensource.apple.com/source/xnu/xnu-201.5/bsd/sys/syslog.h.auto.html
> Fix `syslog` 3.13 issues

- stubs/setuptools/METADATA.toml
- stubs/setuptools/pkg_resources/__init__.pyi
As of https://setuptools.pypa.io/en/latest/history.html#v71-1-0 , `pkg_resources` is marked as `py.typed`.
I can't really use the `obsolete_since` marker, but I think an `extra_description` is good enough.
Closes #12399
> Bump setuptools to 71.1.* and mark `pkg_resources` as obsolete

- stubs/ExifRead/exifread/_types.pyi
Changes return type for `Reader.__iter__()` from `bytes` to `Iterator[bytes]`.
**Related Issues:**
- Closes #12371
> ExifReader: Fix `Reader.__iter__()`

- stubs/redis/METADATA.toml
> Mark redis as obsolete

- CONTRIBUTING.md
> Require documenting `Any` uses

- stdlib/multiprocessing/forkserver.pyi
- stdlib/multiprocessing/popen_spawn_win32.pyi
- stdlib/multiprocessing/reduction.pyi
- stdlib/multiprocessing/spawn.pyi
- stdlib/multiprocessing/util.pyi
Move `multiprocessing` constants to `Final` as none of these constants are documented.
> Use Final for `multiprocessing` constants

- stdlib/unittest/case.pyi
- stdlib/unittest/loader.pyi
- stdlib/unittest/main.pyi
- stdlib/unittest/result.pyi
- stdlib/unittest/util.pyi
Use Final for all `unittest` constants except https://docs.python.org/3/library/unittest.mock.html#default and https://docs.python.org/3/library/unittest.mock.html#filter-dir, which are documented and make sense to override in cases.
> Use Final for `unittest` constants

- stdlib/zipfile/__init__.pyi
These constants represent compression methods, and shouldn't be overridden.
> Use `Final` for `zipfile` constants

- stdlib/symtable.pyi
CC @JelleZijlstra, I was referring to this with my question on Discord.
> Reflect deprecation for `symtable.Class.get_methods()`

- stubs/pygit2/pygit2/__init__.pyi
The [pygit2](https://github.com/python/typeshed/tree/main/stubs/pygit2) stubs package was missing the `as` keyword (`import ... as ...`) for `pygit2.RemoteCallbacks` causing it to not be found by mypy.
This PR simply adds this so `RemoteCallbacks` is reexported from the module `pygit2`.
> Add reexport to RemoteCallbacks in pygit2

- requirements-tests.txt
- stdlib/_ctypes.pyi
Closes https://github.com/python/typeshed/pull/12501
> Update pyright to 1.1.375

- stdlib/tkinter/__init__.pyi
There are common options (that are almost always used) for the Listbox `selectmode`, these are taken from the docs here https://tcl.tk/man/tcl8.6/TkCmd/listbox.htm#M9
My making the selectmode `Literal[...] | str` typecheckers will pass any string, but e.g. vscode will suggest the literal options.
> `tkinter`: add suggested `Listbox` `selectmode`s

- stdlib/sqlite3/dbapi2.pyi
`version_info` and `version` were both removed in 3.14: https://github.com/python/cpython/issues/93370
> sqlite3 removals for 3.14

- stdlib/argparse.pyi
Remove the deprecated overload for 3.14: https://docs.python.org/es/dev/whatsnew/3.14.html#argparse
> Update `argparse.BooleanOptionalAction` for 3.14

- stdlib/@tests/test_cases/check_dataclasses.py
- stdlib/dataclasses.pyi
Fixes #12401 by adding a hack, in the form of overload `def is_dataclass(obj: Never)` -- because `Any` is compatible with `Never`, but no real type is.
Previously `is_dataclass(Any)` matched the wrong overload rule and inferred incorrect return type.
> Fix inferred type of `is_dataclass(Any)`

- stdlib/datetime.pyi
First time contributor here. Please correct or reject if not needed.
This pull request is to address the imprecise deprecation messages regarding timezone-aware datetime objects
Issue: #12328
> more precise timezone-aware deprecation message

- stdlib/zipfile/__init__.pyi
- stdlib/zipfile/_path.pyi
Noticed a typing issue using `Path.at` (see example below) and turn out the attribute was missing in a stub file.
```python
from zipfile import Path
zip_path = Path("C:/test.zip", "file.txt")
print(zip_path.at)  # will print 'file.txt'
```
> fix missing 'at' attribute in zipfile.Path

- stubs/flake8-2020/flake8_2020.pyi
Ref https://github.com/python/typeshed/issues/9550
Flake8-2020 is also archived: https://github.com/asottile-archive/flake8-2020#archived & https://github.com/asottile-archive/flake8-2020#archived
Do we want to mark it with `no_longer_updated = true` for the same reasons we did https://github.com/python/typeshed/pull/8929 ?
> Flake8-2020: Add Final and remove Any

- CONTRIBUTING.md
Note that the section about `no_longer_updated` makes no mention of a 6 month wait period.
> Update outdated labels and stub_uploader timing in CONTRIBUTING.md

- stubs/flake8-2020/METADATA.toml
flake8-2020 is archived: https://github.com/asottile-archive/flake8-2020#archived & https://github.com/asottile-archive/flake8-2020#archived
Following our [Third-party library removal policy](https://github.com/python/typeshed/blob/main/CONTRIBUTING.md#third-party-library-removal-policy) and https://github.com/python/typeshed/pull/12538#issuecomment-2294940947, this should be merged in 6 months, then removed after the next run of stub_uploader.
> [February 2025] flake8-2020 is an archived repo

- stdlib/cmd.pyi
More accurate type for `IDENTCHARS` in `cmd`.
> Use `Final` in `cmd`

- stubs/JACK-Client/METADATA.toml
- stubs/networkx/METADATA.toml
- stubs/seaborn/METADATA.toml
- stubs/shapely/METADATA.toml
- stubs/tensorflow/METADATA.toml
Releases: https://pypi.org/project/numpy/#history
Closes https://github.com/python/typeshed/issues/12551
> Pin numpy in various stubs

- stdlib/socketserver.pyi
Fixed `DatagramRequestHandler.packet` type hint to be `bytes`. `typeshed` is currently typing it as a `socket`.
In Python's stdlib, `packet` is set in the following code located in socketserver.py.
```Python
class DatagramRequestHandler(BaseRequestHandler):
"""Define self.rfile and self.wfile for datagram sockets."""
def setup(self):
from io import BytesIO
self.packet, self.socket = self.request
self.rfile = BytesIO(self.packet)
self.wfile = BytesIO()
```
`self.packet` is the first element in the `self.request` tuple which is a `typedshed._RequestType`.
```Python
_RequestType: TypeAlias = _socket | tuple[bytes, _socket]
```
Additionally, in the `setup()` method shown above `self.packet` is being passed to `BytesIO()`, so it is definitely a `bytes` object.
> Fix DatagramRequestHandler.packet type hint.

- stdlib/@tests/test_cases/builtins/check_dict-py39.py
- stdlib/@tests/test_cases/builtins/check_dict.py
- stdlib/@tests/test_cases/builtins/check_pow.py
- stdlib/@tests/test_cases/builtins/check_sum.py
- stdlib/@tests/test_cases/check_dataclasses.py
- stdlib/@tests/test_cases/collections/check_defaultdict-py39.py
- stdlib/collections/__init__.pyi
- stdlib/dataclasses.pyi
- stdlib/typing.pyi
- stubs/JACK-Client/jack/__init__.pyi
- stubs/Pillow/@tests/test_cases/check_tk_compat.py
- stubs/WebOb/@tests/test_cases/check_wsgify.py
- stubs/openpyxl/@tests/test_cases/check_base_descriptors.py
- stubs/openpyxl/@tests/test_cases/check_nested_descriptors.py
- stubs/pygit2/pygit2/_pygit2.pyi
- stubs/pygit2/pygit2/utils.pyi
- stubs/pywin32/win32comext/axdebug/documents.pyi
- tests/pytype_test.py
A lot of these pyright ignores didn't have associated error code before, hence we had to use a blank suppression comment
I also re-enabled tests that used to fail on pyright, but now pass.
xref https://github.com/python/mypy/issues/12358 for some tests that are still disabled
> Using precise code for `pyright: ignore` and re-enabling various pyright tests

- stdlib/socketserver.pyi
This better matches [the documentation](https://docs.python.org/3/library/socketserver.html#socketserver.StreamRequestHandler) and it also removes instances of the problematic `BinaryIO` semi-protocol.
> socketserver: Use BufferedIOBase instead of BinaryIO

- stubs/docker/docker/models/containers.pyi
Instead of `dict[str, str] | ...` the `volumes` keyword argument accepts `dict[str, dict[str, str]] | ...` in **./docker/models/containers.pyi**
see documentation: [docker-py.readthedocs.io/en/stable/containers.html](https://docker-py.readthedocs.io/en/stable/containers.html#docker.models.containers.ContainerCollection.run) (at the moment version 7.1, but it is the same for older version too)
```
volumes (dict or list) –
A dictionary to configure volumes mounted inside the container. The key is either the host path or a volume name, and the value is a dictionary with the keys:
bind The path to mount the volume inside the container
mode Either rw to mount the volume read/write, or ro to mount it read-only.
For example:
{'/home/user1/': {'bind': '/mnt/vol2', 'mode': 'rw'},
'/var/www': …
```
> Fix 'volumes' argument type hint for 'run' and 'create' functions in containers.pyi

- stubs/Flask-Cors/flask_cors/core.pyi
- stubs/Flask-Cors/flask_cors/version.pyi
@srittau As promised, I have added the constants.
> Improve type annotations in Flask-Cors stubs

- stdlib/codecs.pyi
Closes #10656 
I ran into the same issue recently. The actual type of input is `memoryview` which tripped me up because I was calling `input.decode("utf-8")` which of course fails for a `memoryview`.
> Fix signature of `CodecInfo.decode`

- stubs/requests/requests/models.pyi
Documented at https://requests.readthedocs.io/en/latest/user/quickstart/#raw-response-content. This is `None` on a new `Response()`.
> Add hint for requests.models.Response.raw

- stubs/beautifulsoup4/bs4/formatter.pyi
As used by the library itself here:
https://git.launchpad.net/beautifulsoup/tree/bs4/formatter.py?h=4.12.3#n168
> beautifulsoup4: Accept void_element_close_prefix=None

- stubs/docutils/docutils/nodes.pyi
The documentation says:
self.transform = transform
"""The `docutils.transforms.Transform` class implementing the pending
operation."""
> Fix type of `transform` argument of `docutils.nodes.pending.__init__`

- tests/_utils.py
- tests/mypy_test.py
- tests/pytype_test.py
Filter the files to run pytype tests on by stdlib/VERSIONS file. This becomes important for Python 3.12, where e.g. checking asynchat.pyi requires asyncore.pyi, both of which have been removed in 3.12.
The implementation was copied from mypy_test.py and adapted to fit into the existing pytype test setup.
---
We're in the process of releasing a new pytype version, which will include basic support for Python 3.12. (I plan to send a separate PR for that soon.) When running pytype_test.py with that new version under 3.12 we saw errors like
```
stdlib/asynchat.pyi (3.12): pytype.load_pytd.BadDependencyError: Can't find pyi for 'asyncore', referenced from 'asynchat'
```
As far as I understand the fix is to not run on stdlib/asynchat.pyi in the first place.
> Filter pytype tests by stdlib/VERSIONS file

- .github/workflows/tests.yml
- requirements-tests.txt
- tests/README.md
- tests/pytype_test.py
pytype 2024.09.13 got released today and includes basic support for Python 3.12.
`python tests/pytype_test.py` runs successfully under Python 3.12 with the new version.
> Update pytype to 2024.09.13 and Python 3.12

- stubs/requests/requests/api.pyi
Utilize `http.cookiejar.CookieJar` instead of the internal `RequestsCookieJar`.
Fixes: https://github.com/python/typeshed/issues/12593
> Correct requests `cookies` argument

- stdlib/@tests/stubtest_allowlists/darwin-py310.txt
- stdlib/@tests/stubtest_allowlists/darwin-py311.txt
- stdlib/@tests/stubtest_allowlists/darwin-py312.txt
- stdlib/@tests/stubtest_allowlists/darwin-py38.txt
- stdlib/@tests/stubtest_allowlists/darwin-py39.txt
- stdlib/@tests/stubtest_allowlists/darwin.txt
- stdlib/@tests/stubtest_allowlists/linux-py310.txt
- stdlib/@tests/stubtest_allowlists/linux-py311.txt
- stdlib/@tests/stubtest_allowlists/linux-py312.txt
- stdlib/@tests/stubtest_allowlists/linux-py38.txt
- stdlib/@tests/stubtest_allowlists/linux-py39.txt
- stdlib/@tests/stubtest_allowlists/linux.txt
- stdlib/@tests/stubtest_allowlists/win32-py313.txt
- stdlib/VERSIONS
`_msi` was removed with the removal of `msilib`.
> Remove `_msi` in 3.13

- .github/workflows/meta_tests.yml
- .github/workflows/tests.yml
- CONTRIBUTING.md
- requirements-tests.txt
- tests/README.md
- tests/pytype_test.py
- tests/runtests.py
- tests/typecheck_typeshed.py
Similar to https://github.com/python/typeshed/pull/12547 , allowing pytype to be run on Windows, but makes it optional and avoids installing it on the CI (until prebuilt wheels are available). See https://github.com/python/typeshed/pull/12547#issuecomment-2348775900 and https://github.com/google/pytype/pull/1756
Closes #12547 (I think it's obvious from this PR which comments/docs need to be updated or removed once prebuilt wheels are available)
> Optional pytype install on Windows (no CI)

- stubs/xdgenvpy/METADATA.toml
- stubs/xdgenvpy/xdgenvpy/__init__.pyi
Diff: https://gitlab.com/deliberist-group/xdgenvpy/-/compare/release%2F2.4.0...release%2F3.0.0?from_project_id=12517320&straight=false
Closes https://github.com/python/typeshed/pull/12665
> Bump xdgenvpy to 3.0.*

- stubs/fpdf2/fpdf/fpdf.pyi
"BI" usage in `FPDF.add_font()`'s `style` parameter (only place where the `_FontStyle` type is used) is supported by fpdf2's code and official documentation. ([doc](https://py-pdf.github.io/fpdf2/Unicode.html#adding-and-using-fonts)) ([code](https://github.com/py-pdf/fpdf2/blob/d9f5d3634ac17b81ba6e3c9e77be6c20c41a339c/fpdf/fpdf.py#L1918))
I believe this was typed incorrectly due to a [vague docstring](https://py-pdf.github.io/fpdf2/fpdf/fpdf.html#fpdf.fpdf.FPDF.add_font), which I'm looking to clarify in [this fpdf2 PR](https://github.com/py-pdf/fpdf2/pull/1263).
Sorry for the small PR but I felt it was appropriate.
> fix: fpdf2: Allow `"BI"` for `_FontStyle` in `fpdf.pyi`

- .github/workflows/meta_tests.yml
- .github/workflows/tests.yml
- tests/pyright_test.py
Available since https://github.com/microsoft/pyright/releases/tag/1.1.371 , crash fixed in https://github.com/microsoft/pyright/releases/tag/1.1.377 (https://github.com/microsoft/pyright/issues/8775)
> Add --threads argument to pyright cli

- .github/workflows/meta_tests.yml
- .github/workflows/tests.yml
- pyrightconfig.stricter.json
- tests/pyright_test.py
This reverts commit f0e16b8.
See conversation in #12688: for this repo, it seems like the argument actually makes pyright run slower, rather than faster.
This PR also switches us to use stricter pyright settings for `xdgenvpy` in CI, which fixes https://github.com/AlexWaygood/typeshed-stats/issues/246, fixes https://github.com/AlexWaygood/typeshed-stats/issues/254, fixes https://github.com/AlexWaygood/typeshed-stats/issues/255, fixes https://github.com/AlexWaygood/typeshed-stats/issues/256, fixes https://github.com/AlexWaygood/typeshed-stats/issues/257, fixes https://github.com/AlexWaygood/typeshed-stats/issues/258, fixes https://github.com/AlexWaygood/typeshed-stats/issues/259, fixes https://github.com/AlexWaygood/typeshed-stats/issues/260, fixes …
> Fixup some pyright CI configuration details

- stubs/fpdf2/fpdf/fpdf.pyi
Methods with the `link` argument can take an internal link (created via `add_link` which returns an `int`) or an external URL as per their docstring.
The type hint only allows for `str`.
`link` already has the correct type hint:
https://github.com/python/typeshed/blob/a94c927642eda093db226eb3e21c3a4681577f85/stubs/fpdf2/fpdf/fpdf.pyi#L343-L345
`add_link` returns an `int`:
https://github.com/python/typeshed/blob/a94c927642eda093db226eb3e21c3a4681577f85/stubs/fpdf2/fpdf/fpdf.pyi#L341
This PR changes the type hint to `str | int`.
> [fpdf2] fix link type to support internal links

- stubs/paramiko/paramiko/transport.pyi
According to https://docs.paramiko.org/en/latest/api/proxy.html, `ProxyCommand` is socket-like.
> paramiko: add `ProxyCommand` to `_SocketLike`

- tests/_metadata.py
- tests/get_external_stub_requirements.py
- tests/mypy_test.py
- tests/pytype_test.py
- tests/regr_test.py
- tests/stubtest_third_party.py
This allows us to keep metadata like python_version and platform_system
and use it to conditionally install packages.
> Pass `Requirement` objects around

- CONTRIBUTING.md
Upstream annotations should have a similar standard as typeshed's.
Closes: #11955
> Amend third-party removal policy

- stdlib/http/client.pyi
I've found code in the library that in a nutshell did this:
```py
headers = {}
headers["Content-Length"] = len(data)
an_https_connection.request("PUT", url, data, headers)
```
And the type checker was not happy about an `int` as a header value.
Apparently Python stdlib allows:
- anything with `.encode("ascii")` since Python 3.0
- an int, explicitly, at least since Python 3.2
- anything that can be passed to `bytes.join`, which is a ReadableBuffer in typeshed
References:
https://github.com/python/cpython/blob/v3.0/Lib/http/client.py
https://github.com/python/cpython/blob/6046c5e0298c25515ea58abc8ab87f7413e3f743/Lib/http/client.py#L831-L834
https://github.com/python/cpython/blob/3.2/Lib/http/client.py
https://github.com/python/cpython/blob/076ca6c3c8df3030307e548d9be792ce3c1c6eea/Lib/http/cl …
> fix: correct headers= kwarg in HTTP[S]Connection

- .github/workflows/tests.yml
- pyrightconfig.json
- stubs/seaborn/METADATA.toml
- tests/README.md
- tests/_metadata.py
- tests/get_external_stub_requirements.py
- tests/pytype_test.py
This still has limitations and exposes problems:
* Platform markers don't work yet, since pyright and uv have different ideas what platforms exist.
* Typed matplotlib is only available for Python 3.9+. Currently, the pyright tests use the same dependencies for all Python versions, making it impossible to test packages with a dependency on matplotlib.
> Support environment markers in requires fields

- tests/_utils.py
- tests/stubtest_third_party.py
- tests/typecheck_typeshed.py
Also add prefix to tmpdir name
> Add option to keep tmp dir to stubtest script

- stubs/redis/redis/client.pyi
solves #12149, the gist of which is:
- a Redis client (redis.Redis) can be obtained by using either its constructor, or `from_url` method
- connection options can be specified as arguments to either 
- some of those options (eg `ssl_ca_data`) were missing as defined parameters for `from_url`
- this caused mypy to give false positives those missing SSL options were specified as kwargs to `from_url`
To fix the issue, following 9 options were added as params to `from_url`
- `ssl_ca_path`
- `ssl_ca_data`
- `ssl_password`
- `ssl_validate_ocsp`
- `ssl_validate_ocsp_stapled`
- `ssl_ocsp_context`
- `ssl_ocsp_expected_cert`
- `redis_connect_func`
- `credential_provider`
> Add missing ssl related arguments to Redis from_url method

- stdlib/xmlrpc/client.pyi
- stdlib/xmlrpc/server.pyi
Two minor fixed to the typeshed:
1.    data may be both `str` and `bytes`; actually CPython uses it both ways
2.    `method=None` does not make much sense and should never happen 🤞
@JelleZijlstra This PR replaces https://github.com/python/typeshed/pull/12071 as I no longer work for @univention and thus no longer have access to the old repository.
> Xmlrpc: accept data:str|bytes and require method:str

- .pre-commit-config.yaml
Renovate won't update this dependency (no automated tools I know of will, sadly) because it exists in the `additional_dependencies` list for this hook.
> Bump flake8-pyi to 24.9.0

- requirements-tests.txt
I'm surprised I'm the first to mention this, maybe the CI and other maintainers (that are using 3.13) have Rust compilation tools already installed and didn't notice?
On Windows, python 3.13, running `python3.13 -m pip install -r .\requirements-tests.txt` results in the following error:
```
Building wheels for collected packages: libcst
Building wheel for libcst (pyproject.toml) ... error
error: subprocess-exited-with-error
× Building wheel for libcst (pyproject.toml) did not run successfully.
│ exit code: 1
╰─> [397 lines of output]
C:\Users\Avasam\AppData\Local\Temp\pip-build-env-3pmjtsds\overlay\Lib\site-packages\setuptools\_distutils\dist.py:261: UserWarning: Unknown distribution option: 'test_suite'
warnings.warn(msg)
WARNING setuptools_scm.pyproject_reading toml section missing …
```
> Lock stubdefaulter to python_version < "3.13" due to missing 3.13 libcst wheels

- stdlib/unittest/mock.pyi
This matches the runtime.
Related to https://github.com/python/typeshed/issues/3968
> add unittest.mock.Base to MagicMixin and MagicProxy

- stubs/six/@tests/stubtest_allowlist.txt
Follow-up to #12749
Fixes #12758
> Allowlist `six.create_bound_method.__code__` (Fix daily test failure)

- stdlib/shlex.pyi
It was changed to Iterable on the basis that `__next__` was abstract: https://github.com/python/typeshed/issues/1476#issuecomment-388663644
But that doesn't seem to be true? Let's see what the test suite says.
> make shlex.shlex Iterator

- stdlib/ipaddress.pyi
added in 2017: https://github.com/python/typeshed/pull/1361
This use case no longer requires the protocol to be an actual base class.
> remove SupportsInt from bases of ipaddress._BaseAddress

- stdlib/@tests/stubtest_allowlists/common.txt
* Move all platform and installation differences into a separate section.
* ~~Remove temporary entries that should be fixed by now.~~
* Split sections for missing items into "should be fixed" and "should not be fixed".
* Add "TODO" markers to appropriate sections.
There probably are some items in the TODO section that should be moved to the "should not be fixed" section, but I want the changes in this PR to be conservative.
> Clean up common stubtest allowlist

- requirements-tests.txt
pytype 2024.10.11 fixes an issue around ParamSpec and circular imports.
pytype 2024.10.11 also drops support for Python 3.8 and 3.9. To account for that, this PR adds a python_version restriction to requirements-tests.txt.
I tested this version with https://github.com/python/typeshed/pull/12745 and confirmed that it fixes the issue.
> Update pytype to 2024.10.11

- CONTRIBUTING.md
- README.md
> Document the supported stdlib versions

- stdlib/hmac.pyi
Attempts to resolve this `# TODO`:
https://github.com/python/typeshed/blob/03fe755ec11617b7437ddb3f914a9d06a022be1d/stdlib/hmac.pyi#L7-L8
This PR replaces the `_Hash` alias with the existing [`hashlib._Hash`](https://github.com/python/typeshed/blob/03fe755ec11617b7437ddb3f914a9d06a022be1d/stdlib/hashlib.pyi#L51), which seems to work perfectly here (all protocol members are used somewhere in `hmac`, and no expected members are missing).
I couldn't find any documentation about whether importing private protocols from different modules is generally acceptable, but I found an existing instance of this being done in [`tarfile`](https://github.com/python/typeshed/blob/352cfc9773193ac7b3bfc28a190d36ec12be42fa/stdlib/tarfile.pyi#L7), so I'm hoping this pattern is fine here as well.
> Reuse `hashlib._Hash` in `hmac`

- stdlib/pickle.pyi
Similar default arguments were filled-in to other parts of pickle in #9501. For whatever reason, `pickle.Pickler.__init__` and `pickle.Unpickler.__init__` aren't picked up by stubdefaulter.
For reference:
```python
>>> import inspect, pickle
>>> inspect.signature(pickle.Pickler)
<Signature (file, protocol=None, fix_imports=True, buffer_callback=None)>
>>> inspect.signature(pickle.Unpickler)
<Signature (file, *, fix_imports=True, encoding='ASCII', errors='strict', buffers=())>
```
> Set literal default arguments for `pickle.Pickler.__init__` and `pickle.Unpickler.__init__`

- stdlib/mmap.pyi
no need to inherit from the protocol-like Iterable and Sized
> remove unneeded fake base classes from mmap.mmap

- stdlib/collections/__init__.pyi
Reversible is protocol-like, plus it subclasses dict which is itself Reversible on all supported python versions now.
> clean inheritance for OrderedDict related classes

- stdlib/csv.pyi
- stdlib/fileinput.pyi
- stdlib/multiprocessing/pool.pyi
I'm at about 90% confidence on this one, so I'm looking forward to the mypy-primer results for validation.
> Remove redundant inheritances from `Iterator`

- tests/REGRESSION.md
I re-read this documentation today after I sent somebody a link to it. Some of its wording could do with a refresh now that it's no longer in the same directory as the stdlib test cases.
> Touchups to `tests/REGRESSION.md`

- stdlib/_csv.pyi
- stdlib/csv.pyi
It does a weird wrapping thing instead:
https://github.com/python/cpython/blob/2a5cdb251674ce8d9a824c102f7cd846d944cfa4/Lib/csv.py#L114
> csv.Dialect doesn't actually subclass _csv.Dialect

- lib/ts_utils/metadata.py
- lib/ts_utils/paths.py
- lib/ts_utils/utils.py
- requirements-tests.txt
- scripts/stubsabot.py
- tests/check_typeshed_structure.py
- tests/mypy_test.py
- tests/regr_test.py
- tests/runtests.py
- tests/stubtest_stdlib.py
- tests/stubtest_third_party.py
Use relative paths, which allows running scripts in any working directory.
> Bundle path handling in ts_utils.paths

- .github/workflows/daily.yml
- .github/workflows/stubtest_third_party.yml
This fixes a problem with gdb changing between the Ubuntu versions.
> [CI] Pin Ubuntu in third party stubtest

- stdlib/zipimport.pyi
This has been [deprecated since 3.10](https://docs.python.org/3/library/zipimport.html#zipimport.zipimporter.load_module), and I'm quite sure that it's been causing problems for the `exec_module` migration. See my comment [here](https://github.com/python/cpython/issues/125746#issuecomment-2425030377).
> Add deprecation annotation for `zipimport.zipimporter.load_module`

- stubs/icalendar/METADATA.toml
icalendar 6.0.1 had some API changes, so it's an ideal candidate to check whether this works.
> Use compatible version marker for icalendar

- stubs/WTForms/METADATA.toml
- stubs/WTForms/wtforms/__init__.pyi
- stubs/WTForms/wtforms/fields/__init__.pyi
If we wanted to be extra nice we could manually run stub_uploader once before merging or wait until tomorrow to merge this, so we have correct stubs for both 3.2.0 and 3.2.1+.
I don't really think it matters though considering how close together these releases were.
> Bump WTForms to ~= 3.2.1

- stdlib/typing.pyi
This matches the order at runtime.
> swap inheritance order for Sequence

- stdlib/typing.pyi
Turns out #12851 wasn't the last one for Iterator; I found one more. I won't be too surprised if mypy-primer turns up problems with this one.
> remove redundant inheritance from Iterator for typing.IO

- stubs/WTForms/@tests/test_cases/check_form.py
- stubs/WTForms/wtforms/form.pyi
This fixes https://github.com/pallets-eco/wtforms/issues/848
> WTForms: Fix incorrect `Form` constructor return type for pyright

- stdlib/_io.pyi
does not inherit from TextIOWrapper at runtime.
As in https://github.com/python/typeshed/pull/12883 , I expect that missing TextIO as a base will cause trouble but this first commit is missing it just to double check.
> correct inheritance for io.StringIO

- stdlib/@tests/stubtest_allowlists/common.txt
- stdlib/contextlib.pyi
Actually putting methods on it may be currently infeasible, but I don't see why it shouldn't exist at all.
> add contextlib._GeneratorContextManagerBase

- stdlib/VERSIONS
- stdlib/_blake2.pyi
- stdlib/hashlib.pyi
This MR moves hashlib.blake2b and hashlib.blake2s into _blake2 where they live at runtime, makes their inheritance accurate, and fills in all the default values, which are notably the primary difference between the blake2b and blake2s classes.
Let's see if losing the inheritance from hashlib._Hash causes any issues.
> fix up blake2b/blake2s classes

- stdlib/email/policy.pyi
The parameter `verify_generated_headers` was added to `_PolicyBase.__init__` in #12638, but it wasn't copied to `EmailPolicy.__init__`. This causes the following to fail to type check in mypy despite being valid at runtime:
```python
import email.policy
email.policy.EmailPolicy(verify_generated_headers=False)  # E: Unexpected keyword argument "verify_generated_headers" for "EmailPolicy"
```
> Add missing parameter to `email.policy.EmailPolicy.__init__`

- stubs/setuptools/distutils/__init__.pyi
- stubs/setuptools/distutils/command/install_data.pyi
- stubs/setuptools/setuptools/_distutils/__init__.pyi
- stubs/setuptools/setuptools/_distutils/command/install_data.pyi
Similarly to https://github.com/python/typeshed/pull/12887 Should fix an import/Any subclassing issue in pywin32 that is inconsistent before/after Python 3.12
https://github.com/mhammond/pywin32/actions/runs/11487030970/job/31970658450?pr=2418#step:5:13
Autogenerated by stubgen then fixed manually.
> Add `install_data` in `distutils-stubs` from `setuptools`

- stdlib/distutils/_msvccompiler.pyi
- stubs/setuptools/distutils/_msvccompiler.pyi
- stubs/setuptools/setuptools/_distutils/_msvccompiler.pyi
This is used by pywin32: https://github.com/mhammond/pywin32/blob/5a46a21be0fdf9472f1904c54bd301745cfc482d/setup.py#L48
There doesn't seem to be a good replacement yet and its still actively being used. Here's some other references:
- https://github.com/pypa/setuptools/issues/2806#issuecomment-2415319446
- https://github.com/pypa/setuptools/issues/3933#issuecomment-1563100268
- https://github.com/pypa/setuptools/issues/3329#issuecomment-1201663383
> setuptools & distutils: Add more recent MSVCCompiler from _msvccompiler

- stubs/WTForms/wtforms/fields/form.pyi
- stubs/WTForms/wtforms/fields/list.pyi
- stubs/WTForms/wtforms/form.pyi
This was changed as part of the upgrade to 3.2.0, I also fixed a couple of related issues I missed.
> WTForms: Form errors no longer use `None` as a special key

- stdlib/asyncio/tasks.pyi
In Python 3.13, `as_completed` returns an object which is both an `Iterator` and an `AsyncIterator`.
> Change return type of `as_completed` in Python 3.13

- stdlib/builtins.pyi
```
>>> try:
...  raise TimeoutError
... except OSError as e:
...  print(e.errno)
... 
None
```
Code in cpython seems to always throw TimeoutError with no arguments.
> OSError.errno can be None

- lib/ts_utils/metadata.py
- scripts/stubsabot.py
- scripts/sync_protobuf/_utils.py
- scripts/sync_protobuf/google_protobuf.py
- scripts/sync_protobuf/s2clientprotocol.py
- scripts/sync_protobuf/tensorflow.py
- stubs/protobuf/METADATA.toml
- stubs/s2clientprotocol/METADATA.toml
- stubs/tensorflow/METADATA.toml
Thanks to @srittau 's work, these scripts can re-use more shared code.
- Simplified `download_file` error handling (400+ return codes already raised errors!)
- Moved `update_metadata` from `scripts/sync_protobuf/_utils.py` to `lib/ts_utils/metadata.py`
- Improved `update_metadata` to support any key (values unvalidated atm) and return the modified dictionary
- Updated `scripts/stubsabot.py` to use `update_metadata`
- Updated `scripts/sync_protobuf/*` to use  `lib/ts_utils`
- Updated `scripts/sync_protobuf/tensorflow.py` and `scripts/sync_protobuf/google_protobuf.py` to use the version directly from the `METADATA.toml` file
> Use `lib/ts_utils` for `scripts/sync_protobuf`

- stubs/pywin32/win32com/__init__.pyi
Some information about what this is:
A dynamic package that contains the generated com modules.
stubtest couldn't autodiscover it because it lives in temp directories and is dynamically added to path. (there's an open PR to have it generated in site-packages instead: https://github.com/mhammond/pywin32/pull/1675)
> Add `win32com.gen_py`

- stdlib/types.pyi
This would be helpful for red-knot, the work-in-progress type checker we're building at Astral.
To figure out which symbols are available in all modules as ["implicit globals"](https://docs.python.org/3/reference/datamodel.html#modules), red-knot [iterates through the symbols declared in typeshed's stub for `types.ModuleType`](https://github.com/astral-sh/ruff/blob/d2c9f5e43c12fdb8741af535dbf3acb5150ca09c/crates/red_knot_python_semantic/src/types.rs#L91-L124). Currently the only implicit global that is not declared in the stub for `types.ModuleType` is `__doc__`[^1]; this PR adds it to the stub. 
While adding `ModuleType.__doc__` is somewhat "redundant" from a purist view of the stubs (since it's the same type as `object.__doc__`, and `ModuleType` inherits from `object`), it's still …
> Add `types.ModuleType.__doc__`

- stdlib/zipimport.pyi
While poking around I was reminded of the approach I used in https://github.com/python/typeshed/pull/11127 to handle inheritance that is different depending on the version.
What do people think overall of this versus having two copies of the class in an if/else? This probably gives us a minimum of duplication, and the only downside is redundant inheritances from object. I suppose it's also less clear when reading the stub that the inheritance is conditional, since the condition switch can be in a different part of the file than then actual usage. Using a one-off local name could help with that, `import _LoaderBasics as _LoaderBasics_if_min_310` or something, but that's probably overkill for most situations.
> inheritance for zipimporter

- stdlib/_ssl.pyi
Fixes #12931
For reference ([docs](https://docs.python.org/3/library/ssl.html#ssl.SSLContext.set_psk_server_callback)): 
> The parameter callback is a callable object with the signature: `def callback(identity: str | None) -> bytes`.
> Fix callback parameter type in `ssl.SSLContext.set_psk_server_callback`

- stubs/google-cloud-ndb/google/cloud/ndb/model.pyi
The docstring indicates that these are supposed to be instances of the class, not type objects.
https://github.com/googleapis/python-ndb/blob/main/google/cloud/ndb/model.py#L6333
Also fix a case where the docstring says Sequence but the type stub says list
https://github.com/googleapis/python-ndb/blob/main/google/cloud/ndb/model.py#L6578
Closes https://github.com/python/typeshed/issues/12460
> Fix type annotations for google-cloud-ndb

- stdlib/tarfile.pyi
It only seems to need something it can read bytes from, rather than a full-fledged `IO[bytes]`.
> Loosen type of fileobj argument to TarFile.addfile

- stdlib/distutils/ccompiler.pyi
- stubs/setuptools/@tests/test_cases/check_distutils.py
- stubs/setuptools/@tests/test_cases/check_extension.py
- stubs/setuptools/setuptools/_distutils/ccompiler.pyi
- stubs/setuptools/setuptools/_distutils/extension.pyi
- stubs/setuptools/setuptools/extension.pyi
This PR is coming via https://github.com/python/mypy/issues/18107#issuecomment-2459028882 post #12928. I think this should maintain compatibility since Sequence is covariant. In particular, the type annotation of the `sources` parameter in `setuptools.Extension.__init__` has been from `list[StrPath]` to ~~`Sequence[StrPath]`~~ `list[str] | list[StrPath]`. `setuptools.Extension` shouldn't need a mutable sequence.
I also added a few test cases, but this is one of my first pull requests to `typeshed` and towards a typing-related project in general (plus I'm not well-versed with type theory) and I'm unsure if these changes are correct – please feel free to guide me towards making these changes in the correct manner, push changes to my branch directly, or close the PR in case it ends up not …
> Improve path-related type hints for `setuptools.Extension()` and `distutils.CCompiler()`

- stubs/docopt/METADATA.toml
> Mark docopt as obsolete in favor of docopt-ng

- stdlib/builtins.pyi
Refs #9864, follows from #12910
Like `OSError.errno`, `strerror` can sometimes be `None`. Usually, both attributes are `None` at the same time.
Since we added `None` to `errno`, it probably makes sense to do the same for `strerror`.
> Mark `OSError.strerror` as sometimes None

- stdlib/logging/config.pyi
Internally, `defaults` gets passed to `configparser.ConfigParser` ([here](https://github.com/python/cpython/blob/85036c8d612007356d2118eb25b460505078b023/Lib/logging/config.py#L74)), which accepts any `Mapping` (not just `dict`).
> Update `logging.config.fileConfig` to accept any `Mapping` for defaults

- stdlib/VERSIONS
- stdlib/_lzma.pyi
- stdlib/lzma.pyi
```
>>> import lzma
>>> lzma.LZMADecompressor
<class '_lzma.LZMADecompressor'>
>>> lzma.LZMACompressor
<class '_lzma.LZMACompressor'>
>>> lzma.LZMAError
<class '_lzma.LZMAError'>
```
No changes, just a move.
> LZMADecompressor, LZMACompressor, and LZMAError live in _lzma

- stdlib/builtins.pyi
Currently, this is intentionally incorrectly typed in order to produce a better mypy error message. But pyright (and presumably other type checkers) end up just treating instances of _NotImplementedType as callable.
I'm happy to drop this if it's particularly important that mypy generate a good error message here, but IMO it would be better to change this so that other type checkers can understand that instances of _NotImplementedType aren't callable, at the cost of making the error message a little worse.
> Type __call__ on builtins._NotImplementedType as None.

- stubs/pysftp/pysftp/__init__.pyi
According to inline documentation in [pysftp](https://github.com/ryhsiao/pysftp/blob/master/pysftp.py#L137-L144), CnOpts.log is either a bool or string and only meaningful custom values are strings, which are treated as file paths.
Same goes for the constructor parameter `log` on [Connection](https://github.com/ryhsiao/pysftp/blob/master/pysftp.py#L137-L144). Corrected the type here, but it is scheduled for removal in a future version.
> [pysftp-types] Logging attribute can be bool or str

- stdlib/@tests/stubtest_allowlists/common.txt
- stdlib/typing.pyi
- stdlib/typing_extensions.pyi
This is the subset of typing module internal base class inheritance that's stable over all supported versions of python.
This probably isn't worth doing either. But [like the maximalist version of this MR](https://github.com/python/typeshed/pull/13011), I wanted to work out what it would look like, and once I did that I feel like it makes sense to push it up to generate a record of that and let other people see it too. 
I know I've pushed up a bunch of MRs lately which are really scraping the bottom of the barrel, metaphorically speaking, in the name of accurate inheritance. So if it's not too weird, I wanted to say that I hope that it's not too much of a pain for the maintainers here for me to do that. I appreciate the work that you all do and I don't want to be making it harder for you.
> add typing._Final

- stdlib/contextlib.pyi
- stdlib/os/__init__.pyi
- stdlib/typing_extensions.pyi
Related to:
https://github.com/python/cpython/pull/126706
https://github.com/python/typeshed/pull/11269
Switching PathLike from abc.ABC to abc.ABCMeta wasn't accepted (reasonably so), so I'm wondering what happens to mypy-primer if we do this.
> The four protocol-like ABCs outside of collections.abc inherit from ABC directly

- stdlib/_codecs.pyi
Related to https://github.com/python/typeshed/issues/13016
The runtime name doesn't have the underscore prefix, and I believe it isn't necessary if type_check_only is used, so I updated that as well.
> mark _codecs.EncodingMap as final

- stdlib/_curses.pyi
- stdlib/curses/__init__.pyi
related to https://github.com/python/typeshed/issues/13016
To get access to the type:
```python
import curses
type(curses.ncurses_version)
```
> `curses._ncurses_version` updates

- stdlib/datetime.pyi
Related to https://github.com/python/typeshed/issues/13016
A weird case of named tuple (general category) that isn't NamedTuple or structseq, just a custom implementation of that pattern.
> Improve `datetime._IsoCalendarDate`

- stdlib/sys/__init__.pyi
Related to https://github.com/python/typeshed/issues/13016
Access to the various types:
```python
_flags = type(sys.flags),
_float_info = type(sys.float_info),
_hash_info = type(sys.hash_info),
_implementation = type(sys.implementation),
_int_info = type(sys.int_info),
_thread_info = type(sys.thread_info),
_version_info = type(sys.version_info),
_asyncgen_hooks = type(sys.get_asyncgen_hooks()),
```
> improvements for hidden types in the sys module

- tests/check_typeshed_structure.py
In https://github.com/python/typeshed/pull/13036 I got really confused as to what the error was trying to tell me, since I didn't add any file that didn't exist in distutils. I had to start digging in the test's code to see that it was checking a different folder than I expected.
Before:
After:
(unrelated but 3.13 errors are indeed looking nice)
> `check_distutils` test: Make the file path of missing setuptools distutils files more obvious

- stdlib/@tests/stubtest_allowlists/linux.txt
- stdlib/_socket.pyi
- stdlib/socket.pyi
I didn't realize there were so many errors being hidden for linux in here when I started. I only have access to MacOS and FreeBSD locally, so I just took the linux pipeline results at mostly face value. In working through all the things that don't exist in the Linux pipeline, I tested against my BSD machine to sort out what was for example, `platform = "win32"` versus `platform != "darwin" and platform != "linux"` or `platform = "darwin" versus "platform != "win32" and platform != "linux"`, etc.
When it didn't seem like any system that had a thing, I commented it out in `_socket` and removed it from `socket`. I expect many of these exist on some linux system somewhere - there's a lot of variance in that space. It seemed like leaving them as a comment in _socket was a good placeholder for …
> add socket.__all__

- stdlib/@tests/stubtest_allowlists/darwin.txt
- stdlib/@tests/stubtest_allowlists/linux.txt
- stdlib/_posixsubprocess.pyi
removed from CPython in 2013...
https://github.com/python/cpython/commit/daf455554bc21b6b5df0a016ab5fa639d36cc595
> remove _posixsubprocess.cloexec_pipe

- stdlib/@tests/stubtest_allowlists/py310.txt
`asyncio.base_events.BaseEventLoop.subprocess_exec` is in both common.txt and py310.txt for some reason
> remove duplicate allowlist entry

- requirements-tests.txt
Fixes #13094. `grpc` and `libcst` have both released versions that claim to support Python 3.13 now (though I haven't actually tried to install them locally)
> Remove unnecessary environment markers

- stdlib/@tests/stubtest_allowlists/common.txt
Fixes stubtest failures on main. I assume there was a merge race or something between two PRs that meant that the entry is now unused? Not sure.
> Remove unused allowlist entry

- stdlib/_typeshed/__init__.pyi
- stdlib/pstats.pyi
- stdlib/tkinter/__init__.pyi
This was a perfectly reasonable way to handle StrEnum. That said, there's only two uses of it, and this is just about the only thing currently in the stdlib that benefits from the complicated MRO-with-skips comparison in the original version of @hauntsaninja's inheritance checker from https://github.com/python/typeshed/issues/3968. As I get ready to propose a version of that check for inclusion in stubtest, it'd be nice to drop that part.
> Avoid using `_typeshed.StrEnum`

- stdlib/tkinter/__init__.pyi
> Fix tkinter ImageSpec #11721

- stdlib/@tests/stubtest_allowlists/darwin.txt
- stdlib/@tests/stubtest_allowlists/linux.txt
- stdlib/@tests/stubtest_allowlists/win32.txt
- stdlib/encodings/mbcs.pyi
- stdlib/encodings/oem.pyi
Two windows-only submodules. The stubs differ only by the functions imported from codecs.
> Add encodings.mbcs and encodings.oem

- stdlib/@tests/stubtest_allowlists/common.txt
- stdlib/encodings/utf_16.pyi
- stdlib/encodings/utf_32.pyi
These are similar to the stubs in https://github.com/python/typeshed/pull/13112, but because they're switching endian, they don't just assign the C function to themselves and call it a day.
> add encodings.utf_16 and encodings.utf_32

- stubs/docutils/docutils/core.pyi
- stubs/docutils/docutils/writers/__init__.pyi
I generated `docutils.core` using stubgen, then I typed `docutils.core.publish_parts`'s return type, which meant also typing `docutils.writers.Writer.parts`.
This solves the docutils part of https://github.com/python/typeshed/issues/12595 (which comes from https://github.com/jaraco/pytest-checkdocs/pull/25/files#diff-17010ff849cd4c7437eae02512d0dc1a0646299e07a65bb7882a487323ead6d2R86-R88)
> Generate `docutils.core` and type `publish_parts`'s return type

- stdlib/@tests/stubtest_allowlists/common.txt
- stdlib/@tests/stubtest_allowlists/darwin.txt
- stdlib/@tests/stubtest_allowlists/linux-py312.txt
- stdlib/@tests/stubtest_allowlists/linux-py313.txt
- stdlib/@tests/stubtest_allowlists/linux.txt
- stdlib/os/__init__.pyi
- stdlib/posix.pyi
Pushing this up with just clearing the allowlist first, so I can see what the pipelines say.
> Cleaning up os/posix module constants

- stdlib/turtle.pyi
All is taken from the docstring of the pen function: https://github.com/python/cpython/blob/d5a08f0ecb31dddd5c2c5d8f4121f22d95913434/Lib/turtle.py#L2351
> Use a `TypedDict` for `turtle._PenState`

- stubs/protobuf/google/protobuf/runtime_version.pyi
Closes https://github.com/python/typeshed/issues/13045
Source code says 
> It should only be accessed by Protobuf gencodes and tests. DO NOT USE it elsewhere.
But some users are using it presumably to avoid parsing `google.protobuf.__version__`. This module is not using the `_` prefix and is pretty simple. May as well add it now that it's been requested.
> Add `google.protobuf.runtime_version`

- stdlib/@tests/stubtest_allowlists/darwin-py310.txt
- stdlib/@tests/stubtest_allowlists/darwin-py311.txt
- stdlib/@tests/stubtest_allowlists/darwin-py312.txt
- stdlib/@tests/stubtest_allowlists/darwin-py313.txt
- stdlib/@tests/stubtest_allowlists/darwin-py38.txt
- stdlib/@tests/stubtest_allowlists/darwin-py39.txt
- stdlib/@tests/stubtest_allowlists/linux-py310.txt
- stdlib/@tests/stubtest_allowlists/linux-py311.txt
- stdlib/@tests/stubtest_allowlists/linux-py312.txt
- stdlib/@tests/stubtest_allowlists/linux-py313.txt
- stdlib/@tests/stubtest_allowlists/linux-py38.txt
- stdlib/@tests/stubtest_allowlists/linux-py39.txt
- stdlib/@tests/stubtest_allowlists/py310.txt
- stdlib/@tests/stubtest_allowlists/py311.txt
- stdlib/@tests/stubtest_allowlists/py312.txt
- stdlib/@tests/stubtest_allowlists/py313.txt
- stdlib/@tests/stubtest_allowlists/py38.txt
- stdlib/@tests/stubtest_allowlists/py39.txt
- stdlib/@tests/stubtest_allowlists/win32-py310.txt
- stdlib/@tests/stubtest_allowlists/win32-py311.txt
- stdlib/@tests/stubtest_allowlists/win32-py312.txt
- stdlib/@tests/stubtest_allowlists/win32-py313.txt
- stdlib/@tests/stubtest_allowlists/win32-py38.txt
- stdlib/@tests/stubtest_allowlists/win32-py39.txt
This makes it easier to ensure that categorization and comments are in sync between one allowlist and another.
With the help of a quick script, I sorted the version-specific allowlists and made sure that comments and fix/don't fix is consistent between the files. Each labeled section is identical to others with the same name, and this should also make consolidating when dropping an old version easier.
On the negative side, this is unfortunately sure to cause a lot of merge conflicts. What do people think? Worth it or not worth it?
There should be no significant differences in overall content in this MR. I did consolidate some comments to an inline version, and there was one entry which had been commented out in all the files where it appeared:
```
```
I'm not sure why it was commented out …
> sort allowlists by version more consistently

- stdlib/@tests/stubtest_allowlists/common.txt
- stdlib/@tests/stubtest_allowlists/darwin-py310.txt
- stdlib/@tests/stubtest_allowlists/darwin-py38.txt
- stdlib/@tests/stubtest_allowlists/darwin-py39.txt
- stdlib/@tests/stubtest_allowlists/linux-py38.txt
- stdlib/@tests/stubtest_allowlists/win32-py310.txt
- stdlib/@tests/stubtest_allowlists/win32-py38.txt
- stdlib/@tests/stubtest_allowlists/win32-py39.txt
The current matrix of python versions is:
```
linux	3.8.18	3.9.20	3.10.15	3.11.10	3.12.7	3.13.0
win32	3.8.10	3.9.13	3.10.11	3.11.9	3.12.7	3.13.0
darwin	3.8.10	3.9.13	3.10.11	3.11.9	3.12.7	3.13.0
```
> sort security backport allowlist entries

- stdlib/@tests/stubtest_allowlists/common.txt
- stdlib/socket.pyi
I suspect this was never added just because it didn't get collapsed into the `socket.[A-Z0-9_]+` regex. Let's see what the gitlab runners say.
> add socket.AF_DECnet value

- stdlib/@tests/stubtest_allowlists/darwin.txt
- stdlib/select.pyi
`KQ_FILTER_NETDEV` is documented as not being available on MacOS.
`POLLMSG` is by observation available on linux but not MacOS or FreeBSD.
> fixes to select module constants

- stdlib/@tests/stubtest_allowlists/common.txt
- stdlib/sys/__init__.pyi
Valid since 3.7. Includes notes on availability for all the sometimes-available sys attributes
> sys.tracebacklimit can be set to `None`

- stdlib/tarfile.pyi
Fixes https://github.com/python/typeshed/issues/12182
@srittau please take a look.
PS.
Why do you have an overload for `name: StrOrBytesPath | None = None` and `name: StrOrBytesPath | None` ?
> Fix todo in tarfile for modes with pipe char

- stdlib/typing.pyi
Per [PEP 563](https://peps.python.org/pep-0563/#runtime-annotation-resolution-and-type-checking), `typing.TYPE_CHECKING` is intended to be a constant. It seems sensible to annotate it as such.
(Apparently some projects do modify it (e.g. sphinx autodoc [temporarily sets it to `True`](https://github.com/sphinx-doc/sphinx/blob/df3d94ffdad09cc2592caccd179004e31aa63227/sphinx/ext/autodoc/importer.py#L182) to help with import analysis), but that sort of use case seems dubious/exceptional enough to warrant a `# type: ignore`.)
> Mark `typing.TYPE_CHECKING` as `Final`

- stdlib/@tests/stubtest_allowlists/common.txt
- stdlib/@tests/stubtest_allowlists/darwin.txt
- stdlib/@tests/stubtest_allowlists/linux.txt
- stdlib/@tests/stubtest_allowlists/win32-py38.txt
- stdlib/@tests/stubtest_allowlists/win32-py39.txt
- stdlib/@tests/stubtest_allowlists/win32.txt
`curses.has_key` is on all three platforms, so it could be moved to common.txt, but the reason it errors is different on windows and non-windows, so I decided to keep it in the platform files. After that I sorted the (non-versioned) platform allowlists.
> sort platform allowlists

- stdlib/gzip.pyi
* Return concrete io.TextIOWrapper instead of typing.TextIO.
* Allow file objects when opening in text mode. Closes: #13175
> Improve gzip.open() annotations

- stdlib/ctypes/__init__.pyi
Surfaced by https://github.com/python/mypy/pull/18251
Also expand the union for `ctypes.c_time_t` so the actual runtime class is included, whatever that ends up being. I'm not sure if the full range of c_short through c_longlong is needed; is there a machine out there where a short is 32-bits wide? I don't know enough to say.
> `ctypes.CDLL._func_restype_` is a type, not an instance

- stdlib/traceback.pyi
This matches the docstring for TracebackException:
https://github.com/python/cpython/blob/8b3cccf3f9508572d85b0044519f2bd5715dacad/Lib/traceback.py#L1007-L1008
> Add missing exceptions field to TracebackException

- stubs/protobuf/METADATA.toml
- stubs/protobuf/google/protobuf/api_pb2.pyi
- stubs/protobuf/google/protobuf/descriptor_pb2.pyi
Closes #13142
Contains docstring changes only (reran `scripts/sync_protobuf/google_protobuf.py`)
> Bump protobuf to ~=5.29.1

- .github/workflows/daily.yml
- .github/workflows/stubsabot.yml
Same idea as https://github.com/python/typing_extensions/pull/516
> Change issue text on daily/stubsabot failure to include exact run URL

- stubs/jsonschema/METADATA.toml
The pin was due to a bug in jsonschema which was fixed https://github.com/python-jsonschema/jsonschema/issues/1268
> Unpin webcolors in jsonschema

- stdlib/@tests/stubtest_allowlists/common.txt
I don't think we need a regex for just two items
> adjust allowlist for `urllib.response.addbase`

- .github/workflows/daily.yml
- .github/workflows/stubtest_stdlib.yml
- stdlib/@tests/stubtest_allowlists/linux-py312.txt
- stdlib/@tests/stubtest_allowlists/linux-py313.txt
- stdlib/os/__init__.pyi
A new failure that showed up in the github runners for https://github.com/python/typeshed/pull/13220
Looks like maybe the version of Ubuntu that the runners use got bumped? The comment in `os/__init__.pyi` says it's Linux 5.6+.
> add CLONE_NEWTIME to os.__all__

- stdlib/@tests/stubtest_allowlists/common.txt
Checks out: https://github.com/python/cpython/blob/ed037d229f64db90aea00f397e9ce1b2f4a22d3f/Lib/configparser.py#L1285
> move configparser.SectionProxy allowlist to don't fix section

- stdlib/@tests/stubtest_allowlists/common.txt
Both of these are functions with attributes added to them. We use a class to approximate that, and I don't see this changing unless new typing features become available or stubtest is changed to accept non-functions for things that are functions at runtime.
> move two more allowlist entries to can't fix

- stdlib/inspect.pyi
latest mypy seems to accept it.
> Fix todo in inspect

- stdlib/tkinter/font.pyi
Fixes #13226
It seems any number of trailing options is accepted:
```python
import tkinter as tk
l = tk.Label()
l.pack()
l.configure(  # renders OK
text="foo",
font=("arial", 12, "normal", "italic", "underline", "overstrike", "roman", "italic", "normal", "bold"),
width=10,
)
>>> l.cget("font")
'arial 12 normal italic underline overstrike roman italic normal bold'
```
> Allow any number of trailing font options in tkinter font description

- stubs/tqdm/tqdm/asyncio.pyi
Fixes https://github.com/python/typeshed/issues/13227
> Fix tqdm.asyncio type inconsistency

- stdlib/traceback.pyi
These are derived from the TracebackException docs: https://docs.python.org/3/library/traceback.html#traceback.TracebackException
and the source code:
https://github.com/python/cpython/blob/8b3cccf3f9508572d85b0044519f2bd5715dacad/Lib/traceback.py#L989
> Add new fields to TracebackException, fix cause/context/lineno types

- stdlib/@tests/stubtest_allowlists/common.txt
Both cases where runtime sets it to None but we ignore that in typeshed because it's unhelpful.
> move numbers.Number.__hash__ and tarfile.TarFile.errors to don't fix

- stdlib/@tests/stubtest_allowlists/common.txt
- stdlib/ctypes/__init__.pyi
These two are instances of a class created by CFUNCTYPE, not functions. Also moves `ctypes.CDLL._FuncPtr` to "don't fix". There's no reason to capture it as "None" unless we get a way to distinguish that it's None on the class but not an instance of the class.
> fixing up ctypes.memmove and ctypes.memset

- stubs/Flask-SocketIO/flask_socketio/__init__.pyi
closes https://github.com/python/typeshed/pull/13268
The new member is a type alias for something in python-socketio (untyped) by the same author, so I don't think I can add an annotation for it.
That class's constructor has a TODO for typing the kwargs, so I added types for those. There's two groups of configs so I defined two separate typed dicts.
SocketIO options
https://github.com/miguelgrinberg/Flask-SocketIO/blob/main/src/flask_socketio/__init__.py#L82
EngineIO options
https://github.com/miguelgrinberg/Flask-SocketIO/blob/main/src/flask_socketio/__init__.py#L114
> Flask-socketio 5.5 + add type of kwargs

- stdlib/codecs.pyi
That these were missing from the stubs was being silenced by this part of the common allowlist:
```
codecs.StreamReaderWriter.\w+
codecs.StreamRecoder.\w+
```
But these weren't part of the group of errors being described, which are errors about things being in the stubs that don't appear to exist at runtime.
> add codecs.StreamRecoder attributes

- lib/ts_utils/metadata.py
- lib/ts_utils/utils.py
Reverts python/typeshed#13287
They're not unnecessary; the relevant pyright checks are now failing on main (e.g. https://github.com/python/typeshed/actions/runs/12476935411/job/34822431014). See https://github.com/python/typeshed/pull/13287#issuecomment-2561492850.
I haven't yet investigated why the relevant CI jobs didn't run on that PR before it was merged
> Revert "Remove unnecessary pyright supressions"

- .github/workflows/daily.yml
- .github/workflows/tests.yml
I don't think we can use it to replace `actions/setup-python` yet because of https://github.com/astral-sh/uv/issues/8666 (unless we configure a dummy project name+version in pyproject.toml)
> Use `astral-sh/setup-uv` to install uv in CI

- pyproject.toml
- stdlib/typing_extensions.pyi
This enables more autofixes that have been added to Ruff in the last few versions.
> Enable more PYI autofixes

- pyproject.toml
https://docs.astral.sh/ruff/rules/#flake8-2020-ytt
typeshed already passes as-is.
I think this group of rules is overall nice to catch odd version checks that flake8-PYI might not. I don't think we'd accept any of the formats it catches, so it can be caught before even going to review.
> Enable Ruff YTT

- stdlib/typing.pyi
This is needed if we do https://discuss.python.org/t/protocol-classes-should-not-match-callable-proto/75475
> typing: broaden type_check_only TypeVar bound

- stdlib/_csv.pyi
> Add csv.Dialect to second arg of register_dialect()

- stdlib/@tests/stubtest_allowlists/py310.txt
- stdlib/@tests/stubtest_allowlists/py311.txt
- stdlib/@tests/stubtest_allowlists/py312.txt
- stdlib/@tests/stubtest_allowlists/py313.txt
- stdlib/@tests/stubtest_allowlists/py39.txt
- stdlib/ast.pyi
The comment on these was incorrect, but there were a lot of other AST classes where that was the case. Here, they switched from an `__init__` to a `__new__` when they were deprecated, in order to return an instance of their replacement.
> fix deprecated ast classes

- stdlib/unittest/runner.pyi
I have a MR for stubtest out at https://github.com/python/mypy/pull/18251. One of the things that got flagged was `unittest.runner.TextTestRunner.resultclass` and I was having a hard time figuring it out. I made a version of `unittest/runner.py` locally that had all of our existing stub annotations inline with the actual code, and ran mypy on that to try and figure it out. This is various fixes that were needed to make mypy satisfied with that version of the file.
- Updating `_ResultClassType` to use `TextTestResult[Any]`: This was the primary issue that got flagged in my MR for stubtest.
- `_WritelnDecorator` takes `_SupportsWriteAndFlush` as the argument. It *is* `_TextTestStream`, which adds `writeln` on top of that, but it doesn't need to be passed something that already has …
> fixes for `unittest.runner`

- stdlib/typing_extensions.pyi
I had MR up before that was similar to this one, and it wasn't accepted. I wanted to take another run at it,
because I don't think I justified it properly. The thing that this fixes is sorting out whether these classes
inherit from `typing.Protocol` or `typing_extenstions.Protocol`.
> Protocol inheritance for typing_extensions.SupportsX classes

- stubs/docker/docker/models/containers.pyi
Previously, `Container.exec_run` and `Container.get_archive` missed type hints on `cmd` and `path` arguments, respectively. 
Added type hints based on docstring.
> Fix missed type hints in docker containers.pyi

- lib/ts_utils/metadata.py
- pyproject.toml
Previous references: https://github.com/python/typeshed/pull/13090#issuecomment-2497712104 and https://github.com/python/typeshed/pull/13108
> Move RUF022+RUF023 ignores to stubs only and remove TODO

- stdlib/_curses.pyi
The source used to deduce  this: https://github.com/python/cpython/blob/aea2e03b276c79f8934d17056a68899e69763fae/Modules/_cursesmodule.c#L2158
> Use SupportsWrite in curses instead of IO Any

- stdlib/@tests/test_cases/ctypes/check_CDLL.py
- stdlib/ctypes/__init__.pyi
CDLL and descendants accept `Path` objects as `name` since 3.12
> stdlib: new signature for CDLL in 3.12

- stdlib/signal.pyi
Apart from regular rewrites of annotations from `GLOBAL: EnumClassName` to `GLOBAL: Literal[EnumClassName.MEMBER]`, you may notice a small different kind of change:
```diff
-    SIG_BLOCK = Sigmasks.SIG_BLOCK
-    SIG_UNBLOCK = Sigmasks.SIG_UNBLOCK
-    SIG_SETMASK = Sigmasks.SIG_SETMASK
+    SIG_BLOCK: Literal[Sigmasks.SIG_BLOCK]
+    SIG_UNBLOCK: Literal[Sigmasks.SIG_UNBLOCK]
+    SIG_SETMASK: Literal[Sigmasks.SIG_SETMASK]
```
The reason why I did is because this unifies the outcomes across pyright and mypy (`reveal_type(SIG_BLOCK)` for old `SIG_BLOCK` is `Sigmasks` according to mypy and `Literal[Sigmasks.SIG_BLOCK]` according to pyright) -- with the new version, both checkers see literal types.
> Make `signal` global enum constants annotated as literals

- stdlib/optparse.pyi
Also add comments for use of `Any`
Follow up to #13282
> optparse: Improve `Option` and `OptionContainer` types

- pyproject.toml
https://docs.astral.sh/ruff/rules/#tryceratops-try
Coding patterns around raising exceptions. We seem to already be respecting all of them except [raise-vanilla-args (TRY003)](https://docs.astral.sh/ruff/rules/raise-vanilla-args/#raise-vanilla-args-try003), but I think that rule is too vague. (relevant: https://github.com/astral-sh/ruff/issues/14398 )
> Enable Ruff TRY (tryceratops)

- .vscode/settings.default.json
Updated VSCode's recommended settings to stop it from removing the following lines on saving the file:
https://github.com/python/typeshed/blob/33d1b169c1780529e8c2b91858caf58852d73220/stdlib/typing.pyi#L5
https://github.com/python/typeshed/blob/33d1b169c1780529e8c2b91858caf58852d73220/tests/mypy_test.py#L42
This has been annoying me for a while and I finally figured out which setting is responsible for that.
> Update vscode recommended settings to not cleanup noqa'd unused imports

- .pre-commit-config.yaml
make renovatebot will be able to handle additional_dependencies in the future: https://github.com/renovatebot/renovate/pull/33417
https://github.com/python/typeshed/pull/12739
> Allow renovate to upgrade additional_dependencies in Python pre-commit hooks

- stdlib/sys/__init__.pyi
CPython defines `sys.platform` in [`Python/sysmodule.c`], which refers to [`Py_GetPlatform`], which in turn just returns a compile constant `PLATFORM` (defined in the build process).
The value for `sys.platform` is therefore built into the interpreter. It is a string that can not change, so conceptually, it seems to make sense to annotate it using `LiteralString`.
There are probably a lot more things in `sys` that could be annotated using `LiteralString` instead of `str` (`sys.version`, `sys.copyright`), but since `sys.platform` is used for [platform checks] that typecheckers are supposed to understand, it probably makes sense to start with this and make the type a bit more precise, even if there is no immediate benefit that I can think of.
[`Python/sysmodule.c`]: …
> Annotate `sys.platform` as `LiteralString`

- stdlib/telnetlib.pyi
`telnetlib.Telnet#expect` copies given sequence and may modify it. https://github.com/python/cpython/blob/2dc476bcb9142cd25d7e1d52392b73a3dcdf1756/Lib/telnetlib.py#L612-L617
So, when a read-only sequence contains `bytes` (e.g. `tuple` of `bytes`) is passed to `expect`, `TypeError` is raised at runtime.
This PR fixes the argument type of the `list` parameter of `Telnet#expect` to reject `Sequence` containing `bytes`.
I know telnetlib is already removed from stdlib in Python 3.13, but this fix may help users of 3.12 and future users of https://pypi.org/project/standard-telnetlib/ etc.
> fix Telnet#expect (stdlib/telnetlib.pyi)

- stdlib/@tests/stubtest_allowlists/win32.txt
- stdlib/ctypes/__init__.pyi
This is the same basic idea as https://github.com/python/typeshed/pull/13252 which did this for ctypes.mmove and ctypes.memset.
> fix ctypes.GetLastError

- README.md
- lib/ts_utils/metadata.py
- pyproject.toml
- stubs/icalendar/METADATA.toml
- stubs/pycocotools/METADATA.toml
- stubs/seaborn/METADATA.toml
This is part of gradually dropping support, cf. #12112
> Officially drop Python 3.8 support

- .github/workflows/meta_tests.yml
Currently it's not running on PRs that only touch the `lib/` directory, which is causing a fair amount of user confusion (https://github.com/python/typeshed/pull/13287, https://github.com/python/typeshed/pull/13393)
> Run the "typecheck our own code" workflow on PRs touching the `lib/` directory

- stdlib/tarfile.pyi
this is an alias for `"w:"` according to the code (which defaults the second segment to `"tar"`)
> add `"w:tar"` as a mode for tarfile

- stubs/requests-oauthlib/requests_oauthlib/oauth1_auth.pyi
it is passed along to oauthlib where the default there is None
> requests-oauthlib: decoding can be None

- stdlib/json/scanner.pyi
It's a module attribute that isn't currently defined.
> Add `json.scanner.NUMBER_RE`

- stdlib/json/encoder.pyi
As recommended in https://github.com/python/typeshed/pull/13405#discussion_r1921215703
> Mark attributes in `json.encoder` as undocumented

- stubs/psycopg2/psycopg2/_psycopg.pyi
> fix(psycopg2): fix copy_expert signature

- stubs/pywin32/win32/win32gui.pyi
> Have `win32gui.SystemParametersInfo` return `Any`

- stdlib/argparse.pyi
Some of these hacks are obsolete, some of them are due to wrong assumptions.
> Clean up argparse hacks

- stdlib/sre_constants.pyi
> Mark constants in sre_constants as final

- stdlib/re.pyi
pyright already considered them final because they are all upper cased but mypy didn't
> Mark top-level re flags as final

- tests/pytype_test.py
- tests/typecheck_typeshed.py
These two options will be on by default in `--strict` in `mypy@2.0`
> Add `--strict-bytes` and `--local-partial-types` to self check

- stdlib/shutil.pyi
Resolves https://github.com/python/typeshed/issues/13480
Allow explicitly passing `None` whilst still getting the deprecation warning.
> Still allow passing `None` to `shutil.rmtree`'s `onerror` parameter on Python 3.12+

- .github/workflows/tests.yml
- lib/ts_utils/requirements.py
- scripts/install_all_third_party_dependencies.py
- tests/README.md
- tests/get_external_stub_requirements.py
- tests/get_stubtest_system_requirements.py
I got tired of translating the bash script to powershell, so there you go.
As further steps it's probably possible to obsolete the `get_external_stub_requirements` and `get_stubtest_system_requirements` scripts entirely with a few modifications (like cli flags for "system vs local" install, "uv vs pip", and specifying third-party stubs to install from) to run such install scripts directly on the CI.
> Cross-platform third-party stubs requirements install script

- stdlib/asyncio/tasks.pyi
The prior typing here is too permissive, this is strictly checked against these two types at runtime. Attempting to pass a task or future, each of which are FutureLike to this API results in a runtime error.
> Fix type for `run_coroutine_threadsafe`

- stdlib/compileall.pyi
This has been true since Python 3.5 (https://github.com/python/cpython/commit/1e3c3e906c9f1fcc463cfb3641d078eec773666f).
```python
>>> compile_file("/home/ichard26/test.py")
True
>>> compile_file("/home/ichard26/process.py")
Compiling '/home/ichard26/process.py'...
***   File "/home/ichard26/process.py", line 28
for 
^
SyntaxError: invalid syntax
False
```
> Update compileall.compile_{dir, file, path} to return bool

- stubs/pyinstaller/PyInstaller/building/api.pyi
Fix typo in internal TypeAlias name at PyInstaller stubs.
> Fix typo at PyInstaller stubs

- CONTRIBUTING.md
The style guide was merged with https://typing.readthedocs.io/en/latest/guides/writing_stubs.html#style-guide in https://github.com/python/typeshed/pull/13332 so the anchor no longer exists.
> [ez] Update link to style guide

- stubs/pyinstaller/PyInstaller/building/build_main.pyi
Complete the incomplete types of Analysis class constructor params.
> PyInstaller: Complete types in build_main.pyi

- stdlib/functools.pyi
`assigned` and `updated` are only iterated over, so any `Iterable` yielding strings will do.
> Relax functools.update_wrapper's parameter types

- pyrightconfig.stricter.json
Following https://github.com/python/typeshed/commit/2d4d7be276b6c07dad0a16dbb33ef0ba0f3a53da, it appears that these stubs no longer have any unannotated parameters or return types 🎉
Fixes https://github.com/AlexWaygood/typeshed-stats/issues/321
> Use stricter pyright settings when testing `hnswlib` in CI

- stubs/vobject/vobject/vcard.pyi
The upstream source code has a docstring explicitly stating that these arguments can be strings or lists of strings:
https://github.com/py-vobject/vobject/blob/662db24688df1f6d8f12d68462a13975bd0d08de/vobject/vcard.py#L18 https://github.com/py-vobject/vobject/blob/662db24688df1f6d8f12d68462a13975bd0d08de/vobject/vcard.py#L58
> Fix constructor args for two vobject classes

- stubs/tqdm/tqdm/std.pyi
The stub for tqdm.wrapattr does not type the `stream` parameter and the generator is marked as `Incomplete`. This PR fixes both.
Example of error from Pylance that is fixed:
```
Type of "wrapattr" is partially unknown
Type of "wrapattr" is "(stream: Unknown, method: Literal['read', 'write'], total: float | None = None, bytes: bool = True, **tqdm_kwargs: Unknown) -> _GeneratorContextManager[Any]
```
```python
file_size = os.stat("source.txt").st_size
with open("source.txt", "rb") as source, open("dest.txt", "wb") as dest:
with tqdm.wrapattr(dest, "write", total=member.file_size, desc="Copying source.txt to dest.txt") as dest_tqdm:
shutil.copyfileobj(source, dest_tqdm)
with open("source.txt", "rb") as source, open("dest.txt", "wb") as dest:
with tqdm.wrapattr(source, "read", …
```
> tqdm: Improve wrapattr

- stdlib/_hashlib.pyi
- stdlib/hashlib.pyi
- stdlib/hmac.pyi
This protocol corresponds to what is called "hash object" in the hashlib documentation. In particular, it includes the non-OpenSSL BLAKE2 implementations which do not inherit HASH.
Supersedes https://github.com/python/typeshed/pull/13518
> Introduce the _HashObject protocol

- stubs/tqdm/tqdm/asyncio.pyi
Make the type of `tqdm.asyncio.tqdm.as_completed` more compatible with stdlib's `asyncio.as_completed`.
The container type is still `Iterator` (= `Generator[_, Any, None]`) because it seems `tqdm.as_completed` cannot be an async iterator, unlike `asyncio.as_completed` in Python>=3.13.
https://github.com/tqdm/tqdm/blob/v4.67.1/tqdm/asyncio.py#L67-L68
> fix yield type of `tqdm.as_completed`

- pyrightconfig.stricter.json
It's fully annotated.
Fixes https://github.com/AlexWaygood/typeshed-stats/issues/322
> Use stricter pyright settings on `dirhash` in CI

- stdlib/@tests/test_cases/check_configparser.py
- stdlib/configparser.pyi
> [configparser] Fix missing fallback argument in SectionProxy.get

- stubs/Deprecated/deprecated/classic.pyi
- stubs/Deprecated/deprecated/sphinx.pyi
In #13020 the stubs were upgrade for 1.2.15, but it missed the kwarg added to the classic.deprecated() and sphinx.deprecated() decorators.
> fix(Deprecated): fix missing extra_stacklevel kwarg for deprecated()

- .github/workflows/tests.yml
Closes #13484 As seen in that PR, some packages can't be installed at all on certain platforms / OSes.
We don't currently have a need to run this test on multiple different platforms, so it seems the TODO was more about future-proofing.
If we need to run this test on different platforms, we'd have to add a matrix for `runs-on`. Let's cross that bridge when we get there, if we get there.
https://github.com/python/typeshed/pull/13484#issuecomment-2684754413
> I think we should just remove the TODO comment.
> Remove uncompletable TODO in test.yml

- stdlib/shutil.pyi
As found on Python's Discord: https://discord.com/channels/267624335836053506/891788761371906108/1346539455267213372
Linux:
```py
>>> import shutil
>>> from pathlib import Path
>>> which(Path("bash"))
'/usr/bin/bash'
```
Python 3.10, Windows:
```py
>>> import shutil
>>> from pathlib import Path
>>> shutil.which(Path("python"))
File "C:\Users\Avasam\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 1492, in which
if any(cmd.lower().endswith(ext.lower()) for ext in pathext):
File "C:\Users\Avasam\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 1492, in <genexpr>
if any(cmd.lower().endswith(ext.lower()) for ext in pathext):
AttributeError: 'WindowsPath' object has no attribute 'lower'. Did you …
```
> `shutil.which` cannot return `PathLike`, and fails with `cmd: PathLike` on Windows Python < 3.12

- stubs/cffi/_cffi_backend.pyi
> gh-13477: Fix parameter type annotations in `_cffi_backend` stub.

- CONTRIBUTING.md
Even if we update all our scripts to depend on uv (given it's in our dev requirements), we can't assume it's already installed for the initial installation if we want to stay flexible. So that section is likely to stay even long-term. I added a mention of `uv` to show how simpler it is.
Renamed `Mac OS` --> `macOS`
I'm also experimenting with rendering that section as a table. Let me know if you like it or not. you can preview at: https://github.com/Avasam/typeshed/blob/mention-uv-in-the-initial-install/CONTRIBUTING.md
> Mention uv for the initial install in CONTRIBUTING.md

- stdlib/@tests/stubtest_allowlists/py310.txt
- stdlib/@tests/stubtest_allowlists/py311.txt
- stdlib/@tests/stubtest_allowlists/py312.txt
- stdlib/@tests/stubtest_allowlists/py313.txt
- stdlib/unittest/case.pyi
NumPy re-exports `unittest.TestCase` in several modules, which caused `stubtest` to complain about incorrect `__init_subclass__` signature (see e.g. https://github.com/numpy/numtype/pull/283/commits/d6af1ad343e47b22d711451db4041c6f86e491cb). 
I noticed that in the relevant typeshed allowlists there was a comment that said
> Runtime has *args, **kwargs, but will error if any are supplied
So I figured that `Never` could also fulfill be used to fulfill that role. That way we can have the cake and eat it too. 
Thoughts?
> annotate `unittest.TestCase.__init_subclass__`

- stubs/geopandas/geopandas/geodataframe.pyi
Issue - https://github.com/python/typeshed/issues/13603
This fixes mypy error in CI workflows.
> Fix override issue in GeoDataFrame.astype return type

- stdlib/distutils/cmd.pyi
- stdlib/distutils/dist.pyi
See https://github.com/pypa/setuptools/pull/4872/files#r1988322516
> distutils: Allow overriding Command and Distribution boolean attributes with actual bool in subclasses

- stdlib/types.pyi
> Fix return type for GenericAlias.__origin__ for type aliases parameterised with a type

- stdlib/@tests/stubtest_allowlists/win32-py310.txt
- stdlib/@tests/stubtest_allowlists/win32-py311.txt
- stdlib/@tests/stubtest_allowlists/win32-py312.txt
- stdlib/@tests/stubtest_allowlists/win32-py39.txt
- stdlib/pathlib.pyi
This basically is uses the same partytrick as #13602, but applied to `Never` itself, and leads to similar issues in the NumPy stubs, as well.
Attempting to use these methods on windows <3.12 will now be reported by mypy as a classic `misc`, instead of `attr-defined`, which IMO was a bit more confusing.
Pyright users won't even notice the difference &mdash; they'll still be confronted with very same `reportAttributeAccessIssue` and `reportUnknownMemberType` power chords.
> annotate `pathlib.Path.{owner,group,is_mount}` on windows

- tests/mypy_test.py
For a long while now I noticed that when the mypy test fails, `No [mypy] section in config file` is printed, but I never really paid attention to it. Turns our the temporary mypy config file was never actually being written to.
I also noticed an additional bug where the same config section would be repeated a lot.
I have an upcoming experimental PR that depends on the `[mypy-tests]` feature, so here you go with a bugfix and removing a bogus error line that affects current tests.
```
testing setuptools (104 files)... failure (exit code 1)
stubs\setuptools\setuptools\namespaces.pyi:10: error: Name "this_name_doesnt_exist" is not defined  [name-defined]
C:\Users\Avasam\AppData\Local\Temp\tmpe41876qa: No [mypy] section in config file
```
```
testing setuptools (104 files)... failure (exit …
```
> Fix mypy test temporary config file creation

- stubs/google-cloud-ndb/METADATA.toml
> [google-cloud-ndb] Remove unncessary stubtest requirements

- .github/workflows/daily.yml
- .github/workflows/stubtest_third_party.yml
Don't print progress when installing packages via apt-get. This prevent spurious output in CI logs.
> [CI] Quieten apt-get

- tests/stubtest_third_party.py
* This makes is easier to call `run_stubtest()` manually, for example when testing the script - no need to construct an `ArgumentParser` instance.
* This concentrates argument error handling in the `main()` function and prevents an unexpected process exit when calling `run_stubtest()`.
> Move error handling to main function

- .github/workflows/daily.yml
- .github/workflows/meta_tests.yml
- .github/workflows/stubsabot.yml
- .github/workflows/stubtest_stdlib.yml
- .github/workflows/stubtest_third_party.yml
- .github/workflows/tests.yml
When looking at GitHub's action runs, the individual jobs are listed in the left sidebar, but since the job names are fairly long, they get cut off, leading to a lot of guessing when finding the correct job. Shorter job names should fix this.
> [CI] Shorten job names

- stdlib/warnings.pyi
This changes the type parameter of `warnings.catch_warnings` in two ways:
- set `covariant=True` &mdash; as it's only used within output positions &mdash;  and renamed it accordingly
- have it `default` to its upper `bound` so that it isn't required anymore to pass a type-argument to a class that is not subscriptable at runtime
The invariance was causing issues within the numpy stubs for a generic a subclass:
https://github.com/numpy/numpy/blob/0aafd8553a986c7d39dde489ac5d42e53322b090/numpy/testing/_private/utils.pyi#L138-L147 to be precise
> covariant `warnings.catch_warnings` type-parameter with default

- CONTRIBUTING.md
- MAINTAINERS.md
The guidelines are unchanged, apart from linking back to the
CONTRIBUTING document and introducting section headers.
This serves multiple purposes:
* The maintainer guidelines are easier to find for maintainers.
* The CONTRIBUTING document needs fewer changes, meaning fewer
"guideline changed" warnings for contributors.
* The – already very long – CONTRIBUTING document is shorter,
and doesn't contain information irrelevant for regular contributors.
> Move maintainer guidelines to MAINTAINERS document

- stubs/decorator/@tests/stubtest_allowlist.txt
- stubs/decorator/decorator.pyi
`get_init` function was removed in version `5.0.0`
current: `5.2.*`
> Improve `decorator`

- scripts/install_all_third_party_dependencies.py
Could it be possible to add support for `uv` as a way to install third party dependencies?
`uv` seems to be most useful when installing a lot of libs.
I think it would speed up the work a lot :relaxed:  especially if you often have to change virtual environment and reinstall packages
I suggest just leaving it behind the `--uv` flag:
```bash
python3 scripts/install_all_third_party_dependencies.py --uv
```
> Support `uv` for installing third party dependencies

- stubs/JACK-Client/METADATA.toml
Disabled by @hauntsaninja last year in https://github.com/python/typeshed/pull/11821 to get daily tests passing.
The other two macOS stubtests that were disabled have been restored since then. Let's see about this one.
> Restore JACK-Client macOS stubtest

- stubs/requests/requests/sessions.pyi
This attribute doesn't exist anymore, at least as of requests 2.32.0.
Unblocks #13722
> [requests] Remove Session.redirect_cache

- lib/ts_utils/metadata.py
- pyproject.toml
- tests/mypy_test.py
[flake8-builtins (A)](https://docs.astral.sh/ruff/rules/#flake8-builtins-a)
- A001-A004 should definitely be disabled in our stubs
- A005 is already disabled in stubs.
- A006 should never happen in stubs since there shouldn't be any lambda.
- See https://github.com/astral-sh/ruff/issues/15293 for more details
At that point, it' easier and more concise to disable the entire group in stubs.
So this group would only apply to our tests/scripts.
> Enable Ruff flake8-builtins (A)

- .github/renovate.json5
This PR:
- Adds a new group with `enabled: false` that covers Python version updates such as https://github.com/python/typeshed/pull/13753. I think it's better for us to do these manually: there's often a specific reason why we can't use the latest Python version for a certain CI job, so automated PRs are just annoying.
- Switches our Renovate config to use `.json5` as the file format rather than `.json`. JSON5 is an extended version of JSON that allows you to use comments, trailing commas, and some other nice things.
Closes https://github.com/python/typeshed/pull/13753
> Disable Python version updates for `actions/setup-python` from Renovate

- lib/ts_utils/paths.py
- pyproject.toml
[flake8-use-pathlib (PTH)](https://docs.astral.sh/ruff/rules/#flake8-use-pathlib-pth)
This category has a lot of good rules regarding `pathlib`, but some rules are also basically asking for a refactoring.
So let's start easy with what's autofixable. We'll look at the other rules in a different PR.
> Enable Ruff flake8-use-pathlib (PTH) (autofix only)

- lib/ts_utils/utils.py
- pyproject.toml
- scripts/create_baseline_stubs.py
- scripts/stubsabot.py
- scripts/sync_protobuf/_utils.py
- scripts/sync_protobuf/google_protobuf.py
- scripts/sync_protobuf/s2clientprotocol.py
- scripts/sync_protobuf/tensorflow.py
- tests/mypy_test.py
- tests/pyright_test.py
- tests/regr_test.py
- tests/runtests.py
- tests/stubtest_third_party.py
- tests/typecheck_typeshed.py
Rules: [Pylint Warning (PLW)](https://docs.astral.sh/ruff/rules/#warning-plw)
Having all 4 Pylint-based groups enabled slightly simplifies the selection to `PL`
[subprocess-run-without-check (PLW1510)](https://docs.astral.sh/ruff/rules/subprocess-run-without-check/#subprocess-run-without-check-plw1510) is the rule that asks for an explicit `check=` param to `subprocess.run` (might be good to also validate whether some of those calls *should* check the result).
[redefined-loop-name (PLW2901)](https://docs.astral.sh/ruff/rules/redefined-loop-name/#redefined-loop-name-plw2901) disallows overwriting a loop variable with an assignement.
Can catch some good code smells, but what it caught here feels quite pedantic. Maybe we could …
> Enable Ruff PLW (Pylint Warning)

- lib/ts_utils/metadata.py
- lib/ts_utils/utils.py
- scripts/sync_protobuf/_utils.py
- tests/mypy_test.py
Refs #12112
Resolves some things ruff complains about when using `target-version = "py39"`.
> Drop Python 3.8 support in typeshed utilities

- stdlib/code.pyi
Fixes #13768
```pycon
>>> interact(local=MappingProxyType({"a": 5}))
Python 3.13.1 (tags/v3.13.1:0671451, Dec  3 2024, 19:06:28) [MSC v.1942 64 bit (AMD64)] on win32
(InteractiveConsole)
>>> a
TypeError: exec() globals must be a dict, not mappingproxy
```
> Make `code.InteractiveInterpreter#locals` a dict not a mapping

- stdlib/types.pyi
> remove outdated comment from `types.pyi`

- .github/renovate.json5
Cc @AlexWaygood. I'm not sure whether this will work. Another alternative is to add `ignoreDeps: ["python"]` at the top level of the config file.
> Try to disable Python in github-actions

- lib/ts_utils/utils.py
https://github.com/python/typeshed/pull/13795#discussion_r2029337823
> There is a specialized class, ``pathspec.GitIgnoreSpec``, which more closely
implements the behavior of **gitignore**. This uses ``GitWildMatchPattern``
pattern by default and handles some edge cases differently from the generic
``PathSpec`` class. ``GitIgnoreSpec`` can be used without specifying the pattern
factory::
> 
> 	>>> spec = pathspec.GitIgnoreSpec.from_lines(spec_text.splitlines())
https://github.com/python/typeshed/pull/13795#discussion_r2029346786
> Could also omit the call to `.readlines()`. `GitIgnoreSpec.from_lines` takes an iterable of lines, so passing the file i/o object directly would work. Not sure if there's any reason to prefer one way or another, though
> Small improvement of `ts_utils.get_gitignore_spec`

- stdlib/ctypes/__init__.pyi
Type-checkers currently require a generic type argument for `ctypes.py_object`. But at runtime this can raise a `TypeError` if not quoted.
We can avoid this contradictory paradox that's sending conflicting mixed signals by setting the type-parameter default of `ctypes.py_object` to `Any`.
> make the type-parameter of `ctypes.py_object` optional

- stdlib/@tests/test_cases/check_tarfile.py
- stdlib/tarfile.pyi
Per https://docs.python.org/3/library/tarfile.html#tarfile.open all of `name`, `mode`, `fileobj`, and `bufsize` are permitted to be positional.
> Fix incorrect keyword-only arguments in tarfile.open()

- stubs/mypy-extensions/mypy_extensions.pyi
See https://github.com/python/mypy_extensions/compare/1.0.0...1.1.0 on what was deprecated.
> Deprecate several things in `mypy_extensions`

- stdlib/_frozen_importlib_external.pyi
- stdlib/importlib/abc.pyi
- Documentation: https://docs.python.org/dev/library/importlib.html#importlib.machinery.WindowsRegistryFinder
- Warning in code: https://github.com/python/cpython/blob/main/Lib/importlib/_bootstrap_external.py#L719-L723
- Documentation: https://docs.python.org/dev/library/importlib.html#importlib.abc.ResourceLoader
- Warning in code: https://github.com/python/cpython/blob/main/Lib/importlib/abc.py#L74-L78
- Documentation: https://docs.python.org/dev/library/importlib.html#importlib.abc.SourceLoader.path_mtime
- Warning in code: https://github.com/python/cpython/blob/main/Lib/importlib/abc.py#L212-L214
> Deprecate `importlib` interfaces

- stubs/PyScreeze/pyscreeze/__init__.pyi
Give parameter `minSearchTime` a default value of 0 in function `pyscreeze.locateCenterOnScreen`. This should be okay because in the actual library, `locateCenterOnScreen` just delegates all of its parameters to `locateOnScreen`, and the type definition here for `locateOnScreen` gives `minSearchTime` a default value of 0.
Fixes #13851
> fix pyscreeze.locateCenterOnScreen

- stubs/auth0-python/@tests/stubtest_allowlist.txt
- stubs/auth0-python/auth0/management/async_auth0.pyi
Add async functions to AyncAuth0 class.
> [auth0-python] Add async functions to AsyncAuth0

- stdlib/_frozen_importlib_external.pyi
This has been present since before Python 3.9, I think.
> Add missing `_optimize` parameter to `importlib.machinery.SourceFileLoader` method.

- pyrightconfig.stricter.json
- stubs/grpcio/@tests/test_cases/check_status.py
- stubs/grpcio/grpc_status/rpc_status.pyi
Addresses https://github.com/python/typeshed/pull/11204#discussion_r2038374612
The test had similar comments and didn't really do anything anyway, so I just removed it (CC @shabbyrobe)
> Remove Any in `stubs/grpcio/grpc_status/rpc_status.pyi`

- lib/ts_utils/metadata.py
- lib/ts_utils/mypy.py
- lib/ts_utils/utils.py
- pyproject.toml
- tests/mypy_test.py
- tests/regr_test.py
- tests/stubtest_third_party.py
Extracted from https://github.com/python/typeshed/pull/13627
Also relates to https://github.com/python/typeshed/issues/12178 and https://github.com/python/typeshed/issues/8403
We have the infra/tooling in place for per-stub mypy configuration. But those configs didn't extend to other tests, making it unusable since stubtest would still fail.
Easier with review with whitespace changes hidden.
> Apply mypy-tests custom config to other mypy-based tests

- stdlib/tarfile.pyi
Source: https://github.com/python/cpython/pull/115257
> Deprecate `TarInfo.tarfile` attribute

- stubs/ratelimit/@tests/stubtest_allowlist.txt
- stubs/ratelimit/METADATA.toml
- stubs/ratelimit/ratelimit/__init__.pyi
- stubs/ratelimit/ratelimit/decorators.pyi
- stubs/ratelimit/ratelimit/exception.pyi
https://github.com/tomasbasham/ratelimit
As much as I'd like to contribute these to upstream, it seems very dead with a few PRs open and no responses from the author. However, the library still works.
> Add ratelimit stubs

- stubs/protobuf/METADATA.toml
- stubs/s2clientprotocol/METADATA.toml
- stubs/tensorflow/METADATA.toml
This should make it more obvious than a manual action needs to be taken (https://github.com/python/typeshed/pull/13922/files#r2072228873)
`pre-commit.ci` isn't an option to automate this as it requires internet access at runtime.
> Mention rerunning sync_protobuf scripts

- tests/pytype_test.py
Extracted from https://github.com/python/typeshed/pull/13795
Fixes #13936
Removes all usages of `os.path.sep`
Alternatively: use `os.path.normpath`. But I went the `pathlib` route.
> `pytype_test`: support either slashes in path params

- stubs/grpcio/@tests/test_cases/check_grpc.py
- stubs/grpcio/grpc/__init__.pyi
The internal typing concept `_CallIterator` is an iterator (and also an iterable).
The stub here is a bit simplified, under the hood the runtime code actually uses the fairly flexible / complex class `grpc._channel._MultiThreadedRendezvous` which kind of does a bit of everything.
Originally proposed in https://github.com/shabbyrobe/grpc-stubs/pull/53
> grpc `_CallIterator` is an iterator

- .github/workflows/tests.yml
- tests/get_external_apt_dependencies.py
Extracted from #13975
Fixes #13973
> [CI] Install apt dependencies when running "pyright: Run test cases"

- stubs/geopandas/METADATA.toml
Add "libproj-dev" and "proj-bin" to apt_dependencies.
These packages are necessary to build the
pyproj dependency
if a pre-built wheel is not available.
> [geopandas] Fix CI tests in some circumstances

- .github/workflows/tests.yml
> [CI] Install apt dependencies when running "mypy: Check stubs"

- stdlib/_typeshed/__init__.pyi
https://docs.python.org/3.14/library/functions.html#int
> Changed in version 3.14: [`int()`](https://docs.python.org/3.14/library/functions.html#int) no longer delegates to the [`__trunc__()`](https://docs.python.org/3.14/reference/datamodel.html#object.__trunc__) method.
> Python 3.14: Remove `SupportsTrunc` from `ConvertibleToInt`

- stdlib/@tests/stubtest_allowlists/py314.txt
- stdlib/uuid.pyi
- Add [uuid.uuid6()](https://docs.python.org/3.14/library/uuid.html#uuid.uuid6), [uuid.uuid7()](https://docs.python.org/3.14/library/uuid.html#uuid.uuid7), and [uuid.uuid8()](https://docs.python.org/3.14/library/uuid.html#uuid.uuid8), along with [uuid.NIL](https://docs.python.org/3.14/library/uuid.html#uuid.NIL) and [uuid.MAX](https://docs.python.org/3.14/library/uuid.html#uuid.MAX).
- Ensure we're consistently using Final across constants (https://github.com/python/typeshed/issues/12311)
- Several constants are strings known at init time, it's more appropriate to use `LiteralString` for these.
> Update `uuid` for 3.14, other minor improvements

- stubs/shapely/shapely/constructive.pyi
Fixes a regression in #13847 where some overloads were missing default values for new optional keyword arguments.
Implementation: https://github.com/shapely/shapely/blob/88309764d16846be5108a0aa236757ad97b1ba9c/shapely/constructive.py#L680-L765
> Fix annotations of shapely.constructive.make_valid

- CONTRIBUTING.md
- lib/ts_utils/metadata.py
- lib/ts_utils/mypy.py
- tests/README.md
- tests/check_typeshed_structure.py
- tests/stubtest_third_party.py
Add mypy plugin support for stubtest
This PR adds support for mypy plugins in stubtest configuration, allowing packages that depend on plugins (like Django) to be properly validated. Implements `mypy_plugins` and `mypy_plugins_config` fields in METADATA.toml.
Fixes #13935
> Add mypy plugin support to stubtest configuration

- stdlib/@tests/stubtest_allowlists/py314.txt
- stdlib/@tests/test_cases/check_dataclasses.py
- stdlib/dataclasses.pyi
Make dataclass updates for 3.14, supporting `doc` on `dataclasses.Field` and `decorator` on `make_dataclass`.
> Update dataclasses for 3.14

- stdlib/@tests/stubtest_allowlists/py314.txt
- stdlib/@tests/test_cases/check_concurrent_futures.py
- stdlib/VERSIONS
- stdlib/concurrent/futures/__init__.pyi
- stdlib/concurrent/futures/interpreter.pyi
- stdlib/concurrent/futures/thread.pyi
This PR adds the new `InterpreterPoolExecutor` along with other `concurrent.futures` updates for 3.14.
Some decisions with this PR to make:
- Whether to simplify the `ExecutionFailed` typing. At runtime a `types.SimpleNamespace` is  passed in but we know that it has specific attributes, to type this I used `type_check_only` protocols. I think we could do one of the following:
- Keep thing as is.
- Update `_interpreters` to use these protocols instead of `types.SimpleNamespace` potentially.
- Simply accept `types.SimpleNamespace`.
- Complexity of the task types. I put some effort in to make the task types as accurate as possible, while realizing the usefulness of such specific types is likely limited. I'm happy to simplify these.
> Add `InterpreterPoolExecutor` (3.14)

- lib/ts_utils/metadata.py
- tests/runtests.py
Addresses the `runtests.py` part of https://github.com/python/typeshed/issues/14025
I tested by running:
`uv run .\tests\runtests.py --run-stubtest .\stubs\networkx\` (should default to 3.10)
`uv run .\tests\runtests.py --run-stubtest .\stubs\networkx\ --python-version=3.9` (should fail some tests)
`uv run .\tests\runtests.py --run-stubtest .\stubs\networkx\ --python-version=3.11` (should work on 3.11)
`uv run .\tests\runtests.py --run-stubtest .\stubs\setuptools\` (should default to 3.9)
`uv run .\tests\runtests.py --run-stubtest .\stubs\setuptools\ --python-version=3.11` (should work on 3.11)
`uv run .\tests\runtests.py --run-stubtest .\stdlib\typing.pyi` (should default to 3.9)
This also deduplicates a Python version in code
> Support `requires_python` in `runtests.py`

- stdlib/tkinter/__init__.pyi
A `tkinter.Event` represents something happening in a widget. The event's `widget` field is basically the widget that caused it. The somewhat misleadingly named `Misc` class means "any widget".
When writing an event handler function, you can specify the type of `event.widget` by using e.g. `event: tkinter.Event[tkinter.Label]`. Before this PR, it is required with strict type checker settings, and you get `Any` if you don't use it. With this PR, it is assumed to be `Misc`. This is suitable for event handlers that don't use the `.widget` field.
For example:
```python
import tkinter
def handle_event(event: tkinter.Event) -> None:
reveal_type(event.widget)
```
Mypy output before:
```
a.py:3: error: Missing type parameters for generic type "Event"  [type-arg]
a.py:4: note: Revealed type is …
```
> Make `tkinter.Event` equivalent to `tkinter.Event[tkinter.Misc]`

- stubs/networkx/networkx/drawing/nx_pylab.pyi
As per the documentation https://networkx.org/documentation/latest/reference/generated/networkx.drawing.nx_pylab.draw_networkx_nodes.html#draw-networkx-nodes and program behavior.
Fun fact: I'm actually using version 2 of this library, 2 majors behind, and it accepts list[str] as well there as well!
> Update nx_pylab.pyi: allow node_color to be a list of strings as well

- stdlib/@tests/stubtest_allowlists/py314.txt
- stdlib/builtins.pyi
Now that we have clinic generated code for `ExceptionGroup`/`BaseExceptionGroup` we enforce naming for positional arguments.
> Update exception group to match clinic generated arguments

- stdlib/builtins.pyi
Remove two differences from types.FunctionType that should be
safe to clean up.
https://discuss.python.org/t/removing-type-checker-internals-from-typeshed/87960/101
> builtins: improve builtins.function

- stubs/docutils/docutils/core.pyi
Required to avoid adding new ignores to Sphinx with the latest types-docutils. See https://github.com/sphinx-doc/sphinx/pull/13564.
Copied form @donBarbos's WIP at https://github.com/python/typeshed/pull/14107.
> Expand docutils.core.Publisher.get_settings types

- stdlib/socketserver.pyi
Adds support for IPv6 addresses to `TCPServer`, related to #10671
> Add hint for IPv6 addresses to TCPServer

- stubs/grpcio/grpc/__init__.pyi
Relevant part in `grpc/__init__.py`: https://github.com/grpc/grpc/blob/cadf3c8329377e93b1f5e2d6a43d91f7a4becc28/src/python/grpcio/grpc/__init__.py#L2344-L2348
It runs `from grpc import aio` inside `__init__.py` if the Python version is 3.6 or later. I bumped into this because after upgrading to Pyright 1.1.401, `grpc.aio` type checking & definition finding regressed.
> Update `grpcio` stub to import `grpc.aio`

- stdlib/ast.pyi
These are the only types that Python's parser will produce.
Fixes #14156. See also https://github.com/python/cpython/pull/134741.
> ast: Precise type for ast.Constant.value

- stdlib/builtins.pyi
This was used to prevent an import cycle that exists
anyway nowadays via `_typeshed`.
> Remove old cycle-prevention workaround

- stubs/grpcio/grpc/__init__.pyi
- stubs/grpcio/grpc/aio/__init__.pyi
Serializers/deserializers should be tied to the request/response type parameter of the containing scope, e.g. so that the `xyz_rpc_method_handler()` functions can return a properly typed `RpcMethodHandler[_TRequest, _TResponse]` based on the types of the serializers/deserializers.
> Improve grpcio serializer/deserializer types

- CONTRIBUTING.md
The label links in CONTRIBUTING.md take you to a search page with a broken label filter. For example:
[`https://github.com/python/typeshed/labels/stubs%3A%20removal`](https://github.com/python/typeshed/labels/stubs%3A%20removal)
It seems that GitHub is having issues with there being a space in the label name. What's weird is that this is the  exact URL that GitHub expects for rendered labels, e.g. https://github.com/python/typeshed/labels/stubs%3A%20removal.
Putting some quotes around the label name seems to make the links work. For example:
[`https://github.com/python/typeshed/labels/%22stubs%3A%20removal%22`](https://github.com/python/typeshed/labels/%22stubs%3A%20removal%22)
> Fix label links in CONTRIBUTING.md

- stdlib/@tests/test_cases/check_concurrent_futures.py
- stdlib/concurrent/futures/thread.pyi
https://github.com/python/cpython/pull/124548
> Update ThreadPoolExecutor attributes for Python 3.14

- stubs/dateparser/METADATA.toml
- stubs/dateparser/dateparser/search/search.pyi
- stubs/dateparser/dateparser/timezone_parser.pyi
Closes #14345
For reference: https://github.com/scrapinghub/dateparser/compare/v1.2.1...v1.2.2
> [dateparser] Update to `~=1.2.2`

- stubs/networkx/networkx/algorithms/minors/contraction.pyi
Annotation is largely in accordance with the documentation:
https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.minors.equivalence_classes.html
The only difference is that `iterable` is of type `Iterable` rather than `set|list|tuple`.
While the documentation does specify that it has to be one of those types, the code only uses the argument to iterate over it once.
> [networkx] completed type annotation for `equivalence_classes`

- stdlib/_csv.pyi
```python
import csv
with open("example.csv", "w", newline='') as csvfile:
csv.writer(csvfile=csvfile)  # TypeError:  expected at least 1 argument, got 0
```
```python
import csv
csv.reader(csvfile="a")  # TypeError:  expected at least 1 argument, got 0
```
> csv: csv.reader and csv.writer - mark csvfile as positional only

- .flake8
F821 is only checked as a test for the F821 monkeypatch functionality in flake8-pyi, but that will be removed.
Cf. PyCQA/flake8-pyi#522. Needed to unblock renovate updates, see #14357.
> Remove flake8 F821 checks for stubs

- stdlib/ast.pyi
Update return type annotations in ast.parse overloads to use 'mod' instead of 'AST' and introduce new overloads for improved type hinting.
> Fix return type annotations and add overloads for ast.parse

- stdlib/compression/zstd/_zstdfile.pyi
In #14129 I made an error in definition of some protocols: inheriting from a class defining a protocol is not enough, they should inherit from `Protocol` as well.
> Fix Protocol inheritance in _zstdfile

- stubs/aiofiles/aiofiles/tempfile/__init__.pyi
When using `aiofiles.tempfile.TemporaryDirectory` with `AsyncExitStack` as shown below:
```python
import asyncio
from contextlib import AsyncExitStack
from typing import reveal_type
from aiofiles.tempfile import TemporaryDirectory
async def main() -> None:
stack = AsyncExitStack()
d = await stack.enter_async_context(TemporaryDirectory())
reveal_type(d)
await stack.aclose()
if __name__ == '__main__':
asyncio.run(main())
```
Mypy reports `Revealed type is "aiofiles.tempfile.temptypes.AsyncTemporaryDirectory"`, but running the code shows: `Runtime type is 'str'`.
This PR fixes this mismatch.
> Fix AiofilesContextManagerTempDir type argument

- stdlib/ctypes/__init__.pyi
This is a follow-up to the version bridge for Python 3.14 added in https://github.com/python/typeshed/pull/14137 and my own contribution to cpython (https://github.com/python/cpython/pull/127275).
See also: https://docs.python.org/3.14/library/ctypes.html#ctypes.CopyComPointer
> Add `CopyComPointer` to `stdlib/ctypes/__init__.pyi`.

- CONTRIBUTING.md
Use the `py` launcher and don't use the `pip` shortcut for upgrading pip itself. The latter is a required change since `pip install -U pip` is blocked by `pip` because it can't function correctly (`pip` can't replace the `pip.exe` wrapper while it is running). The former is more of a style change to get inline with the common suggestions for windows users to not have global `python` executables visible.
> Update windows install instructions for windows

- stubs/docutils/docutils/core.pyi
Source: https://github.com/python/typeshed/pull/14107#discussion_r2193181563
thanks @felixfontein
> [docutils] Fix issue with `*_path` params

- stubs/PyMySQL/@tests/stubtest_allowlist.txt
- stubs/PyMySQL/pymysql/__init__.pyi
> [PyMySQL] Fix issue with import constants attributes

- stdlib/ast.pyi
This is the only annotation in typeshed that uses `Literal[True, False]`. The most similar annotations are `Literal[True, 1]`. 371 annotations are `bool | None`.
> Change ast.MatchSingleton.value from `Literal[True, False]` to `bool`

- pyrightconfig.stricter.json
Fixes https://github.com/AlexWaygood/typeshed-stats/issues/351
> Use stricter pyright settings when testing `channels`

- lib/ts_utils/paths.py
- scripts/create_baseline_stubs.py
- scripts/stubsabot.py
> [stubsabot] Support "Removal" PRs

- stubs/psycopg2/psycopg2/extras.pyi
To address that `RealDictCursor` is now failing as untyped under mypy strict mode
See https://github.com/python/typeshed/issues/14417 for deeper explanation and examples
> psycopg2: Add types to RealDictCursor.execute

- stdlib/difflib.pyi
Source: https://github.com/python/cpython/pull/130170
> [difflib] Update `pat` param for `IS_LINE_JUNK`

- stdlib/_operator.pyi
- stdlib/argparse.pyi
- stdlib/builtins.pyi
- stdlib/cgi.pyi
- stdlib/compileall.pyi
- stdlib/contextlib.pyi
- stdlib/copy.pyi
- stdlib/fileinput.pyi
- stdlib/fractions.pyi
- stdlib/gettext.pyi
- stdlib/gzip.pyi
- stdlib/imghdr.pyi
- stdlib/inspect.pyi
- stdlib/math.pyi
- stdlib/socket.pyi
None of these protocols are available at runtime. Even though they're priviate, some tools may benefit from them being explicitly marked as `@type_check_only`.
> Add `@type_check_only` to various typeshed-only procotols in stdlib

- stdlib/turtle.pyi
While it would be possible to use the hack described in the comment
now that pytype support has been removed, that hack is a bit too
"magical" for stubs that are supposed to be fairly straight-forward
API descriptions. This would also introduce extra stub-only attributes
and would imply that e.g. `_Screen.setup()` and `setup()` refer to the
same object at runtime when they don't.
> Remove obsolete comments from turtle.pyi

- scripts/stubsabot.py
Use colors for output and move processed distribution name to the front
Helps with #14466
> stubsabot: Handle errors when determining action

- stubs/yt-dlp/yt_dlp/networking/common.pyi
The fact that this parameter wasn't annotated was tripping up an internal assertion in typeshed-stats: typeshed-stats thought that pyright shoudl probably be complaining about this stubs package, because we have the strictest pyright settings enabled for this project in CI but there are still unannotated parameters in the package. Possibly I should adjust the logic in typeshed-stats so that the assertion doesn't trigger if the parameter name is `_`, but it also seems preferable to fully annotate stubs packages where possible. In this case it seems fairly clear that any additional keyword arguments passed to `__init__` are just discarded: https://github.com/yt-dlp/yt-dlp/blob/23c658b9cbe34a151f8f921ab1320bb5d4e40a4d/yt_dlp/networking/common.py#L223-L250
Fixes …
> Fully annotate `yt-dlp`

- lib/ts_utils/metadata.py
- lib/ts_utils/mypy.py
- requirements-tests.txt
- scripts/stubsabot.py
Hi,
From Pyhon3.11, `tomli` was merged into the Python standard library as `tomllib`
https://wiki.debian.org/Python/Backports
> prefer newer "tomllib" over "tomli" backport

- stdlib/platform.pyi
Source: https://github.com/python/cpython/pull/116471
Docs: https://docs.python.org/3.14/library/platform.html
> [platform] Deprecate `java_ver`

- tests/stubtest_third_party.py
I just had a fatal error testing latest mypy master. I need the traceback to properly report a bug. I figured always showing the traceback in case of fatal error may be beneficial.
This is already the case for `stubtest_stdlib`.
I see no documented adverse effect: https://mypy.readthedocs.io/en/stable/config_file.html#confval-show_traceback
> Add --show-traceback to stubtest_third_party

- stubs/pysftp/METADATA.toml
> [pysftp] Pin `paramiko~=3.0` when running stubtest

- stdlib/@tests/stubtest_allowlists/py314.txt
- stdlib/@tests/test_cases/check_concurrent_futures.py
- stdlib/_interpreters.pyi
- stdlib/concurrent/futures/interpreter.pyi
Source: https://github.com/python/cpython/pull/133957
* Add `do_call` function
* Add `interp`, `results` attributes to `WorkerContext`
* Remove `ExecutionFailed`
* Remove `shared` argument from methods
> [concurrent.futures.interpreter] Update to 3.14.0b4

- stdlib/array.pyi
Docs: https://docs.python.org/dev/library/array.html
Source: https://github.com/python/cpython/issues/80480
> [array] Add `w` typecode and deprecate `u` typecode

- scripts/stubsabot.py
Currently, stubsabot only does diff analysis for GitHub hosted projects. Typeshed has a few third-party stubs whose upstream projects are hosted on GitLab. It would be nice if stubsabot could do diff analysis for those too (having a "diff" URL in the PR body is especially handy).
Apparently GitLab has a REST API that works pretty similarly to GitHub's. It also doesn't appear to require an access token (at least for the `/projects/:id` endpoint, which is all this would need to use). I took a stab at updating stubsabot to use this API in a way that mirrors the current GitHub API use. It turned out to be pretty straightforward. This makes stubsabot do roughly the same diff analysis for GitLab projects that it does for GitHub projects, including adding a convenient diff URL to the PR body.
I …
> [stubsabot] Support diff analysis for GitLab hosted projects

- stdlib/glob.pyi
Source: https://github.com/python/cpython/pull/117371
Warning was added to runtime in 3.13. And I added a check for 3.10 since the *root_dir* argument appeared only in this version.
> [glob] Deprecate `glob0` and `glob1` functions

- stubs/django-filter/django_filters/filterset.pyi
for FilterSetOptions and filterset_factory
fixes #14565
> [django-filter] Replace list with more generic Sequence

- stubs/lupa/lupa/lua51.pyi
- stubs/lupa/lupa/lua52.pyi
- stubs/lupa/lupa/lua53.pyi
- stubs/lupa/lupa/lua54.pyi
Support get/set/del from Lua tables.
Lua table values are all Any because we can't typecheck across language boundaries.
Support unpack_returned_tuples in the LuaRuntime constructor.
> Lupa stubs:

- stubs/cachetools/METADATA.toml
- stubs/cachetools/cachetools/__init__.pyi
Closes #14642
Diff: https://github.com/tkem/cachetools/compare/v6.1.0...v6.2.0
> [cachetools] Update to 6.2.*

- stubs/networkx/networkx/algorithms/approximation/connectivity.pyi
- stubs/networkx/networkx/algorithms/connectivity/connectivity.pyi
Adds type hints to previously incomplete items in `algorithms/connectivity/connectivity.pyi`. Changes were done referencing https://networkx.org/documentation/stable/_modules/networkx/algorithms/connectivity/connectivity.html
> networkx: Fix incompletes in connectivity/connectivity

- stubs/yt-dlp/METADATA.toml
- stubs/yt-dlp/yt_dlp/__init__.pyi
> [yt-dlp] Update to 2025.9.5

- stdlib/@tests/stubtest_allowlists/common.txt
- stdlib/builtins.pyi
Should be safe now that we've updated pyright.
> Add @disjoint_base to builtins.tuple

- stdlib/asyncio/events.pyi
- stdlib/builtins.pyi
Subtest no longer complains when these types are marked `@type_check_only` since python/mypy#19568
> Mark stub-only types with runtime aliases as `@type_check_only` in stdlib

- stubs/PyYAML/yaml/_yaml.pyi
- stubs/cffi/_cffi_backend.pyi
- stubs/gdb/gdb/__init__.pyi
- stubs/gdb/gdb/disassembler.pyi
- stubs/gevent/@tests/stubtest_allowlist.txt
- stubs/gevent/gevent/_greenlet_primitives.pyi
- stubs/gevent/gevent/_hub_primitives.pyi
- stubs/gevent/gevent/_imap.pyi
- stubs/gevent/gevent/greenlet.pyi
- stubs/gevent/gevent/libev/corecext.pyi
- stubs/gevent/gevent/resolver/cares.pyi
- stubs/greenlet/greenlet/_greenlet.pyi
- stubs/hdbcli/hdbcli/dbapi.pyi
- stubs/hdbcli/hdbcli/resultrow.pyi
- stubs/lupa/lupa/lua51.pyi
- stubs/lupa/lupa/lua52.pyi
- stubs/lupa/lupa/lua53.pyi
- stubs/lupa/lupa/lua54.pyi
- stubs/lupa/lupa/luajit20.pyi
- stubs/lupa/lupa/luajit21.pyi
- stubs/mysqlclient/MySQLdb/_mysql.pyi
- stubs/psycopg2/psycopg2/_psycopg.pyi
- stubs/pywin32/_win32typing.pyi
- stubs/pywin32/pythoncom.pyi
- stubs/pywin32/win32/lib/pywintypes.pyi
- stubs/shapely/shapely/lib.pyi
- tests/stubtest_third_party.py
Follow up to #14699
Based on the stubtest errors -- I haven't looked at the source.
Mostly mechanical additions of `@disjoint_base`, but see separate commits for special cases in `gevent` and `pywintypes`.
> Add `@disjoint_base` decorator to the third-party stubs

- .github/workflows/daily.yml
We currently run the daily tests for PRs that touch `requirements-tests.txt`, but only in the  main `python/typeshed` repo. This makes these tests also run when opening PRs in forks. This is useful for e.g. experimenting with different mypy versions in the CI.
> [CI] Run daily tests on pull requests in forks

- stubs/docutils/@tests/stubtest_allowlist.txt
- stubs/docutils/docutils/nodes.pyi
- stubs/docutils/docutils/transforms/universal.pyi
Since these type aliases were taken from source codes, it would be a good idea to report this to `docutils` core team
> [docutils] Extend applicable types to _ContentModelCategory

- stdlib/@tests/stubtest_allowlists/common.txt
- stdlib/@tests/stubtest_allowlists/py310.txt
- stdlib/@tests/stubtest_allowlists/py311.txt
- stdlib/@tests/stubtest_allowlists/py312.txt
- stdlib/@tests/stubtest_allowlists/py313.txt
- stdlib/@tests/stubtest_allowlists/py39.txt
- stdlib/_collections_abc.pyi
- stdlib/typing.pyi
This reverts commit 8a7f09e3511f3a1d04281c60167b8dcc3b78938b.
`ByteString` was added back to Python 3.14 at the last minute, since several users reported that the deprecation warnings had not been prominent enough prior to its removal. It is still scheduled to be removed, but its removal has been postponed to 3.17.
Helps with https://github.com/python/typeshed/issues/14741
> Revert "Byestring removal for 3.14 (#12490)"

- stubs/gdb/gdb/__init__.pyi
Even though the parent thread for `ThreadExitedEvent` won't change from `Event` to `ThreadEvent` until 17.0 is released, this actually makes type checking work better in practice for all released versions that support `ThreadExitedEvent` because at run time `ThreadExitedEvent` has the lone attribute, `inferior_thread`, that it would have inherited from `ThreadEvent`.
Fixes #14729 
Upstream GDB issue:
* https://sourceware.org/bugzilla/show_bug.cgi?id=33444
> [gdb] Update ThreadExitedEvent parent class for 17.0 (#14729)

- pyrightconfig.stricter.json
It's fully annotated following https://github.com/python/typeshed/pull/14695.
Fixes https://github.com/AlexWaygood/typeshed-stats/issues/365, fixes https://github.com/AlexWaygood/typeshed-stats/issues/366, fixes https://github.com/AlexWaygood/typeshed-stats/issues/367, fixes https://github.com/AlexWaygood/typeshed-stats/issues/368
> Use stricter pyright settings for `xmltodict`

- stubs/grpcio/@tests/test_cases/check_aio.py
- stubs/grpcio/@tests/test_cases/check_handler_inheritance.py
- stubs/grpcio/@tests/test_cases/check_server_interceptor.py
- stubs/grpcio/grpc/__init__.pyi
- stubs/grpcio/grpc/aio/__init__.pyi
`ServerInterceptor` and `GenericRpcHandler` should not be generic over request/response themselves, but rather should have generic methods:
* `ServerInterceptor`: a given instance of this should be able to intercept any call, and so should have a generic method over all request/continuation types rather than the instance being specialized itself
* `GenericRpcHandler` (and `ServiceRpcHandler`): this is "An implementation of arbitrarily many RPC methods" and has a `service` method that takes a parameter describing the method to handle, but that parameter dictates the request/response types. The instance of the `GenericRpcHandler` itself does not know about the request/response types. In theory this could be described using dependent types, but since this is Python the best we can do is have …
> grpcio: improve server interceptor typing

- stubs/Jetson.GPIO/METADATA.toml
fixes https://github.com/python/typeshed/issues/14810
> Pin `Jetson.GPIO` to 2.1.11

- stdlib/typing_extensions.pyi
The default / implicit value for `TypedDict.__closed__` is `None`.
That's how it's implemented in both typing_extensions and https://github.com/python/cpython/pull/137933.
/CC @JelleZijlstra
> Fix PEP 728 TypedDict.__closed__ annotation in typing_extensions

- stdlib/typing.pyi
The `type_params` attribute of `TypeAliasType` should accept instances of `typing_extensions.TypeVar`, as well as of `typing.TypeVar` (on those Python versions in which these are different classes.) Same goes for `ParamSpec` and `TypeVarTuple`.
> TypeAliasType type_params accepts typing_extensions.TypeVar also

- stubs/jsonschema/jsonschema/exceptions.pyi
The __init__() argument is defined as Sequence[ValidationError], and self.context is a list initialized from said argument.
See also the code, which does not allow passing `None` for `context`:
* https://github.com/python-jsonschema/jsonschema/blob/980a0c1fd95ed2e50b73161a8f7c8dd44169deca/jsonschema/exceptions.py#L61
* https://github.com/python-jsonschema/jsonschema/blob/980a0c1fd95ed2e50b73161a8f7c8dd44169deca/jsonschema/exceptions.py#L84
* https://github.com/python-jsonschema/jsonschema/blob/980a0c1fd95ed2e50b73161a8f7c8dd44169deca/jsonschema/exceptions.py#L93
> chore(jsonschema): exceptions._Error.context cannot be None

- stubs/yt-dlp/@tests/stubtest_allowlist.txt
- stubs/yt-dlp/yt_dlp/extractor/common.pyi
- stubs/yt-dlp/yt_dlp/extractor/commonmistakes.pyi
- stubs/yt-dlp/yt_dlp/extractor/commonprotocols.pyi
Typeshed doesn't include stubs for the individual extractor modules, but we do stub a few modules with common code. This makes stubtest run for those modules and fixes few inconsistencies that have accumulated.
> [yt-dlp] Check common code in extractor subpackage with stubtest

- stubs/Jetson.GPIO/@tests/stubtest_allowlist.txt
- stubs/Jetson.GPIO/Jetson/GPIO/constants.pyi
- stubs/Jetson.GPIO/Jetson/GPIO/gpio.pyi
- stubs/Jetson.GPIO/Jetson/GPIO/gpio_cdev.pyi
- stubs/Jetson.GPIO/Jetson/GPIO/gpio_pin_data.pyi
- stubs/Jetson.GPIO/Jetson/GPIO/gpio_pinmux_lookup.pyi
- stubs/Jetson.GPIO/METADATA.toml
> [Jetson.GPIO] Update to 2.1.12
